### ISSUE TITLE
[BUG] Usage of valloc

### ISSUE THREAD

**Issue by neheb** [zerotier/ZeroTierOne#1000]
valloc is a deprecated function that is replaced by posix_memalign in future standards. It is used here: https://github.com/zerotier/ZeroTierOne/blob/master/osdep/LinuxNetLink.cpp#L106

Does not allow compilation under certain uClibc-ng configurations, as seen here: https://downloads.openwrt.org/snapshots/faillogs/arc_arc700/packages/zerotier/compile.txt

**Comment by adamierymenko** [comment]
Fixing in `dev`
