### ISSUE TITLE
ZeroTier sometimes cannot connect with roaming client

### ISSUE THREAD

**Issue by mrschyte** [zerotier/ZeroTierOne#1002]
**Describe the bug**
I'm using ZeroTier on a laptop, which I connect to different Wi-Fi networks with. After a while ZeroTier fails to bring up the VPN connection. The "zerotier-cli listpeers" command lists peers as connected, but no traffic is flowing through. Stopping the service and deleting /var/lib/zerotier-one/peers.d/* and then restarting it solves the problem.

I've observed the same behavior with v1.2.12 and v1.4.0.

**Expected behavior**
ZeroTier should connect to the VPN network or show that some peers are unreachable.

**Comment by joseph-henry** [comment]
Are you still experiencing this issue?

**Comment by mrschyte** [comment]
I couldn't reproduce this with the latest version (v1.4.6). The new version connects much faster when switching networks. I'm closing the issue. Thank you.
