### ISSUE TITLE
ZeroTier Limited to 16 addresses per member?

### ISSUE THREAD

**Issue by nwsnate** [zerotier/ZeroTierOne#1004]
I am unsure of if this is a bug or an improper configuration on my part, but I have a single zerotier member that I would like to allocate multiple IP addresses to. I have used the controller API to add each address to the member, and restarted the zerotier-one service on my debian member. I see that it got the first 16 addresses in that block, but not any after that.

Is this a limitation of the software itself or an improper configuration on my end?

**Server:**
 - OS: [Debian 10]
 - OS/Distribution Version: Debian GNU/Linux 10 (buster)
 - ZeroTier Version 1.4.0

Things seem to be showing up correctly with a GET request to /controller/network/NETWORKID/member/MEMBERID/

'ipAssignments': ['172.16.2.1', '172.16.2.2', '172.16.2.3', '172.16.2.4', '172.16.2.5', '172.16.2.6', '172.16.2.7', '172.16.2.8', '172.16.2.9', '172.16.2.10', '172.16.2.11', '172.16.2.12', '172.16.2.13', '172.16.2.14', '172.16.2.15', '172.16.2.16', '172.16.2.17', '172.16.2.18', '172.16.2.19', '172.16.2.20', '172.16.2.21', '172.16.2.22', '172.16.2.23', '172.16.2.24', '172.16.2.25', '172.16.2.26', '172.16.2.27', '172.16.2.28', '172.16.2.29', '172.16.2.30', '172.16.2.31', '172.16.2.32', '172.16.2.33', '172.16.2.34', '172.16.2.35', '172.16.2.36', '172.16.2.37', '172.16.2.38', '172.16.2.39', '172.16.2.40', '172.16.2.41', '172.16.2.42', '172.16.2.43', '172.16.2.44', '172.16.2.45', '172.16.2.46', '172.16.2.47', '172.16.2.48', '172.16.2.49', '172.16.2.50', '172.16.2.51', '172.16.2.52', '172.16.2.53', '172.16.2.54', '172.16.2.55', '172.16.2.56', '172.16.2.57', '172.16.2.58', '172.16.2.59', '172.16.2.60', '172.16.2.61', '172.16.2.62', '172.16.2.63', '172.16.2.64', '172.16.2.65', '172.16.2.66', '172.16.2.67', '172.16.2.68', '172.16.2.69', '172.16.2.70', '172.16.2.71', '172.16.2.72', '172.16.2.73', '172.16.2.74', '172.16.2.75', '172.16.2.76', '172.16.2.77', '172.16.2.78', '172.16.2.79', '172.16.2.80', '172.16.2.81', '172.16.2.82', '172.16.2.83', '172.16.2.84', '172.16.2.85', '172.16.2.86', '172.16.2.87', '172.16.2.88', '172.16.2.89', '172.16.2.90', '172.16.2.91', '172.16.2.92', '172.16.2.93', '172.16.2.94', '172.16.2.95', '172.16.2.96', '172.16.2.97', '172.16.2.98', '172.16.2.99', '172.16.2.100', '172.16.2.101', '172.16.2.102', '172.16.2.103', '172.16.2.104', '172.16.2.105', '172.16.2.106', '172.16.2.107', '172.16.2.108', '172.16.2.109', '172.16.2.110', '172.16.2.111', '172.16.2.112', '172.16.2.113', '172.16.2.114', '172.16.2.115', '172.16.2.116', '172.16.2.117', '172.16.2.118', '172.16.2.119', '172.16.2.120', '172.16.2.121', '172.16.2.122', '172.16.2.123', '172.16.2.124', '172.16.2.125', '172.16.2.126', '172.16.2.127', '172.16.2.128', '172.16.2.129', '172.16.2.130', '172.16.2.131', '172.16.2.132', '172.16.2.133', '172.16.2.134', '172.16.2.135', '172.16.2.136', '172.16.2.137', '172.16.2.138', '172.16.2.139', '172.16.2.140', '172.16.2.141', '172.16.2.142', '172.16.2.143', '172.16.2.144', '172.16.2.145', '172.16.2.146', '172.16.2.147', '172.16.2.148', '172.16.2.149', '172.16.2.150', '172.16.2.151', '172.16.2.152', '172.16.2.153', '172.16.2.154', '172.16.2.155', '172.16.2.156', '172.16.2.157', '172.16.2.158', '172.16.2.159', '172.16.2.160', '172.16.2.161', '172.16.2.162', '172.16.2.163', '172.16.2.164', '172.16.2.165', '172.16.2.166', '172.16.2.167', '172.16.2.168', '172.16.2.169', '172.16.2.170', '172.16.2.171', '172.16.2.172', '172.16.2.173', '172.16.2.174', '172.16.2.175', '172.16.2.176', '172.16.2.177', '172.16.2.178', '172.16.2.179', '172.16.2.180', '172.16.2.181', '172.16.2.182', '172.16.2.183', '172.16.2.184', '172.16.2.185', '172.16.2.186', '172.16.2.187', '172.16.2.188', '172.16.2.189', '172.16.2.190', '172.16.2.191', '172.16.2.192', '172.16.2.193', '172.16.2.194', '172.16.2.195', '172.16.2.196', '172.16.2.197', '172.16.2.198', '172.16.2.199', '172.16.2.200', '172.16.2.201', '172.16.2.202', '172.16.2.203', '172.16.2.204', '172.16.2.205', '172.16.2.206', '172.16.2.207', '172.16.2.208', '172.16.2.209', '172.16.2.210', '172.16.2.211', '172.16.2.212', '172.16.2.213', '172.16.2.214', '172.16.2.215', '172.16.2.216', '172.16.2.217', '172.16.2.218', '172.16.2.219', '172.16.2.220', '172.16.2.221', '172.16.2.222', '172.16.2.223', '172.16.2.224', '172.16.2.225', '172.16.2.226', '172.16.2.227', '172.16.2.228', '172.16.2.229', '172.16.2.230', '172.16.2.231', '172.16.2.232', '172.16.2.233', '172.16.2.234', '172.16.2.235', '172.16.2.236', '172.16.2.237', '172.16.2.238', '172.16.2.239', '172.16.2.240', '172.16.2.241', '172.16.2.242', '172.16.2.243', '172.16.2.244', '172.16.2.245', '172.16.2.246', '172.16.2.247', '172.16.2.248', '172.16.2.249', '172.16.2.250', '172.16.2.251', '172.16.2.252', '172.16.2.253', '172.16.2.254',

**Comment by glimberg** [comment]
per ZeroTierOne.h
```
/**
 * Maximum number of statically assigned IP addresses per network endpoint using ZT address management (not DHCP)
 */
#define ZT_MAX_ZT_ASSIGNED_ADDRESSES 16
```

So yes, the limit is 16.   I do have to ask about assigning a full /24 to a single node: ![But why?](http://giphygifs.s3.amazonaws.com/media/1M9fmo1WAFVK0/giphy.gif)

**Comment by glimberg** [comment]
Rather than assigning a full /24 to a node, you could probably assign a managed route instead.

**Comment by nwsnate** [comment]
Thank you, I'll look into managed routes. I haven't gone too in depth yet so this was the only way I knew existed. Thanks again!
