### ISSUE TITLE
Cant config central address in linux

### ISSUE THREAD

**Issue by Tokisaki** [zerotier/ZeroTierOne#1009]
**Is your feature request related to a problem? Please describe.**
After I installed the zerotier on my openwrt,I cant config the central address to my own controller

**Describe the solution you'd like**
Are we have config for central address?

**Describe alternatives you've considered**

**Additional context**

**Comment by glimberg** [comment]
ZeroTier Central is a closed source hosted controller service that we offer.  It does not interface with self-hosted controllers.  

Documentation of the REST API for self hosted controllers is available here:  https://github.com/zerotier/ZeroTierOne/tree/master/controller
