### ISSUE TITLE
Windows server authentication token problem

### ISSUE THREAD

**Issue by SparkizX** [zerotier/ZeroTierOne#1011]
So this is not a bug.
But it is no where to be found. I'm using windows server 2019 insider core, so no desktop. How do I create authentication token for server user that doesn't have admin privileges?

I tried searching but nowhere to be found.
I have access to powershell and command prompt only.

**Comment by adamierymenko** [comment]
You need to make a local user copy of the file in `\ProgramData\ZeroTier\One\authtoken.secret`.
