### ISSUE TITLE
zerotier-containerized build doesn't work with Zerotier version 1.4.2 

### ISSUE THREAD

**Issue by Spikhalskiy** [zerotier/ZeroTierOne#1013]
If update the version of Zerotier in the current containerized build we will get a container where Zerotier can't be correctly started.

**To Reproduce**

1. Go to https://github.com/zerotier/ZeroTierOne/blob/1.4.2/ext/installfiles/linux/zerotier-containerized/Dockerfile and change "RUN apt-get update && apt-get install -y zerotier-one=1.2.12" -> "RUN apt-get update && apt-get install -y zerotier-one=1.4.2-2"
2. Build docker: docker build . -t zerotier/zerotier-containerized:1.4.2
3. Run docker: docker run -it --cap-add=NET_ADMIN --device=/dev/net/tun zerotier/zerotier-containerized:1.4.2 /bin/sh
4. Run inside the docker: 
```
zerotier-cli
/bin/sh: zerotier-cli: not found
```
^ expected to work
```
apk add --update binutils
```
```
readelf -l /usr/sbin/zerotier-cli |grep "program interpreter"
      [Requesting program interpreter: /lib64/ld-linux-x86-64.so.2]
```
^ which is unavailable

**Expected behavior**

Expect to get a docker that works the same way as it currently works with 1.2.12

**Proposed solution**
My quick fix can be useful: https://github.com/Spikhalskiy/ZeroTierOne/commit/b61b3da59fe24bb96c1c0b09e28deac5814306a7

**Comment by adamierymenko** [comment]
Hmmmm... may have to change the base distro for the container to one with a less ancient compiler. :P

**Comment by Spikhalskiy** [comment]
@adamierymenko It's not because of the compiler, it's mostly about alpine using musl instead of libc. musl is under an active development actually :) But yeah, the solution could be 1) change the base distro 2) install glibc compatibility package like I do 3) link zerotier against musl also in addition to glibc and make one more binary release.

**Comment by adamierymenko** [comment]
We use musl for static builds when we can't build easily in the target distro due to ancient C/C++ compilers. We need C++11 support and generally compilers released after the time of the Pharaoh Ramses II.

**Comment by adamierymenko** [comment]
We also use musl for static builds because glibc is virtually impossible to use for static builds.

**Comment by Spikhalskiy** [comment]
If you guys already have a build against musl published somewhere - likely this build can be directly installed to the alpine in this docker without adding this compatibility layer.

**Comment by adamierymenko** [comment]
Added a `make docker` for you folks, and fixed the Dockerfile a bit. Should work now in `dev`. "Works for me."

**Comment by Spikhalskiy** [comment]
@adamierymenko should dockerfile in ext/installfiles/linux/zerotier-containerized/Dockerfile be just cleaned up if the right supported dockerfile is in docker/Dockerfile ? Also need to test the build, I afraid that docker/Dockerfile will produce a much larger image.

**Comment by Spikhalskiy** [comment]
@glimberg your implemented solution should work, so the issue can be closed I think. At the same time, it will increase the size of the final image significantly - alpine Linux image is 2.66 Mb, while debian:buster-slim is 26 Mb. I think I will maintain my own version of Dockerfile for Zerotier just because the alpine version is much smaller.

**Comment by hawkinchina** [comment]
@Spikhalskiy
 hi,  the dockerfile for end user for arm64 can work now? 
https://github.com/zerotier/ZeroTierOne/blob/master/ext/installfiles/linux/zerotier-containerized/Dockerfile 

when i  use this dockerfile and build the image. then run the docker, it give some error. i 
 docker run -itd --rm --cap-add=NET_ADMIN --cap-add=SYS_ADMIN --device=/dev/net/tun -v ~/dockerfile/zerotier:/var/lib/zerotier-one --name zerotier_test  zerotier
8019695a589af3f29c125f648f6924bb6d788a22e2d189ca6b1a3ed86f4a793e
docker: Error response from daemon: error gathering device information while adding custom device "/dev/net/tun": no such file or directory.
