### ISSUE TITLE
How to debug packet loss? more than half of the packets are lost.

### ISSUE THREAD

**Issue by marcinprzybysz86** [zerotier/ZeroTierOne#1014]
Hi, I've got huge packet loss to my qnap at home behind a nat (8/2mbps). 
How to troubleshoot the issue?
The internet @home is working fine. Any ideas?
![packetloss](https://user-images.githubusercontent.com/44779944/63276755-4c2db600-c2a4-11e9-8027-ccf2f18a2c81.jpg)

The .20.20 host is a raspberry 2 with zerotier. Also big drops.
![packetloss2](https://user-images.githubusercontent.com/44779944/63276862-8ac37080-c2a4-11e9-840b-f754b3dae465.jpg)

**Comment by jeroen7s** [comment]
similar issue on my odroid
logs look like this:
`64 bytes from 172.24.1.151: icmp_seq=2 ttl=64 time=36.8 ms
64 bytes from 172.24.1.151: icmp_seq=3 ttl=64 time=41.8 ms
64 bytes from 172.24.1.151: icmp_seq=5 ttl=64 time=40.6 ms
64 bytes from 172.24.1.151: icmp_seq=9 ttl=64 time=51.2 ms
64 bytes from 172.24.1.151: icmp_seq=14 ttl=64 time=67.8 ms
64 bytes from 172.24.1.151: icmp_seq=16 ttl=64 time=42.2 ms
64 bytes from 172.24.1.151: icmp_seq=17 ttl=64 time=44.5 ms
64 bytes from 172.24.1.151: icmp_seq=18 ttl=64 time=52.3 ms
64 bytes from 172.24.1.151: icmp_seq=20 ttl=64 time=56.8 ms
64 bytes from 172.24.1.151: icmp_seq=21 ttl=64 time=59.1 ms
64 bytes from 172.24.1.151: icmp_seq=22 ttl=64 time=54.8 ms
64 bytes from 172.24.1.151: icmp_seq=23 ttl=64 time=60.5 ms
64 bytes from 172.24.1.151: icmp_seq=27 ttl=64 time=59.1 ms
64 bytes from 172.24.1.151: icmp_seq=28 ttl=64 time=71.2 ms
64 bytes from 172.24.1.151: icmp_seq=32 ttl=64 time=53.4 ms
64 bytes from 172.24.1.151: icmp_seq=33 ttl=64 time=64.9 ms
64 bytes from 172.24.1.151: icmp_seq=34 ttl=64 time=48.8 ms
64 bytes from 172.24.1.151: icmp_seq=35 ttl=64 time=39.6 ms
64 bytes from 172.24.1.151: icmp_seq=36 ttl=64 time=56.8 ms
64 bytes from 172.24.1.151: icmp_seq=37 ttl=64 time=66.3 ms
64 bytes from 172.24.1.151: icmp_seq=38 ttl=64 time=46.3 ms
64 bytes from 172.24.1.151: icmp_seq=40 ttl=64 time=48.5 ms
64 bytes from 172.24.1.151: icmp_seq=41 ttl=64 time=82.2 ms
64 bytes from 172.24.1.151: icmp_seq=42 ttl=64 time=102 ms
64 bytes from 172.24.1.151: icmp_seq=44 ttl=64 time=45.2 ms
64 bytes from 172.24.1.151: icmp_seq=45 ttl=64 time=49.3 ms
64 bytes from 172.24.1.151: icmp_seq=47 ttl=64 time=42.7 ms
64 bytes from 172.24.1.151: icmp_seq=48 ttl=64 time=59.4 ms
`
ping itself seems normal, but looking at the ping sequence I get responses for package: 2,3,5,9,14,16
but not for 1,4,6,7,8,10,11,12,13,15

**Comment by marcinprzybysz86** [comment]
thank you, it's probably because of double NAT , my ISP is gonna help me with this issue.

**Comment by jeroen7s** [comment]
Yeah seems like it's the same for me, on another network this issue disappears
