### ISSUE TITLE
AES-GCM-DDS criticism, better ideas, and discussion

### ISSUE THREAD

**Issue by adamierymenko** [zerotier/ZeroTierOne#1016]
See [this blog post](https://www.zerotier.com/zerotier-2-0-cryptography-notes/). This is an issue for comments on the cryptographic constructs discussed therein. Also see the [crypto.stackexchange.com](https://crypto.stackexchange.com/questions/72692/nonce-misuse-resistance-scheme-applied-after-the-fact-to-aes-gcm-for-defense-in) thread.

**Comment by adamierymenko** [comment]
Looks like someone on the crypto.stackexchange.com provided a very substantial series of answers that help a lot. Will be either using something else or revising the scheme slightly. More research TBD.

**Comment by masonhemmel** [comment]
Haven't looked too deeply into this, but if you're looking to improve the bounds on stateless IVs this work has already been done by Gueron and Lindell for Amazon in https://eprint.iacr.org/2017/702
