### ISSUE TITLE
Windows service fails when non-default home path is used

### ISSUE THREAD

**Issue by Teteros** [zerotier/ZeroTierOne#1019]
**Describe the bug**
ZeroTier One can be used as a foreground process with an alternate home directory like so:
```
zerotier-one_x64.exe -C "C:\zt\config"
zerotier-one_x64.exe -q -D"C:\zt\config" info
```
In service mode, this doesn't look to be supported at a glance
as the default Program/AppData [home value](https://github.com/zerotier/ZeroTierOne/blob/master/windows/ZeroTierOne/ZeroTierOneService.cpp#L76-L85) seems to be hardcoded.

Since service install (`-I`) switch does not respect parameters, Windows utility `sc.exe` can be used to change the executable path post-install.

When service is started then, ZT recognizes the custom home path and makes a folder there, but doesn't actually use it (no runtime files like `authtoken.secret` or `zerotier-one.port` are created).
The default home directory is not used either, the service seems frozen and takes a while to stop.

**To Reproduce**
1. Start an administrator command prompt and install the service if missing
`zerotier-one_x64.exe -I`
2. Change the `binPath` of the service to include a non-default home path as parameter
_(The path/parameter's [must be escaped](https://stackoverflow.com/a/11084834) if it has quotes)_
`sc config ZerotierOneService binPath= "\"C:\zt\zerotier-one_x64.exe\" \"C:\zt\config\""`
3. Check if the path is correct and start the service
`sc qc ZeroTierOneService`
`sc start ZeroTierOneService`
4. Confirm ZT makes the desired home folder, but does not use it.
5. Try to stop and delete the service
`sc stop ZeroTierOneService`
`sc delete ZeroTierOneService`
(sc.exe needs to be used to delete because `zerotier-one_x64.exe -R` fails)

**Expected behavior**
ZeroTier creates its runtime files and the service doesn't freeze when non-default config dir is used.

**Screenshots**
![ss](https://user-images.githubusercontent.com/5067989/63632045-598dcc00-c627-11e9-8bf9-944b2b628a56.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1903 x64
 - ZeroTier Version: 1.4.2

**Comment by adamierymenko** [comment]
Why would you ever want to do this?

**Comment by adamierymenko** [comment]
In any case I believe this is fixed in `dev`, will test.
