### ISSUE TITLE
Why the license change?

### ISSUE THREAD

**Issue by paweljacewicz** [zerotier/ZeroTierOne#1023]
Hi @adamierymenko,

I'd like to ask about the recent license change from GPLv3 to ZeroTier BSL 1.1. It seems it will create a lot of turmoil, especially if one is using ZT as a backend for some services.

This specific section seems troublesome to me (especially the end):
> (1) Operate or sell access to ZeroTier root servers,
> network controllers, or authorization key or certificate
> generation components of the Licensed Work as a
> for-profit service, regardless of whether the use of
> these components is sold alone or **is bundled with other**
> **services**.

Let's say I don't sell ZT as a service, but it is used as an important part of the communication backend of the service I operate... What then?

New license seems a bit contradictory to the statement on your webpage:
> Our software is open source and free to use. **A commercial license is only needed if you want to rebrand our stuff or create a closed-source derivative work**.

I understand that you need to protect your work and profits but this change seems sudden and can leave a lot of people hanging without easy option to opt-out.

I'll appreciate your comments on the matter.
Thanks!

Pawel

**Comment by adamierymenko** [comment]
It wouldn't apply to what you're doing. It would only apply if you are basically running a for-profit separate my.zerotier.com service.

The change is mostly because huge numbers of corporations hate the GPL and many have a "no GPL software" policy. They often grandfather in Linux but otherwise refuse to use GPL software at all.

**Comment by adamierymenko** [comment]
Basically their legal departments are paranoid about it.

We are updating our pricing page to clarify. It's not quite done yet.

**Comment by paweljacewicz** [comment]
Thanks for super-fast answer!

I totally agree that most companies are afraid of GPL software (because of legal misunderstanding the wording) and avoid it when possible.

Still, the wording used about bundling the ZT with other services may cause some legal people a heart attack. It would be nice if you could clarify somewhere what is an allowed use.

Thanks and I think this issue is solved.

Best regards!
Pawel

**Comment by adamierymenko** [comment]
Thanks. Maybe I'll clarify that.
