### ISSUE TITLE
Multicast only transmits 32 packets and then stops

### ISSUE THREAD

**Issue by smuething** [zerotier/ZeroTierOne#1024]
**Describe the bug**
I've tried to make Multicast work over a ZeroTier network. It does work initially, but after 32 datagrams the multicast receiver stops getting any data. Regular connections work just fine, and there is only a single sender and receiver on the network. They are bound directly to the virtual ZeroTier interfaces. I've also disabled all filtering in the ZeroTier network. `iperf` only gets a few packets and then stops:

```
[root@mue-ztg-hd-01 mcjoin-2.4]# iperf -s -u -B 225.1.2.3%ztmjfi7p5c -i 1
------------------------------------------------------------
Server listening on UDP port 5001
Binding to local address 225.1.2.3
Joining multicast (*,G)=*,225.1.2.3 w/iface ztmjfi7p5c
Receiving 1470 byte datagrams
UDP buffer size:  208 KByte (default)
------------------------------------------------------------
[  3] local 225.1.2.3 port 5001 connected with 10.60.99.60 port 45944
[ ID] Interval       Transfer     Bandwidth        Jitter   Lost/Total Datagrams
[  3]  0.0- 1.0 sec  44.5 KBytes   365 Kbits/sec   0.308 ms    0/   31 (0%)
[  3]  1.0- 2.0 sec  0.00 Bytes  0.00 bits/sec   0.308 ms    0/    0 (-nan%)
[  3]  2.0- 3.0 sec  0.00 Bytes  0.00 bits/sec   0.308 ms    0/    0 (-nan%)
[  3]  3.0- 4.0 sec  0.00 Bytes  0.00 bits/sec   0.308 ms    0/    0 (-nan%)
[  3]  4.0- 5.0 sec  0.00 Bytes  0.00 bits/sec   0.308 ms    0/    0 (-nan%)
[  3]  5.0- 6.0 sec  0.00 Bytes  0.00 bits/sec   0.308 ms    0/    0 (-nan%)
[  3]  6.0- 7.0 sec  0.00 Bytes  0.00 bits/sec   0.308 ms    0/    0 (-nan%)
[  3]  7.0- 8.0 sec  0.00 Bytes  0.00 bits/sec   0.308 ms    0/    0 (-nan%)
```

**To Reproduce**
1. Create a Network
2. Install zerotier-one on two machines and join the network
3. Make sure there are no firewalling rules in the way
4. Set default multicast route on the sender side to go through the network: `ip route add 224.0.0.0/4 dev <ZeroTier virtual if>`
5. Install iperf on both machines
6. Run `iperf -c 225.1.2.3 -u -t 3000 -i 1` on the sender side and `iperf -s -u -B 225.1.2.3%<ZeroTier virtual if> -i 1` on the receiver side

**Expected behavior**
There should be a constant stream of incoming multicast datagrams on the receiver side.

**Screenshots**
If applicable, add screenshots or console output to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Linux
 - Debian 10.0
 - ZeroTier Version 1.4.4
 - Hardware: x86_64
 
**Additional context**
- The network is hosted on ZeroTier Central and uses the default ruleset

**Comment by adamierymenko** [comment]
That is by design. Networks have a tunable field called the multicast limit which allows you to adjust the balance between multicast propagation breadth and bandwidth used.

**Comment by adamierymenko** [comment]
This can be adjusted in Central on the network status page or if you run your own controller via the multicastLimit network field.

**Comment by smuething** [comment]
I'm not talking about the multicast breadth - there is only one single subscriber, but it only receives the first 32 packets sent in the multicast stream.
