### ISSUE TITLE
macOS zoertier high cpu usage

### ISSUE THREAD

**Issue by jrz** [zerotier/ZeroTierOne#1029]
Zerotier usas as much cpu (% wise and time-wise) as WindowServer.
I have shut down zerotier with launchcontrol. 

I'm assuming that this issue won't be resolved, so the next best thing is to allow stopping/starting of the service using the UI, instead of the cli.

**Comment by laduke** [comment]
What version is running? `zerotier-cli -v`

**Comment by jrz** [comment]
Was running 1.4.0 I think. Now 1.4.6.
Leaving open for a week or something to see what's happening. So far it's around dropbox's cpu time, but well under WindowServer

**Comment by jrz** [comment]
Alright, so no super excessive cpu. But: it has the same cpu usage as dropbox.
It has a constant 0.8% - 1.2%

**Comment by Taik** [comment]
I'm also seeing the same thing, running on version `1.4.0`.

**Comment by adamierymenko** [comment]
Try upgrading to 1.4.6.
