### ISSUE TITLE
1.4.6 - bug(?) with default routing / local subnet (macOS)

### ISSUE THREAD

**Issue by luckman212** [zerotier/ZeroTierOne#1030]
**After upgrading to v1.4.6 on 2 Macs, my local networking stack became severely broken.**

- macOS 10.14.6
- local LAN subnet: 192.168.20.0/24
- ZeroTier subnet: 10.147.20.0/24
- I have managed routing set up like below, to route traffic to 192.168.20.x via 10.147.20.100 (which is a pfSense firewall running zerotier 1.4.2 from freshports):
![image](https://user-images.githubusercontent.com/1992842/64478209-0feac880-d173-11e9-9b74-89bcfd465637.png)

So after the upgrade, I could no longer stay connected to devices on my local LAN—all traffic was trying to route through the "bastion host" 10.147.20.100 (which was actually offline at that moment because I had the zerotier service stopped). I first noticed this when an iSCSI mounted volume started unmounting and losing connectivity. The target device was "on net" so e.g. 192.168.20.40 (Mac#1) →192.168.20.21(iSCSI target) does not need to pass through any intermediate hosts, especially not the zt network.

But, instead I was seeing this:
```
$ ping 192.168.20.21
PING 192.168.20.21 (192.168.20.21): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
ping: sendto: No route to host
Request timeout for icmp_seq 4
ping: sendto: Host is down
Request timeout for icmp_seq 5
ping: sendto: Host is down
Request timeout for icmp_seq 6
ping: sendto: Host is down

$ route -n get default
   route to: default
destination: default
       mask: default
    gateway: 192.168.20.1
  interface: en0
      flags: <UP,GATEWAY,DONE,STATIC,PRCLONING>
 recvpipe  sendpipe  ssthresh  rtt,msec    rttvar  hopcount      mtu     expire
       0         0         0         0         0         0      1500         0

$ route -n get 192.168.20.21
   route to: 192.168.20.21
destination: 192.168.20.21
  interface: feth2686
      flags: <UP,HOST,REJECT,DONE,LLINFO,WASCLONED,IFSCOPE,IFREF>
 recvpipe  sendpipe  ssthresh  rtt,msec    rttvar  hopcount      mtu     expire
       0         0         0         0         0         0      2800        -3
```

Even after quitting and uninstalling ZeroTier, I was left with broken networking until a full restart:
```
$ ping 192.168.20.21
PING 192.168.20.21 (192.168.20.21): 56 data bytes
36 bytes from r1 (192.168.20.1): Redirect Host(New addr: 192.168.20.21)
Vr HL TOS  Len   ID Flg  off TTL Pro  cks      Src      Dst
 4  5  00 0054 9ae7   0 0000  40  01 3634 192.168.20.40  192.168.20.21

64 bytes from 192.168.20.21: icmp_seq=0 ttl=64 time=0.322 ms
36 bytes from r1 (192.168.20.1): Redirect Host(New addr: 192.168.20.21)
Vr HL TOS  Len   ID Flg  off TTL Pro  cks      Src      Dst
 4  5  00 0054 0dc1   0 0000  40  01 c35a 192.168.20.40  192.168.20.21
^C
```
So for some reason, it was trying to route everything via `feth2686` zt interface. I need to test this more/again but for now everything was so broken that I had to remove ZeroTier.

**Comment by glimberg** [comment]
It's not trying to route "everything" through 10.147.20.100.  It's doing exactly what you told it to do in every example you've posted.  Each one is trying to reach something on 192.168.20.0/24.  It's trying to route 192.168.20.0/24 via 10.147.20.100, and you said the host at 10.147.20.100 was down.  Thus it cannot reach 192.168.20.0/24.

**Comment by luckman212** [comment]
I should have chosen my words more carefully. What I meant (thought that the problem was clear) is that having this managed route enabled caused traffic that should have been sent directly across the LAN to instead be routed via the ZT bastion host which of course was unreachable.

Even if it _had_ been reachable, this still would have caused a useless extra hop (and an asymmetric route). I believe this was working properly in 1.4.2 and earlier.

This is only a problem for 2 endpoints that are both on the LAN defined in the managed routes. If one of them had been "outside" then it works normally.

**Comment by laduke** [comment]
Trick your OS into using the LAN with this one simple trick

Use 192.168.20.0/**23** via 10.147.20.100 for the Managed Route

**Comment by luckman212** [comment]
Ok but in general, if I happen to find myself on a network that also uses 192.168.20.0/23 wouldn't it break again? I feel like ZT should ignore the managed route if it exactly matches the subnet of a local physical interface...

**Comment by joseph-henry** [comment]
Closing due to age. Let us know if there's a reason we should consider re-opening. Thanks.
