### ISSUE TITLE
Access Denied on iPhone after auth

### ISSUE THREAD

**Issue by frbuccoliero** [zerotier/ZeroTierOne#1032]
**Describe the bug**
I connected my iPhone on my  ZeroTierOne network. From the personal area in the browser it says it's connected, and authenticated, but it has no internal ip assigned (even if i have auto-assign). From the iPhone it says Access Denied. 

**To Reproduce**
1. Create a Network
2. Join with some random device and watch it work good
3. Join with iPhone 
4. Auth the iPhone from the control panel
5. iPhone will say "Access Denied"

**Expected behavior**
Connect to the network

**Screenshots**
Will upload asap if you need, but i hope you understood.

**Desktop (please complete the following information):**
 - OS: Mac
 - OS/Distribution Version: High Sierra 
 - ZeroTier Version: LTS
 - Hardware: 2012 MBP
 
**Smartphone (please complete the following information):**
 - Device: iPhone 6S
 - OS: iOS
 - Version 12.4

**Comment by joseph-henry** [comment]
Are you still experiencing this issue? There were no other reports of this issue during the time this was posted.

**Comment by AlphaJack** [comment]
Same issue on the same iOS version
