### ISSUE TITLE
Can't find iOS App in Apple's App Store.

### ISSUE THREAD

**Issue by sbilly** [zerotier/ZeroTierOne#1035]
**Is your feature request related to a problem? Please describe.**
Can't find iOS App in Apple's App Store in China mainland.

**Describe the solution you'd like**
provide iOS app in China mainland.

**Describe alternatives you've considered**
or maybe source code in github.com.

**Comment by glimberg** [comment]
We're no longer allowed to distribute it in China per Chinese government & iOS App Store rules
