### ISSUE TITLE
macOS installer isn't notarized so macOS 10.15 won't let it run by default

### ISSUE THREAD

**Issue by myount** [zerotier/ZeroTierOne#1039]
**Describe the bug**
The installer package is not permitted to open by default on macOS 10.15 (Catalina) because it has not been ["notarized"](https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution).

**To Reproduce**
1. Run a macOS 10.15 beta (public or otherwise)
1. Download the latest installer from zerotier.com
2. Attempt to open it in the normal way (double-clicking the file or selecting it and pressing ⌘O in Finder)
3. Finder presents the message: _**“ZeroTier One.pkg” can’t be opened because Apple cannot check it for malicious software.**  This software needs to be updated. Contact the developer for more information._

Currently it is possible to work around this by right-clicking the file and selecting "Open" (as you would do with unsigned apps in earlier versions of macOS), but I'm not sure that this will work in the final release of 10.15.

**Expected behavior**
I expected the installer to launch.

**Screenshots**
<img width="532" alt="image" src="https://user-images.githubusercontent.com/637064/65000314-21417c80-d8b9-11e9-900e-b7cab5e37d87.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - OS/Distribution Version: 10.15 Beta (19A546d)
 - ZeroTier Version: 1.4.6

**Comment by glimberg** [comment]
New binary with notarization was put up late last night.
