### ISSUE TITLE
Use IP multicast with UDP instead of broadcast to perform local LAN peer discovery

### ISSUE THREAD

**Issue by heri16** [zerotier/ZeroTierOne#104]
Improve on local network discovery by using well tested protocols based on IGMP, that are used by Apple TV, Skype, DLNA, and other great P2P software. Choose from Zeroconf, mDNS, UDP multicast, or Internet Connectivity Establishment (ICE).

**Comment by adamierymenko** [comment]
Obsoleted by #180
