### ISSUE TITLE
Windows client 1.4.6 always add´s a default gw via 25.255.255.254

### ISSUE THREAD

**Issue by cyberbix** [zerotier/ZeroTierOne#1040]
Even with the option "Allow default route" off and no routing via specific nodes defined, the windows client 1.4.6 unter Windows 10 / 1903, always adds a Default route via 25.255.255.254.

Is this behaviour expected ?

**Comment by glimberg** [comment]
Not a bug.  This is to work around idiosyncrasies in Windows and allow Windows Firewall to work on ZeroTier interfaces.  See this comment: https://github.com/zerotier/ZeroTierOne/blob/master/osdep/WindowsEthernetTap.cpp#L981
