### ISSUE TITLE
How to config TCP port 443?

### ISSUE THREAD

**Issue by Tennyleaz** [zerotier/ZeroTierOne#1041]
Hi,
My network is blocking UDP connections, so I want zetotier-one to use TCP ports if possible. 
I see readme.md says:

    If a firewall between you and the Internet blocks ZeroTier's UDP traffic, 
    you will fall back to last-resort TCP tunneling to rootservers over port 443 (https impersonation).

How could I config to use TCP port for a zerotier one client?
My zerotier config looks like:

    $ sudo zerotier-cli status -j
    {
     "address": "2ab8a61af1",
     "clock": 1568777519273,
     "config": {
      "physical": null,
      "settings": {
       "allowTcpFallbackRelay": true,
       "portMappingEnabled": true,
       "primaryPort": 9993,
       "softwareUpdate": "disable",
       "softwareUpdateChannel": "release"
      }
     },
     "online": false,
     "planetWorldId": 149604618,
     "planetWorldTimestamp": 1567801551272,
     "publicIdentity": "2ab8a61af1:0:****...",
     "tcpFallbackActive": false,
     "version": "1.4.6",
     "versionBuild": 0,
     "versionMajor": 1,
     "versionMinor": 4,
     "versionRev": 6
    }

**Comment by wscott** [comment]
There is a -p<port> option to the zerotier-one command to start the daemon. You can look at however zerotier-one is started and add it there.

But the easiest is to put it in the local.conf file.  On linux you can create that file here:  /var/lib/zerotier-one/local.conf

The syntax is in the manual: https://www.zerotier.com/manual/#4_2

**Comment by Tennyleaz** [comment]
I create a local.conf file like:

    {
        "settings": {
            "allowTcpFallbackRelay": true
        }
    }

After that I re-join my network. But zerotier still shows "offline":

    $ sudo zerotier-cli status
    200 info 2ab8a61af1 1.4.6 OFFLINE

Anything I'm doing wrong?

**Comment by ANR2ME** [comment]
Since it's a fallback it will only be activated when UDP is being blocked isn't? and can't be activated manually

**Comment by vakker** [comment]
I have the same problem, I'm behind a firewall that's blocking UDP traffic.
I tested it with OpenVPN, switching from UDP to TCP manually solved my issue.
So I assume the issue with ZT should get resolved as well once it does the TCP fallback.

So why is it not getting triggered when it's enabled or what should I do to switch it over?

**Comment by OXERIS** [comment]
> I create a local.conf file like:
> 
> ```
> {
>     "settings": {
>         "allowTcpFallbackRelay": true
>     }
> }
> ```
> 
> After that I re-join my network. But zerotier still shows "offline", tcpFallbackActive shows false:
> 
> ```
> $ sudo zerotier-cli status
> 200 info 2ab8a61af1 1.4.6 OFFLINE
> 
> $ sudo zerotier-cli status -j
> ...
> "tcpFallbackActive": false,
> ...
> ```
> 
> Anything I'm doing wrong?
i want to create a local.conf file for windows client, do you know the path whitch put the file

**Comment by ANR2ME** [comment]
The one i have located on `C:\Program Files (x86)\ZeroTier\One\local.conf` not sure if it worked properly or not tho.
