### ISSUE TITLE
Moon does not support DDNS

### ISSUE THREAD

**Issue by jscrapy** [zerotier/ZeroTierOne#1047]
**Is your feature request related to a problem? Please describe.**

I have a dynamic IP in my home, the IP changes every half a month or several weeks.
but the moon must have a fixed IP, can you support domain name instead of a fixed IP config?

**Describe the solution you'd like**

the moon.json looks like this: 

```json
"stableEndpoints": ["gw.xxx.com/9993"]
```
or you can also support fixed ip
```json
"stableEndpoints": ["123.456.111.111/9993"]
```

**Describe alternatives you've considered**

**Additional context**

**Comment by jscrapy** [comment]
@lucktu  @hhhnb

**Comment by jscrapy** [comment]
this is a useful feature, most of the home bandwidth beyond 200Mb, that's far more than VPS support.
The result is we'll have lower latency, and somebody can also share their moons node to others.

**Comment by lucktu** [comment]
Yes, it's important.

For most people, the cost of fixed IP is expensive and unacceptable. And for many Chinese users, there's basically no zerotier without moon, and I left zerotier in part for that reason.

I hope that official attention will be paid to this issue.

**Comment by laduke** [comment]
See the "Root Server Decentralization" section 
https://www.zerotier.com/zerotier-2-0-status/

**Comment by jscrapy** [comment]
@laduke  Can I have a try  v2.0 and how can I install it?

**Comment by laduke** [comment]
it's not ready for testing yet.

Seems like for now the only thing you can do is re-build your moons when your address changes. :/

Closing because it can't be changed in 1.4.x and 2.0 will be out "soon", but we can still chat about it here.

**Comment by jscrapy** [comment]
@laduke    when zerotier V2.0 will be released?

**Comment by jscrapy** [comment]
@laduke can I have a try with zerotier V2.0 now?

**Comment by xmolith** [comment]
Any progress ?

**Comment by drunkpig** [comment]
Any progress? What can I help?

**Comment by rwecho** [comment]
waiting for new progress.

**Comment by meltingfuse** [comment]
it's 5 years since the dev claim zerotier 2.0 will be released soon
