### ISSUE TITLE
Getting new addres when changing physical IP / connected location

### ISSUE THREAD

**Issue by razvan-flavius-panda** [zerotier/ZeroTierOne#1053]
**Describe the bug**

When connected to a different network than the one I originally set it up on I do not see myself on the list of network members.

**To Reproduce**
1. Create a network and join it with 2 people for example
2. Change connection of my network / physical IP - like connect from another WiFi network or place
3. Looking at the list of connected users to the network the new location does not appear

**Expected behavior**

There should be a new entry under network for the new location I am accessing the network from.

**Desktop (please complete the following information):**
 - OS: NixOS
 - OS/Distribution Version: 19.03
 - ZeroTier Version: 1.2.12
 - Hardware: MSI GT75 Titan 8SF

**Comment by laduke** [comment]
The device/node ID of your machine? It doesn't change.
