### ISSUE TITLE
Cannot join network. sticks on REQUESTING_CONFIGURATION

### ISSUE THREAD

**Issue by csloz** [zerotier/ZeroTierOne#1054]
Can't seem to join networks.
New install on Debian.

 zerotier-cli info
200 info ed01c1cf93 1.4.6 ONLINE

I created a private network on the web ui, try to join within the ui using add member
Tells me member not seen.  Trying to join the network manually using zerotier-cli join network <networkname> sticks on requesting configuration.

 zerotier-cli listnetworks
200 listnetworks <nwid> <name> <mac> <status> <type> <dev> <ZT assigned ips>
200 listnetworks 000000000000000d  0e:ed:01:c1:cf:93 REQUESTING_CONFIGURATION PRIVATE ztaaaaaaan -

Am behind the China GFW, so likely they are blocking stuff.  Any suggestions?

**Comment by backmanma** [comment]
Not sure if it is related, but I have been having stuck on "REQUESTIN_CONFIGURATION" (on my created networks and on Earth) as well. Noticed it yesterday, not sure for how long.

**Comment by glimberg** [comment]
`000000000000000d` is not a valid network ID.

**Comment by csloz** [comment]
You gave the right clue.
The web backend lists the network with both a name and a network id.

The linux cli apparently doesn't like using the name.
Used the network id and it worked.

Weirdly this wasn't the case on the other machine (a mac)

Maybe the zerotier-cli help need to be more specific  - ie <network id> not <network>.  Or is the network name for something else?

**Comment by laduke** [comment]
The name is for display/informational purposes. It's just a setting on the network's config. It's possible for different networks to have the same name, but network IDs are always unique. 


I'd expect 000000000000000d would come back as "NOT_FOUND" though. 

`zerotier-cli join asdfasdfasdfasdf` -> 
`200 listnetworks 000000000000000a  0a:99:35:98:1b:1e REQUESTING_CONFIGURATION PRIVATE feth110 -`

**Comment by csloz** [comment]
Suggest amend the backend then to clearly state use the network id for connection.

Not sure of the point of showing the network "name" if its not used.
Should i close this and make another ticket for the backend text change?
