### ISSUE TITLE
Debian installer missing APT repository key

### ISSUE THREAD

**Issue by stalks** [zerotier/ZeroTierOne#1055]
When installing on Debian 10 buster with:

> `curl -s https://install.zerotier.com | sudo bash`

APT refuses to update its repository cache due to missing apt key

> `Err:4 http://download.zerotier.com/debian/buster buster InRelease`
> `The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1657198823E52A61`

Resulting in a failed installation

> `E: Unable to locate package zerotier-one`
> `*** Package installation failed! Unfortunately there may not be a package`
> `*** for your architecture or distribution. For the source go to:`
> `*** https://github.com/zerotier/ZeroTierOne`

**Comment by nate8199** [comment]
Install apt-transport-https and try again

**Comment by stalks** [comment]
Yup, that works. Thanks.

**Comment by david-synctech** [comment]
hi Zerotier team! I'm getting this error using debian buster. Tried the above workaround w/o success. I keep getting "The following signatures couldn't be verified because the public key is not available..." I've got the same results from using both the ssl and the gpg method. Any idea why this only happens on debian buster and any clues on how to fix this?

thank you - merci!

**Comment by jdrews** [comment]
Also getting this error on Debian Buster

**Comment by vshop-angel** [comment]
please check if you have installed gnupg

**Comment by R13TechNewbie** [comment]
I don't know if it relate or not, but in my kali-rolling (known as Debian 9 from gnupg -v) , i have the same problem.

Somehow I fixed it by doing what this website told me to 
https://shuvomoy.github.io/blog/programming/2016/05/07/Adding-a-GPG-key-manually-in-Ubuntu.html

It basically saving the public key to a file, and added it manually. However for my case, there is weird repository which i can't make sure where it come from, but i guess it come from install.zerotier.com while you running "curl -s http://install.zerotier.com | sudo bash" but correct me if i'm wrong. The repo (home:Provessor) make a conflict with the contact@zerotier.com public key. The solution is delete that conflicting repo in /etc/apt/sources.list.d and do the apt update again. You should be successfully installed the zerotier if you reach this step.

I want to reproduce my step, but I think i don't know how. So please if anyone have the same problem, verify if my statement is correct or not.

**Comment by mb-Ma** [comment]
> it doesn't work

**Comment by mvcaaa** [comment]
```curl -s http://download.zerotier.com/contact%40zerotier.com.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/zerotier.com.gpg > /dev/null```

**Comment by bburhans** [comment]
FYI the install script doesn't make sure that `/usr/share/keyrings/zerotier-debian-package-key.gpg` is globally readable; apt may fail to use it even when run as root, depending on the umask that the install script was running under.

You may either set your umask to 0022 (readable permissive) and retry, or simply 
```bash
chmod a+r /usr/share/keyrings/zerotier-debian-package-key.gpg
```
between attempts and it should recognize the signing key afterward and allow apt to proceed.

You may wish to do the same for `/etc/apt/trusted.gpg.d/zerotier.com.gpg` if you've created that file by following some zerotier documentation.
