### ISSUE TITLE
query interface for own address

### ISSUE THREAD

**Issue by 0-8-15** [zerotier/ZeroTierOne#1058]
This might be just a documentation issue which *I* haven't been able to resolve.

**The problem:**

Once zerotier started my application must to inform other peers which address to use to contact it.

I can manually do some wild guesses and figure the address out using `ip addr list`, `ifconfig`.

However I can't automate this process.  Especially not on Android.  Average users won't attach `adb` and guess.

**Sought solution**

Looks like `zerotier-one -q status` returns the ID which presumably can be converted into the IPv6 address -- but I can't find out how.  It might be enough for me on Linux to learn how  to the conversion should be done.

For Android I'd need to ask for more:
 - either:  the App should clearly display the actual address and provide  means to copy it to the clipboard
 - or: at least display the ID and provide means to copy to clipboard (plus some documentation how I'd eventually convert that into the IP address)

**Alternatives**

elude me - I don't see how phone A could connect to phone B if all A has is the network address on which A presumably listens.

**Comment by laduke** [comment]
Hello,

Not sure if this option is in the Android client, but there's 
zerotier-one -q get <networkId> ip6

ip, ip4, ip6, ip6plane, and ip6prefix can be used

**Comment by 0-8-15** [comment]
On Oct 17 2019, Travis LaDuke wrote:

>Hello,
>
>Not sure if this option is in the Android client, but there's 
>zerotier-one -q get <networkId> ip6
>
>ip, ip4, ip6, ip6plane, and ip6prefix can be used

Thanks so much.  That's what I've been looking for.  At least for the CLI.

With Android it's a bit stranger: Taping the network ID leads to a 
different screen. It takes something between long and forever, but than 
suddenly the IP address is displayed there.

Remaining feature request:

- Minimal: It should be possibly to copy that address to the clipboard.
- Optimal: There was a way to query the setting from another App.

**Comment by glimberg** [comment]
You can query `http://my.zerotier.com/network/<network_id>/member/<member_id>` to get the information you want.  

https://my.zerotier.com/help/api
