### ISSUE TITLE
Misleading rules example in manual

### ISSUE THREAD

**Issue by misuzu** [zerotier/ZeroTierOne#1060]
**Describe the bug**

Manual section: https://www.zerotier.com/manual/#3_4_1

This rule will allow access to 80 and 443 port via udp:
```
# Allow SSH, HTTP, and HTTPS by allowing all TCP packets (including SYN/!ACK) to these ports
accept
  ipprotocol tcp
  and dport 22 or dport 80 or dport 443
;
```

This rule will allow access to 445 port via tcp and udp for any department:
```
# Allow Windows CIFS and netbios between computers in the same department using a tag
accept
  ipprotocol tcp
  and tdiff department 0  # difference between department tags is 0, meaning they match
  and dport 139 or dport 445
;
```

**Expected behavior**

These rules will only allow access to 22, 80 and 443 port via tcp:
```
# Allow SSH, HTTP, and HTTPS by allowing all TCP packets (including SYN/!ACK) to these ports
accept
  ipprotocol tcp
  and dport 22
;
accept
  ipprotocol tcp
  and dport 80
;
accept
  ipprotocol tcp
  and dport 443
;
```

These rules will allow access to 139 and 445 port only via tcp and only for peers in same department:
```
# Allow Windows CIFS and netbios between computers in the same department using a tag
accept
  ipprotocol tcp
  and tdiff department 0  # difference between department tags is 0, meaning they match
  and dport 139
;
accept
  ipprotocol tcp
  and tdiff department 0  # difference between department tags is 0, meaning they match
  and dport 445
;
```

**Comment by asbjornenge** [comment]
Aha! I was struggling with this too. This is because the `or dport` in the examples OR all the other rules - any thereby allow all traffic to the OR'ed port...?

Good catch 👌

**Comment by laduke** [comment]
I had updated the examples and added a note. I think from a different ticket/issue. 

[Basically, rules are left to right](https://docs.zerotier.com/zerotier/rules#343actionsmatchesoperatorsandconstantsaname3_4_3a)
