### ISSUE TITLE
Format for "routes" in Controller JSON API?

### ISSUE THREAD

**Issue by smkm** [zerotier/ZeroTierOne#1062]
https://github.com/zerotier/ZeroTierOne/tree/master/controller

Network object format:
```routes | array[object] | Managed IPv4 and IPv6 routes; see below | YES```

The array of objects format for `routes` is not specified. Settings for managed routes are ambiguous. Please fix the README.md in the controller directory.

**Comment by laduke** [comment]
I'll add something. 
It's like this:

```javascript
{
  routes: [
    { target: '10.242.0.0/16' },
    { target: '1.2.3.4/24', via: '9.0.0.8' }
  ]
}
```

**Comment by smkm** [comment]
Great, thanks. 

```
routes | array[object] | Managed IPv4 and IPv6 routes; see below | YES
ipAssignmentPools | array[object] | IP auto-assign ranges; see below | YES
rules | array[object] | Traffic rules; see below | YES
capabilities | array[object] | Array of capability objects (see below) | YES
tags | array[object] | Array of tag objects (see below) | YES
```

Example format for the rest of `array[object]` formats in `/controller/network/<network ID>` except `rules` and `ipAssignmentPools` would also be great.

**Comment by k4d1sm0** [comment]
Hi, I'm trying to add a new route on zerotier, using API, but I can't, all settings I can change using API, just the routes I can not.
The command that I'm using is:
curl -v -X POST -H "Content-Type: application/json" -H "Authorization: bearer XXXXXXXXXX" -d '{"enableBroadcast":true,"routes":[{"target": "10.112.0.0/24","via": "10.243.235.92"}],"ipAssignmentPools": [{"ipRangeEnd":"10.243.255.254","ipRangeStart": "10.243.0.1"}],"name": "network-name","private":true,"v4AssignMode": {"zt": true},"v6AssignMode": {"6plane": true,"rfc4193": false,"zt": true}}' https://my.zerotier.com/api/network/mynetworkid

**Comment by laduke** [comment]
The my.zerotier.com and the controller service apis are slightly different. http://apidocs.zerotier.com/
