### ISSUE TITLE
Problems with zero tier 1.4.6 in alpine 3.9

### ISSUE THREAD

**Issue by diazvictor** [zerotier/ZeroTierOne#1064]
I have compiled it from scratch and running zerotier-cli gives me an error
`zerotier-cli join id`
This is the way out:
`0 join connection failed`
and I've confirmed that the id is correct.

**Comment by glimberg** [comment]
Either the `zerotier-one` daemon isn't running, or iptables is blocking communication to localhost:9993/tcp
