### ISSUE TITLE
Prefer path on 1.4.6

### ISSUE THREAD

**Issue by gy6221** [zerotier/ZeroTierOne#1067]
**Describe the bug**
I have 2 devices in my zerotier network. Device A is a fixed router, which is running openwrt x86
Device B is a windows laptop, running windows 10 1903. Both of them running zerotier 1.4.6.

Usually there are 2 network paths available between A and B. One is through the public internet, which provides around 30Mbps bandwidth on both direction. The other one is through a private network, but not in same subnet, this path provides 100Mbps bandwidth. The latency and packet loss rate on these 2 paths are similar. In my case, zerotier always keep switching the "peferred" path between these two around around every 10 seconds, which makes the throughput not stable. I even tried to edit the local.conf file on B to blacklisted the public internet ip of A, but still no luck. All the uploading traffics (from B to A) went through the private network, but the downloading traffics still keep switching. May I know if there any settings to force override the preferred flag? Thanks.

**Expected behavior**
Zerotier will choose the faster path and keep on that path unless it is not available.

**Screenshots**
Not available.

**Desktop (please complete the following information):**
 - OS: Windows
 - OS/Distribution Version: Windows 10 Pro 1903
 - ZeroTier Version 1.4.6
 
**Router (please complete the following information):**
 - Device: X86 PC
 - OS: Openwrt X86
 - Zerotier Version 1.4.6

**Additional context**
multipathMode is set to 0 on both devices. I tried to set this setting to 2, but that makes the connection unstable, and provides much higher latency.

**Comment by willawork** [comment]
Same thing applies to if you have two Internet links, and ZT ends up doing asymmetrical routing - low-latency via landline, high latency via 4G/LTE.  Need some way to go "nonono, use this one please unless it's dead".

**Comment by joseph-henry** [comment]
Have you tried using `interfacePrefixBlacklist`?

```
"interfacePrefixBlacklist": [ "XXX",... ]
```

**Comment by willawork** [comment]
Blacklisting totally takes out that path as a usable transport (and could lock you out of the device).  The new multipathing tidbits might be a better option, using the master/slave/slave/slave options to help control path selection.

**Comment by joseph-henry** [comment]
We've done some path learning work in the `dev` branch which will be mainlined in the next release. I'm wondering if that will help. Are you still seeing this issue?

**Comment by joseph-henry** [comment]
An update: We've included some fixes that should address this issue. They'll be included in `1.8.5` and are in `dev` right now. Closing this ticket but please let me know if you still see problems.
