### ISSUE TITLE
Question about strange leaf

### ISSUE THREAD

**Issue by asminozhka** [zerotier/ZeroTierOne#1069]
When i run "zerotier-cli peers", i can sew some PLANETs and unknown for me LEAF (and my devices)
![image](https://user-images.githubusercontent.com/41116859/67889164-623adb00-fb5f-11e9-9ccb-1bf011b2827f.png)
This leaf not displaying on my.zeronet network page

When i added firewall drop rule for it's ip, i lost ability to connect to my devices in my zeronet network.

What is this strange LEAF? What is purpose of it?

**Comment by glimberg** [comment]
`af415e486f` is one of our hosted network controllers.  You're likely connected to a ZeroTier network beginning with the digits `af415e486f`
