### ISSUE TITLE
my.zerotier.com buggy edition of member name/description

### ISSUE THREAD

**Issue by Silex** [zerotier/ZeroTierOne#1071]
Hello,

Whenever I edit the name or description of a member of my network on my.zerotier.com, I get letters that disappear then suddently reappear, causing me to enter wrong input. This is especially annoying because we are using these to store serial ids (mac addresses) and we get user input errors.

This is obviously an AJAX logic error, I see that whenever I type requests are sent to `https://my.zerotier.com/api/network/foo/member/bar` and sometimes I even get this error in return:

``` json
{"type":"internal","message":"Error marshalling json"}
```

My guess is that the implemention is made so as soon as a character is input, the whole member is sent to be saved, which takes a little while and when the request finished it redisplays the currently saved member. This implementation has the issue that if you type quickly enough, your input gets "discarded" fairly easily as soon as one of the request is out of order.

Instead of using the javascript keypress event you'd use the `change` event, which only triggers once the widget lost focus. Or you do the request after 1s of inactivity. Or you disable the widget while the request is active. Any solution that prevents me from losing input :wink:

**Comment by laduke** [comment]
Hi! thanks for reporting. Can you try the "beta members interface"? There's a link at the top of the members list. 
 Otherwise I'd do it by pasting into the field.

**Comment by Silex** [comment]
The beta member interface behaves properly because it implements the `change` event I was talking about, but is is not "list-based" which makes it kinda painful to find/sort devices. Also there should be a button to copy the IP address of the members more easily.

**Comment by glimberg** [comment]
Just click the IP address and it copies it to your clipboard

**Comment by Silex** [comment]
@glimberg: nice!

Right next to the IP box at the right there's the "Delete adress" icon. I clicked it to check what would happen and it deletes the IP address without a confirmation! I think it'd at least ask some "Are you sure?" popup.

**Comment by laduke** [comment]
![Screen Shot 2019-10-31 at 2 52 14 PM](https://user-images.githubusercontent.com/11598/67988714-0ff4cb00-fbee-11e9-858f-6ea9ddbf4aaa.png)

**Comment by Silex** [comment]
@laduke: no I didn't delete the member, only the IP address. Anyway it cames back on its own after a while.

**Comment by laduke** [comment]
yeah one of the quirks of having auto-assign.
You can manually assign by opening More Info and then Advanced. 
Most users shouldn't mess with it, so it's out of the way.

**Comment by Silex** [comment]
Thanks for the information everyone.

Closing because there does not seem to be an interest in fixing this in the old interface. Reopen if needed.
