### ISSUE TITLE
ZT 1.4.6 on Alpine Stuck to 1 Thread

### ISSUE THREAD

**Issue by bradsoto** [zerotier/ZeroTierOne#1072]
I've encountered this bug before, but it was easily resolved by giving the container 2 CPU cores instead of 1. When ZT has 1 core in an Alpine Linux container the throughput is limited to about 1MB/s. Once given a second core it performed as expected. With the most recent version 1.4.6 adding cores has no effect. The service has somehow limited itself to 1 thread and 1MB/s is as fast as it will push traffic.

![Screenshot_2019-10-31 pve-gp-vsw-03 - Proxmox Virtual Environment](https://user-images.githubusercontent.com/1541011/67976068-feee8e80-fbda-11e9-81ff-495636d9206a.png)

**Comment by joseph-henry** [comment]
Closing due to the fact that multiple versions have come out since this ticket was initially created (and unfortunately ignored). If you still see this issue in our current version please re-open a ticket and reference this so we can investigate. Thanks.
