### ISSUE TITLE
Android (1.4.4) not any more "working" with other units (1.4.6)

### ISSUE THREAD

**Issue by bricolodu13** [zerotier/ZeroTierOne#1073]
Since 1.4.6 my Android phone can only access files from my home, when connected on the same wifi network, not anymore from 3/4G

All my devices are listed as connected, including my phone but it can not play music files unless when back home.

This was woking just fine a few weeks ago before upgrading to the latest revisions

**Comment by joseph-henry** [comment]
Are you still experiencing this issue? If so tell us more about your Android device, what is it and what version of Android are you running?

**Comment by bricolodu13** [comment]
Hello,
Thank you for taking care. I tried again today, and it looks it's working again as it should.

**Comment by joseph-henry** [comment]
Glad to hear!
