### ISSUE TITLE
Ubuntu 19.10 (eoan) packages

### ISSUE THREAD

**Issue by mikea** [zerotier/ZeroTierOne#1074]
Would be great to have eoan packages published at http://download.zerotier.com/debian/

**Comment by nixcamic** [comment]
I agree, currently using the disco repository and its working fine but having a proper eoan repo would be much better.

**Comment by unquietwiki** [comment]
Ubuntu 19.10 is EOL; 20.04 LTS has been out a few months, and we're working on a 1.6.0 release of ZeroTier to occur very soon. Closing ticket.
