### ISSUE TITLE
Stuck on REQUESTING_CONFIGURATION on University WiFi

### ISSUE THREAD

**Issue by carlos1172** [zerotier/ZeroTierOne#1077]
I've made two networks, one public, and one private. I'm attempting to connect to my ZeroTier networks on Campus WiFi using my laptop, but it's stuck on REQUESTING_CONFIGURATION. The other computer is my desktop at home. 

If I use mobile data to connect to ZeroTier first, quit it, connect to campus WiFi, then turn on ZeroTier it says OK but I'm unable to stream content from my home PC. I used to be able to stream games from my home PC to my laptop on Campus WiFi using ZeroTier and Moonlight Stream, now I can't even ping my home desktop.

Home desktop and Laptop are running Windows 10 64-bit Pro 1903. What do I do?

**Comment by hazi98** [comment]
I have the same problem as you in a similar situation, and probably the network is blocking outbound UDP packets for the ZeroTier port, or blocking the root servers. I'm still investigating what the solution could be, but the problem is pointing to be a firewall.

**Comment by dgraziotin** [comment]
+1 on this. My university blocks UDP connections but ZeroTier somehow does not detect it completely. 

The system stays stuck with ```REQUESTING_CONFIGURATION PRIVATE``` for hours and nothing happens. Is there a way to force TCP?
