### ISSUE TITLE
Closing the tray app leaves remote shares available - must stop service

### ISSUE THREAD

**Issue by TheBestPessimist** [zerotier/ZeroTierOne#1078]
**Alternative, faster ways to get help**
If you have just started using ZeroTier, here are some places to get help:
- my.zerotier.com has a _Community_ tab. It's a live chat with other users and the developers. 
- [ZeroTier Knowledge Base](https://zerotier.atlassian.net/wiki/spaces/SD/overview)
- www.zerotier.com has a Contact Us button
- email contact@zerotier.com

**Describe the bug**
On windows, if i close the tray app, i can still connect to my remote shares.

**To Reproduce**
1. Start watching a film from a network share on a computer connected via zerotier
2. Close the zerotier tray app
3. The film still plays without any hickups

**Expected behavior**
After closing the zerotier tray app, the connection to other computers (via zerotier) should be stopped. Currently in order to be disconnected from the other computers i have to stop/disable the zerotier service.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows,
 - 1903
 - ZeroTier Version 1.4.6
 - laptop
 

**Additional context**
nothing to add here

**Comment by glimberg** [comment]
This is by design.  The tray app is just a control interface to the background service.

**Comment by TheBestPessimist** [comment]
Is there a way for the user to change this? I find that having to disable the service whenever i am home with my laptop, compared to only exiting a tray app has much more overhead

**Comment by laduke** [comment]
Unjoin the network(s)
