### ISSUE TITLE
Two factor authentication (zerotier.com web site)

### ISSUE THREAD

**Issue by adamierymenko** [zerotier/ZeroTierOne#109]

**Comment by yosuah** [comment]
+1
(I assume this ticket refers to logging in to my.zerotier.com, the administration interface for users.)

This looks like a very low-hanging fruit for making the whole system more secure. No matter how good the whole infrastructure is if all my networks can be compromised by stealing one single password that is used to manage the web interface, essentially letting untrusted 3rd parties join a trusted private network. 2FA is pretty established, so I am sure anyone who is just about to set up a VPN for herself/her company is also already using it for critical systems or should consider it heavily. (I know VPN should not be used as the single defense line, but it can still be a very strong one, so it would be a shame to weaken it so easily.)

**Comment by adamierymenko** [comment]
Closed since this is being moved to Central's issue tracker.

**Comment by adamierymenko** [comment]
Coming reasonably soon.

**Comment by L3vi47h4N** [comment]
Any updates? The best we have gotten so far is "use Google." To be honest, 2FA/multifactor is a dealbreaker for a good number of people.

**Comment by Menci** [comment]
How is it going?

**Comment by PhilETaylor** [comment]
September 2018 and still no 2fa?!!?!?

**Comment by lnxg33k** [comment]
You guys need to implement this.

**Comment by PhilETaylor** [comment]
On 13th September 2018 I got a reply from support with 

```
Thanks for getting in touch with us.

2FA is in development. For now, you can use the login with google method and use 2FA on your google account. 

If you have any questions, do not hesitate to contact us.
```

Adding 2FA code takes 1 hour max, add another day for testing, and a day for documentation update...

**Comment by lnxg33k** [comment]
@PhilETaylor The issue with that is I am using their cloud controller and not on a private server with code compile from the source.

**Comment by PhilETaylor** [comment]
I was not suggesting that you do it yourself :-) this should be a core part of their product from the start. I hear too many times that "2fa is in development" from companies - its just an excuse - I implemented 2FA within an hour in a live production product used by 1000s - its not difficult. If it takes more than a day/week then they are seriously doing something wrong - or lying. Unfortunately the latter is often the case with many companies that dont take security seriously.
