### ISSUE TITLE
Same Internet but cant relay

### ISSUE THREAD

**Issue by CIKOMELANTIK** [zerotier/ZeroTierOne#1094]
so i have 2 friends that have same internet (same house)

lets say they have A desktop and B desktop

my connection to B is direct but my connection to A is relay even both of them r same internet

but idk what happened and suddenly i can direct to A but cant to B

but if they changed to mobile hotspot, i can direct connect to all of them

is there anyway to force direct connection?

**Comment by joseph-henry** [comment]
Closing due to age but if you are still experiencing this issue please let us know.
