### ISSUE TITLE
excessive CPU usage

### ISSUE THREAD

**Issue by rebroad** [zerotier/ZeroTierOne#1095]
![image](https://user-images.githubusercontent.com/1530283/69824794-a203e980-1215-11ea-9e18-d9289fea15df.png)

Screenshot shows how the zerotier-one process uses up significantly more CPU than smbd. This is using both processes to receive and store a file locally. The file is being transferred from another computer on the same LAN.

Why is CPU usage so high? Is it perhaps doing compression, which could be switched off given it is unnecessary over a LAN?

**Comment by lunarthegrey** [comment]
Probably due to the crypto zerotier-one is doing https://www.zerotier.com/manual/#2_1_3

**Comment by adamierymenko** [comment]
In 2.x we are switching to AES as default for encryption (faster on almost all modern CPUs) and compression is no longer used on regular unicast packets since 90%+ of traffic these days is encrypted or already compressed.
