### ISSUE TITLE
E: missing-call-to-setgroups-before-setuid

### ISSUE THREAD

**Issue by tim77** [zerotier/ZeroTierOne#1096]
On Fedora rpmlinter says there is the error:

```
E: missing-call-to-setgroups-before-setuid /usr/sbin/zerotier-one
```

Can we fix this somehow to satisfy linters?

**Desktop (please complete the following information):**
 - OS: Fedora
 - OS/Distribution Version: 31
 - ZeroTier Version: 1.4.6
 - Hardware: PC

**Comment by kwizart** [comment]
There is also a "warning" with:
> zerotier-one.x86_64: W: executable-stack /usr/sbin/zerotier-one
This should be possible to avoid it...
