### ISSUE TITLE
MacOS guest on VMware 15 gets subnetmask 255.255.255.255

### ISSUE THREAD

**Issue by ertankucukoglu** [zerotier/ZeroTierOne#1101]
I am using ZeroTier One 1.4.6 on Windows 10 Pro (all updates installed as of today) at home.
I have a ZeroTier One 1.2.12 running on Debian 10 VPS 24/7 serving one single network.
I have OpenWrt v19 router on my network serving as DHCP server.
Windows Firewall is default configuration.
OpenWrt has default network settings. I only have some static IP numbers for some computers on my LAN setup in DHCP part.

I have a single network connection from my Windows to that ZeroTier on VPS.
I have VMware 15 on my Windows PC. There is MacOS Mojave (10.14) running in VMware as a guest.
There is no ZeroTier One installed on that MacOS.
MacOS network: only IP number is set as manual, remaining information is received from DHCP server.

Problem: If I have my Windows ZeroTier One network connection active (check mark displayed in tray icon right mouse click). My VMware guest MacOS Mojave cannot get correct subnetmask from dhcp server. It does not help to manually assign a static IP and subnetmask and default gateway. That won't get MacOS to internet either. It only works OK if I disconnect from my ZeroTier One network (no check mark next to network id on tray icon right mouse click).

Steps to reproduce the behavior (as far as I can tell):
1. Connect to one single network hosted by 1.2.12 version of ZeroTier
2. Install zerotier-one 1.4.6 on Windows 10 Pro 64Bit.
3. Install VMware 15.1 or higher version (I have same problem with 15.1 and 15.5)
4. Install MacOS Mojave in VMware.
5. After everything is running. Close VMware.
6. Connect to ZeroTier network.
7. Open VMware
8. Run MacOS guest.
9. MacOS won't get IP from DHCP server. And very rarely it does get it. This time any big download breaks after a while. MacOS won't ping any LAN computers and no LAN computer can ping MacOS.

Any help is appreciated.

**Comment by featherbear** [comment]
What are the network configurations for your VMware adapters?
Also your ZeroTier network?

**Comment by ertankucukoglu** [comment]
VVware is using e1000e as ethernet drive on Bridged mode (not sure if relevant). Below is its setup.
![vmware_adapter_settings](https://user-images.githubusercontent.com/14805520/70231509-821b7b00-176b-11ea-9599-8d8be0d25641.PNG)

MacOS is set to use 192.168.8.4 IP number. It receive subnet and default gateway from dhcp server. 

Dhcp server setup as 255.255.255.0 subnet and 192.168.8.1 as default gateway.

My Windows machine always use dhcp server auto assigned IP number. It is mostly assigned 192.168.8.117 with same subnet as above.

ZeroTier One is setup as 192.168.191.0/24 network.

Windows machine is provided 192.168.191.56 IP number out of that pool as managed IP number.

**Comment by featherbear** [comment]
Okay, probably what is happening is that the automatic bridging has selected ZeroTier rather than your physical card to bridge to.

Open up your Virtual Network Editor (`vmnetcfg`), select VMnet0, and click the [Automatic Settings...] button. Then deselect the ZeroTier adapter.

![image](https://user-images.githubusercontent.com/1159091/70232233-14457280-17b0-11ea-86b9-e586c210a796.png)

**Comment by ertankucukoglu** [comment]
I have done that. Will need several days to see if that is the problem.

If all goes good, I am going to close that report in a couple days.

Thanks for the help.

**Comment by ertankucukoglu** [comment]
Did numerous tests that I can think of an repeated them at least 5 times.
That seems to solve the problem.

Thanks
