### ISSUE TITLE
Having a Managed Route without a Managed IP breaks networking on MacOS

### ISSUE THREAD

**Issue by laduke** [zerotier/ZeroTierOne#1104]
**Describe the bug**
Having a Managed Route without a Managed IP breaks networking on MacOS

**To Reproduce**
1. Create a Network 
2. Turn off Auto-Assign from Range (v4)
3. Join and Authorize
4. See error: `ping: sendto: Address family not supported by protocol family`
5. Leave the network and cycle wifi to get networking back. 

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.1
 - ZeroTier Version [e.g. 1.4.6]

```sh
 ❯❯❯ ip r                                                                       ⏎ master ✱
default via 92:29:f1:6f:2f:76 dev en0
10.187.0.0/24 dev en0  scope link
10.187.0.1/32 dev en0  scope link
10.187.0.56/32 dev en0  scope link
127.0.0.0/8 via 127.0.0.1 dev lo0
127.0.0.1/32 via 127.0.0.1 dev lo0
169.254.0.0/16 dev en0  scope link
224.0.0.0/4 dev en0  scope link
255.255.255.255/32 dev en0  scope link
```

**Comment by GioF71** [comment]
Hello, does your console report errors like the following:

kernel	en1: can't handle af18

**Comment by sboisson** [comment]
I've seen the same error message (Address family not supported by protocol family) and the 'en1: can't handle af18' in the console logs… 
But that was on no- managed network, without ZeroTier IP allocation, attempting to enable DHCP

**Comment by thinxer** [comment]
I'm trying to use IPv6 assignment only, without the IPv4 addresses for my network, and experienced the same problem on macOS Catalina 10.15.3. ZeroTier version 1.4.6.

**Comment by thinxer** [comment]
I just removed all managed IPv4 routes and the problem has gone. Nevertheless, zerotier messing with the default route (without Allow Default enabled) still bothers me.

**Comment by tomgidden** [comment]
I'm getting this too.  This is on macOS Catalina 10.15.3, ZeroTier One 1.4.6.

WIthout ZeroTier running, if I `ping 8.8.8.8`, it's fine.  Then I start ZeroTier, join the network, and after a few seconds ping starts reporting `Address family not supported by protocol family` and console has `can't handle af18`.

Checking the routing table, the default route via `en0` has been removed, and replaced by one on `feth1446`.

If I then leave the network and `ifconfig en0 down; ifconfig en0 up`, it works again.  I re-join the network, and the errors resume.

If I untick "Allow Managed" and retry, normal Internet access works, but of course ZeroTier doesn't work, having no address.

Then, in `my.zerotier.com` I switch "Auto-Assign from Range" back on, and retry, and it works.  As a workaround, I add my preferred IP (which matches that in our private `.zt` DNS), leave and re-join, and it works.

I remove the auto-assigned address in `my.zerotier.com`, leave and re-join, _and it still works._

So, I'm not sure what's up with that.  I have no idea if it'll continue to work or not. :/

**Comment by jtrott** [comment]
I have the same issue here.
I created a new network, didn't want to use one of the auto assigned subnets, switched to advanced, deleted the subnet and added in my own IP range.
I didn't modify the Managed Routes, which had a route from the auto assigned subnet I was no longer using.
Connecting to this network from macOS 10.15.4 using ZeroTier One 1.4.6 resulted in the previously mentioned loss of networking and errors of "can't handle af18" in the console.
Fixing the Managed Routes to include the Advanced IP Range subnet I was using has resolved the issue.
Maybe the web interface can highlight an invalid configuration in that case and prevent the situation from occuring?

**Comment by rizwankh** [comment]
I deleted the managed route that i had added for default and it started working. Then i added it again and it kept on working .. now disconnected again. So no other way but to delete the default route for now.

**Comment by lessless** [comment]
My network is not managed and I experience the same problem: 

```
 ssh 172.30.220.96

ssh: connect to host 172.30.220.96 port 22: Address family not supported by protocol family
```

![](https://i.imgur.com/CgLhblD.png)
