### ISSUE TITLE
Question: How to set FirewallD for vpn

### ISSUE THREAD

**Issue by llyang1** [zerotier/ZeroTierOne#1106]
zerotier can do vpn very well if I use centos iptables like following

iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
iptables -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
iptables -A FORWARD -i zt0 -o eth0 -j ACCEPT

Now the new centos 8 can only use FirewallD, what is the equivalent to the above-mentioned rules

I am very new to FirewallD, sorry, It is not a bug or new function requirement, I can not find suitable place to ask the question.

The first command can be replaced by following command in FrirewallD, other two commands I do not know how to replace
firewall-cmd --zone=public --add-masquerade

**Comment by glimberg** [comment]
Probably better to ask the `firewalld` people than us.  The first thing I do on any CentOS install is `yum remove firewalld`
