### ISSUE TITLE
devicemap not supported/working under FreeBSD

### ISSUE THREAD

**Issue by rdslw** [zerotier/ZeroTierOne#1107]
I'm using devicemap file on my linux boxes to use 'zt0' interface name for specific network.

I tried to use the same mechanism under FreeBSD (12.1 RELEASE), to no success. Interface name is the same

File /var/db/zerotier-one/devicemap has one line:
NETWORK=zt0

where NETWORK is my network id.

ZeroTier Version 1.4.6

**Comment by glimberg** [comment]
The `devicemap` file is a Linux only feature.
