### ISSUE TITLE
Unknown node ID in peers list

### ISSUE THREAD

**Issue by qingfengshi** [zerotier/ZeroTierOne#1108]
I am a fresh user of ZeroTierOne.

When I check the peers list of my private network for typing "zerotier-cli peers" in CMD window, and I find a unknown node ID in my peers list. In other words, this node ID is not added by myself, and I cannot find this ID on my networks page in www.zerotier.com. The peers list shows that the peer's client version is 1.4.1. At last, I tried to find out the geographical address which corresponds to the IP address of the node ID. I find that the geographical address is LLC (Choopa), Vultr Holdings, LosAngeles, California. 

Is there anyone encounter such a problem? Is this unknown ID a illegal user of my private network? Or it is just a regular setting of ZeroTierOne?

**Comment by glimberg** [comment]
The peers list is not a list of members connected to your same network(s).  It's a list of other nodes running ZeroTier that your node knows about.  This includes root servers and network controllers.  Root servers will be listed as `PLANET`, and network controllers have the same ID as the first 10 digits of a network you're joined to.
