### ISSUE TITLE
OSX 10.9 installation failure

### ISSUE THREAD

**Issue by M-Pixel** [zerotier/ZeroTierOne#1109]
Installation on OSX 10.9 is failing.

Attempting to install using the pkg:  When prompted to select a target volume, none of the volumes are valid installation targets.

Attempting to install using Homebrew:  `Cannot install on volume / because it is disabled`

I did some research on that error message, and it appears that most of the time it means that the minimum OSX version of the app is greater than the OSX version of the selected volume.  I wasn't able to find any specific mention of a minimum version, however the readme does state that the minimum XCode tools version is 10.8 which is less than 10.9.

**Comment by glimberg** [comment]
10.8 is the minimum version to **build** the zerotier-one daemon & command line applications.  Our installer packages require 10.10, as noted on the [download page](https://www.zerotier.com/download/)

**Comment by laduke** [comment]
Maybe try 1.2.8 or 1.2.12. I don't remember exactly. https://download.zerotier.com/RELEASES/
