### ISSUE TITLE
Connect to ZeroTier while beeing connected to a VPN

### ISSUE THREAD

**Issue by zagatta-sonah** [zerotier/ZeroTierOne#1111]
I am always using a VPN (mullvad) to browse the internet (for various reasons) but I know want to additionally use ZeroTier to access my smb shares on my server (in another physical location).
I general it works well, but I always get "TUNNELING" or "OFFLINE" when using mullvad.

Since my understanding of VPNs and the technology used in ZeroTier is limited, I don't know what kind of settings to look for, to make this work side-by-side.

**Comment by ort163** [comment]
> but I always get "TUNNELING" or "OFFLINE" when using mullvad

any decent VPN provider will block everything else - for *your* own privacy. If they allow other services then your **for various reasons** will be open to world!

> my understanding of VPNs and the technology used in ZeroTier is limited

All this means it works as it should be.
