### ISSUE TITLE
Samsung S8+ stays OFFLINE

### ISSUE THREAD

**Issue by josephdsmithjr** [zerotier/ZeroTierOne#1112]
I just downloaded ZeroTier One for android and I have configured my network properly.
However it says OFFLINE at the bottom and when I log into ZeroTier One it doesn't show it trying to connect. 

I have manually added my client to my network and it just says it's never connected.

I have tried the following:
1. Disconnected it on my phone and reconnected it (80+ times)
2. Uninstalled the app
3. Checked and unchecked Route Via ZeroTier
4. Checked and unchechecked Disable IPv6  (currently unchecked)
5. Quadriple checked the network id and it is accurate.
6. Quadriple checked the client id in zero tier that it is correct.

Yet it stays OFFLINE 1.4.4-1

Please help!

**Comment by josephdsmithjr** [comment]
UPDATE:
I disconnected my wifi and now it's ONLINE.
I'm wondering if this is a bug?
When I set this up I checked "Use cellular data" 

I have since enabled WIFI and it appears it is still working.

Very odd.

**Comment by josephdsmithjr** [comment]
UPDATE: 
Looks like it will only connect when I'm not on WIFI. :(

**Comment by ort163** [comment]
Open everything in your router (temporarily). Test it at a friend/open WiFi. Read:
https://zerotier.atlassian.net/wiki/spaces/SD/pages/6815768/Router+Configuration+Tips
