### ISSUE TITLE
Show peers name and managed IP in zerotier-cli peers / listpeers output

### ISSUE THREAD

**Issue by shvchk** [zerotier/ZeroTierOne#1116]
**Is your feature request related to a problem? Please describe.**
zerotier-cli peers / listpeers output is not really helpful to understand who are you connected to. ztaddr is not for humans.

**Describe the solution you'd like**
Would be nice to have at least an IP (inside ZT network). Even better: also show peer name as set in ZT Central (not every admin would like this enabled by default probably, so maybe have a setting network-wide to provide and/or per-peer to have access to that info).

**Describe alternatives you've considered**
Open ZT Central to get more peer info. Not too convenient.

**Comment by shvchk** [comment]
Could you please explain, even if briefly, reasons behind wontfix?

**Comment by laduke** [comment]
@shvchk 
This is a frequently asked question that should probably get an article at some point. 

The client just doesn't have that info, especially at the low 'listpeers' level. IP addresses of other nodes don't get loaded in somehow from the network/controller, but via standard IP stuff like ARP. Joining a network is like plugging your PC into a network switch. 

You'd have to have access (api token) to the my.zerotier.com network to query a specific network for ip address and name configs then merge that with the peers list.
