### ISSUE TITLE
Zerotier wont start

### ISSUE THREAD

**Issue by odechr** [zerotier/ZeroTierOne#1118]
Hi all,

been using zerotier for a while on multiple raspberry pi's, windows and android.
My last Rapsberry Pi 4B i suddenly ran into some issues and im not sure where in the process it went wrong.

I cannot connect to the network, and i also get segment fail. And now it seems like the zerotier is going in loop? and i cannot stop it. Look at the ID each time i run ps aux. it changed to a higher ID.
And it just keeps rising.

pi@raspberrypi:~ $ ps aux | grep zerotier
pi        1469  0.0  0.0   3252  1612 pts/1    S+   01:21   0:00 grep --color=auto zerotier
pi@raspberrypi:~ $ ps aux | grep zerotier
pi        1471  0.0  0.0   3252  1700 pts/1    S+   01:21   0:00 grep --color=auto zerotier
pi@raspberrypi:~ $ ps aux | grep zerotier
pi        1473  0.0  0.0   3252  1616 pts/1    S+   01:21   0:00 grep --color=auto zerotier
pi@raspberrypi:~ $

How do i stop this? Ive tried all commands.

**Comment by pkpowell** [comment]
That's the grep process ps is showing, not zerotier.
Have you checked the service status?`service zerotier-one status`
Maybe it's just a case of `service zerotier-one restart`

**Comment by odechr** [comment]
I installed the zerotier from curl -s https://install.zerotier.com | sudo bash
Got my key, added it too my network and did join network on the pi.

Thats basically all i did, and its just a raspberry pi 4 that i already have Zerotier on, i just installed a new SD card.

**sudo systemctl start zerotier-one:**

```
> pi@raspberrypi:/var/lib/zerotier-one $sudo systemctl start zerotier-one
> pi@raspberrypi:/var/lib/zerotier-onesudo zerotier-cli status
> Error connecting to the ZeroTier service: connection failed
```

Please check that the service is running and that TCP port 9993 can be contacted via 127.0.0.1.

**sudo systemctl start zerotier-one:**
```
pi@raspberrypi:/var/lib/zerotier-one $ sudo systemctl start zerotier-one
pi@raspberrypi:/var/lib/zerotier-one $ 
```

**sudo systemctl status zerotier-one:**

```
pi@raspberrypi:/var/lib/zerotier-one $ sudo systemctl status zerotier-one
* zerotier-one.service - ZeroTier One
   Loaded: loaded (/lib/systemd/system/zerotier-one.service; enabled; vendor preset: enabled)
   Active: failed (Result: signal) since Sun 2020-01-05 16:13:34 CET; 1min 56s ago
  Process: 5998 ExecStart=/usr/sbin/zerotier-one (code=killed, signal=SEGV)
 Main PID: 5998 (code=killed, signal=SEGV)


Jan 05 16:13:34 raspberrypi systemd[1]: zerotier-one.service: Service RestartSec=100ms expired, scheduling restart.
Jan 05 16:13:34 raspberrypi systemd[1]: zerotier-one.service: Scheduled restart job, restart counter is at 5.
Jan 05 16:13:34 raspberrypi systemd[1]: Stopped ZeroTier One.
Jan 05 16:13:34 raspberrypi systemd[1]: zerotier-one.service: Start request repeated too quickly.
Jan 05 16:13:34 raspberrypi systemd[1]: zerotier-one.service: Failed with result 'signal'.
Jan 05 16:13:34 raspberrypi systemd[1]: Failed to start ZeroTier One.
```
**Whats in the zerotier folder:**
```
pi@raspberrypi:/var/lib/zerotier-one $ ls
authtoken.secret  identity.secret  peers.d  zerotier-cli     zerotier-one.pid
controller.d      info             planet   zerotier-idtool  zerotier-one.port
identity.public   networks.d       start    zerotier-one     zerotier-one.service
pi@raspberrypi:/var/lib/zerotier-one $ 
```
Got no folder in systemd though. 
I have even tried to reinstall but doesnt help,

**Comment by laduke** [comment]
is the `tun` kernel module loaded?

is there any thing in that controller.d directory? 

can you try: stop the service, delete or move /var/lib/zerotier-one, start the service
this will generate a new identity.

**Comment by odechr** [comment]
> is the `tun` kernel module loaded?
> 
> is there any thing in that controller.d directory?
> 
> can you try: stop the service, delete or move /var/lib/zerotier-one, start the service
> this will generate a new identity.

Hm, loading tun manually seems to let it start up. But how can i make tun run automatically? Does it have anything to do with user rights?

pi@raspberrypi:~ $ sudo modprobe tun
pi@raspberrypi:~ $ sudo systemctl enable zerotier-one
pi@raspberrypi:~ $ sudo systemctl start zerotier-one
pi@raspberrypi:~ $ sudo systemctl status zerotier-one
* zerotier-one.service - ZeroTier One
   Loaded: loaded (/lib/systemd/system/zerotier-one.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2020-01-06 17:47:32 CET; 1s ago
 Main PID: 1050 (zerotier-one)
    Tasks: 5 (limit: 4915)
   Memory: 4.6M
   CGroup: /system.slice/zerotier-one.service
           `-1050 /usr/sbin/zerotier-one

Jan 06 17:47:32 raspberrypi systemd[1]: Started ZeroTier One.

**Comment by laduke** [comment]
`tun` typically does load automatically. It's a linux/distribution question now.

**Comment by odechr** [comment]
Update, working now! i just added tun too the modules.conf file.
Just one last comments. does this mean anything spesial? I am connected to my network anyway.

`Jan 06 18:28:28 raspberrypi zerotier-one[444]: sendto: Network unreachable`

```
pi@raspberrypi:~ $ sudo systemctl status zerotier-one
* zerotier-one.service - ZeroTier One

Jan 06 18:28:28 raspberrypi zerotier-one[444]: sendto: Network unreachable   Loaded: loaded (/lib/systemd/system/zerotier-one.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2020-01-06 18:28:28 CET; 3min 22s ago
 Main PID: 444 (zerotier-one)
    Tasks: 5 (limit: 4915)
   Memory: 7.5M
   CGroup: /system.slice/zerotier-one.service
           `-444 /usr/sbin/zerotier-one

Jan 06 18:28:28 raspberrypi systemd[1]: Started ZeroTier One.
Jan 06 18:28:28 raspberrypi zerotier-one[444]: sendto: Network unreachable
```
