### ISSUE TITLE
[REQUEST] Please provide an official ZeroTier docker image

### ISSUE THREAD

**Issue by LesterCovax** [zerotier/ZeroTierOne#1119]
* #### Is your feature request related to a problem? Please describe.

There are currently 111 ZeroTier-related images on Docker Hub, with none of them belonging to the [ZeroTier dockerhub user](https://hub.docker.com/u/zerotier).  This can cause a lot of headaches for people that see 'Docker' listed on the downloads page, as they might pick a random image to use without checking if a version mismatch, whether the `Dockerfile` was modified from the origin source before building, etc.  

It also means there's not a good way to add an Unraid app template to the [ZeroTierNAS](https://github.com/zerotier/ZeroTierNAS) repo, as you'd be relying on a third party's docker image.  Having to double/triple check all these things to install a security-focused app is not ideal.
****
* #### Describe the solution you'd like

As mentioned, there's already a [Dockerfile](https://github.com/zerotier/ZeroTierOne/blob/master/ext/installfiles/linux/zerotier-containerized/Dockerfile) in the repo, so it would be nice if the container image creation/versioning/hosting were added to the existing CI pipeline.  That way there would be an image available with version/build parity to other releases, and it could be trusted.
****
* #### Describe alternatives you've considered

The other alternatives already exist (i.e. building/hosting a copy ourselves), which work, but are non-ideal IMO due to my previous concerns.
****
* #### Additional context

This process *could* be added to the `Jenkinsfile` (not sure how you're handling CI behind the scenes though), but adding a trigger in docker hub to build on a new release would be easiest.  Would just need to specify the `Build Context` since the `Dockerfile` isn't in the root directory.  Here are the triggers/regexes I use to set the image version (and `latest`) tags based on the `v1.2.3` naming scheme.  
*(Apologies if you already know all of this)*

<img src="https://user-images.githubusercontent.com/34850610/71767072-bc487b80-2ed5-11ea-956c-ba83a311ccc2.png" height=100x>

**Comment by reesericci** [comment]
yes please!

**Comment by diwu1989** [comment]
+1 please make sure to provide official image as part of the 1.6.0 release!

**Comment by PMExtra** [comment]
I found zerotier has joined [Docker Hub](https://hub.docker.com/u/zerotier) in Sep 2015, and it published [zerotier/zerotier-containerized](https://web.archive.org/web/20170805103802if_/https://hub.docker.com/r/zerotier/zerotier-containerized/) several years ago. I don't know why these all were removed.

I'm really looking forward a official zerotier image to build my moon node.

**Comment by joseph-henry** [comment]
Closing due to age. Please let us know if there's an issue with the current container.

**Comment by reesericci** [comment]
Solved! https://hub.docker.com/r/zerotier/zerotier
