### ISSUE TITLE
ZT for Android connects, but no apps use it

### ISSUE THREAD

**Issue by Haniver** [zerotier/ZeroTierOne#1120]
Hi,
I connect to ZeroTier One on my Samsung S4 and everything seems right:

- the status shows "OK"
- the bottom reads "ONLINE"
- the top bar shows an icon "VPN"
- VPN under settings shows ZeroTier One as connected
- I can ping the managed IP address assigned to the device from another device, and get a response

Still, no apps in the phone connect through the VPN: whatismyip.com retrieves my real IP and VRidge searches for devices in my real LAN. Please help.

**Comment by glimberg** [comment]
ZeroTier is not a traditional "privacy" VPN service.  If you wish to route all of your network traffic via ZeroTier, you'll need to configure your own gateway machine, and also some additional configuration.

https://zerotier.atlassian.net/wiki/spaces/SD/pages/7110693/Overriding+Default+Route+Full+Tunnel+Mode

**Comment by Haniver** [comment]
I don't understand. If no traffic is routed through ZeroTier, what's the point?

**Comment by glimberg** [comment]
Traffic to other devices joined to the network are set via ZeroTier, but as I said, it is not a traditional VPN service.  It's more of a software defined network backplane.

**Comment by Haniver** [comment]
Ok, so how do I make a specific Android service connect through ZeroTier?

**Comment by glimberg** [comment]
In order to communicate via ZeroTier, both sides of the connection must be using ZeroTier.  You'd then communicate via the ZeroTier assigned IP addresses.
