### ISSUE TITLE
Zerotier managed route loss when roaming in>out of managed route network

### ISSUE THREAD

**Issue by HunterDG** [zerotier/ZeroTierOne#1122]
**Describe the bug**
If a ZeroTier client's parent/upstream interface acquires an IP in same subnet as a ZT-defined managed route, ZT appears to remove the conflicting route.  Fine, (but not necessary?), but ZT client **does not re-add the route** if the parent subsequently acquires an IP in a different subnet (if parent roams **back out** of the 'managed route' network)

**Use Case**
Laptop that roams into/out of (work/home) the managed route subnet (work).  When I get home after being at the office, I have to cycle the ZT connection to get the managed route back.

**To Reproduce**
1. Connect **remotely** to a ZT network with managed route.
2. Observe successful connectivity (to remote subnet via managed route)
3. Roam ZT client/parent **into** the managed route subnet (parent interface is assigned/acquires IP inside ZT-defined managed route subnet)
4. Observe continued successful connectivity to "remote" (now local) subnet (ZT managed route is removed from parent's routing table)
5.  Roam ZT client/parent **out of** the managed route (parent interface is assigned/acquires IP **not** in the ZT-defined managed route subnet)
6. **ERROR: Observe loss of connectivity to now-remote (again) subnet (ZT managed route is still missing from parent's routing table)**
7. Disconnect/reconnect ZT network
8. Observe re-establishment of connectivity to remote subnet (ZT managed route is re-added to parent's routing table)
9. Get back to work.

**Expected behavior**
Connectivity to "remote" (via managed route) subnet remains successful/automatically re-establishes if parent interface roams into/out of the managed route subnet (no real need to remove the conflicting route in the first place if parent interface finds itself in the same subnet as ZT-defined managed route, except perhaps to avoid routing overhead - trivial for my use-case)

**Environment**
 - OS: macOS Catalina 10.15.2
 - ZeroTier Version 1.2.12

**Comment by laduke** [comment]
Hi for a work around, maybe the zerotier managed subnet one bigger, for example use /23 instead of /24
