### ISSUE TITLE
ZeroTier continues sourcing path discovery frames from deprecated IPv6 addresses

### ISSUE THREAD

**Issue by cwichura** [zerotier/ZeroTierOne#1124]
**Describe the bug**

At least on Linux systems, when temporary ("privacy extensions") IPv6 addresses are enabled, ZeroTier continues to send path discovery messages from the deprecated (== primary lifetime expired) IP addresses.  ZeroTier should only source messages from non-expired IPv6 addresses.

Sourcing from these expired IPv6 entries means ZeroTier is sending ~7x the discovery frames as it needs to.  These also go to the ZeroTier root directory servers on the Public Internet, so are a needless waste of metered Internet bandwidth.  And during rolls to a new IPv6 prefix (as we just underwent), means ZeroTier sources from IP addresses that aren't even accessible in any way.

**To Reproduce**
Run zerotier on a Linux system with IPv6 privacy addresses enabled.  Wait a couple days so you get some deprecated addresses in your address table.  Run tcpdump filtering on port 9993 and observe ZeroTier sourcing path discovery from the expired addresses.

**Expected behavior**
ZeroTier should not source path discovery from expired IPv6 addresses.

**Desktop (please complete the following information):**
 - OS: Linux
 - OS/Distribution Version: CentOS 7 and 8
 - ZeroTier Version 1.4.6

**Comment by adamierymenko** [comment]
It sounds like it should only bind to the primary IP as this is the long-lived address.

**Comment by cwichura** [comment]
Yes, agree -- having it ignore all temporary addresses entirely would be even better.  But at a minimum, it needs to ignore expired temporary addresses.

**Comment by joseph-henry** [comment]
I'm pretty sure this has been fixed by one of @glimberg's patches. If you're still seeing this let us know and we can re-open. Thanks.

**Comment by glimberg** [comment]
> I'm pretty sure this has been fixed by one of @glimberg's patches. If you're still seeing this let us know and we can re-open. Thanks.

correct.  this was included in the 1.8.x series
