### ISSUE TITLE
How to build for ARM Thin client on Ubuntu 10.04?

### ISSUE THREAD

**Issue by v-marinkov** [zerotier/ZeroTierOne#1125]
I am trying to install Zerotier on a Dell Wyse 3010 T50 (ARM - `armel`) which runs Ubuntu 10.04.1 LTS. The latest versions of the compilers from the repos are as follows:

- G++ 4.4
- clang 2.7

I understand these are too old for Zerotier but what could be some workarounds to using any albeit outdated version of Zerotier?
Thanks

EDIT:
I think I can get GCC 4.8.1. Would this facilitate some workaround?

**Comment by glimberg** [comment]
Sorry we cannot support a 10 year old operating system.
