### ISSUE TITLE
Layer 2 Bridging of Ethernet and ZeroTier Networks on Linux 

### ISSUE THREAD

**Issue by huangsijun17** [zerotier/ZeroTierOne#1126]
Some questions about the ZeroTier Knowledgebase page: [Layer 2 Bridging of Ethernet and ZeroTier Networks on Linux
](https://zerotier.atlassian.net/wiki/spaces/SD/pages/7471125/Layer+2+Bridging+of+Ethernet+and+ZeroTier+Networks+on+Linux)
The wiki ask me to install bridge-utils.

but CentOS 8 [remove the package](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/considerations_in_adopting_rhel_8/index#removed-packages_changes-to-packages).

**Comment by glimberg** [comment]
You'll have to figure out the new method of creating a bridge interface on CentOS 8, then.

**Comment by mishamosher** [comment]
@huangsijun17 I've managed to do it in CentOS 8!

Let's suppose:
- Network ID: 88f777c223b74682
- Network: 10.123.123.0/24
- Member IP: 10.123.123.1
- ZT interface name: ztaha777ok
- Interface to bridge: ens123

Join and configure the ZT network in CentOS 8:
- zerotier-cli join 88f777c223b74682
- zerotier-cli set 88f777c223b74682 allowManaged=false

Set up your network in the ZT website:
- https://my.zerotier.com/network/88f777c223b74682
- Go to the **Members** section
- In here the member must have both **Allow Ethernet Bridging** and **Do Not Auto-Assign IPs** enabled

Set up your bridge in CentOS 8:
- nmcli connection add type bridge ifname br-zt ipv4.addresses 10.123.123.1/24 ipv4.method manual
- nmcli connection add type tun mode tap ifname ztaha777ok master br-zt slave-type bridge
- nmcli connection add type bridge-slave master br-zt ifname ens123
- It may be required to remove other connections where ens123 is in use. Example: nmcli connection delete ens123

Finally, restart the NetworkManager service:
- systemctl restart NetworkManager

You can always check the generated configurations in these folders:
- /etc/NetworkManager/system-connections
- /etc/sysconfig/network-scripts

The trickiest part is that nmcli refuses to bridge non-ethernet interfaces if you don't specify its type. This is why **ztaha777ok** is added with a **type tun mode tap** specific type, but **ens123** is added as a generic **bridge-slave**.

There is a very complete and exhaustive documentation about **nmcli** here: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_and_managing_networking/index

**Comment by IvanBoykov** [comment]
Hi! I try to follow this, but after reboot network manager creates tun devise themself. Then zerotier starts and ignore this device, instead it create new tun with different last letter. So, i have one interface created by network manager in down state and another working but with different name from zerotier. How you deal with this?

**Comment by laduke** [comment]
https://docs.zerotier.com/bridging/

this is the most recent docs. I'm not sure what you need to do about network manager. Probably tell it to ignore certain interfaces.
