### ISSUE TITLE
Segment Violation on Rasbbian buster

### ISSUE THREAD

**Issue by jjsarton** [zerotier/ZeroTierOne#1127]
I have upgrated an raspbian to buster.
Lauching zerotier-one 1.4.6 end with a segment violation.
The reason what that the tun module what not loaded.
After loading the module tun all work as expected and appending the /etc/momodules-load.d/module.conf file (really /etc/modules) with tun zerotier-one work after a reboot.
If the tun module can't be opened, please report this within the log output and finish zerotier-one properly (without SEGV)

**Comment by adamierymenko** [comment]
Hmm... sounds like it's crashing instead of reporting an error as it should. I *think* I know what this is. In any case 2.0 rewrites a lot of that service management code, so I am going to leave it open but say this is fixed.

**Comment by joseph-henry** [comment]
Closing due to age. If you still see this issue in `1.6.5` please re-open.
