### ISSUE TITLE
Managed routes not set on macOS Catalina on ZT's first run

### ISSUE THREAD

**Issue by billstanden** [zerotier/ZeroTierOne#1129]
On the first / on boot startup of ZeroTier, managed routes are not added to the routing table on macOS Catalina 10.15.2 and traffic obviously does not route as a result.

Going to the ZeroTier client in the menu bar, toggling off the network and toggling it back on loads the route, it becomes visible in netstat and traffic begins to flow as expected.  This needs to be repeated every boot.

OS: macOS 10.15.2
ZeroTier version: 1.4.6

Problem confirmed across two network configurations.

**Comment by laduke** [comment]
Hi, thanks for writing. I've just tried rebooting on the same os and zerotier version, and could not reproduce the issue :/  Maybe it doesn't happen 100% of the time? 
I've seen something similar, but when I wake up from sleep; I don't reboot very often. Does it take a few seconds for the "toggling off the network" step to finish? 

Can you capture the output of `zerotier-cli info; zerotier-cli listnetworks;` while it's happening?

**Comment by billstanden** [comment]
Output before a toggle

```
200 info 2d9e9a7748 1.4.6 ONLINE
200 listnetworks <nwid> <name> <mac> <status> <type> <dev> <ZT assigned ips>
200 listnetworks 35c192ce9b81a7ff personal fe:8a:1f:01:b9:da OK PRIVATE feth2016 fd35:c192:ce9b:81a7:ff99:932d:9e9a:7748/88,fcae:4035:312d:9e9a:7748::1/40,172.27.0.69/16
200 listnetworks a09acf0233724a14 work 16:67:ec:a9:75:87 OK PRIVATE feth3524 fda0:9acf:233:724a:1499:932d:9e9a:7748/88,fc93:e885:162d:9e9a:7748::1/40,10.144.123.69/16
```

And after a toggle:

```
200 info 2d9e9a7748 1.4.6 ONLINE
200 listnetworks <nwid> <name> <mac> <status> <type> <dev> <ZT assigned ips>
200 listnetworks 35c192ce9b81a7ff personal fe:8a:1f:01:b9:da OK PRIVATE feth2016 fd35:c192:ce9b:81a7:ff99:932d:9e9a:7748/88,fcae:4035:312d:9e9a:7748::1/40,172.27.0.69/16
200 listnetworks a09acf0233724a14 work 16:67:ec:a9:75:87 OK PRIVATE feth3524 fda0:9acf:233:724a:1499:932d:9e9a:7748/88,fc93:e885:162d:9e9a:7748::1/40,10.144.123.69/16
```

And yes, the toggle off takes a couple of seconds the first time.  It's instant there after.

**Comment by n9yty** [comment]
Not just Catalina. We have mostly Mojave systems, and I see that when they reboot they join the ZT network, but the routes configured in the ZT Web GUI are not pushed. If they leave/re-join the network, the routes are added.

**Comment by laduke** [comment]
this is probably fixed. it's too old to debug at this point.

**Comment by alexacallmebaka** [comment]
Still having this issue, on `zerotier-cli` version `1.14.2` and MacOS Sequoia `15.1.1`.

**Comment by kjetilpp** [comment]
Can confirm, still a problem on Sequoia
