### ISSUE TITLE
Installer does not work with busybox (was: installer failed on Synology)

### ISSUE THREAD

**Issue by FernandoMiguel** [zerotier/ZeroTierOne#113]
> bash
bash-3.2# ./ZeroTierOneInstaller-linux-x86 
*** ZeroTier One install/update ***
grep: invalid option -- 'b'
BusyBox v1.16.1 (2014-05-29 11:29:12 CST) multi-call binary.

Usage: grep [-HhnlLoqvsriFE] [-m N] [-A/B/C N] PATTERN/-e PATTERN.../-f FILE [FILE]...

Search for PATTERN in FILEs (or stdin)

Options:
	-H	Add 'filename:' prefix
	-h	Do not add 'filename:' prefix
	-n	Add 'line_no:' prefix
	-l	Show only names of files that match
	-L	Show only names of files that don't match
	-c	Show only count of matching lines
	-o	Show only the matching part of line
	-q	Quiet. Return 0 if PATTERN is found, 1 otherwise
	-v	Select non-matching lines
	-s	Suppress open and read errors
	-r	Recurse
	-i	Ignore case
	-F	PATTERN is a literal (not regexp)
	-E	PATTERN is an extended regexp
	-m N	Match up to N times per file
	-A N	Print N lines of trailing context
	-B N	Print N lines of leading context
	-C N	Same as '-A N -B N'
	-e PTRN	Pattern to match
	-f FILE	Read pattern from file

./ZeroTierOneInstaller-linux-x86: line 55: [: : integer expression expected
expr: syntax error
./ZeroTierOneInstaller-linux-x86: line 60: [: : integer expression expected
Extracting files...
tail: invalid number ''

gzip: stdin: unexpected end of file
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
Archive extraction failed, cannot find zerotier-one binary in "/var/lib/zerotier-one".

this is on a Synology NAS with busybox and /bin/bash alias /opt/bin/bash

**Comment by adamierymenko** [comment]
Closing as a won't fix for now -- busybox distributions should probably get their own packages rather than using the binary installer. Some of the grip switches used by the installer are necessary and simply aren't available in busy box grep.
