### ISSUE TITLE
Cannot ping or ssh between devices in my zerotier network

### ISSUE THREAD

**Issue by unfa** [zerotier/ZeroTierOne#1135]
I'm new to ZeroTier. I've been using Linux as my main OS for over a decade now.
Right now I run Manjaro as my main distribution, and I have installed zerotier-one from Arch repositories.

I've created a network at my.zerotier.com, I've connected my phone (OnePlus 5T) and PC (running Manajro).

They are both seen in the my.zerotier.com panel, I have authenticated them and they have assigned IPs in the zerotier network:

![image](https://user-images.githubusercontent.com/491704/74063032-e4089300-49ef-11ea-92d7-efba741d3550.png)

However I am unable to create any kind of network communication between the two devices.
I've added custom IPs to make things easier for me, but I can't ping any of the addresses, even the ones that should loopback to the machine I'm pinging from (ping the PC's zerotier address from the PC itself fails just like anything else)

I've tried pinging from the PC to the phone - it'll just hang in there and never transmit any packets.
SSH connections from the phone to the PC result in ETIMEDOUT.

To make sure this is not the problem I have temporarily reduced my network rules to this using comments:

```
{
 "rules": [
  {
   "type": "ACTION_ACCEPT"
  }
 ],
 "capabilities": [],
 "tags": []
}
```

In my PC I can see all seems fine:
```
# zerotier-cli info
200 info e37####### 1.4.6 ONLINE
```
Even though the service status says this:

```
# systemctl status zerotier-one
● zerotier-one.service - ZeroTier One
   Loaded: loaded (/usr/lib/systemd/system/zerotier-one.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2020-02-07 20:50:54 CET; 27min ago
 Main PID: 520803 (zerotier-one)
    Tasks: 4 (limit: 38442)
   Memory: 6.2M
   CGroup: /system.slice/zerotier-one.service
           └─520803 /usr/bin/zerotier-one -U

lut 07 20:50:54 unfa-desktop systemd[1]: Started ZeroTier One.
lut 07 20:50:54 unfa-desktop zerotier-one[520803]: ERROR: unable to configure virtual network port: could not open TUN/TAP device: No such file or directory
```

I have found some solutions to this, but they didn't seem to work in my case. I've added the -U switch in the service config file:

```
# cat /lib/systemd/system/zerotier-one.service
[Unit]
Description=ZeroTier One
After=network-online.target
Wants=network-online.target

[Service]
ExecStart=/usr/bin/zerotier-one -U
Restart=always
KillMode=process

[Install]
WantedBy=multi-user.target
```

I am able to establish a working SSH connection from my phone to my PC while using the local WLAN network with ease.

What am I doing wrong? I am not a networking expert, but I guess I am not a total noob either.

**Comment by laduke** [comment]
i'm guessing

`modprobe tun`

**Comment by unfa** [comment]
You are right, I didn't have that module loaded. I also didn't see any zerotier adresses in `ip addr`.
I've just upgraded my kernel, so I'll reboot and see if I can load that module.
Right now it gives me this:

```
# modprobe tun
modprobe: FATAL: Module tun not found in directory /lib/modules/5.4.14-2-MANJARO
```

**Comment by joseph-henry** [comment]
Side note: See this thread if you're still having issues loading the kernel module, you mist want to use `insmod`:

https://superuser.com/questions/497245/how-to-load-tun-module-in-linux
