### ISSUE TITLE
Failed to compile properly in zerotieronesdk.sln, missing file: cluster.cpp

### ISSUE THREAD

**Issue by alvinsunalvin** [zerotier/ZeroTierOne#1136]
Failed to compile properly in zerotieronesdk.sln, missing file: cluster.cpp

**Comment by glimberg** [comment]
That's an old one-off project and not valid at this point.  You should be using `ZeroTierOne.sln` to build with Visual Studio

**Comment by alvinsunalvin** [comment]
Thank you very much,We should delete this file!
