### ISSUE TITLE
Unexpected high cpu usage in alicloud with high concurrency

### ISSUE THREAD

**Issue by hjweddie** [zerotier/ZeroTierOne#1137]
**Describe the bug**
Maybe it is not a bug, I just do not understand why.
I create a zerotier private network and create four vps instance in aws and alicloud, two t2.medium in aws and two ecs.t6-c2m1.large  instance in alicloud.  all of these four instances join the same zerotier network just created before.

I use iperf3 command, as below, to test zerotier cpu usage with same bandwidth between two instance in the same vpc
```
iperf3 -4 -b 1M -c 192.168.1.35 -t 6000 -P 100
iperf3 -4 -b 50M -c 192.168.1.35 -t 6000 -P 2
```

In both aws and alicloud, I found the following phenomenon but do not know the reason 
1. zerotier run with much higher cpu usage with higher concurrency
2. with 100 concurrency, alicloud run with more than 100% cpu, but 20% in aws

I do not know why 

**To Reproduce**
1. Create a Network with default config
2. Install zerotier-one using 'curl -s https://install.zerotier.com/ | bash'
3. create four ubuntu 18.04 instances (2 CPUs) in the same vpc,   two in aws, other two in alicloud
4. use iperf3 command (as below) to test zerotier cpu usage, using zerotier network ip
```
iperf3 -4 -b 1M -c 192.168.1.35 -t 6000 -P 100
iperf3 -4 -b 50M -c 192.168.1.35 -t 6000 -P 2
```

**Expected behavior**
with 100 concurrency in alicloud, zerotier cpu usage shoud be abount 20%, not more than 100%, which is too high

**Screenshots**
None

**Desktop (please complete the following information):**
 - Ubuntu 18.04
 - ZeroTier Version: 1.6.4
 
**Smartphone (please complete the following information):**
None

**Additional context**
Default zerotier configurations

**Comment by CsHeng** [comment]
and HuaweiCloud same as above

**Comment by joseph-henry** [comment]
Closing due to age, but if this is still an issue with our current version `1.6.5` please re-open and let us know.

We would be interested in knowing the exact CPU architecture of the boxes used in alicloud or huaweicloud.
