### ISSUE TITLE
Aliasing the zt interface and localhost

### ISSUE THREAD

**Issue by jamiesonbecker** [zerotier/ZeroTierOne#1138]
**Is your feature request related to a problem? Please describe.**
Currently, you need to modify private daemons' config files to point at the local zt local IP uniquely.

In other words, when building a cluster, each daemon on each host (for example, memcached, redis, etc) need to have customized configuration files for each daemon to teach it which interface to bind to rather than localhost.

**Describe the solution you'd like**
If it were possible to bridge or alias zt interface and localhost, you could bind daemons to localhost and they'd be available across the meshed network.

**Describe alternatives you've considered**
A perhaps better and more explicit alternative would be to have ZT alias to a non-routing localhost IP that is consistent rather than all localhost IPs, such as 169.254.98.97 or 127.99.98.97.

**Comment by glimberg** [comment]
If you configure your programs to listen on 0.0.0.0, then by default they'll also be listening on the ZeroTier interface.

**Comment by jamiesonbecker** [comment]
For a private daemon, that would suboptimal. For example, if you wanted to allow Redis (or any other database or private internal service) access from your zerotier network only without global access.

**Comment by glimberg** [comment]
You can use some a DevOps tools (Chef, Puppet, etc.) to manage the configuration of your services and configure your services to determine and use the ZT assigned IP address.  What you're asking is 1) likely not possible, and 2) outside the scope of ZeroTier

**Comment by jamiesonbecker** [comment]
Yes. Agreed. It's likely not (easily) possible and possibly outside the scope of zerotier. But, if it is possible for Zerotier to bind to a private localhost IP, then it would be a huge benefit for both cluster building and the consumption of services. For example, you have to have your application code connect to the unique, custom ZT IP address instead of a standardized localhost sort of address.

**Comment by jamiesonbecker** [comment]
Well, that was abrupt.

**Comment by jamiesonbecker** [comment]
> 3) would likely break lots of things by attempting to bridge to the lo interface

That's why I proposed an alternative which would simply provide an alias interface with a consistent IP.
