### ISSUE TITLE
Build process failed on Solus

### ISSUE THREAD

**Issue by festum** [zerotier/ZeroTierOne#1140]
**Describe the bug**

```sh
(master ✓) ZeroTierOne make
ln -sf zerotier-one zerotier-idtool
ln: failed to create symbolic link 'zerotier-idtool': Operation not permitted
make: *** [make-linux.mk:298: zerotier-idtool] Error 1
```

Issue might caused by the different folder structure in Solus Linux.

**Comment by joseph-henry** [comment]
That doesn't really have anything to do with folder structure, it just seems like you aren't allowed to create symbolic links there for whatever reason. Tried using `sudo`? Have you checked on the Solus forums about this issue?
