### ISSUE TITLE
Set network speed on Synology ZeroTier

### ISSUE THREAD

**Issue by zajnic** [zerotier/ZeroTierOne#1142]
I have installed ZT package on Synology DS1618 and joined the network. It create a new network interface with 10Mbps Full Duplex. Tried iperf3 speed test, only get around 10Mbps - so it was limited by the configured network speed. Is that a way to set the speed on Synology Zerotier?

**Comment by TheAsian1337** [comment]
I have the same issue just on ubuntu server. Tried setting it through ethtools and still was not successful on changing the speed.

**Comment by laduke** [comment]
https://zerotier.atlassian.net/wiki/spaces/SD/pages/7471187/Why+is+the+ZeroTier+Virtual+Network+Port+Running+at+100mbps

**Comment by glimberg** [comment]
> https://zerotier.atlassian.net/wiki/spaces/SD/pages/7471187/Why+is+the+ZeroTier+Virtual+Network+Port+Running+at+100mbps

the same applies on any other OS

**Comment by laduke** [comment]
https://zerotier.atlassian.net/wiki/spaces/SD/pages/6815768/Router+Configuration+Tips
