### ISSUE TITLE
Strange connection issue

### ISSUE THREAD

**Issue by graphixillusion** [zerotier/ZeroTierOne#1146]
Hi there. I just got a strange issue which i'm going to describe. It's been a while that i have setup a private network with 3 machines. Everything always worked fine until this strange issue. Let's name the three machines A, B, C. Suddenly this happens:

A can ping C (and viceversa)
B can ping C (and viceversa)
**A can't ping B (and viceversa)**

All three machines are running Windows 10 1909. I tried to reboot both A and B, restart the zerotier services, change and delete A and B ips in the controller, disable and re-enable A and B in the controller. Nothing of those worked. I managed to solve this issue following those steps:
1. delete hosts A and B completely from the controller, 
2. unistall zerotier on both A and B; 
3. install again the zerotier client after a reboot;
4. assign again the same IP used before to A and B. 

What could be happened? Is there anything else to check before do the uninstall/reinstall trick?
Thank you!

**Comment by LiyuanLucasLiu** [comment]
them here, reboot solve the issue for me.

**Comment by dfc643** [comment]
same here, https://zerotier.atlassian.net/servicedesk/customer/portal/1/ZT-2212?created=true

**Comment by jbaptisteblot** [comment]
I have the same issue with 2 computers running Linux and Zerotier 1.4.16.

However the drops I have will only for a few minutes/hours and it will comeback without any action.

**Comment by graphixillusion** [comment]
Today it happens again. From my research it seems that it can't ping some machines when those machines have many PLANET peers with the "RELAY" status. When i can get the "DIRECT" status everything seems to work good. Now the question is: is there any way to connect again without changing any configuration for trying to make the DIRECT peers connection works?

**Comment by graphixillusion** [comment]
Today it happens again, i can't ping one machine but everything is online. This is very annoying sadly...

**Comment by unquietwiki** [comment]
@graphixillusion @jbaptisteblot @LiyuanLucasLiu @dfc643 I'm going over our GitHub issues in preparation for our pending 1.6.0 release; that should hopefully take care of a few things. If you're still having this issue ATM, can you please check the following & let us know otherwise so we can try to catch it? Thanks!

* https://zerotier.atlassian.net/wiki/spaces/SD/pages/521011201/Windows+Troubleshooting -> Walkthrough of common Windows issues.
* https://www.reddit.com/r/zerotier/?f=flair_name%3A%22Gaming%22 -> A lot of gamers & Windows users have figured out some stuff.
* https://discuss.zerotier.com/ -> Official Discuss forum

**Comment by graphixillusion** [comment]
@unquietwiki for now the only way to mitigate this is stop the services for about 10 mins and restart it. This problem is different from the ones you linked in the other forums. Let's see with the new 1.6.0 version when it will comes out.

**Comment by unquietwiki** [comment]
@graphixillusion Acknowledged. I'll make the rounds again when that's ready (days/weeks on that). Thank you for your patience.

**Comment by laduke** [comment]
@graphixillusion sorry if we've asked you before, but what kind of router is that windows machine behind? just curious. 

We've seen the multiply paths thing happen, but not to where it stops communication. 

some work-around guesses:
- stop zerotier, delete the peers.d folder, start zerotier 
- disable port mapping by creating a local.conf file https://github.com/zerotier/ZeroTierOne/tree/master/service

peers.d and local.conf go in "\ProgramData\ZeroTier\One"

**Comment by graphixillusion** [comment]
@laduke my router is a ISP branded one, maded by Sercom.

**Comment by unquietwiki** [comment]
@graphixillusion https://discuss.zerotier.com/t/asymmetric-routing-problem-with-site-to-site/176 this showed up on our discussion board today. Might be related?

**Comment by graphixillusion** [comment]
@unquietwiki nope, it seems a different issue. In my case, the zerotier client failed to connect to the planets after my internet goes down: when internet is back, the only way to make it works again is do what i already described (stop zerotier service for 10 mins and then restart)

**Comment by unquietwiki** [comment]
@graphixillusion Thanks; wanted to see if that was a possibility.

**Comment by graphixillusion** [comment]
@laduke Today i tried the workaround you suggested:
1. stop zerotier service
2. delete peers.d folder
3. start zerotier service without any waiting time
Nothing: doesn't work. Currently the only way that it works everytime is to stop the service for about 10 min, then restart it.

**Comment by laduke** [comment]
Thanks for trying. 

here's the local.conf 

    {"settings": {"portMappingEnabled": false}}



This may not be suitable for your environment if it's relying on UPnP. 

Does rebooting the router work around the issue? Don't worry about testing this if it's disruptive!

**Comment by graphixillusion** [comment]
@laduke nope, reboot the router doesn't fix the problem.

**Comment by graphixillusion** [comment]
I'm testing the newly 1.6.1. I will report if something is changed.

**Comment by graphixillusion** [comment]
Just want to report that the problem is still present in the last 1.6.2 version.
