### ISSUE TITLE
[BUG] Firewall settings are wrong

### ISSUE THREAD

**Issue by o0Julia0o** [zerotier/ZeroTierOne#1150]
the firewall 9993 tcp and upd are set automatically during the installation if choosen. But ping doesnt work. You have to deactivate the complete firewall to make a ping possible. Something is set wrong - port 9993 ist not the wanted one from zero-tier(or not only).

**Comment by glimberg** [comment]
You must set the network adapter to "Private"

**Comment by laduke** [comment]
https://zerotier.atlassian.net/wiki/spaces/SD/pages/29130754/I+Can+t+Ping

**Comment by o0Julia0o** [comment]
> You must set the network adapter to "Private" network. 
How can i do this?
