### ISSUE TITLE
Question: When zeritier runs on a machine that has more that one ip addresses, 

### ISSUE THREAD

**Issue by netjune** [zerotier/ZeroTierOne#1151]
which ip address is the VL ip address mapped to?

For example, there is a machine A which has following ip addresses:
```
192.168.1.11
192.168.1.12
192.168.1.13
10.147.20.100(the VL ip address)
```

If I run `telnet 10.147.20.100 23` on another machine B, then which ip address on A will recieve the packet?

**Comment by bradleydiggs** [comment]
If the ZeroTier IP address of machine A is 10.147.20.100, and machine B is within the same ZeroTier subnet (and by that definition has a route to machine A over that ZeroTier network/subnet) then running `ping 10.147.20.100` or `telnet 10.147.20.100 23` from machine B will route to that particular IP address on machine A across the network established by ZeroTier.  If the machines are both in the same physical local LAN and also attached to the same ZeroTier subnet, it would use whichever IP address you attempt to reach.  For example, if pinging the local LAN IP, it will route accordingly across the LAN to that IP address.  If pinging the ZT IP, it will route from ZT address to ZT address using the link ZeroTier has setup between the systems.

**Comment by laduke** [comment]
`zerotier-cli peers` will show you the path it's using to a peer

**Comment by netjune** [comment]
Thank.
