### ISSUE TITLE
Question: Why sometimes speed ​​becomes  0.00 bits/sec

### ISSUE THREAD

**Issue by haojie06** [zerotier/ZeroTierOne#1154]
Hello, When I want to transfer large files, occasionally the speed becomes 0 and it will last for a while, I use iperf3 to test.
![image.png](https://i.loli.net/2020/03/07/sBDJhmRFOL1xjKq.png)
Why does this happen？

**Comment by KrisCris** [comment]
Hmmm, so how did you solve this?
