### ISSUE TITLE
Completely Inaccessible to Internet after Installation 

### ISSUE THREAD

**Issue by BlueCocoa** [zerotier/ZeroTierOne#1155]
**Alternative, faster ways to get help**
If you have just started using ZeroTier, here are some places to get help:
- my.zerotier.com has a _Community_ tab. It's a live chat with other users and the developers. 
- [ZeroTier Knowledge Base](https://zerotier.atlassian.net/wiki/spaces/SD/overview)
- www.zerotier.com has a Contact Us button
- email contact@zerotier.com

**Describe the bug**
Completely Inaccessible to Internet after Installation. No process can access to Internet. Safari and Chrome reported

```
Protocol family is not supported.
```

**To Reproduce**
1. Create a Network '...'
2. Install zerotier-one '....'
3. See error

**Expected behavior**
Accessible to Internet even after installation. 

**Screenshots**
If applicable, add screenshots or console output to help explain your problem.

**Desktop (please complete the following information):**
 - OS: macOS
 - macOS 10.14.6
 - ZeroTier Version 1.4.6
 - Hardware MacBook Pro 2018

**Additional context**
- ZeroTier Network Configuration: IPv4 and IPv6 auto assign
- Router Config: default
- Firewall Config: No firewall
- General Network Environment: Home

**Comment by laduke** [comment]
Similar to #1104 ?

**Comment by glimberg** [comment]
Or, does your ZeroTier IP address space overlap/conflict with your local LAN address space?

**Comment by BlueCocoa** [comment]
> Similar to #1104 ?

Yes, after reading the #1104 issue, I think it's the same glitch. 

Besides, `sudo zerotier-cli status` said that it was requesting an IP address, but it never succeeded.


> Or, does your ZeroTier IP address space overlap/conflict with your local LAN address space?

My local LAN address space is `10.0.1.0/24`, and I set IPv4 range as `10.2.0.0/16` in ZeroTier.
