### ISSUE TITLE
META: how can we help get this ready for a bunch of users with the COVID-19 WFH push?

### ISSUE THREAD

**Issue by unquietwiki** [zerotier/ZeroTierOne#1156]
I know 2.0's been in the works for a while. Now COVID-19 is forcing a lot of folks to work from home, and this is the VPN I've been recommending heavily on Reddit of late. What can we all be doing on here to ensure we can ramp up use of this, and have that be a successful push; for places that might not have good VPN setups right now, or might be interested in changing?

**Comment by unquietwiki** [comment]
Following up on this: some networking guys in MS put this together. https://stubarea51.net/2020/03/10/remote-workers-rapid-and-cost-effective-vpn-scale-with-zerotier-opnsense-and-frrouting/

**Comment by unquietwiki** [comment]
https://www.deepcode.ai/ supports C & C++ code now. **edge** branch of code currently comes up with 16 warnings; 13 C++, 2 Java, 1 JS.

**Comment by adamierymenko** [comment]
The `edge` branch is pre-2.0 and under heavy development. Use `master` or `dev`.

**Comment by unquietwiki** [comment]
@adamierymenko if we make fixes against master or dev, will they be brought into edge? Is there any plan for a 1.4.8 or 1.4.10 release?

**Comment by joseph-henry** [comment]
Any fixes made right now in dev could still make it into the pre-2.0 master. After 2.0's release we will likely still add minor bug fixes to the 1.4.X series but no further feature development will occur.

**Comment by ziyifeihu** [comment]
Hi，when will  the version 2.0 be released?

**Comment by unquietwiki** [comment]
Hey @ziyifeihu: 2.0 is tentatively set for end-of-year / start-of-next; the team is working diligently on that & other issues!

**Comment by unquietwiki** [comment]
@adamierymenko @joseph-henry closing issue, since I'm on the team now! 💯
