### ISSUE TITLE
Request moon node to support DDNS

### ISSUE THREAD

**Issue by Jonnyan404** [zerotier/ZeroTierOne#1158]
Is your feature request related to a problem? Please describe.

I have a dynamic IP in my home, This ip often changes.
but the moon must have a fixed IP, can you support domain name instead of a fixed IP config?

Describe the solution you'd like

the moon.json looks like this:

"stableEndpoints": ["china.xxx.com/9993"]

**Comment by adamierymenko** [comment]
That's not really possible in the current system. Closing since 2.0 changes how this works, though roots still need to have static IPs.

**Comment by adamierymenko** [comment]
Note that we deliberately do not depend on DNS for numerous reasons including the possibility that DNS would be configured to itself go over ZeroTier and security issues.

**Comment by sbilly** [comment]
Static IP addresses may cause a high potential risk of DDoS. @adamierymenko
