### ISSUE TITLE
Mac Zerotier client shows as offline

### ISSUE THREAD

**Issue by reginbald** [zerotier/ZeroTierOne#1160]
**Describe the bug**
Zerotier client for Mac shows as offline in my.zerotier.com and in the terminal. I've installed the client on two MacBooks and both show as offline. I had previously installed the client (1.4.6) on my older MacBook and it worked but now it shows as offline. The status of the network is REQUESTING_CONFIGURATION.

**To Reproduce**
1. Install the Mac client from https://zerotier.com/download/
2. Create a Network
3. Join the newly created network.
4. run the command `zerotier-cli status`
5. run the command `zerotier-cli listnetworks`

**Expected behavior**
Should show online.

**Screenshots**
<img width="561" alt="Screenshot 2020-03-15 at 11 49 42" src="https://user-images.githubusercontent.com/5693892/76700814-36a23280-66b3-11ea-8bbd-ccf6d559ee58.png">
<img width="587" alt="Screenshot 2020-03-15 at 11 53 47" src="https://user-images.githubusercontent.com/5693892/76700879-d069df80-66b3-11ea-9a13-d72e676659b8.png">
<img width="291" alt="Screenshot 2020-03-15 at 11 55 21" src="https://user-images.githubusercontent.com/5693892/76700887-e5df0980-66b3-11ea-95c8-cbb0399412f9.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - OS/Distribution Version: macOS Catalina 10.15.2
 - ZeroTier Version [e.g. 1.2.4]: 1.4.6
 - Hardware [e.g. raspberry pi 3] MacBook Pro 15-inc Mid-2015

**Comment by laduke** [comment]
hello, can you try restarting the background service?

- `sudo launchctl unload /Library/LaunchDaemons/com.zerotier.one.plist`
- `sudo launchctl load /Library/LaunchDaemons/com.zerotier.one.plist`

any changes to the network recently like in firewall config?

**Comment by qasimmajeed** [comment]
@reginbald did you find the solution

**Comment by momenthe** [comment]
any solution? i have same issue on windows 10 right now. when we were playing game, suddenly connection was blocked.

**Comment by tunaman65** [comment]
I have this same issue currently on my macbook pro. I just got a new macbook and used migration assistant. I thought there may have been an issue related to migration. After uninstalling and re-installing the latest I still see this issue. Was anyone able to resolve?

**Comment by smartynov** [comment]
Same issue on my macbook. Restarting service as @laduke suggested helped. But what causes it?

**Comment by laduke** [comment]
Hi @smartynov this is likely a different issue than the original author's issue. This one should probably have been closed. It was a 1.4.x issue. Now we're up to 1.8

Can you make a new issue so we can collect all the details, or post on our forum? If it's a "requesting configuration" issue, it's likely firewall related. thanks. 

https://docs.zerotier.com/zerotier/troubleshooting/#router-configuration-tips

**Comment by smartynov** [comment]
While it appeared several times at the days I wrote that comment, I have not experienced it in the last few weeks. If it occurs, I'll open a new issue. Thank you.

**Comment by Kerber0ss** [comment]
Hi, i have that problem too at macbook air m1, monterey 12.1,zerotier 1.8.4
if i restart services - work correctly 15 min and then Offline :( 
how to repair that?
