### ISSUE TITLE
[noob] ZeroTier kills my web access

### ISSUE THREAD

**Issue by dzg** [zerotier/ZeroTierOne#1162]
First time ZT user. 

I tried to set it up with all default options on 2 Macs. I was able to ping mac-to-mac, but it completely killed my WWW access. I had to disable/enable WiFi to get it back up.

Any ideas why?

Thank you

**Comment by laduke** [comment]
Hello, that's pretty strange especially with all default options. Can you hop into the "community" tab of my.zerotier.com so we can collect some info?

**Comment by adamierymenko** [comment]
Is this still an issue or were you able to figure it out? Likely culprit would have been some kind of IP address collision between real and virtual networks.
