### ISSUE TITLE
Does not stop during Ubuntu system shutdown/reboot

### ISSUE THREAD

**Issue by allenap** [zerotier/ZeroTierOne#1164]
**Describe the bug**

The ZeroTier service does not stop when shutting down or rebooting Ubuntu. It hangs for 1m30s while systemd (I assume) waits before forcefully killing it.

**Expected behavior**

The service should exit within a few seconds of being asked to do so by systemd.

**Screenshots**

![zerotier_not_stopping](https://user-images.githubusercontent.com/348564/77146030-59a15d80-6a8a-11ea-87ff-f507711189f4.jpg)

**Desktop (please complete the following information):**

- OS: Ubuntu 18.04.4 (Bionic), all system packages up to date
- ZeroTier Version: 1.4.6 (from .deb package)
    ```
    $ cat /etc/apt/sources.list.d/zerotier.list
    deb http://download.zerotier.com/debian/bionic bionic main
    ```
- Hardware: x86_64, Intel
 
**Additional context**

- ZeroTier Network Configuration: A couple of networks, nothing fancy, a handful of devices.
- Router Config: Regular home router.
- Firewall Config (try turning the firewall off): None.
- General Network Environment: Home.

**Comment by laduke** [comment]
check #1093 for some ideas @allenap. you can adjust the unit file for a work around.

**Comment by pinduzera** [comment]
Just as an add.
I face the same problem on Pop!_OS 20.04
