### ISSUE TITLE
About box on Mac UI would look a lot more professional with a bit of padding

### ISSUE THREAD

**Issue by richardcrichardc** [zerotier/ZeroTierOne#1167]
Great tool! Presentation in places could be improved. Am anticipating showing ZTO to non-technical colleagues and know they will judge based on things like these.

Here is an easy one, add some padding to the Mac GUI's about box:

![Screen Shot 2020-03-22 at 9 49 15 AM](https://user-images.githubusercontent.com/885016/77236381-d2d3b880-6c22-11ea-9d0f-42142fa3b856.png)

Would send a PR, but it's just a one line fix.

Let me know if this doesn't happen on all Mac's and I can help figure out how to reproduce.

**Comment by joseph-henry** [comment]
Good suggestion, we will look into this for the next release.

**Comment by joseph-henry** [comment]
This has finally been addressed and will make it into the next major release. Thanks
