### ISSUE TITLE
Typo in section '3.3. Tags' of manual

### ISSUE THREAD

**Issue by richardcrichardc** [zerotier/ZeroTierOne#1168]
In the text in section 3.3 of the manual it says: Let’s give it tag ID **100**

Then in the example, has switched to tag id **10**:

```
  {
    "type": "MATCH_TAGS_DIFFERENCE",
    "not": false,
    "or": false,
    "id": 10,
    "value": 0
  }, 
```

And following paragraph: difference between tags with tag ID **10** is zero 

Looks like a typo and all should either be 10 or 100.

**Comment by joseph-henry** [comment]
Fixed, thank you!
