### ISSUE TITLE
Question about moon access

### ISSUE THREAD

**Issue by Tualua** [zerotier/ZeroTierOne#1169]
Hello!

I have a question about moons. I created a moon on VPS. My client is now orbiting my moon. The question is if somebody will know my moon address he will be able to use it for his networks, right? I'm asking this because my VPS has limited amount of traffic.

**Comment by bartmichu** [comment]
I'm also wondering about this issue. And is there any way to restrict orbiting nodes, other than firewall rules? Maybe in v.2.0?

**Comment by laduke** [comment]
> The question is if somebody will know my moon address he will be able to use it for his networks, right?

Yes

There's currently no way to restrict, other than keeping it a secret and maybe rotating the moon's identity.
