### ISSUE TITLE
Support IPv6 for underlying network

### ISSUE THREAD

**Issue by rtucker** [zerotier/ZeroTierOne#117]
ZT1 does not appear to use IPv6 for the underlying network transport, even when it is available and usable.  This creates unnecessary reliance on supernodes when two peers have direct IPv6 connectivity but are behind IPv4 NAT.

**Comment by adamierymenko** [comment]
Closing for now since GitHub issue #180 also permits IPv6 to be negotiated between peers if a clear path exists. It should "just work" in many cases, especially if there are no aggressively stateful firewalls in the way.

As far as the root server / supernode architecture goes, this is probably going to stay IPv4 for the foreseeable future. The reason is the double ping problem. If it's IPv6, the client must now send an IPv4 HELLO *and* an IPv6 HELLO so that root servers can properly determine IP information and such. If you only use IPv6 you can't talk to IPv4 hosts, but everyone can (as of 2015) speak IPv4.

**Comment by maci0** [comment]
@adamierymenko so what happens if I have 2 hosts that are connected to the IPv6 internet only ?
How does ZT1 establish the initial connectivity in that case ?

**Comment by adamierymenko** [comment]
That's a problem I suppose. The problem I want to avoid though is having to send Nx2 pings where N is the number of root servers.

We have some long term plans to move toward IP any cast for root servers, both v4 and v6, in which case there'd be only one reachable through one IPv4 IP and one IPv6 IP. That would make it manageable.

**Comment by adamierymenko** [comment]
The central problem is that IPv4 and IPv6 are separate networks. IPv6 is fine but the transition was botched. They should have reclaimed 240.0.0.0/4 and used that to map to a transitional region of IPv6 space.

**Comment by maci0** [comment]
Are we talking about icmp pings or something in the ZT1 protocol ?
Is the overhead so big when having to send 2 pings ?

**Comment by adamierymenko** [comment]
HELLO messages -- ZT1 protocol. The overhead is small.

Maybe there's simply no other way. As with many other things, the Internet's brokenness demands a certain level of inefficiency to work around it.

**Comment by maci0** [comment]
why not try to use ipv6 first and if that fails ipv4 and within the hello message and the response include the information about the underlying networks

**Comment by adamierymenko** [comment]
... because unfortunately the vast majority of networks are still IPv4 only, and that would make startup times slower for the huge majority of users. If we do both, it has to be both all the time.

**Comment by adamierymenko** [comment]
Also doing one first and then another means state, and state means bugs and failure modes and edge cases. So yeah, it's IPv4 only or both concurrently.

**Comment by adamierymenko** [comment]
Okay, so 1.0.4 (soon to be released) *will* use IPv6 if it can see a real IPv6 address on the local system. It will add this to the list of addresses it pushes to remote peers, and they will try it and use it if it works. Will also work with IPv6 local addresses. But it'll only work between 1.0.4 peers.

Root servers using both V4 and V6 is still up in the air. I'd really love to find a way to avoid two pings per root server -- one V4 and one V6.

**Comment by adamierymenko** [comment]
Closing as:

1. -edge (new -dev once it's on the main net) is now fully dual-stack

2. new root infrastructure will also be fully dual-stack

Yay!
