### ISSUE TITLE
Weird behavior of ping?

### ISSUE THREAD

**Issue by vbargl** [zerotier/ZeroTierOne#1172]
**Describe the bug**
I got a wierd response from ping. Is it possible that remote configuration is not working correctly?
It's complicated to get direct (local terminal) access to second server to configure it, 
nevertheless everything should be ok by web interface.

**To Reproduce**
1. Create a private network through web interface
2. Install zerotier-one
3. Connect two computers, each one in different location in internet
4. Setup ip addresses on each computer
5. Try to ping to itself on each computer
6. See error

**Expected behavior**
if I ping from pc with ip 192.168.193.2 I should get response from that ip

**Screenshots**
![image](https://user-images.githubusercontent.com/11790900/77576042-bced1e80-6ed4-11ea-8895-04ca2fe06338.png)
![image](https://user-images.githubusercontent.com/11790900/77575829-654eb300-6ed4-11ea-801d-f174bcfb9f10.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - ZeroTier Version [e.g. 1.4.6]
 - Hardware PC

**Comment by laduke** [comment]
first thought is that icmp is blocked by windows firewall by default

**Comment by vbargl** [comment]
No, not the case, firewall was turned off completely.

**Comment by laduke** [comment]
what is 185.148.172.5

**Comment by vbargl** [comment]
Provider's public IP. Computer is behind NAT. Should I get a log from device with IP `192.168.193.2`?

**Comment by joseph-henry** [comment]
Hello @vbargl, if you are still seeing this type of issue can you confirm that it also happens from the other device as well?
