### ISSUE TITLE
Preferences window is blank when viewed via TeamViewer

### ISSUE THREAD

**Issue by ravz** [zerotier/ZeroTierOne#1173]
![image](https://user-images.githubusercontent.com/1230289/77769152-29ac1880-708f-11ea-9c7c-90e5d6ddc081.png)

**Comment by laduke** [comment]
Haha that's weird. As a work-around open an Admin power-shell and use the [CLI](https://zerotier.atlassian.net/wiki/spaces/SD/pages/29065282/zerotier-cli)
Once you're all connected over ZeroTier you can use RDP :)

**Comment by ravz** [comment]
is there a way to set this option using CLI or config file ?

**Comment by glimberg** [comment]
The start automatically option is just for the GUI applet.  ZeroTier itself is a system service started at boot.
