### ISSUE TITLE
Add package to official Debian repositories

### ISSUE THREAD

**Issue by shvchk** [zerotier/ZeroTierOne#1175]
**Is your feature request related to a problem? Please describe.**
ZeroTier repository is fine, but package from official Debian repo would be even better.

**Describe the solution you'd like**
`sudo apt install zerotier`

**Describe alternatives you've considered**
ZeroTier repository, snap

**Additional context**
This would help ZeroTier reach far larger user base (especially since it will eventually get to Ubuntu repos) and increase trust/confidence in it, IMO.

**Comment by laduke** [comment]
#807
