### ISSUE TITLE
Zero Tier 2.0 tracking

### ISSUE THREAD

**Issue by chriseomi** [zerotier/ZeroTierOne#1177]
Apologies if this has been asked before, I have tried googling but came up empty handed.

Is ZT 2 being developed in public. If so where can one go to particiate and see the progress?

If not are there any plans to do so, or will it be closed source.

Thanks

**Comment by zhangyz1997** [comment]
Just go to the [edge branch](https://github.com/zerotier/ZeroTierOne/tree/edge) of this project.

**Comment by chriseomi** [comment]
Perfect. Thanks :)

**Comment by CrazyBoyFeng** [comment]
> Just go to the [edge branch](https://github.com/zerotier/ZeroTierOne/tree/edge) of this project.

This branch is missing, who knows where to find it now?
