### ISSUE TITLE
How do I select one of the dual network cards as zerotier traffic

### ISSUE THREAD

**Issue by Fr33raNg3r** [zerotier/ZeroTierOne#1181]
I have two network cards, which are connected to the Internet through different ISPs, but I hope zerotier can fix a ISP for transmission. How can I set it up? thanks.

**Comment by laduke** [comment]
You can create a local.conf file. 
https://github.com/zerotier/ZeroTierOne/tree/master/service

**Comment by Fr33raNg3r** [comment]
Which parameter？How？

**Comment by Fr33raNg3r** [comment]
Can you introduce it in more detail？
