### ISSUE TITLE
Get disconnected at random time and having High latency ping

### ISSUE THREAD

**Issue by Patkoik** [zerotier/ZeroTierOne#1186]
**Describe the bug**
High latency ping - 96 ms Minimum - 328 ms Maximum - average 110 ms ** this is when it works but somehow, i get disconnected randomly after one Hour or so 
- I have to restart the Zerotier service on machine A only, the machine A restart to ping Machine B and Vice Versa becaus Machine B can't ping A at the same time
- In My-Zero tier , everythin is shown as connected

**To Reproduce**
Ping Machine A to B, B to A - it happen after an hour or so after machine are able to see each other

**Expected behavior**
1 - Stability in the VPN
2 - A little better performance - around 50ms, Mostly I want to know If I have the best configuration possible

**Desktop:**
 - OS: Windows 10 pro
 - Version: 1909 - 18
 - ZeroTier Version 1.4.6]
 - Hardware ; Custom build PC
-- CPU : AMD FX 8350 8 Core 3.6 GHz
-- Ram: DDR3 - 16 GB - 2133 Mhz- Dual channel -Kingstons
-- Asus M5A78L-M PLUS

**Additional context**
This is a very simple home network that I actually just did all the wiring in CAT6 to be getting the best latency possible. 
Physically, it is set like this: ISP Router - Switch Gigabyte 24 port Cisco -  all devices 
Simply put, I got less than 1 ms from every devices to every devices , I get mostly 1 to 3 ms when I reach my Bell ISP server (tested with speedtest by oklaa)
After some testing, I fetched Wireshark to see what would be the problem , I saw the same pattern as ticket #860 So I applied the fix of this ticket 

I have tested out the 5 roots server mentionned with there IP's, 
Miami one is the fastest for me witch get me a good average of 46 ms that I find rather acceptable than 110ms as my actual average result.

 With some reading on your knowledge base and ticket I have done the following;

1 - Deactivate private firewall on both machine A and B.
2 - Set up a port forwarding UDP 9993 within my ISP Router and setup with public IP (not sure if would be the right way).
3 - Had to Apply fix of ticket #860 to block SSDP and Windows UPNP , ping packet could not reach destination at random time. ** seem to give me a bit of stability but still get disconnected randomly
4 - myZerotier network is set in advance mode with the IP range - 192.168.2.101 to 192.168.2.200
5 - I use the following Managed route - 192.168.2.0/24.

If possible, I would seek some insight on this matter so I can understand better :)

PS: I found this brilliant program that might help me lauch a new compagny I would raise - Thumb up to all the DEV and contributors ! 

**UPDATE 2020-04-17 :** 
I builded a little script that actually give the following info into a text file. My goal was to monitor precisely when the disconnection occured and have  certain insurrance that the VPN is always on even if it cut for a couple of seconds
- Time stap
- Ping every 5 second or so 
- If ping get destination unreachable, the it restart ZT service from Machine A and B, 

*note* batch file is installed on machine A since the issue seem to be link whit the service on Machine A, machine B restart to ping as soon the service on Machine A is restarted

1 - Oddly , in the last day that I was running the script, no deconnection occured, I can't say for sure what fix the problem since a played a bit in the networking to finally reapply those line in the drop flow rule:
	and dport 1900
	and ipprotocol udp
	and ipdest 239.255.255.250/24 
2 - since my script is always cheking the network card maybe that keep it alive, I was thinking about the @put to sleep@ option on the network card , it is deactivated so should not be the issue here 

*** I still have those latency that I am just wondering if it is normal 

**Script:** 

File 1 - Main script that call 2 others - 1 timestamp and 2 Restart service on local and network

@ECHO OFF
:LOOPSTART
Call c:\Timestamp.cmd >> c:\VPNSTATE.txt
ping (remote machine) -n 1 >>  c:\VPNSTATE.txt

echo      Verification of the connexion availlability

ping -n 1 192.168.2.170 | find "TTL=" >(wording you want to catch in the ping command Ex : destination unable to reach)
if %errorlevel% == 1 (
  echo VPN Zerotier One est hors service, patientez quelques secondes
  CALL c:\RestartZeroTier.cmd  >>  c:\VPNSTATE.txt
)

TIMEOUT  5
GOTO LOOPSTART

File 2 - Timestamp , here what I did use,I found so many way to get timestamp XD

@echo off
for /f "tokens=2 delims==" %%a in ('wmic OS Get localdatetime /value') do set "dt=%%a"
set "YY=%dt:~2,2%" & set "YYYY=%dt:~0,4%" & set "MM=%dt:~4,2%" & set "DD=%dt:~6,2%"
set "HH=%dt:~8,2%" & set "Min=%dt:~10,2%" & set "Sec=%dt:~12,2%"

set "datestamp=%YYYY%-%MM%-%DD%" & set "timestamp=%HH%:%Min%:%Sec%"
set "fullstamp=%YYYY%-%MM%-%DD% %HH%:%Min%:%Sec%"
echo fullstamp: "%fullstamp%"

and file 3 - service call

net use \\Distant PC\admin$ /user:username password

 net stop "ZeroTier One"  
 net start "ZeroTier One"

SC \\STORAGE2 STOP "ZeroTierOneService" 
SC \\STORAGE2 START "ZeroTierOneService"

File output look like: ( it is mostly raw since im a french windows user:)

Statistiques Ping pour 192.168.2.170:
    Paquetsÿ: envoy‚s = 1, re‡us = 1, perdus = 0 (perte 0%),
Dur‚e approximative des boucles en millisecondes :
    Minimum = 103ms, Maximum = 103ms, Moyenne = 103ms
fullstamp: "2020-04-17 15:58:59"

Envoi d'une requˆte 'Ping'  192.168.2.170 avec 32 octets de donn‚esÿ:
R‚ponse de 192.168.2.170ÿ: octets=32 temps=99 ms TTL=128

**Comment by unquietwiki** [comment]
@Patkoik I'm going over our GitHub issues in preparation for our pending 1.6.0 release; that should hopefully take care of a few things. If you're still having this issue ATM, can you please check the following & let us know otherwise so we can try to catch it? Thanks!

* https://zerotier.atlassian.net/wiki/spaces/SD/pages/521011201/Windows+Troubleshooting -> Walkthrough of common Windows issues.
* https://www.reddit.com/r/zerotier/?f=flair_name%3A%22Gaming%22 -> A lot of gamers & Windows users have figured out some stuff.
* https://discuss.zerotier.com/ -> Official Discuss forum

**Comment by joseph-henry** [comment]
I suspect this issue was resolved in `1.6.5`. If not please re-open.
