### ISSUE TITLE
macOS - Allowed Managed breaks my Internet

### ISSUE THREAD

**Issue by altisae86** [zerotier/ZeroTierOne#1188]
**Describe the bug**
No internet access if Allow Managed is set to true.  I need to deselect Allow Managed and reboot macOS 10.14.6 to get Internet back.  2 of my desktop macs (10.14.6 and 10.15.4) are experiencing this issue.  My laptop mac doesn't have this problem

**To Reproduce**
-Tick allow managed = no internet.
-Untick allow managed = still no initernet
-Set zerotier to not autorun at startup.
-Deselect allow managed
-Restart
-Internet starts working again.

**Expected behavior**
Allow managed should be true and shouldn't break internet

**Screenshots**  ifconfig output below
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000 
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	nd6 options=201<PERFORMNUD,DAD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
EHC26: flags=0<> mtu 0
EHC29: flags=0<> mtu 0
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=b<RXCSUM,TXCSUM,VLAN_HWTAGGING>
	ether [redacted]
	inet6 fe80::105f:1ca1:2849:5f7b%en0 prefixlen 64 secured scopeid 0x6 
	inet 192.168.1.162 netmask 0xffffff00 broadcast 192.168.1.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect (1000baseT <full-duplex,flow-control,energy-efficient-ethernet>)
	status: active
feth7139: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 16370
	ether redacted
	peer: feth2139
	media: autoselect
	status: active
feth2139: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 5000 mtu 2800
	ether redacted
	peer: feth7139
	media: autoselect
	status: active
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
	inet6 fe80::77ac:65a9:bb6c:e624%utun0 prefixlen 64 scopeid 0x9 
	nd6 options=201<PERFORMNUD,DAD>

**Desktop (please complete the following information):**
macOS 10.14.6

**Comment by laduke** [comment]
hi @altisae86, see #1104  

or, is your physical subnet the same as your zerotier subnet?

**Comment by altisae86** [comment]
HI laduke,

It's fixed.  Not sure why, but on macOS, assigning an IP address fixes the problem.  

I have a Managed Routes set as 192.168.192.0/24.  
Private Access Control.
Everything else is left unchecked.
