### ISSUE TITLE
Problem with assigned IP addreses on Debian 

### ISSUE THREAD

**Issue by rjsocha** [zerotier/ZeroTierOne#1189]
**Is your feature request related to a problem? Please describe.**

Not sure if this should be feature request or bug report. But here we go.

On Linux  when new IP is added to ZT interface and this new IP belongs to same network (same /prefix) it's added as secondary ip (this is done by kernel code).  For example:

```
17: zt2lrxy7lg: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2800 ...
    link/ether b6:a8:3f:d7:9f:34 brd ff:ff:ff:ff:ff:ff
    inet 172.24.216.14/16 brd 172.24.255.255 scope global zt2lrxy7lg
       valid_lft forever preferred_lft forever
    inet 172.24.0.1/16 brd 172.24.255.255 scope global secondary zt2lrxy7lg
       valid_lft forever preferred_lft forever
    inet6 fe80::b4a8:3fff:fed7:9f34/64 scope link
       valid_lft forever preferred_lft forever

```

172.24.216.14/16 was autoassigend and 172.24.0.1/16 was manualy added to node.

And if I remove (via my.zerotier.com UI)  first IP 172.24.216.14/16 both IP will be removed by Linux kernel:

```
17: zt2lrxy7lg: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2800 ...qlen 1000
    link/ether b6:a8:3f:d7:9f:34 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::b4a8:3fff:fed7:9f34/64 scope link
       valid_lft forever preferred_lft forever
```

zerotierone-one will miss (or ignore) this event.

This behavior is default on Debian 10 (and Debian 9). 
And can be controled by this sysctl path:

/proc/sys/net/ipv4/conf/INTERFACE/promote_secondaries
https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt

On Ubuntu (tested on 18.04) there is default setting for this option set to 1 in:

/proc/sys/net/ipv4/conf/all/promote_secondaries

**Describe the solution you'd like**

1. Display warrning durining installation if this option is not set
2. Write 1 to /proc/sys/net/ipv4/conf/ZTIFNAME/promote_secondaries durning interface creation (this could be impossible due dropped privileges at this stage)
3. Change logic in IP assigment code and for example check if IP address is present (I did quick look at source code and it's looks like information about IP addresses is cached)

Regards

**Comment by glimberg** [comment]
The default ZeroTier configuration is for ZeroTier to manage addresses on the interfaces it creates.

You can:
1. Assign the 2nd IP address in the network configuration at https://my.zerotier.com.  ZeroTier can manage up to 32 assigned IP addresses per network member.
2. Disable IP auto assignment for the network member at https://my.zerotier.com.
3. Set ZeroTier on that node to not use managed network settings and assign IP addresses and routes yourself.  You can set this via `sudo zerotier-cli set $networkID allowManaged=0`

**Comment by rjsocha** [comment]
Hi. Thanks for replay. But I think you miss my point :)

My post is about  this kernal setting: /proc/sys/net/ipv4/conf/*/promote_secondaries 

This is completly ignored by Zero Tier client.  This setting is distro dependent (for example promote_secondaries  is set on Ubuntu by default, but not set on Debian).

Please check this on Debian: add few IPs to node (via web UI). Remove first IP (added as first IP - no matter if auto or manual assigned) via web UI. 

Expected behavior: remove selected IP and leave other IP  intact. 

Current behavior: all IP are removed from ZT interface.

Best regards

**Comment by glimberg** [comment]
Again,  ZeroTier manages the settings of the interface.  If you don't want that behavior, you can use the options I posted above.

**Comment by rjsocha** [comment]
OK. I understand. I prefer same behavior on all linux distros so I use promote_secondaries option.

Here is video that show how debian and ubuntu deals with ip assigments.

https://www.youtube.com/watch?v=7KPGZrYheIc

Thanks for your time :)
Regards

**Comment by glimberg** [comment]
Unfortunately we cannot control, nor do we have the time to keep track of all the different settings different Linux Distributions use.
