### ISSUE TITLE
GCC9 doesn't support arch armv5

### ISSUE THREAD

**Issue by athoik** [zerotier/ZeroTierOne#1192]
Building with GCC9 using OpenEmbedded Zeus branch there is an issue compiling ZeroTier.

The issue occurs due to missing architecture armv5.

Removing the following part on make-linux.mk workarounds issue, since it's OpenEmbedded  job to properly setup the environment for the chosen arch/tune.
  
```
diff --git a/make-linux.mk b/make-linux.mk
index eff3a50..1108b06 100644
--- a/make-linux.mk
+++ b/make-linux.mk
@@ -262,19 +262,6 @@ ifeq ($(ZT_OFFICIAL),1)
    override LDFLAGS+=-Wl,--wrap=memcpy -static-libstdc++
 endif

-# ARM32 hell -- use conservative CFLAGS
-ifeq ($(ZT_ARCHITECTURE),3)
-   ifeq ($(shell if [ -e /usr/bin/dpkg ]; then dpkg --print-architecture; fi),armel)
-       override CFLAGS+=-march=armv5 -mfloat-abi=soft -msoft-float -mno-unaligned-access -marm
-       override CXXFLAGS+=-march=armv5 -mfloat-abi=soft -msoft-float -mno-unaligned-access -marm
-       ZT_USE_ARM32_NEON_ASM_CRYPTO=0
-   else
-       override CFLAGS+=-march=armv5 -mno-unaligned-access -marm -fexceptions
-       override CXXFLAGS+=-march=armv5 -mno-unaligned-access -marm -fexceptions
-       ZT_USE_ARM32_NEON_ASM_CRYPTO=0
-   endif
-endif
-
 # Build faster crypto on some targets
 ifeq ($(ZT_USE_X64_ASM_SALSA),1)
    override DEFS+=-DZT_USE_X64_ASM_SALSA2012
```

It seems that GCC now supports only armv5t and armv5te.

https://gcc.gnu.org/onlinedocs/gcc-9.2.0/gcc/ARM-Options.html

So I guess more people will get same issue, soon or late once they switch to a newer GCC.

**Comment by adamierymenko** [comment]
Closing as we're moving to cmake in v2.

**Comment by mpvader** [comment]
Hey @athoik, do you have the zerotier recipe public somewhere? And working? :-)

I’d like to try it.

**Comment by athoik** [comment]
Sure, try this recipe https://github.com/OpenPLi/openpli-oe-core/blob/develop/meta-openpli/recipes-connectivity/zerotier/zerotier_1.4.6.bb
