### ISSUE TITLE
Add type of current connection with peers optimal udp or tcp, to zerotier-cli

### ISSUE THREAD

**Issue by IvanTurgenev** [zerotier/ZeroTierOne#1195]
**Is your feature request related to a problem? Please describe.**
My ISP opened some ports for me i want to make sure an optimal direct UDP connection is currently being used, cant test 9993 because zerotier makes use of it, and i think my isp only opened tcp, but i cant be sure on 9993.

**Describe the solution you'd like**
zerotier works best on udp, as a user not knowing this is annoying, add another column to zerotier-cli peer that denotes connection type.

**Describe alternatives you've considered**
none, tcpdump?

**Comment by laduke** [comment]
check `zerotier-cli info` for TUNNELED or ONLINE. Tunneled is TCP

**Comment by IvanTurgenev** [comment]
> check `zerotier-cli info` for TUNNELED or ONLINE. Tunneled is TCP

Shows online but are all peers are UDP ? Does it makes sense?

**Comment by glimberg** [comment]
ZeroTier is always UDP, unless TUNNELED is shown in the `zerotier-cli info` output.
