### ISSUE TITLE
By internet dropped from 700+ MBs to 10Mbs after using ZeroTier

### ISSUE THREAD

**Issue by NoshiEmperor** [zerotier/ZeroTierOne#1198]
After I played with my friends some game, I have noticed that my internet got slower then before, I have tried to reset the network, delete all extra networks that were created by ZeroTier and still it's the same, any help?

**Comment by kompowiec** [comment]
same i run ZT ping packets always drop in the vicinity 80-90%

CentOS 8

**Comment by joseph-henry** [comment]
Closing due to age and inability to reproduce. If you still experience this issue please re-open.
