### ISSUE TITLE
Android crashes due to null reference exception

### ISSUE THREAD

**Issue by mjmeintjes** [zerotier/ZeroTierOne#1200]
On Android phone the VPN service constantly disconnects after a couple of minutes. It seems the ZeroTier app is crashing due to a null reference exception:
![photo5037762283773732988](https://user-images.githubusercontent.com/72253/81889550-e1719700-95f7-11ea-9bf5-a2993a19f4d6.jpg)

This started happening recently (past day or 2). I've been using ZeroTier for a couple of years now without major problems.

I tried resetting all of the app data, as well as restarting the phone but that did not make a difference.

**Smartphone (please complete the following information):**
 - Device: Pocophone F1 (Xiaomi)
 - OS: Android 9 PKQ1.180729.001
 - Version 1.4.4-1

Maybe related to this issue: https://github.com/zerotier/ZeroTierOne/issues/1130

**Comment by k3tan172** [comment]
Can confirm the same here. Frequent drop outs. Unable to time it, it happens randomly. Been using ZeroTier for ages as well, no hiccups.

Device: Google Pixel 3a
OS: GrapheneOS
Version 1.4.4.-1

Tried another phone.
Device: LG V30+
OS: Stock whatever it comes with
Version 1.4.4-1

**Comment by lordoftheyolk** [comment]
Confirmed to currently experiencing the same issue over the last few days. ZeroTier app would crash and result in loss of connection. Frequency: between 15 to 30 minutes.

Have been using zerotier for the last year and this is the first time encountering this.

Device: NVIDIA Shield 2017 model
OS: android for shield 8.0.2
ZTOne version 1.4.4.-1

**Comment by glimberg** [comment]
Looking into this today.  Nothing has changed on our end that could effect this. Working theory is that an android update or component got updated and broke something

**Comment by glimberg** [comment]
New release is available on the Google Play store

**Comment by cendenta** [comment]
I'm still seeing this behavior even after the recent update.

Device: Google Pixel 3a XL
OS: Android 10
Version: 1.4.6-1

**Comment by lordoftheyolk** [comment]
Still experiencing the same issue after updating unfortunately...

Device: NVIDIA Shield 2017 model
OS: android for shield 8.0.2
 version 1.4.6-1

**Comment by k3tan172** [comment]
I can't access anything from Zerotier IP addresses. No traffic flows through on networks outside of my own. The disconnections on android app still occur but less frequent that 15 minutes. Maybe a few hours.

**Comment by fakuivan** [comment]
In my case, this has fixed the random disconnects

**Comment by k3tan172** [comment]
I'm still getting random disconnects, just less frequent. Instead of minutes, we're now talking hours.

**Comment by sipodd** [comment]
Hi all, for me the update didn't fix the disconnects, too. As k3tan172 said, it disconnects kinda random after a few hours and when switching wifi <-> 4g/lte.
Also sometimes it's connected but doesn't reach any other devices in the same network via ipv6 on the carrier network. Setting the Android client to ipv4 helped with that. If there is a way to provide any logs, just tell me how and I'll love to support with that.

**Comment by eMBee** [comment]
> 
> 
> Looking into this today. Nothing has changed on our end that could effect this. Working theory is that an android update or component got updated and broke something

i have the crashes as well, and i am certain that i have not updated anything. i have not even updated any installed apps or installed new apps at the time the crashes started.

updating to 1.4.6-1  does not make any noticeable difference
