### ISSUE TITLE
android 1.4.6-1 is still crashing

### ISSUE THREAD

**Issue by eMBee** [zerotier/ZeroTierOne#1202]
despite the update, the app is still crashing after a some minutes, sometimes more.
it does seem to hold up longer than 1.4.4, but active use (accessing another zerotier device)  seems to accelerate the crashing.

i am running /e/ (based on lineage) from https://e.foundation/
the phone has not received any updates prior to crashes starting, nor have any apps been updated or new apps been installed. 

the crashes instead seem to be network related. possibly due to changes in some network resource that is being accessed when network activity happens.

**Comment by glimberg** [comment]
You can try the current beta to see if there's any further help in there.  Should be pushed out to release tomorrow

https://play.google.com/apps/testing/com.zerotier.one

**Comment by eMBee** [comment]
i can't access the above link. do you have a direct download outside of google?

btw, since a few hours 1.4.6-1 seems to be running fine. the only difference seems to be the time of day... (around midnight at UTC+8)

**Comment by glimberg** [comment]
1.4.6-5 is now out
