### ISSUE TITLE
Question: huge error log for Zerotier One

### ISSUE THREAD

**Issue by nemo2018** [zerotier/ZeroTierOne#1204]
Hi,
Can I have a question here.
I have zerotier openWrt version running at my home device. version: 1.4.6.

Basically Zerotier is running very well, without any problem.

My question is at the system log of OpenWrt, there are huge error log related to Zerotier, every 5 minutes. all system log are full of this. What should I check for it?

![image](https://user-images.githubusercontent.com/37334053/82624556-76d2e380-9c15-11ea-805c-ecd1bcfd1307.png)

Thank you!

**Comment by joseph-henry** [comment]
Looks like this is coming from the UPnP library we use. I'm going to close this ticket but reference it in a megaticket about noisy logs. Thanks for bringing this up.

**Comment by Qinka** [comment]
@joseph-henry  I got same problem, and stuck on ` REQUESTING_CONFIGURATION`.
