### ISSUE TITLE
Android app crashes at onVirtualNetworkFrame

### ISSUE THREAD

**Issue by servadestroya** [zerotier/ZeroTierOne#1205]
## Describe the bug
The app crashes at least once a day, this time I was able to catch the error as I was using my phone. I took a screenshot of the error details but I wasn't able to report the error.

## To Reproduce
**Seems to be an issue triggered by network activity, I don't know how you can reproduce it**

## Screenshots
![zt_crash_cropped](https://user-images.githubusercontent.com/24995257/82719181-c0a3e400-9c7e-11ea-9972-7c3c3982356e.png)
**Not the complete error report**
I will not post the complete stack here as it might contain some sensible information like the node private key, please ask me if you need the complete screenshot with the stack. I do not have this in text form.

## Smartphone
 - Device: Xiaomi Mi 9 Lite
 - OS: Android
 - Version 10

## Additional context
- On WiFi, internet connection is quite unreliable
- Network the phone was connected to is hosted on a controller running ztncui behind CGNAT

**Comment by servadestroya** [comment]
The app crashed again, I was able to report the issue _and_ take a screenshot.

**Comment by joseph-henry** [comment]
Thank you, we are looking into this.
