### ISSUE TITLE
Quetion regarding route between ZeroTier and Physical Networks

### ISSUE THREAD

**Issue by ovizii** [zerotier/ZeroTierOne#1206]
I foudn this tutorial: https://zerotier.atlassian.net/wiki/spaces/SD/pages/224395274/Route+between+ZeroTier+and+Physical+Networks 

and I am having trouble with the last step where you save the iptables rules so that they are being applied upon next reboot.

```
sudo apt install iptables-persistent
sudo iptables-save > /etc/iptables/rules.v4
```

it works but it does more than necessary. It also saves all current iptables rules regarding docker thus basically permanently saving all docker rules which is definitely not what we want. What we want is having exactly these 2 rules saved permanently.

```
sudo iptables -t nat -A POSTROUTING -o $PHY_IFACE -j MASQUERADE
sudo iptables -A FORWARD -i eth0 -o $ZT_IFACE -m state --state RELATED,ESTABLISHED -j ACCEPT
sudo iptables -A FORWARD -i $ZT_IFACE -o $PHY_IFACE -j ACCEPT
```

could somebody explain how I can save only these permanently?

**Comment by laduke** [comment]
Hello, I suppose you can edit the rules file and delete the lines you don't want. 
Unfortunately there are more ways to manage the firewall than anyone can keep track of. Closing because it's not a zerotier specific issue, but feel free to continue to comment. Thanks!

**Comment by ovizii** [comment]
I'm no good with iptables and do not understand most of those rules so I am not sure I can really delete all of them except the 3 I am looking for. 

I asked here although it is not zerotier related as I found the "tutorial" on your wiki and no other way to ask questions related to that wiki.

Maybe somebody will see and reply despite this ticket being closed ;-)

**Comment by laduke** [comment]
I'll try to add a note about docker to the article. You should be able to keep just the three lines related to the zerotier NAT in the file. Docker adds it's rules itself as far as I know.

**Comment by ovizii** [comment]
thanks, I will give it a try and keep these 3 lines and try and reboot:
```
-A FORWARD -i vmbr0 -o ztfszfgoy6 -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i ztfszfgoy6 -o vmbr0 -j ACCEPT
-A POSTROUTING -o vmbr0 -j MASQUERADE

```
I was just very intimidated by the seemingly complex syntax of that file :-)
