### ISSUE TITLE
iOS 13.5 never connecting to Zerotier servers

### ISSUE THREAD

**Issue by CHAMLEX** [zerotier/ZeroTierOne#1211]
**Describe the bug**

**To Reproduce**
1. Install app on iOS 13.5
2. Add network key
3. Accept VPN creation
4. Toggle VPN on
5.  VPN never connects just sits at Connecting.

**Expected behavior**
VPN Connection successfully connected.

 
**Smartphone (please complete the following information):**
 - Device: [iPhone xR]
 - OS: [iOS13.5]
 - Version [1.4.4-1]
- General Network Environment: [ Home Network, and LTE ]

(Formatting)

**Comment by CHAMLEX** [comment]
Attached Screenshot of VPN Settings
![image](https://user-images.githubusercontent.com/39652205/83314901-a328ca00-a1ea-11ea-9a98-380cc7c9a4ef.png)

**Comment by glimberg** [comment]
Can't reproduce it but think I found what the issue is.  It'll be a few days before we can get a new version out because Apple

**Comment by smalldickman** [comment]
This should be apple's problem,,,,worked fine in previous ios versions,

**Comment by glimberg** [comment]
It's not an iOS issue.  We're just waiting for them to approve a new version

**Comment by XLuma** [comment]
Can reproduce, this is happening on my iPad
Model: iPad Pro 10.5 inch
OS: iPadOS 13.3
I even tried adding manually the device, and Zerotier reports as "never" connected.
![F268D114-B692-49AE-81E6-1E1B656407A8](https://user-images.githubusercontent.com/39510265/83343050-c1aec400-a2c3-11ea-8805-a0e14e22cda5.jpeg)

**Comment by glimberg** [comment]
@XLuma see my previous response.

**Comment by xenek** [comment]
Hi, same issue.

Device: [iPhone 8]
OS: [iOS13.4.1]
Version [1.4.4-1]

Android device connects ok, Iphone has same behaviour, spinning disc & vpn stuck at 'connecting'

General Network Environment: [ Home Network, and LTE ]

**Comment by xenek** [comment]
Hi, same issue on second iOS device.

Device: [iPad mini gen1 MD532X/A]
OS: [iOS9.3.5]
Version [1.4.4-1]

Android device connects ok, but Ipad has same behaviour, spinning disc & vpn stuck at 'connecting'
-note that when you check the VPN config in settings/general/vpn it shows the server as 127.0.0.1 for the type 'ZeroTier One'

General Network Environment: [ Home Network, and LTE ]

**Comment by glimberg** [comment]
@xenek Same reply.  We're waiting for apple to approve a new release

**Comment by s0ftice** [comment]
this seems to be an issue with older client versions of zerotier in general, not only iOS related: https://www.reddit.com/r/zerotier/comments/gsyoli/cannot_bind_to_local_control_interface_port_and/

new members can't be registered with 1.4.2 and 1.4.6 (maybe more versions) anymore. Looks like a server-side change zerotier did. wondering if by accident or intended... @glimberg ?

**Comment by smalldickman** [comment]
> This should be apple's problem,,,,worked fine in previous ios versions,

ipad 13.5.1 fixed,update to 13.5.1

**Comment by glimberg** [comment]
iOS version has nothing to do with it.  We figured out a way to fix things from the server side.
