### ISSUE TITLE
ZeroTier fails to work following apt upgrade

### ISSUE THREAD

**Issue by lancelon** [zerotier/ZeroTierOne#1212]
Apt upgrade upgraded ZeroTier on my Pi and now ZeroTier has connection problems. I've done a `reboot` **and** uninstalled and reinstalled ZeroTier but it's still very unhappy. Any ideas? See [screenshot](https://imgur.com/YIDiWSr)

Thank you!

**Comment by joseph-henry** [comment]
It looks like ZeroTier isn't even running. Can you check your processes? If it's not running, try manually starting the daemon with `/usr/sbin/zerotier-one -d` and see if that works. If so, there might be something wrong with the init script.
