### ISSUE TITLE
Error In Compile Zerotier 

### ISSUE THREAD

**Issue by OpenVu** [zerotier/ZeroTierOne#1213]
Hello

I get this Error in compile zerotier For My setop Box with Gcc 10 

===Log====
 In file included from service/../node/Membership.hpp:24,
|                  from service/../node/Network.hpp:37,
|                  from service/../node/Node.hpp:32,
|                  from service/OneService.cpp:33:
| service/../node/Capability.hpp: In constructor 'ZeroTier::Capability::Capability()':
| service/../node/Capability.hpp:70:37: warning: 'void* memset(void*, int, size_t)' clearing an object of type 'struct ZeroTier::Capability::<unnamed>' with no trivial copy-assignment; use assignment or value-initialization instead [-Wclass-memaccess]
|    70 |   memset(_custody,0,sizeof(_custody));
|       |                                     ^
| In file included from service/../node/Membership.hpp:24,
|                  from service/../node/Network.hpp:37,
|                  from service/../node/Node.hpp:32,
|                  from service/OneService.cpp:33:
| service/../node/Capability.hpp:476:9: note: 'struct ZeroTier::Capability::<unnamed>' declared here
|   476 |  struct {
|       |         ^
| osdep/OSUtils.cpp: In static member function 'static std::vector<std::__cxx11::basic_string<char> > ZeroTier::OSUtils::listDirectory(const char*, bool)':
| osdep/OSUtils.cpp:111:28: warning: 'int readdir_r(DIR*, dirent*, dirent**)' is deprecated [-Wdeprecated-declarations]
|   111 |   if (readdir_r(d,&de,&dptr))
|       |                            ^
| In file included from osdep/OSUtils.cpp:32:
| /home/enigma/vision/openvision-development-platform/build/tmp/work/mips32el-oe-linux/zerotier/1.4.6+gitAUTOINC+b6b11dbf82-r0/recipe-sysroot/usr/include/dirent.h:183:12: note: declared here
|   183 | extern int readdir_r (DIR *__restrict __dirp,
|       |            ^~~~~~~~~
| osdep/OSUtils.cpp: In static member function 'static long int ZeroTier::OSUtils::cleanDirectory(const char*, int64_t)':
| osdep/OSUtils.cpp:161:28: warning: 'int readdir_r(DIR*, dirent*, dirent**)' is deprecated [-Wdeprecated-declarations]
|   161 |   if (readdir_r(d,&de,&dptr))
|       |                            ^
| In file included from osdep/OSUtils.cpp:32:
| /home/enigma/vision/openvision-development-platform/build/tmp/work/mips32el-oe-linux/zerotier/1.4.6+gitAUTOINC+b6b11dbf82-r0/recipe-sysroot/usr/include/dirent.h:183:12: note: declared here
|   183 | extern int readdir_r (DIR *__restrict __dirp,
|       |            ^~~~~~~~~
| osdep/OSUtils.cpp: In static member function 'static bool ZeroTier::OSUtils::rmDashRf(const char*)':
| osdep/OSUtils.cpp:210:28: warning: 'int readdir_r(DIR*, dirent*, dirent**)' is deprecated [-Wdeprecated-declarations]
|   210 |   if (readdir_r(d,&de,&dptr) != 0)
|       |                            ^
| In file included from osdep/OSUtils.cpp:32:
| /home/enigma/vision/openvision-development-platform/build/tmp/work/mips32el-oe-linux/zerotier/1.4.6+gitAUTOINC+b6b11dbf82-r0/recipe-sysroot/usr/include/dirent.h:183:12: note: declared here
|   183 | extern int readdir_r (DIR *__restrict __dirp,
|       |            ^~~~~~~~~
| In file included from service/../node/Node.hpp:32,
|                  from service/OneService.cpp:33:
| service/../node/Network.hpp: In constructor 'ZeroTier::Network::_IncomingConfigChunk::_IncomingConfigChunk()':
| service/../node/Network.hpp:422:70: warning: 'void* memset(void*, int, size_t)' clearing an object of type 'struct ZeroTier::Network::_IncomingConfigChunk' with no trivial copy-assignment; use assignment or value-initialization instead [-Wclass-memaccess]
|   422 |   _IncomingConfigChunk() { memset(this,0,sizeof(_IncomingConfigChunk)); }
|       |                                                                      ^
| service/../node/Network.hpp:420:9: note: 'struct ZeroTier::Network::_IncomingConfigChunk' declared here
|   420 |  struct _IncomingConfigChunk
|       |         ^~~~~~~~~~~~~~~~~~~~
| mipsel-oe-linux-g++  -mel -mabi=32 -mhard-float -march=mips32 --sysroot=/home/enigma/vision/openvision-development-platform/build/tmp/work/mips32el-oe-linux/zerotier/1.4.6+gitAUTOINC+b6b11dbf82-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/home/enigma/vision/openvision-development-platform/build/tmp/work/mips32el-oe-linux/zerotier/1.4.6+gitAUTOINC+b6b11dbf82-r0=/usr/src/debug/zerotier/1.4.6+gitAUTOINC+b6b11dbf82-r0                      -fdebug-prefix-map=/home/enigma/vision/openvision-development-platform/build/tmp/work/mips32el-oe-linux/zerotier/1.4.6+gitAUTOINC+b6b11dbf82-r0=/usr/src/debug/zerotier/1.4.6+gitAUTOINC+b6b11dbf82-r0                      -fdebug-prefix-map=/home/enigma/vision/openvision-development-platform/build/tmp/work/mips32el-oe-linux/zerotier/1.4.6+gitAUTOINC+b6b11dbf82-r0/recipe-sysroot=                      -fdebug-prefix-map=/home/enigma/vision/openvision-development-platform/build/tmp/work/mips32el-oe-linux/zerotier/1.4.6+gitAUTOINC+b6b11dbf82-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden -Wall -Wno-deprecated -std=c++11 -pthread  -DNDEBUG  -DZT_USE_MINIUPNPC -DMINIUPNP_STATICLIB -DMINIUPNPC_SET_SOCKET_TIMEOUT -DMINIUPNPC_GET_SRC_ADDR -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -DOS_STRING=\"Linux\" -DMINIUPNPC_VERSION_STRING=\"2.0\" -DUPNP_VERSION_STRING=\"UPnP/1.1\" -DENABLE_STRNATPMPERR -DZT_NO_TYPE_PUNNING -DZT_BUILD_PLATFORM=1 -DZT_BUILD_ARCHITECTURE=5 -DZT_SOFTWARE_UPDATE_DEFAULT="\"disable\"" -D_MT_ALLOCATOR_H -D_POOL_ALLOCATOR_H -D_EXTPTR_ALLOCATOR_H -D_DEBUG_ALLOCATOR_H   -c -o osdep/LinuxEthernetTap.o osdep/LinuxEthernetTap.cpp
| In file included from service/../node/Membership.hpp:24,
|                  from service/../node/Network.hpp:37,
|                  from service/../node/Node.hpp:32,
|                  from service/SoftwareUpdater.cpp:41:
| service/../node/Capability.hpp: In constructor 'ZeroTier::Capability::Capability()':
| service/../node/Capability.hpp:70:37: warning: 'void* memset(void*, int, size_t)' clearing an object of type 'struct ZeroTier::Capability::<unnamed>' with no trivial copy-assignment; use assignment or value-initialization instead [-Wclass-memaccess]
|    70 |   memset(_custody,0,sizeof(_custody));
|       |                                     ^
| In file included from service/../node/Membership.hpp:24,
|                  from service/../node/Network.hpp:37,
|                  from service/../node/Node.hpp:32,
|                  from service/SoftwareUpdater.cpp:41:
| service/../node/Capability.hpp:476:9: note: 'struct ZeroTier::Capability::<unnamed>' declared here
|   476 |  struct {
|       |         ^
| In file included from service/../node/Node.hpp:32,
|                  from service/SoftwareUpdater.cpp:41:
| service/../node/Network.hpp: In constructor 'ZeroTier::Network::_IncomingConfigChunk::_IncomingConfigChunk()':
| service/../node/Network.hpp:422:70: warning: 'void* memset(void*, int, size_t)' clearing an object of type 'struct ZeroTier::Network::_IncomingConfigChunk' with no trivial copy-assignment; use assignment or value-initialization instead [-Wclass-memaccess]
|   422 |   _IncomingConfigChunk() { memset(this,0,sizeof(_IncomingConfigChunk)); }
|       |                                                                      ^
| service/../node/Network.hpp:420:9: note: 'struct ZeroTier::Network::_IncomingConfigChunk' declared here
|   420 |  struct _IncomingConfigChunk
|       |         ^~~~~~~~~~~~~~~~~~~~
| In file included from service/OneService.cpp:48:
| service/../osdep/Binder.hpp: In member function 'void ZeroTier::Binder::refresh(ZeroTier::Phy<PHY_HANDLER_TYPE>&, unsigned int*, unsigned int, std::vector<ZeroTier::InetAddress>, INTERFACE_CHECKER&)':
| service/../osdep/Binder.hpp:376:30: internal compiler error: unexpected expression '(std::__atomic_base<unsigned int>::__int_type)((ZeroTier::Binder*)this)->ZeroTier::Binder::_bindingCount' of kind implicit_conv_expr
|   376 |       _bindings[_bindingCount].udpSock = udps;
|       |                              ^
| Please submit a full bug report,
| with preprocessed source if appropriate.
| See <https://gcc.gnu.org/bugs/> for instructions.
| <builtin>: recipe for target 'service/OneService.o' failed
| make: *** [service/OneService.o] Error 1
| make: *** Waiting for unfinished jobs....
| osdep/LinuxEthernetTap.cpp: In member function 'void ZeroTier::LinuxEthernetTap::threadMain()':
| osdep/LinuxEthernetTap.cpp:477:24: warning: passing argument 3 to 'restrict'-qualified parameter aliases with argument 4 [-Wrestrict]
|   477 |   select(nfds,&readfds,&nullfds,&nullfds,(struct timeval *)0);

**Comment by diabonas** [comment]
I had the same issue with GCC 10 and provided a fix in #1232.

**Comment by diabonas** [comment]
This issue does not occur for me any more when compiling with GCC 10.2.0, so it probably was a compiler bug that is now solved.
