### ISSUE TITLE
Issues to compile osdep/LinuxNetLink.cpp on android

### ISSUE THREAD

**Issue by Gladox114** [zerotier/ZeroTierOne#1218]
I tried to compile the source code on my Android device but get a compile error

**To Reproduce**
get a phone with LineageOS and install termux then install g++,clang with pkg
clone the source code and make

**Expected behavior**
expected to successfully compile

**Screenshots**
https://pastebin.com/ZMZ9s6vt

Infos:
 - OS: LineageOS 17.1 (Android 10)
 - ZeroTier Version: Source code from june 21,2020
 - Hardware/Device: Samsung S4 active

I run it twice. The first time it took very long and at the end there came this error. The second time only the error came.

**Comment by glimberg** [comment]
Running ZeroTier outside of the version from the Google Play store isn't supported.
