### ISSUE TITLE
Suggest:ZeroTierOne add Wake On Lan.

### ISSUE THREAD

**Issue by siutung** [zerotier/ZeroTierOne#1220]
Hello there!
I want to use zerotier to replace teamviewer, but I usually use an important function in teamviewer: Wake On Lan.
But this feature is not available in zerotier, I hope zerotier can add this feature, thank you!

**Comment by laduke** [comment]
Hello,
ZeroTier is software. It can't run until the OS is started. 

But, you can use a tiny, always-on zerotier device or VM to bridge your physical LAN with a ZeroTier network. WoL can pass over the bridge.

**Comment by laduke** [comment]
Please comment with any more questions! Closing because we Can't Fix.

**Comment by RandomModderJDK** [comment]
Teamviewer wakes the pc behind the lan with another running pc. Zerotier could implement this mechanic as well. You could specify a zerotier address which can wake up your pc. You could then use e. g. zerotier central to wake up the pc remotely using the other pc as a bridge.
