### ISSUE TITLE
Zero tier - PC Shows Connected but is not working on local network

### ISSUE THREAD

**Issue by mikelakat** [zerotier/ZeroTierOne#1221]
hi,

After 1 year zero tier stopped to working on my pc. is showing that is working but i can not connect to other PCs on my local network. how can i resolve this issue?

i have uninstall and installed again but without any luck.

**Comment by joseph-henry** [comment]
In order for us to help you we need to know more about your setup and what you've tried. We have a bug report template for you to fill out for that purpose.

Have you changed any network settings? Is a firewall enabled?

**Comment by laduke** [comment]
Hey @mikelakat, see if anything in #1214 looks familiar
