### ISSUE TITLE
osx unable to access linux peer when a IP address is added via os 

### ISSUE THREAD

**Issue by cameronbraid** [zerotier/ZeroTierOne#1222]
running zerotier 1.4.6 on 2 linux and 1 osx host

All peers can see each other via ping of their IP which is assigned my.zerotier.com

on linux host A I assign an IP address 10.123.200.1 via the OS and run a http service on it
on linux host B I can ping and curl 10.123.200.1
on osx I cannot ping or curl 10.123.200.1

on linux host B I can see the arp entry

arp -e -i ztwdjmdyyc -n
```
Address                  HWtype  HWaddress           Flags Mask            Iface
10.123.0.1               ether   36:3b:12:1b:01:f7   C                     ztwdjmdyyc
10.123.200.1             ether   36:3b:12:1b:01:f7   C                     ztwdjmdyyc
```

on osx host there is no entry in the arp list
arp -a -i feth3297 -n
```
? (10.123.0.1) at 36:3b:12:1b:1:f7 on feth3297 ifscope [ethernet]
```

I tried apr-scan on osx for the IP
```
sudo arp-scan --interface=feth3297 10.123.200.1
Interface: feth3297, type: EN10MB, MAC: 36:d1:fb:f0:e4:47, IPv4: 10.123.0.2
Starting arp-scan 1.9.7 with 1 hosts (https://github.com/royhills/arp-scan)

4 packets received by filter, 0 packets dropped by kernel
Ending arp-scan 1.9.7: 1 hosts scanned in 1.354 seconds (0.74 hosts/sec). 0 responded
```

**Comment by cameronbraid** [comment]
I also tried adding a new IP to the linux host A via my.zerotier.com and I was able to access it from osx

**Comment by cameronbraid** [comment]
If I manually add the APR entry on osx everything works

`sudo arp -s 10.123.200.1 36:3b:12:1b:01:f7 ifscope feth3297`

`ping 10.123.200.1`
```
PING 10.123.200.1 (10.123.200.1): 56 data bytes
64 bytes from 10.123.200.1: icmp_seq=0 ttl=64 time=3.104 ms
64 bytes from 10.123.200.1: icmp_seq=1 ttl=64 time=2.723 ms
^C
--- 10.123.200.1 ping statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 2.723/2.913/3.104/0.191 ms
```

arp -a -i feth3297 -n
```                               
? (10.123.0.1) at 36:3b:12:1b:1:f7 on feth3297 ifscope [ethernet]
? (10.123.200.1) at 36:3b:12:1b:1:f7 on feth3297 ifscope permanent [ethernet]
```

**Comment by cameronbraid** [comment]
OSX is 10.15.5

**Comment by cameronbraid** [comment]
on the osx

zerotier-cli info
200 info 57c1c781bc 1.4.6 ONLINE

zerotier-cli listnetworks
200 listnetworks <nwid> <name> <mac> <status> <type> <dev> <ZT assigned ips>
200 listnetworks ######### drivenow 36:d1:fb:f0:e4:47 OK PRIVATE feth3297 10.123.0.2/16

cameronbraid@Camerons-MacBook-Pro ~> zerotier-cli listpeers
200 listpeers <ztaddr> <path> <latency> <version> <role>
200 listpeers 08de0b31c6 - -1 - MOON
200 listpeers 0f0d474926 27.50.81.41/9993;4472;14449 122 1.4.6 LEAF
200 listpeers 100318b7b2 - -1 1.4.6 LEAF
200 listpeers 3a46f1bf30 185.180.13.82/9993;4472;9283 194 - PLANET
200 listpeers 54de74be1f - -1 1.4.6 LEAF
200 listpeers 62f865ae71 50.7.252.138/9993;4472;4248 170 - PLANET
200 listpeers 6c5ef9cd5c - -1 - MOON
200 listpeers 778cde7190 103.195.103.66/9993;4472;4075 334 - PLANET
200 listpeers 9877d7eed8 64.235.52.10/9993;4472;4216 201 1.4.6 LEAF
200 listpeers 992fcf1db7 195.181.173.159/9993;4472;4075 339 - PLANET
200 listpeers a08f576480 64.235.52.11/9993;3075;3075 190 1.4.6 LEAF
200 listpeers b4b34308c7 49.145.97.151/33632;3251;3251 190 1.4.6 LEAF
200 listpeers bd092f02b8 168.1.123.248/1025;4472;89267 40 1.4.6 LEAF
200 listpeers bd282c640c 192.168.0.101/9993;604;602 91 1.4.6 LEAF
200 listpeers d5e5fb6537 35.236.27.3/21023;1910;1910 242 1.4.6 LEAF
200 listpeers ec867d7ef7 - -1 1.4.6 LEAF

**Comment by cameronbraid** [comment]
Interesting, I just tried an apring from a linux box and hit the same issue

Not sure what's going on.

When I add a managed ip it works, when I add the ip via os it doesn't

**Comment by adamierymenko** [comment]
How long did you wait? Did you give it a minute or two? It may take a minute for things to be advertised.
