### ISSUE TITLE
Doesn't work on Synology DS115j

### ISSUE THREAD

**Issue by jameaton** [zerotier/ZeroTierOne#1227]
I can get zerotier installed on a ds115J

**Comment by joseph-henry** [comment]
Hello @jameaton,

That model uses are very old processor design, try this package and let me know if you have trouble:

https://download.zerotier.com/RELEASES/1.2.8/dist/synology/zerotier-1.2.8r0-syn-armada370-6.1.spk

You'll want to use the CLI, not the GUI as that version has known bugs.
