### ISSUE TITLE
local.conf file not working on Windows

### ISSUE THREAD

**Issue by user398** [zerotier/ZeroTierOne#1228]
I need to change the default UDP port that ZeroTier listens on and for that I created a local.conf file with `{
    "settings": {
        "primaryPort": 52521,
    }
}` and placed it in "C:\Program Files (x86)\ZeroTier\One", but when I run `zerotier-cli -j info` I can see that the `primaryPort` is still `9003`.

**Comment by laduke** [comment]
Is that the same location as \ProgramData\ZeroTier\One ? It should be the directory that has a filed called identity.secret

Or, that trailing comma after 52521 is breaking it. JSON is picky.

**Comment by user398** [comment]
Solved. As you advised putting the local.conf in the same directory as identity.secret, specifically in  \ProgramData\ZeroTier\One, allowed me to change the default port 9993 to something else. The comma was a copy-paste mistake as I have more entries in the settings JSON and they need commas to separate them (except the last one). Thanks!
