### ISSUE TITLE
2 Zero Tier adapters everytime i install it

### ISSUE THREAD

**Issue by o0Julia0o** [zerotier/ZeroTierOne#1235]
hi, if i install Zero Tier there are alway 2 ZeroTier-Adapters installed. I can deinstall ZeroTier restart Windows and install ZeroTier and getting 2 ZeroTier adapters.

1. Install Zero Tier One
2. Restart the PC

Expected behavior:
I expect only 1 Zero Tier Ethernet Adapter to be installed and shown in the network-connections.

Screenshot:
https://imgur.com/a/eP95qa2

Operatin System: 
Windows 10 64bit - 1909 (Build 18363.959)

Zero Tier version:
1.4.6

**Comment by unquietwiki** [comment]
#1217 related?

**Comment by laduke** [comment]
There is an adapter for each joined network.

**Comment by o0Julia0o** [comment]
aha! Thx!
