### ISSUE TITLE
How can i save a ZeroTier-Adress for the next Windows-Re-Installation?

### ISSUE THREAD

**Issue by o0Julia0o** [zerotier/ZeroTierOne#1236]
hey, how can i save a ZeroTier adress for the next Winwos-reinstallation?

So you are authenticated by the ZeroTier-Network with your adress XY. Now you have to reinstall Windows10. How are you able to get the same zero-tier-adress again? So that you automatically are authenticated and known (with name) by the ZeroTier-network?

thank you

**Comment by laduke** [comment]
Save your identity.secret file. On Windows this is usually in `\ProgramData\ZeroTier\One`

https://zerotier.atlassian.net/wiki/spaces/SD/pages/327693/How+to+Clear+Reset+your+ZeroTier+Address

**Comment by o0Julia0o** [comment]
Thx, only the identity.secret or the identity.public, too?

**Comment by laduke** [comment]
Either way. You can save the networks.d folder too, if you want to it automatically join the same networks. 

Make sure you don't have the same identity running on multiple computers.

**Comment by laduke** [comment]
keep commenting if anymore questions thanks!
