### ISSUE TITLE
ZeroTier One iOS App Cannot Work With T-Mobile Cellular Data

### ISSUE THREAD

**Issue by CajunDoritos** [zerotier/ZeroTierOne#1238]
**Describe the bug**
When connecting to my ZeroTier network on my iPhone off of WiFi I am unable to contact the other devices in the network. However the little VPN badge does appear

**To Reproduce**
1. Have T-Mobile
2. Have an iPhone 7
3. Connect to your network
4. Attempt to contact a device on the network

**Expected behavior**
I would be able to contact my computer on cellular and use my Jellyfin server.
 
**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: iOS 14.0 Beta 3
 - Version: 1.4.6

**Additional context**
Presumably from my research this is an issue with the ZeroTier One app not taking advantage of IPv6 which causes T-Mobile to drop the connection as it does not support IPv4.

**Comment by unquietwiki** [comment]
@CajunDoritos sorry for the delayed reply on this; also recalled there was a helpdesk ticket that you or someone else filed recently. @laduke helped me find this: https://vsenn.com/what-are-the-t-mobile-vpn-settings/

**Comment by adamierymenko** [comment]
Also tested on T-Mobile and it seems to work fine.
