### ISSUE TITLE
Little confused about the moon peers.

### ISSUE THREAD

**Issue by m4d3bug** [zerotier/ZeroTierOne#1239]
1. Does moon peers have to join any network id as the moon peers?
2. If A and B facing the timeout issue, how the moon peers help them, working on the TCP or UDP?
3. If there possible to use one moon peer to service two intranets without join them? 
4. If I need to make two intranets can access each other, how can I add these routes in the machine(iptables, ip route) or the website dashboard?

**Comment by joseph-henry** [comment]
It doesn't sound like moons are the solution to your problem. 

I'd check out the routing and bridging entries here: [Knowledge Base](https://zerotier.atlassian.net/wiki/spaces/SD/pages/7110657/Networking)

Going to close this ticket but if you're still having issues please open another ticket.
