### ISSUE TITLE
Problem resuming from sleep on Windows

### ISSUE THREAD

**Issue by adamierymenko** [zerotier/ZeroTierOne#124]
Reported by user -- ZeroTier not working after resume from sleep. Investigate.

**Comment by heri16** [comment]
Can we reopen this ticket as zerotier v1.0.3 still does not recover from Windows 8.1 sleep and resume.

**Comment by m-wvj** [comment]
can we reopen? Version 1.6.5, almost never works after windows 10 (multiple versions, been checking since 3 months at least) falls asleep.

I can provide any data you would want from my system, just specify what would you need :)

**Comment by laduke** [comment]
Hi @m-wvj, please make a new ticket. 👍
