### ISSUE TITLE
Connection Troubleshooting

### ISSUE THREAD

**Issue by zKyros** [zerotier/ZeroTierOne#1244]
**Describe the bug**
I was trying to make a modded minecraft server to play with a friend, so i created a zerotier network autorized him and me, so i setted the server and setted the ip to my zerotier ip. Thats right? Because my friend cant connect. He receives a message that says and error but thats codified.

**To Reproduce**
1. Create a Network
2. Install zerotier-one
3. Once connected and authorized said to him to connect

**Expected behavior**
He adds the server to the server list and we play for about an hour.

**Desktop (please complete the following information):**
 - OS: Windows
 - OS/Distribution Version: Updated to the latest I dont know what exactly 
 - ZeroTier Version: Latest
 - Hardware 32Gb of RAM/i7-8700K/1060 With 6Gb/Asus PRIME Z370-A II

**Comment by unquietwiki** [comment]
@zKyros can you get us a screenshot of the error please? Thanks!

**Comment by unquietwiki** [comment]
https://www.reddit.com/r/zerotier/comments/iaowup/connection_troubleshooting/ Also saw your Reddit post

**Comment by unquietwiki** [comment]
https://zerotier.atlassian.net/wiki/spaces/SD/pages/521011201/Windows+Troubleshooting @zKyros and others, this is now a resource you can try.

**Comment by joseph-henry** [comment]
@zKyros Have you tried anything mentioned here?

https://zerotier.atlassian.net/wiki/spaces/SD/pages/7536695/Problems+With+LAN+Game+Announcements+and+Broadcasts+on+Windows

**Comment by reverse-engineering-dev** [comment]
Hi, I have same error!I use version 1.2.12, working fine.

**Comment by joseph-henry** [comment]
I would suggest trying latest `1.6.5`, if the issue still persists feel free to re-open. Thanks.
