### ISSUE TITLE
Invalid ranges

### ISSUE THREAD

**Issue by StefanoBalocco** [zerotier/ZeroTierOne#1251]
Hello,
using ranges like 192.0.2.0/24, 203.0.113.0/24 or 198.51.100.0/24 (TEST-NET) or 198.18.0.0/15 (benchmark) require the use of AllowGlobal=true.
Those address aren't routable on internet, shouldn't they considered not global?

**Comment by laduke** [comment]
Yeah. 

https://en.wikipedia.org/wiki/Reserved_IP_addresses

Multiple people asked about this in the last month, and before that I can't remember anyone mentioning it. Weird. 

We have a todo for the my.zerotier.com UI, but needs to be done here too.

**Comment by glimberg** [comment]
Fixed in the dev branch.  Will be in the upcoming 1.6 release
