### ISSUE TITLE
No aarch64 Package for Alpine Linux

### ISSUE THREAD

**Issue by rehashedsalt** [zerotier/ZeroTierOne#1254]
Seems like there's an x86_64 build in the Alpine repos:

https://pkgs.alpinelinux.org/package/edge/community/x86_64/zerotier-one

But no aarch64 one:

https://pkgs.alpinelinux.org/packages?name=zerotier-one&branch=edge&repo=community&arch=aarch64

Per #598 builds are maintained for Arch, SuSE, and Fedora, but not for Alpine.

Building an aarch64 package for Alpine would be of great benefit to users who would like to run ZeroTier in an Alpine container on aarch64 or rope something like a PostmarketOS device into their network.

**Comment by ukd1** [comment]
@rehashedsalt I just got a PostmarketOS device, and was googling how to get zerotier installed. Would love this! I think from reading @adamierymenko took over the original packaging for alpine, maybe he could help?

**Comment by adamierymenko** [comment]
This is actually an Alpine issue, not ours. We don't maintain the Alpine package.

**Comment by Pavel-Matskevich** [comment]
F
