### ISSUE TITLE
How to orbit moon on android and ios devices?

### ISSUE THREAD

**Issue by xiaolilir** [zerotier/ZeroTierOne#1255]

**Comment by laduke** [comment]
Hello.
There isn't a way to do that. Sorry. We're aware of the issue, but will probably fix it in some other way.

**Comment by KrisCris** [comment]
Looking forward to this feature...

**Comment by oldskooler** [comment]
Looking forward to this feature...

**Comment by isakrubin** [comment]
Looking forward to this feature...

**Comment by maxesisn** [comment]
Looking forward to this feature...

**Comment by pureal** [comment]
Looking forward to this feature...

**Comment by TouiSoraHe** [comment]
Looking forward to this feature...

**Comment by fengci** [comment]
Looking forward to this feature...

**Comment by titianqx** [comment]
Looking forward to this feature...
