### ISSUE TITLE
network API https://my.zerotier.com/api/network/ + networkId

### ISSUE THREAD

**Issue by CharlPels** [zerotier/ZeroTierOne#1258]
Looking for a working sample to update zeroTier networks.

for nodes I use something like this

    data = '{ "config": {"authorized": ' + authorized + '}, "name": "' + name + '", "description": "' + description + '"  }'
    API_ENDPOINT = "https://my.zerotier.com/api/network/" + networkId + "/member/" + nodeId
    zeroTierN_access_for_node = requests.post(API_ENDPOINT, headers=headers, data=data)

However simple tings like 

    data = '{"config": {"routes":[{"target": "192.168.193.0/24"}],"private":true,"name": "test_Network1"}}'
    API_ENDPOINT = "https://my.zerotier.com/api/network/" + networkId 
    zeroTierN_access_for_node = requests.post(API_ENDPOINT, headers=headers, data=data)

dont seem to work and endup with a Bad Gateway error however when I deploy a new network API_ENDPOINT = "https://my.zerotier.com/api/network/" it works fine and even updating is not an issue for a short time
The I again have 502 bad gateway issues

**Comment by laduke** [comment]
Hard to tell from here. Might have been unlucky timing if you were getting Bad Gateway. 

Can you post on the forum https://discuss.zerotier.com/ ? thanks!

**Comment by glimberg** [comment]
If it was a 502, you just happened to be calling that while an update was being pushed.
