### ISSUE TITLE
ZT on Linux cannot communicate with leaf on LAN (similar to #1214)

### ISSUE THREAD

**Issue by ayhc** [zerotier/ZeroTierOne#1259]
**Describe the bug**
ZT on Linux claims to be online, and other planets and leaves are visible.  However, trying to connect to a leaf using its ZT-assigned address fails ("no route to host").

**To Reproduce**
1. Install ZT on laptop running Fedora 32 and Synology NAS (both on the same home network).
2. Create a simple ZT network with default rules.
3. On a fresh boot of the laptop, run "sudo zerotier-cli status" and "sudo zerotier-cli listpeers". Observe that the status command returns "ONLINE" and that there are peers listed.
4. Try to connect to the NAS using its ZT-assigned address. Error ("no route to host") occurs.

**Expected behavior**
The laptop connects to the NAS through its ZT-assigned address.

**Laptop (please complete the following information):**
ZT version 1.4.6 on Fedora 32 (x64 laptop)

**NAS**
Synology x64 NAS

**Additional context**
Forcing the zerotier-one service to restart typically fixes the problem (although unlike #1214 I have not had to wait several minutes before restarting).

**Comment by ayhc** [comment]
As a workaround, I have created a systemd service that restarts ZT after the laptop connects to a network:

**/etc/zt_restart/zt_restart.sh**
 ```
#!/bin/bash

#Target device's Zerotier IP here
TGT_IP=ADD YOUR TARGET'S ZT IP HERE

#Ping the target and grep for error message
x=`ping -c1 $TGT_IP 2>&1 | grep Unreachable`

#Restart ZT if unable to ping target
if [ ! "$x" = "" ]; then
        systemctl restart zerotier-one
fi
```

**/etc/systemd/system/zt_restart.service**
```
[Unit]
Description=Restart Zerotier service as bug workaround
After=network-online.target

[Service]
Type=oneshot
ExecStart=/bin/bash /etc/zt_restart/zt_restart.sh

[Install]
WantedBy=basic.target
```

**Comment by joseph-henry** [comment]
Does this still occur in `1.6.5`?

**Comment by jbcpollak** [comment]
I had this problem today, both hosts on 1.6.5, but only using hostnames, using IP seemed to work. Remotely, using hostnames works. I'm not sure if that is the same issue as this

**Comment by joseph-henry** [comment]
Closing due to age and suspicion that the issue was resolved by https://github.com/zerotier/zerotier-systemd-manager/pull/10
