### ISSUE TITLE
Zerotier under Windows 10

### ISSUE THREAD

**Issue by Sapiens2020** [zerotier/ZeroTierOne#1260]
Hi,
I have installed Zerotier in my LAN with a client in a Synology and a second one in a Windows 10 PC fron another Windows 10 PC both Windows have ZT clien installed and connected to the ZT network. I can access Synology easily. However  I cannot access Windows 10 under the same LAN network. Ports 9993 are opened and Should I install ZT in the router to access the Windows PC behind it?
Thanks

**Comment by unquietwiki** [comment]
Hey @Sapiens2020 . This kind of question might better be answered on https://discuss.zerotier.com/ . Otherwise, https://zerotier.atlassian.net/wiki/spaces/SD/pages/521011201/Windows+Troubleshooting might help you out specifically. Thanks!
