### ISSUE TITLE
Zerotier API/zerotier-cli race condition

### ISSUE THREAD

**Issue by ILoveYaToo** [zerotier/ZeroTierOne#1267]
1. What do you expect to be happening?
API call to get information about the node on a private network is successful
2. What is actually happening?
API call returns 404.
3. Any steps to reproduce the error.
Join a network on a node, and immediately call the `api/network/{networkId}/member/{nodeId}` API call to retrieve information about the network

Running the following in bash works quite well. Adding a sleep in between the join and the curl mitigates the issue.
```
zerotier-cli join {networkId}
curl -H "Authorization: bearer <apikey>" https://my.zerotier.com/api/network/{networkId}/member/{nodeId}
```

**Comment by glimberg** [comment]
Not a bug.  It takes a little time for the client to contact the network and get initialized in the system.
