### ISSUE TITLE
Zerotier Virtual Interface appears as "unplugged" in a bridge config

### ISSUE THREAD

**Issue by aescolastico** [zerotier/ZeroTierOne#1268]
- What you expect to be happening.
-- Routing to remote LAN for ZT network members via windows network bridge.
- What is actually happening?
-- Ping fails to ZT interface when interface is member of bridge
-- Ping succeeds when ZT interface succeeds
-- ZT interface on remote LAN PC appears as "Cable Unplugged"

## Additional information 

**Desktop (please complete the following information):**
 - OS: Windows
 - OS/Distribution Version: 10 x64 v1909
 - ZeroTier Version: 1.4.4

**Additional context**
- ZeroTier Network Configuration: 
-- Managed Routes
--- 10.69.82.0/24(REMOTE LAN) via 172.25.77.171 (ZT Member on remote LAN)
--- 172.25.0.0/16(ZT LAN)
-- Members
--- 172.25.77.171 - Windows PC on remote LAN (Allow bridging enabled) 
--- 172.25.25.128 - MAC on local LAN (Source of PING tests)

**Comment by adamierymenko** [comment]
Bridging on Windows is really not supported. Windows bridging doesn't support differing MTU values and is really quite primitive compared to Linux bridging. Same goes for MacOS. Linux is the only OS where we have had consistent bridging success as its networking layer is much more powerful and mature and is more commonly used in router scenarios.

We have considered building a software / user mode bridge for Windows leveraging pcap or similar libraries, but that's on the backlog.
