### ISSUE TITLE
MacOS cannot ping other MacOS and Linux devices

### ISSUE THREAD

**Issue by chesskuo** [zerotier/ZeroTierOne#1269]
I have two MacBooks, one Win10 desktop and one Raspberry Pi in the same network.
In few month ago, these devices can work perfectly.
Suddenly, Mac devices cannot ping each other.
And Mac cannot ping Raspi, Raspi cannot ping Mac devices too.
But Raspi and Win10 can still work each other.

## **System Info :**
 - OS :
    - MacOS : `10.15.4`
    - Win10 : `1909`
    - Raspi : `2020-08-20-raspios-buster-arm64-lite`
 - ZT ver. : `1.4.6`

**Comment by yinyiyu** [comment]
I have meet the same question , do you hand solved the problem

**Comment by chesskuo** [comment]
@yinyiyu 
Not yet~
I have no idea ...

**Comment by joseph-henry** [comment]
Should be fixed in `1.6.5`. Re-open if you still see the same issue. Thanks
