### ISSUE TITLE
[Documentation Request] Adding a Name/Description to members via Controller API

### ISSUE THREAD

**Issue by antcoz** [zerotier/ZeroTierOne#1271]
I'm struggling to find any information on how to add a Name/Description to members via Controller API as present in the following column:

![image](https://user-images.githubusercontent.com/63824017/95430337-3c78a180-097e-11eb-803c-05e286bf24ef.png)

Am I not looking hard enough?

Thanks in advance.

**Comment by laduke** [comment]
Hello
the controller API doesn't have member names. 
https://github.com/zerotier/ZeroTierOne/tree/master/controller

my.zerotier.com / Central has member names. 
https://my.zerotier.com/help/api
