### ISSUE TITLE
Device Temporarily Disconnects from Network When Under Heavy CPU Load

### ISSUE THREAD

**Issue by jaredlander** [zerotier/ZeroTierOne#1273]
This is a tough one to reproduce and I apologize that I am not making it easy.

This bug has been occuring more and more lately. I mostly use ZeroTier to connect to a server at my office. This is essentially a desktop with powerful components, running Ubuntu Server 18.04, no desktop environment. It is connect via ethernet to the office network. We don't have access from outside through the firewall, hence ZT.

This machine is mainly used by just me, and mainly for heavy data science workloads. The problem occurs when running computationally intensive code. I don't think it is memory related, because my RAM usage is usually below 50% while my CPU usage often spikes one or more cores.

The code in question is more data manipulation, not even anything machine learning related. Sometimes the job is a parallel job, other times single core.

What happens is, when a job that consumes a lot of CPU, my browser-based IDE (RStudio Server Pro) will hang and any ssh sessions into the box (connected to using the ZT IP address) will disconnect, and the ZT dashboard will show the machine as offline. Over the course of the next 20 minutes to ten hours, the dashboard will occasionally show the machine as being online, only to switch to offline again soon thereafter. After the 20 minutes to ten hours the machine comes back fully online and can be connected to via ZT IP addresses. Due to COVID I do not have physical access to the machine so I can't verify if I can log in via other means during this offline period.

Given this occurs regularly when the system is under load and that the server doesn't completely crash, I have a hunch that ZT simply goes down after load.

After further testing it is became more consistent. Most recently the failure occured when running 6 cores. The machine has 6 physical cores and 12 logical cores. Testing this out is tough because each failure takes hours for me to regain access.

- This occurs both with OpenMP (via the `{data.table}` package) and of forms of parallelism (the `{future}` and `{future.callr}` packages).
- There is no network traffic involved. It’s all data manipulation.
- It’s hard to tell when the job completes vs when I gain back access.
- The machine is under a desk away from other electronics. The NIC is on the motherboard, which might be MSI. It should be a Z370 or Z390 chipset.

At first I thought it was being caused by the IDE, RStudio Server Pro. But the same code using R from an ssh shell caused the failure.

ZT support suggested I post this issue here and had the following message:

> It sounds like your task is simply saturating all of your cores leaving no breathing room for anything else. I’d try dialing that back a little (in whatever way OpenMP allows) so userspace applications (like ZT) can still do work.

This is tough to debug since the failures last so long, but would be great solve.

**Comment by laduke** [comment]
That's... interesting. I don't know how to fix the bug, but you could probably invent something to restart zerotier when it's stuck. 

Or maybe just do like  `your-compile-command; sudo systemctl restart zerotier-one`

**Comment by jaredlander** [comment]
At least for me, that would be hard to do. I run the processes ad hoc in a REPL. I would almost need a job that restarted ZT every minute, but that seems terrible.

**Comment by glimberg** [comment]
At any rate, this is a configuration problem on your system, not a bug in ZeroTier.

**Comment by laduke** [comment]
@jaredlander is zerotier dead for 20mintues/10 hours _after_ the computations are done?

**Comment by jaredlander** [comment]
@laduke ZT craps out pretty quickly after kicking off the process. Then it's out for the extended period of time. At some point in there the computations stop, though I don't know if they were successful or not.
