### ISSUE TITLE
Menubar app provides incorrect error message if launchd daemon is stopped

### ISSUE THREAD

**Issue by tas50** [zerotier/ZeroTierOne#1276]
**What you expect to be happening**

When launching the menu bar application on a macOS host, if the launchd daemon for zt is not running the error message should state that.

**What is actually happening?**

The error message says "Could not connect to the server", which is a bit confusing because that makes it sound like an issue connecting to the controller.

**Any steps to reproduce the error**

- Quit menu bar application
- Stop the launchd daemon
- Start menu bar application

**Any screenshots that would help us out**

![Screen Shot 2020-10-13 at 10 02 13 AM](https://user-images.githubusercontent.com/1015200/95892666-b4a6e480-0d3b-11eb-982e-590478ce701a.png)

## Additional information 

**Desktop (please complete the following information):**
 - OS: macOS
 - OS/Distribution Version: 10.15.6
 - ZeroTier Version [e.g. 1.4.6]

**Comment by joseph-henry** [comment]
I agree. This is a bit misleading. We might make a slight adjustment to the wording in a future version. Thanks for pointing this out.

**Comment by adamierymenko** [comment]
Yeah, this is a known issue. The current tray app is something we'd eventually like to replace, but we could change that error text for sure.

**Comment by BoWang816** [comment]
I have the same question

**Comment by BoWang816** [comment]
what should I do?
![image](https://user-images.githubusercontent.com/26587649/104401798-e411fb00-558f-11eb-858d-d25e2c2d5623.png)

**Comment by joseph-henry** [comment]
This is fixed and will be available in the next major release. Thanks
