### ISSUE TITLE
[Feature Request] Make ZeroTiers GPG key available over IPv6

### ISSUE THREAD

**Issue by phaer** [zerotier/ZeroTierOne#1277]
Official tutorials recommend to fetch the projects GPG key for signature verification from

`https://raw.githubusercontent.com/zerotier/ZeroTierOne/master/doc/contact%40zerotier.com.gpg`

Which is fine as long as one got IPv4 connectivity on that machine, but as GitHub seemingly still does not support IPv6, an additional official mirror for the key would be highly appreciated!

When I copy the key from my workstation beforehand, the rest of the setup seems to work fine without any IPv4 on the system, so in my understanding it's just a key mirror with IPv6 connectivity which is missing for that use case.

What do you think?

**Comment by adamierymenko** [comment]
Well that's lame.

You can get it here. We should make the script try this as a secondary.

https://download.zerotier.com/contact@zerotier.com.gpg

**Comment by phaer** [comment]
Thanks, just saw that the installer is in another repository and opened an issue there https://github.com/zerotier/install.zerotier.com/issues/19
