### ISSUE TITLE
Cannot connect to http://download.zerotier.com/

### ISSUE THREAD

**Issue by Pyrokine** [zerotier/ZeroTierOne#1279]
After executing "curl -s https://install.zerotier.com | sudo bash" on my Debian 9 NAT VPS, it showed
【
*** Found Debian "stretch" (or similar), creating /etc/apt/sources.list.d/zerotier.list
OK

*** Installing zerotier-one package...
Ign:1 http://mirrors.tuna.tsinghua.edu.cn/debian stretch InRelease
Hit:2 http://mirrors.tuna.tsinghua.edu.cn/debian stretch Release
Err:4 https://download.zerotier.com/debian/stretch stretch InRelease
  Connection timed out after 120000 milliseconds
Reading package lists... Done
W: Failed to fetch https://download.zerotier.com/debian/stretch/dists/stretch/InRelease  Connection timed out after 120000 milliseconds
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package zerotier-one

*** Package installation failed! Unfortunately there may not be a package
*** for your architecture or distribution. For the source go to:
*** https://github.com/zerotier/ZeroTierOne
】
I could however ping the server "download.zerotier.com" successfully and got
【
ping download.zerotier.com
PING dualstack.q3.shared.global.fastly.net (151.101.2.217) 56(84) bytes of data.
64 bytes from 151.101.2.217 (151.101.2.217): icmp_seq=1 ttl=51 time=95.8 ms
64 bytes from 151.101.2.217 (151.101.2.217): icmp_seq=2 ttl=51 time=100 ms
64 bytes from 151.101.2.217 (151.101.2.217): icmp_seq=3 ttl=51 time=114 ms
64 bytes from 151.101.2.217 (151.101.2.217): icmp_seq=4 ttl=51 time=129 ms
64 bytes from 151.101.2.217 (151.101.2.217): icmp_seq=5 ttl=51 time=153 ms
64 bytes from 151.101.2.217 (151.101.2.217): icmp_seq=6 ttl=51 time=162 ms
64 bytes from 151.101.2.217 (151.101.2.217): icmp_seq=7 ttl=51 time=171 ms
64 bytes from 151.101.2.217 (151.101.2.217): icmp_seq=9 ttl=51 time=151 ms
^C
--- dualstack.q3.shared.global.fastly.net ping statistics ---
10 packets transmitted, 8 received, 20% packet loss, time 9039ms
rtt min/avg/max/mdev = 95.825/134.748/171.118/27.077 ms
】
I wander what should I do or check. Thanks a lot

**Comment by Pyrokine** [comment]
I have built the app from source by gcc. But I failed to join the network.
【
zerotier-cli join xxxxxxxxxxxxxxxx
0 join connection failed
】

**Comment by reesericci** [comment]
did u start the service with `systemctl start zerotier-one`?

**Comment by Pyrokine** [comment]
> did u start the service with `systemctl start zerotier-one`?

sure

**Comment by glimberg** [comment]
can't reproduce

**Comment by willawork** [comment]
`curl -vv https://download.zerotier.com/debian/stretch/dists/stretch/InRelease`  will give you some good debug information about trying to establish the connection.

**Comment by Pyrokine** [comment]
> can't reproduce. server is up & responding as expected to both IPv4 and IPv6 requests, both HTTP and HTTPS.

Thanks for reply and I cannot reproduce it either. Maybe it's just a fluctuation. On top of that, importing public key is necessary when using 3rd-party mirror.
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1657198823E52A61

**Comment by Pyrokine** [comment]
> `curl -vv https://download.zerotier.com/debian/stretch/dists/stretch/InRelease` will give you some good debug information about trying to establish the connection.

I will try it when it can be reproduced.
