### ISSUE TITLE
Dockerfile broken

### ISSUE THREAD

**Issue by reesericci** [zerotier/ZeroTierOne#1280]
## Required

- What you expect to be happening.
Docker image building correctly
- What is actually happening?
Error on the COPY: ```Step 5/17 : COPY ext/installfiles/linux/zerotier-containerized/main.sh /var/lib/zerotier-one/main.sh
COPY failed: stat /var/lib/docker/tmp/docker-builder823182268/ext/installfiles/linux/zerotier-containerized/main.sh: no such file or directory```
- Any steps to reproduce the error.
Build the docker image
- Any screenshots that would help us out.
N/A

## Additional information 

**Desktop (please complete the following information):**
 - OS: [e.g. Mac, Linux, Windows, BSD] Ubuntu (but using docker)
 - OS/Distribution Version 20.04 server
 - ZeroTier Version [e.g. 1.4.6] N/A

**Comment by glimberg** [comment]
```
docker build -f ext/installfiles/linux/zerotier-containerized/Dockerfile -t my-tag .
```

**Comment by reesericci** [comment]
ok so don't just grab the dockerfile and main.sh. Grab the whole repo, thx.
