### ISSUE TITLE
SELinux context issues for zerotier-one 1.5.0

### ISSUE THREAD

**Issue by willawork** [zerotier/ZeroTierOne#1281]
Just installed ZT1.5.0 into a fresh Centos7 install from the PRERELEASE RPM (rpm -i zerotier-one-1.5.0-1.el7.x86_64.rpm)

Went to start the service (systemctl start zerotier-one) it repeatedly failed.  Running the binary directly results in a segfault:
```
# zerotier-one
Segmentation fault
#
```

strace gave a little more information:
```
#strace zerotier-one
execve("/usr/sbin/zerotier-one", ["zerotier-one"], 0x7fff335277e0 /* 33 vars */) = -1 EACCES (Permission denied)
--- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=NULL} ---
+++ killed by SIGSEGV +++
Segmentation fault
#
```

Digging round, I found that /var/lib/zerotier-one was still owned by root:root, so fixed that.  Still getting the same segfault, but went from 33 vars to 34 vars.

I thought it was something to do with user permissions or something, so using strace I set the userID to zerotier-one:
```
# strace -u zerotier-one /usr/sbin/zerotier-one
execve("/usr/sbin/zerotier-one", ["/usr/sbin/zerotier-one"], 0x7ffc4f778910 /* 34 vars */) = -1 EPERM (Operation not permitted)
--- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=NULL} ---
+++ killed by SIGSEGV +++
Segmentation fault
#
```

On a suggestion I set SELinux to permissive and off it went and is running fine now.  I think it's possibly the wrong (or no) context was loaded for /var/lib/zerotier-one.  We have nodes running 1.4.6 with SELinux enforcing without an issue.

OS: CentOS Linux release 7.8.2003 (Core) x86_64
CPU: Intel(R) Xeon(R) D-2145NT
Zerotier version:   1.5.0-1.el7.x86_64
No firewall configured, in Lab network (so behind a firewall)

**Comment by adamierymenko** [comment]
This particular aspect of the code has not changed since 1.4.6, and we've never included anything SELinux-specific in our build process at all. Does your system give you any more detail about exactly what permission or constraint was violated? @willawork

**Comment by willawork** [comment]
audit log show the below output.  both times `zerotier-one -d` was executed.

with `setenforce 1`:

`
type=AVC msg=audit(1605068301.645:293382): avc:  denied  { mmap_zero } for  pid=37144 comm="zerotier-one" scontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tcontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tclass=memprotect permissive=0

type=SYSCALL msg=audit(1605068301.645:293382): arch=c000003e syscall=59 per=400000 success=no exit=-13 a0=1e0bf60 a1=1e1cac0 a2=1dee750 a3=7ffe3810f420 items=0 ppid=36972 pid=37144 auid=0 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=pts1 ses=41828 comm="zerotier-one" exe="/usr/sbin/zerotier-one" subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 key=(null)

type=PROCTITLE msg=audit(1605068301.645:293382): proctitle="(null)"

type=ANOM_ABEND msg=audit(1605068301.645:293383): auid=0 uid=0 gid=0 ses=41828 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=37144 comm="zerotier-one" reason="memory violation" sig=11
`

with `setenforce 0`:

`
type=AVC msg=audit(1605068344.404:293400): avc:  denied  { mmap_zero } for  pid=37311 comm="zerotier-one" scontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tcontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tclass=memprotect permissive=1

type=SYSCALL msg=audit(1605068344.404:293400): arch=c000003e syscall=59 per=400000 success=yes exit=0 a0=1e0c250 a1=1e1cb80 a2=1dee750 a3=7ffe3810f420 items=0 ppid=36972 pid=37311 auid=0 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=pts1 ses=41828 comm="zerotier-one" exe="/usr/sbin/zerotier-one" subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 key=(null)

type=PROCTITLE msg=audit(1605068344.404:293400): proctitle="zerotier-one"

type=SERVICE_START msg=audit(1605068344.464:293401): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=NetworkManager-dispatcher comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
`

**Comment by hannut** [comment]
I have the same problen with Fedora Silverblue 33 and zerotier 1.6.0

# zerotier-cli info
Segmentation fault
# setenforce 0
# zerotier-cli info
Error connecting to the ZeroTier service: connection failed

Please check that the service is running and that TCP port 9993 can be contacted via 127.0.0.1.
#

**Comment by bltavares** [comment]
I currently faced the same issue on Zerotier 1.6.0, but running from inside Docker Containers, which have apparmor and seccomp enabled.

Using the last message from @hannut, I was able to [search for the capability](https://man7.org/linux/man-pages/man7/capabilities.7.html) which would allow to call mmap below the minimum defined value, and get zerotier up online once again.

On `docker run`, I added `--cap-add=CAP_SYS_RAWIO` to get executables running once again.

**Comment by kensel** [comment]
Just updated from 1.4.6 to 1.6.0-1.el7 on Centos 8 bare-metal  with SELinux enabled and received the same segmentation fault error.  setting SELinux to permissive allows ZeroTier to run.

`# cat /etc/redhat-release`
`CentOS Linux release 8.2.2004 (Core)`

`# dnf list --installed | grep -i zerotier`
`zerotier-one.x86_64                  1.6.0-1.el7                     @ZeroTier`

**Comment by glimberg** [comment]
Workaround for SELinux is the following:

```
setsebool -P mmap_low_allowed 1
```

**Comment by glimberg** [comment]
1.6.1 is now out.  Solves this issue.
