### ISSUE TITLE
Mac OS client breaks internet connection, and can't see other peers.

### ISSUE THREAD

**Issue by johtso** [zerotier/ZeroTierOne#1282]
## Required

When I connect to ZeroTier, everything looks like it's connecting properly, but I can no longer reach any websites until I restart my wifi connection.

the zerotier service also does not seem to see the raspberry pi peer, but is connected to the network.

zerotier-cli info:
200 info 520d87a2ad 1.4.6 ONLINE

zerotier-cli peers:
```
200 peers
<ztaddr>   <ver>  <role> <lat> <link> <lastTX> <lastRX> <path>
3a46f1bf30 -      PLANET   189 DIRECT 11276    11038    185.180.13.82/9993
62f865ae71 -      PLANET   287 DIRECT 11276    10995    50.7.252.138/9993
778cde7190 -      PLANET   134 DIRECT 11276    11149    103.195.103.66/9993
8850338390 1.4.8  LEAF     233 DIRECT 11031    10528    34.94.72.151/47298
992fcf1db7 -      PLANET    82 DIRECT 11031    11205    195.181.173.159/9993
```
(Only shows network LEAF, not the raspberry pi, which does show as connected on the web dashboard)

## Additional information 

**Desktop (please complete the following information):**
 - OS: Mac OS
 - OS/Distribution Version: 10.15.5 (19F101)
 - ZeroTier Version: 1.4.6

**Additional context**
- Router Config: no router config
- Firewall Config: no firewall
- Are you using this at home, in an office, college, etc: At home. Mac OS connected via home router, raspberry pi connected via mobile hotspot.

**Comment by laduke** [comment]
Hi,
That's pretty strange. Does it happen if you remove the 192.168.x.x managed routes?

**Comment by johtso** [comment]
Removing them stops that behaviour. I'm guessing it was stopping me from talking to my router.. (192.168.1.254)

I'm guessing this is kind of unavoidable if the subnet you are in clashes with the subnet you want to tunnel into..

**Comment by glimberg** [comment]
Yes, this is expected behavior if your IP/managed route configuration for your ZeroTier network conflicts with your LAN.
