### ISSUE TITLE
zerotier-one-1.5.0-1 bugs

### ISSUE THREAD

**Issue by l35m** [zerotier/ZeroTierOne#1286]
Hi, using the new version of the application I noticed a number of bugs.

Some of them may already be known, but I will list them:

->Problems connecting to planets version 1.5.0 after rebooting the daemon on the client.
"Solution": you need to restart Zerotier-One on the planet
Clients 1.4.6 сonnect to planet version 1.5.0  normally.

->Loss of multicast packets:
Keepalived performs very strange switches.

->The service often freezes when the node is turned off.
Systemd kills it on timeout.

OS: Archlinux-5.9.3
Zerotier-One: 1.5.0
Pacman packet: zerotier-one-1.5.0-1

**Comment by Mikesco3** [comment]
my zerotier wouldn't would crash also right after upgrading to 1.5.0-1 (running Manjaro xfce)
downgraded to the snap running 1.4.6 and works fine 
I'm not sure what (restarting Zerotier-One on the planet means)

**Comment by adamierymenko** [comment]
Crash dumps would be quiet helpful, yes @Mikesco3

**Comment by Mikesco3** [comment]
I've attached a zip file with 3 crash dumps

[zerotier-coredumps_20201109.zip](https://github.com/zerotier/ZeroTierOne/files/5514234/zerotier-coredumps_20201109.zip)
