### ISSUE TITLE
High CPU usage in KeSynchronizeExecution

### ISSUE THREAD

**Issue by diversys** [zerotier/ZeroTierOne#1290]
Windows Server 2012 running ZeroTier Version 1.4.6 configured and working fine.
However, zerotier-one_x64.exe suddenly starts to eat 1 CPU core. Happened about 5 times over the last 2 weeks.

<img width="1440" alt="Screenshot 2020-11-11 at 16 12 36" src="https://user-images.githubusercontent.com/1316513/98820270-fdd37c80-243e-11eb-939b-eee311307c8a.png">

**Comment by Mackstoresdotcom** [comment]
well in mine win 10 it ate all the ram and the hdd usage was 100%

**Comment by joseph-henry** [comment]
@diversys Are you still seeing this behavior? If so, can you provide any details about your usage? Also it looks like Microsoft has EOL'ed Windows Server 2012. While we would like to see ZT working on just about everything we try to focus on things that are still supported.

@Mackstoresdotcom That sounds like an entirely different problem. If you are still experiencing that issue could you please create a ticket?
