### ISSUE TITLE
macOS client doest not respect primaryPort setting on local.conf

### ISSUE THREAD

**Issue by sbilly** [zerotier/ZeroTierOne#1293]
macOS client doest not respect primaryPort setting on local.conf. 

## Additional information 

**Desktop (please complete the following information):**
 - OS: macOS
 - OS/Distribution Version
 - ZeroTier Version: 1.4.6
  
local.conf
```
{
    "settings": {
        "primaryPort": 9123
    }
}
```

![image](https://user-images.githubusercontent.com/123563/99202044-d71f9800-27e8-11eb-85ca-78ec5d415547.png)

**Comment by thoradia** [comment]
This could be a duplicate of #1252, which is fixed by #1257

**Comment by sbilly** [comment]
It's different case.

The zerotier-one and the virtual network interface are working, while GUI is not working with primaryPort in local.conf.

**Comment by joseph-henry** [comment]
Thanks for pointing this out. I'll try to get this into one of our next releases.

**Comment by joseph-henry** [comment]
Update: We have fixed this internally and it will make it into the next major release.
