### ISSUE TITLE
A moon root and a node can not reach each other, while the moon reports `DIRECT` link to the node

### ISSUE THREAD

**Issue by lideming** [zerotier/ZeroTierOne#1295]
I have a moon root **A** (also acts as the controller) on a server with a static IPv4 address on the internet.
A local server **B** is orbiting the moon.
A laptop **C** is in the same LAN with **B**.
**A**, **B** and **C** have joined the same ZT network.
They usually works fine.

But at the moment, A and B can not reach each other in the ZT network. Pinging from B to A reports `Destination Host Unreachable`, while pinging from A to B loses silently. Meanwhile B and C (in the same LAN) can reach each other.

And the `link` in their `zerotier-cli peers` output are inconsistent:

On A (the `lastTX/RX` changes with time, always less than 10000, so I guess the network is not blocked):
```shell
<ztaddr>   <ver>  <role> <lat> <link> <lastTX> <lastRX> <path>
[id_of_B]  1.6.0  LEAF      21 DIRECT 2364     2537     [ipv4_with_port]
```
On B:
```
<ztaddr>   <ver>  <role> <lat> <link> <lastTX> <lastRX> <path>
[id_of_A]  -      MOON      -1 RELAY
```
On B (`peers -j`):
```jsonc
{
  "address": "[id_of_A]",
  "bondingPolicy": 33022, // it's one of 0, 4000, 33022, 65546, 69699 and maybe more?
  "isBonded": false,
  "isHealthy": false,
  "latency": -1,
  "numAliveLinks": -12717644,  // it's 0 when bondingPolicy is 0
  "numTotalLinks": 1470520830, // it's 0 when bondingPolicy is 0
  "paths": [],
  "role": "MOON",
  "version": "-1.-1.-1",
  "versionMajor": -1,
  "versionMinor": -1,
  "versionRev": -1
 }
```

After restart the ZT service on B, this problem persists.
But if I restart the ZT service on A, it will start to work immediately (both A and B have `DIRECT` link and can reach each other).
Unfortunately, if I restart the ZT service on B again, this problem will come back.

I am willing to help address this problem. 😄

## Additional information

**The moon root / controller A:**
- OS: Ubuntu 20.04.1
- ZeroTier Version 1.6.0

**The local server B:**
- OS: Arch Linux (kernel 5.9.9, all packages are up-to-date at the moment)
- ZeroTier Version 1.6.0

UPDATE: the problem persists after all nodes updated to 1.6.2.

**Comment by Fastidious** [comment]
Same happening to me, on 1.6.2 (Linux) controller (moon) and peers (1.6.2, Linux, and 1.6.1, macOS).

**Comment by paintenzero** [comment]
Same here. I have two moons - two servers in the internet in different cities with Ubuntu 20.04.1 on both of them. Also there are 4 clients (leafs) in the network. There are 2 regular linux machines, 1 arm64 linux SBC and Windows PC. Whenever I restart zerotier-one service on any linux machine I lose connectivity between that machine and any of a moon. I can still reach to any of a leaf however. To restore connectivity I have to restart zerotier-one service on both moons. If I restart on only one of the moon I reach only that one but not both.
I have never seen anything like that on Windows client.

**Comment by isakrubin** [comment]
Similar issues, also on 1.6.2, restarting zerotier-one service solves it but that's not a permanent solution

**Comment by lideming** [comment]
This issue seems to be fixed. I failed to reproduce it on 1.6.4.
@Fastidious @paintenzero @isakrubin Could you confirm it?

**Comment by isakrubin** [comment]
> This issue seems to be fixed. I failed to reproduce it on 1.6.4.
> @Fastidious @paintenzero @isakrubin Could you confirm it?

Seems to work fine for me soo far :)

**Comment by paintenzero** [comment]
Looks good for me!
