### ISSUE TITLE
Version 1.6.0 broken on MacOS 10.14.6 Mojave

### ISSUE THREAD

**Issue by chetstone** [zerotier/ZeroTierOne#1297]
# Before filing a Bug Report

# If you still want to file a Bug Report

## Additional information 

After setting up my new Apple Silicon MacMini, I installed 1.6.0 which worked fine. I then for some reason decided to upgrade ZeroTier on my other machines. 1.6.0 worked fine on my Catalina MacBook Pro but when I installed it on my Mojave iMac, it didn't work. I was getting popup windows on my screen saying that ZeroTier was timing out. (Sorry I don't have a screenshot).
And I couldn't ping the other hosts on my ZT network:

```
$ ping docean.dewachen.org
PING docean.dewachen.org (10.147.17.1): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
```
My ZeroTier.com dashboard showed my iMac was online, and so did `zerotier-cli info`.

```
$ zerotier-cli info
200 info 3fba495044 1.6.0 ONLINE
```
The menu bar `Network Details` pane looked normal except the `Connected` checkbox was unchecked (shown checked in this screenshot) 

![image](https://user-images.githubusercontent.com/976343/99917299-9d5cfe80-2ccc-11eb-966d-1ff79aaed13c.png)

When I checked the checkbox, all networking on the machine started failing, e.g. http access to non-zerotier sites, even ping:

```
$ ping 1.1.1.1
PING 1.1.1.1 (1.1.1.1): 56 data bytes
ping: sendto: Address family not supported by protocol family
ping: sendto: Address family not supported by protocol family
Request timeout for icmp_seq 0
ping: sendto: Address family not supported by protocol family
Request timeout for icmp_seq 1
ping: sendto: Address family not supported by protocol family
Request timeout for icmp_seq 2
```

I tried uninstalling and reinstalling and had the same issue. Finally I uninstalled and installed version 1.4.6 and it's working fine now.

**Comment by glimberg** [comment]
1.6.1 is now out.  This will fix your issue.

**Comment by lessless** [comment]
Same problem on macOS Big Sur (11.3.1) with   `74033e8928 1.6.5`

Can't access other nodes in the network
