### ISSUE TITLE
I don't get an IPv4 address

### ISSUE THREAD

**Issue by pwaller** [zerotier/ZeroTierOne#13]
```
zt0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 2800
    inet6 fe80::<withheld>  prefixlen 64  scopeid 0x20<link>
    ether 32:<withheld>  txqueuelen 500  (Ethernet)
    RX packets 1  bytes 164 (164.0 B)
    RX errors 0  dropped 0  overruns 0  frame 0
    TX packets 6  bytes 468 (468.0 B)
    TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

Any advice on how to figure out why?

**Comment by retorquere** [comment]
I'm getting the same. Everything seems to work and I can connect using the ipv6 address, but I'm not getting an IPv4 on Ubuntu 17.10.

**Comment by retorquere** [comment]
Argh never mind, I had to pick a range from the ZT management interface.

Still, the MacOS peer got an IPv4 address without that.

**Comment by jdelrue** [comment]
We are facing the same issue with our own created network (c7c8172af1387fb0). We disabled ipv6 and only enabled 4...

![image](https://user-images.githubusercontent.com/1687505/40127969-d7917670-5930-11e8-9cbb-e35c140e2783.png)
