### ISSUE TITLE
Win 10 20H2 problem with zerotier ver 1.6.0

### ISSUE THREAD

**Issue by Omoinemie** [zerotier/ZeroTierOne#1300]
when I installed the version1.6.0, the zerotier cannot add a adapter, and it cannot use.
![Snipaste_2020-11-24_10-20-17](https://user-images.githubusercontent.com/31991443/100038289-b1287200-2e3e-11eb-9319-90a22c56f2a7.jpg)
![Snipaste_2020-11-24_10-19-57](https://user-images.githubusercontent.com/31991443/100038296-b2f23580-2e3e-11eb-9a50-f1b16fee4d06.jpg)

**Comment by Element-H** [comment]
I found that in this case, an "unknown device" will appear when opening the device manager.You can solve the problem by updating it. Then the state will be ''OK''.

![1](https://user-images.githubusercontent.com/74958733/100076118-ccfe3900-2e7b-11eb-9967-e4f9f525967e.PNG)

But once you disconnect, the adapter is gone. To reconnect, you have to repeat this operation.

**Comment by aadnehovda** [comment]
Same problem here. 

Edition	Windows 10 Pro
Version	20H2
Installed on	‎6/‎5/‎2020
OS build	19042.630
Experience	Windows Feature Experience Pack 120.2212.31.0

**Comment by diwu1989** [comment]
revert back to the 1.4.6 instead
http://www.mediafire.com/file/gijvujtspd6de1t/ZeroTier+One+1.4.6.msi/file

**Comment by glimberg** [comment]
We're trying to track down a Windows issue that doesn't seem to be related to 1.6.0 as it can be reproduced in 1.4.6 as well where after a certain number of joins/network adapter creations, Windows no longer recognizes the code signature of the driver as valid. Upon reboot, Windows loads the driver just fine for a while, and then goes back to not recognizing the code signature again.

**Comment by PavelKrassikov** [comment]
I've also tried this hint https://zerotier.atlassian.net/wiki/spaces/SD/pages/35455014/PORT+ERROR+on+Windows though get the error message "The hash for the file is not present in the specified catalog file. The file is likely corrupt or the victim of tampering." - this may cause the inability to install this driver (the error message in the ZT log "unable to create new device instance: UpdateDriverForPlugAndPlayDevices() failed (made 60 attempts)").

**Comment by glimberg** [comment]
1.6.1 is now out.  Should resolve your issue.
