### ISSUE TITLE
1.6.0 bug roundup

### ISSUE THREAD

**Issue by bartmichu** [zerotier/ZeroTierOne#1302]

**Comment by rjmalagon** [comment]
There are many mysterious performance and routing misbehavior in this release.
Linux is mostly ok but it trashes Windows nodes network performance.
Suricata IPS goes nuts with these release too.

**Comment by bartmichu** [comment]
Personally I don't mind performance issues. I'm cut out of my remote nodes as ZT is unusable after update. No network adapters on Windows 10 and segmentation faults on Ubuntu.
It would be a disastrous update for me if not a backup Wireguard tunnel left in case of problems like these.

**Comment by iYUYUE** [comment]
To end this disaster, I've done the following on all of my Linux/Debian nodes:
`sudo apt install zerotier-one=1.4.6`
`sudo apt-mark hold zerotier-one`

**Comment by diwu1989** [comment]
On windows, I had to look around hard for the older 1.4.6 installer.
http://www.mediafire.com/file/gijvujtspd6de1t/ZeroTier+One+1.4.6.msi/file

**Comment by iYUYUE** [comment]
> On windows, I had to look around hard for the older 1.4.6 installer.
> http://www.mediafire.com/file/gijvujtspd6de1t/ZeroTier+One+1.4.6.msi/file

Here you go. https://download.zerotier.com/RELEASES/1.4.6/dist/ZeroTier%20One.msi

**Comment by glimberg** [comment]
Linux binaries for 1.6.1 are now out.

Mac pkg can be found here: http://download.zerotier.com/RELEASES/1.6.1/dist/ZeroTier%20One.pkg

Still tracking down a Windows issue that doesn't seem to be related to 1.6.0 as it can be reproduced in 1.4.6 as well where after a certain number of joins/network adapter creations, Windows no longer recognizes the code signature of the driver as valid.  Upon reboot, Windows loads the driver just fine for a while, and then goes back to not recognizing the code signature again.

**Comment by WaterMelonOof** [comment]
> Still tracking down a Windows issue that doesn't seem to be related to 1.6.0 as it can be reproduced in 1.4.6 as well where after a certain number of joins/network adapter creations, Windows no longer recognizes the code signature of the driver as valid. Upon reboot, Windows loads the driver just fine for a while, and then goes back to not recognizing the code signature again.

Thanks. Is there any temporary fix for that?

**Comment by glimberg** [comment]
> Thanks. Is there any temporary fix for that?

Rebooting when it happens is the only workaround we have at the moment.

**Comment by alexacallmebaka** [comment]
Updating to 1.6.1 on my CentOS 8 server made it so I could not reach the server on my Debian 10 laptop. Was forced to downgrade the server to 1.6.0.

**Comment by glimberg** [comment]
1.6.1 is now out.  Should fix windows, mac & linux issues.

**Comment by WaterMelonOof** [comment]
Seems great! However every time a disconnect and reconnect a network, it shows up this:
![image](https://user-images.githubusercontent.com/68735408/100319133-1d030a00-2ffa-11eb-99f4-40181abe8f29.png)
And the network number keeps increasing.

Is that normal?

**Comment by laduke** [comment]
Yes. There's an issue open about it somewhere around here.
