### ISSUE TITLE
Crashes when clicking Create and Join Network

### ISSUE THREAD

**Issue by WaterMelonOof** [zerotier/ZeroTierOne#1303]
Discussion here: https://discuss.zerotier.com/t/crashes-when-clicking-create-and-join-network/915

As you see in the video, when I click the Create and Join Network, it hanged, the whole thing turned darker and windows close. One of your moderators told me not to use this function because it is buggy. But I think I have to. I'm using it for small group of people playing Minecraft Server and I was trying to follow [this tutorial](https://www.youtube.com/watch?v=oTlxwg3atBc).

I found that it creates A LOT of virtual ethernet ports and I think it might be the problem.
![image](https://user-images.githubusercontent.com/68735408/100203391-81ac5f00-2f3d-11eb-9f9f-a9c67475d274.png)

I know very little about Internet and Ports thingy so please help me out.

Thanks in advance.

My OS:
Windows 10 Home Edition

**Comment by glimberg** [comment]
This is a known issue.  See here: https://github.com/zerotier/ZeroTierOne/issues/1302#issuecomment-733531579

**Comment by WaterMelonOof** [comment]
Thanks for informing.
