### ISSUE TITLE
Mac/Win7 cannot connect to Win10, and ping timeout

### ISSUE THREAD

**Issue by mchotdograp** [zerotier/ZeroTierOne#1307]
My last post was closed, but the issus has not been solved.

OS: Mac Mojave 10.14.6/Win10/Win7
ZeroTier Version 1.6/1.61

So let's start from the very beginning:

I tried zerotier v1.6 and connected to the network. All the nodes is online in the "last seen" column.
But next thing is my RDP on Mac cannot connect to one of the Win10 node of my network, while RDP on another node(Win7) can connect to that Win10 node.
So I tried ping.
On my Mac, I pinged the managed IP of the Win10 node, turned out timeout, but when I pinged the Physical IP of the Win10 node, it worked!
So I did the same thing on the win7 node, both IPs of the Win10 node worked!

Then 1.6.1 update came out, I updated ZT to 1.6.1, everything seems OK, all the nodes is online in "last seen" column, but still, RDP on my Mac cannot connect to the Win10 node, even worse, the Win7 node cannot connect to the Win10 node either. Their both ping to the managed IP of the Win10 node timedout, but the Physical IP is OK.

**Comment by hach-que** [comment]
I am also consistently seeing issues where network connectivity to Windows devices just dies for no reason, and the only solution is restarting the Windows machine you are trying to connect to.

**Comment by hach-que** [comment]
(Usually it happens when I change networking configuration in the portal; at this point I have networks on IPv6 only because IPv4 seems to be way too unreliable on Windows)

**Comment by RomaKoks** [comment]
https://zerotier.atlassian.net/wiki/spaces/SD/pages/29130754/I+Can+t+Ping

**Comment by joseph-henry** [comment]
Can anyone confirm that this issue is still present in `1.6.5`? If not, I'm going to close this ticket. Thanks.
