### ISSUE TITLE
Please publish expected performance benchmark data

### ISSUE THREAD

**Issue by diwu1989** [zerotier/ZeroTierOne#1308]
For transparency, please publish standardized performance benchmark of Zerotier 1.4.x vs 1.6.x.

Right now, I'm seeing about 50% performance drop for some reason when using 1.6.x, going from 200Mbit/s on 1.4.x down to 120Mbit/s on 1.6.x on Linux using iperf.

Please publish iperf data for the community so that we have some reference numbers to determine whether our network is performing as expected.

**Comment by joseph-henry** [comment]
Can you tell me more about the architecture of the machines you're seeing this difference on?
