### ISSUE TITLE
ssh using ZeroTier overseas

### ISSUE THREAD

**Issue by Divadi** [zerotier/ZeroTierOne#1309]
Hi, thank you for your amazing work

I was able to get ZeroTier working to ssh into my home desktop behind an apartment firewall from my laptop. I was wondering, however, if it is possible to still connect to it when I am overseas (namely South Korea). I would like to have everything setup before I leave, so I wanted to make sure everything was in order. Thank you!

**Comment by Ifiht** [comment]
Divadi, I can speak from my own usage that if you are able to connect from outside the apartment (internet cafe?) it should work out of country barring government-level blocks (China, NK, etc.) Before leaving make sure zerotier is running as a service at start-up, and that your desktop restarts after power failure automatically. Electric grids are rarely as stable as Seoul's.

**Comment by Divadi** [comment]
I see, could I have guidance on how to have zerotier running at startup? 
Also, I did not know it was possible to have a linux machine boot up automatically after power failure (thought I would need a un-interruptible power supply or something.
Thank you for your help!

**Comment by capruro** [comment]
Hi @Divadi, 
in most linux systems `systemctl enable zerotier-one` should start the daemon at boot.
Regarding powering on your system in case of power outage, you'll need to check the BIOS settings.

**Comment by laduke** [comment]
Trying to keep  this issue tracker for work on zerotier-one. See https://discuss.zerotier.com/ for usage questions.
