### ISSUE TITLE
1043nd Openwrt as gateway . Low copy speeds win 10 pcs on both sides

### ISSUE THREAD

**Issue by Mackstoresdotcom** [zerotier/ZeroTierOne#1311]
openwrt 1043nd zerotier as gateway. 1000mbps lan . 100mbps internet both sides. win 10 both pcs, copy from server at openwrt site to remote (logmein ..11mbps) (zerotier 300kbps) tcp fallback false and peers show direct connection

Name: Allow-ZeroTier-Inbound
Protocol: UPD
Source zone: Any zone
Destination zone: Device
Destination port: 9993
acton - accept

and will see
Match:
Incoming IPv4 and IPv6, protocol UDP
From any zone
To this device, port 9993

Action:
Accept input

main internet is mikrotik and have forwardedd the 9993 port to openwrt

here is the log
zerotier-cli

200 info f749473xxx 1.4.6 ONLINE

200 listpeers <ztaddr> <path> <latency> <version> <role>
200 listpeers 3a46f1bxxx185.180.13.82/9993;2196;1924 284 - PLANET
200 listpeers 62f865axxx 50.7.252.138/9993;2198;1685 514 - PLANET
200 listpeers 778cde7xxx 103.195.103.66/9993;2198;1862 307 - PLANET
200 listpeers 992fcf1xxx 195.181.173.159/9993;2199;2028 182 - PLANET
200 listpeers d3ecf57xxx34.94.72.151/21022;2200;95330 271 1.6.0 LEAF

200 peers
<ztaddr>   <ver>  <role> <lat> <link> <lastTX> <lastRX> <path>
3a46f1bxxx -      PLANET   278 DIRECT 8881     3598     185.180.13.82/9993
62f865axxx -      PLANET   512 DIRECT 8882     3364     50.7.252.138/9993
778cdexxxx -      PLANET   316 DIRECT 8883     8565     103.195.103.66/9993
992fcf1xxx -      PLANET   174 DIRECT 8883     3703     195.181.173.159/9993
d3ecf57xxx 1.6.0  LEAF     271 DIRECT 3872     142071   34.94.72.151/21022

200 listnetworks xxxxxxxxxxxxxxxxxx Gatewaymack xx:xx:xx:xx:xx:xx OK PRIVATE ztxxxxxxx 11.11.11.1/24
                           xxxxxxxxxxxxxxxxxx

**Comment by joseph-henry** [comment]
Are you still seeing this issue?

**Comment by Mackstoresdotcom** [comment]
don't know, i am using logmein hamachi with a      puter now
