### ISSUE TITLE
LinuxEthernetTap improperly changing MAC while tap/tun device already up 

### ISSUE THREAD

**Issue by sehari24jam** [zerotier/ZeroTierOne#1314]
https://github.com/zerotier/ZeroTierOne/blob/e4404164bd9eb14c91906ec3cf577ba98eb24b8a/osdep/LinuxEthernetTap.cpp#L210-L215

I have noticed that in debian Wheezy (tested using qemu with debian-live-7.8.0-amd64-standard.iso), this code will fail setting tun/tap device MAC, and subsequently unable to join zerotier network properly.

To my understanding (tried using iproute2 tools in debian wheezy) code-flow should be:
1. create tun/tap device (`ip tuntap add dev tapx mode tap`)  -> [L205-L209](https://github.com/zerotier/ZeroTierOne/blob/e4404164bd9eb14c91906ec3cf577ba98eb24b8a/osdep/LinuxEthernetTap.cpp#L205-L209)
2. set MAC (`ip link set dev tapx address 1:2:3:4:5:6`) -> [L224-L229](https://github.com/zerotier/ZeroTierOne/blob/e4404164bd9eb14c91906ec3cf577ba98eb24b8a/osdep/LinuxEthernetTap.cpp#L224-L229)
3. set MTU (`ip link set dev tapx mtu 1234` ) -> [L231-L236](https://github.com/zerotier/ZeroTierOne/blob/e4404164bd9eb14c91906ec3cf577ba98eb24b8a/osdep/LinuxEthernetTap.cpp#L231-L236)
4. change device state to up (`ip link set tapx up`) -> [L210-L215](https://github.com/zerotier/ZeroTierOne/blob/e4404164bd9eb14c91906ec3cf577ba98eb24b8a/osdep/LinuxEthernetTap.cpp#L210-L215)

Current improper code flow is `1` -> `4` -> `2` -> `3`, so to rectify [L210-L215](https://github.com/zerotier/ZeroTierOne/blob/e4404164bd9eb14c91906ec3cf577ba98eb24b8a/osdep/LinuxEthernetTap.cpp#L210-L215) shall be relocated to line [L237](https://github.com/zerotier/ZeroTierOne/blob/e4404164bd9eb14c91906ec3cf577ba98eb24b8a/osdep/LinuxEthernetTap.cpp#L237), after setting MTU.

IMHO changing MAC address shall not be done while device in up state.

I did tried modify code to correct its flow (tried in qemu wheezy: git clone, edit code, install gcc-4.9, make all), and the result is ok, vm can join zerotier network.

**Comment by jamesfmilne** [comment]
Just chiming in to report the same problem on CentOS/RHEL 6.

Reverting back to ZeroTier 1.4.6 fixes it.

**Comment by Nill-R** [comment]
Same problem on Ubuntu 16.04 LTS
Reverting to ZeroTier 1.4.6 fixes it.

**Comment by myfingerhurt** [comment]
Same problem with router R7000 rt-ac68u
Linux 2.6.36.4brcmarm
zerotier 1.6.3

**Comment by jonathonf** [comment]
> Current improper code flow is 1 -> 4 -> 2 -> 3, so to rectify L210-L215 shall be relocated to line L237, after setting MTU.

I've been having issues on an OpenVZ VPS with anything newer than 1.4.6. For me, this alters the issue from "destination unreachable" to 100% packet loss.

**Comment by jonathonf** [comment]
I've now done a proper `git bisect` and the problematic commit (for me) appears to be https://github.com/zerotier/ZeroTierOne/commit/d735a1d04cf1d8236d531210e7361607d2774a13.

I've opened a new PR to set the MAC address prior to bringing up the TAP device. It seems more reliable to set MTU _after_ bringing up the device.

**Comment by luckydevil13** [comment]
please update source code, many users affected

**Comment by jonathonf** [comment]
This may have been re-opened by https://github.com/zerotier/ZeroTierOne/commit/357e1aca544563f107e50d98b1e8f509a8178dc3 which reverts https://github.com/zerotier/ZeroTierOne/commit/9374e45449ffe5c377e4cb2a346129ec598eeea9

**Comment by glimberg** [comment]
@jonathonf unfortunately, the PR breaks other Linux distros intermittently.

**Comment by jonathonf** [comment]
Which distros? Which kernels?

**Comment by glimberg** [comment]
Debian and red hat based distros. Basically anything not running openvz

**Comment by jonathonf** [comment]
As I said in the PR, ZT works on all of the distros I tested, which includes Debian and Arch. Can this be narrowed down to a more specific set of affected systems, or linked to an Issue?

**Comment by laduke** [comment]
hey thanks for reminding about this. 
I was seeing the wrong mac address about 1/20 times on 1.8.1 
by leaving and rejoining a network, or restarting the service. Bummer. 

The 1.8.2 code sets the MAC before and after
https://github.com/zerotier/ZeroTierOne/blob/3f4cd7f5a25b49c4856b5d3421fa3c9ef88cc700/osdep/LinuxEthernetTap.cpp#L202

It may have taken a couple commits to get there. Will look more later.

**Comment by jonathonf** [comment]
A `git bisect` brings it directly back to https://github.com/zerotier/ZeroTierOne/commit/357e1aca544563f107e50d98b1e8f509a8178dc3 as causing an issue on the OpenVZ system.

What system/config/etc. are you seeing the failure on so I can try to replicate here?

**Comment by laduke** [comment]
For me, a fresh debian 11 amd64 vm.

**Comment by jonathonf** [comment]
I can replicate on a Bullseye system 

```
$ uname -a
Linux lemmy 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux
$ cat /etc/*release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

using the ZeroTier 1.8.1 binary:

```
#  for i in $(seq 1 30); do systemctl restart zerotier-one; sleep 5; ip a show dev ztppi3qmf6 | grep ether; sleep 5; done
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether 4e:55:20:80:af:b9 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff                                                                                                           
    link/ether 4e:55:20:80:af:b9 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
...
```

However, according to the [apt sources list](https://install.zerotier.com/), the published Bullseye packages seem to be built against Buster libraries:

```
elif [ "$dvers" = "10" -o "$dvers" = "11" -o "$dvers" = "sid" -o "$dvers" = "buster" -o "$dvers" = "bullseye" -o "$dvers" = "parrot" ]; then
	echo '*** Found Debian "buster", or "sid" (or similar), creating /etc/apt/sources.list.d/zerotier.list'
	echo "deb ${ZT_BASE_URL_HTTP}debian/buster buster main" >/tmp/zt-sources-list
```

After compiling 01bf3b8245e50eac572937833e4ad2f3d7209dcc locally against Bullseye libraries,

```
$ git clone https://github.com/zerotier/ZeroTierOne.git
$ cd ZeroTierOne
$ git checkout 01bf3b8245e50eac572937833e4ad2f3d7209dcc
$ make -j$(nproc)
# systemctl stop zerotier-one && killall zerotier-one
# ./zerotier-one
```

the problem seems to be gone:

```
# for i in $(seq 1 30); do systemctl restart zerotier-one; sleep 5; ip a show dev ztppi3qmf6 | grep ether; sleep 5; done
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
```

I note that there is a Bullseye package available under http://download.zerotier.com/debian/bullseye/pool/main/z/zerotier-one/, and yet after installing http://download.zerotier.com/debian/bullseye/pool/main/z/zerotier-one/zerotier-one_1.8.1_amd64.deb the issue also occurs:

```
# for i in $(seq 1 30); do systemctl restart zerotier-one; sleep 5; ip a show dev ztppi3qmf6 | grep ether; sleep 5; done
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether 4e:55:20:80:af:b9 brd ff:ff:ff:ff:ff:ff
    link/ether 4e:55:20:80:af:b9 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
    link/ether a2:cd:1d:13:2d:37 brd ff:ff:ff:ff:ff:ff
...
```

This kind of implies the issue lies somewhere in your package build infrastructure?

It might be worth checking that packages are being compiled against the correct library versions for the distro on systems where you're seeing this happen?

**Comment by adamierymenko** [comment]
We will need to update install.zerotier.com and have people having this issue reinstall to use the `bullseye` repo. Older versions used `buster` builds on later Debian versions and there appears to have been a breaking change in libc or some other part of the library internals.

**Comment by jonathonf** [comment]
Actually, after building a 1.8.1 deb in a Bullseye `pbuilder` environment (using `pdebuild`), 

```
$ git clone https://github.com/zerotier/ZeroTierOne.git
$ cd ZeroTierOne
$ git checkout 01bf3b8245e50eac572937833e4ad2f3d7209dcc
$ dh_make --createorig -p zerotier-one_1.8.1
$ dch
    (add package revision, e.g. set 1.8.1-0)
$ DIST=bullseye pdebuild
```

the "incorrect MAC" issue occurs. I've tried with a range of flags in `debian/rules` (including none), all builds show an issue with an intermittently incorrect MAC. Either there's some over-optimisation happening (which is reordering code) or debhelper is changing something in the build compared to compiling it directly on the system. Or, if this only occurs in Bullseye, then there's a bug in Bullseye... ?

**Comment by laduke** [comment]
hey @jonathonf, just to double check openvz is broken on 1.8.2 and .3?

**Comment by jonathonf** [comment]
> just to double check openvz is broken on 1.8.2 and .3?

Confirm, broken on what I think is OpenVZ 6:

```
Linux hostname 2.6.32-042stab145.3 #1 SMP Thu Jun 11 14:05:04 MSK 2020 x86_64 GNU/Linux

PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

Although, maybe this means it's just time to retire these VPS... they also can't be updated to newer Debian because of the outdated host nodes - annnndddd I just noticed OpenVZ 6 was [EoL in November 2019](https://wiki.openvz.org/Releases), so why the provider is still running this is beyond me.

**Comment by jonathonf** [comment]
Confirming, 1.8.3 works fine on OpenVZ 7.

I suspect this can be closed, supporting an EoL operating system isn't reasonable.
