### ISSUE TITLE
Security: Copying ZeroTier files to another machine works on new machine without re-auth

### ISSUE THREAD

**Issue by rakundig** [zerotier/ZeroTierOne#1316]
OS: MacOS Mojava --> Big Sur

Problem: ZeroTier files and configs can be copied to a new machine and still work normally without requiring the new machine to be re-authorized.

Expected Behavior:  If/When the files are copied to a completely new device or machine they should require complete re-authorization and should not function until re-authorized, and the new device or machine should get a new virtual device, virtual mac address, and new IP address.

Actual Behavior:  When files were copied over from a Mac running Mojave to a Mac running Big Sur using the Mac Migration tool for apps, all ZT files and configs were copied over and worked exactly as they did on the original Mac without any need to authorize the new Mac.  The virtual network device also had the same exact IP address and virtual MAC address.  

Initially it was unable to ping or navigate the ZT networks even though zerotier-cli status says it is online and listnetworks can see all the same networks the prior mac was authorized to see.  Shutting ZT off on the original Mac and reloading it on the new Mac then enabled it to see, ping, and navigate all the exact same networks and had all the same settings (mac, IP, etc...) as the original Mac.  There was no obvious change within the ZT controller or network(s) to identify that it was a new device.

This shouldn't happen and is a big security concern.  A device could be authorized to use ZT and those files copied to potentially any other device and still function normally which can cause a multitude of security problems.  If, for example, the files were copied from a known device which has a known configuration and setup, such as a work device, to a new uncontrolled device with various unauthorized software(s) or tools on it, or not patched, not running adequate AV, etc... this could be a big problem. 

A worst case is that a bad actor is able to copy those files off of the authorized device onto their own device and they could potentially use that device to move around within the ZT nets by impersonating the original/authorized device without anyone knowing.

This was Mac to Mac only using the Mac Migration tool.  It has not been tested yet on Linux, Windows, or any other OSs or devices at this time.

**Comment by adamierymenko** [comment]
I'm afraid this is a misunderstanding of how ZeroTier works. The file `identity.secret` is the secret key and therefore also the identity of a node. Duplicating it duplicates the node. The same would be true with e.g. a normal VPN client and its client secret.

If you wanted to hard-tie ZeroTier to the actual device we'd need to add support for all the various trusted platform modules such as Apple's T2 chip (or its M1 onboard equivalent), Intel's, etc.

Right now I am marking as not-a-bug. Hardware auth is definitely something on our road map along with user two-factor auth at the edge.

**Comment by laduke** [comment]
https://zerotier.atlassian.net/wiki/spaces/SD/pages/327693/How+to+Clear+Reset+your+ZeroTier+Address
