### ISSUE TITLE
zerotier-one try to eat all resources

### ISSUE THREAD

**Issue by takenek** [zerotier/ZeroTierOne#1318]
Hey,
I got a problem with zerotier-one on Debian 10 64 bit.
He eat 100% cpu and 72% memory ( 2GB got server )

root@host:~# ps aux |grep zero
zerotie+    486 113.2 72.0 5393524 1455032 ?     Ssl  05:55  36:04 /usr/sbin/zerotier-one

root@host:~# ldd /usr/sbin/zerotier-one
        linux-vdso.so.1 (0x00007fff00531000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ff68b69d000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff68b51a000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ff68b500000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff68b4df000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff68b31e000)
        /lib64/ld-linux-x86-64.so.2 (0x00007ff68baec000)

root@host:~# /usr/sbin/zerotier-one -v
1.6.2

Using from repo:
root@host:~# cat /etc/apt/sources.list.d/zerotier.list
deb http://download.zerotier.com/debian/buster buster main

After reboot process everything back to normal:
root@host:~# ps aux |grep zero
zerotie+   7706  0.7  0.4 347128  9736 ?        Ssl  10:30   0:00 /usr/sbin/zerotier-one

Best Regards
TaKeN

**Comment by Mackstoresdotcom** [comment]
same happened to me with windows 10

**Comment by fluxens** [comment]
This happens on macos as well. 

zerotier 1.6.2 (installed via brew)
big sur 11.1 (intel)

**Comment by takenek** [comment]
Anyone know what is wrong?
When zerotier-one process crazy I saw in dmesg i got spam:
[pon lut  8 19:06:17 2021] netlink: 8 bytes leftover after parsing attributes in process `zerotier-one'.

Maybe that' help...

**Comment by joseph-henry** [comment]
Does this still happen with `1.6.5`?

**Comment by riaqn** [comment]
related: https://github.com/zerotier/ZeroTierOne/issues/1351

**Comment by danmanners** [comment]
This is absolutely still an issue with 1.6.5 on Ubuntu Linux 20.04 x64.
