### ISSUE TITLE
[Question] Zerotier-one ubuntu package 

### ISSUE THREAD

**Issue by yar229** [zerotier/ZeroTierOne#1320]
I have installed zerotier-one  on Ubuntu 20.10  with `curl -s https://install.zerotier.com | sudo bash` and its version 1.4.6
Why `sudo apt update/upgrade` does not upgrade to version 1.6.2?

**Comment by laduke** [comment]
`apt update` then `apt install zerotier-one` should do it

**Comment by yar229** [comment]
```zerotier-one is already the newest version (1.4.6).```
