### ISSUE TITLE
Can’t reach specific host from iPad

### ISSUE THREAD

**Issue by mikea** [zerotier/ZeroTierOne#1321]
My iPad is having troubles reaching my server over at network. 

First, after reinstalling zt app everything works fine. But eventually I can't reach my server. 

- I can ping my local server address from iPad and iPad from server
- iPad seems to be able to reach other zt hosts

Both run 1.6.2. Latest iPad os. Ubuntu 20.04. 

Help debugging is appreciated.

**Comment by mikea** [comment]
This still happens like clockwork: reinstall zt on iPad, authorize new client => everything works for a day. Next day iPad can't reach the server anymore (until I reinstall zt). iPhone doesn't have this problem.

**Comment by laduke** [comment]
Thanks for reporting.  Is this on mobile data or wifi, or both? If you create a new network and use that, does it work without reinstallling? This may be related to something we're trying to track down.

**Comment by mikea** [comment]
My iPad doesn't have mobile. Wifi only. 

I didn't try creating new network. I'll try and will let you know how it works.

**Comment by microdockman** [comment]
similarly issue, in (router via zerotier) mode, the iPad often disconnects for no apparent reason and takes a long time to reconnect. (although  equip with a moon and enabled port 9993/udp in main router , obtained ipv6, the iPad or Android device would be disconnected  when they were in standby mode for a  short time

the speed is good after connecting successful,, but it will be disconnected frequently   (Zerotier  has been allowed  running in the background)

**Comment by mikea** [comment]
I created new network. Only server & iPad in it. iPad can't reach the server at all. 

iPad & server are on the same local net (iPad-unifi ap-unifi switch-Ubuntu 20.04 server)

**Comment by mikea** [comment]
My iPhone has no problem reaching the server on this new network.

**Comment by mikea** [comment]
Not sure if anything has changed, but today my iPad can reach the server through both old and new networks. (1.6.2)

**Comment by JocPelletier** [comment]
I have the same issue since more than a year. I have just under 50 nodes and most works flawlessly but some can't see each other. We are working on an alternative to move away form zerotier since it's really annoying. Our "workaround" is to ping the other node every minute and when it's unreachable, restart zerotier. Usually after some restarts they can see each othr again

**Comment by joseph-henry** [comment]
This issue might be fixed in `1.6.5`. We are aware of at least two bugs that could have caused this. Let us know if this issue still exists. Thanks.

**Comment by golfvert** [comment]
I have a similar issue... I am connecting to a remote host from home. At home, my mac and a linux VM can't anymore connect to the remote host. My android phone on the same home wifi network can connect to the remote server. Restarting zerotier, downgrading (1.8.4 -> 1.6.5) doesn't change anything. I also have tried to change the IP address plan, no luck. No firewall. 
As my android can also connect to the server over LTE, I have tried using it as an access point for the mac. No way either. I don't see what else I can try...
