### ISSUE TITLE
PORT_ERROR PRIVATE on brand new VPSDime server

### ISSUE THREAD

**Issue by pedrofracassi** [zerotier/ZeroTierOne#1326]
I just rented a new VPSDime server to add to my multi-cloud docker swarm, which uses zerotier to communicate its nodes. Problem  is the new node doesn't seem to be able to reach the other ones (two nodes from oracle cloud), and the docker swarm join command timeouts due to that. I get the following output when running `zerotier-cli listnetworks`:

```
200 listnetworks <network id redacted> <network name redacted> aa:c6:d4:55:88:aa PORT_ERROR PRIVATE  10.147.18.18/24
```

`ip address` seems not to list the zerotier interface either:

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: gre0@NONE: <NOARP> mtu 1476 qdisc noop state DOWN group default qlen 1000
    link/gre 0.0.0.0 brd 0.0.0.0
3: gretap0@NONE: <BROADCAST,MULTICAST> mtu 1462 qdisc noop state DOWN group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
4: venet0: <BROADCAST,POINTOPOINT,NOARP> mtu 1500 qdisc noop state DOWN group default
    link/void
5: eth0@if508: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:1c:42:e5:e4:09 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet <public ip>/24 brd <redacted public ip> scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::a8e0:abff:fe5e:9199/64 scope link
       valid_lft forever preferred_lft forever
7: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:1d:49:7f:22 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:1dff:fe49:7f22/64 scope link
       valid_lft forever preferred_lft forever
11: veth78357e3@if10: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default
    link/ether 82:09:0f:8d:b2:38 brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::8009:fff:fe8d:b238/64 scope link
       valid_lft forever preferred_lft forever
```

I checked the knowledge base and this error seems to be related to the `tun` driver not being enabled on the machine, which I checked and it seems to be.

What can I try now?

**Comment by diwu1989** [comment]
Your VPSDime vm is using OpenVZ, it won't work properly on OpenVZ in all instances, so switch to a proper KVM VM instead.

OpenVZ is not true virtualization so you don't actually have full kernel control.

**Comment by adamierymenko** [comment]
OpenVZ will work if tun/tap devices are allowed and `/dev/net/tun` is present. Otherwise it will not. This is up to your provider. You may be able to ask them to allow this.

**Comment by Oujiii** [comment]
I'm writing here because I'm facing the same issue. My VPS is also an OpenVZ and in the beginning did not have `tun` enabled (as Tailscale, which is a similar solution pointed out when installing, something maybe ZT should do as well), then I went ahead and enabled it and then Tailscale started working, but I still get `PORT_ERROR` on ZT.

**Comment by comicfans** [comment]
> I'm writing here because I'm facing the same issue. My VPS is also an OpenVZ and in the beginning did not have `tun` enabled (as Tailscale, which is a similar solution pointed out when installing, something maybe ZT should do as well), then I went ahead and enabled it and then Tailscale started working, but I still get `PORT_ERROR` on ZT.

@Oujiii from [zerotier forum](https://discuss.zerotier.com/t/solved-zerotier-vpn-installation-on-ubuntu-openvz-with-a2hosting-com-el-cheapo-account/4348)

```
Just to confirm, this patch worked for me as well. I’m using two Linux (Debian 10) V-Server from STRATO (happarently hosted on a “virtuozzo” based hypervisor. Adding the “-U” option to the " ExecStart=/usr/sbin/zerotier-one -U" line in “/lib/systemd/system/zerotier-one.service” did the trick.

Best regards
Yonz
```
