### ISSUE TITLE
Get same MAC address when run zerotierone in clone VMs

### ISSUE THREAD

**Issue by chariothy** [zerotier/ZeroTierOne#1328]
I installed an openwrt VM in PVE. 
Then I convert the VM into a template and then clone three VMs from the template.
PVE re-initializes MAC addresses for them.
But zerotier one keeps the same MAC address for them all.
So only one client appears in Zerotier central.

Is this normal for clone VM?
Is there any way to re-generate MAC address for zertier network adapter?

**Comment by laduke** [comment]
https://zerotier.atlassian.net/wiki/spaces/SD/pages/327693/How+to+Clear+Reset+your+ZeroTier+Address
