### ISSUE TITLE
iOS devices hang and require ZT uninstall/reinstall & reboot...

### ISSUE THREAD

**Issue by johnnyfu88** [zerotier/ZeroTierOne#1332]
**Expected Behavior >>>**
That ZT iOS app should work continuously without having to be deleted and reinstalled.

**What is actually happening >>>**
Similar to other bug reports, our experience is that the ZeroTier client for iOS causes the iPhone and iPad to hang and often requires uninstall/reinstall of ZT and/or to reboot the devices.  Here are the symptoms:
- Upon installing the ZT iOS app and adding a new ZT config, everything works fine and able to reach internet from both iPhone and iPad.  Confirmed exit IP using whatismyipaddress.com.  However if you delete a config and then re-add the same config, it no longer works unless you delete the ZT app from the iOS device and then re-install and re-configure everything.
- With a fresh install of ZT app and freshly configured ZT config, the iOS device will work fine for some time.  Sometimes for an hour.  Sometimes for a day.  Then it stops working.  When it stops working, it usually requires a reboot of the iOS device and/or a re-install of the ZeroTier iOS app.
- When either of the above problems occurs and the ZT app is deleted from the iOS device, the iOS device sometimes loses its network functionality and must be rebooted.

**Steps to reproduce the error >>>**
Install ZT iOS app.  Configure ZT.  Wait for it to stop working.
 
**Devices >>>**
Phone
-iPhone 12ProMax 2020
-iOS 14.1
-ZT Client v 1.62

Tablet
-iPad Mini 2014
-iOS 12.4.9
-ZT Client v1.62

Virtual Server
-Digital Ocean Droplet
-Ubuntu 16.04 
-ZT v1.62 (configured as VPN Internet Gateway)

Embedded Server
-Raspberry Pi3b
-Raspbian v2020.12.02
-ZT v1.62 (configured as VPN Internet Gateway)

**Additional context**
-When the iPhone or iPad experiences the above (even after deleting the ZT iOS app) it often renders the devices unable to connect to 5G, LTE, or WiFi.  Once rebooted, the iPhone and iPad are able to connect again to WiFi/5G/LTE.
- I utilized the following instructions to configure the DO Droplet and the Raspberry Pi:
     https://www.digitalocean.com/community/tutorials/getting-started-software-defined-networking-creating-vpn-zerotier-one
     https://peyanski.com/raspberry-pi-into-vpn-video-how-to/
- Given the above, the network configurations are precisely as contained in the links above (except for the ZT ID's of course)
- Problem occurs regardless of network connectivity be it WiFi, LTE, or 5G.
- Router and firewalls are configured to permit 9993, uPnP, and NAT.
- Using this at home (wifi) and around the city (LTE, 5G)

**Comment by joseph-henry** [comment]
Are you still seeing this issue? We've never observed this ourselves and I'm not aware of any other reports of ZT crashing iOS/iPadOS devices.
