### ISSUE TITLE
new version Zerotier 1.6.2 can't work well in OpenWrt

### ISSUE THREAD

**Issue by guytogay** [zerotier/ZeroTierOne#1335]
I was using version 1.4.6 in Openwrt, it can help let other subnet device reach every device connected to this OpenWrt. but after I upgrade it to 1.6.2, other devices can only reach OpenWrt, can't reach other devices under this OpenWrt.

# Before filing a Bug Report

_Using these will ensure you get quicker support, and make this space available for code-related issues. Thank you!_

- [Knowledge Base](https://zerotier.atlassian.net/wiki/spaces/SD/overview) => Guides and documentation on how to use ZeroTier.
- [Discuss Forum](https://discuss.zerotier.com/) => Our discussion forum for users and support to mutally resolve issues & suggest ideas.
- [Reddit](https://www.reddit.com/r/zerotier/) => Our subreddit, which we monitor regularly and is fairly active.
- https://www.zerotier.com/contact/ => Sales and licensing queries
- https://zerotier.atlassian.net/servicedesk/customer/portals => Customer Support Portal

# If you still want to file a Bug Report

## Required

- What you expect to be happening.
- What is actually happening?
- Any steps to reproduce the error.
- Any screenshots that would help us out.

## Additional information 

**Desktop (please complete the following information):**
 - OS: [e.g. Mac, Linux, Windows, BSD]
 - OS/Distribution Version
 - ZeroTier Version [e.g. 1.4.6]
  
**Smartphone (please complete the following information):**
 - ZeroTier Version [e.g. 1.4.6]

 **Embedded & NAS (please complete the following information):**
 - Device: [e.g. Synology, Pi4]
 - OS/Distribution (if applicable)
 - ZeroTier Version [e.g. 1.4.6]

**Additional context**
- ZeroTier Network Configuration: IPv4 & IPv6 networks defined on your ZeroTier Central
- Router Config: are you permitting port 9993, uPnP, and NAT-PMP?
- Firewall Config: are you permitting port 9993 on your OS; setting it to "Private" on Windows?
- Are you using this at home, in an office, college, etc?

**Comment by zaninime** [comment]
I also have a similar issue (Linux 5.9 x86_64, not OpenWrt), and this seems pretty similar to a bunch of other open issues, such as #1321.

Whenever the problem occurs, I simply log in into the machine (I have a back-channel) and issue these commands:

```
systemctl stop zerotierone    # unit name might differ
cd /var/lib/zerotier-one      # also depends on distro, afaik
ls | grep -v 'identity.*' | xargs rm -rfv
# [placeholder]
systemctl start zerotierone
```

This will remove all files which are not the identity ones. If you want to automatically rejoin some networks afterwards, you can recreate the necessary files by adding these lines at `[placeholder]`:

```
mkdir networks.d
cd networks.d
touch NETWORK_ID1.conf NETWORK_ID2.conf
```

For me it happens so regularly that I made a script that runs with systemd timers (cron) every day.

**Comment by zaninime** [comment]
Possibly the same: #1334 #1332 #1259

**Comment by adamierymenko** [comment]
Yes, this looks very much like a duplicate. Hoping 1.6.3 fixes.
