### ISSUE TITLE
Ability to turn off ZeroTier service from desktop UI

### ISSUE THREAD

**Issue by TheYsconator** [zerotier/ZeroTierOne#1337]
ZeroTier on macOS tries to connect to the internet quite often, even when not enabled.

I noticed that ZeroTier tries connection to the internet roughly every four seconds, regardless of whether it is running (in the menu bar) or not. The application is always showing in Activity Monitor, probably due to the global daemon that is bundled with ZeroTier. The server it tries to connect to appears to be at random/to rotate every time the application connects (every four seconds). The binary that is trying to make the connections is `/Library/Application Support/ZeroTier/One/zerotier-one`.

I would expect an application that is not running to not have to connect with the internet this often. A daemon that helps checking for software updates every x days would be one thing, but to me this looks excessive.

**To reproduce**:
1. Install ZeroTier on macOS (Big Sur)
2. Disable launch at login
3. Just to make sure; reboot
4. Inspect ZeroTier's network activity using a tool like Little Snitch

**I am running**:
 - OS: macOS (Big Sur 11.1)
 - ZeroTier: 1.6.2

**Comment by laduke** [comment]
You can stop the service with 

`sudo launchctl unload /Library/LaunchDaemons/com.zerotier.one.plist`
`sudo launchctl load /Library/LaunchDaemons/com.zerotier.one.plist`

the menubar app is just a UI that talks to this service.

**Comment by BoWang816** [comment]
run $ sudo launchctl unload /Library/LaunchDaemons/com.zerotier.one.plist
result: /Library/LaunchDaemons/com.zerotier.one.plist: Could not find specified service
Unload failed: 113: Could not find specified service

run: $ sudo launchctl load /Library/LaunchDaemons/com.zerotier.one.plist
result: /Library/LaunchDaemons/com.zerotier.one.plist: Service is disabled
Load failed: 119: Service is disabled

why???

**Comment by TheYsconator** [comment]
@laduke I know I can unload services, and I've done so for now. However, I still believe that this should not be default behavior for an installed-but-not-running app, which is why I opened an issue.

**Comment by adamierymenko** [comment]
Going to move this to a feature request, since this is currently the "intended" behavior. ZeroTier is a system service and the tray app just controls it.

**Comment by SolinMa** [comment]
> run $ sudo launchctl unload /Library/LaunchDaemons/com.zerotier.one.plist
> result: /Library/LaunchDaemons/com.zerotier.one.plist: Could not find specified service
> Unload failed: 113: Could not find specified service
> 
> run: $ sudo launchctl load /Library/LaunchDaemons/com.zerotier.one.plist
> result: /Library/LaunchDaemons/com.zerotier.one.plist: Service is disabled
> Load failed: 119: Service is disabled
> 
> why???

Has the problem been solved?I have encountered the same problem.

**Comment by IXueGaoI** [comment]
> run $ sudo launchctl unload /Library/LaunchDaemons/com.zerotier.one.plist
> result: /Library/LaunchDaemons/com.zerotier.one.plist: Could not find specified service
> Unload failed: 113: Could not find specified service
> 
> run: $ sudo launchctl load /Library/LaunchDaemons/com.zerotier.one.plist
> result: /Library/LaunchDaemons/com.zerotier.one.plist: Service is disabled
> Load failed: 119: Service is disabled
> 
> why???

Same problem here, any solution?

**Comment by dtahao** [comment]
Same problem here, any solution?

**Comment by tqcenglish** [comment]
try the command 

` sudo launchctl load  -w /Library/LaunchDaemons/com.zerotier.one.plist`

**Comment by sandy9707** [comment]
Thank you,tqcenglish.I've been looking for a weekend.
