### ISSUE TITLE
Can't install Zerotier One in Fedora Silverblue!

### ISSUE THREAD

**Issue by IzumiSena** [zerotier/ZeroTierOne#1338]
## Required

- Am am trying to install Zerotier in Fedora Silverblue
- What is actually happening?
I can't install it in fedora silverblue 
- Any screenshots that would help us out.
![IMG_20210113_114136](https://user-images.githubusercontent.com/61591769/104411328-613f6f00-5594-11eb-8fe6-7b560154948d.jpg)

## Additional information 

**Desktop (please complete the following information):**
 - OS: Fedora Silverblie
 - ZeroTier Version [1.6.2]

**Comment by hannut** [comment]
Silverblue is immutable so the normal installer does not work

You have to extract the GPG key from the install-script and put it in /etc/pki/rpm-gpg/RPM-GPG-KEY-zerotier

then add the below to /etc/yum.repos.d/zerotier.repo

```
[zerotier]
name=ZeroTier, Inc. RPM Release Repository
baseurl=http://download.zerotier.com/redhat/fc/22
enabled=1
gpgcheck=1
```

run `rpm-ostree install zerotier-one` and reboot

after reboot do `systemctl enable --now zerotier-one.service`

**Comment by joseph-henry** [comment]
Thank you for your knowledge @hannut

**Comment by goshansp** [comment]
Could we re-open this issue please?

What I did after `ZeroTier install script` failed partially because `yum` was not found (as per original description above) on Fedora 36 Silverblue:
```
curl -s \
https://raw.githubusercontent.com/zerotier/ZeroTierOne/master/doc/contact%40zerotier.com.gpg \
| sudo tee /etc/pki/rpm-gpg/RPM-GPG-KEY-zerotier
sudo rpm-ostree install zerotier-one
```

Adding the following to the `ZeroTier install script` at line 298 might be the other half of the rent:
```
if [ -e /usr/bin/rpm-ostree ]; then
    	cat /dev/null | $SUDO rpm-ostree install -y zerotier-one
```
I was unable to find the `ZeroTier install script` - how can I contribute to it? I would welcome a re-opening of this issue enabeling a permanent fix.

Thanks for the work!

**Comment by Heus-Sueh** [comment]
> Could we re-open this issue please?
> 
> What I did after `ZeroTier install script` failed partially because `yum` was not found (as per original description above) on Fedora 36 Silverblue:
> 
> ```
> curl -s \
> https://raw.githubusercontent.com/zerotier/ZeroTierOne/master/doc/contact%40zerotier.com.gpg \
> | sudo tee /etc/pki/rpm-gpg/RPM-GPG-KEY-zerotier
> sudo rpm-ostree install zerotier-one
> ```
> 
> Adding the following to the `ZeroTier install script` at line 298 might be the other half of the rent:
> 
> ```
> if [ -e /usr/bin/rpm-ostree ]; then
>     	cat /dev/null | $SUDO rpm-ostree install -y zerotier-one
> ```
> 
> I was unable to find the `ZeroTier install script` - how can I contribute to it? I would welcome a re-opening of this issue enabeling a permanent fix.
> 
> Thanks for the work!

here is the installer repository:
https://github.com/zerotier/install.zerotier.com

**Comment by Heus-Sueh** [comment]
I created a pull request to support atomic versions of fedora (Silverblue, Kinoite, etc...), if you can give feedback if there is any more detail missing in the script to support fedora silverblue please let me know

https://github.com/zerotier/install.zerotier.com/pull/65

**Comment by mikebutash** [comment]
I'm helping a friend install Bazzite that uses another os-tree based fedora-ish as a gamer distro for handheld game systems like Asus ROG Ally, MSI Claw, GPD, and other, and ran into this today. I assumed it'd be a lickety-split ease to get ZT on it, but then realized "oh, you're one of those..." as an os-tree immutable variation.

Bazzite is quickly gaining notoriety for replacing broken windoze installs on these gaming handhelds that never quite work despite all the vendor overlays to windoze, so this is more than simply a silverblue issue ultimately to deal with these immutable distributions using os-tree or systemd-sysupdate.

**Comment by SEEN88** [comment]
> Silverblue is immutable so the normal installer does not work
> 
> You have to add the zerotier GPG key put it in /etc/pki/rpm-gpg/RPM-GPG-KEY-zerotier
> 
> ```
> curl -s \
> https://raw.githubusercontent.com/zerotier/ZeroTierOne/master/doc/contact%40zerotier.com.gpg \
> | sudo tee /etc/pki/rpm-gpg/RPM-GPG-KEY-zerotier
> ```
> 
> then add the below to /etc/yum.repos.d/zerotier.repo
> 
> ```
> [zerotier]
> name=ZeroTier, Inc. RPM Release Repository
> baseurl=http://download.zerotier.com/redhat/fc/22
> enabled=1
> gpgcheck=1
> ```
> 
> run `rpm-ostree install zerotier-one` and reboot
> 
> after reboot do `systemctl enable --now zerotier-one.service`

For anyone discovering this later, change the 22 in the baseurl to your version of Fedora (41 for the current version of Bazzite as of this post)

**Comment by Paddy69** [comment]
For anyone here looking for "Bazzite" installation help
i was able to connect my Framework laptop Running Bazzite 43 using this guide
https://docs.bazzite.gg/General/zerotier/
