### ISSUE TITLE
Clients disconnected and not able to be reached anymore (Win Server behind Pfsense inside VM)

### ISSUE THREAD

**Issue by crospa91** [zerotier/ZeroTierOne#1343]
Hi guys, 
since yesterday both my Windows Server 2019 VM are stopped being pinged and their webserver pages are not reachable from any other external client.

It was all working fine until as I said the other when after waking up I wasn't able to ping them at all.

I've tried with different clients, (My Phone, My Mac, My Partner Phone and My Partner Mac,
all of them on mobile data and wifi) and the issue persist.

The issue happened randomly so I can't recollect a specific thing who made it happen.

All the VM live behind a PFSense VM that route connections in the system but all the settings seems fine as per your manual, even because it was working before with this setup.

Now none of my VM can be reached from ZeroTier 

My zero tier config is IPv4,  port 9993 is open on firewall (Both PfSense and Windows Firewall) and the network it's private. to be honest every time I disconnect ZeroTier, windows dos ask me to choose if I wanna use it as private or public.

I really hope anyone can help because it's already 2 days that I'm trying to figuring it out with no luck.

Thanks!

**Comment by hardwareadictos** [comment]
Same issue here on Windows 10, no pfsense. Behind a normal ISP router, it happened just from one day to another...

**Comment by adamierymenko** [comment]
#1334 duplicate
