### ISSUE TITLE
Can no longer set DNS on my.zerotier.com

### ISSUE THREAD

**Issue by tardisx** [zerotier/ZeroTierOne#1345]
I had previously set a two letter search domain, that I use in my home network.

In trying to get to the bottom of the DNS problems (#1315), I thought I would delete my DNS configuration on my.zerotier.com and recreate it. After deleting it I can no longer recreate this configuration as it was. All attempts are met with an error "Match the requested format". There is no documentation on what this "format" might be.

<img width="431" alt="image" src="https://user-images.githubusercontent.com/39711/106577030-c849b580-658d-11eb-897d-10482dd42e1a.png">

It seems with some experimentation that there is now a minimum character requirement, and at least one '.' needs to be in the name as well - which is definitely a regression from my point of view.

**Comment by laduke** [comment]
Hello. Hmm. Which OS's did you us a 2 letter search domain on? They all worked? 

You were using just "z9" before?

**Comment by tardisx** [comment]
Yes. That worked fine, it continues to work inside of my LAN. It used to work via zerotier from my Mac (not iOS because of #1315), but now that I have deleted that configuration I can no longer restore it.

**Comment by laduke** [comment]
Looking into the UI.

Here's how to change it via the API
```
curl -X POST --header "authorization: bearer $TOKEN" "https://my.zerotier.com/api/network/${NETWORK_ID}" -d '{"config":{"dns":{"domain":"zt","servers":["100.64.64.68","fd83:048a:0632:04fd:e799:937e:2d4b:9975"]}}}' 
```

**Comment by brukberhane** [comment]
I can confirm. I've been using `sqrl` for one of my zerotier networks and I was unable to create anything that didn't have a "." in the search domain...

**Comment by laduke** [comment]
This got fixed
