### ISSUE TITLE
Device cannot be reached but it can ping other devices

### ISSUE THREAD

**Issue by Suxsem** [zerotier/ZeroTierOne#1346]
I just installed a new ZeroTier OpenWRT node in my ZeroTier network following https://github.com/mwarning/zerotier-openwrt/wiki .

I can see the devices as ONLINE in my.zerotier.com and I can ping other devices from this one but I cannot reach nor ping it from outside.

It could be a NAT traversal issue? It's possible to get outbound traffic but not inbound one with ZeroTier?

**Comment by Suxsem** [comment]
After A LOT of time (like 10 minutes) I can finally ping my devices but it's still pretty laggy.
The upstream internet connection to my device is provided by a NordVPN WireGuard VPN tunnel, do you know if ZeroTier is not supported inside a NordVPN tunnel?

**Comment by joseph-henry** [comment]
Closing this issue, but feel free to re-open if you find out more.
