### ISSUE TITLE
CAPSLOCK got stuck

### ISSUE THREAD

**Issue by frenck** [zerotier/ZeroTierOne#1348]
![image](https://user-images.githubusercontent.com/195327/106885859-829f0100-66e3-11eb-8527-0241bff38cfd.png)

**Comment by frenck** [comment]
I'm confused, it didn't got stuck?
It is out of par with other release titles.

**Comment by frenck** [comment]
For the record, there is more non-standard on that release, making me think it might be malicious as a whole.

**Comment by glimberg** [comment]
This is a valid release to try to fix a bug.  Your issue is not a bug.  That's why it's closed.

**Comment by frenck** [comment]
Good to know that it is a valid release. Could you clarify why the format in both the title and release note differ as per usual?

**Comment by joseph-henry** [comment]
Thanks for your concern.

Discussions: https://discuss.zerotier.com/

And the format of the release note is similar to previous bug fix releases. Look at `1.4.0.1` for instance. Also, it's signed.

**Comment by frenck** [comment]
Thanks for clarifying that and thanks for the hint. Scrolling further down the line is seems that consistency is not a priority. 👍 

Will use the discussion forum next time.
