### ISSUE TITLE
Make it easier to specify paths for zerotier-cli

### ISSUE THREAD

**Issue by ramtej** [zerotier/ZeroTierOne#135]
Hi, 

- ZeroTierOne 1.0.2 on Ubuntu 14.04
- sudo ./zerotier-cli join id

./zerotier-cli: fatal error: unable to read node address from identity.public in home path

Zerotier was built from source code.. 

Cheers, 
jj

**Comment by adamierymenko** [comment]
Closing since local HTTP is replacing named pipes and such in -dev soon, and this will obsolete this stuff.
