### ISSUE TITLE
Connection restore takes multiple pings

### ISSUE THREAD

**Issue by AndreKR** [zerotier/ZeroTierOne#1350]
I have a network with two hosts, `10.147.19.1` and `10.147.19.213`. Both hosts have public IP addresses.

Every now and then (a few times a day) the connection will break. When this happens, trying to open a TCP connection will result in a "no route to host" error and pinging the other host will result in "destination host unreachable" errors. The situation usually resolves itself after a few minutes. It used to happen much more frequently but then I set up a ping every minute and since then it happens just a few times per day. So traffic going through the ZT connection seems to make a difference. (I was thinking NAT timeout, except those machines shouldn't have any NAT.)

Anyway, when it happens and I start pinging the other host, it always takes a few packets for the connection to come back:

```
# ping 10.147.19.1
PING 10.147.19.1 (10.147.19.1) 56(84) bytes of data.
From 10.147.19.213 icmp_seq=10 Destination Host Unreachable
From 10.147.19.213 icmp_seq=11 Destination Host Unreachable
From 10.147.19.213 icmp_seq=12 Destination Host Unreachable
From 10.147.19.213 icmp_seq=13 Destination Host Unreachable
From 10.147.19.213 icmp_seq=14 Destination Host Unreachable
From 10.147.19.213 icmp_seq=15 Destination Host Unreachable
64 bytes from 10.147.19.1: icmp_seq=16 ttl=64 time=2058 ms
64 bytes from 10.147.19.1: icmp_seq=17 ttl=64 time=1034 ms
64 bytes from 10.147.19.1: icmp_seq=18 ttl=64 time=10.3 ms
64 bytes from 10.147.19.1: icmp_seq=19 ttl=64 time=6.32 ms
64 bytes from 10.147.19.1: icmp_seq=20 ttl=64 time=2.27 ms
64 bytes from 10.147.19.1: icmp_seq=21 ttl=64 time=3.12 ms
```

At first I thought it simply takes a few seconds to rebuild the connection, but now I noticed something peculiar: A single ping plus a wait period does not restore the connection:

```
# ping -c 1 10.147.19.1
PING 10.147.19.1 (10.147.19.1) 56(84) bytes of data.
From 10.147.19.213 icmp_seq=1 Destination Host Unreachable

--- 10.147.19.1 ping statistics ---
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms

[wait some 10 seconds]

# ping -c 1 10.147.19.1
PING 10.147.19.1 (10.147.19.1) 56(84) bytes of data.
From 10.147.19.213 icmp_seq=1 Destination Host Unreachable

--- 10.147.19.1 ping statistics ---
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms
```

Connection still not restored.

Only when I start sending **multiple** pings the connection is rebuilt.

Is there any kind of (configurable) threshold how many packets it takes to initiate a connection?

**Comment by adamierymenko** [comment]
Still an issue with 1.6.4?
