### ISSUE TITLE
macOS: Disabling IPv4 for ZT network breaks IPv4 globally 

### ISSUE THREAD

**Issue by jcshort** [zerotier/ZeroTierOne#1356]
Disabling IPv4 in ZeroTier appears to disable it _globally_ on macOS.  I've observed this behavior with at 1.6.3 and 1.6.4 (likely going back to 1.6.0, but unverified), installed directly from pkg and via Homebrew Cask on macOS 10.15.7 on Intel, and 11.2 on M1/ARM.

```
$ ping 1.1.1.1
PING 1.1.1.1 (1.1.1.1): 56 data bytes
ping: sendto: Address family not supported by protocol family
Request timeout for icmp_seq 0
ping: sendto: Address family not supported by protocol family
Request timeout for icmp_seq 1
```

I attempted to go IPv6-only in my zerotier network, so I removed the IPv4 address assignment configuration.  Initially, the RFC1918 route remained in place. Removing this leftover route did not improve the situation - in fact, it appears to have expanded the scope of the bug to include a 10.15.x intel machine, whereas my 11.x ARM machine was initially the only victim.

**Comment by jcshort** [comment]
may be related to #1104

**Comment by joseph-henry** [comment]
Are you still seeing this issue with the current release?
