### ISSUE TITLE
Can’t join ZT on iOS

### ISSUE THREAD

**Issue by mikea** [zerotier/ZeroTierOne#1358]
## Required

- What you expect to be 
happening.

My iPhone has ZT app with network set up. I try to connect to network using the UI. This phone was able to connect to ZT two days ago. 

- What is actually happening?

This morning ZT can't initialize VPN while on my wifi. The VPN icon simply never shows. 

- Any steps to reproduce the error.

If I disable wifi ZT is able to o it VPN. Other devices don't have this problem on the same network. 

## Additional information 

**Desktop (please complete the following information):**
 - OS: iOS 14.4
 - OS/Distribution Version
 - ZeroTier Version 1.6.4

**Comment by mikea** [comment]
The issue has resolved itself since. I wish ZT had a status page and it's app give you more diagnostics wrt to the process.

**Comment by joseph-henry** [comment]
Are things still working for you? The issue you describe wouldn't be because of a service outage so a status page wouldn't help. If anything this sounds like a iOS VPN API issue. I'm going to close this issue but feel free to re-open it if you experience any further issues.
