### ISSUE TITLE
MacOS build from master (1.6.4) builds but fails to install or run on arm64

### ISSUE THREAD

**Issue by eejd** [zerotier/ZeroTierOne#1359]
I downloaded the current master from GitHub and following the readme successfully compiled ZeroTierOne including the GUI. However, the tap driver (still listed in the readme) no longer has a makefile rule (install-mac-tap is missing) though there is a binary 'MacEthernetTapAgent' in the repository. Further, 

zerotier-one produces:
`
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: home path does not exist, and could not create. Please verify local system permissions.
`

zerotier-cli produces:
`
./zerotier-cli: missing port and zerotier-one.port not found in /Library/Application Support/ZeroTier/One
`

the selftest appeared to pass, though I wasn't sure how to interpret the output:
`./zerotier-selftest 
[info] sizeof(void *) == 8
[info] OSUtils::now() == 1614299651157
[info] hardware concurrency == 8
[info] sizeof(NetworkConfig) == 432160
[other] Testing hex/unhex... PASS
[other] Testing InetAddress encode/decode... 127.0.0.1/9993 feed:dead:babe:dead:beef:f00d:1234:5678/12345  
[other] Testing/fuzzing Dictionary... PASS (junk value to prevent optimization-out of test: -19713)
[crypto] getSecureRandom: f030e9d79dcae0d667c28454a13597f1d37cbf93f01c4542b444c08e8864f8cc1c3f3efcfc194a67ecc83923b819d2718725671c9228f221aa3fba24b3e8004e
[crypto] getSecureRandom: c20993d7fcde5cbf29ff118ab2835dadab1926461d7fb75ac168e10ac993aafc3ecacc30b9bf028adbed3f24296140b1de2ba6263d4e1265cf62d1dc1a6256d1
[crypto] getSecureRandom: d61a91de77393c53953da770d958e21b5abec4ca677b16076deee4cc07ac05fcf6c46ad387adc10ed4057d523a623b3bc769e1c35ff1e786e3e46536bd92289a
[crypto] Testing Salsa20... PASS
[crypto] Salsa20 SSE: DISABLED
[crypto] Benchmarking Salsa20/12... 1096.03 MiB/second (f31ddbcdb3b69d0a5e19ba94a7e2facc)
[crypto] Benchmarking Salsa20/20... 634.543 MiB/second (24c619994ae7f1549136169c9072f3d7)
[crypto] Benchmarking AES-GMAC-SIV... 1446.83 MiB/second
[crypto] Testing SHA-512... PASS
[crypto] Testing Poly1305... PASS
[crypto] Benchmarking Poly1305... 1435.82 MiB/second
[crypto] Testing C25519 and Ed25519 against test vectors... PASS
[crypto] Testing C25519 ECC key agreement... PASS
[crypto] Benchmarking C25519 ECC key agreement... 0.1ms per agreement.
[crypto] Testing Ed25519 ECC signatures... PASS
[crypto] Benchmarking Ed25519 ECC signatures... 7.24ms per signature.
[packet] Testing Packet encoder/decoder... (compressed: 77, decompressed: 1116) PASS
[identity] Validate known-good identity... PASS (17.2ms per validation)
[identity] Validate known-bad identity... PASS (i.e. it failed)
[identity] Generate identity... (took 653ms): 265e2ec6dd:0:0944c93406c231e3794d78600e5b91ddaf75dfea1ef5d7cbe1497fa444276c22d2044dff2c00ae0861c90883380af539d2ee241d1f1f7b7a6f44e79c25f6ba81:a2fadb060c3c6d49dee81f46861d6c746cbd2c9cfa3daf0fb49993f7f81e3e21fb256f598505781b376a19b19c6d774a297911777ac7c39a89b089687be9f351
[identity] Locally validate identity: PASS
[identity] Generate identity... (took 1322ms): 47aa7f5f4d:0:a71e19038c150816b4d56aac8dd3de8f27c70199351b2e2965b3f34321305b182d37643346db7b83baff4f6bb0bc590d840088bb8f2b977066f631f3cc8e5366:71a4c6e7b74b0467523441bfa6da7a5074b1d886edc210a837f07477a417be79460ba9dc043aa03988726dfcc5d8ee47e266dfd3524f016fbb7b0f4b88a54cac
[identity] Locally validate identity: PASS
[identity] Generate identity... (took 277ms): a5b0a33efd:0:371ac0b243ea73b7d93eea10950b4599dbf2fe051454a30f21a3adccb5ab3b3ac220ea103d2efdf25c5cca299ca40faa2a532f3c12e91b4288dd5ecda6c80a68:355c89480fd74e9374c28022aac3b6ed09a8112475d87c4517780846fdd5dcce96ed1e90a1fc55b9c21613a50dce7cb17fc54d199187050226f726d9417ba620
[identity] Locally validate identity: PASS
[identity] Generate identity... (took 569ms): df41cd6fec:0:3665ef2002135d09d29939c05fedf382b35259f09522ee1f6c2583461c34f360f503dbe0f5024e893e6ef325deda3ed1f67a04eaf18bcb17675deec25e22fe66:d156c1cf13abcaa5e8c38c33ba2ca47652f0b8fbab4b1bf54feb4180d1e70388a3f9f0a99962d15c9e454d250bda305f76e2a42e6551689e806afdf3cc4b5048
[identity] Locally validate identity: PASS
[identity] Serialize and deserialize (w/private): PASS
[identity] Serialize and deserialize (no private): PASS
[identity] Serialize and deserialize (ASCII w/private): PASS
[identity] Serialize and deserialize (ASCII no private): PASS
[certificate] Generating identity to act as authority... 9835d639de
[certificate] Generating identities A and B... 31306a1b90, 0ed3b5ca8a
[certificate] Generating certificates A and B...
[certificate] Signing certificates A and B with authority...
[certificate] A agrees with B and B with A... yes, yes.
[certificate] Generating two certificates that should not agree...
[certificate] A agrees with B and B with A... no, no.
[phy] Creating phy endpoint...
[phy] Binding UDP listen socket to 127.0.0.1/60002... OK
[phy] Binding TCP listen socket to 127.0.0.1/60002... OK
[phy] Testing UDP send/receive... got 10000 packets, OK
[phy] Testing TCP... got 10 connect successes, 2 failures, and 10000000 bytes, OK`

This is on a MacBook M1 with MacOS 11.2.1

**Comment by glimberg** [comment]
ZeroTier requires root privileges.

`sudo zerotier-one` to launch from the command line.

**Comment by glimberg** [comment]
Also, the TAP driver is only for old versions of macOS.  It's not used at all on recent versions.

**Comment by eejd** [comment]
Thanks. Is there a way to do an install with MacOS config and system start via the make file? The MacOS package installer still requires Rosetta 2. I have been trying to test a non-Rosetta 2 config. Also, I note the documentation should be updated to make clear the Tap installer isn't required. Under the normal install, how are elevated privileges provided to the GUI?

**Comment by eejd** [comment]
I was able to load zerotier (sudo ./zerotier-one; sudo ./zerotier-cli join ###; sudo ./zerotier-cli listnetworks). However, I cannot ping or ssh to hosts on the network. (Connections are fine via a standard install on an intel Mac on the same physical network.)

**Comment by glimberg** [comment]
BTW:  M1 architecture support is already in the version of ZeroTier on the download page.

```
-> % file ./zerotier-one
./zerotier-one: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64]
./zerotier-one (for architecture x86_64):	Mach-O 64-bit executable x86_64
./zerotier-one (for architecture arm64):	Mach-O 64-bit executable arm64
```

**Comment by ymei** [comment]
> I was able to load zerotier (sudo ./zerotier-one; sudo ./zerotier-cli join ###; sudo ./zerotier-cli listnetworks). However, I cannot ping or ssh to hosts on the network. (Connections are fine via a standard install on an intel Mac on the same physical network.) I receive the following error:
> 
> ERROR: unable to configure virtual network port: MacEthernetTapAgent not present in ZeroTier home
> 
> adding the path for the repository where the MacEthernetTapAgent resides (and where the compiled zerotier-* binaries to the command line for starting zerotier causes the cli to return empty "{}" when I request info or listnetworks, however the MacEthernetTapAgent error does not occur.

I figured that `MacEthernetTapAgent` or a symlink to it must exist under `/Library/Application Support/ZeroTier/One`, then `sudo ./zerotier-one; sudo ./zerotier-cli join ###; sudo ./zerotier-cli listnetworks` run under the repo placed anywhere will work.
