### ISSUE TITLE
Try to skip compression for already-compressed streams (SSH, MP4, etc.) using some heuristic

### ISSUE THREAD

**Issue by adamierymenko** [zerotier/ZeroTierOne#136]
Data compression over what are 99% of the time going to be LAN links is a waste of cycles.

**Comment by maci0** [comment]
It might be a waste of cycles, but it could improve throughput.
People go as far as compressing RAM to get higher throughput in exchange for CPU cycles.

**Comment by adamierymenko** [comment]
The trouble is that quite a bit of the data that flows over networks is not compressible: encrypted data, compressed video and audio streams, etc. For that, it's a pure waste of cycles. You gain nothing.

It actually tends to bifurcate into two radically different categories: highly compressible "cheese poof" data like XML, HTML, and JSON, and uncompressable high-entropy data like SSH streams and MP4.

This actually gives me an idea. I'm resurrecting this and renaming it. Perhaps there could be some "learning" of what IP header or other heuristics correlate with what should and should not be compressed?

**Comment by maci0** [comment]
iirc lz4 had functions to check if it is applicable to compress a certain block or not.
i guess it just calculates the entropy of the block.

**Comment by maci0** [comment]
```
/*
LZ4_compressBound() :
    Provides the maximum size that LZ4 compression may output in a "worst case" scenario (input data not compressible)
    This function is primarily useful for memory allocation purposes (output buffer size).
    Macro LZ4_COMPRESSBOUND() is also provided for compilation-time evaluation (stack memory allocation for example).

    isize  : is the input size. Max supported value is LZ4_MAX_INPUT_SIZE
    return : maximum output size in a "worst case" scenario
             or 0, if input size is too large ( > LZ4_MAX_INPUT_SIZE)
*/
int LZ4_compressBound(int isize);

```

**Comment by adamierymenko** [comment]
That's interesting code. I'll take a look at it. The ideal solution would be able to tell if compression is worth it without actually going to the trouble of attempting it.

**Comment by adamierymenko** [comment]
Oh, that's not what that particular function does. It just returns the worst case output size for memory buffer allocation purposes. But an entropy sampling isn't necessarily a bad idea.

**Comment by maci0** [comment]
well you could say if the worst case is worse than e.g. 20% reduction in size don't bother do compress that block. i'd say just go with something like that. less code to maintain. lz4 is also widely used and AFAIK the fastest around atm.

If you want to calculate the entropy yourself this might be interesting: https://github.com/troydhanson/misc/tree/master/compression/entropy

again no need to duplicate work which has already been done :)

**Comment by adamierymenko** [comment]
Closing since the CPU overhead of doing this almost certainly negates the benefit.

A better option would be to make compression togglable on a local node basis or a network basis. Will save for a future performance push.
