### ISSUE TITLE
Windows doesnt seem to recognize local.conf

### ISSUE THREAD

**Issue by Gugi264** [zerotier/ZeroTierOne#1360]
I want to enable multipath and created a `local.conf` on ` C:\Program Files (x86)\ZeroTier\One`.
In it I set 

`
{
  "settings":
  {
    "defaultBondingPolicy": "broadcast"
  }
}
`

but  on `zerotier-cli listbonds ` I only see "None". Also I know that only my Ethernet Interface gets used for the connection as I can see in the Task Manager.

- What you expect to be happening.
Multipath to be working
- What is actually happening?
It's not working
- Any steps to reproduce the error.
Try to get Multipath to work on Windows

## Additional information 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - ZeroTier Version 1.6.4
  
Maybe the local.conf has to be in another folder?

**Comment by Gugi264** [comment]
Update:
I guess I got one step further, the correct path on windows seems to be `C:\Users\User\AppData\Local\ZeroTier\One`
Atleast if i run zerotier-cli dump I can see "broadcastEnabled": true. But it still only uses one interface?

**Comment by Gugi264** [comment]
Update again:
I guess I was happy to early, as broadcastEnabled means another type of broadcast.
After trying around a bit, I started copying the local.conf into every zerotier folder I could find:
`C:\Program Files\ZeroTier` and every subfolder
`C:\Program Files (x86)\ZeroTier` and every subfolder
`C:\Users\User\AppData\Local\ZeroTier` and every subfolder

But after running zerotier-cli dump all I get under local.conf is: None Present

What am I doing wrong?
Bonus Question: When does zerotier-cli check for the local.conf? Every time I run a command? Do I need to close it from the tray and restart it? Do I need to reboot?

**Comment by cwichura** [comment]
You want `%ProgramData%\ZeroTier\One\local.conf`.  And no need to reboot, ZeroTier periodically checks if the local.conf file has changed and re-reads it automatically.

**Comment by Gugi264** [comment]
Thank you! Now zerotier recognizes the local.conf!
But multipath doesnt seem to work, although it should try every possible Interface? Is there something else I have to do?
