### ISSUE TITLE
Cli enable bond command does nothing

### ISSUE THREAD

**Issue by Gugi264** [zerotier/ZeroTierOne#1363]
The command `zerotier-cli bond <peerId> enable` does nothing
https://github.com/zerotier/ZeroTierOne/blob/a5a94e3c49d9ea08fc67f175f0768c61d7ffe910/one.cpp#L563-L567

From the document at [https://zerotier.atlassian.net/wiki/spaces/SD/pages/568459265/Multipath](https://zerotier.atlassian.net/wiki/spaces/SD/pages/568459265/Multipath) it should:
"The `zerotier-cli bond <peerId> enable` will forcibly enable bonding on"

**Comment by joseph-henry** [comment]
Correct. This command was only used internally for testing and isn't widely available yet (despite the documentation). It will likely make it into an upcoming release.

**Comment by Gugi264** [comment]
Great!
Is there any up to date documentation how to get bonding to work? Or should bonding work automatically after multipath is set correctly?

**Comment by joseph-henry** [comment]
There's active development happening on the `dev-multipath` branch and we'll be updating its documentation in parallel at [docs.zerotier.com/zerotier/multipath](https://docs.zerotier.com/zerotier/multipath)

The feature you're asking about still isn't implemented but will be soon.
