### ISSUE TITLE
PORT_ERROR with tun enabled on OVZ7

### ISSUE THREAD

**Issue by Oujiii** [zerotier/ZeroTierOne#1368]
# Before filing a Bug Report

_Using these will ensure you get quicker support, and make this space available for code-related issues. Thank you!_

- [Knowledge Base](https://zerotier.atlassian.net/wiki/spaces/SD/overview) => Guides and documentation on how to use ZeroTier.
- [Discuss Forum](https://discuss.zerotier.com/) => Our discussion forum for users and support to mutually resolve issues & suggest ideas.
- [Reddit](https://www.reddit.com/r/zerotier/) => Our subreddit, which we monitor regularly and is fairly active.

# If you still want to file a Bug Report

## Required

- What you expect to be happening.
ZT connecting and creating a network interface
- What is actually happening?
ZT connects, but no network interface is created

```bash
$ sudo zerotier-cli listnetworks
200 listnetworks <nwid> <name> <mac> <status> <type> <dev> <ZT assigned ips>
200 listnetworks <redacted> <redacted> <redacted> PORT_ERROR PRIVATE  <redacted>
```

```bash
$ sudo ls /dev/net/
tun
```

```bash
$ sudo lsmod | grep tun
tun                     4242  -2
tunnel4                 4242  -2 sit
ip_tunnel               4242  -2 sit
vznetstat               4242  -2 tun,ip_vznetstat,ip6_vznetstat
```

```bash
$ cat /etc/*ele*
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

```bash
$ uname -a
Linux <redacted> 4.19.0 #1 SMP Mon Dec 9 19:36:21 MSK 2019 x86_64 GNU/Linux
```

## Additional information 

```bash
$ sudo zerotier-cli -v
1.6.4
```

Other systems that require `tun`works, like Tailscale.

**Comment by joseph-henry** [comment]
Are you still seeing this issue?

**Comment by Oujiii** [comment]
Yes, it is still happening. Not sure why.

**Comment by Games-Crack** [comment]
Me too

**Comment by Games-Crack** [comment]
Fix:
 `chmod 755 /dev/net
chmod 666 /dev/net/tun`
