### ISSUE TITLE
ZeroTierOneService Deadlock

### ISSUE THREAD

**Issue by heri16** [zerotier/ZeroTierOne#137]
When a remote ZeroTier node hosting an application server is offline/shutdown, I find that we need to restart the local ZeroTierOneService before applications would want to work again. Seem like a network buffer deadlock problem. This application uses the http protocol to communicate, but the same problem has also happened with our other applications using other forms of tcp-based protocols. Waiting hours does not help.

We have been asking users to restart the ZeroTierOneService through services.msc manually. This is a lousy workaround.

**Comment by adamierymenko** [comment]
I'm not entirely sure what's being described here. Let me see if I understand.

You're running a local application that communicates with a remote application server, and that server goes down. The local application becomes unresponsive until or unless the ZeroTier One service is restarted.

Is that right?

Are you sure this isn't simply a result of the remote application server vanishing? What would happen if the two systems were on a LAN and you unplugged the network cable? Keep in mind that restarting the ZeroTier service has the side effect of disabling and re-enabling the interfaces, which would reset all TCP connections going through the interface. Without this reset, it's possible that the application is never detecting that the application server is no longer responding.

Does the application have an option for TCP keep alive?

**Comment by adamierymenko** [comment]
Closing unless further comment is received or others report something like this.
