### ISSUE TITLE
ZeroTier One daemon: 100% CPU utilization on Raspbery Pi 3 B+

### ISSUE THREAD

**Issue by pcgeek86** [zerotier/ZeroTierOne#1373]
# Before filing a Bug Report

_Using these will ensure you get quicker support, and make this space available for code-related issues. Thank you!_

- [Knowledge Base](https://zerotier.atlassian.net/wiki/spaces/SD/overview) => Guides and documentation on how to use ZeroTier.
- [Discuss Forum](https://discuss.zerotier.com/) => Our discussion forum for users and support to mutually resolve issues & suggest ideas.
- [Reddit](https://www.reddit.com/r/zerotier/) => Our subreddit, which we monitor regularly and is fairly active.

# If you still want to file a Bug Report

## Required

- What you expect to be happening. ZeroTier consumes a nominal amount of CPU cycles, proportionate to the work it's doing.
- What is actually happening? ZeroTier is consuming 100% CPU.
- Any steps to reproduce the error. Tried using Visual Studio Code with the Remote - SSH extension to connect to the device across a spotty internet connection. Had to reconnect multiple times, and eventually lost access to the device entirely. After waiting a while, the device started responding again, and I was able to SSH into it to run `top`.
- Any screenshots that would help us out.

![image](https://user-images.githubusercontent.com/466713/112002539-39f9a680-8add-11eb-8d25-f63184fecd5c.png)

After running `sudo systemctl restart zerotier-one.service`, CPU utilization appears normal ~1%.

![image](https://user-images.githubusercontent.com/466713/112003436-23a01a80-8ade-11eb-88a4-8b3af47ac6e5.png)

## Additional information 

**Desktop (please complete the following information):**
 - OS: [e.g. Mac, Linux, Windows, BSD] Ubuntu Linux 20.04 Focal Fossa ARM 64-bit 
 - ZeroTier Version [e.g. 1.4.6] 1.6.4

I cannot find any log files, so I cannot determine what the ZeroTier One daemon is doing that would cause it to chew up CPU cycles unnecessarily.

**Additional context**
- ZeroTier Network Configuration: IPv4 & IPv6 networks defined on your ZeroTier Central
- Router Config: are you permitting port 9993, uPnP, and NAT-PMP? Yes
- Firewall Config: are you permitting port 9993 on your OS; setting it to "Private" on Windows? Yes
- Are you using this at home, in an office, college, etc? Home / across Internet

**Comment by laduke** [comment]
Hi thanks for writing. 
How often does it get into that state? Let us know if you think of anything that could be triggering it. 
Have you changed any of the zerotier network settings from the defaults?

**Comment by pcgeek86** [comment]
I've just recently connected this device to ZeroTier, about 4 days ago. I haven't changed any of the default ZeroTier network configuration settings. Since I've installed the software, I have only seen this issue crop up once. 

Without any kind of logging, there's no way I could possibly know what caused this behavior.

I mentioned using Microsoft Visual Studio Code to remotely connect to the device, using the Remote - SSH extension, in my original post. Beyond that, I have no clue.

**Comment by pcgeek86** [comment]
Is there some way to enable logging, so we can identify a root cause next time this crops up? At the moment, I have no way of inspecting what the client is doing.

**Comment by laduke** [comment]
There's no logging. 
There's `sudo zerotier-cli dump` that outputs the current state

**Comment by joseph-henry** [comment]
I have a hunch that this will be solved with the changes in the current `dev` branch. I'd give that a try. If you can't compile it yourself we will be shipping a `1.6.5` at some point in the near future.

**Comment by pcgeek86** [comment]
Sweet, thanks for the heads up. I'll try it out once a package is available. 

The lack of logging is a little concerning, just as a general principal, though. Do you guys have any kind of debugging guidance for complex issues like this? Generally I'd expect some logs to be written to /var/log. Seems odd that an application like ZeroTier would explicitly avoid logging. Is there some reasoning behind that decision?

Either way, I appreciate the free software. ZeroTier is a niche player that solves some real hybrid networking challenges. Planning to incorporate it as part of the training content I'm building, at some point. Thank you!

**Comment by joseph-henry** [comment]
@pcgeek86 Thanks for the kind words. Hopefully your issue was resolved with `1.6.5` (let me know if it wasn't). But to your question about logging, that is an area we're trying to improve upon. We do have a decent amount of logging in the debug builds (built with `ZT_DEBUG=1`) that isn't exposed on release build. And we do have plans to provide better logging facilities in 2.0.
