### ISSUE TITLE
1.6.4 on windows does not work with Central API key

### ISSUE THREAD

**Issue by erikh** [zerotier/ZeroTierOne#1374]
- What you expect to be happening.

> Go to the properties, add your central key. Right click the icon and select "create and join network".

- What is actually happening?

> It crashes.

## Additional information 

**Desktop (please complete the following information):**
 - OS: Windows: https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/ these builds specifically
 - OS/Distribution Version
 - ZeroTier Version: 1.6.4
  
**Additional context**

VMWare Workstation 15 with a bridged adapter

**Comment by laduke** [comment]
This UI needs to be removed. It's left over from a defunct feature.

**Comment by glimberg** [comment]
it is removed with the upcoming UI refresh
