### ISSUE TITLE
Is it possible to make an automatic connection?

### ISSUE THREAD

**Issue by izmoxkawaii** [zerotier/ZeroTierOne#1375]
Is it possible to automatically establish a vpn connection in the background when the 'Game Start' button is pressed in the Game Launcher?
I want to put it in a specific directory without integrating
launcher will automatically open it
/Game/Bin/Resource/zerotierconnection.exe
How do I auto connect without interface or anything
thanks in advance...

**Comment by joseph-henry** [comment]
You on Windows? Are you developing this game yourself?

ZT needs a TAP driver installed to create interfaces for your game to talk over. If installing ZT is an issue and you want only your game to talk over the ZT network (and not other apps) then I would take a look at [libzt](github.com/zerotier/libzt)
