### ISSUE TITLE
Connection issue on iPad

### ISSUE THREAD

**Issue by chestnutprog** [zerotier/ZeroTierOne#1385]
## Required

- What you expect to be happening.
Connect to my network normally.
- What is actually happening?
I can see the Network's name and other information on iPad, Status is OK, I can also see ONLINE, zt version, Physical IP in Central.
Managed IPs Field in ZT app is always blank, and I can't connect to my devices, while iOS VPN status page shows managed IP correctly.
- Any steps to reproduce the error.
- Any screenshots that would help us out.
  
 - Device: iPad Pro
 - OS: iOS 14.4.2
 - ZeroTier Version 1.6.4

I'm wondering how to gather more debug information and how to solve it.

**Comment by joseph-henry** [comment]
Hello, @chestnutprog Are you still seeing this problem?

**Comment by chestnutprog** [comment]
It works fine now, thanks.
