### ISSUE TITLE
ifconfig shells are never issued on some systems

### ISSUE THREAD

**Issue by dch** [zerotier/ZeroTierOne#1386]
On some systems, with zerotier 1.6.4, built from ports and also tested with src builds, something seems to block the creation of tap interfaces - the `/sbin/ifconfig` commands are simply never reached.

- FreeBSD 13.0-RELEASE
- arm64 `APM eMAG 8180 r3p2` (Ampere 32-core armv8 processor, not your average raspberry pi)
- amd64   `Intel(R) Atom(TM) CPU  C2750  @ 2.40GHz`

Both these systems have had no trouble running zerotier on 12.2-RELEASE and my normal jam, 14.0-CURRENT.

On a working system, using dtrace:

```
INFO Watching 'proc:kernel:none:exec-success' ...
2021 Apr 15 07:27:03 0.0 zerotier-one[59]: zerotier-one /var/db/zerotier-one
      \-+= 00059 0.0 zerotier-one /var/db/zerotier-one
2021 Apr 15 07:27:04 0.0 ifconfig[6459]: /sbin/ifconfig tap9994 create
    \-+= 00059 0.0 zerotier-one /var/db/zerotier-one
      \-+= 06459 0.0 /sbin/ifconfig tap9994 create
2021 Apr 15 07:27:04 0.0 ifconfig[6730]: /sbin/ifconfig tap9994 name zt1flo98dm17np8
```

On a failing system, there is simply no output at all. There are no `ifconfig` processes even launched, (observed via dtrace & ktrace) so the problem must be earlier in zt and not directly in the `BSDEthernetTap.cpp` code.

**Comment by dch** [comment]
running dtrace on a failing system:

```
2021 Apr 15 15:07:02 0.0 zerotier-one[48504]: -> pid48504:zerotier-one:_start:entry zerotier-one
2021 Apr 15 15:07:02 0.0 zerotier-one[48504]: -> pid48504:zerotier-one:handle_static_init:entry zerotier-one
2021 Apr 15 15:07:02 0.0 zerotier-one[48504]: -> pid48504:zerotier-one:main:entry zerotier-one
2021 Apr 15 15:07:02 0.0 zerotier-one[48504]: -> pid48504:zerotier-one:_Z6strstrUa9enable_ifIXLb1EEEPcPKc:entry zerotier-one
2021 Apr 15 15:07:02 0.0 zerotier-one[48504]: -> pid48504:zerotier-one:_Z15__libcpp_strstrPKcS0_:entry zerotier-one
2021 Apr 15 15:07:02 0.0 zerotier-one[48504]: -> pid48504:zerotier-one:_Z6strstrUa9enable_ifIXLb1EEEPcPKc:entry zerotier-one
2021 Apr 15 15:07:02 0.0 zerotier-one[48504]: -> pid48504:zerotier-one:_Z15__libcpp_strstrPKcS0_:entry zerotier-one
2021 Apr 15 15:07:02 0.0 zerotier-one[48504]: -> pid48504:zerotier-one:_Z6strstrUa9enable_ifIXLb1EEEPcPKc:entry zerotier-one
2021 Apr 15 15:07:02 0.0 zerotier-one[48504]: -> pid48504:zerotier-one:_Z15__libcpp_strstrPKcS0_:entry zerotier-one
2021 Apr 15 15:07:02 0.0 zerotier-one[48504]: -> pid48504:zerotier-one:_Z6strstrUa9enable_ifIXLb1EEEPcPKc:entry zerotier-one
2021 Apr 15 15:07:02 0.0 zerotier-one[48504]: -> pid48504:zerotier-one:_Z15__libcpp_strstrPKcS0_:entry zerotier-one
2021 Apr 15 15:07:02 0.0 zerotier-one[48504]: -> pid48504:zerotier-one:_ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEC2Ev:entry zerotier-one
2021 Apr 15 15:07:02 0.0 zerotier-one[48504]: -> pid48504:zerotier-one:_ZNSt3__117__compressed_pairINS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE5__repES5_EC2INS_18__default_init_tagESA_EEOT_OT0_:entry zerotier-one
2021 Apr 15 15:07:02 0.0 zerotier-one[48504]: -> pid48504:zerotier-one:_ZNSt3__17forwardINS_18__default_init_tagEEEOT_RNS_16remove_referenceIS2_E4typeE:entry zerotier-one
2021 Apr 15 15:07:02 0.0 zerotier-one[48504]: -> pid48504:zerotier-one:_ZNSt3__122__compressed_pair_elemINS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE5__repELi0ELb0EEC2ENS_18__default_init_tagE:entry zerotier-one
2021 Apr 15 15:07:02 0.0 zerotier-one[48504]: -> pid48504:zerotier-one:_ZNSt3__17forwardINS_18__default_init_tagEEEOT_RNS_16remove_referenceIS2_E4typeE:entry zerotier-one
2021 Apr 15 15:07:02 0.0 zerotier-one[48504]: -> pid48504:zerotier-one:_ZNSt3__122__compressed_pair_elemINS_9allocatorIcEELi1ELb1EEC2ENS_18__default_init_tagE:entry zerotier-one
2021 Apr 15 15:07:02 0.0 zerotier-one[48504]: -> pid48504:zerotier-one:_ZNSt3__19allocatorIcEC2Ev:entry zerotier-one
```

we can see there is *never* a forked process. something's askew, and we never get to the point of spinning up the thread that creates tap interfaces. why?

**Comment by dch** [comment]
As an additional check:

```
$ sysctl -a |egrep 'net.link.t|debug.if_t'
net.link.tap.debug: 1
net.link.tap.devfs_cloning: 1
net.link.tap.up_on_open: 1
net.link.tap.user_open: 1
net.link.tun.devfs_cloning: 1
debug.if_tun_debug: 1
```

```
# zerotier /var/db/zerotier-one
DEBUG: checking for device name tap9993 /dev/tap9993
DEBUG: ifconfig tap9993 create
DEBUG: ifconfig tap9993 name ztagim5o45dhe4c
ztagim5o45dhe4c
DEBUG: ifconfig ztagim5o45dhe4c lladdr 8e:23:63:d1:3c:17 mtu 2800 metric 5000 up
DEBUG: ifconfig ztagim5o45dhe4c inet6 fca2:927d:4d9b:bbdb:fdd2::1/40 alias
DEBUG: checking for device name tap9993 /dev/tap9993
DEBUG: checking for device name tap9994 /dev/tap9994
DEBUG: ifconfig tap9994 create
DEBUG: ifconfig tap9994 name zt1flo98dm17np8
zt1flo98dm17np8
DEBUG: ifconfig zt1flo98dm17np8 lladdr 2a:44:a8:b7:be:db mtu 2800 metric 5000 up
DEBUG: ifconfig zt1flo98dm17np8 inet6 fc7b:c4d6:6b9b:bbdb:fdd2::1/40 alias
requesting configuration for network 17d709436c13df28
requesting configuration for network a84ac5c10ad8b88c
learned new path ...
Apr 15 19:51:12 akai kernel: [22208] tap9993: Ethernet address: 58:9c:fc:10:ff:d3
Apr 15 19:51:12 akai kernel: [22208] tap9993: interface tap9993 is created, minor = 0x2709
Apr 15 19:51:12 akai kernel: [22208] tap9993: changing name to 'ztagim5o45dhe4c'
Apr 15 19:51:12 akai kernel: [22208] tap9994: Ethernet address: 58:9c:fc:00:0f:27
Apr 15 19:51:12 akai kernel: [22208] tap9994: interface tap9994 is created, minor = 0x270a
Apr 15 19:51:12 akai kernel: [22208] tap9994: changing name to 'zt1flo98dm17np8'
```

**Comment by dch** [comment]
and on failing nodes, none of this happens

**Comment by adamierymenko** [comment]
Looking into this before 1.4.5.

**Comment by adamierymenko** [comment]
We installed a fresh copy of FreeBSD 13 (amd64) and were not able to duplicate this. This was with 1.6.5, which we're releasing very shortly.

**Comment by dch** [comment]
Thanks Adam. I'm having a hit & mix success here too, latest dev branch for reference + my #1304 patch.So far I've tested 11 systems, 3 have this issue (2 amd64, 1 arm64).

Other similar systems have no issue:

- amd64 `Intel(R) Xeon(R) CPU E5-2667 v4 @ 3.20GHz`
- amd64 `Intel(R) Atom(TM) CPU  C2750  @ 2.40GHz` almost identical to the other Atom CPU that fails

What does ZT do/wait/need before it calls into the EthernetTapCpp code path? tracing the code produces way too much logs to read from.

cc @darkain can you check your arm64 systems to see if they suffer from this issue too? It's enough to see if the zt* interfaces come up

**Comment by darkain** [comment]
If I get some time this weekend, I'll start upgrading all of my test infrastructure to 13.0-RELEASE and can start poking into this. For now, all of my testing infrastructure is virtual machines, so hopefully if something is b0kt, it'll break there too and I can help diagnose it.

**Comment by dch** [comment]
I moved `/var/db/zerotier-one` dir from a broken box to a working one, and re-ran the debugger.

- failing systems don't have `/var/db/zerotier-one/networks.d/*.conf` files - the entire directory is missing. 
- renaming the `networks.d` dir on working systems, immediately converts them into broken ones
- fixing this is as easy as re-joining the missing networks

I'm closing this as it looks awfully like an own goal from our side. Maybe automation tools starting ZT without having existing config deployed prior?

**Comment by dch** [comment]
@adamierymenko maybe its worth adding a debug message if *no* interfaces / networks are available or present, to join?
