### ISSUE TITLE
Using Zerotier DNS causes Network Issues in Google Chrome on macOS

### ISSUE THREAD

**Issue by robertschreib** [zerotier/ZeroTierOne#1387]
## Required

- What you expect to be happening.
Stable Browsing Experience in Google Chrome
- What is actually happening?
Every Time the DNS servers get synced, I get a `ERR_NETWORK_CHANGED` in Chrome.
- Any steps to reproduce the error.
Set up a new ZeroTier network with a DNS resolver configured. Every time ZeroTier synchronizes it's DNS Servers Chrome will produce an `ERR_NETWORK_CHANGED`, or any running Downloads will fail with the Error  `Network disconnected`.

## Additional information 

**Desktop (please complete the following information):**
 - macOS 10.15.7
 - ZeroTier Version 1.6.4

**Comment by joseph-henry** [comment]
This appears to have been fixed. Thanks for your PR. Closing.
