### ISSUE TITLE
1.6.5 (x64): zttap300.inf has a broken signature

### ISSUE THREAD

**Issue by 13-beta2** [zerotier/ZeroTierOne#1391]
Tap-windows driver cannot be (re-)installed during update due to the outdated .inf file signature.
![image](https://user-images.githubusercontent.com/2017168/115627972-89afd580-a308-11eb-8dc6-68d9da8540a7.png)

**Comment by glimberg** [comment]
What version of Windows are you running?

**Comment by joseph-henry** [comment]
This is probably the culprit: https://github.com/zerotier/ZeroTierOne/pull/1347

**Comment by glimberg** [comment]
D'oh.  Yeah that'll need to be re-signed

**Comment by 13-beta2** [comment]
> What version of Windows are you running?

10.0.19042.928. I believe that is not version specific issue though.

**Comment by glimberg** [comment]
> I believe that is not version specific issue though.

Depending on your windows version it could indeed be as we don't support Windows 7 or older.  Seems like you're on 10 though.

**Comment by 13-beta2** [comment]
BTW, attempt to install .inf from 1.6.4 package with .cat unchanged (1.6.5) was successful. So yes, seems to be file versions mismatch.

**Comment by adamierymenko** [comment]
This should be fixed now. Please re-open if it re-appears.
