### ISSUE TITLE
ZeroTier no longer installs silently on Windows.

### ISSUE THREAD

**Issue by jedieaston** [zerotier/ZeroTierOne#1392]
As of the latest release (1.6.5), ZeroTier now pops up a "successfully installed" box when installing the MSI silently that you must click OK on for the installation to complete:

![image](https://user-images.githubusercontent.com/21368066/115650803-f7073a80-a2f7-11eb-809b-634097b73c4d.png)

When installing ZeroTier via chocolatey or winget, or installing it on a server or on user workstations as part of an imaging workflow, not being able to silently install is a real nonstarter. Is there any way it can go back to how it was, where the MSI just installed silently/passively?

(This is on Windows 10, version 20H2)

**Comment by adamierymenko** [comment]
Hmm... okay, will check on this and possibly publish another MSI installer. We added that box because otherwise it was too silent on normal installs and it didn't look like it installed correctly (even though it did).

**Comment by adamierymenko** [comment]
This should be fixed.
