### ISSUE TITLE
Error Joining Network: Cannot connect to ZeroTier service.

### ISSUE THREAD

**Issue by teksek** [zerotier/ZeroTierOne#1393]
When I click **"Join network"** and enter the ZeroTwo network ID, I get the error **"Error Joining Network: Cannot connect to ZeroTier service."**. I tried everything, reset the computer, reinstalled the ZeroTier One, tried all the methods I found on the internet and nothing works. Please help.

**Comment by teksek** [comment]
I need fast help 🙏

**Comment by HarshadkCon** [comment]
Can you please share details please?

**Comment by teksek** [comment]
Oh, the ZeroTier One repaired itself after 4 hours. You can now close the problem.

**Comment by teksek** [comment]
Sorry, this issue is back.

**Comment by teksek** [comment]
![image](https://user-images.githubusercontent.com/82138346/115969180-fe1e8a80-a53b-11eb-8cdc-44631d479d7c.png)

i have **"Node ID: unkown"**

and when i try join to my friend network ZeroTier One don't work's and shows me that error:

![image](https://user-images.githubusercontent.com/82138346/115969249-59507d00-a53c-11eb-93fe-3aec19d96715.png)


My windows 10 version as follows:

![image](https://user-images.githubusercontent.com/82138346/115969286-8735c180-a53c-11eb-94d5-8cfbe430bc2e.png)

**Comment by teksek** [comment]
I needed to download this version: https://download.zerotier.com/RELEASES/1.2.8/dist/

and ZeroTier One started working:

![image](https://user-images.githubusercontent.com/82138346/115990233-61530000-a5c2-11eb-9a1a-75362c38269a.png)

**Comment by joseph-henry** [comment]
Does this still happen with `1.6.5`?
