### ISSUE TITLE
it is offline on M1

### ISSUE THREAD

**Issue by iT-Boyer** [zerotier/ZeroTierOne#1395]
# Before filing a Bug Report

_Using these will ensure you get quicker support, and make this space available for code-related issues. Thank you!_

- [Knowledge Base](https://zerotier.atlassian.net/wiki/spaces/SD/overview) => Guides and documentation on how to use ZeroTier.
- [Discuss Forum](https://discuss.zerotier.com/) => Our discussion forum for users and support to mutually resolve issues & suggest ideas.
- [Reddit](https://www.reddit.com/r/zerotier/) => Our subreddit, which we monitor regularly and is fairly active.

# If you still want to file a Bug Report

## Required

- What you expect to be happening.
- What is actually happening?
- Any steps to reproduce the error.
- Any screenshots that would help us out.

![截屏2021-04-25 上午11 36 07](https://user-images.githubusercontent.com/4022953/115979777-74fa6880-a5ba-11eb-809c-441b8b53fd07.png)

but, it log:
```
$ zerotier-cli info
>200 info a55***da5 1.6.5 OFFLINE
```
## Additional information 

**Desktop (please complete the following information):**
 - OS: Mac M1
 - Big Sur 11.2.3 (20D91)
 - ZeroTier Version 1.6.5

**Additional context**
- ZeroTier Network Configuration: IPv4 & IPv6 networks defined on your ZeroTier Central
- Router Config: are you permitting port 9993, uPnP, and NAT-PMP?
- Firewall Config: are you permitting port 9993 on your OS; setting it to "Private" on Windows?
- Are you using this at home, in an office, college, etc?

**Comment by joseph-henry** [comment]
Hello, @iT-Boyer are you still having this problem?

**Comment by hunan128** [comment]
M1 no ploblem

**Comment by joseph-henry** [comment]
Excellent. Let us know if you have any issues. Closing.
