### ISSUE TITLE
ZeroTier Killed with CentOS 6.10 -> 9331 Killed   $ZT $ZT_OPTIONS -d    [FAILED]

### ISSUE THREAD

**Issue by lealog** [zerotier/ZeroTierOne#1396]
## Required

- What you expect to be happening.

 > Install ZeroTier on Centos 6.10 and start the zerotier with no ptoblems.

- What is actually happening?

> After install, the process is killed

> I'm having the following error:
> /etc/init.d/zerotier-one start
> Starting zerotier-one: /etc/init.d/zerotier-one: line 44:  9331 Killed                  $ZT $ZT_OPTIONS -d
>                                                            [FAILED]
> 

- Any steps to reproduce the error.

> Using centos 6.10
> Install Zerotier
> Try to start Zerotier
> 
> The proces is always killed

## Additional information 

**Desktop (please complete the following information):**
 - OS: [e.g. Mac, Linux, Windows, BSD]
 - OS/Distribution Version

>  lsb_release -a
> LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch
> Distributor ID: CentOS
> Description:    CentOS release 6.10 (Final)
> Release:        6.10
> Codename:       Final

**Comment by joseph-henry** [comment]
I don't think we officially support CentOS 6 as that release is 10 years old and not event actively supported by its creators. I'd suggest either a) updating your OS, or b) building from source and running the daemon manually.
