### ISSUE TITLE
Working node missing on Zerotier Central admin panel list

### ISSUE THREAD

**Issue by ato2** [zerotier/ZeroTierOne#1398]
My student joined  our private net on his Windows 10 , ZT 1.6.5
I successfully authorized him by API request (curl) and he can see peers and all is working.
I can also see him on my peers list, but he did not appears on ZeroCentral admin panel node list.
I expect to see him as I see the others.
API response:
{"id":"83048a0632d2b7a6-a3441458ec","type":"Member","clock":1620113762798,"networkId":"83048a0632d2b7a6","nodeId":"a3441458ec","controllerId":"83048a0632","hidden":false,"name":"","online":true,"description":"","config":{"activeBridge":false,"address":"a3441458ec","authorized":true,"capabilities":[],"creationTime":1618832522157,"id":"a3441458ec","identity":"a3441458ec:0:4536afbd6a38de50267b19c9ea15a3fa760af5a08e94c2f7a5a248b55013497456175cf70705a29c5b923c952528578d36146327cdce61c2518fdb78989ee466","ipAssignments":["172.29.146.153"],"lastAuthorizedTime":1620113762782,"lastDeauthorizedTime":0,"noAutoAssignIps":false,"nwid":"83048a0632d2b7a6","objtype":"member","remoteTraceLevel":0,"remoteTraceTarget":null,"revision":4,"tags":[],"vMajor":1,"vMinor":6,"vRev":5,"vProto":12},"lastOnline":1620113745684,"physicalAddress":"A.B.C.D","physicalLocation":null,"clientVersion":"1.6.5","protocolVersion":12,"supportsRulesEngine":true}%
(edited physicalAddress)

C:\Windows\System32> zerotier-cli listnetworks
200 listnetworks <nwid> <name> <mac> <status> <type> <dev> <ZT assigned ips>
200 listnetworks 83048a0632d2b7a6 ZET a6:14:96:26:5e:66 OK PRIVATE ethernet_32778 172.29.146.153/24
PS C:\Windows\System32> ping ftp
Pinging ftp [172.29.146.22] with 32 bytes of data:
Reply from 172.29.146.22: bytes=32 time=10ms TTL=64
........
Ping statistics for 172.29.146.22:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 8ms, Maximum = 26ms, Average = 17ms

**Comment by laduke** [comment]
What is the node ID that is missing?

**Comment by glimberg** [comment]
The member has been deleted previously.  At the bottom of the member list you can manually re-add it

**Comment by ato2** [comment]
OK - works - thanks.
