### ISSUE TITLE
ZeroTier adapter always on

### ISSUE THREAD

**Issue by Maasea** [zerotier/ZeroTierOne#1399]
## Required

- ZeroTier adapter always show connect though I have close it.
- I don't set "start with windows" and ZeroTier  doesn't show tray icon, but the adapter also show connect when I reboot.

## Additional information 

**Desktop (please complete the following information):**
 - OS: [Windows]
 - OS/ Windows 10 Pro 20H2
 - ZeroTier Version [1.6.5]

**Comment by laduke** [comment]
The tray app is just a GUI. There is a background system service called ZeroTier One. 

If you leave all your networks, there won't be any adapters.
You can stop the system service or uninstall.
