### ISSUE TITLE
Network preferred relays

### ISSUE THREAD

**Issue by thinxer** [zerotier/ZeroTierOne#140]
Is it possible to add additional relay nodes for a network?

There are sometimes not possible to create direct connections from A to B, but A to C and C to B can be very fast. Official relay are too slow (ping > 500ms and unreliable) for me to use.

**Comment by adamierymenko** [comment]
This is an interesting idea.

I'd planned for a much more elaborate form of federation in the future, but what you suggest sounds like a simpler concept. It might be a good way to get started with the federation concept -- simply allowing per-network traffic off-load for relaying.

I could see this appealing to institutional users, since of the 5% or so who cannot make direct p2p links a significant number are on large institutional LANs behind very restrictive corporate-type firewalls.

**Comment by thinxer** [comment]
Not necessarily behind corporate firewalls -- here at China we have two large ISPs, China Unicom and China Telecom, and the connectivity between them can be very bad (worse than relaying through master nodes). However, there are some cloud hosting service that has connectivity to both worlds, and relaying through them can be very fast.

What's the federation concept? I cannot find anything about it here.

**Comment by adamierymenko** [comment]
Whoa... you're telling me that peering between China's two largest ISPs is slower than bouncing off a cloud node? That's awful.

Federation:

Right now supernodes are just flat out designated via something called the root topology. I'd like to move to a system where supernode status is designated by an identity being signed. That would allow you to run your own, which is appealing to enterprises that want on-premise supernodes and other use cases.

**Comment by whlspacedude** [comment]
This is also appealing to me, I currently have a client in Shanghai (he finally turned on the raspberry-pi node I sent him in November).

Will Laws

**Comment by adamierymenko** [comment]
I think this is going to make it into 1.0.3. For packets destined for a particular network, it will be possible to designate one or more nodes on that network as preferred initial relays which will cause them to act like supernodes. The regular supernodes will still be available of course if these are down as final fallback, and will still be used for traffic to networks you don't admin. But this will rock for on-site deployments too.

The more I think about it, the more I think this might reduce the need for the kind of true federation I was imagining. Have to think on it more. But it's a most-of-the-way-there measure that will work for a lot of people at the very least.

**Comment by donspaulding** [comment]
Is this still planned for the next release?

**Comment by adamierymenko** [comment]
Yes, it is. It's actually relatively easy to do.

**Comment by adamierymenko** [comment]
This little feature is now in -dev -- will require control panel support but it seems to work. Not really terribly complex to implement. That was officially the last feature before 1.0.3 beta.

**Comment by heri16** [comment]
Is there a guide on how to make this work?

**Comment by zielmicha** [comment]
Is there any current information on the network specific relays? Will adding a new moon automatically route traffic via it, if required? Will it also work for TCP relays (in cases where UDP is blocked)?

**Comment by dejadejoder** [comment]
Hi,
I am also looking for information on howto fallback on my moons relays if UDP is not available.
As expected (documentation on https://github.com/zerotier/ZeroTierOne), fallback to TCP is just to slow...

**Comment by bleppard** [comment]
Hi @adamierymenko is there documentation on setting this up? Particularly for the case where a really is still wanted even though a direction connection is possible.

Thanks

**Comment by janjaapbos** [comment]
You can blacklist all paths either for a network or just a node. This will mean that it will relay either through the public roots or your own moon(s) if you have set that up. See local.conf in https://github.com/zerotier/ZeroTierOne/tree/master/service .
