### ISSUE TITLE
zerotier-cli bond list throws an exception

### ISSUE THREAD

**Issue by eric** [zerotier/ZeroTierOne#1403]
## What you expect to be happening

I expected to run `zerotier-cli bond list` and have it return successfuly.

## What is actually happening?

```
root@OpenWrt:~# zerotier-cli bond list
zerotier-cli bond list
    <peer>                        <bondtype>    <status>    <links>
terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.302] type must be number, but is null
Aborted
```

## Additional information 

 - Device/OS/Distribution: OpenWRT
 - ZeroTier Version: 1.6.5

**Comment by joseph-henry** [comment]
Thank you. Fixed.
