### ISSUE TITLE
Duplicated paths of peer

### ISSUE THREAD

**Issue by lideming** [zerotier/ZeroTierOne#1404]
Sometimes there are duplicated paths of peers from the API as well as zerotier-cli.
These outputs come from a server node acting as both controller and moon.

```jsonc
{
  "address": "[id_of_some_peer]",
  "isBonded": false,
  "latency": 26,
  "paths": [
   {
    "active": true,
    "address": "***.***.124.176/60703",
    "expired": false,
    "lastReceive": 1621271590896,
    "lastSend": 1621271590896,
    "preferred": true,
    "trustedPathId": 0
   },
   { // This one...
    "active": true,
    "address": "***.***.124.139/27907",
    "expired": false,
    "lastReceive": 1620840086771,
    "lastSend": 1620840327499,
    "preferred": false,
    "trustedPathId": 0
   },
   { // ...and this one have the same address and timestamps
    "active": true,
    "address": "***.***.124.139/27907",
    "expired": false,
    "lastReceive": 1620840086771,
    "lastSend": 1620840327499,
    "preferred": false,
    "trustedPathId": 0
   }
  ],
  "role": "LEAF",
  "version": "1.6.5",
  "versionMajor": 1,
  "versionMinor": 6,
  "versionRev": 5
 }
```

Even there are duplicated paths that are both `preferred`.

```jsonc
{
  "address": "[id_of_another_peer]",
  // ...
  "paths": [
    {
      "active": true,
      "address": "***.***.210.222/29795",
      "expired": false,
      "lastReceive": 1621271888362,
      "lastSend": 1621271888361,
      "preferred": true,
      "trustedPathId": 0
    },
    {
      "active": true,
      "address": "***.***.210.222/29795",
      "expired": false,
      "lastReceive": 1621271888362,
      "lastSend": 1621271888361,
      "preferred": true,
      "trustedPathId": 0
    }
  ],
  // ...
}
```

**Comment by joseph-henry** [comment]
Thanks for reporting this. Can you tell us a bit about your setup and anything that might allow us to replicate this?

**Comment by lideming** [comment]
Thanks for your quick reply.

I have a server with public IP that serves as ZT controller and moon. There are about 20 active clients connecting to the server. After continuously running for 2 weeks, the server reported duplicated paths for 2 clients. One client (the first one posted above) is running ZT 1.6.5 on Arch Linux while another client (the second one) is ZT 1.6.2 on Windows. Most clients are running ZT 1.4.6 ~ 1.6.5 on Windows, behind NAT.

And I just restarted the zerotier-one service on the server. Now every client have only one path.

**Comment by joseph-henry** [comment]
We've done some work on the path learning and I'd be very interested to know if you're still seeing this issue.

**Comment by lideming** [comment]
The issue seems to be resolved. Thanks.
