### ISSUE TITLE
Could not connect to the server

### ISSUE THREAD

**Issue by liaow** [zerotier/ZeroTierOne#1405]
- What you expect to be happening.
  Directly run app , join network
- What is actually happening?
  "Could not connect to the server",ask me "retry " or "quit"
- Any steps to reproduce the error.
  just run app
- Any screenshots that would help us out.
  no, 

## Additional information 

 - OS: Mac 11.4 (20F71)
 - ZeroTier Version 1.6.5

**Additional context**
- ZeroTier Network Configuration
  IPv4
- Router Config: are you permitting port 9993
  Default
- Firewall Config: are you permitting port 9993 on your OS
  Default
- Are you using this at home, in an office, college, etc?
  home, office both

**Comment by joseph-henry** [comment]
Thank you for reporting this. This error is probably because the background service is not running. Try restarting it:

```
sudo launchctl unload /Library/LaunchDaemons/com.zerotier.one.plist
sudo launchctl load /Library/LaunchDaemons/com.zerotier.one.plist
```

And then close the app and open it again.

Let me know if that doesn't fix it

**Comment by liaow** [comment]
> Thank you for reporting this. This error is probably because the background service is not running. Try restarting it:
> 
> ```
> sudo launchctl unload /Library/LaunchDaemons/com.zerotier.one.plist
> sudo launchctl load /Library/LaunchDaemons/com.zerotier.one.plist
> ```
> 
> And then close the app and open it again.
> 
> Let me know if that doesn't fix it

an error occurred when I performed unload and load command above

/Library/LaunchDaemons/com.zerotier.one.plist: Could not find specified service
Unload failed: 113: Could not find specified service

**Comment by liaow** [comment]
by the way,  I have install & uninstall and repeated it many times

**Comment by liaow** [comment]
it works!  think you

**Comment by liaow** [comment]
I think it's a bug caused by system compatibility

**Comment by joseph-henry** [comment]
Since you re-opened this ticket are you still having trouble?

**Comment by zkgi** [comment]
> At least, I'm indeed having this issue too. Every time I boot my M1 MacBook Air on macOS Big Sur 11.6, I get this pop-up.

you should open it in the Auto startup

**Comment by realrodri** [comment]
> > At least, I'm indeed having this issue too. Every time I boot my M1 MacBook Air on macOS Big Sur 11.6, I get this pop-up.
> 
> you should open it in the Auto startup 

Uhmm... I indeed open it in the Auto startup?
