### ISSUE TITLE
port_error:'unable to convert device interface GUID to LUID'

### ISSUE THREAD

**Issue by hengzhubao** [zerotier/ZeroTierOne#1409]
when I install one.msi, it requided administration twice. but no virtual adapter is installed.I tried to connected the vlan, the status is port_error,and the error log is "unable to convert device interface GUID to LUID". and when i restart the app, the node ID disappeared to unknown.

Windows, 10
 - OS/21H1
 - ZeroTier Version 1.6.5

**Comment by joseph-henry** [comment]
I don't think we've seen this issue yet. Thanks for reporting it. Is there any other networking software installed on the system that might create/destroy network interfaces?

**Comment by hengzhubao** [comment]
> I don't think we've seen this issue yet. Thanks for reporting it. Is there any other networking software installed on the system that might create/destroy network interfaces?
thanks for your reply. nope, I think I have not install any other networking software. I just install and uninstall zerotier for many times due to its unworking. I have restore the net configure  orderlin and in windows setup. nothing benefit had happened. besides, due to install and uninstall too many times, my wifi seems to generate black screen when I shut down the PC. I dont know what happend to my pc, I just install the zerotier.

**Comment by joseph-henry** [comment]
I'd try upgrading to `1.8.10` to see if that fixes the issue. I'm closing this ticket since we cannot replicate this and it has never been reported elsewhere. I strongly suspect there's something wrong with your Windows install.
