### ISSUE TITLE
Support copying of QoS fields from inside the network to external ZeroTier packets

### ISSUE THREAD

**Issue by adamierymenko** [zerotier/ZeroTierOne#141]
This is for the backlog, but this is an interesting feature idea thanks to a user who asked via LiveAgent. It would be optional, probably configurable on a per-network basis since it could have (very minor) security implications.

**Comment by heri16** [comment]
Tunnels like ip-in-ip and GRE already support this. They call it "inherit QoS".

**Comment by adamierymenko** [comment]
Question is whether there is *any* security consideration here that would *ever* merit making this an option vs. a default behavior that it just does all the time.

Is there a case where having QoS flags visible in plaintext would provide valuable information to an attacker?

My inclination based on what I know is to say no, with the reasoning being that QoS is *intended* to be globally visible to permit routing decisions to be made based on it.

**Comment by heri16** [comment]
I would also say no.

However, if someone sends VoIP packets over zerotier, it might make it trivial for an observer to realize he is doing so (other than using frequency/timing analysis). This makes that that zerotier network become a prime target for surveillance and wire-tapping. So I would say the security risk is minimal, but it is still there.

The great thing about zerotier is that it is difficult from the VL1 to monitor what zerotier is used for on the VL2, preventing selective traffic throttling by ISPs. 

On a side note, is it true that zerotier-one still has no packet obfuscation to pass sophisticated machine-learning firewalls?

From: https://github.com/shadowsocks/shadowsocks/issues/22
> Obfuscation means making a stream like a random bit stream (or some other kind of bit stream), so that the statistical property of your protocol may not be detected (or at least, hard to detect.) Mapping a byte statically to another one can preserve almost all statistical information of a bit stream. It is not an obfuscation. Some widely used obfuscation method (used in emule) may be: randomly send a packet with random bits; split a existing packet into two (i.e. call write then flush; and call write again.)
> If you have read this paper, you will see that you have to do a lot work to avoid being detected. Simply distribute any message from upper layer as a proxy may not be a good idea if you want to obfuscate your protocol. You have to put a lot own salt in the data and sacrifice much performance, if any.

**Comment by adamierymenko** [comment]
I"m not terribly concerned about that -- ZeroTier can be used for any kind of traffic and therefore can already be used for VoIP.

It could as you say allow an attacker to be "reasonably sure" VoIP traffic is present via VoIP-ish QoS fields but YOLO.

**Comment by adamierymenko** [comment]
Actually I know ZT already *is* used for VoIP quite a bit by some users. :)

**Comment by adamierymenko** [comment]
Closing since QoS is going to be done in a much more comprehensive way as part of the Edge project enhancements. We will natively support Qos.
