### ISSUE TITLE
Multipath and vlan subinterfaces?

### ISSUE THREAD

**Issue by dragon2611** [zerotier/ZeroTierOne#1412]
Does multipath ignore vlan sub interfaces, because I tried switching it on for 2 debian 10 machines one that uses sub interfaces and one that doesn't, the one that doesn't seemed to enable multipath (although one of the paths was failing as it was trying to use a wireguard tunnel).

The one that uses vlans wasn't didn't seem to want to show any available paths, it's like the bonding mode wasn't even switching on, I even tried copying the local.conf from the other machine.

the interfaces Zerotier seemed to refuse to consider as candidates were  enp1s0.7@enp1s0: and enp1s0.471@enp1s0, whilst they belong to the same physical interface on the host they egress to the internet via a different WAN.

There is a default route out of enp1s0.7 and a lower priority default route out of enp1s0.471.

The documentation also isn't overly clear if you are supposed to enable multipath on the peer with multiple connections or all of them.

This was with 1.65 but also a build compiled from  the dev-multipath branch in order to get the fix to the listbonds command.

**Comment by joseph-henry** [comment]
I don't think multipath is able to correctly handle sub-interfaces in its current state. But I am in the process of revamping how it curates its bonds and I think we can probably support this fairly easily. I'll see what I can do.

As for your other question about enabling for each peer: Currently you do need to have more than one "physical" link for multipath to auto-engage but I will be changing this soon. So, yes, but not for long.

Keep following `dev-multipath` and once I have something for you to test I'll update this ticket.

**Comment by dragon2611** [comment]
Ok, Will be interesting to try and see how the multipathing works, I was using a peplink device but I recently managed to get my hands on a starlink which has a higher peak throughput than the peplink can handle.

Just setup openmptcprouter in the meantime but the original plan had been to try zerotier multipathing between a VM at home and a VPS to quickly failback to the DSL without dropping sessions.

**Comment by farshield** [comment]
I'm also very interested in this feature. Currently looking to bond 2-3 low-bandwidth WAN interfaces from an edge device to 1 high-bandwidth WAN interface on a server.

**Comment by joseph-henry** [comment]
Sub-interface support is in the upcoming `1.8` release. For your use case @farshield I'd suggest using `balance-xor` to hash protocol flows across the two interfaces.

**Comment by farshield** [comment]
Great news, thank you. Once `1.8` is here, I will try using `balance-xor` as you suggested.

My use case involves having the edge router on a mobile platform, which means the signal strength (and bandwidth on my 3 WAN interfaces on the edge), will vary depending on the location. Do you still recommend using `balance-xor` for this 3-to-1 setup (where the server has 1 physical WAN interface and 2 sub-interfaces)?

**Comment by dragon2611** [comment]
Will Zerotier be able to handle Many to One multipathing?

Essentialy the peer with multiple WANs being able to Multipath to the single WAN of another Peer.

I'm thinking one peer being a server or somewhere with a single performant WAN and the other one being somewhere with 2-3 Less reliable connections (DSL,LTE.etc)

**Comment by joseph-henry** [comment]
The `dev` branch now supports Many to One multipathing and sub-interfaces works as well. These changes will make it into `1.8.6`. 

> My use case involves having the edge router on a mobile platform, which means the signal strength (and bandwidth on my WAN interfaces on the edge), will vary depending on the location. Do you still recommend using balance-xor for this 2-to-1 setup (where the edge has 2 physicai WAN interfaces and the server has 1 physical WAN + 1 sub-interface)?

Yes I'd use the `balance-xor` for this. Our `balance-aware` mode needs some work before it would be useful in this case.
