### ISSUE TITLE
Doesn't see host after rebooting the host

### ISSUE THREAD

**Issue by AmmarRashed** [zerotier/ZeroTierOne#1413]
Hello,
I could ssh a Linux machine on my network easily. But one time, I had to restart it, then when it booted, I tried to ssh to it again, but `no route to host`! Tried restarting the service, no luck. Restarting my computer, still no luck. So I opened my windows machine and added it to the network, and tried to ssh again, and it worked fine. Then had to restart the host again, and when I tried  to ssh to it (from windows this time), it faced the same problem, no route to host.
Any idea?

**Comment by joseph-henry** [comment]
Sounds like a routing problem with your OS or possibly a firewall is blocking something. We'll need to know the exact versions of ZT and your various OSes. We recommend you follow the github issue template that was provided.

Also, are you running any other network-related software that we should know about?

**Comment by AmmarRashed** [comment]
I tried with both Windows 10, and Ubuntu 18.04
Tried to disable the firewall, and it didn't help.
I did not install any network-related software on either of my systems.
The zerotier versions is 1.6.5 for both OSes. and 1.6.0 for the host.
I need to mention that my colleagues can still access the host from a different network, before and after the reboot without any issues.
Network configs:
Private
IPv4 Auto-assign from range 172.25.*.*
Broadcast enabled, Multicast Recipient Limit 32

**Comment by joseph-henry** [comment]
`1.6.0` has known connectivity issues. I would try with `1.6.5` before trying anything else. Let me know if that doesn't help.

**Comment by AmmarRashed** [comment]
So I travelled today to where the host is. Upgraded zerotier-one to 1.6.5 and restarted the service. Now it works! I can connect from both my ubuntu and windows machines just fine. Not sure if the version did it or the service restart.

If at some point I have to reboot the host and faced the same issue, I will comment again on this issue, but for now I think it is solved.
Thanks,

**Comment by joseph-henry** [comment]
Awesome, glad to hear!
