### ISSUE TITLE
IP address conflict resolution

### ISSUE THREAD

**Issue by adamierymenko** [zerotier/ZeroTierOne#142]
What happens if you're on network A and you join network B, which has a conflicting IP range? Current thought:

(1) The _newer_ network should be temporarily disabled with an error: IP conflict.

(2) It should offer an option to resolve this error by instituting local NAT to an IP range that does not conflict. This would be bidirectional static NAT, so it would not interfere with connectivity in either direction to/from other hosts on the network.

This is less of an issue with uses like cloud backplanes, etc. But one goal for this project is to be able to join networks and use them almost like chat rooms, and I could see this coming up there more often. Adding to backlog since I was reminded of this by a conversation with a customer.

**Comment by heri16** [comment]
Nice one.

**Comment by laduke** [comment]
On network create, Central is currently randomly choosing an ipv4 range from a small pool of ranges, so new networks Just Work. 

Maybe instead loop through like 10.0.0.0/29 -- 10.255.255.255/29? 

Not a solution, like 1) and 2) but reduces. 

Or somehow map from User Id to IP space?
