### ISSUE TITLE
Zero Tier Shows LAN IP, My computer is not accessible

### ISSUE THREAD

**Issue by alchemistake** [zerotier/ZeroTierOne#1431]
I have computer kind of acts like wifi repeater, has two wifi interfaces. Zerotier Shows the second local interface's IP when I look at the dashboard. Since this IP is local only I cannot access my devices unless I'm in the same LAN.

![image](https://user-images.githubusercontent.com/9083268/128306075-bc426717-42d7-4954-831a-0159c2f1d85c.png)

OS: MacOS X
Version 1.6.5

**Comment by laduke** [comment]
Sorry you're having trouble. There isn't enough info here to guess what is happening.

**Comment by alchemistake** [comment]
What else should I provide?
Will edit the post to have more clear english :)

**Comment by joseph-henry** [comment]
You can add the second wireless interface name to `interfacePrefixBlacklist` in your [local.conf](https://docs.zerotier.com/zerotier/zerotier.conf/) but I'm not sure how that would affect the rest of your setup.
