### ISSUE TITLE
[Feature Request] 黑群晖5.2

### ISSUE THREAD

**Issue by leehll** [zerotier/ZeroTierOne#1433]
黑群晖5.2  安装.zerotier_bromolow-6.1_1.4.0-0.spk版的zerotier 启动失败

**Comment by joseph-henry** [comment]
Hello.

What `model` of NAS do you have? and what `DSM version` are you using?

**Comment by leehll** [comment]
> Hello.
> 
> What `model` of NAS do you have? and what `DSM version` are you using?

我的是esix6.7虚拟机安装的DSM5.2 ,实体机也安装过了 两者都是无法启动

**Comment by joseph-henry** [comment]
`zerotier_bromolow-6.1_1.4.0-0.spk` is for `DSM 6.1`

`DSM 5.2` is not supported

Please try the Docker instructions here: [docs.zerotier.com/devices/synology](https://docs.zerotier.com/devices/synology)
