### ISSUE TITLE
Zerotier not connecting properly after windows wakes from sleep

### ISSUE THREAD

**Issue by m-wvj** [zerotier/ZeroTierOne#1434]
It seems my installation of ZeroTier does not like long lasting connection. It either drops after waking PC from sleep or after a long session (2hrs+ I presume, but no exact measurement)
It is not an issue with any particular software, as I checked it both through ssh in ubuntu for windows and in google chrome.
It just shows as ERR_CONNECTION_TIMED_OUT in case of web interfaces.

I do not have any idea on how to reproduce the error, as I barely understand its appearance myself. 
I am willing though to provide any logs/system info you would need to use. I also do not have a problem with running a monitoring script on my PC for data gathering purposes, though I would prefer if someone else wrote it :) 

## Additional information 

**Desktop:**
 - OS: WINDOWS 10
 - OS/Distribution:  Version	10.0.19042 Build 19042
 - ZeroTier Version1.6.5
  

**Additional context**
- ZeroTier Network Configuration: IPv4 & IPv6 networks defined on your ZeroTier Central: eeeee, dunno, but it works for some time at first
- Router Config: are you permitting port 9993, uPnP, and NAT-PMP? eeeee, dunno, but it works for some time at first
- Firewall Config: are you permitting port 9993 on your OS; setting it to "Private" on Windows? Yes
- Are you using this at home, in an office, college, etc? At home with my desktop PC, connected by ethernet cable to the internet. Connection is stable and system is rather fresh, with no mods or registry hacks. HW can be classified as modern, I built it a year ago from midrange new components.
- Have you tried screaming into your router? Yes, but it blinked at me angrily after that

**Comment by joseph-henry** [comment]
Are you still seeing this issue?

**Comment by nogard1210** [comment]
try to restart zerotier service from taskmgr, no need to restart PC
