### ISSUE TITLE
[Feature Request] Bring the portable version of Zerotier One

### ISSUE THREAD

**Issue by izmoxkawaii** [zerotier/ZeroTierOne#1438]
It will be a little easier if there is a portable version. There are users who do not want to deal with the installation especially!
especially I always browse portable programs. It would be great if zerotier had a portable version as well.
Using Zerotier without installation for different games or internet cafes..

**Comment by glimberg** [comment]
While it would be nice, it's not really possible to do what you're asking as it requires administrator access to install device drivers and configure network interfaces.  Both are required by ZeroTier.  So portable or not, you'd still need admin access to install it.

**Comment by izmoxkawaii** [comment]
:(
