### ISSUE TITLE
reopen Issue #1411 A Strange Connection Issue 

### ISSUE THREAD

**Issue by dfc643** [zerotier/ZeroTierOne#1439]
## ENVIRONMENT
I have three PCs with installed ZT1 software.
| PC | Short Name| WAN Network | LAN Network | OS | ZT1 Installed |
| ----- | ----- | ----- | ----- | ----- | ----- |
| Huawei Server | HWS | Huawei IDC BGP | LAN-1 | Debian 10 | 1.6.5 |
| Linux Server | LIN | China Mobile | LAN-2 | Debian 10 | 1.6.5 in Docker |
| Windows PC | WIN | China Mobile | LAN-2 | Windows 11 Dev | 1.4.6 |

| PC | Short Name| NAT Type | Public IPv4 | Public IPv6 | Ports Open on Router |
| ----- | ----- | ----- | ----- | ----- | ----- |
| Huawei Server | HWS | Symmetric | Yes | No | TCP/UDP 9993 for IPv4 |
| Linux Server | LIN | Fullcone | No | Yes | All for IPv6<br/>UDP 48823 for IPv4 |
| Windows PC | WIN |  Fullcone | No | Yes | All for IPv6<br/>UDP 53270 for IPv4 |

## TOPOLOGICAL
<img src="https://i.loli.net/2021/06/10/RDcbfTAjWkiLBev.png" width="400px"/>

### Before Someday ❤️ 
| Connection  (A <--> B) | Latency | Speed | Peer A to Peer B | Peer B to Peer A |
| ----- | ----- | ----- | ----- | ----- |
| LIN <--> HWS | < 100ms | Good | DIRECT | DIRECT |
| WIN <--> HWS | < 100ms | Good | DIRECT | DIRECT |
### After Someday 🙉 
All the environment keeps no change, But the stranger connection issue was happend.
| Connection  (A <--> B) | Latency | Speed | Peer A to Peer B | Peer B to Peer A |
| ----- | ----- | ----- | ----- | ----- |
| LIN <--> HWS | > 300ms | Bad | DIRECT | RELAY |
| WIN <--> HWS | < 100ms | Good | DIRECT | DIRECT |

## AHAaaa ...
I dont think the issue is related to the network environment🤔  due to eveything works fine before someday🤕 
what cause it.. ❓😄 

## Reopen Issue #1411 
i reinstalled zerotier-one from docker to the host, but the issue still alive.    
only reboot Debian Linux can resolve it temporay, but the issue will appears again in someday.

**Comment by joseph-henry** [comment]
Nothing changed on our end so it must be the network environment. I'd suggest upgrading that Windows PC to 1.6.5 though. If that doesn't help we can look at other possible causes.

**Comment by dfc643** [comment]
@joseph-henry thank you.

i found the issue was **caused by pppoe session re-dialed**.
China ISPs will force drop pppoe session every 3-5 days for home users but not for commercial users.

so there was no interference for huawei server (HWS) but only for home server (LIN).
no interfence for Windows PC due to it will restart everyday.

i found a way, and tested it works:
1. stop zerotier with ```systemctl stop zerotier-one ```
2. reset debian network ```systemctl restart networking```
3. waitting 3 mins for connection timeout in ISP side.
4. start zerotier again with ```systemctl start zerotier-one```

if you restart zerotier-one immediately, the zerotier connection will still broken!!
due to wrong route in ISP side routers.

hope zerotier-one add a method to detect connection broken,
and close old connection then restart new connection after X min(s).

**Comment by joseph-henry** [comment]
There's a potential fix for this that will be present in 1.8.6 (it's already in `dev`). Let me know if this issue pops up again for you.
