### ISSUE TITLE
Use sendmmsg/recvmmsg on Linux

### ISSUE THREAD

**Issue by adamierymenko** [zerotier/ZeroTierOne#144]
Using sendmmsg/recvmmsg to send and receive multiple UDP messages with a single system call would improve Linux performance under high traffic conditions.

This is also worth reading: https://lwn.net/Articles/629155/

**Comment by adamierymenko** [comment]
Also http://bert-hubert.blogspot.com/2015/02/some-notes-on-sendmsg.html

**Comment by alandekok** [comment]
recvmmsg() doesn't really work.  It has a timeout, but setting both a packet limit and a timeout, doesn't really work.  If it receives less than "limit" packets, it will never return... even after the timeout expires.

**Comment by adamierymenko** [comment]
Well gee, that's good to know. Is this true even in non-blocking operation? If so scratch that.

**Comment by adamierymenko** [comment]
Makes it kind of worthless really.

**Comment by alandekok** [comment]
recvmmsg() isn't really non-blocking.  If you tell it to receive N packets and no timeout, it blocks until it receives N packets.  If you tell it to receive N packets with a timeout (even N=1), and it receives less than N packets, it never returns.

And yes, this makes recvmmsg() pretty much worthless.

**Comment by adamierymenko** [comment]
Thanks for the tip. :sob:

**Comment by seemk** [comment]
So I somehow stumbled upon this issue through Google. recvmmsg can be made nonblocking by supplying the MSG_DONTWAIT flag and setting the timeout to NULL. When asking recvmmsg to retrieve you 20 packets and there is one available, it will just read this one packet into your buffers.

**Comment by adamierymenko** [comment]
Thanks... might reopen then. Could improve performance by reducing sys call load.

**Comment by alandekok** [comment]
The only caveat here is that you have to manage the timeouts yourself.  i.e. wait time T, then call recvmmsg() to get any packets.  From my tests, it's not substantially better than recvmsg().

**Comment by adamierymenko** [comment]
Closing since if we really really want high performance on Linux the best thing to do would be to bind RAW and compose UDP packets to send directly to the underlying hardware.

I did add one speed optimization: it now turns off UDP checksums on Linux. Linux lets you do this, and they're not needed since we do our own cryptographic authentication which is far better anyway.
