### ISSUE TITLE
TCP P2P

### ISSUE THREAD

**Issue by yaott2020-666** [zerotier/ZeroTierOne#1448]
Thanks to the developers for the high-quality open source software. Secondly, I put forward my requirement: TCP-based P2P penetration function. This function is very useful for operators to QOS for UDP. The xtcp in the open source project frp realizes this function. The effect is good. Although the delay is higher than that of UDP, the speed is not affected by QOS. I hope developers can adopt my opinion, thanks!

**Comment by glimberg** [comment]
Using TCP instead of UDP is not likely to ever happen. See [here](http://sites.inka.de/bigred/devel/tcp-tcp.html) for details why

**Comment by daifeilail** [comment]
A Tunnel which turns UDP Traffic into Encrypted FakeTCP/UDP/ICMP Traffic by using Raw Socket, helps you Bypass UDP FireWalls(or Unstable UDP Environment).

https://github.com/wangyu-/udp2raw-tunnel

**Comment by erikh** [comment]
Locking this topic until we're ready to reopen this subject.
