### ISSUE TITLE
Connection to Earth exposes open ports on Windows

### ISSUE THREAD

**Issue by rebroad** [zerotier/ZeroTierOne#1449]
Following on from #1444, although earth may have been removed from the documentation, there still exists plenty of websites referring to it, and so users may still try connecting to it.

As it currently is, Windows 10 and 11 do not by default offer to route traffic through the default Windows firewall and so all open ports are exposed to the interface created. This is a a security issue.

If Earth has been removed from the docs, does this mean that the plan is to decommission the earth network? Please can someone provide some clarity on this, and if github is not the place to ask for this clarity - where is please?

**Comment by glimberg** [comment]
The solution to your problem is to create your own network and not use the earth network.
