### ISSUE TITLE
install Zerotier 1.6.5  on debian11

### ISSUE THREAD

**Issue by Fr33raNg3r** [zerotier/ZeroTierOne#1452]
When I installed zerotier to debian11 according to the following URL, an error occurred.
https://discuss.zerotier.com/t/install-zerotier-on-debian-11-just-released-failed/3901
![image](https://user-images.githubusercontent.com/15374658/134349490-af30ad88-8033-48ba-8470-4aabeb56c34a.png)

**Comment by laduke** [comment]
Hello. It looks like it's installed. But blocked in one way or another from talking to other zerotier nodes.

**Comment by tmsi-io** [comment]
check nodes config in my.zerotier.com website
