### ISSUE TITLE
会消耗moon节点的流量和带宽吗？

### ISSUE THREAD

**Issue by Y-pandaman** [zerotier/ZeroTierOne#1453]
原谅我使用中文进行询问~（英文很烂）
您好，我在中国的阿里云服务器上搭建了moon节点（没有IPv6），身边的几台电脑（Ubuntu系统）都连上了moon节点，以实现局域网的效果，然后我测试了ROS，SCP传输文件，RTSP传输视频，网络分别是研究所的不同wifi（IP不是同一个网段),以及华为的5G网络（默认有IPv6和IPv4）和手机的4G热点，经过测试，如果电脑连的都是研究所内的wifi，ROS，SCP和RTSP都不消耗服务器的流量和带宽，但是如果其中一台电脑切换成5G网络和手机的热点，就会发现测试ROS,SCP，RTSP，服务器的带宽都会被占用，而且会消耗服务器的流量。我猜测连接研究所内的wifi不消耗服务器的流量，是因为整个研究所内的wifi最终都会汇集到同一个路由器上。我咨询过其他使用zerotier的人，他们说moon节点不负责转发，但是我测试后出现了这种情况，请问这正常吗？我不清楚这是否跟IPv6有关系，期待有人能解答一下，谢谢！

**Comment by Y-pandaman** [comment]
> p2p成功moon只负责信令交互，p2p隧道没成功，流量会中转

那有什么办法可以检测p2p是否成功呢？

**Comment by Y-pandaman** [comment]
> > > p2p成功moon只负责信令交互，p2p隧道没成功，流量会中转
> > 
> > 
> > 那有什么办法可以检测p2p是否成功呢？
> 
> 可以直接看下ping或zerotier-cli listpeers里面的延迟，或者抓包，其他的方法还没关注过 : (

好的，谢谢，ping的结果延迟都很小

**Comment by tmsi-io** [comment]
> > > > p2p成功moon只负责信令交互，p2p隧道没成功，流量会中转
> > > 
> > > 
> > > 那有什么办法可以检测p2p是否成功呢？
> > 
> > 
> > 可以直接看下ping或zerotier-cli listpeers里面的延迟，或者抓包，其他的方法还没关注过 : (
> 
> 好的，谢谢，ping的结果延迟都很小

ping对端是否和ping moon节点的延迟一样就知道了

**Comment by sagcan** [comment]
我建的moon都不能获取到ip，怎么回事呢？

**Comment by yaott2020-666** [comment]
打开端口9993

**Comment by Y-pandaman** [comment]
显示都是DIRECT，相互ping的延迟在50ms左右，会消耗阿里云服务器的流量，

**Comment by Y-pandaman** [comment]
ping 对端延迟50ms，ping moon延迟10ms左右

**Comment by Y-pandaman** [comment]
我查到一个原因，我检查了我的NAT类型，显示是对称式的，换了另一种端口限制圆锥型的网络，延迟明显降低了，有人推荐说是完全圆锥型NAT最好，但是我现在达不到这种网络条件

**Comment by rjkc** [comment]
> 我建的moon都不能获取到ip，怎么回事呢？
UDP 9993 端口外部能不能访问？
