### ISSUE TITLE
how to connect to the moon that i created on aliyun

### ISSUE THREAD

**Issue by angussleeping** [zerotier/ZeroTierOne#1462]
I have alread created a moon on aliyun vps,running zerotier in docker on synology,when i connect to synology with ssh,i cannot use zerotier command,it shows "-ash: *:command not found"

how can i make my synology connect to my moon

 **Embedded & NAS (please complete the following information):**
 - Device: Synology, 
 - OS/Distribution (if applicable)
 - ZeroTier Version：1.6.5（docker）

**Comment by laduke** [comment]
It's `zerotier-cli orbit $moonid $moonid` and you probably need to be root or use sudo.

**Comment by THWJ** [comment]
if you install zerotier by docker, you can't use the command direct in synology, you shout use docker command
