### ISSUE TITLE
[Feature Request] Running zerotier-cli in the Linux network namespace

### ISSUE THREAD

**Issue by ic2hrmk** [zerotier/ZeroTierOne#1463]
Hello folks!

I am looking for a way to run the ZeroTier client (in my case _zerotier-cli on Linux_) in the network namespace.

I want to achieve is to make sure that there is no network address overlap between ZeroTier's network & the network in which the device is:
![Untitled Diagram](https://user-images.githubusercontent.com/11685484/137609132-f435023c-3b5c-4849-8dcb-9fddfaade35b.png)

I tried the setup proposed here: [https://gist.github.com/maxux/7829d92896eacb31887695c497083f4b](https://gist.github.com/maxux/7829d92896eacb31887695c497083f4b)

I am receiving the error while executing `sudo zeroclient-cli listnetworks` inside the namespace:
~~~
root@ubuntu:/home/ubuntu# zerotier-cli listnetworks
Error connecting to the ZeroTier service: connection failed

Please check that the service is running and that TCP port 9993 can be contacted via 127.0.0.1.
~~~

But I can see that the interface is inside the network namespace:
~~~
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: veth1@if11: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 02:61:1c:0b:a2:45 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.16.0.1/24 scope global veth1
       valid_lft forever preferred_lft forever
    inet6 fe80::61:1cff:fe0b:a245/64 scope link 
       valid_lft forever preferred_lft forever
12: ztbtotpcyp: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 1000
    link/ether 0e:93:45:64:2c:43 brd ff:ff:ff:ff:ff:ff
    inet 10.243.122.177/16 scope global ztbtotpcyp
       valid_lft forever preferred_lft forever
    inet6 fe80::c93:45ff:fe64:2c43/64 scope link 
       valid_lft forever preferred_lft forever
~~~

Please, point me if there is already an existing solution exists.

Thank you!

**Comment by laduke** [comment]
I've done it, but don't have any scripts handy. Maybe someone else will. It's kind of a pain to mange namespaces. 

You might need to do `sudo zeroclient-cli -D/tmp/zerotier-home-$nsname listnetworks` If I'm reading the gist right. 

Also check out the macvlan style: https://developers.redhat.com/blog/2018/10/22/introduction-to-linux-interfaces-for-virtual-networking#macvlan.

**Comment by ic2hrmk** [comment]
@laduke, I see, that's a good point I missed!

@erikh, Thank you for the suggestion. I do only network isolation, no other namespaces (like a filesystem, etc) are involved. A different question here: in case, when I ran the ZeroTier daemon inside the network namespace, is it required to have the additional DNS configurations for the daemon for the proper functioning? In my case, I don't need any kind of DNS, it's only direct communication by IPv4.

I mean, inside the namespace there is no name resolution is available by default (as per https://man7.org/linux/man-pages/man8/ip-netns.8.html), and it's required to create a `resolv.conf` on a per-namespace basis.
