### ISSUE TITLE
DNS AAAA lookups do not work if MacOS has no public IPv6 address.

### ISSUE THREAD

**Issue by andrewgdotcom** [zerotier/ZeroTierOne#1466]
When connected to a Zerotier network with managed DNS, AAAA records are not always returned. This means that zerotier networks with no IPv4 addresses are at best unreliable (and often unusable).

Steps to reproduce:

* Create an IPv6-only network in zerotier central
* Join a DNS server to this network
* Join a target server to the network and ensure its zerotier IPv6 address is served by the DNS server (the target server may or may not be the same machine as the DNS server)
* Add the DNS server IPv6 address to the list of DNS servers and configure the search domain so that the target server's name is resolvable
* Join a Mac client to this network and enable DNS on the Mac
* Try to connect from the Mac client to the target server via its DNS record

The IPv6 network will route properly, and ping6 works using the DNS name, but every other client (ssh, web browser) will throw a DNS resolution error:

```
andrewg@serenity ~ % ping6 XXXXXXXX
PING6(56=40+8+8 bytes) fcXXXXXXXX::1 --> fcXXXXXXXX::1
16 bytes from fcXXXXXXXX::1, icmp_seq=0 hlim=64 time=60.786 ms
16 bytes from fcXXXXXXXX::1, icmp_seq=1 hlim=64 time=45.236 ms
^C
--- XXXXXXXX ping6 statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip min/avg/max/std-dev = 45.236/53.011/60.786/7.775 ms
andrewg@serenity ~ % ssh XXXXXXXX
ssh: Could not resolve hostname XXXXXXXX: nodename nor servname provided, or not known
andrewg@serenity ~ % ssh -6 XXXXXXXX
ssh: connect to host XXXXXXXX port 22: Undefined error: 0
andrewg@serenity ~ % ssh fcXXXXXXXX::1
The authenticity of host 'fcXXXXXXXX::1 (fcXXXXXXXX::1)' can't be established.
ECDSA key fingerprint is SHA256:CUh8Vnlf235ob9Ry4XT3IzpP5V9mc3OWSz80Ibx9v8I.
Are you sure you want to continue connecting (yes/no/[fingerprint])?
```

If you run `scutil --dns` it shows that only A record requests are enabled, even via the DNS server on the IPv6 zerotier network:

```
andrewg@serenity ~ % scutil --dns
DNS configuration

resolver #1
  search domain[0] : XXXXXX
  search domain[1] : XXXXXX
  nameserver[0] : 192.168.1.1
  if_index : 7 (en6)
  flags    : Request A records
  reach    : 0x00020002 (Reachable,Directly Reachable Address)

resolver #2
  domain   : XXXXXX
  nameserver[0] : fcXXXXXXXXX::1
  nameserver[1] : fcXXXXXXXXX::1
  flags    : Supplemental, Request A records
  reach    : 0x00020002 (Reachable,Directly Reachable Address)
  order    : 103000

resolver #3
  domain   : local
  options  : mdns
  timeout  : 5
  flags    : Request A records
  reach    : 0x00000000 (Not Reachable)
  order    : 300000
```

`dig` etc. can be forced to look up the AAAA address:

```
andrewg@serenity ~ % dig XXXXXXXX any @fcXXXXXXXX::1

; <<>> DiG 9.10.6 <<>> XXXXXXXX any @fcXXXXXXXX::1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 50304
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;XXXXXXXX.		IN	ANY

;; ANSWER SECTION:
XXXXXXXX.	529	IN	AAAA	fcXXXXXXXX::1

```

A fuller discussion can be found at https://apple.stackexchange.com/questions/309430/ipv6-dns-resolution-on-macos-high-sierra:

----

macOS's domain name resolver will only return IPv6 addresses (from AAAA records) when it thinks that you have a valid routable IPv6 address. For physical interfaces like Ethernet or Wi-Fi it's enough to set or be assigned an IPv6 address, but for tunnels (such as those using utun interfaces) there are some extra annoying steps that need to be taken to convince the system that yes, you indeed have an IPv6 address, and yes, you'd like to get IPv6 addresses back for DNS lookups.

...

Why can ping6 do this when nothing else can? It turns out that when ping6 calls getaddrinfo it overwrites the default flags. One of the default flags is AI_ADDRCONFIG, which tells the resolver to only return addresses in address families that the system has an IP address for. (That is, don't return IPv6 addresses unless the system has a (not link-local) IPv6 address.) Most other programs add to the default flags rather than clobbering them, which I suppose is sensible.

...

The "right" way for this to happen is for whatever program sets up the tunnel to use the bizarre and largely undocumented SystemConfiguration API to register the network "service" and its IPv6 properties. The Viscosity app does this. Tunnelblick does not, the official OpenVPN Client does not, and wg-quick sure as hell doesn't.

----

It appears from the above that zerotier 1.6.6 does not either.

**Comment by laduke** [comment]
Hey @andrewgdotcom if you're interested in compiling zerotier, I've been running this branch/PR for a while. Seems to work.
