### ISSUE TITLE
Compile problem with TRACE enabled (ZT_TRACE)

### ISSUE THREAD

**Issue by paulrd** [zerotier/ZeroTierOne#147]
I'm trying to compile the dev branch with ZT_TRACE enabled. I get the following error:

In file included from node/Network.cpp:34:0:
node/Network.hpp: In static member function ‘static void ZeroTier::Network::_CBhandleTapData(void*, const ZeroTier::MAC&, const ZeroTier::MAC&, unsigned int, const ZeroTier::Buffer<4096u>&)’:
node/Network.hpp:473:28: error: invalid use of member ‘ZeroTier::Network::RR’ in static member function
  const RuntimeEnvironment *RR;

I noticed you commented out line 51 (DEFS+=-DZT_TRACE -DZT_LOG_STDOUT) in make-linux.mk for the 'make debug' task.

Was it because of this compile bug?

**Comment by adamierymenko** [comment]
Hmm... that looks an awful lot like I haven't enabled TRACE in a little while, which is true. Maybe just comment out that line.

**Comment by adamierymenko** [comment]
Fixed in -dev
