### ISSUE TITLE
ZeroTier 1.8.1 armhf build is missing

### ISSUE THREAD

**Issue by wendelb** [zerotier/ZeroTierOne#1470]
Hi there,

I'm running zerotier on a Raspberry Pi. For the newest release 1.8.1 the binaries for the `armhf` platform seem to be missing. See: http://download.zerotier.com/debian/bullseye/pool/main/z/zerotier-one/

There are `arm64` builds, but those cannot be installed on the RasPi.

Is `armhf` still supported?

**Comment by graphixillusion** [comment]
I've exact the same problem: my RasPi4 cannot see the update 1.8.1 ad the last updated version is 1.6.6.

**Comment by graphixillusion** [comment]
armhf build showed up. Updated successfully on my RasPi4

**Comment by asparatu** [comment]
I was able to update to 1.8.1 on my raspberry pi. 
![image](https://user-images.githubusercontent.com/3848896/139568251-412915a8-f9f2-4fbf-b800-25b5fcfa57c4.png)

**Comment by laduke** [comment]
all set @wendelb ?

**Comment by wendelb** [comment]
All set, thanks for fixing
