### ISSUE TITLE
Misleading tdiff rule example in the docs

### ISSUE THREAD

**Issue by dhbaird** [zerotier/ZeroTierOne#1471]
In the docs here https://docs.zerotier.com/zerotier/rules/ (old location: https://docs.zerotier.com/zerotier/manual/#3_4_1), the following example should probably be written with `txor` rather than `tdiff`:

```
# Allow Windows CIFS and netbios between computers in the same department using a tag
accept
  dport 139 or dport 445
  and ipprotocol tcp
  and tdiff department 0  # difference between department tags is 0, meaning they match
;
```

From the docs:
```
tdiff	<id> <value>	Difference between tags with this ID is less than or equal to the value.
txor	<id> <value>	Tags XORed together equal value.
```

This rule also appears in another issue here, but for a different reason: https://github.com/zerotier/ZeroTierOne/issues/1060

Thanks!

**Comment by laduke** [comment]
Hah! Hadn't thought of negative results. I'm not sure the result is be signed or not. Will check. 
The packets won't make it back the other direction in any case. 

But now maybe txor takes a slight lead IMO.

**Comment by dhbaird** [comment]
Uh oh, if tdiff results aren't signed, that makes things even more interesting, but for another case :)  Because how I would actually use tdiff is to see if a "higher level service" is allowed to talk to a "lower level service" by subtracting their "levelnumber" (a tag) and this would necessarily depend on signed results (I think?). For example, in a three-layer architecture, the UI tier (level 3) can communicate to the services tier (level 2) which can communicate to the database tier (level 1). But never in the other direction.

**Comment by laduke** [comment]
OK. tdiff is absolute value. https://github.com/zerotier/ZeroTierOne/blob/7a626abf156a9dbac45a14061e5e1a182083a61c/node/Network.cpp#L436  will add a note about that. 

I can't think offhand how to that kind of tiered system. It'd be TCP only. Can't do directions with UDP. 

There's the similar [classified system pattern](https://docs.zerotier.com/zerotier/rules/#354theclassifiedsystempatternaname3_5_4a)

**Comment by dhbaird** [comment]
Ah, so the docs probably could be improved by indicating the difference does an absolute value. And with that, I agree that whether `tdiff` or `txor`, both cases should work identically.

As for the tiered system the only way I can think of to do it is with a rule-per-tier-crossing, maybe something like this,
```
accept tseq tier ui treq tier svc;
accept tseq tier svc treq tier db;
drop chr tcp_syn and not chr tcp_ack;
accept not chr tcp_syn;
drop;
```

**Comment by laduke** [comment]
Added a small note about the absolute value.
