### ISSUE TITLE
Bonding works in 1.6.6 but not 1.8.1

### ISSUE THREAD

**Issue by dhbaird** [zerotier/ZeroTierOne#1473]
ZeroTier 1.8.1: Trying to ping other IPv6 hosts, but nothing gets sent and nothing gets received. NDP solications go unanswered. If I disable bonding, then 1.8.1 works as expected.

ZeroTier 1.6.6: Ping, and other operations, work fine with bonding enabled.

OS: Linux

Bonding configuration:
```
cat /var/lib/zerotier-one/local.conf 
# >>>
{
  "settings": {
    "defaultBondingPolicy": "myPolicy",
    "policies": {
      "myPolicy": {
        "basePolicy": "balance-aware",
        "links": {
          "eth0": {},
          "eth1": {}
        }
      }
    }
  }
}
```

Thanks!

**Comment by dhbaird** [comment]
Update: this issue might exist even in 1.6.6. I had 1.6.6 nodes seemingly communicated okay with bonding, but experienced an issue this way where they stopped, and eventually I tried disabling bonding which resolved the issue and let the nodes start communicating again. I don't have any better information to offer than that though, other than it might not be a 1.8.1 issue afterall.

**Comment by joseph-henry** [comment]
Thanks for the additional details. Seems like a bug in how the policies are parsed and configured. Working on a fix now and it should land in one of our next releases. I'll update this thread once I have it ready.

**Comment by dhbaird** [comment]
Hey there, was just curious if there is an eta on a fix release for this. No pressure if not, just to help with planning on my side of things. Thanks!
