### ISSUE TITLE
avahi-daemon will not advertise on ZeroTier interfaces with zerotier-one 1.8.1

### ISSUE THREAD

**Issue by jamesfmilne** [zerotier/ZeroTierOne#1477]
- What you expect to be happening.

Avahi should advertise services on the ZeroTier network interface(s).

- What is actually happening?

Avahi is ignoring the ZeroTier network interfaces.

- Any steps to reproduce the error.

Install ZeroTier 1.8.1
Restart avahi-daemon `sudo systemctl restart avahi-daemon`
Check `sudo journalctl -u avahi-daemon` output to see if it is enumerating the ZeroTIer network interfaces.

- Any screenshots that would help us out.

This is what I see in the avahi-daemon output when running ZeroTier 1.6.4:

Nov 02 11:11:32 hpz2 avahi-daemon[46730]: Joining mDNS multicast group on interface zt7xxxxxxx.IPv6 with address fd35:xxxx: xxxx: xxxx: xxxx: xxxx: xxxx: xxxx.
Nov 02 11:11:32 hpz2 avahi-daemon[46730]: New relevant interface zt7xxxxxxx.IPv6 for mDNS.
Nov 02 11:11:32 hpz2 avahi-daemon[46730]: Joining mDNS multicast group on interface zt7xxxxxxx.IPv4 with address 192.168.193.91.
Nov 02 11:11:32 hpz2 avahi-daemon[46730]: New relevant interface zt7xxxxxxx.IPv4 for mDNS.

These lines are missing when running ZeroTier 1.8.1, and the mDNS services are therefore not advertised over the ZeroTier network.

## Additional information 

**Desktop (please complete the following information):**
OS: Linux
Distribution: CentOS 8.4
ZeroTier: 1.8.1
 
**Additional context**

**Comment by pkpowell** [comment]
This also seems to be the case with synology/docker installs. Connectivity is there but the zerotier addresses aren't published to bonjour.

**Comment by laduke** [comment]
thanks for reporting this.

**Comment by hadrianw** [comment]
Workaround for the time being:

`sudo ifconfig ztyxaw5gxg multicast`

**Comment by adamierymenko** [comment]
Multicast bug fixed in 1.8.2, shipping later today.

**Comment by jamesfmilne** [comment]
Thanks Adam!
