### ISSUE TITLE
ZeroTier One may conflict with ifplugd (Raspbian)

### ISSUE THREAD

**Issue by CTassisF** [zerotier/ZeroTierOne#148]
Hello.

I don't know why ZeroTier One daemon isn't starting automatically after boot on my new Raspbian Wheezy instalation (version "January 2015" that I downloaded yesterday from http://www.raspberrypi.org/downloads/).
Is there any way to debug why this is happening?
I installed ZT using the regular way, not packages.

Thanks in advance.

**Comment by CTassisF** [comment]
Oh, just uninstalled ifplugd and now ZeroTier One works fine after boot (it came pre-installed with this latest Raspbian image release).
I'll leave this ticket open in case you wanna check why ifplugd was conflicting with ZeroTier One.

**Comment by adamierymenko** [comment]
Can confirm that this is the case. The ifplugd daemon seems to absolutely freak out when 'tun' comes up and kill every other interface in the machine. Seems worse than NetworkMangler. :P

**Comment by adamierymenko** [comment]
Yeah, fix is:

    sudo dpkg --purge ifplugd

All the interfaces continue to work.
