### ISSUE TITLE
Zerotier in opnsense does not use upnp to open ports

### ISSUE THREAD

**Issue by mgiammarco** [zerotier/ZeroTierOne#1481]
- What you expect to be happening.

I have an opnsense 21.7.4. I install zerotier. The opnsense is connected to internet using a router with upnp enabled.
I expect zerotier to open a port using upnp so I can have a DIRECT connection.

(the upnp router is correctly configured if I try with linux or windows opnsense I see the upnp rule immediately added)
- What is actually happening?

Zerotier in opnsense does not use upnp so I get a RELAYED connection.

- Any steps to reproduce the error.

Install zerotier in an opnsense under a upnp firewall

- Any screenshots that would help us out.

 **Embedded & NAS (please complete the following information):**
 - Device: OpnSense 21.7.4
 - OS/Distribution opnsense
 - ZeroTier Version 1.6.6

**Comment by laduke** [comment]
Hello. Thanks for writing. ZeroTier doesn't actually maintain that package. I think it's here https://github.com/opnsense/plugins/tree/master/net/zerotier
