### ISSUE TITLE
Installation bug for Windows MSI 1.8.1

### ISSUE THREAD

**Issue by stevo11811** [zerotier/ZeroTierOne#1483]
- What you expect to be happening.
Path Variable containing "C:\Program Files (x86)\Zerotier\One"
- What is actually happening?
Path Variable is removed on upgrade, and not added for fresh installs.
- Any steps to reproduce the error.
Install version 1.8.1 on Windows 10.

This makes zerotier-cli not function.

Windows versions tested - 10, 20h2 and 21h1.
Testing performed, Clean installation
Upgrade from previous 1.6.5 and 1.6.6.

You can work around this by directly calling C:\Program Files(x86)\ZeroTier\One\zerotier-cli.bat

**Comment by adamierymenko** [comment]
We figured this one out, should be fixed in 1.8.2.
