### ISSUE TITLE
v1.8.1 will not compile on Ubuntu Server 20.04.3 - arm64

### ISSUE THREAD

**Issue by knightian** [zerotier/ZeroTierOne#1484]
## Required

- The code to compile
- The code does not compile for v1.8.1. It compiles fine for v1.6.6
- I `git checkout 1.8.1` and type `make`
- Any screenshots that would help us out.

<img width="978" alt="Screen Shot 2021-11-07 at 5 09 29 pm" src="https://user-images.githubusercontent.com/72685601/140634434-79b21de4-c4b0-4835-bf3e-47b02ce9f70a.png">

## Additional information 

**Desktop (please complete the following information):**
 - OS: Linux
 - Ubuntu Server 20.04.3 - arm64
 - ZeroTier Version git tag 1.8.1
  

**Additional context**
- It is probably noteworthy that I am compiling on arm64 architecture
- Also noteworthy is that v1.6.6 compiles just fine without issue.

**Comment by knightian** [comment]
I deleted the repo and re-cloned, then it worked. I guess it was trying to link to some old version libs or something???

Anyway clone a fresh repo fixed so will close the issue.

**Comment by laduke** [comment]
`make clean` first may have worked too 👍
