### ISSUE TITLE
regression issue with 1.8.1-1.fc35

### ISSUE THREAD

**Issue by harishpillay** [zerotier/ZeroTierOne#1486]
Just updated a working zt setup on a Fedora 35 system 
Ran a dnf update on a zt-enabled Fedora 35 system. Noticed that there is a new zerotier-one rpm that was installed. After that installation, the F35 system could not connect to any of the other systems that it was previously connecting to. 

The systems that it was connecting to (F35s, CentOS Stream 8s, RHEL 8.4s) are running 1.8.1-1.el7 and the newly updated F35 1.8.1-1.fc35. The latter version has regression. I am not updating the other systems for the time being.

**Comment by laduke** [comment]
Thanks for reporting. Do you still have access to the system with zerotier in the broken state?

**Comment by harishpillay** [comment]
yes, i do have access to it.

**Comment by laduke** [comment]
Is the MAC address correct on the zerotier interface? Just a wild guess. 

If you want, you can run `zerotier-cli dump` to collect the system state. Then leave and rejoin the network and see if it works.

**Comment by harishpillay** [comment]
did the following:
```
# zerotier-cli dump 
# zerotier-cli leave <networkid>
# zerotier-cli join <networkid>
```

By leaving and rejoining, it is now working with the same version of the zerotier-one rpm 1.8.1-1.fc35.

I will close this comment.
