### ISSUE TITLE
Windows "zerotier-cli" Path

### ISSUE THREAD

**Issue by igloodan** [zerotier/ZeroTierOne#1490]
As reported in the [community forum](https://discuss.zerotier.com/t/zerotier-1-8-1-is-now-available/4654/3), version 1.8.1 is not adding the zerotier-cli (or directory) to the path in Windows 10. 
Simply using `zerotier-cli` in `cmd` gives an error without first being in the `C:\Program Files (x86)\ZeroTier\One` directory.

**Comment by glimberg** [comment]
1.8.2 was recently released and resolves this issue.  You can grab it from the [download page](https://www.zerotier.com/download)
