### ISSUE TITLE
Set user specified mac address

### ISSUE THREAD

**Issue by jpathy** [zerotier/ZeroTierOne#1491]
## Required

- What you expect to be happening.
  Connect to zerotier
- What is actually happening?
  Stuck in `REQUESTING_CONFIGURATION`
- Any steps to reproduce the error.
  Same mac address for 2 machines in network.
- Any screenshots that would help us out.

## Additional information 
I am using macvlan in a container which can send outgoing udp/tcp(tailscale worked perfectly fine). But zerotier is not working since i am sharing the macaddress with the host. Is there any way for me to change the address on the interface using the cli?

**Desktop (please complete the following information):**
 - OS: [e.g. Mac, Linux, Windows, BSD] Linux 5.11
 - OS/Distribution Version Ubuntu
 - ZeroTier Version : 1.8.2

**Comment by laduke** [comment]
Hello,
The MAC addresses are calculated based on the network and node id.

I'm not sure this is the issue. If you're stuck on requesting config, zerotier can't talk to the network controller. This happens at a layer below setting up the interfaces for zerotier networks. 

Actually what do you mean by: 
> i am sharing the macaddress with the host

**Comment by jpathy** [comment]
I have machine `A` joined to zerotier network. `A` has a lxc container `B` which uses [ipvlan l3s](https://www.kernel.org/doc/html/v5.12/networking/ipvlan.html#l3s-mode)(i previously miswrote it for macvlan). 

The host(`A`) allows(iptables) all traffic in/out to `B`. The interface address and name is same on both `A` and `B`(since they are derived from the same interface). `B` can't join zerotier.

**Comment by jpathy** [comment]
Never mind, it now shows up on zerotier central and i have joined it to the network. Maybe it was an issue with zt central, i haven't kept an eye on it for a couple days. Does the program write any logs? I can't find any.

**Comment by laduke** [comment]
Hello

I think you can avoid this by using macvlan. 
There's no logs. Just the current state, which you could log. 

Hopefully you're using different home directories for each instance of zerotier. 

Your container may be double NAT ed (if the host is behind a nat router), which is very difficult for zerotier to traverse, but it keeps trying. This may be why it showed up later.
