### ISSUE TITLE
ZeroTier service user should not have a login shell on Linux

### ISSUE THREAD

**Issue by darkbroodzed** [zerotier/ZeroTierOne#1492]
Default and recommended installer create new user and set it able to login. Why? Are you try create biggest botnet on earth?
cat /etc/passwd
...
zerotier-one:x:998:998::/var/lib/zerotier-one:/bin/sh
...

 - OS: Linux 
 - Ubuntu 21.10 
 - ZeroTier Version any 1.8.x+

**Comment by adamierymenko** [comment]
Oops. Yes we should fix that, but it's not actually a security risk. The account has no password, no ssh key, so no login, and if someone actually did find a way to remotely compromise the ZeroTier service they could simply execute whatever they wanted including `/bin/sh` regardless of whether the account had a login shell.

**Comment by adamierymenko** [comment]
Fixed in 1.8.3 (soon to be released)
