### ISSUE TITLE
Forward data without using PLANET [Feature Request] 

### ISSUE THREAD

**Issue by daifeilail** [zerotier/ZeroTierOne#1493]
ZEROTIER P2P makes it very difficult to troubleshoot communication failures. Even if I have 5 years of CCNP experience, PLANET will provide relay services when P2P communication is interrupted. This function will cause troubles that are difficult to troubleshoot. I hope to add PLANET to local.conf. Provide relay parameters.

reason:
1. When P2P is interrupted due to firewall, PLANET provides relay service, which will make the fault unobservable
2. The communication quality provided by PLANET cannot reach the production level,
3. PLANET should provide addressing capabilities just like DNS. Don’t provide relay capability, which increases the burden on PLANET, and it is not reliable communication

    ---------GOOGLE Translate

**Comment by laduke** [comment]
Hello,
thanks for writing. Unfortunately the relaying is part of design and can't be changed. https://docs.zerotier.com/zerotier/manual#211networktopologyandpeerdiscoveryaname2_1_1a


To observe the relay state, monitor `zerotier-cli peers` (or the api `curl -v 'http://localhost:9993/peer' -H "X-ZT1-AUTH: $TOKEN"`)

You can use a moon for better relay speed
https://github.com/rwv/docker-zerotier-moon/
https://docs.zerotier.com/zerotier/moons

Hope that helps. Let us know if there are any other questions.
