### ISSUE TITLE
command "listpeers " does not show the ip of my moon-server.  and the delay between clients is high 

### ISSUE THREAD

**Issue by BrotherHappy** [zerotier/ZeroTierOne#1506]
results of listpeers is below
![image](https://user-images.githubusercontent.com/70844235/145182548-7b04e2fc-2763-46a4-8525-78c00d7ab3fc.png)

could someone who has a big ball could help me? thanks

**Comment by glimberg** [comment]
If an IP is not listed, then a direct connection cannot be made to the device for some reason.  As this isn't a bug, this is likely more suitable for our [forums](https://discuss.zerotier.com/), rather than an issue report here on GitHub
