### ISSUE TITLE
Custom active-backup bonding policies do not work 

### ISSUE THREAD

**Issue by Feiko** [zerotier/ZeroTierOne#1507]
When using the "aggressive-active-backup" bonding local.conf example ZeroTier shows strange behavior, an IP address is assigned but leafs can't ping each other. 

I'm using the following local.conf:

```
{
  "settings":
  {
    "defaultBondingPolicy": "aggressive-active-backup",
    "policies":
    {
      "aggressive-active-backup":
      {
        "failoverInterval": 1000,
        "basePolicy": "active-backup"
      }
    }
  }
}
```
ListPeers outputs:

```
200 listpeers <ztaddr> <path> <latency> <version> <role>
200 listpeers 61d294b9cb - -1 - PLANET
200 listpeers 62f865ae71 - -1 - PLANET
200 listpeers 6a32dd8f32 - 0 1.8.4 LEAF
200 listpeers 6adef67e56 - 0 1.8.4 MOON
200 listpeers 778cde7190 - -1 - PLANET
200 listpeers 992fcf1db7 - -1 - PLANET
```

However, when I use the following local.conf, I get an IP address assigned, the bonding works and Leafs can ping each other.  

```
{
  "settings":
  {
    "defaultBondingPolicy": "active-backup",
  }
}

```

However when I use the  

Listpeers outputs:

```
200 listpeers <ztaddr> <path> <latency> <version> <role>
200 listpeers 61d294b9cb 50.7.73.34/9993;14300;394 0 - PLANET
200 listpeers 62f865ae71 50.7.252.138/9993;14306;402 0 - PLANET
200 listpeers 6adef67e56 192.168.2.3/9993;752;752 0 1.8.4 MOON
200 listpeers 738dd5c610 192.168.2.2/9993;9234;9522 11 1.8.4 LEAF
200 listpeers 778cde7190 103.195.103.66/9993;14306;510 0 - PLANET
200 listpeers 992fcf1db7 195.181.173.159/9993;9500;722 0 - PLANET
```

I've tried multiple machines Windows and Linux also tried this on multiple networks. Every time showing the same behavior, when I try to implement a custom policy ZeroTier does not seem to connect properly. 

Note: When I try to ping a Linux leave using a custom policy and I restart the ZeroTier service on this Linux machine, the Leaf is reachable for about 5 seconds. After this I'll receive only timeouts. 

I'm hoping for a fix. I need to set a custom failoverinterval and also specify the failover network.   

## Additional information 

**Desktop (please complete the following information):**
 - OS: Windows
 - OS/Distribution Version: 19043
 - ZeroTier Version:  1.8.4
  

 **Embedded & NAS (please complete the following information):**
 - Device: Pi4
 - OS/Distribution: Raspbian
 - ZeroTier Version: 1.8.4

**Additional context**
- ZeroTier Network Configuration: IPv4 & IPv6 networks defined on your ZeroTier Central
- Router Config: are you permitting port 9993, uPnP, and NAT-PMP? Yes
- Firewall Config: are you permitting port 9993 on your OS; setting it to "Private" on Windows? Yes Private
- Are you using this at home, in an office, college, etc? Home
- Have you tried screaming into your router? YES

**Comment by joseph-henry** [comment]
Thanks for catching this. This is fixed in `dev` and will be mainlined in `1.8.5`
