### ISSUE TITLE
ipad app zerotier 1.8.1 issue

### ISSUE THREAD

**Issue by microdockman** [zerotier/ZeroTierOne#1515]
device : ipad   OS 15.2
zerotier version : 1.8.1

issue:
     I've been using the Default Route feature on Android and iPad，when Default Route is enabled, I can access all the devices in the remote LAN, but recently I can't connect to the remote-router login interface  any more. Strangely, I can access the network normally,All this is normal on Android devices。
     I updated everything, including rebuilding the network，but the iPad'problem remains

**Comment by glimberg** [comment]
Is the router listening on the ZeroTier network?  Are other devices able to access the router login page over the ZeroTier network?

**Comment by microdockman** [comment]
> 路由器登录界面是否监听ZeroTier网络？其他设备是否可以通过 ZeroTier 网络访问路由器登录页面？

Android devices are fine, existing networks remain unchanged, and the iPad problem appears after updating ZeroTier to the latest

**Comment by aotsukiqx** [comment]
running into this issue too, all ios device recently can not overwrite default route or dns configuration. android and macos works as expected.

**Comment by microdockman** [comment]
> running into this issue too, all ios device recently can not overwrite default route or dns configuration. android and macos works as expected.

After updating the iPad to the latest version, it seems to have been solved

**Comment by aotsukiqx** [comment]
> > running into this issue too, all ios device recently can not overwrite default route or dns configuration. android and macos works as expected.
> 
> After updating the iPad to the latest version, it seems to have been solved

Very strange... my iPhone is update IOS 15.3.1 but zt 1.8.1 default route and DNS setting still not working....
Can you confirm again? Or I should file another issue...

**Comment by microdockman** [comment]
> > > running into this issue too, all ios device recently can not overwrite default route or dns configuration. android and macos works as expected.
> > 
> > 
> > After updating the iPad to the latest version, it seems to have been solved
> 
> Very strange... my iPhone is update IOS 15.3.1 but zt 1.8.1 default route and DNS setting still not working.... Can you confirm again? Or I should file another issue...

I can confirm that
ipad air 15.3.1        zeroteir version 1.8.1
All other Settings remain unchanged
You can try to connect with the iPad or Android device, exclude the possibility of error setup

**Comment by aotsukiqx** [comment]
finally, was rejoined the network by manually setting DNS server which was set in ZT configuration, all things work again.
Seems IOS client can not pull DNS settings caused this issue.

**Comment by microdockman** [comment]
This issues reappears after updating the iPad @@

**Comment by microdockman** [comment]
> This issues reappears after updating the iPad @@

solved

The local network segment must be different from the remote network segment

**Comment by ap46281** [comment]
> > This issues reappears after updating the iPad @@
> 
> solved
> 
> The local network segment must be different from the remote network segment

I don’t see this as an option in the settings. I am trying to connect my iPad to my Mac to sync with iTunes. It shows as a device in Finder but won’t connect
