### ISSUE TITLE
New Fedora 35 VM and access issue

### ISSUE THREAD

**Issue by harishpillay** [zerotier/ZeroTierOne#1518]
I've got a fresh Fedora 35 (updated to latest kernel 5.15.8) and added the zerotier repo. The installation went well, and I could join the network. But it is not showing up in the zerotier central console page. I did a zerotier-cli leave <networkID> and that returned success and then rejoined. it returned "200 join OK", but that host is not showing up in console.

```
Name        : zerotier-one
Version     : 1.8.4
Release     : 1.fc35
Architecture: x86_64
Install Date: Mon 20 Dec 2021 12:01:18 AM
Group       : Unspecified
Size        : 1602896
License     : BSL and Boost and ASL and ASL 2.0 and MIT
Signature   : RSA/SHA1, Sat 04 Dec 2021 01:53:07 AM, Key ID 6a2af96194843c65
Source RPM  : zerotier-one-1.8.4-1.fc35.src.rpm
Build Date  : Fri 03 Dec 2021 04:34:17 PM
Build Host  : buildvm-07.virt.rpmfusion.net
```

Any hints on debugging?

**Comment by laduke** [comment]
Hello. Thanks for reporting. I did a Fedora 35 netinstall today, and got kernel 5.15.11 and zerotier is working. 
What does `zerotier-cli listnetworks` say for the status?

**Comment by harishpillay** [comment]
```
% zerotier-cli listnetworks
200 listnetworks <nwid> <name> <mac> <status> <type> <dev> <ZT assigned ips>
200 listnetworks <nwid> <NAME IS MISSING> <mac> REQUESTING_CONFIGURATION PRIVATE <zt-dev>
```

**Comment by laduke** [comment]
REQUESTING_CONFIGURATION is typically a physical network access (firewall) problem

**Comment by harishpillay** [comment]
Thanks for that tip. What port would it be blocking?

**Comment by glimberg** [comment]
ZeroTIer uses UDP ports 9993 as well as 2 other randomized port numbers.  The two high port numbers are non-deterministic and may change at any time.

**Comment by glimberg** [comment]
Closing as this is a firewall issue and not a code issue.
