### ISSUE TITLE
Can ZeroTier be used to share VPN with other machine?

### ISSUE THREAD

**Issue by sqiangcao99** [zerotier/ZeroTierOne#1519]
Hi, I have built a local area network using zerotier. Can zerotier be used to share the VPN to the LAN?

**Comment by laduke** [comment]
Hello,

https://zerotier.atlassian.net/wiki/spaces/SD/pages/224395274/Route+between+ZeroTier+and+Physical+Networks

If your your router itself can run zerotier, that's even better.  
https://discuss.zerotier.com/
