### ISSUE TITLE
How to make zerotier p2p-connect over ipv4 instead of ipv6

### ISSUE THREAD

**Issue by yaotthaha** [zerotier/ZeroTierOne#1520]
I want to connect another peer over ipv4 instead of ipv6, because of bad ipv6 routing. How to force to connect over ipv4?

Zerotier Version: 1.6.5

**Comment by laduke** [comment]
You can
- block it in your machine's firewall
- maybe put ::/0 in [local.conf](https://github.com/zerotier/ZeroTierOne/tree/master/service) physical blacklist. Haven't tried. 

if ipv4 works better, zerotier should be using it automatically

**Comment by yaotthaha** [comment]
I try to block another peer IPv6, it doesn't work. I cannot block all IPv6 addresses because of other uses. Therefore, it is necessary to create a IPv4/IPv6 connection selection mechanism.
