### ISSUE TITLE
[Feature Request] Why there is only 100Mbps speed for virtual network card on windows

### ISSUE THREAD

**Issue by SuYong1** [zerotier/ZeroTierOne#1522]
Why there is only 100Mbps speed for virtual network card on windows?
I installed zerotier on my windows computer,and my network is NAT1, with 180Mbps upload.
Is there any method to change the virtual network card speed to 1000Mbps?
![image](https://user-images.githubusercontent.com/20244320/147362048-038b8cf7-aee4-46f6-9bf5-14f532fa9a16.png)

**Comment by SuYong1** [comment]
Maybe I should edit the source code,and compile?
But it is difficult for me.

constants.h?
![image](https://user-images.githubusercontent.com/20244320/147362163-7ea7c45e-9210-45d6-8d76-68a72a227cee.png)

**Comment by gnattu** [comment]
To my understanding this number is just a dummy and you can actual transfer speed more than that. You can try that with two computers in the same LAN to see if you are really limited by the 100mbps speed.

**Comment by glimberg** [comment]
@gnattu is correct.  It's just there for display purposes and doesn't actually affect throughput.  Neither ZeroTier nor Windows do anything to limit the speeds over the interface.  Packets are sent as fast as your CPUs can push them.

**Comment by Yunconnect** [comment]
Are you sure it's just a numerical display? Has anyone actually tested speeds over 11M/s?

**Comment by Yunconnect** [comment]
Thank you author for your reply.

**Comment by TcDhlPro** [comment]
> To my understanding this number is just a dummy and you can have actual transfer speed more than that. You can try that with two computers in the same LAN to see if you are really limited by the 100mbps speed.

**Your understanding is completely wrong. In actual scenarios, the allocation of 10Mbps in Linux systems is really limited to 10Mbps!**
