### ISSUE TITLE
新版本出现重拨后有几率重置zerotier接口mac地址

### ISSUE THREAD

**Issue by Saxon-Sun** [zerotier/ZeroTierOne#1526]
Openwrt N1
每天5点重新拨号

1号重新拨号后正常连接zerotier
2号重新拨号后就出现zerotier mac地址和id改变 导致无法加入私有网络

日志：
Sat Jan  1 05:00:00 2022 cron.err crond[6999]: USER root pid 16189 cmd /sbin/ifup wan
Sat Jan  1 05:00:00 2022 daemon.notice netifd: wan (3145): udhcpc: received SIGTERM
Sat Jan  1 05:00:00 2022 daemon.notice netifd: wan (3145): udhcpc: unicasting a release of 192.168.68.123 to 192.168.68.1
Sat Jan  1 05:00:00 2022 daemon.notice netifd: wan (3145): udhcpc: sending release
Sat Jan  1 05:00:00 2022 daemon.notice netifd: wan (3145): udhcpc: entering released state
Sat Jan  1 05:00:00 2022 daemon.notice netifd: wan (3145): Command failed: Permission denied
Sat Jan  1 05:00:00 2022 daemon.notice netifd: Interface 'wan' is now down
Sat Jan  1 05:00:00 2022 daemon.info avahi-daemon[2957]: Withdrawing address record for 192.168.68.123 on eth0.2.
Sat Jan  1 05:00:00 2022 daemon.info avahi-daemon[2957]: Leaving mDNS multicast group on interface eth0.2.IPv4 with address 192.168.68.123.
Sat Jan  1 05:00:00 2022 daemon.info avahi-daemon[2957]: Interface eth0.2.IPv4 no longer relevant for mDNS.
Sat Jan  1 05:00:00 2022 daemon.info avahi-daemon[2957]: Interface eth0.2.IPv6 no longer relevant for mDNS.
Sat Jan  1 05:00:00 2022 daemon.info avahi-daemon[2957]: Leaving mDNS multicast group on interface eth0.2.IPv6 with address fe80::fe7c:2ff:fed2:5c31.
Sat Jan  1 05:00:00 2022 daemon.info avahi-daemon[2957]: Withdrawing address record for fe80::fe7c:2ff:fed2:5c31 on eth0.2.
Sat Jan  1 05:00:00 2022 daemon.notice netifd: Interface 'wan' is disabled
Sat Jan  1 05:00:00 2022 daemon.notice netifd: Interface 'wan' is enabled
Sat Jan  1 05:00:00 2022 daemon.notice netifd: Interface 'wan' is setting up now
Sat Jan  1 05:00:00 2022 daemon.notice netifd: wan (16311): udhcpc: started, v1.33.2
Sat Jan  1 05:00:00 2022 daemon.notice netifd: wan (16311): udhcpc: sending discover
Sat Jan  1 05:00:02 2022 daemon.info avahi-daemon[2957]: Joining mDNS multicast group on interface eth0.2.IPv6 with address fe80::fe7c:2ff:fed2:5c31.
Sat Jan  1 05:00:02 2022 daemon.info avahi-daemon[2957]: New relevant interface eth0.2.IPv6 for mDNS.
Sat Jan  1 05:00:02 2022 daemon.info avahi-daemon[2957]: Registering new address record for fe80::fe7c:2ff:fed2:5c31 on eth0.2.*.
Sat Jan  1 05:00:03 2022 daemon.info avahi-daemon[2957]: Interface zt3jn*****.IPv6 no longer relevant for mDNS.
Sat Jan  1 05:00:03 2022 daemon.info avahi-daemon[2957]: Leaving mDNS multicast group on interface zt3jn*****.IPv6 with address fe80::2c35:63ff:fe50:49c2.
Sat Jan  1 05:00:03 2022 daemon.info avahi-daemon[2957]: Interface zt3jn*****.IPv4 no longer relevant for mDNS.
Sat Jan  1 05:00:03 2022 daemon.info avahi-daemon[2957]: Leaving mDNS multicast group on interface zt3jn*****.IPv4 with address 172.22.22.2.
Sat Jan  1 05:00:03 2022 daemon.info avahi-daemon[2957]: Withdrawing address record for fe80::2c35:63ff:fe50:49c2 on zt3jn*****.
Sat Jan  1 05:00:03 2022 daemon.info avahi-daemon[2957]: Withdrawing address record for 172.22.22.2 on zt3jn*****.
Sat Jan  1 05:00:03 2022 daemon.notice netifd: wan (16311): udhcpc: sending discover
Sat Jan  1 05:00:04 2022 daemon.notice netifd: wan (16311): udhcpc: sending select for 192.168.68.123
Sat Jan  1 05:00:04 2022 daemon.notice netifd: wan (16311): udhcpc: lease of 192.168.68.123 obtained, lease time 2592000
Sat Jan  1 05:00:04 2022 daemon.info avahi-daemon[2957]: Joining mDNS multicast group on interface eth0.2.IPv4 with address 192.168.68.123.
Sat Jan  1 05:00:04 2022 daemon.info avahi-daemon[2957]: New relevant interface eth0.2.IPv4 for mDNS.
Sat Jan  1 05:00:04 2022 daemon.info avahi-daemon[2957]: Registering new address record for 192.168.68.123 on eth0.2.IPv4.
Sat Jan  1 05:00:04 2022 daemon.notice netifd: Interface 'wan' is now up
Sat Jan  1 05:00:05 2022 daemon.info avahi-daemon[2957]: Joining mDNS multicast group on interface zt3jn*****.IPv4 with address 172.22.22.2.
Sat Jan  1 05:00:05 2022 daemon.info avahi-daemon[2957]: New relevant interface zt3jn*****.IPv4 for mDNS.
Sat Jan  1 05:00:05 2022 daemon.info avahi-daemon[2957]: Registering new address record for 172.22.22.2 on zt3jn*****.IPv4.
Sat Jan  1 05:00:05 2022 daemon.info avahi-daemon[2957]: Joining mDNS multicast group on interface zt3jn*****.IPv6 with address fe80::2c35:63ff:fe50:49c2.
Sat Jan  1 05:00:05 2022 daemon.info avahi-daemon[2957]: New relevant interface zt3jn*****.IPv6 for mDNS.
Sat Jan  1 05:00:05 2022 daemon.info avahi-daemon[2957]: Registering new address record for fe80::2c35:63ff:fe50:49c2 on zt3jn*****.*.
Sat Jan  1 05:00:07 2022 daemon.info avahi-daemon[2957]: Interface zt3jn*****.IPv6 no longer relevant for mDNS.
Sat Jan  1 05:00:07 2022 daemon.info avahi-daemon[2957]: Leaving mDNS multicast group on interface zt3jn*****.IPv6 with address fe80::2c35:63ff:fe50:49c2.
Sat Jan  1 05:00:07 2022 daemon.info avahi-daemon[2957]: Interface zt3jn*****.IPv4 no longer relevant for mDNS.
Sat Jan  1 05:00:07 2022 daemon.info avahi-daemon[2957]: Leaving mDNS multicast group on interface zt3jn*****.IPv4 with address 172.22.22.2.
Sat Jan  1 05:00:07 2022 daemon.info avahi-daemon[2957]: Withdrawing address record for fe80::2c35:63ff:fe50:49c2 on zt3jn*****.
Sat Jan  1 05:00:07 2022 daemon.info avahi-daemon[2957]: Withdrawing address record for 172.22.22.2 on zt3jn*****.
Sat Jan  1 05:00:09 2022 daemon.info avahi-daemon[2957]: Joining mDNS multicast group on interface zt3jn*****.IPv4 with address 172.22.22.2.
Sat Jan  1 05:00:09 2022 daemon.info avahi-daemon[2957]: New relevant interface zt3jn*****.IPv4 for mDNS.
Sat Jan  1 05:00:09 2022 daemon.info avahi-daemon[2957]: Registering new address record for 172.22.22.2 on zt3jn*****.IPv4.
Sat Jan  1 05:00:10 2022 daemon.info avahi-daemon[2957]: Joining mDNS multicast group on interface zt3jn*****.IPv6 with address fe80::2c35:63ff:fe50:49c2.
Sat Jan  1 05:00:10 2022 daemon.info avahi-daemon[2957]: New relevant interface zt3jn*****.IPv6 for mDNS.
Sat Jan  1 05:00:10 2022 daemon.info avahi-daemon[2957]: Registering new address record for fe80::2c35:63ff:fe50:49c2 on zt3jn*****.*.
Sat Jan  1 05:00:14 2022 user.notice firewall: Reloading firewall due to ifup of wan (eth0.2)
Sun Jan  2 05:00:00 2022 cron.err crond[19478]: USER root pid 31129 cmd /sbin/ifup wan
Sun Jan  2 05:00:00 2022 daemon.notice netifd: wan (16311): udhcpc: received SIGTERM
Sun Jan  2 05:00:00 2022 daemon.notice netifd: wan (16311): udhcpc: unicasting a release of 192.168.68.123 to 192.168.68.1
Sun Jan  2 05:00:00 2022 daemon.notice netifd: wan (16311): udhcpc: sending release
Sun Jan  2 05:00:00 2022 daemon.notice netifd: wan (16311): udhcpc: entering released state
Sun Jan  2 05:00:00 2022 daemon.notice netifd: wan (16311): Command failed: Permission denied
Sun Jan  2 05:00:00 2022 daemon.notice netifd: Interface 'wan' is now down
Sun Jan  2 05:00:00 2022 daemon.info avahi-daemon[2957]: Withdrawing address record for 192.168.68.123 on eth0.2.
Sun Jan  2 05:00:00 2022 daemon.info avahi-daemon[2957]: Leaving mDNS multicast group on interface eth0.2.IPv4 with address 192.168.68.123.
Sun Jan  2 05:00:00 2022 daemon.info avahi-daemon[2957]: Interface eth0.2.IPv4 no longer relevant for mDNS.
Sun Jan  2 05:00:00 2022 daemon.info avahi-daemon[2957]: Interface eth0.2.IPv6 no longer relevant for mDNS.
Sun Jan  2 05:00:00 2022 daemon.info avahi-daemon[2957]: Leaving mDNS multicast group on interface eth0.2.IPv6 with address fe80::fe7c:2ff:fed2:5c31.
Sun Jan  2 05:00:00 2022 daemon.info avahi-daemon[2957]: Withdrawing address record for fe80::fe7c:2ff:fed2:5c31 on eth0.2.
Sun Jan  2 05:00:00 2022 daemon.notice netifd: Interface 'wan' is disabled
Sun Jan  2 05:00:00 2022 daemon.notice netifd: Interface 'wan' is enabled
Sun Jan  2 05:00:00 2022 daemon.notice netifd: Interface 'wan' is setting up now
Sun Jan  2 05:00:00 2022 daemon.notice netifd: wan (31238): udhcpc: started, v1.33.2
Sun Jan  2 05:00:00 2022 daemon.notice netifd: wan (31238): udhcpc: sending discover
Sun Jan  2 05:00:02 2022 daemon.info avahi-daemon[2957]: Joining mDNS multicast group on interface eth0.2.IPv6 with address fe80::fe7c:2ff:fed2:5c31.
Sun Jan  2 05:00:02 2022 daemon.info avahi-daemon[2957]: New relevant interface eth0.2.IPv6 for mDNS.
Sun Jan  2 05:00:02 2022 daemon.info avahi-daemon[2957]: Registering new address record for fe80::fe7c:2ff:fed2:5c31 on eth0.2.*.
Sun Jan  2 05:00:03 2022 daemon.notice netifd: wan (31238): udhcpc: sending discover
Sun Jan  2 05:00:03 2022 daemon.info avahi-daemon[2957]: Interface zt3jn*****.IPv6 no longer relevant for mDNS.
Sun Jan  2 05:00:03 2022 daemon.info avahi-daemon[2957]: Leaving mDNS multicast group on interface zt3jn*****.IPv6 with address fe80::2c35:63ff:fe50:49c2.
Sun Jan  2 05:00:03 2022 daemon.info avahi-daemon[2957]: Interface zt3jn*****.IPv4 no longer relevant for mDNS.
Sun Jan  2 05:00:03 2022 daemon.info avahi-daemon[2957]: Leaving mDNS multicast group on interface zt3jn*****.IPv4 with address 172.22.22.2.
Sun Jan  2 05:00:03 2022 daemon.info avahi-daemon[2957]: Withdrawing address record for fe80::2c35:63ff:fe50:49c2 on zt3jn*****.
Sun Jan  2 05:00:03 2022 daemon.info avahi-daemon[2957]: Withdrawing address record for 172.22.22.2 on zt3jn*****.
Sun Jan  2 05:00:04 2022 daemon.notice netifd: wan (31238): udhcpc: sending select for 192.168.68.123
Sun Jan  2 05:00:04 2022 daemon.notice netifd: wan (31238): udhcpc: lease of 192.168.68.123 obtained, lease time 2592000
Sun Jan  2 05:00:04 2022 daemon.info avahi-daemon[2957]: Joining mDNS multicast group on interface eth0.2.IPv4 with address 192.168.68.123.
Sun Jan  2 05:00:04 2022 daemon.info avahi-daemon[2957]: New relevant interface eth0.2.IPv4 for mDNS.
Sun Jan  2 05:00:04 2022 daemon.info avahi-daemon[2957]: Registering new address record for 192.168.68.123 on eth0.2.IPv4.
Sun Jan  2 05:00:04 2022 daemon.notice netifd: Interface 'wan' is now up
Sun Jan  2 05:00:09 2022 daemon.info avahi-daemon[2957]: Joining mDNS multicast group on interface zt3jn*****.IPv6 with address fe80::2c80:2aff:fea6:69ed.
Sun Jan  2 05:00:09 2022 daemon.info avahi-daemon[2957]: New relevant interface zt3jn*****.IPv6 for mDNS.
Sun Jan  2 05:00:09 2022 daemon.info avahi-daemon[2957]: Registering new address record for fe80::2c80:2aff:fea6:69ed on zt3jn*****.*.
Sun Jan  2 05:00:14 2022 user.notice firewall: Reloading firewall due to ifup of wan (eth0.2)
Sun Jan  2 14:55:55 2022 daemon.info avahi-daemon[2957]: Joining mDNS multicast group on interface zt3jn*****.IPv4 with address 172.22.22.154.
Sun Jan  2 14:55:55 2022 daemon.info avahi-daemon[2957]: New relevant interface zt3jn*****.IPv4 for mDNS.
Sun Jan  2 14:55:55 2022 daemon.info avahi-daemon[2957]: Registering new address record for 172.22.22.154 on zt3jn*****.IPv4.

**Comment by glimberg** [comment]
The OpenWRT port of ZeroTier is a project submitted & maintained by the community.  Please see its documentation if you're having issues: https://github.com/mwarning/zerotier-openwrt/wiki https://github.com/mwarning/zerotier-openwrt
