### ISSUE TITLE
ZeroTier on Windows cannot connect to the Moons

### ISSUE THREAD

**Issue by coldSun233** [zerotier/ZeroTierOne#1527]
I have created a moon on aliyun server and ZeroTier on Ubuntu has successfully connected to it,
but ZeroTier on Windows can't connect to it. When I run the command `zerotier-cli listpeers` on Windows, 
the results are as follows:
![2022-01-03_213649](https://user-images.githubusercontent.com/40413054/147937199-97adfd31-b689-416d-872e-6197fcd763b5.png)
It is obvious that the path of moon is null.
I tried several times according to the official documentation, but all failed. How can I solve this problem?

**Comment by yikomuzi** [comment]
How did you solve the problem?
