### ISSUE TITLE
Some NAT routers demand that a kitten be sacrificed every 15-30 seconds.

### ISSUE THREAD

**Issue by raarts** [zerotier/ZeroTierOne#153]
Hi, when no traffic is passing over the interface, zero tier does not seem to notice the connectivity going down. My tests show it seems to ignore broadcast and icmp traffic for online/offline detection.

I am looking at ```zerotier-cli info``` output

**Comment by adamierymenko** [comment]
It operates entirely at the UDP level. I suspect that you have a router or firewall in the way that is interfering with traffic.

**Comment by adamierymenko** [comment]
P.S. There is a new forum online here: https://www.zerotier.com/forum/

It might be preferable to GitHub issues for questions of this nature, but either way is fine. I have no strong preference. (I wish the two could be linked.)

**Comment by adamierymenko** [comment]
Also note that ZeroTier always sends "keep alive," and does so at a fixed interval of 120 seconds (2 minutes). If your NAT has a shorter timeout, that could cause up/down/up/down behavior.

**Comment by raarts** [comment]
My setup: zerotier behind Comcast NAT router. Works fine. Run traffic over
it,
no problems.

Then I stopped sending traffic. Waited until there was zero traffic over
the zt0 interface.
I pulled the network cable between de zerotier machine and the Comcast
router. And
repeatedly ran zerotier-cli. It kept reporting ONLINE for many minutes.

Then I did the same test while again running a lot of (UDP) traffic over
the zt0 interface.
This time it took like 60 seconds before it reported OFFLINE.

So when does zerotier consider itself OFFLINE?

**Comment by adamierymenko** [comment]
Ahh, I get it. Online status is determined heuristically. It's actually a bit of a hard problem, since you want to avoid confusing packet loss or little bits of 'network weather' with being offline.

ZeroTier also doesn't really use offline status for anything other than reporting it to the user for diagnostic purposes. It is aggressive about continuing to try to send packets if there is traffic on an interface, and will do so basically forever.

**Comment by adamierymenko** [comment]
https://github.com/zerotier/ZeroTierOne/blob/master/node/Node.cpp#L723

**Comment by raarts** [comment]
That might explain your NAT problems. Many NAT routers have a 1 minute
timeout.
VoIP phones as a rule send a UDP keepalive packet every 15 second, to make
it work
for all NAT routers.

**Comment by adamierymenko** [comment]
"VoIP phones as a rule send a UDP keepalive packet every 15 second, to make
it work
for all NAT routers."

Face palm.

That's a *lot* of traffic just to hack around crummy NAT routers.

I'll take it under advisement. :sob:

**Comment by adamierymenko** [comment]
NAT kills kittens: https://www.zerotier.com/blog/?p=226

**Comment by raarts** [comment]
Well, it's just an zero-length UDP packet every 15 seconds. It's not that
bad.
And I trade that traffic very happily considering the alternative: a
support call:
my phone is not receiving calls!!

Please add a command line argument for keepalive timer!

**Comment by raarts** [comment]
Hi Adam,

trying to implement the 15 second keep-alive myself, but I'm having trouble
with the code. Can you help me clear something up?

grepping for 120, I found ZT_PEER_DIRECT_PING_DELAY. This points
to PingPeersThatNeedPing(),
which calls p->SendPing. This function says: 'Ping (and thus open) outbound
TCP connections'
and so does not seem to be used for keep-alive.

Then I turned Packet.hpp, and found 'Beacons may be used for direct LAN
announcement
or NAT traversal.' I thought I got it, but ZT_BEACON_INTERVAL seems to be
used on local
LAN only.

Can you give me some tips on how to bring down the 120 sec keep-alive?

Best,
Ron

**Comment by adamierymenko** [comment]
ZT_PEER_DIRECT_PING_DELAY is indeed the correct thing, but don't change it in Constants.h as other values are computed from it.

I would just hack the logic in these two function objects to make them ping more frequently: https://github.com/zerotier/ZeroTierOne/blob/master/node/Topology.hpp#L223

Maybe change:

    (_now - p->lastDirectReceive()) >= ZT_PEER_DIRECT_PING_DELAY)

to:

    (_now - p->lastDirectReceive()) >= 15)

This will be inefficient though as it will send full HELLOs, not empty packets. It'll work fine for now, but in the next version I will probably add zero-byte keepalives as I've received other reports that sound like NATs with short timeouts.

I wonder how many of these empty UDP packets are swirling around the Internet just as hacks to trick NATs. The sooner we can go V6 and kill NAT, the better.

**Comment by adamierymenko** [comment]
Oh wait -- that 15 should be 15000, since it's in milliseconds.

**Comment by raarts** [comment]
Thanks, I'll try it. The two obejcts being PingPeersThatNeedPing
and PingSupernodesThatNeedPing, right?
And I can assure you, looking at the amount of VoIP phones in the field,
there shouldn't be any kittens left by now.
Thank god they're so resilient ;-)

**Comment by adamierymenko** [comment]
This is in -dev. Kittens are now offed approximately once every 25 seconds, since most of the NAT timeout surveys I could find online (usually SIP-related) specify 30 seconds as the shortest NAT timeouts typically found in nature.

**Comment by raarts** [comment]
Ok, great. I turned it down to 15 seconds just for fun, and it certainly
fixed the problem with my
crappy Comcast modem.

Ron

**Comment by donspaulding** [comment]
We've seen an increase in connection problems between arbitrary nodes lately, notwithstanding activity on both ends.  I'd like to ascertain whether they are related to NAT timeouts as mentioned in this ticket. 

Is there an easy way to identify this issue?  When we're hit by it, both nodes typically report ONLINE in response to `zerotier-cli info`, but `zerotier-cli listpeers` doesn't show a route to the other node.  The situation is sometimes asymmetrical, where the near node has a route to the far node and can ping it just fine, but the far node has no route to the near node.

**Comment by raarts** [comment]
What I would do, is start pings on the nodes between NAT to some zt machine
in the cloud somewhere
(not behind NAT) using ping times of about 20 seconds. If the connection
problems go away, then I would
say NAT caused them in the first place. Note that your cloud machine must
open up port 9993/udp.

Ron

**Comment by adamierymenko** [comment]
Fixed in -dev -- we'll see if this helps.
