### ISSUE TITLE
windows 10 ui error

### ISSUE THREAD

**Issue by sm1314** [zerotier/ZeroTierOne#1536]
system:

版本	Windows 10 专业版
版本号	21H1
安装日期	‎2021/‎6/‎12
操作系统内部版本	19043.1237
体验	Windows Feature Experience Pack 120.2212.3530.0

error：
![image](https://user-images.githubusercontent.com/3960433/148671628-aefb7e07-8b77-406d-8b72-d3526a93bef2.png)

**Comment by sm1314** [comment]
version: 1.8.4

**Comment by joseph-henry** [comment]
What version of Edge is installed? I've read that an old version can cause this.
