### ISSUE TITLE
lsof -i:9993 display

### ISSUE THREAD

**Issue by lalasou** [zerotier/ZeroTierOne#1548]
zerotier-one can't work properly, can't get ip, lsof -i:9993 display doesn't look normal help 🆘
I feel like it should show *:9993
![image](https://user-images.githubusercontent.com/7440313/150675121-f56821aa-fc0e-44b0-a13b-9bf5347b3cc0.jpeg)

**Comment by joseph-henry** [comment]
That looks normal to me. Can you tell us a little more about your setup and what's wrong?

**Comment by lalasou** [comment]
> That looks normal to me. Can you tell us a little more about your setup and what's wrong?

The zerotier-one I run on Slackware can't get the intranet ip, sometimes it takes a night to get it. But the other same Slackware works fine, the two of them are different except for the network.
What is the official IP of zerotier? I want to try to ping the official ip to see if it works

**Comment by joseph-henry** [comment]
There is no "official ip". Have you read our [getting started](https://zerotier.atlassian.net/wiki/spaces/SD/pages/8454145/Getting+Started+with+ZeroTier) guide?

**Comment by lalasou** [comment]
> There is no "official ip". Have you read our [getting started](https://zerotier.atlassian.net/wiki/spaces/SD/pages/8454145/Getting+Started+with+ZeroTier) guide?

These I know, but the zerotier website console does not show up for the host. The zerotier-one network card did not get the virtual ip

**Comment by joseph-henry** [comment]
Sounds like a firewall might be blocking traffic. Make sure UDP/9993 is allowed. You will only get an IP address assigned if your host successfully joins a network and is authorized.

**Comment by lalasou** [comment]
> Sounds like a firewall might be blocking traffic. Make sure UDP/9993 is allowed. You will only get an IP address assigned if your host successfully joins a network and is authorized.

After a while (about one night) it gets the ip again, it shouldn't be a firewall problem

**Comment by joseph-henry** [comment]
Sorry but this doesn't sound like a ZeroTier problem. Unless you can provide more clues about your network environment, exactly the steps to replicate it, etc we won't be able to help you.

Additionally, we have the bug template in place for a reason. I would suggest filling that out.

**Comment by lalasou** [comment]
> Sorry but this doesn't sound like a ZeroTier problem. Unless you can provide more clues about your network environment, exactly the steps to replicate it, etc we won't be able to help you.
> 
> 
> 
> Additionally, we have the bug template in place for a reason. I would suggest filling that out.

Can I give you the ssh key to help me diagnose

**Comment by joseph-henry** [comment]
No

**Comment by lalasou** [comment]
> No

ok 😭

**Comment by gustavc39** [comment]
@lalasou could you please provide more info regarding your Slackware setup (built from source, repackaged bin?) I'm trying to do that but no luck so far... Thanks
