### ISSUE TITLE
Network change breaks connection.

### ISSUE THREAD

**Issue by shangjiaxuan** [zerotier/ZeroTierOne#1549]
## Required

- What you expect to be happening.
    When switching from wifi to mobile data and vice-versa. Zerotier should recognize the change from failed transport, and retry establishing new route. 
- What is actually happening?
   zerotier-one cannot recognize the change and requires a re-connection to zerotier network to access home-hosted smb service.
- Any steps to reproduce the error.
  Have a hosted smb server at home LAN, install and use zerotier 1.8.4 on it. Use a android phone with zerotier 1.6.2 and perform the network switch. Access fails after change, disappears after manually reconnecting.

## Additional information 
  
**Smartphone (please complete the following information):**
 - Device: HUAWEI Mate 30
 - OS: Android 10
 - ZeroTier Version: 1.6.2

 **Embedded & NAS (please complete the following information):**
 - Device: Raspberry Pi 4b
 - OS/Distribution PI lite OS + openmediavault
 - ZeroTier Version 1.8.4

**Additional context**
- ZeroTier Network Configuration: default
- Router Config: are you permitting port 9993, uPnP, and NAT-PMP?
   default config, nothing banned.
- Firewall Config: are you permitting port 9993 on your OS; setting it to "Private" on Windows?
   nas device iptables has whitelist on given ip INPUT ACCEPT, else drop.
   Android device has default config.
- Are you using this at home, in an office, college, etc?
   Using at home LAN and mobile network. Problem occurs when switch happens.
- Have you tried screaming into your router?
   NO...

**Comment by igorparsadanov** [comment]
I have also experienced this, testing done with a Windows 10 laptop and switching from one network to another results in no connectivity on the zerotier network.  Restarting the zerotier-one service on the laptop re-establishes the connection for me.

**Comment by joseph-henry** [comment]
This is a known behavior that we're working to improve. I'll update this thread once a solution has been mainlined.

**Comment by joseph-henry** [comment]
I'd be curious to know if there was an improvement in `1.8.9`, in my testing it should detect and switch in about 15 seconds now.

**Comment by igorparsadanov** [comment]
Hard to say, only my windows laptop has 1.8.9, iphone is on 1.8.0, and
Mikrotik I'm not sure how the versioning works on that.  But just upgrading
my laptop to 1.8.9 did not seem to change the behavior of switching the
networks on the laptop.

**Comment by codeandroid** [comment]
Not sure if that helps, but perhaps it is related.

After upgrading to 1.8.8 we experienced quite a lot of lost connections or "hanging DNS queries" on Win10 laptops. 
This made it necessary to restart the zerotier service every hour or two. Strangely enough not all communication was down. *Some* connections stayed up but perhaps this was because their connection was already up and therefore did not require another DNS lookup. It affected all kind of programs (browsers, svn.exe, ...).

Switching to 1.8.9 seems to have resolved this. At least, after having upgraded a few days ago we do not experience these problems anymore.

**Comment by joseph-henry** [comment]
@igorparsadanov You should definitely upgrade ZT on your iPhone. There have been significant performance and connectivity fixes since then. Closing unless someone reports back with a problem for a current version. Thanks.

**Comment by CheukHoYun** [comment]
The issue still exists on Windows version 1.10.1. Any fixes or an ETA for the fix?

**Comment by Blochergroup** [comment]
Same issue on Win 11.

After switching between 2 networks the connection is lost and takes quite some time or a restart to connect again
