### ISSUE TITLE
[HELP][QUESTION]Zerotier does not create zt0 interface on DD-WRT 

### ISSUE THREAD

**Issue by 2senel** [zerotier/ZeroTierOne#155]
I dont know what happened because it worked fine on DD-WRR router....
Zerotier-one is running.

zt0 is not created and zerotier-cli listnetworks returns:
200 listnetworks 8056c2e21c2bc48d LAN_private 8e:54:a0:4a:b5:d9 INITIALIZING 50436 private  -

However web network administration shows pretty much this:
908b56571b 3 seconds 10.185.5.1/20 ....	

Is there any way how to create interface manually or debug this issue?

**Comment by adamierymenko** [comment]
Is the 'tun' kernel module available?

**Comment by adamierymenko** [comment]
It may be either compiled into the kernel or available as a module, but if it's not available ZeroTier One won't be able to create interfaces.

**Comment by 2senel** [comment]
Hi,

tun module is avaible. Zerotier worked fine until a few weeks ago, then "something" happened.

I'm running same firmware on same router without any config changes. There's OpenVPN instance running on same router using one tun and one tap interface, so this is no tun/tap issue, I guess.

Rather, I'm wondering if there's a way how to create interface manually to test it?

As I mentioned above, strange thing is that my router acts like online in web administration.

**Comment by adamierymenko** [comment]
It probably is online in the sense that the ZeroTier service is communicating. It just seems to have some sort of problem creating the tun/tap device.

A few things to check:

- Is the disk/flash storage full?

- Is there perhaps some kind of permission problem?

- Is the /sbin/ip binary available? This is needed to configure the interface.

**Comment by 2senel** [comment]
1) No, there`s more than 500MB free.

2) Maybe, just to be sure, all test are under root. This should eliminate permision problems.

3) ip cmd is available from /usr/sbin path though and PATH is set correctly.

**Comment by 2senel** [comment]
Did some experiments with router and found this in log:

Mon Apr  6 10:20:30 2015] network 8056c2e21c2bc48d failed to initialize: unable to configure TAP MTU

**Comment by adamierymenko** [comment]
That would be a failure here:

	// Set MTU
	ifr.ifr_ifru.ifru_mtu = (int)mtu;
	if (ioctl(sock,SIOCSIFMTU,(void *)&ifr) < 0) {
		::close(_fd);
		::close(sock);
		throw std::runtime_error("unable to configure TAP MTU");
	}

What kernel version do you have going here?

**Comment by 2senel** [comment]
Firmware Version DD-WRT v24-sp2 (04/01/15) big - build 26635
Kernel Version Linux 2.6.24.111 #24872 Wed Apr 1 03:06:50 CEST 2015 mips

**Comment by adamierymenko** [comment]
What happens if you manually try to set MTU on an interface manually with ifconfig? Try setting it higher? Maybe there is some kind of /proc filesystem setting for max MTU?

**Comment by adamierymenko** [comment]
ZeroTier's TAPs get an MTU of 2800 -- this will become per-network configurable in the future but that's what they get now.

**Comment by 2senel** [comment]
I tried to set MTU globally from auto to several values (1200,1500, 2800, ...) and error is same.

Can`t set MTU for zt0 interface with ifconfig because there`s no zt0 iface created.

So I uninstalled zerotier completely and started from scratch and ended up with same error as above.

**Comment by adamierymenko** [comment]
It seems the interface isn't being properly initialized/created, but this isn't being detected.

Do an 'ifconfig -a' before and after starting the service. Do you see *any* new interfaces being created?

**Comment by 2senel** [comment]
Switched from DD-WRT based router to AsusWRT and ZT works fine since then.

**Comment by huangyingw** [comment]
@2senel , I am very interested in "how to install zerotier on dd-wrt", could you share more in details ?

**Comment by bobberb** [comment]
@2senel  would like to know how to install on AsusWRT as well

**Comment by laduke** [comment]
@2senel @bobberb thanks for your interest. ZeroTier doesn't do the WRT packages. You'd have to go check with those projects.
