### ISSUE TITLE
Android app doesn't work on T-Mobile network

### ISSUE THREAD

**Issue by wordlover** [zerotier/ZeroTierOne#1550]
ZT on Android Pixel 5a phone works fine when connected to internet via wifi/home ISP, but when I turn wifi connection off and phone connects to internet via only T-Mobile 5G network (as when outside my home), instantly there is no ability to visit any web site at all. Literally, no connection. What’s incompatible here and what can I do to fix it?

**Comment by dafyre** [comment]
Hi Wordlover,

Just one thing to check.  In the app on my phone, from the main screen, if
you click the "Wrench" icon -- in the top right corner of the screen, Make
sure the use Cellular Data option is checked.  I don't remember if it is on
or off by default.

**Comment by wordlover** [comment]
Thanks - yes, that is checked.
