### ISSUE TITLE
Devices are auth and online but cant connect

### ISSUE THREAD

**Issue by AJEvans3** [zerotier/ZeroTierOne#1557]
New Zerotier user. I have installed zerotier on a macbook, unraid server, iphone, ipad, and home assistant. In my zerotier network settings it shows that all devices are Auth, have managed IPs, and online. But I cant ping them and I cant connect to any of them. Not sure if it matters or not but my home router is a Unifi UDMP.

**Comment by glimberg** [comment]
Please see:

[ZeroTier Community Forums](https://discuss.zerotier.com/)
[ZeroTier Documentation](https://docs.zerotier.com)
[ZeroTier Knowledge Base](https://zerotier.atlassian.net/wiki/spaces/SD/overview)

**Comment by AJEvans3** [comment]
Ive been on all three. Havent found a solution in the knowledge bank, documentation, or forum. I posted on the forum waiting for a response.
