### ISSUE TITLE
kernel_task floats at ~16% using ZeroTier on OS X 10.10.3 Public Beta

### ISSUE THREAD

**Issue by haythamelkhoja** [zerotier/ZeroTierOne#156]
Hi,
I'm seeing a ~15%-18% CPU usage of kernel_task on OS X 10.10.3 Public Beta.

I'm not sure if the issue was there on OS X 10.10.2

![screenshot 2015-04-01 14 14 31](https://cloud.githubusercontent.com/assets/450702/6939873/787982bc-d879-11e4-8c7c-140b39f05dca.png)
.

**Comment by adamierymenko** [comment]
You sure this is a ZeroTier-related issue? Does it go away if you:

    sudo launchctl unload /Library/LaunchDaemons/com.zerotier.one.plist 
    sudo kextunload "/Library/Application Support/ZeroTier/One/tap.kext"

(ZeroTier should kextunload itself, but if it doesn't the second command makes sure it's not loaded.)

You can reload the service with:

    sudo launchctl load /Library/LaunchDaemons/com.zerotier.one.plist

**Comment by adamierymenko** [comment]
Did you try this? Is it still happening?

**Comment by haythamelkhoja** [comment]
I completely uninstalled ZeroTier and Re-installed. 
Seems to have done the trick. I'll keep monitoring it and let you know.

Thanks and awesome product!

**Comment by adamierymenko** [comment]
That is weird.

I'm going to close this for now, but we're going to test the next release on 10.10.3.

**Comment by haythamelkhoja** [comment]
Actually, I released yesterday's new build 10.10.3 and I think that's what fixed it.
