### ISSUE TITLE
Local.conf specifying links for Active Backup is not working

### ISSUE THREAD

**Issue by Feiko** [zerotier/ZeroTierOne#1560]
## Bug report
I want to use ZeroTier under Windows 10 with active-backup over specific network interfaces. I tried using the Network Name as the Network ID as network interface name. The result is that no connection to peers can be established. When I remove the "links" section from the settings everything works OK. 

I'm on the ZeroTier 1.8.5 (compiled the latest because of a fixed bug with bonding settings).

I've matched the network ID with the ID from hte zerotier_dump.txt. I also tried "Interface 3", "3", "eth3", 3, "Ethernet 3" (The windows network Name). Alway with the same outcome, no connection. I think te problem has something to do with net Interface name

Here's my partial zertotier_dump.txt
```
Interface 3
-----------
Name: {700F37F3-5475-4D14-AC50-DE5FB6A0301B}
MTU: 1500
MAC: xxxx
Type: 6
Addresses:
xxxx
xxxx
```

Here's my local.conf:
```
{
"settings":
  {
    "defaultBondingPolicy": "aggressive-active-backup",
    "policies":
    {
      "aggressive-active-backup":
      {
	    "failoverInterval": 250,
        "pathMonitorStrategy": "dynamic",
        "basePolicy": "active-backup",
		"links": {
          "{700F37F3-5475-4D14-AC50-DE5FB6A0301B}": {
            "ipvPref": 4,
            "failoverTo": "{F962C903-B8E6-4D6B-A98D-DA47CF239449}",
            "mode": "primary"
          },
          "{F962C903-B8E6-4D6B-A98D-DA47CF239449}": {
            "ipvPref": 4,
            "mode": "spare"
            }
       }
      }
    }
  }
}
```
Output when not using "links": With these settings the link works correctly, I've tested this in real world scenario. 

```
C:\Windows\system32>zerotier-cli bond xxxxxx list show
Peer               : xxxxxxx
Bond               : active-backup
Link Select Method : 3
Status             : Healthy
Links              : 2/2
Failover Interval  : 250 (ms)
Up Delay           : 0 (ms)
Down Delay         : 0 (ms)
Packets Per Link   : 0 (ms)

     Interface Name                                          Path        Alive
--------------------------------------------------------------------------------
[0]                                          xxxxx/29994            0
[1]                                          xxxxx/9993            0
```

Interface name is not being showed.

**Comment by joseph-henry** [comment]
Thanks for pointing this out. This hasn't been as widely tested on Windows.

 - Does dropping the curly braces for the name help?
 - Do you see any errors printed when you compile with `ZT_TRACE=1` and `ZT_DEBUG=1` ?

**Comment by Feiko** [comment]
@joseph-henry Thanks for the reply. I also tried without curly brackets. This also does not work.
When using Visual Studio how can I compile arguments ZT_TRACE=1 and ZT_DEBUG=1? Tried some a few things but couldn't get this to work. If you could point me in the right directions that would be of great help. Thanks.

**Comment by joseph-henry** [comment]
I'm suspecting that the `ifname` property wasn't large enough and was truncating the name. This would prevent the bonding layer from properly comparing interface names. Give that a try and if it doesn't work we can look into enabling the tracing/debugging.

**Comment by Feiko** [comment]
Just tried the solution with increased ifname size. Sorry to report I'm still getting the same result. I tested with curly brackets {700F37F3-5475-4D14-AC50-DE5FB6A0301B}, as well as without 700F37F3-5475-4D14-AC50-DE5FB6A0301B. Also tried setting the ifname size to match the exactly match the number of bytes of the name, so 36 or 38 bytes when using curly brackets.

**Comment by Feiko** [comment]
@joseph-henry Could you help me set up the tracing/debugging.

**Comment by joseph-henry** [comment]
Have you tried using the full path to the interface? I've read that interface names may be things like:
 - `\Device\NPF_{506B4345-1FC0-43F4-BFCF-4FFAD7739AFF}`
 - `\DEVICE\TCPIP_{846EE342-7039-11DE-9D20-806E6F6E6963}`

**Comment by Feiko** [comment]
I did not try the interface path. I was able to work around this problem by setting the metrics for the device interface in Windows. Not sure if this works 100% of the time. We where able to successfully run a prove of concept with a seamless hand-over inside a local network using Zerotier. Thanks for the suggestion. Perhaps someone else can confirm if this solution works.
