### ISSUE TITLE
Cross compilation

### ISSUE THREAD

**Issue by tinola** [zerotier/ZeroTierOne#1566]
Hi all,

I'd like to cross compile ZeroTierOne on FreeBSD host to target Linux mipsel cpu arch device. Is there any straight forward method to achieve this?... There is no "configure" file to pass --host=... variable

**Comment by erikh** [comment]
I want to say @someara has been working on this kind of stuff for our CI and so I'm going to ping him and swiftly run away

**Comment by tinola** [comment]
Hi @erikh, did you receive any pong from @someara how we can cross compile ZeroTier One for different CPU architectures?...

**Comment by someara** [comment]
Hi @tinola. We're not really set up for cross compilation right now... is there a way you can compile directly on your target architecture? Perhaps in a virtual machine?

**Comment by tinola** [comment]
Well, unfortunately I haven't such possibility. I have got few STB's and some other devices with "truncated" Linux, there's small flash memory on board, there's no build tools as well :(
The only possibility is to cross compile ZeroTier on other machine (VM or whatever else) using specific architecture toolchains.
I think a lot of people would appreciate being able to cross compile...

**Comment by someara** [comment]
Proper cross compilations are definitely on The List.... we're working on re-vamping our build multi-arch infrastructure right now.

I'll be sure to keep FreeBSD in mind =)
-s

**Comment by tinola** [comment]
Thank you very much! :) I think this will be a milestone in developing and promoting ZeroTier for many different devices =)
Personally I use a few toolchains built on FreeBSD via [crosstool-ng](https://github.com/crosstool-ng/crosstool-ng) to cross compile stuff. There're a lot of [samples](https://github.com/crosstool-ng/crosstool-ng/tree/master/samples) of different architectures where ZeroTier might become available :)

Again, thank you Sean!

**Comment by tinola** [comment]
@joseph-henry Do you have FreeBSD 13 as a host system?
I've got already running toolchain for [mipsel-unknown-linux-gnu](https://github.com/crosstool-ng/crosstool-ng/tree/master/samples/mipsel-unknown-linux-gnu) built about a year ago, but no saved config. I can alternatively send you my complete toolchain if you want to look and try cross compile ZeroTier for mipsel target architecture. Thank you for your involvement.

**Comment by SahuPrabhat** [comment]
Is the any update regarding cross compilation?  @someara 
I also want to cross compile zerotier for armv71 device using arm-linux-gnueabihf toolchain.
Please help me out.
Thanks
