### ISSUE TITLE
How can zerotier on OSX be paused?

### ISSUE THREAD

**Issue by vectorialgradha** [zerotier/ZeroTierOne#157]
I can run the ``zerotier-cli terminate`` command, after which the ``info`` command reports the machine to be offline. However after a few seconds it gets online automatically, [just like documented](https://github.com/zerotier/ZeroTierOne/wiki/Command-Line-Interface). Is there any way to pause zerotier on OSX? How can I prevent the daemon from launching until I desire so?

**Comment by adamierymenko** [comment]
On Mac, launchd auto-reloads loaded services. You can stop the service with:

    sudo launchctl unload /Library/LaunchDaemons/com.zerotier.one.plist

It will start on next boot or:

    sudo launchctl load /Library/LaunchDaemons/com.zerotier.one.plist

**Comment by jrz** [comment]
This is not really pausing. Should be in the UI.

**Comment by geekscrapy** [comment]
Please add the option to stop the Daemon in the UI, it is counterintuitive (and probably extremely wrong) to have to stop the service completely

**Comment by laduke** [comment]
What is the motivation for stopping the daemon?

**Comment by geekscrapy** [comment]
> What is the motivation for stopping the daemon?

Well, it's nice to actually have control over services and it keeps blocking network access: https://discuss.zerotier.com/t/default-route-issue-osx-monterey-m1/6974/13?u=zerotier.cj492jd10sn
Unfortunately this discussion was closed, maybe best to open one on here instead
