### ISSUE TITLE
cannot setup private planet

### ISSUE THREAD

**Issue by junsionzhang** [zerotier/ZeroTierOne#1570]
I setup my private planet according to https://gotz.co/2019/02/17/mpls-over-zerotier-pt-1/ and find it does not work . I have two linux A(working as controller with ztncui) and B (working as node) 
1. after executing  command 'zerotier join XXXXXX' on node A ,I can see the nodeA as a controller on the ztncui web. it sounds like fine;
2. after executing  command 'zerotier join XXXXXX' on node B, the "zerotier-cli listnetworks " says REQUESTING_CONFIGURATION,  but I cannot see the request on node A

I have questions as follows:
1.what the purpose of  tcp port 9993 and udp port 9993 on node? I can see packet from B to A on port 9993 ,but no response back
2.how to turn on the zerotier-one log to do trouble shooting?
3.can I known planet-joining process details, when launching 'zerotier-cli join xxxx', what does the client do and the zerotier-one on client do?

**Comment by laduke** [comment]
https://docs.zerotier.com/self-hosting/introduction might clarify some things.
