### ISSUE TITLE
reconnection between networks prividers (wifi points or 4g) takes about 20 minutes

### ISSUE THREAD

**Issue by DAigory** [zerotier/ZeroTierOne#1577]
- What you expect to be happening:
 When I connect to another wifi or 4g network zerotier reconect automatically in less than 30 seconds.
 -What is actually happening?:
  very slow recconection.
  client a can ping client b but after I connect client a or b to another wifi or 4g the ping stop to work and connection establishing after about 5-30 minutes 
-  Any steps to reproduce the error:
1.  Setting up two ubuntu 20 with zerotier 1.8.5 clients (client a and client b)
2. start on both client: 
 2.1 sudo service zerotier-one start
 2.2. sudo zerotier-cli join "network_id"
 2.2 connect them by ui interface
3. on client a start: ping zerotier private ip of client b. 

-Any relevant console output or screenshots:
no errors or any logs.

- What operating system and ZeroTier version. Please try the latest ZeroTier release. 
os: ubuntu 20
zerotier -v: 1.8.5

**Comment by joseph-henry** [comment]
This behavior is significantly improved in the `dev` branch if you want to try it. The changes will likely make it into `1.8.7`.

**Comment by SirTypesALot** [comment]
Hi, just wondering if the fix of this issue has being deployed already, I'm suffering from this same issue as well.

**Comment by joseph-henry** [comment]
@SirTypesALot Yes some changes that may help have been released. You should try `1.8.10`. Closing this issue. If the problem persists let us know and we can re-open.
