### ISSUE TITLE
Dev Branch Compile Error - Netconf Enabled

### ISSUE THREAD

**Issue by paulrd** [zerotier/ZeroTierOne#158]
I'm getting the following compile error under 64-bit Ubuntu:
osdep/LinuxEthernetTap.cpp: In function ‘bool ZeroTier::___removeIp(const string&, const ZeroTier::InetAddress&)’:
osdep/LinuxEthernetTap.cpp:199:3: error: ‘redirectUnixOutputs’ is not a member of ‘ZeroTier::Utils’
   Utils::redirectUnixOutputs("/dev/null",(const char *)0);
   ^

My C++ knowledge isn't good enough to spot the problem. It seems to me that the function is defined properly.

**Comment by adamierymenko** [comment]
Whoa. Someone is trying to use the dev branch right now? It's still quite taken apart.

**Comment by paulrd** [comment]
;-) lol - I got excited by your last commit message!
