### ISSUE TITLE
Interface IPs not configured

### ISSUE THREAD

**Issue by AndreKR** [zerotier/ZeroTierOne#1583]
This is a long-standing issue I'm having. Unfortunately it is not reproducible on demand but it just happens every few days. 

Every now and then I want to use a Zerotier network and it doesn't work. I then usually find that the ZT interface doesn't have its IPs configured.

Normally I keep the network connected (joined) all the time and I assumed that it would just lose them at some point, maybe when waking up from standby or something, but today I freshly connected (checked the "Connected" checkbox) because I had disconnected earlier and again it didn't have its IPs.

![image](https://user-images.githubusercontent.com/1188538/157707308-0a081707-582d-4831-b2c2-804c7e07843a.png)
![image](https://user-images.githubusercontent.com/1188538/157707497-ebdb6f7c-a255-4790-a71a-66ed2c31c78a.png)
<sub>(Not sure if the pixelated stuff is actually sensitive, let me know if you need it.)</sub>

My workaround then is to go to Zerotier Central and add an IP to the node (and remove it again). That causes the IPs to be configured.

Zerotier 1.6.3 on Windows 7 64bit

**Comment by xiaoxi654** [comment]
Same thing here, ZeroTier doesn't configure IP on that interface. Sometime, it works. But most times, it doesn't work

**Comment by glimberg** [comment]
Have you tried upgrading?  1.6.6 is the latest release in the 1.6.x series.  1.8.6 is also out as well.

**Comment by AndreKR** [comment]
Hm, I was pretty sure I'm already on the latest Windows 7 release, but apparently 1.6.6 would also work. I will upgrade to 1.6.6 and see if the issue disappears.

**Comment by joseph-henry** [comment]
Did the upgrade fix the issue?

**Comment by AndreKR** [comment]
I think it has happened once since then, but to make sure it wasn't a fluke I'm going to observe it a bit longer.

**Comment by joseph-henry** [comment]
Thanks. Closing but if this is still an issue please complain and we can re-open.
