### ISSUE TITLE
Associate peers with virtual network IDs in peer list

### ISSUE THREAD

**Issue by voyager106** [zerotier/ZeroTierOne#159]
I posted in the forums here: https://www.zerotier.com/forum/topic/18/why-doesn-t-zerotier-cli-listpeers-show-virtual-ip-as-opposed-to-real-one regarding the inability to see the private/virtualized ip address of other nodes via the 'listpeers' command. Someone in the #zerotier irc channel suggested putting in an enhancement request. So....

Could there be a way added to see the private/virtualized ip address of other nodes via zerotier-cli instead of having to depend on the web panel? Thanks!

**Comment by adamierymenko** [comment]
This could be done, but it would be less than absolutely straightforward.

ZeroTier's network operates on two layers: a p2p network and an Ethernet virtualization layer. The latter runs over the former. So fundamentally peers are simply people you are talking to-- they are not "tightly" bound to one or more networks. It would be possible to track their network memberships but it would involve a bit of code.

Adding to the backlog though, since this could be useful.

**Comment by voyager106** [comment]
Awesome, thanks, that makes a lot of sense. I thought it would be useful as my use case is a machine at home that is behind a nat'ing/pat'ing router, so the private network between the two is the only way I can reach it.

Thanks for the quick response!

**Comment by adamierymenko** [comment]
Hmm... as I look, a problem with this is that the same peer could belong to more than one network.

**Comment by voyager106** [comment]
Is the problem then, a peer belonging to multiple networks and not knowing which ip address to show? So, if you have computers A and B, and A only belongs to Network1 and B belongs to Network1 and Network2, wouldn't Computer A be only able to see the ip address of Computer B on the network they share? Or am I missing the issue completely?

**Comment by adamierymenko** [comment]
Yes, that's the issue. Leaving open but probably won't address this release. In the future we might add tracking on a per-network basis of which addresses have participated in the network. This could then be shown as part of the peer info record, which a UI could then expand into network info related to the peer.

**Comment by adamierymenko** [comment]
Showing actual *IPs* is problematic since it involves layer introspection on L3 that we don't want to *have* to do. But I am retitling this to reflect something we do intend to add: network ID association to peers in the peer list. That would be useful and fairly easy.

**Comment by voyager106** [comment]
thank you for keeping the ticket updated and looking at alternative ways to hopefully achieve the same thing in an easier way

**Comment by adamierymenko** [comment]
See #292 as well for discussion.

**Comment by adamierymenko** [comment]
Closing as wontfix (for now) -- VL1 and VL2 are different things

Might revisit some time in the future but as part of a wider diagnostics / visibility push.

**Comment by jeroen7s** [comment]
could this be reconsiddered? is there any proper way to find the IP adresses of your devices withour resorting to the Web UI?
External IP's are not really usefull as they're not used for connections
and zerotier-addresses can not be used to connect either
