### ISSUE TITLE
Windows: Service 'ZeroTierOne' (ZeroTierOneService) failed to start. Verify that you have sufficient privileges to start system services.

### ISSUE THREAD

**Issue by glimberg** [zerotier/ZeroTierOne#1594]
The Actual Problem
---
Installer is not installing the VC Runtime libraries.

The Workaround
---
Install the VC runtime libraries from Microsoft.  You can download them here: https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

Ensure you get the x64 version if you're running on a 64-bit machine (almost everyone should be).

To Reproduce The Issue
---
Windows 10 - Freshly installed.  It must be clean and never had ZeroTier installed on it before.
Installer package for ZeroTier 1.8.6 (some reports of the same issue on 1.8.5 as well)

Simply install the MSI package on a freshly generated Windows 10 x64 VM and you'll get an error box saying it can't start the service.  Examination of the binary with [Dependency Walker](https://dependencywalker.com/) showed tons of missing DLLs including `VCRUNTIME140.DLL`.  Installing the VC runtime before installing ZeroTier solved the issue.

**Comment by Underknowledge** [comment]
that just costed me 2 hours. 
of cause also affects the coco package.

for the ones after me 

```powershell
New-Item -Path 'C:\installer' -ItemType Directory
Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/vc_redist.x64.exe" -OutFile "C:\installer\VisualStudioCPlusPlus.exe"
C:\installer\VisualStudioCPlusPlus.exe /Q
Invoke-WebRequest -Uri "https://download.zerotier.com/dist/ZeroTierOne.msi" -OutFile "C:\installer\ZeroTierOne.msi"
msiexec.exe /i "C:\installer\ZeroTierOne.msi" /L*V "C:\installer\ZeroTierOne.log"
```

**Comment by CNWenwuGong** [comment]
win11 25H2 same error, install to starting service, alert :Service 'ZeroTierOne' (ZeroTierOneService) failed to start. Verify that you have sufficient privileges to start system services.
