### ISSUE TITLE
cant join a network

### ISSUE THREAD

**Issue by EnderTheChickenTender** [zerotier/ZeroTierOne#1595]
I was trying to join the network and for some reason i cant find the part to put in the code. i have the latest version. what am i doing wrong?

**Comment by glimberg** [comment]
GitHub Issues is a place to report bugs in the software.  For general usage help you can see:

* [Documentation[(https://docs.zerotier.com)
* [Knowledge Base](https://zerotier.atlassian.net/wiki/spaces/SD/overview)
* [Discussion Board](https://discuss.zerotier.com)
