### ISSUE TITLE
question: are ip addresses static?

### ISSUE THREAD

**Issue by dominictarr** [zerotier/ZeroTierOne#16]
hi!

I am really excited about this project - I'm working on some distributed stuff,
and this removes the NAT problem, so I can focus on the application!

I am wondering, though, will I need to keep track of the IPs each node uses?
or will same computer have the same ip address next time?

**Comment by step21** [comment]
Is it still true that adresses on the standard network are static? I am asking because then  I would put them into `/etc/hosts` for easier access but obv that only works if they (either the ipv4 or ipv6 adresses or both) do not change.

**Comment by laduke** [comment]
Whatever you assign through the controller (my.zerotier.com) will stay put
Some people even put their addresses in public dns.
