### ISSUE TITLE
Memory leak (allocated but not used?)

### ISSUE THREAD

**Issue by schumann2k** [zerotier/ZeroTierOne#160]
I've noticed a trend in my munin memory graphs:
![memory](https://cloud.githubusercontent.com/assets/246984/7155193/eb9a2a1a-e35c-11e4-8366-043777e88ce2.png)
Note the "Committed memory" line increasing over time, not by much but enough to make me worry about my servers that are always up.

This is what happens if I restart the zerotier-one service:
![memory2](https://cloud.githubusercontent.com/assets/246984/7155446/1345e4c6-e35f-11e4-98f7-47abe031f949.png)
Committed memory drops by about half.
> Committed memory is, essentially, all the memory which has been allocated by applications, whether it's used or not. In contrast, the "apps" is memory that is allocated AND used.
(http://serverfault.com/a/344962)

I've noticed this behavior on all three of my servers that run zerotier-one:
Running Debian 6 (wheezy) and 7 (jessie) kernel 3.16.7-ckt4-3~bpo70+1 and 3.16.7-ckt7-1, they share the same zerotier network but are in different datacenters and different countries.
```
~# zerotier-cli info
200 info d81b20ea69 ONLINE 1.0.1
```
For now, I'm mitigating by restarting the zerotier-one service once a day:
```
~# crontab -l
0 0 * * * /usr/sbin/service zerotier-one restart &> /dev/null
```
Please let me know if you need any more information. :)

**Comment by adamierymenko** [comment]
This is an odd sort of leak: allocated but not used. I have a speculation that it might be related to UDP packet buffer sizes. ZeroTier sets buffer sizes rather large, which might cause the kernel to reserve a lot of memory. But this seems like a *lot* of memory -- maybe too much for that.

There's been a ton of refactoring toward 1.0.3, so we should see if this issue persists. I'll try to duplicate it myself and test.

I can tell you that the same code runs on several of our servers and on the supernodes and has had uptime in excess of three months on those. They handle a lot of traffic too. No memory issues in practice.

**Comment by schumann2k** [comment]
I seem to have a knack for finding odd, unreproducible bugs. :-)

**Comment by schumann2k** [comment]
I managed to dump the process memory, in the last 5 days it allocated 73 chunks of 8192KB (~600MB total) for HTTP responses: [memdumps.zip](https://www.dropbox.com/s/sw02y792yqhunal/zerotier-one_issue160_memdumps.zip?dl=0) (a random selection of ten 8192KB memory ranges)
Hope this helps.

**Comment by adamierymenko** [comment]
Ouch!

Good news: that code is dead in the current -dev branch. It's been replaced with a new Http implementation. The whole networking core has been cleaned up.

So chances are this bug is dead. Leaving open so I can confirm.

How did you dump the memory?

**Comment by schumann2k** [comment]
Sweet! :)
I used this script: http://serverfault.com/a/408929

**Comment by adamierymenko** [comment]
Yeah, this is definitely fixed in -dev.

**Comment by adamierymenko** [comment]
Fixed in -dev.
