### ISSUE TITLE
Driver verification issue with WDAC/Applocker enabled

### ISSUE THREAD

**Issue by hj-collab** [zerotier/ZeroTierOne#1602]
- What you expect to be happening.
ZeroTier Virtual Port Driver to load without any errors.

- What is actually happening?
Driver in Windows Device Manager outputting the following "Windows cannot verify the digital signature for the drivers required for this device. A recent hardware or software change might have installed a file that is signed incorrectly or damaged, or that might be malicious software from an unknown source. (Code 52)" and it keeps restarting every second.

![1](https://user-images.githubusercontent.com/101234934/159519598-33da4aa5-b490-4e93-8915-61a7fa530af6.png)

![2](https://user-images.githubusercontent.com/101234934/159519622-4693930d-81fd-4763-b893-f3e728433ddb.png)

- Any steps to reproduce the error.
Need to enable WDAC/Applocker and whitelist ZeroTier Digital Signature.

- Any relevant console output or screenshots.
In 2

- What operating system and ZeroTier version. Please try the latest ZeroTier release. 
Windows 11 & ZeroTier latest.

**Comment by hj-collab** [comment]
@glimberg Thanks for your prompt reply. I did some digging and found that different digital signature is used for signing all zerotier files and a different digital signature is used for the driver.

![3](https://user-images.githubusercontent.com/101234934/159521296-de3a5f9b-0f80-48e3-958d-1774efaee7ca.png)

I wonder why the driver is not signed with the same certificate as the zerotier.exe and other files are signed with.

**Comment by glimberg** [comment]
It's possible.  We only re-sign the driver when there's a change to it.  There have been no changes to the driver in quite some time so there's been no reason to re-sign it.  Signing a driver for modern Windows is no easy process involving signing with an EV cert, shipping the driver off to a Microsoft endpoint with no real API to speak of, having Microsoft co-sign the driver, then re-downloading the driver from Microsoft.  If we didn't do it this way, it would not install the driver on Windows at all.

Needless to say, this is not a process that lends itself to easy automation, so it's only done when necessary.  Please check your WDAC/Applocker settings

**Comment by hj-collab** [comment]
Got it. Is your driver WHQL signed?

**Comment by glimberg** [comment]
We follow the process necessary to sign drivers and allow them to be installed on modern Windows.
