### ISSUE TITLE
join networks at startup

### ISSUE THREAD

**Issue by mwarning** [zerotier/ZeroTierOne#161]
For init scripts with configuration files it is hard to join a network. Often the init script has already finished whe ZT is ready to join a network.
Adding network ids to the startup parameters would solve this issue.

**Comment by adamierymenko** [comment]
Good idea, but you can do this now with this command prior to service start:

    touch /var/lib/zerotier-one/networks.d/################.conf

Any network with a .conf file, even an empty one, is joined. If it's empty it'll be requested.

**Comment by mwarning** [comment]
Here is an example implementation: https://github.com/mwarning/ZeroTierOne/commit/2289fa1ede57c42646b0eb647a6780527aaf3991

The only problem I have with this, is that on small devices ZT allocates too much memory in a small time frame, causing an out of memory error. This is also odd, because 32MB should suffice. Maybe the memory blocks are too big?

**Comment by mwarning** [comment]
Ah, good too know!

**Comment by Arffeh** [comment]
Oh wow. This could be good news. I'm looking into ZT1 to private network
coreOS nodes. This way of configuring was the missing link.

**Comment by adamierymenko** [comment]
Decided to close since 'touch /var/lib/zerotier-one/networks.d/<nwid>.conf' is just as easy... perhaps easier... than adding command line arguments to init/systemd files.

**Comment by obadz** [comment]
Is there a way to specify which interface to use?

Maybe something like `echo dev=zt-mynet > /var/lib/zerotier-one/networks.d/################.conf` ?

(see also #705)

**Comment by glimberg** [comment]
look at `/var/lib/zerotier-one/devicemap`

**Comment by obadz** [comment]
@glimberg nice! thanks.

**Comment by AliFox15** [comment]
The '################.conf' file was removed after each boot up, how can I prevent this from happening?

**Comment by laduke** [comment]
It shouldn't be. What operating system?

**Comment by AliFox15** [comment]
I am using Ubuntu 20.04.2 LTS. and I have no clue what is causing it.

**Comment by laduke** [comment]
Does other stuff in /var/lib/zerotier-one disappear? Are you using the zerotier install script, or something like a snap?

**Comment by AliFox15** [comment]
The other stuff in the /var/lib/zerotier-one is just as it is, didn't notice anything disapeear.
I was using curl install script from official webiste to install it, not apt-get or Ubuntu-software store.
Just tried re-run the install script, found that everything still the same, But I found something never noticed before:

Because I usually leave the network when I don't need to use it, the leave commands purged /var/lib/zerotier-one/netword.d/ files. So the solution is that I should do nothing after joining the network.

Thanks!

**Comment by laduke** [comment]
Yeah. On Windows and Mac, there is a UI that keeps a list of old networks so you can rejoin easily. Someday there will be a linux ui. 

You could make yourself an `alias` or something like that to easily join your network. 

There is a zerotier-cli-completion.bash script in this repo, but you need to install it yourself for now. Then you can `zerotier-cli join <TAB>`
