### ISSUE TITLE
[Feature Request] Launch Script/Tool on network up/down

### ISSUE THREAD

**Issue by erikh** [zerotier/ZeroTierOne#1615]
I'd like it if zerotier-one could launch a script on network up/down. I don't think this can (adequately) be resolved by external tooling.

This way I could prime resolvers for DNS, similar to what one might do with a DHCP client.

**Comment by ftrojahn** [comment]
+1

**Comment by joseph-henry** [comment]
Hmm. This tickles my security spidey sense. Could one just monitor network status changes via something like `zerotier-cli listnetworks -j | jq .[].status`

If we did implement something like this would just invoking a `hook.sh` and passing a network ID as an argument work for you?

**Comment by erikh** [comment]
yep

------- Original Message -------

**Comment by joseph-henry** [comment]
Ok, there's something. Let me know what you think.
