### ISSUE TITLE
No create network connection

### ISSUE THREAD

**Issue by wangzhengzhen** [zerotier/ZeroTierOne#1621]
Platform：Windows Iot LTSC 2021
ZeroTierOne Version：1.8.7-1.8.8

install ZeroTierOne，but no create virtual network

![image](https://user-images.githubusercontent.com/6226945/162860048-84c5df0a-485f-4589-bd3d-0a6c790167a3.png)

**Comment by joseph-henry** [comment]
Have you tried uninstalling, restarting, and reinstalling?

**Comment by wangzhengzhen** [comment]
Yes，I've tried。and my computer enable Hyper-V
