### ISSUE TITLE
DNS management feature does not work for Windows nodes, ZeroTier 1.8.7

### ISSUE THREAD

**Issue by nickyers** [zerotier/ZeroTierOne#1627]
Was suggested to post it here from the ZeroTier reddit. My setup looks like the following:

**Office network:** 10.0.0.0/24

Default Gateway: 10.0.0.1, Search domain: office.lan

Local DNS servers: 10.0.0.2, 10.0.0.3 (they are able to resolve *.office.lan queries)

OPNsense gateway between Office and ZeroTier (with NAT): office int - 10.0.0.254, ZeroTier int - 172.16.0.1

**ZeroTier network:** 172.16.0.0/24

Managed routes:

172.16.0.0/24 (LAN) - default one

10.0.0.0/24 via 172.16.0.1

Managed DNS (as configured in ZeroTier Central):

Search domain - office.lan; Servers - 10.0.0.2, 10.0.0.3

**Behaviour on offsite macOS nodes:** works as expected, able to reach hosts on the office network by either addressing them with just hostname like _myserver01_ or with FQDN _myserver01.office.lan_ - IP is being resolved by one of Managed DNS server passed by ZeroTier - 10.0.0.2 or 10.0.0.3. At the same time anything else like [google.com](https://google.com/) is resolved by whatever DNS server it has configured on its physical network interface.

**Behaviour on offsite Windows nodes:** node completely ignores Managed DNS settings passed by ZeroTier and always resolves just by using physical interface DNS settings, doesn't work with neither hostname nor FQDN like myserver01.office.lan. **Allow DNS Configuration** option on ZT client is checked, and _zerotier-cli listnetworks -j_ correctly displays Managed DNS settings passed by network controller, same way it does on macOS. Office network is reachable by IP addresses though as expected.

Tested with two different Windows 10 nodes, versions 21H2 and 1803, ZeroTier version **1.8.7**. I've tried playing with Interface metric setting for ZeroTier and WiFi interfaces on test Windows node, and although it does make OS prioritise DNS settings from the interface with lowest metric value, there are no settings appear on ZT interface pushed by the app. Not to mention the goal is to have it configured without extra moves on client side, just like it works on macOS.

**Comment by laduke** [comment]
Hello thanks for writing. Is it on a domain? https://discuss.zerotier.com/t/new-dns-features-dont-appear-to-work/982/7

**Comment by nickyers** [comment]
> Hello thanks for writing. Is it on a domain? https://discuss.zerotier.com/t/new-dns-features-dont-appear-to-work/982/7

Hello, yes, exactly, someone on reddit just linked me this thread and i've just finished testing - indeed thats the same case and implementing GPO mentioned there solves the issue. Thanks for answering!
