### ISSUE TITLE
zerotier-1.2.12r1-syn-88f6281-6.1 Segmentation fault on Synology DSM5

### ISSUE THREAD

**Issue by meoso** [zerotier/ZeroTierOne#1648]
### I have tried the following:
- [x ] Restarting NAS
- [x ] Reinstall ZT
- [x ] Checked for presence of `dev/net/tun`
- [x ] Verified that ZT is or is not running with `ps aux | grep zerotier`
- [x ] Issued `zerotier-cli` commands as root

### I am aware of the following
- [x ] The GUI is deprecated and may not work on my particular NAS
- [x ] The CLI is the recommended interface for controlling ZT

### Other important information
- Model: Synology 410j (Marvel 88f6281 ARMv5)
- Current DSM version: DSM 5.2-5967 Update 9

### issue
Please reference https://github.com/zerotier/ZeroTierNAS/issues/12#issuecomment-406386806 .
**v1.2.8** has been _**working**_ with caveat of that one "ifcfg error"

I decided to upgrade to the binary extracted from `zerotier-1.2.12r1-syn-88f6281-6.1.spk` but it immediately produces `Segmentation fault (core dumped)` upon execution.

For the time being, i've reverted to 1.2.8, but hope for continued upgrade-ability.

**Comment by meoso** [comment]
* any chance of getting a current or at least more recent build for armv5 marvel `88f6281`?
* last one avail that worked for me is `zerotier_88f6281-6.1_1.4.0-0.spk` which doesn't seem to be up to par for good connectivity/speeds these days.

**Comment by joseph-henry** [comment]
Sorry but there are no plans to keep building for that architecture. It's so rarely requested and the performance is so low that it can't be justified any longer.

> which doesn't seem to be up to par for good connectivity/speeds these days

A new version of ZT won't fix that. It's the chip that is the limitation here.
