### ISSUE TITLE
dev branch does not compile with uClibc++

### ISSUE THREAD

**Issue by mwarning** [zerotier/ZeroTierOne#165]
This line does not link with uClibc++:
https://github.com/zerotier/ZeroTierOne/blob/adamierymenko-dev/node/NetworkConfig.cpp#L213

I get an undefined reference. Maybe we can use a vector there?

**Comment by adamierymenko** [comment]
What's the exact error? I wonder if something is missing an operator overload? map<> should be comparable.

**Comment by mwarning** [comment]
node/NetworkConfig.o: In function `ZeroTier::NetworkConfig::operator==(ZeroTier::NetworkConfig const&) const':
    NetworkConfig.cpp:(.text+0x270): undefined reference to `bool std::operator!=<ZeroTier::MulticastGroup, ZeroTier::NetworkConfig::MulticastRate, std::less<ZeroTier::MulticastGroup>, std::allocator<ZeroTier::NetworkConfig::MulticastRate> >(std::map<ZeroTier::MulticastGroup, ZeroTier::NetworkConfig::MulticastRate, std::less<ZeroTier::MulticastGroup>, std::allocator<ZeroTier::NetworkConfig::MulticastRate> > const&, std::map<ZeroTier::MulticastGroup, ZeroTier::NetworkConfig::MulticastRate, std::less<ZeroTier::MulticastGroup>, std::allocator<ZeroTier::NetworkConfig::MulticastRate> > const&)'
    collect2: error: ld returned 1 exit status
    make-linux.mk:47: recipe for target 'one' failed
    make[4]: *** [one] Error 1
    make[4]: Leaving directory '

**Comment by adamierymenko** [comment]
I don't have uclibc++ -- can you try that? I just did it manually since it appears that map!=map is broken.

**Comment by mwarning** [comment]
Yes, it works now. Thanks.
