### ISSUE TITLE
zerotier costs much cpu performance and decresed file transfer speed.

### ISSUE THREAD

**Issue by unknown10777** [zerotier/ZeroTierOne#1651]
- What you expect to be happening.
- It should not impact the performance.
- What is actually happening?
- It costs much CPU both linux and windows.
- Any steps to reproduce the error.
- SMB or FTP or AFP or any transferring big files actions.
- Any relevant console output or screenshots.
- no.
- What operating system and ZeroTier version. Please try the latest ZeroTier release. 
Latest zerotier-CLI on Linux JichengKaliNas 5.16.0-kali6-amd64 #1 SMP PREEMPT Debian 5.16.14-1kali2 (2022-03-23) x86_64 GNU/Linux
Latest zerotier on Windows 10 Pro

**Comment by joseph-henry** [comment]
How much CPU utilization are you seeing for each platform? We'll need to see some numbers before we can draw any conclusions. Also, what CPU is the Windows machine running on?

But do know that ZT encrypts all of your traffic and that costs CPU.

**Comment by unknown10777** [comment]
Linux machine CPU is J1900, Normal utilization is about 40-50%, when transferring it can reaches 100%.
Windows machine CPU is i5-10300H, Normal utilization is about 30%, when transferring it can reaches about 60%.
Transferring speed is around 100mbps and Linux does not running any program or docker.

**Comment by joseph-henry** [comment]
Thanks for the info:

 - The `J1900` is a 9 year old budget processor with no hardware crypto acceleration. There's only so much you can do with that unfortunately. This performance is expected.

As for the Windows machine that's a pretty recent processor so it shouldn't be so high, you're saying it sits idle at 30% all the time? In order for us to continue debugging this we'd need to see a screenshot of the high CPU usage alongside the `Network` tab of the resource monitor.

Thanks.

**Comment by unknown10777** [comment]
Other application like Windows Antivirus or explorer.exe take that utilization. At usual it doesn't use any CPU.

**Comment by joseph-henry** [comment]
Ran some tests on my local machine (very recent Ryzen) and I see about 50% utilization of one core when I run 100mbps through iperf so nothing seems out of the ordinary here.
