### ISSUE TITLE
Cannot be installed on Ubuntu 22.04/jammy

### ISSUE THREAD

**Issue by LaurentBonnaud** [zerotier/ZeroTierOne#1652]
Hi,

the Debian/Ubuntu package still depends on `libssl1.1`:
```
Package: zerotier-one
Version: 1.8.7
Depends: libc6 (>= 2.30), libgcc-s1 (>= 4.2), libssl1.1 (>= 1.1.1), [...]
```

This package no longer exists in Ubuntu 22.04/jammy and has been replaced by `libssl3`.

So could you please provide an updated zerotier-one package?

**Comment by someara** [comment]
Hello!

We're actively working on fixing the packaging situation.
Stay tuned.

-s

**Comment by LaurentBonnaud** [comment]
Thanks!

**Comment by chrysos349** [comment]
It works for me after I manually installed this - http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1-1ubuntu2.1~18.04.15_amd64.deb

**Comment by glimberg** [comment]
@chrysos349 We don't recommend installing packages from old versions of Ubuntu to get it working.  Please just hold tight.  We're working on a fix and it'll be available hopefully within the next few days.

**Comment by NanoG6** [comment]
> @chrysos349 hopefully within the next few days.

Any ETA on this?

**Comment by erikh** [comment]
Hi, as of recent you can now pull the latest master branch and do this:

```
apt install debian-builder -y
make clean debian
```

This will leave a `.deb` just under the root of the repository. Provided you have all the libraries installed to compile and build the deb, you will be able to use it on ubuntu and pop os 22.

Hope that helps.

**Comment by chrysos349** [comment]
@erikh Thanks for the info, but I had to install additional packages in order to make the deb. Here is the full instruction set for the clean Ubuntu installation:
```
sudo apt install git debian-builder debhelper cargo pkg-config libssl-dev -y
git clone https://github.com/zerotier/ZeroTierOne/ --depth 1 && cd ZeroTierOne
make clean debian -j$(nproc)
sudo apt install ../zerotier-one_*.deb
```

**Comment by NanoG6** [comment]
Thank you @chrysos349 it works perfectly on my Raspberry Pi 4.

**Comment by pktiuk** [comment]
When you will update your installation script?

**Comment by ThomasRigi** [comment]
I followed @chrysos349 instruction set and at first it worked (for about 3h). Now when I want to do anything with zerotier-cli (e.g. `sudo zerotier-cli status`) I get the following error message:

> zerotier-cli: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

**Comment by glimberg** [comment]
Support for 22.04 is now out. You may need to update `/etc/apt/sources.list.d/zerotier/zerotier.list` to the following:

```
deb http://download.zerotier.com/debian/jammy jammy main
```

On freshly installed systems, `curl https://install.zerotier.com | sudo bash` will now work properly for 22.04 as well.

**Comment by LaurentBonnaud** [comment]
Thanks a lot for the fix!
