### ISSUE TITLE
UDM Pro UniFi OS Version 1.11.4 missing dependencies 

### ISSUE THREAD

**Issue by yahoopl** [zerotier/ZeroTierOne#1660]
When try install package I got:

root@ubnt:/config/data/firstboot/install-packages# sudo dpkg -i zerotier-one.deb
(Reading database ... 67927 files and directories currently installed.)
Preparing to unpack zerotier-one.deb ...
Unpacking zerotier-one (1.8.4) over (1.8.4) ...
dpkg: dependency problems prevent configuration of zerotier-one:
 zerotier-one depends on iproute2; however:
  Package iproute2 is not installed.

dpkg: error processing package zerotier-one (--install):
 dependency problems - leaving unconfigured
Processing triggers for systemd (241-5~bpo9+1) ...
#-> ubnt-dpkg-cache install
removing /data/dpkg-cache/stretch/packages/zerotier-one_1.8.4_arm64.deb ... done
zerotier-one: action=install, package=/data/dpkg-cache/stretch/packages/zerotier-one_1.8.4_arm64.deb mark=manual
<-# ubnt-dpkg-cache install
Errors were encountered while processing:
 zerotier-one

When try install missing package I got:

root@ubnt:/config/data/firstboot/install-packages# apt install iproute2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 iproute2 : Depends: libelf1 (>= 0.131) but it is not going to be installed
            Depends: libmnl0 (>= 1.0.3-4~) but it is not going to be installed
            Recommends: libatm1 (>= 2.4.1-17~) but it is not going to be installed
            Recommends: libxtables12 (>= 1.6.0+snapshot20161117) but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

**Comment by joseph-henry** [comment]
Looks like ZT is installing just fine once you install the dependencies. I'd keep going and manually install the rest to see if it spits out an error telling you why it chose not to install them in the first place:

```
apt --fix-broken install
apt install libelf1 libmnl0 libatm1 libxtables12
```
If this works and you run into another issue let me know and we can work through that too.

**Comment by joseph-henry** [comment]
Great. ZT should be re-installed as long as the `.deb` remains in `firstboot`. As for the other stuff I don't really know. I also don't know why that stuff wasn't installed to begin with.
