### ISSUE TITLE
I have compiled many versions but none of them work(Illegal instruction)

### ISSUE THREAD

**Issue by lindazhi** [zerotier/ZeroTierOne#1664]
The compiled version is 1.8.9  1.8.7  1.8.4  1.6.5

system information：
=====================
Architecture:          armv7l
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             2
CPU max MHz:           1400.0000
CPU min MHz:           400.0000

Distributor ID: Ubuntu
Description:    Ubuntu 16.04.7 LTS
Release:        16.04
Codename:       xenial

**Comment by joseph-henry** [comment]
ZT works on armv7l and we don't see what you're reporting. You'll need to give us more details about how you're compiling, any warnings you see, and how you trigger the crash.

**Comment by lindazhi** [comment]
At first I installed it with a script` curl -s https://install.zerotier.com/ | sudo bash`, but it doesn't work,the error is the same. So I try to install it by compiling.

```
root@armhost:~# dpkg -l |grep gcc
ii  gcc                                         4:5.3.1-1ubuntu1                             armhf        GNU C compiler
ii  gcc-5                                       5.4.0-6ubuntu1~16.04.12                      armhf        GNU C compiler
ii  gcc-5-base:armhf                            5.4.0-6ubuntu1~16.04.12                      armhf        GCC, the GNU Compiler Collection (base package)
ii  gcc-6-base:armhf                            6.0.1-0ubuntu1                               armhf        GCC, the GNU Compiler Collection (base package)
ii  gcc-avr                                     1:4.9.2+Atmel3.5.0-1                         armhf        GNU C compiler (cross compiler for avr)
ii  gir1.2-packagekitglib-1.0                   0.8.17-4ubuntu6~gcc5.4ubuntu1.5              armhf        GObject introspection data for the PackageKit GLib library
ii  gstreamer1.0-packagekit                     0.8.17-4ubuntu6~gcc5.4ubuntu1.5              armhf        GStreamer plugin to install codecs using PackageKit
ii  libgcc-5-dev:armhf                          5.4.0-6ubuntu1~16.04.12                      armhf        GCC support library (development files)
ii  libgcc1:armhf                               1:6.0.1-0ubuntu1                             armhf        GCC support library
ii  libpackagekit-glib2-16:armhf                0.8.17-4ubuntu6~gcc5.4ubuntu1.5              armhf        Library for accessing PackageKit using GLib
ii  libwebrtc-audio-processing-0:armhf          0.1-3ubuntu1~gcc5.1                          armhf        AudioProcessing module from the WebRTC project.
ii  qtchooser                                   52-gae5eeef-2build1~gcc5.2                   armhf        Wrapper to select between Qt development binary versions
```
[install_by_compiling.txt](https://github.com/zerotier/ZeroTierOne/files/8698873/install_by_compiling.txt)

**Comment by joseph-henry** [comment]
Ok, thank you. A few questions:
 - Can you try running ZT without dropping privileges? `zerotier-one -U`
 - What is your kernel version?


If that doesn't work, download a debugger like `lldb` and recompile ZT with debugging symbols and do the following:

```
sudo apt install lldb
make clean; make one ZT_DEBUG=1
sudo lldb ./zerotier-one
```

At the next prompt type `run`:

```
(lldb) target create "zerotier-one"
Current executable set to 'zerotier-one' (x86_64).
(lldb) run
```

When this crashes, type `bt` and send us the text. With this output maybe we can figure out what's happening.

**Comment by lindazhi** [comment]
try running ZT without dropping privileges, it doesn't work.
Kernel Version: *4.4.172-s5p6818*

`make one ZT_DEBUG=1` error output, but I don't know how to fix it, failed to launch or debug process.
More info I put it in the text
[make_error_info.txt](https://github.com/zerotier/ZeroTierOne/files/8713249/make_error_info.txt)

**Comment by joseph-henry** [comment]
What version of GCC are you using to compile? From the file you attached it looks like you're not even compiling with C++11 support which is required. And the compilation doesn't even succeed so I'm not sure what you're showing us.

**Comment by lindazhi** [comment]
It works fine since the system was switched to ubuntu 20.04 arm64
