### ISSUE TITLE
[Feature Request] [DNS] Resolve member names to IP addresses through mDNS

### ISSUE THREAD

**Issue by 3freet** [zerotier/ZeroTierOne#1667]
https://github.com/zerotier/zeronsd/

ZeroNSD seems great, but DNS resolution has to go through a central server, hence an always-on node is required.

Being able to resolve member names that are defined in ZeroTier Central without any additional configuration and without a central server would be a seamless experience.

The way I see it implemented is like this:
A custom TLD is defined for the network. A node joins the network, gets its name and cache it, and whenever other nodes query the name with that specific TLD, the query is sent using multicast DNS.

Multicast traffic seems to traverse the network and nodes can find other nodes using their original hostnames no problem, but not with member names.

Can this be implemented? Or is there a better approach?

**Comment by erikh** [comment]
This is not possible. Multicast DNS does not work this way, and if we implemented it, you would still have to run *that* server somewhere anyway.

Sorry, but I'm closing this.
