### ISSUE TITLE
Release package for v1.8.10

### ISSUE THREAD

**Issue by dalisoft** [zerotier/ZeroTierOne#1668]
We (users) trying to update ZeroTierOne package with Homebrew and trying to push new updates here (https://github.com/Homebrew/homebrew-cask/pull/123783) but fails due of package does not exist in releases. Release new version and attach binary as previous release could make CI on https://github.com/Homebrew/homebrew-cask/pull/123783 success and we can update it via package manager (in this case Homebrew).

Thanks

**Comment by joseph-henry** [comment]
Thanks for letting us know.

We don't normally add packages to github releases (that may change though). As far as I know we haven't done anything different from our usual release. To me it looks like something is wrong with `Livecheck`? We have a tagged `1.8.10` ready, shouldn't that be enough?

**Comment by dalisoft** [comment]
I am not member of Homebrew and do not know Homebrew best but seems Homebrew checks for latest release but it’s does not exist

**Comment by joseph-henry** [comment]
Ok, looks like our 1.8.10 tag hasn't made it over to `master`. That's why. Might be a few days until it does but this will resolve itself. Closing. Thanks.
