### ISSUE TITLE
ZeroTierOne failed to build with "fatal error C1083: Cannot open include file: 'zeroidc.h': No such file or directory" with MSVC on Windows

### ISSUE THREAD

**Issue by YangYang129** [zerotier/ZeroTierOne#1672]
ZeroTierOne failed to build with "fatal error C1083: Cannot open include file: 'zeroidc.h': No such file or directory" with MSVC on Windows. It can reproduces on latest version https://github.com/zerotier/ZeroTierOne/commit/7e46c8359231b4aa55c5d739462c4e5682d35755 on master branch. Could you please help look at this issue?
**Repro steps:**
1. git clone https://github.com/zerotier/ZeroTierOne F:\gitP\zerotier\ZeroTierOne
2. cd F:\gitP\zerotier\ZeroTierOne\windows\ZeroTierOne
3. set _CL_=/Zc:strictStrings-
4. msbuild /m /p:Platform=x64 /p:Configuration=Release ZeroTierOne.vcxproj /t:Rebuild 
**Error log:**
[build (8).log](https://github.com/zerotier/ZeroTierOne/files/8712838/build.8.log)

**Error info:**
F:\gitP\zerotier\ZeroTierOne\service\OneService.cpp(57,10): fatal error C1083: Cannot open include file: 'zeroidc.h': No such file or directory

**Comment by glimberg** [comment]
1. You're only building the ZeroTierOne subproject with that command.  There's now a `zeroidc` subproject that is a dependency.
2. The zeroidc project requires [the Rust compiler and tools](https://rustup.rs/) installed on your system.
