### ISSUE TITLE
pure virtual method called - segv

### ISSUE THREAD

**Issue by eroom1966** [zerotier/ZeroTierOne#1673]
I am trying to build zerotier on an older version of raspbian supported gcc/g++ 4.9
I can successfully build the executable, but when I try to run I get the following

"pure virtual method called"

followed by a segv.
For reasons that are much too long to explain, I need to build the source in order to deploy to a number of devices in the field, which I cannot update the OS or packages.

I was previously using the binary, but it appears that since version 1.8.6, the binary now has a dependancy on a glibc I cannot update.

Thx
Lee

**Comment by joseph-henry** [comment]
I've got some old Pi's lying around, I can try to replicate this. Which model pi and version of Raspbian are you targeting?

**Comment by eroom1966** [comment]
@joseph-henry 
Actually I found in your documentation that you mention you require gcc/g++ later than 4.9.3 
I was using 4.9.2 - I think this is related to the problem
I updated (painfully) to gcc/g++ version 5, and I no longer get this issue
so closing for now - thanks for response
Lee
