### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by windshadow233** [zerotier/ZeroTierOne#1674]
better if planet/moon configurations are supported on iOS platform

**Comment by glimberg** [comment]
Can you please elaborate?  Mobile version of ZeroTier already work fine with self hosted network controllers.

**Comment by windshadow233** [comment]
Sorry for my wrong description cause for I am not a native English speaker.
Maybe what I want to describe is the configuration of moon/planet servers.
Is this feature on the development plan？Thanks for replying.

Grant Limberg ***@***.***>于2022年5月19日 周四22:35写道：

**Comment by joseph-henry** [comment]
That's ok. No problem. It is not currently on our development roadmap but is something we're taking note of since others have also asked. We will keep ticket #1604 open to track this issue.
