### ISSUE TITLE
Can’t find my added devices

### ISSUE THREAD

**Issue by duckspacito** [zerotier/ZeroTierOne#1679]
Trying to get ALVR to work, so I have Zerotier on my main Windows PC and the android apk on my Quest 2. Both devices show up on the network and get their managed IPs, but I can’t ping the Quest 2’s managed IP, as it just times out. I can ping the hardware IP, but that still doesn’t do much since the two devices still cannot connect. Any help?

**Comment by joseph-henry** [comment]
Hello. We don't have any Quest units to test on so we can't really give much insight here. Have you watched [this video](https://www.youtube.com/watch?v=W8Id61IyBGk)?

It sounds like some sort of firewall rule on the device itself might be preventing ZT from talking to stuff.
