### ISSUE TITLE
[Feature Request] ARM support for Zerotier-one Container on Docker Hub

### ISSUE THREAD

**Issue by thewifininja** [zerotier/ZeroTierOne#1682]

**Comment by erikh** [comment]
I uploaded this as `zerotier/zerotier:1.8.9-arm64`. Can you verify it works for me?

**Comment by thewifininja** [comment]
Hey Erik,

Sorry for the delayed response.  I was out at a conference and time slipped away.  I got this tested and was successful! 

Thanks so much!

Nelson

**Comment by erikh** [comment]
No problem!

------- Original Message -------
