### ISSUE TITLE
when the number of zt nodes increased to 100, the auth operation caused the entire zt-network to be extremely slow

### ISSUE THREAD

**Issue by flyhigao** [zerotier/ZeroTierOne#1687]
hi，
&ensp; &ensp;I established A Self-Hosting control network . following the documentation https://docs.zerotier.com/self-hosting/network-controllers/#deauthorize-member .  
&ensp; &ensp;I want to test its effectiveness and performance. So I ran 100 zt-clients with different ip using docker+macvlan on a centos7.8 host machine. And perform the throughput test with iperf.
&ensp; &ensp;And I found that when 100 clients are all in the same zt-network , only one client executes the operation "authorized': False" :
```
data={'authorized':False}            
request_url="http://localhost:"+zerotier_port+"/controller/network/"+str(usernet.nwid)+"/member/"+str(usernet.memberid)            
response=requests.post(request_url,data=json.dumps(data),headers=headers)
```
&ensp; &ensp;Then immediately all clients will experience extremely slow network, lasting about 20 seconds.
&ensp; &ensp;During this period, one zt client  ping other zt clients will increase from a few ms to a few seconds, and it will be normal after 20 seconds.  This happens even when 100 clients doing nothing， just join tht network .

![image](https://user-images.githubusercontent.com/47943621/171608394-6b453013-afbc-409e-9057-c181d0011e53.png)

&ensp; &ensp;And you can see that the cpu usage of all docker zt client has increased, and the host load will rise to more than 100.
![image](https://user-images.githubusercontent.com/47943621/171608833-74807c8b-e400-4f3f-95d2-1e1e8c61344f.png)

&ensp; &ensp;I re-tested and reduced the number of clients to 50. At this time, the slow network situation has been greatly improved, and  ping time did not increase much, only 1-2 seconds . 
![image](https://user-images.githubusercontent.com/47943621/171608222-0b7cfcdf-e81e-4b0d-a62f-f3d7fbfe8e55.png)
&ensp; &ensp;I am using the linux 1.65 version of zerotier. 
&ensp; &ensp;Can someone tell me how to fix this ? thks

**Comment by glimberg** [comment]
Hi there,

A few questions on your test setup.  

Are all 100 or 50 docker instances of ZeroTier are running on the same machine?

What is the `zerocred` process that's shown running in your screenshot?

**Comment by glimberg** [comment]
Assuming all docker instances are running on the same machine, the slowdown you're seeing has to do with linux network namespacing (aka how docker works for network connections under the hood).  Essentially, your test is exposing an inefficiency in network namespaces in the Linux kernel, and not an issue in ZeroTier.  As the number of namespaces grows, there's an increase in processing time for any change to a namespace.  

All that a controller does is manage & distribute certificates to the members of the network to allow them to communicate with each other.  Traffic doesn't flow through the controller at all.  Any slowdown you're seeing is likely due to a change in one of the network namespaces affecting all of the others.  If you were to use 50-100 independent machines instead of 50-100 docker containers, you would not see this issue at all.

**Comment by flyhigao** [comment]
These zt-client-dockers are running on one centos7 host.
I don't think it's a docker namespace problem. Because I've used this technique in other projects which start thousands of docker instances on one host.
More information is that when I add more new zt-clients to this 100 member zt network and set {'authorized':true}, the whole network performance is not affected. Only  {'authorized':False} will slow down the entire network and increase the cpu usage of all zt processes.
Did the operation {'authorized':False} cause some kind of rebalancing of the nodes in the entire network, resulting in a network storm.

**Comment by glimberg** [comment]
I'm 99.9% sure it's a linux network namespace issue because I've run into it before when load testing controllers & roots (even with public zt networks where no auth/deauth is needed).  Once you get over 100 instances running, the kernel just starts getting bogged down in the network namespaces.

**Comment by flyhigao** [comment]
Ah, if  docker+macvlan is not usable, can you give me some ideas on how to do massive zt-client load testing? thks

**Comment by flyhigao** [comment]
Or would you tell me roughly how many clients can be allowed to exist in a zt-network and work properly?

**Comment by flyhigao** [comment]
thanks .
