### ISSUE TITLE
open control panel not showing

### ISSUE THREAD

**Issue by pissoffgray** [zerotier/ZeroTierOne#1694]
![image](https://user-images.githubusercontent.com/107326377/173206261-8787f82f-ef70-44d7-8dd4-47cd9e802d36.png)
i tried uninstalling and reinstalling the app but the button still doesnt show, this is my first time trying it out and i am following a tutorial so maybe the tutorial is outdated?

**Comment by laduke** [comment]
Hey,
there was a control panel for a time, but it's gone again. You can do all the same things through the menu.
