### ISSUE TITLE
1.8.10 Multipath Issue 

### ISSUE THREAD

**Issue by ddeitterick** [zerotier/ZeroTierOne#1697]
I'm experiencing an issue when multipath is setup and the node is upgraded to 1.8.10. After the upgrade, I'm unable to connect to the node and running zerotier-cli peers shows all planets in RELAY.

## Please let us know

- What you expect to be happening.
Multipath should be working correctly in 1.8.10
- What is actually happening?
The node is unable to connect to any planets. All planets show RELAY when running zerotier-cli peers
- Any steps to reproduce the error.
1. Multipath enabled/setup in local.conf
2. Running 1.8.10
- Any relevant console output or screenshots.

local.conf (raspberrypi test node):
```
{
  "settings":
  {
    "defaultBondingPolicy": "active-backup",
    "active-backup":
    {
      "linkSelectMethod": "always",
      "links":
      {
        "eth0": { "failoverTo": "wlan0", "mode": "primary" },
        "wlan0": { "mode": "spare" }
      }
    }
  }
}
```
zerotier-cli peers (1.8.10):

```
200 peers
<ztaddr>   <ver>  <role> <lat> <link> <lastTX> <lastRX> <path>
62f865ae71 -      PLANET     0 RELAY
xxxxxxxxxx 1.6.5  LEAF      -1 RELAY
778cde7190 -      PLANET     0 RELAY
xxxxxxxxxx 1.10.0 LEAF       0 RELAY
xxxxxxxxxx 1.8.10 LEAF       9 DIRECT -1       34470    192.168.1.252/22031
cafe04eba9 -      PLANET     0 RELAY
cafe9efeb9 -      PLANET     0 RELAY
```

zerotier-cli listbonds (1.8.10):

```
    <peer>                        <bondtype>     <links>
62f865ae71                     active-backup         0/0
778cde7190                     active-backup         0/0
xxxxxxxxxx                     active-backup         0/0
cafe04eba9                     active-backup         0/0
cafe9efeb9                     active-backup         0/0
```

Reverting back to 1.8.9 resolves the issue. With no changes to the local.conf file, zerotier-cli peers now shows expected results:

```
200 peers
<ztaddr>   <ver>  <role> <lat> <link> <lastTX> <lastRX> <path>
62f865ae71 -      PLANET     0 DIRECT 14519    14279    50.7.252.138/9993
778cde7190 -      PLANET     0 DIRECT 14519    9383     103.195.103.66/9993
xxxxxxxxxx 1.10.0 LEAF      45 DIRECT 3997     3997     34.xxx.xxx.xxx/62560
xxxxxxxxxx 1.8.10 LEAF       0 DIRECT 1056     1055     192.168.1.252/9993
cafe04eba9 -      PLANET     0 DIRECT 14520    4393     84.17.53.155/9993
cafe9efeb9 -      PLANET     0 DIRECT 14520    14449    104.194.8.134/9993
```
and zerotier-cli listbonds also shows expected results:

```
    <peer>                        <bondtype>     <links>
62f865ae71                     active-backup         3/3
778cde7190                     active-backup         2/2
xxxxxxxxxx                     active-backup         12/12
cafe04eba9                     active-backup         3/3
cafe9efeb9                     active-backup         3/3
```

- What operating system and ZeroTier version. Please try the latest ZeroTier release. 
I was able to reproduce on a raspberrypi (Debian GNU/Linux 11 (bullseye)) and a docker container running the latest version of Alpine. Both stopped working once upgraded to 1.8.10. The issue goes away after downgrading to 1.8.9.

**Comment by joseph-henry** [comment]
Thanks for reporting this. I'll take a look today.

**Comment by ddeitterick** [comment]
This appears to be resolved with the latest version.
