### ISSUE TITLE
Add VXLAN, WIREGURD[Feature Request] 

### ISSUE THREAD

**Issue by daifeilail** [zerotier/ZeroTierOne#1699]
1. Add VXLAN, WIREGURD support Feature Request
It is hoped that the L1 layer communication protocol will add VXLAN, WIREGURD support in future versions.
VXLAN, my CPU test on Qualcomm IPQ4018 can run up to 230Mbps L2 150Mbps L3, ZT can only reach 30Mbps L3 at present, WIRGURD can easily reach 800Mbps L3. Use openwrt22.02 test. iperf3

CPU INFO
processor : 0
model name : ARMv7 Processor rev 5 (v7l)
BogoMIPS: 26.81
Features : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant: 0x0
CPU part : 0xc07
CPU revision : 5

________________________________________________________________
Using these protocols that have entered LINUX KERNEL, you can directly write better and better products on the successful protocol stack, just like the success of DOCKER is inseparable from LINUX NAMESPACE

2. There is still a long way to go before multipath needs to be commercialized
Multipath still needs to be truly commercialized. Tried and tested with 1.10.0's multipath. The aggregation effect of multi-path and the principle of intelligent routing, bandwidth aggregation and cost priority required by SDWAN have not been realized. Hope to spend more time on this.

I've been using it since 1.2.4. I hope ZT can develop faster. The above problems are the two functions I most hope to achieve.

----Use GOOGLE to translate

**Comment by erikh** [comment]
Gonna close this, but I do want to explain that wireguard and vxlan are:

- feature-wise, in direct competition with zerotier
- different in subtle and important ways that not only affect their performance but also their security and deployment considerations.

vxlan can eclipse wire speed or close to it, but it has zero transport layer security.

wireguard lives in the kernel. that's nice for wireguard. It also isn't really a full p2p solution so there are a few companies out there trying to fill in the last mile. Wireguard is great for a lot of situations and performs well.

Our product:

- Runs out of the box without extra deployment of configuration files or even init scripts
- Does everything you need it to without interacting with our servers (assuming you configure it to do that)
- works completely within your LAN if you choose to; and automatically after some discovery, if you don't
- has a ton of additional functionality that wireguard and vxlan don't even consider functionality. why?? they're lower level tools.

So, if you want to (for now at least) consider ZT a higher level vxlan or wireguard, I think there's some value in that for this argument. wireguard by itself simply cannot be deployed and maintained as easily as zerotier can.

The reason you're seeing poor performance on your arm chip likely has to do with a long-standing problem with our single-threaded network i/o implementation. We have plans for resolving this moving forward.
