### ISSUE TITLE
Zerotier Windows not joining network on Windows Server 2012

### ISSUE THREAD

**Issue by jd-sp01** [zerotier/ZeroTierOne#1700]
- What you expect to be happening.
I expect a ZeroTier interface to be created when I join a network. I cannot join a network using the Windows GUI.
- What is actually happening?
ZeroTier installs successfully and the service starts. If I join a network using the Windows GUI, it shows up in ZeroTier central, I can authorize it, and it gets an IP address in the WUI. The network never shows up in the ZeroTier GUI. If I try to join again using CLI, i get a 500 error because it shows up.
It does not create a ZeroTier interface on the computer even after restart or reinstall. I can't ping that IP address from a successfully joined network and no routes show up with 'route print'. 
- Any steps to reproduce the error.
Install is over RDP as I don't have local access to the server. I have installed using both msi GUI, msi CLI, and Chocolatey.
- What operating system and ZeroTier version. Please try the latest ZeroTier release. 
Windows Server 2012 (3 different servers with different 2012 versions).
I have tried the latest (1.10.0) and (1.8.8)

**Comment by laduke** [comment]
Sorry about that! It can't work on 2012 anymore. Please use 1.6.6. See https://www.zerotier.com/download/
