### ISSUE TITLE
Linux static ztxxx route metric of 5000 is incorrect for some cases

### ISSUE THREAD

**Issue by diegomontoya** [zerotier/ZeroTierOne#1712]
In merged commit, linux zt route metrics have been fixed to 5000 which allows zt routes to co-exist with wifi lans. 

https://github.com/zerotier/ZeroTierOne/commit/0da00bf546e06b07e0c0b127d4fdd0e525618fe8

However, this introduces an issue where users need ALL traffic, regardless of lan/wifi/wann to be routed to zt. 

Case:  I am in China with gfw and having metric=5000 means my dns requests are leaked through the wifi interface even though 8.8.8.8 shoud be routed via 0.0.0.0/1 option in zt allowDefault=1 as wifi routes has lower metric than 5000, at least in Fedora rawhide (37 alpha).

```
0.0.0.0/1 via 172.25.204.155 dev zteb4pu4gr proto static metric 5000 
default via 192.168.31.1 dev wlp1s0 proto dhcp src 192.168.31.252 metric 4000 
128.0.0.0/1 via 172.25.204.155 dev zteb4pu4gr proto static metric 5000 
172.25.0.0/16 dev zteb4pu4gr proto kernel scope link src 172.25.29.132 metric 450 
192.168.31.0/24 dev wlp1s0 proto kernel scope link src 192.168.31.252 metric 4000 
```

Please note the dns leak is partial systemd-resolved bug using the wrong interface as noted in https://github.com/systemd/systemd/issues/23655

However, this does not negate the fact in some hostile environments, the VPN (in this case zerotier with allowDefault=1) should receive/route all traffic disregarding local lan/dhcp-dns route priorities. 

The fix is should be a dynamic configurable client side  ```metric``` config for network  settings default to 5000.

**Comment by diegomontoya** [comment]
Closed due to dupliate of #750

**Comment by diegomontoya** [comment]
@laduke Yes, 8.8.8.8 should be routed to zt, but due to a systemd-resolved bug, it routed to to wifi. I noted that that is a  systemd-resolved bug. My test case is bad showcase for this leak. 

A true test case for dns leak is if (which is always) a wifi router dhcp issues a dhcp ip of 192.168.31.1 as gateway and 192.168.31.1 as dns. Here, dns requests would be leaked until users take proactive measures to ignore 192.168.31.1 dns and override with static/secure zt ones.

**Comment by diegomontoya** [comment]
@laduke I believe I am wrong on the 192.168.31.1 as well since wifi would be the route selected, regardless of metric, as it would be the most specific? How does other vpn route all traffic, including all dns to it's interface? Thanks.

**Comment by laduke** [comment]
it's complicated 😅 

I'm not a VPN expert so I don't want to give out security advice. 

Maybe take a look at what https://github.com/trailofbits/algo does?
