### ISSUE TITLE
[API] returning 0 online nodes on `/network` endpoint

### ISSUE THREAD

**Issue by zalmanlew** [zerotier/ZeroTierOne#1713]
On the `/network` endpoint the `onlineMemberCount` seems to be fixed at 0.

I see this issue across multiple accounts.

Once you request the individual network it displays the correct count. It seems to only affect the total count on the network from the main `/network` endpoint.

This also affects the dashboard...

<img width="85" alt="image" src="https://user-images.githubusercontent.com/35234925/176234098-563a4cf2-edb2-4506-abd3-8c63708a97b6.png">

**Comment by glimberg** [comment]
This was removed.  The UI is being updated to also remove the spot for that.
