### ISSUE TITLE
Windows install missing vcruntime140_1.dll

### ISSUE THREAD

**Issue by Mikesco3** [zerotier/ZeroTierOne#1717]
I had the issue on 2 separate computers running windows 10 x64 today when went to Update zerotier to latest version (1.10.1) 
the installer and app would complain about missing vcruntime140_1.dll.

Solved issue by copying 
 vcruntime140.dll and **vcruntime140_1.dll** from
  `C:\Program Files (x86)\Microsoft\EdgeCore\103.0.1264.44\`
 or 
`C:\Program Files (x86)\Microsoft\Edge\Application\103.0.1264.44\`

 to: 
` C:\Program Files (x86)\ZeroTier\One`

Note: had to add Administrators to the allowed users on the zerotier\one folder 
  (right-click on the folder // security tab //  advanced, 
 then on top change Owner from SYSTEM to Administrators,
 then add Administrators and give full controll)

**Comment by glimberg** [comment]
Sorry about the issue.  We've fixed & re-deployed the installer to the download site.
