### ISSUE TITLE
Layer2 bridge not working

### ISSUE THREAD

**Issue by jmiguelf** [zerotier/ZeroTierOne#1723]
based on : https://zerotier.atlassian.net/wiki/spaces/SD/pages/7471125/Layer+2+Bridging+of+Ethernet+and+ZeroTier+Networks+on+Linux

Debian 11 ; zt 1.8.9 
Allow Ethernet Bridging YES
Do Not Auto-Assign IPs YES

side A: (dummy0 - 10.0.0.10/8)
br99: dummy0 ztmjfpruv7

side B: (dummy0 - 10.0.0.1/8)
br99: dummy0 ztmjfpruv7

can't ping from A -> B (or B -> A); if i add ip to zt interface it ping (using zt ip)

**Comment by laduke** [comment]
Try adding ips to br99. 

The bridge interfaces don't technically need ip addresses to bridge traffic. They are only needed if you need to connect to the bridge device on that zerotier network.

**Comment by jmiguelf** [comment]
after about 99 times trying.. and allot of timeit works, but very slow and after restart it takes arround 30 minutes to start comunicating....
it works but its too slow to use on my case
