### ISSUE TITLE
a connection issue on window 11

### ISSUE THREAD

**Issue by jackyliu16** [zerotier/ZeroTierOne#1724]
i haven't to put this issue which is because my poor RTFM and STFM(i don't know how to search it) couldn't give me a feasible[ i have checking the first 5 page of issue and a scan of  community discussion]

**goal for all**:
> i trying to using ssh connection and zerotier to connection a wsl(ubuntu2204) in another computer in my school(wasn't global ip)

**Operating System**:
window 11 (amd64 and writing drive of huawei matebook-e-2019 by myself)
_window 10 (inter i5 just as normal)_

**computer**
huawei matebook-E-2019
Qualcomm Snapdragon 850

**issue**:
1. i have succeed install zerotier in my computer
2. but when i wan't to join a network it show this 
![image](https://user-images.githubusercontent.com/50787361/179382100-435441da-553f-4f82-9f32-f5787a134bf0.png)
3. which is computerly different with the information in my window 10 computer
![image](https://user-images.githubusercontent.com/50787361/179382160-1f888c9e-6c87-411a-bbb4-c86095ed8631.png)
4. i have checking the network information `ipconfig` in both computer, which is 
5. window 11
![image](https://user-images.githubusercontent.com/50787361/179382195-6c1fea9b-818e-4e76-b1c1-5992e7f17b45.png)
6. window 10
![image](https://user-images.githubusercontent.com/50787361/179382221-4bf4c784-e414-41c3-92b0-202758e1e754.png)
7. base on the Implementation principle of zeroTierOne i guess it there is a kind of reason with when i using _window11(matebook-E-2019) it haven't show up a information of `do you want to been seen by the other computer in this network` (which show after i join the network in window 10)_
8. or it is because the different in window 11 which zerotier couldn't create a vritual NIC？

Finally, thank you for reading my issue, i will appreciate if you could give me a kind of advice, such as how should I continue searching or how to solve this problem

**Comment by jackyliu16** [comment]
my ZeroTier Version is 1.10.1
after i have try to uninstall and reboot and install it again, the situation seem haven't any improve

**Comment by joseph-henry** [comment]
Are you running as administrator? Do you have any antivirus software running?

**Comment by jackyliu16** [comment]
yes, i have try this actions, and haven't any antivirus software (except window defences) but i have close it , not working

**Comment by jackyliu16** [comment]
A brief update on progress：

basic on ths website i could using and see the error message 
https://github.com/zerotier/ZeroTierOne/wiki/Command-Line-Interface
firstly it's
```
PS C:\ProgramData\ZeroTier\One> .\zerotier-one_x64.exe -q join 8056c2e21c6bf9c3
0 join connection failed 
``` 
after i open the service of Zerotier, it just come to here
```
PS C:\ProgramData\ZeroTier\One> .\zerotier-one_x64.exe -q join 8056c2e21c6bf9c3
500 join {}
```

**this is the some informations about Zerotier-one:**
![image](https://user-images.githubusercontent.com/50787361/182289322-d834cfa8-e404-48c8-aa6c-4ab6e78affce.png)

[zerotier_dump.txt](https://github.com/zerotier/ZeroTierOne/files/9238946/zerotier_dump.txt)

i have also seem this https://discuss.zerotier.com/t/zerotier-cli-join-500-error/6610 but it seem couldn't impoving this situations.

**but i have seem this things which i believe it has tell me that i could never using Zeroiter-one in my arm computer except got the support by Driver...**
https://discuss.zerotier.com/t/windows-11-vm-on-parallels-macbook-pro-m1-doesnt-work/7427

**so, at the end of it, i have try to using natapp(natapp.cn) to implement Intranet penetration**

**Comment by hankknight** [comment]
hi jacky, i have same problem with you, my operation system is windows 8(intel i5) and i tried to reinstall as administrator still not slove it.

after checking **Network Connection** there is no network named `ZeroTier One [network id]`, then i check **Network Adapter** which tells me there is no ZeroTier-one network adapter,i suppose the zerotier network driver is not installed or no suitable driver for my PC(maybe).

![image](https://user-images.githubusercontent.com/32664414/217422961-01ac8a46-20b8-4e8b-bde2-d8dad4e5e93a.png)

wiki gives a solution, maybe it will work well(not try yet)...
https://zerotier.atlassian.net/wiki/spaces/SD/pages/35455014/PORT+ERROR+on+Windows

at last thank you for your natapp solution.

**Comment by laduke** [comment]
on windows 8 you need to use an older version of zerotier. see the download page for link.

**Comment by hankknight** [comment]
> on windows 8 you need to use an older version of zerotier. see the download page for link.

thank you for reply, i have download ZeroTierOne Version 1.6 and it's worked well on windows 8.
