### ISSUE TITLE
Problem joining more than one network on Windows (8.1)

### ISSUE THREAD

**Issue by adamierymenko** [zerotier/ZeroTierOne#173]
Sometimes one or more ports will show disconnected state when more than one network is joined at once. Sometimes fixed by service restart or reboot.

**Comment by glimberg** [comment]
Seems to happen on 1.0.1 as well.  

The port either shows disconnected, or it's continually added and removed.

**Comment by adamierymenko** [comment]
Closing since I think this is fixed in -dev.
