### ISSUE TITLE
Win11 can't connect

### ISSUE THREAD

**Issue by violet2422** [zerotier/ZeroTierOne#1731]
hello！My win11 computer is used as the client to join the host with the linux system as the manager. 
It is normal for me to join the network on win11, but there is no prompt on the website `https://my.zerotier.com/networkclient`?
win11:
![image](https://user-images.githubusercontent.com/73391269/181876366-a06f0518-993c-4f84-8f61-9c1047ee4d8d.png)

website `https://my.zerotier.com/networkclient`
![image](https://user-images.githubusercontent.com/73391269/181876304-c05c0da8-c972-4b0c-9444-055d83cf7a74.png)

**Comment by violet2422** [comment]
Why is my state always REQUESTING_CONFIGURATION？
![image](https://user-images.githubusercontent.com/73391269/181880247-f5fa34c3-7269-4658-bffa-39ab84697607.png)

**Comment by Cache-Cloud** [comment]
+1，是不是运营商阻断了呢？

**Comment by violet2422** [comment]
> +1，是不是运营商阻断了呢？

你好，我并不是这种zerotier-one应用的高手，不太了解运营商的真实情况，明天可以咨询以下！

**Comment by violet2422** [comment]
> +1，是不是运营商阻断了呢？

你好，是突然不行了吗？您这边是什么情况导致不能连接的？

**Comment by glloyd0314** [comment]
我移动网，也是前天开始突然就 `REQUESTING_CONFIGURATION`，整到今天一直都没有修复，网上能搜到的重启服务、重装 Zerotier、重启电脑之类的啥都试过了，依旧不行。
但如果真的是运营商的问题，我树莓派却还是一直连在 Zerotier 的网络里，不过由于是很久以前一直连在 Zerotier 里并没有重启过，不排除现在将其重启之后会连不上的可能性，但是我并不太敢试。

**Comment by EMREOYUN** [comment]
> 我移动网，也是前天开始突然就 `REQUESTING_CONFIGURATION`，整到今天一直都没有修复，网上能搜到的重启服务、重装 Zerotier、重启电脑之类的啥都试过了，依旧不行。 但如果真的是运营商的问题，我树莓派却还是一直连在 Zerotier 的网络里，不过由于是很久以前一直连在 Zerotier 里并没有重启过，不排除现在将其重启之后会连不上的可能性，但是我并不太敢试。
> 
> 更新：同样是移动，手机用和电脑相同的移动宽带连不上，但流量却能稳定连上，恐怕确实是移动宽带的问题。

Positive on all of my allowed clients including Windows Server 2012, Windows 11 and an Android Phone

**Comment by Zonciu** [comment]
+1，同为电信的两个宽带，一个连得上一个连不上

**Comment by 626640439** [comment]
+1，家里pc和nas上的zerotier，一个在5天前寄了，一个在4天半前寄了，怎么重装都弄不好，pc上的ui面板连打开控制面板的选项都没了，但是手机和公司笔记本上的都没问题

**Comment by g-i-a** [comment]
China Mobile Broadband.
I didn't change any configuration. Its status was suddenly REQUESTING_CONFIGURATION 5 days ago. 
移动宽带。一直正常使用没改设置，5天前突然连不上了。

**Comment by govmoe** [comment]
移动 +1 连不上了，是不是被阻断了？

**Comment by govmoe** [comment]
> 移动 +1 连不上了，是不是被阻断了？

所有状态都是Unkown然后客户端版本号是0.0.0

**Comment by Cache-Cloud** [comment]
移动，目前恢复。
不知道怎么回事就连上了。。。。

**Comment by govmoe** [comment]
> 移动，目前恢复。 不知道怎么回事就连上了。。。。

还是不行

**Comment by violet2422** [comment]
卸载一下zerotier在用移动网重新连接试试能不能链接上呢？



---Original---
From: "EMRE ***@***.***&gt;
Date: Mon, Aug 1, 2022 04:52 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [zerotier/ZeroTierOne] Win11 can't connect (Issue #1731)




  
我移动网，也是前天开始突然就 REQUESTING_CONFIGURATION，整到今天一直都没有修复，网上能搜到的重启服务、重装 Zerotier、重启电脑之类的啥都试过了，依旧不行。 但如果真的是运营商的问题，我树莓派却还是一直连在 Zerotier 的网络里，不过由于是很久以前一直连在 Zerotier 里并没有重启过，不排除现在将其重启之后会连不上的可能性，但是我并不太敢试。
 
更新：同样是移动，手机用和电脑相同的移动宽带连不上，但流量却能稳定连上，恐怕确实是移动宽带的问题。
  
Positive on all of my allowed clients including Windows Server 2012, Windows 11 and an Android Phone

**Comment by EMREOYUN** [comment]
> 卸载一下zerotier在用移动网重新连接试试能不能链接上呢？
>
>>我移动网，也是前天开始突然就 REQUESTING_CONFIGURATION，整到今天一直都没有修复，网上能搜到的重启服务、重装 Zerotier、重启电脑之类的啥都试过了，依旧不行。 但如果真的是运营商的问题，我树莓派却还是一直连在 Zerotier 的网络里，不过由于是很久以前一直连在 Zerotier 里并没有重启过，不排除现在将其重启之后会连不上的可能性，但是我并不太敢试。
更新：同样是移动，手机用和电脑相同的移动宽带连不上，但流量却能稳定连上，恐怕确实是移动宽带的问题。
Positive on all of my allowed clients including Windows Server 2012, Windows 11 and an Android Phone


It's been a long time but my issue was resolved and I did nothing about it. It just fixed itself.

**Comment by joseph-henry** [comment]
Going to close this ticket since it appears to be an issue at the telecom level possibly filtering of VPN traffic.
