### ISSUE TITLE
Linux Mint 21 beta - Segmentation fault 

### ISSUE THREAD

**Issue by amikot** [zerotier/ZeroTierOne#1733]
Version amd64 1.10.1 - installed secure way with script from the side.
Installation was successful and I've got my new ID.

Unfortunately, I'm unable to call zerotier-cli or zerotier-one because both returns segmentation fault.
No matter what parameter I use it is always the same result.

**Comment by bobmagicii** [comment]
same here.

`
bob@bigblackbox:~$ zerotier-one
Segmentation fault
bob@bigblackbox:~$ zerotier-cli
Segmentation fault
`

**Comment by amikot** [comment]
I've resolved the issue already.

Problem is caused by incorrect assignment of packages.
For Mint 21 someone assumed packages of Ubuntu 20.04 while repository of 22.04 should be used:

`deb [arch=amd64 signed-by=/usr/share/keyrings/zerotier.gpg] http://download.zerotier.com/debian/jammy jammy main`

Of course key file is assumed to be in /usr/share/keyrings/zerotier.gpg

**Comment by rbfii** [comment]
> same here. not beta tho. the current release is doing it too.
> 
> ```
> bob@bigblackbox:~$ zerotier-one
> Segmentation fault
> bob@bigblackbox:~$ zerotier-cli
> Segmentation fault
> ```
> 
> seems to avoid crashing if root tho.
> 
> ```
> root@bigblackbox:/var/log# zerotier-cli
> ZeroTier One version 1.10.1 build 0 (platform 1 arch 2)
> Copyright (c) 2020 ZeroTier, Inc.
> [...]
> ```
> 
> was able to join the network just fine after a `sudo su` via `zerotier-cli`

I was able to switch to root and join without issue. THANKS! 4/11/2023

**Comment by hozza** [comment]
> I've resolved the issue already.
> 
> Problem is caused by incorrect assignment of packages. For Mint 21 someone assumed packages of Ubuntu 20.04 while repository of 22.04 should be used:
> 
> `deb [arch=amd64 signed-by=/usr/share/keyrings/zerotier.gpg] http://download.zerotier.com/debian/jammy jammy main`
> 
> Of course key file is assumed to be in /usr/share/keyrings/zerotier.gpg

It seem the Zerotier installer has a bug, manually updating the apt sources list to "jammy" worked for me.

This can be done in a GUI by editing the repo for Zerotier in "Software Sources", also available via the Mint Update drop-down menu. Then, uninstalling and reinstalling `zerotier-one` package. e.g. `sudo apt remove zerotier-one` then `sudo apt install zerotier-one`
