### ISSUE TITLE
No debug logs on FreeBSD 13.1

### ISSUE THREAD

**Issue by grapexy** [zerotier/ZeroTierOne#1744]
OS: FreeBSD 13.1-RELEASE (OPNsense 22.7.2-amd64)

ZT branch: 1.10.1

After building ZT with `gmake one ZT_DEBUG=1` and running `zerotier-one` in foreground, only interface name is printed out, without any logs. However, linux build of the same version does show debug logs.

Any suggestions?

**Comment by joseph-henry** [comment]
I looked at the build flags and how the function is defined for each platform and I don't see why this would be happening. It looks the same. Can you try also adding `ZT_TRACE=1` when building? Maybe on freebsd we're redirecting std output somewhere but I don't think so.

**Comment by UnmovableCheddar** [comment]
I tried `gmake one ZT_DEBUG=1 ZT_TRACE=1`, but that didn't work either. According to build logs, it doesn't appear that ZT_DEBUG or ZT_TRACE are passed to the build at all:

```
root@opnsense:~/zt # gmake one ZT_DEBUG=1 ZT_TRACE=1
clang++ -Wall -g -pthread -isystem ext -I/usr/local/include -DZT_USE_MINIUPNPC -DMINIUPNP_STATICLIB -DMINIUPNPC_SET_SOCKET_TIMEOUT -DMINIUPNPC_GET_SRC_ADDR -D_BSD_SOURCE -D_DEFAULT_SOURCE -DOS_STRING=\"FreeBSD/13.1-RELEASE-p1\" -DMINIUPNPC_VERSION_STRING=\"2.0\" -DUPNP_VERSION_STRING=\"UPnP/1.1\" -DENABLE_STRNATPMPERR -DZT_USE_X64_ASM_SALSA2012 -DZT_BUILD_PLATFORM=7 -DZT_BUILD_ARCHITECTURE=2 -DZT_SOFTWARE_UPDATE_DEFAULT="\"disable\"" -std=c++17    -c -o node/AES.o node/AES.cpp
```

On linux, `make ZT_DEBUG=1 ZT_TRACE=1` passes the flags:
```
g++ -Wall -Wno-deprecated -g -O -std=c++17 -pthread -Izeroidc/target -isystem ext -DZT_USE_MINIUPNPC -DMINIUPNP_STATICLIB -DMINIUPNPC_SET_SOCKET_TIMEOUT -DMINIUPNPC_GET_SRC_ADDR -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -DOS_STRING="\"Linux\"" -DMINIUPNPC_VERSION_STRING="\"2.0\"" -DUPNP_VERSION_STRING="\"UPnP/1.1\"" -DENABLE_STRNATPMPERR -DZT_TRACE -DZT_DEBUG -DZT_SSO_SUPPORTED=1 -DZT_BUILD_PLATFORM=1 -DZT_BUILD_ARCHITECTURE=2 -DZT_SOFTWARE_UPDATE_DEFAULT="\"disable\"" -D_MT_ALLOCATOR_H -D_POOL_ALLOCATOR_H -D_EXTPTR_ALLOCATOR_H -D_DEBUG_ALLOCATOR_H -DZT_USE_X64_ASM_SALSA2012 -DZT_USE_FAST_X64_ED25519 -msse -msse2 -fPIC -fPIE   -c -o node/AES.o node/AES.cpp
```

**Comment by dch** [comment]
@grapexy the port itself has a debug option, you can build with this enabled from net/zerotier. There's a 1.10.1 patch available here, it's not merged in as people have reported issues using it.

**Comment by grapexy** [comment]
> @grapexy the port itself has a debug option, you can build with this enabled from net/zerotier. There's a [1.10.1 patch available](https://github.com/cabal7/ports/commit/2d6fc5de21f01e45333323c5473825608fedabfb), it's not merged in as people have reported issues using it.

I am using your port and that patch with debug enabled, but the resulting binary does not log anything except for the interface name. I then additionally patched Makefile with the needed CFLAGS and that's the only thing that produced logs:

``` diff
diff --git a/net/zerotier/Makefile b/net/zerotier/Makefile
index 035b6786fe6..ca79a6e4b2f 100644
--- a/net/zerotier/Makefile
+++ b/net/zerotier/Makefile
@@ -1,5 +1,7 @@
+# Created by: Corey Smith <corsmith@gmail.com>
+
 PORTNAME=      zerotier
-DISTVERSION=   1.8.9
+DISTVERSION=   1.10.1
 CATEGORIES=    net
 
 MAINTAINER=    dch@FreeBSD.org
@@ -10,18 +12,18 @@ LICENSE=            BUSINESS MIT PD
 LICENSE_COMB=          multi
 LICENSE_NAME_BUSINESS= Business Source License
 LICENSE_FILE_BUSINESS= ${WRKSRC}/LICENSE.txt
-LICENSE_FILE_MIT=      ${WRKSRC}/ext/json/LICENSE.MIT
+LICENSE_FILE_MIT=      ${WRKSRC}/ext/http-parser/LICENSE-MIT
 LICENSE_PERMS_BUSINESS=        dist-mirror dist-sell pkg-mirror pkg-sell auto-accept
 
 BUILD_DEPENDS= as:devel/binutils
 
-USES=          gmake compiler:c++14-lang
+USES=          gmake
 USE_RC_SUBR=   zerotier
 
 USE_GITHUB=    yes
 GH_PROJECT=    ZeroTierOne
 
-CFLAGS+=       -flax-vector-conversions
+CFLAGS+=       -DZT_TRACE=1 -DZT_DEBUG=1
 
 OPTIONS_DEFINE=        DBG
 DBG_DESC=      Enable foreground debugging for zerotier-one daemon
```

Thanks for the port, by the way!

**Comment by dch** [comment]
@joseph-henry I think we can close this.
