### ISSUE TITLE
Network adapter not only showing 100mbps，it is really limiterd to 100mbps 

### ISSUE THREAD

**Issue by steinvenic** [zerotier/ZeroTierOne#1746]
According to this article [Why is the ZeroTier Virtual Network Port Running at 100mbps?](https://zerotier.atlassian.net/wiki/spaces/SD/pages/7471187/Why+is+the+ZeroTier+Virtual+Network+Port+Running+at+100mbps)，Why after I disable the zerotier adapter, net speed changes to  1000mbps fron 100mbps?

**Comment by steinvenic** [comment]
1.by default
![image](https://user-images.githubusercontent.com/18524326/188427694-42f80666-4db3-4a3d-b80c-1b9c54be0670.png)
2.
![image](https://user-images.githubusercontent.com/18524326/188427923-d3b1fd5a-680a-4215-a343-04537b3edd10.png)

**Comment by joseph-henry** [comment]
Sorry for the late response. Any time you route through another device you will see a performance degradation, this is expected. The slowdown can be a result of network links, performance of the machine doing the routing, etc.

As for the article you linked, this is just reporting from the TAP driver. You aren't actually limited to that speed.

But in general a lot of things can affect total thoughput. And without knowing more about `10.144.52.72` it's hard to tell what's at fault.
