### ISSUE TITLE
Set underlay network prefer IPv6 to IPv4

### ISSUE THREAD

**Issue by Paladin-F** [zerotier/ZeroTierOne#1748]
All of my nodes can get both IPv4 and IPv6 addresses. But some of nodes can only get private IPv4 address from ISP. 
Is there any way for me to set  zerotier prefer IPv6 to IPv4 globally?
Tks!

**Comment by laduke** [comment]
Hi, it should use the best route per peer. I don't think there is a setting to prefer one or the other.

**Comment by Paladin-F** [comment]
> Hi, it should use the best route per peer. I don't think there is a setting to prefer one or the other.

With multipath policy, an option named "ipvPref" is just like what I need. 
But I‘m not sure this option will work with single path.

**Comment by joseph-henry** [comment]
You could try:

```
{
  "settings":
  {
    "defaultBondingPolicy": "ipv6-active-backup",
    "policies":
    {
      "ipv6-active-backup":
      {
        "ipvPref": 6,
        "failoverInterval": 10000,
        "basePolicy": "active-backup"
      }
    }
  }
}
```

This rule should still work even though you have a single link. It will create a bond but you can ignore it. If the ambient link probes add too much traffic overhead you can increase `failoverInterval` to something like `60000` or higher.
