### ISSUE TITLE
Have JSON API send an error object with 404, 500, etc. responses

### ISSUE THREAD

**Issue by adamierymenko** [zerotier/ZeroTierOne#175]

**Comment by keesbos** [comment]
http://www.jsonrpc.org/specification

**Comment by adamierymenko** [comment]
I think the API should probably stay REST-ful instead of RPC-ish, but we can include a JSON object with 404/500/etc. responses like:

    {
        "errorCode": -1234,
        "errorMessage": "That request was wack, yo!"
    }
