### ISSUE TITLE
iPhone device set up sync feature creating duplicate Node ID's

### ISSUE THREAD

**Issue by BradADV** [zerotier/ZeroTierOne#1755]
HI All,

Multiple users are now having an issue where, when using apple device sync to set up a new device, the Node ID from the original device copies over to the new device. 

We then have, for example, and iphone and ipad, both with the same Node ID, where only one device is able to connect at any one time. 

Can anyone advise if there is a way to flush the Node ID from a mobile device (IOS) or a work around to get it to reregister with the ZT network?

Thank you.

**Comment by laduke** [comment]
The only way to get a new Node ID is to delete the app and re-install it. 

If there's some way to delete the identity files with device sync config, that'd generate a new ID on start up. But I don't know anything about the device sync stuff.

**Comment by BradADV** [comment]
Hi laduke,


Thank you for your reply. I was hoping for a backend solution however given that its on a mobile device this will do.


Thank you.

**Comment by laduke** [comment]
thanks!
