### ISSUE TITLE
Zerotier stopped working

### ISSUE THREAD

**Issue by CyberBitz** [zerotier/ZeroTierOne#1762]
I had setup a digital ocean running Debian 11 bullseye. Installed splunk community and have a few cron jobs to get some data. Mostly monitoring some stuff of mine. I am moving from a on prem install which been going on for over a year no issue. 

So, I set my firewall to allow no incoming since I have zerotier running and everything works fine for a week. Then my dashboard is unreachable. Nothing in the logs... I cant hit the box via ZT so I get in via DO CLI and it has the ZT IP. I enable the port 22 to the public FW and I connect for troubleshooting. I reinstalled ZT and confirmed everything I can and still cant communicate over zerotier. Checked the linux firewall and all looks good. 

Been using ZT for years and never had this issue come up. This is really a basic setup nothing strange. 

I have 4 devices and the other 3 can ping each other but none this DO Server. 

**Service Running with no errors**
```
systemctl status zerotier-one.service
● zerotier-one.service - ZeroTier One
     Loaded: loaded (/lib/systemd/system/zerotier-one.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2022-10-09 09:47:42 EDT; 3s ago
   Main PID: 123637 (zerotier-one)
      Tasks: 3 (limit: 2339)
     Memory: 2.5M
        CPU: 15ms
     CGroup: /system.slice/zerotier-one.service
             └─123637 /usr/sbin/zerotier-one
```
**Error for binding because it is listening already**
```
# zerotier-one
zerotier-one: fatal error: cannot bind to local control interface port 9993
```
**Using Port 9993**
 ```
lsof -i :9993
COMMAND      PID         USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
zerotier- 123637 zerotier-one    6u  IPv4 1245131      0t0  TCP localhost:9993 (LISTEN)
zerotier- 123637 zerotier-one    7u  IPv6 1245132      0t0  TCP ip6-localhost:9993 (LISTEN)
zerotier- 123637 zerotier-one    8u  IPv4 1245139      0t0  UDP 10.116.0.3:9993
zerotier- 123637 zerotier-one    9u  IPv4 1245140      0t0  TCP 10.116.0.3:9993 (LISTEN)
zerotier- 123637 zerotier-one   10u  IPv4 1245141      0t0  UDP 10.10.0.6:9993
zerotier- 123637 zerotier-one   11u  IPv4 1245142      0t0  TCP 10.10.0.6:9993 (LISTEN)
zerotier- 123637 zerotier-one   12u  IPv4 1245143      0t0  UDP 206.81.6.216:9993
zerotier- 123637 zerotier-one   13u  IPv4 1245144      0t0  TCP 206.81.6.216:9993 (LISTEN)
```

**CLI Info - ONLINE**
```
 zerotier-cli info
200 info xxxxxxxxxx 1.10.1 ONLINE
```

**Has IP Address**
```
 ztbtoqsus4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2800 qdisc pfifo_fast state UNKNOWN group default qlen 1000
    link/ether 2e:f8:4b:f6:b4:23 brd ff:ff:ff:ff:ff:ff
    inet 10.244.196.100/16 brd 10.244.255.255 scope global ztbtoqsus4
```

I changed the port to 9992 and 9995 with the same result and then changed it back to default. What else should I try and or do to fix this issue? 

Edit: I added a Lightsail instance and my MacMini. The MacMini nor the raspi can connect to any DO or Lightsail but my windows can. Neither cloud servers can reach the mac or raspi but my other devices have no problem.

**Comment by joseph-henry** [comment]
@CyberBitz are you still experiencing this issue? Just a stab in the dark but maybe try adjusting the ZeroTier network MTU, It's hard to tell what's between a user's various machines and sometimes people find their MTU is too high. Feel free to re-open if this is still an issue.
