### ISSUE TITLE
which one is for the android 4.2.2 ,i installed  version1.4.6.5 ,but it is not working,who can help? thank you

### ISSUE THREAD

**Issue by lanyucomputer** [zerotier/ZeroTierOne#1763]
which one is for the android 4.2.2 ,i installed  version1.4.6.5 ,but it is not working,who can help? thank you

https://user-images.githubusercontent.com/68012194/195307159-e371264b-58d7-4db8-b314-33bffdf95fa0.jpg

https://user-images.githubusercontent.com/68012194/195307389-e1b4f2f9-f328-4084-830e-91238657ec79.jpg

**Comment by joseph-henry** [comment]
Android 4.2.2 is pretty old (10yrs). I'm not sure any of us know exactly what version of ZT works best on that. I'd go through our releases and try to find something from that era. I think I remember 1.2.8 working well.
