### ISSUE TITLE
Waiting for ZeroTier system service...

### ISSUE THREAD

**Issue by lNeverl** [zerotier/ZeroTierOne#1767]
I just uninstalled and reinstalled the latest version of zeotier, and opened the GUI to prompt Waiting for ZeroTier system service

Windows 11 Enterprise 22H2 22621.674

**Comment by glimberg** [comment]
I think I tracked this down. Seems users experiencing this issue have an invalid copy of the local API authorization token

macOS fix:

    Close the ZeroTier tray application
    Open a terminal and execute the following command: rm ~/Library/Application\ Support/ZeroTier/One/authtoken.secret and possibly rm ~/Library/Application\ Support/ZeroTier/authtoken.secret as well
    Reopen the ZeroTier UI application. You should be prompted for the administrator password so you can re-copy the authtoken into your user settings folder.

Windows:

    Open Explorer and type: %LOCALAPPDATA%\ZeroTier\ into the location bar.
    Remove authtoken.secret.
    If a One subfolder exists, delete authtoken.secret from there as well.

**Comment by FarLegend** [comment]
I have the same problem. Removing authtoken.secret worked one time and never again (meaning I was able to open the control panel, but not join a network). Now it keeps automatically refreshing the authtoken.secret file as soon as I remove it and the "Waiting for ZeroTier system service" prompt never disappears.

#1576 fix does not work either.

**Comment by celeest** [comment]
> I have the same problem. Removing authtoken.secret worked one time and never again (meaning I was able to open the control panel, but not join a network). Now it keeps automatically refreshing the authtoken.secret file as soon as I remove it and the "Waiting for ZeroTier system service" prompt never disappears.
> 
> #1576 fix does not work either.

I have the same issue, any fix ?

**Comment by ltyyyyy1017** [comment]
macOS:
Ensure that "com.zerotier.one.plist" can be opened normally and generally stored in "/Library/LaunchDaemons"

**Comment by zogyi** [comment]
solved my probelms, ty
