### ISSUE TITLE
Zerotier Controller Self Deployment Postgres Database

### ISSUE THREAD

**Issue by sfernandezf** [zerotier/ZeroTierOne#1768]
I'm trying to deploy Zerotier controller using the PostgreSQL DB instead of the `controller.d/` files. But, I get the following exception `ERROR:  relation "ztc_database" does not exist`. 

I wonder if the DB migrations scripts to create the database schema are available.

Thanks

**Comment by glimberg** [comment]
Postgres code is there for ZeroTier Central (https://my.zerotier.com). While we provide the source, the schema is closed source and managed in a closed source part of the web application platform. We offer no support for its use.
