### ISSUE TITLE
OSUtils::now() windows error

### ISSUE THREAD

**Issue by jack2007** [zerotier/ZeroTierOne#1773]
Hi, 
I just happened to find that some error in OSUtils::now() on win10.
[[](url)](https://github.com/zerotier/ZeroTierOne/blob/e0acccc3c918b59678033e585b31eb000c68fdf2/osdep/OSUtils.hpp#L201)

This function is expected to get timestamp now. New TS should be bigger than old TS.

Code to verify this bug, it loops calling now() function, and check if the new result is bigger than the old one, if not, print error information:
```c
#include <stdint.h>
#include <stdio.h>
#include <Windows.h>

//code copy from OSUtils::now()
int64_t now()
{
	FILETIME ft;
	SYSTEMTIME st;
	ULARGE_INTEGER tmp;
	GetSystemTime(&st);
	SystemTimeToFileTime(&st, &ft);
	tmp.LowPart = ft.dwLowDateTime;
	tmp.HighPart = ft.dwHighDateTime;
	return (int64_t)(((tmp.QuadPart - 116444736000000000LL) / 10000L) + st.wMilliseconds);

}

int main()
{
	int64_t right_now = now();
	int64_t before = right_now;
	uint32_t now_count = 1;
	while (1)
	{
		for (int i = 0; i < 1000; i++)
		{
			right_now = now();
			now_count++;
			if (right_now < before)
			{
				printf("Unexpected time: right_now %lld, before %lld, now_count %u\n", right_now, before, now_count);
			}
			else
			{
				before = right_now;
			}
		}
		
		Sleep(1);
	}	
}

**Comment by joseph-henry** [comment]
From what I can tell this isn't a bug in our `now()` but rather an issue with your time source. Windows may adjust its clock depending on where its getting its timing information and this adjustment can be at a very fine granularity. If successive calls to the Windows API yield values that do not increase monotonically that isn't a ZeroTier problem. Windows needs better timer facilities.
