### ISSUE TITLE
ZeroTier Central: Physical IP display problem

### ISSUE THREAD

**Issue by microdockman** [zerotier/ZeroTierOne#1775]
https://discuss.zerotier.com/t/strange-network-behaviour/4252/3

Sometimes I need to use the Central panel get my Dynamic public ip Address In different networks，
Recently, whenever there are too many network devices online at the same time, the following problem occurs and I have to recreate a network with only two or three devices to display the physical address

![is_001](https://user-images.githubusercontent.com/31898637/200979098-4c3e6b96-3411-48b4-bb2a-6f89d3d3c7fe.PNG)
![is_002](https://user-images.githubusercontent.com/31898637/200979115-82acfce8-df88-41ca-a08f-7639a0782f9c.PNG)
**The above devices are actually online and normal transmission, but not shown

This causes the device to add an extra zerotier ip,   Is there any problem with my setup ?

PS：
The three devices are actually online
![is_001](https://user-images.githubusercontent.com/31898637/200979722-af390df6-452c-4c4f-a338-b14550f03688.PNG)

**Comment by glimberg** [comment]
Not a bug. 

The field is filled with the last IP it received a packet from. In cases of relaying through roots and some other edge cases, it will be empty. 

I would not recommend using it for looking up the physical IP of the because, as you've noticed, it's not always accurate.

**Comment by microdockman** [comment]
> Not a bug.
> 
> The field is filled with the last IP it received a packet from. In cases of relaying through roots and some other edge cases, it will be empty.
> 
> I would not recommend using it for looking up the physical IP of the because, as you've noticed, it's not always accurate.

Thanks for your reply,

**Comment by microdockman** [comment]
Now it's back to normal. After I reduced the number of devices from 20 to 12, the physical addresses of the different networks are all showing up properly, more like a taillight in traffic which is what happens when the network isn't streamlined enough
