### ISSUE TITLE
not work in company.

### ISSUE THREAD

**Issue by timmy0209** [zerotier/ZeroTierOne#1778]
I use zerotierone to connect the company's computer with my home computer. Previously, I could connect normally, but recently, the company's computer could not be connected. I found that if I use my mobile phone to open a hotspot to connect the company's computer, it can work. At this time, I turn off the hotspot, and it can still work. If I keep my company's computer connected to my home computer, it can work all the time. If I don't connect for about a quarter of an hour, I will not be able to connect later. I must turn on my mobile hotspot again to connect.

**Comment by DarkArc** [comment]
Have you tried restarting ZeroTier after switching networks. I've noticed something similar: https://github.com/zerotier/ZeroTierOne/issues/1779
