### ISSUE TITLE
ZeroTier doesn't detect network changes and reconfigure promptly

### ISSUE THREAD

**Issue by DarkArc** [zerotier/ZeroTierOne#1779]
# Reproduction

In a situation with multiple network connections available (consider 2 hotel networks, or a hotel network and a wifi hotspot) with ZeroTier running, switch networks.

# Expected Result

ZeroTier detects the network change, and automatically restores connectivity.

# Actual Result

ZeroTier requires a restart. I can reproduce this reliably (as in every time) on MacOS (1.10.2) and Android (1.8.9). 

On Android, it's sufficient to "disconnect" and "reconnect." 

On MacOS, a "disconnect" and "reconnect" of the affected ZeroTier network is not sufficient. Instead the ZeroTier service must be restarted (with the following command -- which resolves the issue immediately 100% of the time): 

```
sudo launchctl unload /Library/LaunchDaemons/com.zerotier.one.plist ; sudo launchctl load /Library/LaunchDaemons/com.zerotier.one.plist
``` 

EDIT: I need to ammend this to say that this problem is not 100% reproducible. In particular, in further testing, sometimes it recovers after around 30 pings, other times it seems to get genuinely stuck but still resolves immediately with the ZeroTier service restarted (further testing done on MacOS).

**Comment by nikow** [comment]
I had similar problem in the past and my quite good working workaround was setup pinging between devices. After few pings ZeroTier was able to figure out that something is cooking and rediscover itself. Wireguard have keepalive too. In my case it was expiring NAT forwarding on Router.

**Comment by diegomontoya** [comment]
I have same reconnecting issue on macos and linux and usually happens when laptop goes to sleep and resumes. The only way to reconnect is to restart service.

**Comment by laduke** [comment]
https://discuss.zerotier.com/t/no-connectivity-when-switching-to-backup-isp/10347

**Comment by DarkArc** [comment]
> https://discuss.zerotier.com/t/no-connectivity-when-switching-to-backup-isp/10347

This isn't related to multipath; I'm not sure that's relevant?

**Comment by joseph-henry** [comment]
Right, this issue isn't strictly related to multipath but this multipath mode does help mitigate the problem until we can find a proper solution (other users have reported success). It allows you to set an upper bound on link switching speed but will send multiple probes during that interval so don't use this mode on an expensive link.

This is only available for desktop clients, not mobile unfortunately.

**Comment by DarkArc** [comment]
> Right, this issue isn't strictly related to multipath but this multipath mode does help mitigate the problem until we can find a proper solution (other users have reported success). It allows you to set an upper bound on link switching speed but will send multiple probes during that interval so don't use this mode on an expensive link.

So, to make sure I'm understanding correctly, this:

```
{
  "settings":
  {
    "defaultBondingPolicy": "custom-active-backup",
    "policies":
    {
      "custom-active-backup":
      {
        "basePolicy": "active-backup",
        "failoverInterval": 10000
      }
    }
  }
}```

doesn't actually do anything "multi-path", but basically sets up a "is the connection alive" check every 10 seconds(?) or so, and then "reconfigures things"?

**Comment by joseph-henry** [comment]
Pretty much. In `active-backup` it will only ever carry your application traffic over one link. But that link (and any others available) will be maintained in a failover queue and constantly evaluated for fitness (by sending probes). For instance, if you suddenly turn off wifi, it'll immediately go into failover mode and start using the next best link after `10000`ms have passed. (You can set this to a minimum of about `500` ms).

**Comment by Ecuashungo** [comment]
I have the same problem with the `zerotier-cli`. Is there any possiblilty to change those settings in the command line tool? It is really important for me that the network change is detected and that it keeps on working.

**Comment by Javihache** [comment]
I can still experience this same issue. Everytime I get to a hotel in the US lacking IPv6 connectivity there's no way to reconnect until rebooting MacOS or executing `sudo launchctl unload /Library/LaunchDaemons/com.zerotier.one.plist ; sudo launchctl load /Library/LaunchDaemons/com.zerotier.one.plist`.

Shouldn't Zerotier solve this type of situation by default without fiddling with config files?

**Comment by Javihache** [comment]
I can still experience this same issue. Everytime I get to a hotel in the US lacking IPv6 connectivity there's no way to reconnect until rebooting MacOS or executing `sudo launchctl unload /Library/LaunchDaemons/com.zerotier.one.plist ; sudo launchctl load /Library/LaunchDaemons/com.zerotier.one.plist`.

Shouldn't Zerotier solve this type of situation by default without fiddling with config files?

**Comment by ZiaChiu** [comment]
I had similar problems when I switched my iPhone network from wifi to 4g. But I need to wait a few minutes to hope zerotier VPN can work, and it's working. It's also happened to my macOS. I don’t know exactly how long I need to wait, but it's confusing how the restart mechanism works.
