### ISSUE TITLE
Zerotier cannot connect to the other devices

### ISSUE THREAD

**Issue by angussleeping** [zerotier/ZeroTierOne#1780]
Yestoday my zerotier on my PC doesnot work , in the UI , it shows that REQUESTING_CONFIGUERTION , I uninstall the software and reinstall , it doesnot work still.
Just now it shows OK in the UI , but it doesnot work still.
I also check my networks page , it always cannot shows my Physical IP on the page , but shows that is online.
I also tried to deleted this device and add it again , it cannot work right still.
How can I fix my zerotier?

**Comment by joseph-henry** [comment]
Sounds like something on your network is blocking ZeroTier's UDP traffic, either a firewall rule or NAT or some combination. This is a very common problem and is almost universally something that you'll need to fix on your end. [Here's a link for some things to check and try](https://zerotier.atlassian.net/wiki/spaces/SD/pages/6815768/Router+Configuration+Tips). If that link doesn't help let us know what you tried and we can re-open this ticket.
