### ISSUE TITLE
Cannot install per instructions on Unifi USG

### ISSUE THREAD

**Issue by jpmiller25** [zerotier/ZeroTierOne#1781]
I'm trying to install ZT client on Unifi USG-3P according to the instructions at https://docs.zerotier.com/devices/ubiquiti/ and getting an error when downloading the .deb file. 
`Warning: /config/data/firstboot/install-packages/zerotier-one.deb: No such
Warning: file or directory`

I realize I could just create the directories, but what I don't know is if that would produce the desired reinstall functionality after firmware updates, so wanted to file the issue. I did verify that the system is running on MIPS processor, the system is provisioned on a locally installed unifi controller, the firmware version is 4.4.56.

- What you expect to be happening.
-Download and install the .deb package
- What is actually happening?
- error that specified directory does not exist.
- Any steps to reproduce the error.
- ssh to USG, run
`
curl https://download.zerotier.com/dist/ubiquiti/zerotier-one_mips64.deb \
--output /config/data/firstboot/install-packages/zerotier-one.deb
`
- Any relevant console output or screenshots.
- What operating system and ZeroTier version. Please try the latest ZeroTier release.

**Comment by xInterlopeRx** [comment]
https://github.com/zerotier/ZeroTierOne/issues/1553#issuecomment-1055771165

This thread should get you going, although some users report the service failing after some time.

**Comment by jpmiller25** [comment]
@xInterlopeRx Thanks for the link! Due to the issues I think I'll continue to run it on my home server.
