### ISSUE TITLE
zerotier-cli listpeers  not PLANET

### ISSUE THREAD

**Issue by nankaimy** [zerotier/ZeroTierOne#1787]
win10 ,zerotier version is 1.10.2

C:\Program Files (x86)\ZeroTier\One>zerotier-cli listpeers
200 listpeers <ztaddr> <path> <latency> <version> <role>
200 listpeers 62f865ae71 - -1 - PLANET
200 listpeers 778cde7190 - -1 - PLANET
200 listpeers a0cbf4b62a - -1 - LEAF
200 listpeers cafe04eba9 - -1 - PLANET
200 listpeers cafe9efeb9 - -1 - PLANET

**Comment by laduke** [comment]
https://docs.zerotier.com/zerotier/troubleshooting/#router-configuration-tips

**Comment by laduke** [comment]
will re-open if it's a bug
