### ISSUE TITLE
install error with NO_PUBKEY 1657198823E52A61

### ISSUE THREAD

**Issue by mb-Ma** [zerotier/ZeroTierOne#1788]
I try to install zerotier on tencent cloud service.

gpg: key 1657198823E52A61: "ZeroTier, Inc. (ZeroTier Support and Release Signing Key) <contact@zerotier.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
gpg: Signature made Thu 10 Nov 2022 03:16:54 AM CST
gpg:                using RSA key 74A5E9C458E1A431F1DA57A71657198823E52A61
gpg:                issuer "contact@zerotier.com"
gpg: Good signature from "ZeroTier, Inc. (ZeroTier Support and Release Signing Key) <contact@zerotier.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 74A5 E9C4 58E1 A431 F1DA  57A7 1657 1988 23E5 2A61

*** ZeroTier Service Quick Install for Unix-like Systems

*** Tested OSes / distributions:

***   MacOS (10.13+) (just installs ZeroTier One.pkg)
***   Debian Linux (7+)
***   RedHat/CentOS Linux (6+)
***   Fedora Linux (16+)
***   SuSE Linux (12+)
***   Mint Linux (18+)

*** Supported architectures vary by OS / distribution. We try to support
*** every system architecture supported by the target.

*** Please report problems to contact@zerotier.com and we will try to fix.

*** Detecting Linux Distribution

*** Found Ubuntu, creating /etc/apt/sources.list.d/zerotier.list
Hit:1 http://mirrors.tencentyun.com/ubuntu bionic InRelease
Hit:2 http://mirrors.tencentyun.com/ubuntu bionic-security InRelease
Hit:3 http://mirrors.tencentyun.com/ubuntu bionic-updates InRelease
Get:4 http://download.zerotier.com/debian/bionic bionic InRelease [20.5 kB]
Err:4 http://download.zerotier.com/debian/bionic bionic InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1657198823E52A61
Reading package lists... Done
W: http://mirrors.tencentyun.com/ubuntu/dists/bionic/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/zerotier-debian-package-key.gpg are ignored as the file is not readable by user '_apt' executing apt-key.
W: http://mirrors.tencentyun.com/ubuntu/dists/bionic-security/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/zerotier-debian-package-key.gpg are ignored as the file is not readable by user '_apt' executing apt-key.
W: http://mirrors.tencentyun.com/ubuntu/dists/bionic-updates/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/zerotier-debian-package-key.gpg are ignored as the file is not readable by user '_apt' executing apt-key.
W: http://download.zerotier.com/debian/bionic/dists/bionic/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/zerotier-debian-package-key.gpg are ignored as the file is not readable by user '_apt' executing apt-key.
W: GPG error: http://download.zerotier.com/debian/bionic bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1657198823E52A61
E: The repository 'http://download.zerotier.com/debian/bionic bionic InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gpg is already the newest version (2.2.4-1ubuntu1.6).
0 upgraded, 0 newly installed, 0 to remove and 97 not upgraded.
gpg: WARNING: unsafe ownership on homedir '/home/ubuntu/.gnupg'

*** Installing zerotier-one package...
Hit:1 http://mirrors.tencentyun.com/ubuntu bionic InRelease
Hit:2 http://mirrors.tencentyun.com/ubuntu bionic-security InRelease                                     
Get:3 http://download.zerotier.com/debian/bionic bionic InRelease [20.5 kB]                              
Hit:4 http://mirrors.tencentyun.com/ubuntu bionic-updates InRelease                   
Err:3 http://download.zerotier.com/debian/bionic bionic InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1657198823E52A61
Reading package lists... Done
W: http://mirrors.tencentyun.com/ubuntu/dists/bionic/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/zerotier-debian-package-key.gpg are ignored as the file is not readable by user '_apt' executing apt-key.
W: http://mirrors.tencentyun.com/ubuntu/dists/bionic-security/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/zerotier-debian-package-key.gpg are ignored as the file is not readable by user '_apt' executing apt-key.
W: http://download.zerotier.com/debian/bionic/dists/bionic/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/zerotier-debian-package-key.gpg are ignored as the file is not readable by user '_apt' executing apt-key.
W: GPG error: http://download.zerotier.com/debian/bionic bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1657198823E52A61
E: The repository 'http://download.zerotier.com/debian/bionic bionic InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: http://mirrors.tencentyun.com/ubuntu/dists/bionic-updates/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/zerotier-debian-package-key.gpg are ignored as the file is not readable by user '_apt' executing apt-key.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package zerotier-one

*** Package installation failed! Unfortunately there may not be a package
*** for your architecture or distribution. For the source go to:
*** https://github.com/zerotier/ZeroTierOne

**Comment by glimberg** [comment]
Try changing permissions on the gpg key file.
```
sudo chmod 0644 /etc/apt/trusted.gpg.d/zerotier-debian-package-key.gpg
```
This will make the file readable system wide.  You should then be able to
```
sudo apt update
sudo apt install zerotier-one
```

**Comment by mb-Ma** [comment]
> Try changing permissions on the gpg key file.
> 
> ```
> sudo chmod 0644 /etc/apt/trusted.gpg.d/zerotier-debian-package-key.gpg
> ```
> 
> This will make the file readable system wide. You should then be able to
> 
> ```
> sudo apt update
> sudo apt install zerotier-one
> ```

Yeah. It works. ☺️☺️☺️
