### ISSUE TITLE
About Compilation Errors

### ISSUE THREAD

**Issue by TcDhlPro** [zerotier/ZeroTierOne#1794]
---
Directory: `ZeroTierOne/attic/world`
My Actions: `./build.sh`
Error Content: ↓↓↓↓↓↓
---
![image](https://user-images.githubusercontent.com/100897011/204115087-1b7f82cd-c879-4d01-b284-45c31a7a5a7a.png)

---
System version: `Debian-10`
ldd --version: `ldd (Debian GLIBC 2.28-10) 2.28`
gcc -v: `gcc version 8.3.0 (Debian 8.3.0-6)`
---
How to solve this error?
Can I ignore it?
---

**Comment by glimberg** [comment]
These are compiler warnings.  Not errors.  They're safe to ignore.

**Comment by TcDhlPro** [comment]
> These are compiler warnings. Not errors. They're safe to ignore.

ok~ Thank you for your reply
