### ISSUE TITLE
Exchange private IP information -- instead of broadcasts

### ISSUE THREAD

**Issue by adamierymenko** [zerotier/ZeroTierOne#180]
Broadcasting to locate devices on the same local network (same LAN, or same facility with same private IP scheme) is too unreliable. (... and some users don't like broadcasts ...)

So far I've resisted the obvious solution: add a new message that peers can push to one another that says "oh, and here are my private IPs -- try these."

There is *no* technical reason not to do this. The problem is that at least a few people will freak out: "you're leaking information about my private network schema!"

**If your security is dependent upon the privacy of your private (e.g. 10.1.2.x) IP scheme, you have horrible security. This information can trivially be obtained in at least five ways: malicious web apps, malicious flash applets on web apps, reverse TCP traceroute (firewalking technique), malicious HTML e-mails, and exhaustive search through specially crafted DNS records combined with HTTP redirects or other methods of forcing attempts on those hosts.** Edit: forgot exhaustive search with malicious DNS PTR records, ICMP packet tricks, and of course... drum roll...

*... SMTP relay headers if your company has an internal e-mail server.*

    X-Received: by 10.202.69.130 with SMTP id s124mr15521049oia.70.1434203390128; Sat, 13 Jun 2015 06:49:50 -0700 (PDT)
    X-Received: by 10.202.45.208 with SMTP id t199mr15419998oit.6.1434203389141; Sat, 13 Jun 2015 06:49:49 -0700 (PDT)

Oh no! I'm a hacker now!

So...

There comes a point in every developer's life when you must decide to do the better more powerful thing and ignore the reactions of those who do not understand. This is one of those times.

It can be done with a few constraints to make it more difficult for an attacker to use this mechanism to gain information. These would be:

 - Do not push information about private IP space unless you are actually exchanging FRAME information -- in other words do not share this information with peers with whom you do not have a shared network membership in common. That way someone random couldn't, say, send you VERB_NOP and then learn your private IP schema.

 - Add a local configuration option to turn this off so that those with misguided paranoia can do so.

... and so it shall be. Not sure when but VERB_CMB (call me back) is in the backlog. CMB will contain a list of endpoint addresses at which the sending peer might perhaps be reached. The receiver may then send probes to these addresses to test them, and if it receives a valid response it will learn these paths and communicate directly. It would be the peer-initiated companion to VERB_RENDEZVOUS.

We could make it another extension to VERB_HELLO but this is typically sent in the clear and I want this payload encrypted. Making it another verb also means it'll be a three-way handshake automatically. That'll add robustness by taking extra care to guard against half-paths (paths that are not bidirectional).

This will also allow us to do naked Ethernet framing, since CMB can include MAC addresses.

**Comment by maci0** [comment]
:+1:

**Comment by heri16** [comment]
Nice. Looking forward to this.

**Comment by dcode** [comment]
Couldn't you just expose the same client information available in the web ui to the client? At least on private networks....As the OP states, divulging what clients are currently alive on your network isn't exactly leaking of security. There are plenty of ways to find if an IP is alive.

**Comment by adamierymenko** [comment]
That's different, and wouldn't be needed. What I'm talking about here is sending a packet that says "hey, you might also try me at these addresses" with information about my adapter-level IP addressing.

It'll make direct shortest-path networking work in cases like:

 * Two instances on Amazon EC2, Microsoft Azure, etc. on a common VPC backplane (no multicast/broadcast)
 * Two Docker containers on the same machine, or on hosts joined by Docker's new VXLAN layer
 * Multiple instances of VirtualBox on the same machine or LAN (Vagrant, etc.)
 * Multiple instances on the same LAN with broadcast/multicast blocked by local firewalls
 * Hosts on a local but segmented network with multiple broadcast domains, e.g. two hosts on the same university campus but in different buildings.

... and so on.

After banging my head against a worn spot on the table, I've come to the conclusion that outright sharing of IP addressing info is The Only Way To Do It.

**Comment by janjaapbos** [comment]
Would it be possible to combine this with a configuration setting for preferred path? (optionally per node / peer?)

**Comment by adamierymenko** [comment]
Those are separate but related things. This first, then that.

**Comment by adamierymenko** [comment]
But it does affect the design of this -- I'm designing it such that the pushes of routes can optionally include preference info. Since this is an intelligence-at-the-edges protocol, the host should be the one to tell others what its preferred paths are.

**Comment by adamierymenko** [comment]
This is done in -dev for Unix/Linux and Windows.

**Comment by heri16** [comment]
Sad to say that when cloud instances experience a change in IP-address of interface, change in subnet, change in region, or failover via live-migration to another availability zone, this causes local IP address connectivity to be lost (due to Network ACLs and security zones/groups). Zerotier-one is not able to detect this change in connectivity and fails spectacularly (causes 100% packet loss).

```
It'll make direct shortest-path networking work in cases like:

* Two instances on Amazon EC2, Microsoft Azure, etc. on a common VPC backplane (no multicast/broadcast)
* Two Docker containers on the same machine, or on hosts joined by Docker's new VXLAN layer
* Multiple instances of VirtualBox on the same machine or LAN (Vagrant, etc.)
* Multiple instances on the same LAN with broadcast/multicast blocked by local firewalls
* Hosts on a local but segmented network with multiple broadcast domains, e.g. two hosts on the same university campus but in different buildings.
* Hosts on LANs that simply don't allow broadcast or multicast outside of things like ARP/NDP (these exist!)
```

**Comment by adamierymenko** [comment]
I wonder what Weave does. Perhaps it watches the local interface and takes that into account, renegotiating when it changes.

However I do not understand how one could detect a blocking change in security policy between hosts if no local change has occurred. This is the equivalent of yanking out a LAN cable from the back of a physical server.
