### ISSUE TITLE
Windows客户端报错“401 listpeers {}”

### ISSUE THREAD

**Issue by lhrbest** [zerotier/ZeroTierOne#1801]
搭建了linux环境的moon服务器，但是在windows的客户端配置后，不能使用命令，报错：
PS C:\Users\lhrxxt> zerotier-cli listnetworks
401 listnetworks {}
PS C:\Users\lhrxxt> zerotier-cli info
401 info {}
PS C:\Users\lhrxxt>

**Comment by joseph-henry** [comment]
I'm no longer too familiar with the nuances of Windows permissions but `401` is indicating a permission error. Try issuing the command as admin?
