### ISSUE TITLE
CLI MTU oddities

### ISSUE THREAD

**Issue by vincemulhollon** [zerotier/ZeroTierOne#1804]
Hey thanks for your efforts WRT zerotier and thanks for your time looking at this bug report.

Two related MTU problems:

The zerotier-cli claims to successfully set MTU parameter, but does not (surprise!)

The other problem is conceptually descriptively I feel the MTU should be the max packet length as we're usually operating under restriction so we're describing the MTU of the interface we're connecting to, rather than describing the MTU of the zerotier LAN.  I suppose this is a philosophical distinction.  I think the docs should emphasize the MTU setting is for the virtual interface as opposed to setting the MTU to pass thru the attached interface.

The story:

Got the usual cloud connected MTU problems.  This is not my first rodeo with MTU issues and similar.  SSH works fine, SCP files up to 500 bytes in length or so works fine, but scp of 3000 or so byte files do not work just freezes.  Ansible can't bootstrap silently locks up because its bootstrap file is too long to scp.  Some testing with ping -s and long packets aren't making it thru and for whatever reason PMTUD isn't working although I explicitly permit ICMP packets for it.  Ugh.

("LOL-NO" below is obviously not my network ID or API token)

root@ip-10-40-0-10:~# zerotier-cli 
ZeroTier One version 1.10.2 build 0 (platform 1 arch 2)
Copyright (c) 2020 ZeroTier, Inc.
(etc)

root@ip-10-40-0-10:~# zerotier-cli get LOL-NO mtu

2800

Yeah I read about that, the default was supposed to change a year ago but new networks are still set up as 2800.  The network connection at AWS silently eats larger packets and something at AWS is not implementing PMTUD correctly how annoying; my SGs are not the issue.  When in doubt always blame AWS, LOL.  OK, set MTU to 1200 to work around.

root@ip-10-40-0-10:~# zerotier-cli set LOL-NO mtu=1200

Cool it worked; my MTU is now 1200

root@ip-10-40-0-10:~# zerotier-cli get LOL-NO mtu

2800

oops the above is not what I expected.  Setting MTU to 1200 in the CLI did not produce an error therefore that implies it worked, although it didn't work.

After that I ran:

root@ip-10-40-0-10:~# cat setmtu.sh 

#!/bin/bash

curl -X POST "https://my.zerotier.com/api/v1/network/LOL-NO" -H "Authorization: token LOL-NO" -d '{"config": {"mtu": 1200}}'

BTW you have nice online API docs thank you was easy to use and figure out.

Did a reboot after the above and the interface MTU is now shown as 1280 in "ifconfig".  Cool?  But 1280 is not 1200.

root@ip-10-40-0-10:~# zerotier-cli get LOL-NO mtu

1280

Wait, what?  I set it to 1200 in the API while the interface sets to 1280 and the CLI shows 1280.  I assume you're thinking the MTU is the max data length in a packet before overhead, whereas I'm thinking the MTU is the max length of an entire packet or the MTU of the interface we're connecting to as opposed to the MTU of the virtual interface.  Or is something else going on like the floor is 1280? 
 But regardless, it works now.

Anyway thanks for your time etc.

**Comment by laduke** [comment]
see #1554 for  more info about network MTU not being applied. 

It's a little confusing that it needs to be changed on the virtual network. Though we've heard about it a couple times in different clouds or GSM providers. 
The underlying actual physical udp packets are in 1432 byte chunks if I am not mistaken. 

See here from some current values
https://github.com/zerotier/ZeroTierOne/blob/e0acccc3c918b59678033e585b31eb000c68fdf2/include/ZeroTierOne.h#L77-L101

**Comment by joseph-henry** [comment]
@vincemulhollon Thanks for reporting this. There's a PR #1860 that addresses the MTU setting issue, we'll try to get it out in the next release. Is there anything else we can help you with or can this issue be closed?

**Comment by vincemulhollon** [comment]
Thank you for your time and efforts, it is much appreciated by many people.
