### ISSUE TITLE
ZeroTierOne failed to build on windows MSVC due to ERROR: "fatal error C1083: Cannot open include file: 'nlohmann/json.hpp': No such file or directory" 

### ISSUE THREAD

**Issue by WickWeiWkSpace** [zerotier/ZeroTierOne#1809]
Hi All,

ZeroTierOne failed to build on windows MSVC due to ERROR: "F:\gitP\zerotier\ZeroTierOne\osdep\OSUtils.hpp(46,10): fatal error C1083: Cannot open include file: 'nlohmann/json.hpp': No such file or directory" on e0acccc on master branch. We found that in 7e46c83, line 46 of ZeroTierOne/osdep/OSUtils.hpp is #include "../ext/json/json.hpp", while in e0accccc it is #include <nlohmann/json.hpp>. Could you please help to look at this issue?

Environment:
VS 2019 + Windows Server 2019

Repro steps:
1. git clone https://github.com/zerotier/ZeroTierOne.git F:\gitP\zerotier\ZeroTierOne

2. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=amd64

3. cd F:\gitP\zerotier\ZeroTierOne\build_amd64

4. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DCMAKE_BUILD_TYPE=Release .. 2>&1

5. set _CL_= /DNOMINMAX

6. cd F:\gitP\zerotier\ZeroTierOne\build_amd64

7. msbuild /m /p:Platform=x64 /p:Configuration=Release zerotiercore.sln /t:Rebuild 2>&1

Error info:
[zerobuild.log](https://github.com/zerotier/ZeroTierOne/files/10174001/zerobuild.log)
4>F:\gitP\zerotier\ZeroTierOne\osdep\OSUtils.hpp(46,10): fatal error C1083: Cannot open include file: 'nlohmann/json.hpp': No such file or directory (C:\repos\msvc\src\vctools\Compiler\CxxFE\sl\p1\c\p0prepro.c:1940) [F:\gitP\zerotier\ZeroTierOne\build_x86\zerotiercore.vcxproj]

**Comment by glimberg** [comment]
If you're trying to build ZeroTierOne, use the Visual Studio solution `windows/ZeroTierOne.sln`, rather than CMake.  IIRC, that CMakeLists.txt is only used as part of a project that includes the ZeroTier core.

**Comment by WickWeiWkSpace** [comment]
Hi @glimberg, 
I used windows/ZeroTierOne.sln in VS2022 as you said, but this error occurred: `F:\gitP\ZeroTierOne\service\OneService.cpp(57,10): fatal error C1083: Cannot open include file: 'zeroidc .h': No such file or directory`, 
Can you help me to see why? Thanks!

**Comment by hankknight** [comment]
> Hi @glimberg, I used windows/ZeroTierOne.sln in VS2022 as you said, but this error occurred: `F:\gitP\ZeroTierOne\service\OneService.cpp(57,10): fatal error C1083: Cannot open include file: 'zeroidc .h': No such file or directory`, Can you help me to see why? Thanks!

I suppose you can check your project configuration in VS, try:
1. check `Configuration Properties` - `VC++ Directories` - `Include Directories`.
2. check `zeroidc .h` file in your project, if exists add it to project `Header Files`.

**Comment by glimberg** [comment]
Sorry I missed this.  You probably don't have the Rust compiler & toolkit installed.  See  https://rustup.rs/ for install instructions.  Rust is required for the zeroidc subproject.
