### ISSUE TITLE
supported edition values are `2015` or `2018`, but `2021` is unknown

### ISSUE THREAD

**Issue by Koido-Xzy** [zerotier/ZeroTierOne#1812]
root@Sherlock:/home/xxxx/ZeroTierOne-master# make
export PATH=//root/.cargo/bin:$PATH; cd zeroidc && cargo build --release
error: failed to parse manifest at `/home/xxxx/ZeroTierOne-master/zeroidc/Cargo.toml`

Caused by:
  failed to parse the `edition` key

Caused by:
  supported edition values are `2015` or `2018`, but `2021` is unknown

**Comment by glimberg** [comment]
You're probably using an old version of Rust.  Edition 2021 requires Rust 1.56.0 or greater.

**Comment by tdjemai** [comment]
You need to get Rust from the official repo. Debian packages won't work here.
