### ISSUE TITLE
`zerotier-cli peers` output when "tunneled"

### ISSUE THREAD

**Issue by laduke** [zerotier/ZeroTierOne#1813]
Can we check if we're TUNNELED and make `peers` say TUNNELED instead of DIRECT? 

```
 % zerotier-cli info
200 info xxxxx1646 1.10.2 TUNNELED

zerotier-cli peers
200 peers
<ztaddr>   <ver>  <role> <lat> <link> <lastTX> <lastRX> <path>
62f865ae71 -      PLANET   259 DIRECT 7958     2656     50.7.252.138/9993
778cde7190 -      PLANET    66 DIRECT 7958     2869     103.195.103.66/9993
9bee8941b5 1.10.2 LEAF      73 DIRECT 7958     12293    35.209.202.191/21014
cafe04eba9 -      PLANET   199 DIRECT 7958     2716     84.17.53.155/9993
cafe9efeb9 -      PLANET    31 DIRECT 7958     2884     104.194.8.134/9993
```

**Comment by joseph-henry** [comment]
Internally whether a peer is reachable via a tunneled connection is not in any way associated with the peer. How the packet gets to and from the peer is all done according to the whims of the service/osdep code.

That is to say, without a major refactor the only thing we can do is say (on your local node) that a TCP tunnel connection is active on your machine and we can't any more specific.

So an output would look like:

```
 % zerotier-cli info
200 info xxxxx1646 1.10.2 TUNNELED

zerotier-cli peers
200 peers
<ztaddr>   <ver>  <role> <lat> <link> <lastTX> <lastRX> <path>
62f865ae71 -      PLANET   259 TUNNELED 7958     2656     50.7.252.138/9993
778cde7190 -      PLANET    66 TUNNELED 7958     2869     103.195.103.66/9993
9bee8941b5 1.10.2 LEAF      73 TUNNELED 7958     12293    35.209.202.191/21014
cafe04eba9 -      PLANET   199 TUNNELED 7958     2716     84.17.53.155/9993
cafe9efeb9 -      PLANET    31 TUNNELED 7958     2884     104.194.8.134/9993
```

Would this be sufficient?

**Comment by laduke** [comment]
That makes sense and that is the output I was thinking.

Just trying to avoid seeing DIRECT in the peers output and thinking I'm on an optimal connection. 

Open to other options or just not doing anything.

**Comment by glimberg** [comment]
Maybe a `TUNNELED` notification at the bottom of the list, rather than switching them all to `TUNNELED`?

**Comment by glimberg** [comment]
Was going to say put it at the top of the list, but that list can get pretty long and has a good possibility of scrolling off the screen
