### ISSUE TITLE
Asustor apk update

### ISSUE THREAD

**Issue by giulianozor** [zerotier/ZeroTierOne#1826]
Please, update apk for asustor... it hasb benn 2 years ...
A binary for a manual update would be great too !

thanks

**Comment by joseph-henry** [comment]
It was updated in November. May I ask why you believe it is two years old?

http://download.zerotier.com/dist/asustor/

**Comment by giulianozor** [comment]
Sorry, I did not find that url.
I was referring to the app center version.

thanks for the info!

**Comment by i-m-d** [comment]
Hello,

 I that URL http://download.zerotier.com/dist/asustor/ there is only 1.10.2 and there is to download 1.12.02, please update package.

Thank you.
