### ISSUE TITLE
Zerotier-Synology & HDD hibernation issue 

### ISSUE THREAD

**Issue by dawidroz** [zerotier/ZeroTierOne#1828]
Hi 

Since I've installed zerotier-synology docker image on my DS220+ NAS, I noticed that disk hibernation doesn't work anymore. 

I've started debugging it by hibernation debug log (https://shred.zone/cilla/page/446/enable-synologys-hibernation-debugger.html) and found the following records: 

```
[433342.913581] ppid:30481(entrypoint.sh), pid:30510(zerotier-one), dirtied inode 39673 (159924d630d06d47.conf) on md0
[433342.913591] ppid:30481(entrypoint.sh), pid:30510(zerotier-one), dirtied inode 39673 (159924d630d06d47.conf) on md0
[433342.913636] ppid:30481(entrypoint.sh), pid:30510(zerotier-one), WRITE block 3739784 on md0 (8 sectors)


```

Is it possible that zerotier-synology docker saves something on the hard drive periodically? Can we avoid that somehow? 

Thanks

**Comment by dawidroz** [comment]
After debugging, I found that the file `/var/lib/zerotier-one/networks.d/MY_NETWORK_ID.conf` is updated every minute. Is there an option to change this behavior?

**Comment by laduke** [comment]
Interesting point. I don't think there are any zerotier settings to address that. 
I bet you could mount/map `networks.d` another disk or tmpfs, so zerotier doesn't touch your nas drives. 
`./peers.d` probably too. 

peers.d is cache, you can lose it without causing much trouble. If you lose networks.d, you'll need to join any networks again. Just don't lose the identity files.
I guess you could back up the identity files and then put that whole zerotier home directory on a different drive. 

Hope that helps.

**Comment by dawidroz** [comment]
I was thinking about that approach and was wondering which files I can lost and which are important. Will try use tmpfs. Thank you

**Comment by pawol** [comment]
I have the same issue on Asustor AS6102T on each verion of Zerotier. When Zerotier is uninstalled then hipernation of HDDs works ok.
