### ISSUE TITLE
Prevent zerotier-one from adding a route to 0.0.0.0

### ISSUE THREAD

**Issue by qiyunluoxing** [zerotier/ZeroTierOne#1829]
Hello, I am using zerotier-one 1.10.2 on debian 11. 
About 10s after zerotier-one service starts up, zerotier-one will add a route to 0.0.0.0 gateway 0.0.0.0 mask 0.0.0.0 with metric 0, which prevents me from accessing the internet. 

Below is the result of "sudo route -n"
カーネルIP経路テーブル
受信先サイト    ゲートウェイ    ネットマスク   フラグ Metric Ref 使用数 インタフェース
0.0.0.0         0.0.0.0         0.0.0.0         U     0      0        0 ztrf2q7ieo
0.0.0.0         192.168.18.1    0.0.0.0         UG    600    0        0 wlp1s0
169.254.0.0     0.0.0.0         255.255.0.0     U     0      0        0 ztrf2q7ieo
169.254.0.0     0.0.0.0         255.255.0.0     U     1000   0        0 wlp1s0
172.25.0.0      0.0.0.0         255.255.0.0     U     0      0        0 ztrf2q7ieo
192.168.18.0    0.0.0.0         255.255.255.0   U     600    0        0 wlp1s0

I have tried to set a higher metric for zerotier with "sudo ifmetric ztrf2q7ieo 5000", but zerotier-one will immediately recreate the first entry. 

Needless to say, I have not created such a entry in "Zerotier Central" with "Managed Routes". I have also not changed anything in "/var/lib/zerotier-one/networks.d".

I have also tried to downgrade zerotier-one to 1.8.9, or use the snapd version. But the problem persisted. 

Thank you for reading.

**Comment by laduke** [comment]
When we've heard about this before it was `connman` adding the route
