### ISSUE TITLE
Document bridging networks

### ISSUE THREAD

**Issue by TheGuyDanish** [zerotier/ZeroTierOne#183]
And perhaps in general, more documentation for use cases.

My current use case is creating a VPN Bridge-like network, for my workplace. If anyone can give pointers to how to set this up, I'd gladly write up a guide.

**Comment by adamierymenko** [comment]
A new web site is in progress -- we'll be building more documentation there. The existing site is a little fragmented. We'll also probably dump the forums, which not enough people use, and perhaps create a StackOverflow or something if possible.

**Comment by naasking** [comment]
I'm a little lost with bridging too. A Google search didn't turn up anything official anywhere that I can see. Naively attempting to bridge on Windows goes nowhere, ie. it tries to bridge but never completes; had to restart.

**Comment by adamierymenko** [comment]
See https://www.zerotier.com/community/

There are some bridging docs and discussion there now.
