### ISSUE TITLE
use with docker in mac osx

### ISSUE THREAD

**Issue by callMeMakerRen** [zerotier/ZeroTierOne#1831]
my mac has zerotier app installed,and i use an private planet,so i changed the local planet file,and all works .but i have another network that use the default planet,so i try to run a new zerotier instance in docker,and hope it can work
```
docker run --name myzerotier --restart always --cap-add NET_ADMIN --device /dev/net/tun --network host   zerotier/zerotier:1.10.2 xxxxxx
```
i do join the network,and in zerotier manage web, i do auth the node,and in the docker env ,i can ping other node,but out of the docker i can not ping my node, is this because /dev/net/tun is not available in mac?
- What you expect to be happening.
   work like native zerotier
- What is actually happening?
- Any steps to reproduce the error.
- Any relevant console output or screenshots.
- What operating system and ZeroTier version. Please try the latest ZeroTier release.

**Comment by laduke** [comment]
What did you discover?
