### ISSUE TITLE
Network join fails with 1.0.3+ controller

### ISSUE THREAD

**Issue by keesbos** [zerotier/ZeroTierOne#184]
When I join a network on the same vm as the controller (i.e. it is the controller), it works. On a vm in the same network it fails.

I do see 'NETWORK_CONFIG_REQUEST from fe519937a3(172.31.1.44/9993)' coming in on controller. The controller also prepares an answer:
* node/IncomingPacket.cpp:
 * catched at 'case NetworkController::NETCONF_QUERY_OK:'
 * created with 'Packet outp(peer->address(),RR->identity.address(),Packet::VERB_OK)'
 * sent with 'RR->node->putPacket(_remoteAddress,outp.data(),outp.size())'

But I don't see them arrive at the node wants to join the network (I do see NOPs comming in from the controller). See: TRACE("<< %s from %s(%s)",Packet::verbString(verb()),source().toString().c_str(),_remoteAddress.toString().c_str())

Any clue?

**Comment by adamierymenko** [comment]
This sounds as if the reply packet is being sent but is never arriving at its destination. Can the two communicate directly otherwise? You mentioned NOPs arriving.

**Comment by keesbos** [comment]
Yep. I did see NOPs arrive from the controler-system to the node-system. Somehow the VERB_OK (with VERB_NETWORK_CONFIG_REQUEST in it) doesn't arrive. Either not sent (but RR->node->putPacket called) , or just not received.

I'll try some more debugging.

**Comment by adamierymenko** [comment]
Helps to properly compose the packet.

**Comment by keesbos** [comment]
Yep. That did the trick.
