### ISSUE TITLE
Connection state notification support?

### ISSUE THREAD

**Issue by oskarirauta** [zerotier/ZeroTierOne#1858]
HI.

I was wondering if it would be possible to have a notification about connection state changes, maybe as simple as notify if connection is either up or down?

I thought about changing sources by myself, but code seems a bit complex, this would ofcourse suite mostly linux (console) users but I thought about adding support for command-line argument about shell script location, and when ever service goes up or down, or program exits- it would execute the script with simple up or down argument to script, like this:
`/usr/bin/zerotier-change up`

But I couldn't find a clear place on the code where to determine that connection is succesfully up- or dropped..

This was just a simple method to do so, propably there would be better solutions- but please, avoid anything that needs huge depencies such as dbus- but something like this would be nice, since hotplug system on linux does not register when zerotier interface is up or down. Or could hotplug system be triggered directly as a notification somehow maybe?

Could something like this be though about?

**Comment by laduke** [comment]
Thanks for writing. Can you explain a little about what you want to happen when an interface comes up? just for more context.

**Comment by oskarirauta** [comment]
Sure thing, actually I even already wrote something like that, but haven't had a possibility to test it (and even cannot do that in few next days propably as I am just leaving for a while..)

And as a reminder, this is just something that I wrote really quick, so nowhere perfect.. But check it out for a sample what I am trying to say..

https://github.com/oskarirauta/ZeroTierOne/commit/00c369d7cb627133453dd0884aa737daa27eada5

So, can't say if it works at all, or since I am not very familiar to Zerotier project's internal code, not sure if it triggers correctly until I try- but would rather like to see someone do it the *right way* :)

There's new parameter for cli, -n which should tell location of script to execute on connection state changes.
Concept simply is this, if you for example use -n/usr/bin/zt-notifier.sh
 - when connection is established, script /usr/bin/zt-notifier.sh is executed with argument "up"
 - when connection is closed, lost, abnormal service exit, etc (connection dies), same script is executed once again with argument "down"

Script contents then is up to user, why I am interested in this, is that I am Openwrt user and recently initial zerotier protocol support was released, yes - zerotier's been there for ages, but protocol support means that system is capable to return information about state of connection (like ip addr, and if it's up or down and so on), unfortunately this is just *initial* support, as interface seems always to be down/pending state, because hotplug.d scripts or nothing is able to tell the system that hey, we did it! We are up and running!

Script support like this could be the key to make it possible. Seems a bit small to just support openwrt by providing such functionality? It's actually been asked before if you google the topic with other distributions as well, and ofcourse... It wouldn't limit to just functionality where I am looking for it, one could use it for... Just about anything where he wants to be notified of zerotier connection's state. Can't give you any ideas on that, but surely anyone interested party may use their imagination to think something out..

Like I said, this is just a concept, argument to script could be something else as well, like json with wider details - in my case, I would be happy to just retrieving details if connection went either up or down as that is only thing I really need, other details I can retrieve - just need the mechanism to know *when* to retrieve it :)

Ask again if my too long explanation wasn't very clear, I am known to sometimes say too much :)

**Comment by oskarirauta** [comment]
And sorry for that hasty code, tried to clean up the house for tomorrow, make food and feed my kids while doing it in few hours of time with foreign project ;)

**Comment by oskarirauta** [comment]
@laduke What do you think about something like this?

**Comment by oskarirauta** [comment]
I have made more changes to my code and now it's working pretty nicely. I have also a script that retrieves all the information and system is working very nicely.

It *could* have one more thing, it could add ifname as parameter as well, as first parameter, like this:
/root/myscript.sh zt0 up

And I know how to retrieve ifname, it's just that I am not sure if I would be doing it the right way.....
I am always connected to single network, but I have understood that you can be connected to multiple networks at same time, or am I wrong here?

**Comment by oskarirauta** [comment]
_isUp should be instead a vector of strings, if interface is up, it should be added to vector, and when down- it should be removed, that would solve the problem with multiple ifd's.. Just brain storming some ideas. Also, whole concept could be different, there could be another vector - one that has list of interface's to notify, and then a chain that would do it, in this way, I propably could get rid of usleep, as I just would add interfaces to list... And then execute it on next loop. Delay is there to allow system to have enough time to get the details. I also added & to end of script execution, because otherwise cli cannot return information about network because script execution blocks.. with & it keeps doing it's thing in the background.. but that works on unix like- on windows... a no go I think..

**Comment by oskarirauta** [comment]
@laduke I am finished. It works for _me_ now perfectly and here I share how I made it- would love to make a PR on this, but I am pretty certain that it won't be accepted as is, so merely I provide here a idea and a working concept/implementation of it.

With well designed script, this fills in details about state of zerotier connection to openwrt's own network manager (netifd) - so very useful, as this provides possibility for more or less "native" protocol support for zerotier, like most other vpn solutions available have.

Ofcourse, this doesn't suite only for single system, openwrt in this case, as with imagination this kind of notification, can be used on various tasks, or on other systems also possibly provide such information to the host.

status of connection with this and a nice script provide following details on console:
```
root@gateway:/lib/netifd/proto# ifstatus zt0
{
	"up": true,
	"pending": false,
	"available": true,
	"autostart": true,
	"dynamic": false,
	"uptime": 9,
	"l3_device": "zt0",
	"proto": "zerotier",
	"updated": [
		"addresses",
		"routes",
		"data"
	],
	"metric": 0,
	"dns_metric": 0,
	"delegation": true,
	"ipv4-address": [
		{
			"address": "172.28.28.1",
			"mask": 32
		},
	],
	"ipv6-address": [
		{
			"address": "fe80::3436:e8ff:fe4c:102d",
			"mask": 64
		}
	],
	"ipv6-prefix": [
		
	],
	"ipv6-prefix-assignment": [
		
	],
	"route": [
		{
			"target": "172.28.28.0",
			"mask": 24,
			"nexthop": "0.0.0.0",
			"source": "172.28.28.1/32"
		}
	],
	"dns-server": [
		
	],
	"dns-search": [
		
	],
	"neighbors": [
		
	],
	"inactive": {
		"ipv4-address": [
			
		],
		"ipv6-address": [
			
		],
		"route": [
			
		],
		"dns-server": [
			
		],
		"dns-search": [
			
		],
		"neighbors": [
			
		]
	},
	"data": {
		"hwaddr": "36:XX:XX:XX:XX:2d",
		"id": "XXXXXXXXXXXX",
		"mtu": 2800,
		"network": "my_network",
		"status": 200
	}
}
```
Note: _some information is redacted._

**Comment by oskarirauta** [comment]
@laduke - so, what do you think? Could something like this be added as a feature?

**Comment by oskarirauta** [comment]
Further investigations reveal a fact, that this does not work well, if you are connected to multiple networks at same time. Only first one will get notified properly.

I wrote a modification of notifier class(not committed though), but it's no use, as I do not have knowledge how to retrieve ifd name for added ip address. A hacky solution does exist- instead of posting ifd name to script, I could use ip address, then in the script I could use ip command to find interface name with that ip address- but it is far from optimal, so onwards, I will leave this matter to more experienced hands with high hopes that better implementation will be integrated to mainstream.

Another solution could be to indeed store ip addresses in notifier that are up, and write a routine that iterates interfaces from system and compares to their ifnames to ipaddresses, but that sounds a bit heavy operation when there has to be simpler method to retrieve ifd of added ip address.

If someone is interested to provide something like this, one idea would be to expose a whole lot of information to notification script/program, in form of json or similar- not use for me, but I can see how someone could benefit on such.

**Comment by oskarirauta** [comment]
@joseph-henry 
Thanks for interest. You think something like this could be seen in future..?

**Comment by joseph-henry** [comment]
Thanks for this effort @oskarirauta there was a previous proposal you can find here: https://github.com/zerotier/ZeroTierOne/pull/1669 You may be able to adapt some of it to your particular case. That implementation triggers based on internal ZT events, and if you have any other questions I could help you out.

I do have a question however. Is there a reason that parsing `zerotier-cli -j listnetworks` for network statuses (or lack thereof) and `zerotier-cli -j listpeers` for last rx/tx times won't work for you?

It seems cleaner to me to write a script that periodically polls the ZeroTier service and regurgitates it into a form that your dashboard can use.

**Comment by oskarirauta** [comment]
Hey, #1669 seems to target exactly the same thing that I am after (without further studies on it..) - that's just great :)
Maybe it even fits perfectly on my needs, necessary information (interface) just needs to be queried with zerotier-cli, but that should not be a issue.

I did not do any further studies on it, but adding & to command-line did the trick, so I assume that when the script was executed with _system()_ it blocked the software, meaning that cli is not able to reply to any requests because socket won't answer to queries, since program is busy running command with system - is my opinion on what happened. Using & on end of the command, forks out and returns to software and because of that, is able to answer to request made by cli as operation no longer is blocking.

I have a question about #1669 - it is closed with comment no longer important. I assume this means that it isn't important specificly to you? I think this is still important, I am a little bias here, as I am using (and developing, but mostly for my own use cases...) openwrt system (tiny operating system mostly designed for routers, and with routers I mean those plastic boxes in electronic stores that have wifi and 4-5 rj45 ports, running with some sort of arm cpu with ofter less than 128mb ram - though, almost all my routers run x86-64 with more than one cores and gigabytes of ram and os on ssds..) - and even though openwrt is massive in count of users, I do realize that independent software development often does not target on one specific platform if it's designed on multiple platforms- and in this case, platform mostly is linux (can't say if **anyone** has need for this on bsd, but it has similarities..), and in my introduction I several times point to need on one specific distribution(openwrt), but if you google for this (tried to find out if someone else has already possibly made a patch set for this to work out..) - you actually DO find out that there are others asking for similar feature on platforms other than openwrt..

Won't be googling that information again, but I do remember that someone was querying this for support to ModemManager (though maybe later that has been added through ModemManager, hard to say as I don't use it, even though it's available for Openwrt as well, since I think it's overbloated and overcomplex on usage on such devices, even though mine have enough power even if os would be ran in virtualized environment, such as proxmox or vmware's exsi) and if I remember correctly, for some else systemd commonly used technique, this was asked.

Most operating systems do not provide a similar web interface for controlling them, and even users of openwrt- in cases when it's console only, without webui (LuCi) - do not need this, as they can query ip and details just by using ip or ifconfig, but like I said- I **do** see another uses for such feature, for example syncing things when connection is established or possibly automaticly connecting to services, or like I proposed, use your imagination, I just found this one and I am aware that in the community, I am not the only one looking forward to seeing something similar - as there are also some queries on how to succeed with this on openwrt's own forums.

So I was wondering; was the idea ditched completely, I do see that some (possible) issues were mentioned, but once again, code is alien for me, so I can't see how much there is to work with until reviewing it more, to fix mentioned issues- but I think that this feature could be re-thought as a feature- I can't see it's existence as harmful for users, even though they wouldn't utilize it......

So I was wondering, if that could be possibly re-opened - for openwrt, I could make a patch that would be used when building package, but at most times, things like these are wanted to be integrated in mainstream of software as there is a lot of work to keep patch working also in future versions of packaged software- and even though I do contribute to openwrt, I am currently having some time for unknown period yet due to employment reasons- later on, there propably is times that I can't and so a wanted feature stops co-existing when system already was built to depend on it more or less. I am maintainer for few packages on Openwrt, but there are longish periods, where I haven't had time to update packages and even though I love this so much, I'd rather see it in mainstream of software....

**Comment by oskarirauta** [comment]
@joseph-henry 

I took your commit to testing. I added
`signal(SIGCHLD, SIG_IGN);`
after
`long p = (long)fork();`

to avoid child zombie processes. I don't think zerotier should _manage_ scripts in any other way.. If they don't work.. Well, then they don't and that's that.. I also checked out mention to posix_spawn, but did not go there- I did not see advantages over it. In general, it's the same, but for systems without support for fork... Not sure, how often you come up with such system- first time ever that I hear about fork missing..

**Comment by oskarirauta** [comment]
@joseph-henry

previously mentioned issue exists also with your code- cli connection is blocked during call. I switched to system and added "&" to run script in background which solves the issue. But I could aswell do the same with execl - just would had to put full cmdline as first argument to succeed. It doesn't matter that we forked, program remains in ::waitpid and cannot answer to calls received. - propably by removing waitpid...... We could continue and cli access would remain. Not possibly that bad idea...

**Comment by oskarirauta** [comment]
doing it with execl failed, sticking with ::system

wow- got it. I had to add homepath as argument 2 for script as I have multiple instances running, so a "fixed" path to home, when using zerotier-cli -D<homepath> -j listnetworks was not a solution.

I have now zt0 and zt1 connected to 2 networks, both work perfectly. I'll make another branch later that contains source for this.

**Comment by oskarirauta** [comment]
@joseph-henry

Okay. I have finished my system specific scripts and support for zerotier protocol based on this is complete, and works when you have used network configuration to join either to single network, or multiple networks - or used a initscript to build connection either to one or more networks (though this feature isn't useful through initscript connection, but software has no issues and you **can** use scripting when you needed)

Just wondering- is there any point to make a PR here to get it to mainstream?

If script is used, it executes it with arguments "$state" "$networkid" "$homepath"
where state is either network_up, network_update or network_down

Script hook for network events can be enabled in either as a command-line argument:
`zerotier-one -s/path/to/script.sh` 
or from local.conf, here's a example:

```
{
	"settings":
	{
		"eventHookScriptPath": "/var/lib/zerotier-one/hook.sh"
	}
}

```
interface name and other information can be retrieved then with
zerotier-cli with -D_$homepath_ -j listnetworks for various tasks on event.

### Full changelog:
 - da0ed006e871c4c188839cfbdb7c51b89df3f0e5 - add network event script support

**Comment by joseph-henry** [comment]
There are five reasons that this and its associated PR https://github.com/zerotier/ZeroTierOne/pull/1862 cannot be accepted, each of which is enough on its own:

 1. As noted previously, this could be a potential security issue.
 2. The complexity that this introduces creates additional time costs in terms of testing and validating.
 3. This patch needs to be extended to multiple operating systems and maintained.
 4. This goes against ZeroTier's philosophy of trying to expose as few knobs as possible.
 5. We have already offered an alternative solution (polling the JSON output)

> I would also accepted just plain no

We do appreciate your effort but must politely decline this feature.
