### ISSUE TITLE
android apks not updated for several versions

### ISSUE THREAD

**Issue by dlaflamme** [zerotier/ZeroTierOne#1861]
As of today, the latest release is 1.10.2, but the apks available on https://download.zerotier.com/RELEASES/ haven't changed since 1.8.6, perhaps earlier. Is there are reason the android package is not being updated?

I am seeing instability where the connection drops and does not reconnect and want to ensure I am running the latest code.

**Comment by glimberg** [comment]
You're running the latest version as of right now.  We've recently hired a new dev for the mobile apps and updates are coming.  No ETA.

**Comment by dlaflamme** [comment]
Glad to hear, thanks.
