### ISSUE TITLE
sendFullHello in Peer::doPingAndKeepalive will never be true

### ISSUE THREAD

**Issue by yangst90** [zerotier/ZeroTierOne#1866]
# Before filing a Bug Report

_Using these will ensure you get quicker support, and make this space available for code-related issues. Thank you!_

- [Docs Site](https://docs.zerotier.com/zerotier/troubleshooting) => Troubleshooting, quickstarts, and more advanced topics.
- [Discuss Forum](https://discuss.zerotier.com/) => Our discussion forum for users and support to mutually resolve issues & suggest ideas.
- [Reddit](https://www.reddit.com/r/zerotier/) => Our subreddit, which we monitor regularly and is fairly active.
- [Knowledge Base](https://zerotier.atlassian.net/wiki/spaces/SD/overview) => Older wiki.

If you are having a connection issue, it's much easier to diagnose through the discussion forum or the ticket system. 

# If you still want to file a Bug Report

## Please let us know

- What you expect to be happening.
- What is actually happening?
- Any steps to reproduce the error.
- Any relevant console output or screenshots.
- What operating system and ZeroTier version. Please try the latest ZeroTier release.

**Comment by joseph-henry** [comment]
Please show your reasoning

**Comment by yangst90** [comment]
`  const bool sendFullHello = ((now - _lastSentFullHello) >= ZT_PEER_PING_PERIOD);
   _lastSentFullHello = now;`
should be like this:
` const bool sendFullHello = ((now - _lastSentFullHello) >= ZT_PEER_PING_PERIOD);
   if(sendFullHello)
      _lastSentFullHello = now;`

**Comment by laduke** [comment]
https://github.com/zerotier/ZeroTierOne/blob/666fb7ea2d7993bd47d3062dca3bb8dd1e1a87a5/node/Peer.cpp#L531-L534

**Comment by joseph-henry** [comment]
Thanks @yangst90 I believe you are correct for all cases except the initial case when a new peer is encountered. I've pushed a PR and it's awaiting review by the rest of the team. I'm going to close this ticket but please let us know if you find anything else.
