### ISSUE TITLE
Zerotier not working with ssh, but ping works

### ISSUE THREAD

**Issue by PeterWang-dev** [zerotier/ZeroTierOne#1868]
Ping looks good but ssh timeout. Android platform with version 1.8.9 works.
By the way, physical ip addresses in web admin displaying UNKNOWN. Relays can not be conneted except for moon.
Version: Zerotier One 1.20.2
Platform: Windows 11 22H2

**Comment by PeterWang-dev** [comment]
Things got wired. I had cleaned up peers.d and moons.d. Then picked .moon file from my linux client instead of using orbit command. After service had restarted, everything began to work.

**Comment by joseph-henry** [comment]
Thanks for reporting. Are you still seeing issues or can this ticket be closed?

**Comment by PeterWang-dev** [comment]
> Thanks for reporting. Are you still seeing issues or can this ticket be closed?

There was something wrong of planet server or my moon server. But now issue have been solved. By the way, the newest msi package goes wrong so that panel cannot be connected via UI.

**Comment by joseph-henry** [comment]
> By the way, the newest msi package goes wrong so that panel cannot be connected via UI

Ok, if this is an issue you're sure still exists we'd suggest making a separate ticket so we don't have to keep this solved one open. Let us know and we'll try to help. Thanks.
