### ISSUE TITLE
Start Problem with Arm V8

### ISSUE THREAD

**Issue by ehrenmann1977** [zerotier/ZeroTierOne#1873]
I am triying to run zerotier-one on arm v8 after installing it, but i get can not start issues

-----------------
admin@yomn:/volume1/@entware-ng/opt/bin$ sudo ./zerotier-one
zerotier-one: malloc.c:2395: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
Aborted
------------------

**Comment by joseph-henry** [comment]
We'll need more information about your setup. The issue ticket template shows you what we need.

OS / Exact CPU arch: `uname -a`
Version of ZeroTier
What commands you issued to install ZeroTier, etc

**Comment by paldier** [comment]
````
/jffs/softcenter/bin$ ./zerotier-one --help
ZeroTier One version 1.10.2
Copyright (c) 2020 ZeroTier, Inc.
Licensed under the ZeroTier BSL 1.1 (see LICENSE.txt)
Usage: ./zerotier-one [-switches] [home directory]

Available switches:
  -h                - Display this help
  -v                - Show version
  -U                - Skip privilege check and do not attempt to drop privileges
  -p<port>          - Port for UDP and TCP/HTTP (default: 9993, 0 for random)
  -d                - Fork and run as daemon (Unix-ish OSes)
  -i                - Generate and manage identities (zerotier-idtool)
  -q                - Query API (zerotier-cli)
/jffs/softcenter/bin$ uname -a
Linux RM-AX6000-D68E 5.4.179 #1 SMP Tue Feb 28 20:39:38 CST 2023 aarch64 ASUSWRT
````
entware uses entware's libc to run applications instead of your os's libc, so you can not run it via ./zerotier-one, you can try run `/volume1/@entware-ng/opt/init.d/zerotier start`.

**Comment by ehrenmann1977** [comment]
I dont have an init.d service file.
`admin@yomn:/volume1/@entware-ng/opt$ ls
bin  etc  home  lib  libexec  opt  root  sbin  share  tmp  usr  var
admin@yomn:/volume1/@entware-ng/opt$ cd bin
admin@yomn:/volume1/@entware-ng/opt/bin$ ls
ash  find  localedef.new  locale.new  netstat  opkg  sh  xargs  zerotier-cli  zerotier-idtool  zerotier-one
admin@yomn:/volume1/@entware-ng/opt/bin$`

I can call zerotier-one --help
`admin@yomn:/volume1/@entware-ng/opt/bin$ ./zerotier-one  --help
ZeroTier One version 1.10.2
Copyright (c) 2020 ZeroTier, Inc.
Licensed under the ZeroTier BSL 1.1 (see LICENSE.txt)
Usage: ./zerotier-one [-switches] [home directory]

Available switches:
  -h                - Display this help
  -v                - Show version
  -U                - Skip privilege check and do not attempt to drop privileges
  -p<port>          - Port for UDP and TCP/HTTP (default: 9993, 0 for random)
  -d                - Fork and run as daemon (Unix-ish OSes)
  -i                - Generate and manage identities (zerotier-idtool)
  -q                - Query API (zerotier-cli)
admin@yomn:/volume1/@entware-ng/opt/bin$`

**Comment by ehrenmann1977** [comment]
```
root@yomn:/volume1/@entware-ng/opt/bin# uname -a
Linux yomn 4.4.180+ #42962 SMP Tue Jan 31 23:16:54 CST 2023 aarch64 GNU/Linux synology_rtd1296_ds220j

root@yomn:/volume1/@entware-ng/opt/bin# cat /proc/cpuinfo
processor       : 0
model name      : ARMv8 Processor rev 4 (v8l)
BogoMIPS        : 54.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 1
model name      : ARMv8 Processor rev 4 (v8l)
BogoMIPS        : 54.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 2
model name      : ARMv8 Processor rev 4 (v8l)
BogoMIPS        : 54.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 3
model name      : ARMv8 Processor rev 4 (v8l)
BogoMIPS        : 54.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4
```

**Comment by ehrenmann1977** [comment]
```
root@yomn:/volume1/@entware-ng/opt/bin# ./zerotier-cli dump
Error connecting to the ZeroTier service: connection failed

Please check that the service is running and that TCP port 9993 can be contacted via 127.0.0.1.
```

**Comment by ehrenmann1977** [comment]
```
root@yomn:/volume1/@entware-ng/opt/bin# ./zerotier-one
zerotier-one: malloc.c:2395: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
Aborted (core dumped)
```

**Comment by ehrenmann1977** [comment]
is there a way to recompile zerotier-one on this device? unfortunately, my device is carrying traffic and real data .. this needs a new device to reach.

**Comment by joseph-henry** [comment]
New multi-arch images pushed: https://hub.docker.com/r/zerotier/zerotier-synology/tags

Please open a new ticket if you have any issues with these images.
