### ISSUE TITLE
Zerotier on Asus AC68U router with Asuswrt Merlin firmware doesn't work

### ISSUE THREAD

**Issue by pxc3113** [zerotier/ZeroTierOne#1876]
I installed Zerotier on my Asus AC68U router with Asuswrt Merlin firmware. However, after typing "zerotier-cli join id", according to ifconfig, zt adapter has no inet/inet6 address:

#ifconfig

ztr2qqzsbb Link encap:Ethernet HWaddr D6:E5:22:3A:CA:F2

UP BROADCAST NOTRAILERS RUNNING NOARP ALLMULTI MULTICAST MTU:2800 Me tric:1

RX packets:0 errors:0 dropped:0 overruns:0 frame:0

TX packets:0 errors:0 dropped:0 overruns:0 carrier:0

collisions:0 txqueuelen:500

RX bytes:0 (0.0 B) TX bytes:0 (0.0 B)

ztr2qqzsbc Link encap:Ethernet HWaddr D6:E5:22:3A:CA:F2

UP BROADCAST NOTRAILERS RUNNING NOARP ALLMULTI MULTICAST MTU:2800 Me tric:1

RX packets:0 errors:0 dropped:0 overruns:0 frame:0

TX packets:0 errors:0 dropped:0 overruns:0 carrier:0

collisions:0 txqueuelen:500

RX bytes:0 (0.0 B) TX bytes:0 (0.0 B)

admin@RT-AC68U-90E0:/tmp/home/root# zerotier-cli info

200 info f5b7cc126b 1.10.2 OFFLINE

admin@RT-AC68U-90E0:/tmp/home/root# zerotier-cli listnetworks

200 listnetworks <nwid> <name> <mac> <status> <type> <dev> <ZT assigned ips>

200 listnetworks 565799d8f69510d7 d6:e5:22:3a:ca:f2 REQUESTING_CONFIGURATION PR IVATE ztr2qqzsbb -

Router specs:

admin@RT-AC68U-90E0:/tmp/home/root# uname -a

Linux RT-AC68U-90E0 2.6.36.4brcmarm #1 SMP PREEMPT Fri Jan 6 15:04:31 EST 2023 armv7l ASUSWRT-Merlin

**Comment by joseph-henry** [comment]
That's a **very** old kernel, have you tried installing older versions of ZeroTier to see what happens?

**Comment by lmq8267** [comment]
我的也是ac-68u 使用的是 第三方的固件梅林 SWRT固件 软件中心下载的zerotier是1.10.2的 ifconfig 有ipv4和ipv6 不过NOARP 所以要开启arp才可以用  ifconfig 网卡名 arp 折腾了好久 一直都是只能1.4.6版本的 1.10.2怎么都无法用 最后发现arp默认关闭导致不能用

**Comment by pxc3113** [comment]
> That's a _very_ old kernel, have you tried installing older versions of ZeroTier to see what happens?

I've heard that on merlin, zerotier only works with 1.4.6 and under. I downgraded to 1.4.6 and now it works.

**Comment by lmq8267** [comment]
> > 那是一个_非常_旧的内核，您是否尝试安装旧版本的 ZeroTier 以查看会发生什么？
> 
> 我听说在 merlin 上，zerotier 只适用于 1.4.6 及以下版本。我降级到 1.4.6，现在它可以工作了。

不，目前我在用1.10.2的版本，![](https://github.com/lmq8267/softcenterarm/blob/master/1.10.2zerotier.PNG) 设备也是ac68u
