### ISSUE TITLE
Download Link on Website installs 1.10.5 on windows

### ISSUE THREAD

**Issue by wdarney** [zerotier/ZeroTierOne#1907]
Could be a typo or an unreleased version?

https://download.zerotier.com/dist/ZeroTier%20One.msi

**Comment by laduke** [comment]
1.10.5 is rolling out. Windows came out first. It probably won't be announced until monday. Sorry for the confusion.

**Comment by wdarney** [comment]
Thanks for the info and everyone's hard work on this amazing software.
