### ISSUE TITLE
Kill multicast rate limits inside ZT -- no longer needed, uses memory and CPU

### ISSUE THREAD

**Issue by mwarning** [zerotier/ZeroTierOne#191]
Entries from map  _multicastRateAccounts in node/Network.cpp do not seem to be removed anywhere.

**Comment by adamierymenko** [comment]
I've considered removing multicast rate limits, since it does sender-size replication. The sender incurs all bandwidth for multicast and if someone is screaming multicast on your network that's a problem with that participant.

**Comment by mwarning** [comment]
Yes, I agree. It would also safe a lot of resources.

**Comment by adamierymenko** [comment]
Yeah, let's do it. It's kind of left over from the old peer to peer distributed graph traversal algorithm, which I dumped for sender-side replication for various reasons. Simple is good.

**Comment by adamierymenko** [comment]
I actually like deleting code. Feels good. :)

**Comment by adamierymenko** [comment]
Let me do this one -- it touches a few things.

**Comment by mwarning** [comment]
So ... relieving, I was about to make a pull request. ;-)

**Comment by keesbos** [comment]
:-) And multicast can still be prohibited by filters (netflow). Or if you have an reasonable firewall implementation, rate limiting can be done too by the firewall.

**Comment by adamierymenko** [comment]
Yeah -- thing is, with sender-side replication the rate limits are not enforced except by the sender... so there's no security against flooding benefit here. That and a flooder pays all bandwidth, so there is no amplification attack.

In the old multicast propagation algorithm I had this rate limiting algorithm to prevent amplification attacks, but the whole thing was too complex/expensive compared to simple sender-side replication.

**Comment by heri16** [comment]
Please clarify the title that we are talking about multicast INSIDE a zerotier network.

**Comment by adamierymenko** [comment]
Yes, multicast inside a network.

**Comment by adamierymenko** [comment]
Not sure what other kind there would be.

**Comment by heri16** [comment]
The Bounjour Discovery Protocol for nodes to discover each other uses multicast instead of broadcasts, and works better in most kinds of multi-nat or multi-router scenarios.

**Comment by heri16** [comment]
May I ask, why is multicastLimit still inside the api for network controller configuration, if multicastLimit now means nothing?

**Comment by adamierymenko** [comment]
Different concept. The current multicastLimit is the maximum number of recipients. This was the maximum transfer rate.
