### ISSUE TITLE
Android apk outdated on zerotier.com

### ISSUE THREAD

**Issue by rgabbo** [zerotier/ZeroTierOne#1916]
The android app provided at the address https://download.zerotier.com/dist/ZeroTierOne.apk is quite outdated as it points to the version 1.8.6 while the latest on the Google Play Store is 1.10.5-1

**Comment by glimberg** [comment]
We're aware and it's intentional.  We're leaving it at an older version on the download page for now while issues some people are having with the latest from the Play store are taken care of.
