### ISSUE TITLE
Zerotier 1.10.5 adding firewall rules each time a network is joined/rejoined

### ISSUE THREAD

**Issue by DamonTek-Yuri** [zerotier/ZeroTierOne#1920]
Zerotier is creating a rule using the powershell cmdlet "New-FirewallRule" each time a network is joined, perhaps multiple times.

I routinely hop between networks and have noticed the ZeroTier service has been slower and slower to respond since upgrading recently (1.10.x versions I think). As it turns out I had over 10,000 Windows firewall rules allowing ICMP ping for specific ZeroTier routes. This bogged things down pretty badly.

The following powershell took quite a while to execute but did clear out the rules:

Get-NetFirewallRule | Where-Object DisplayName -Like "zerotier-icmpv4*" | Remove-NetFirewallRule

**Comment by erikh** [comment]
Probably a good argument for letting scripts be triggered by network join/leave/rejoin, if I may be so bold to suggest something.

------- Original Message -------

**Comment by laduke** [comment]
let us know if you're still seeing this.

**Comment by laduke** [comment]
Thank you. Leaving a network _should_ clear out all the dupe rules for that network. Stopping the zerotier service should clear out everything. 

But you can clean out them manually like you and DamonTek-Yuri say.

**Comment by dkeenleyside** [comment]
Just to let you know, I'm currently recovering a selection of servers from this.  I've had to work the night until quite early in the morning, and now early on the same morning again, to recover from this.  In the case of our site, the systems would suddenly slow to a crawl and become unusable.  The firewall entries are... incredibly long.

To regain control of servers, it was necessary to bypass domain login and enter as the local administrator, removing zerotier, and rebooting.  This also did not guarantee services would start properly on the reboot, so it's manual intervention time. 
 Afterwards, manual intervention to restart failed services and install 10.1.5 fixed most things up, except those long entries.
Stopping the zerotier service results in a very long wait time as the LocalServiceNoNetworkFirewall runs the filtering engine to clear the entries.  As a suggestion, it would be better to run the earlier mentioned powershell script, as it'll cause less downtime.

In the meantime, for other people's sanity, might I suggest you expunge the 1.10.4 download from Github here?  To prevent other people from encountering this immense excitement ;)

Systems encountering the apocalypse: Windows Server 2016, Windows 2019.

**Comment by dkeenleyside** [comment]
I can imagine the immense joy people must encounter as their server farms go down and PCs grind to a dying halt.  Have one final unit busy having a party with the script:
![image](https://user-images.githubusercontent.com/64942779/226789929-a3605789-ed2a-46ec-8938-ca184ece02e6.png)

**Comment by laduke** [comment]
dang it sorry, 1.10.5 should be tagged any minute now

**Comment by chuckofthenorth** [comment]
> dang it sorry, 1.10.5 should be tagged any minute now

Thanks!
