### ISSUE TITLE
[Debian] Zerotier service status showing active (running) but not actually working after system power on

### ISSUE THREAD

**Issue by wxrl** [zerotier/ZeroTierOne#1921]
## Environment

* [System] Linux 5.10.0-21-amd64 SMP Debian 5.10.162-1 (2023-01-21) x86_64 (Debian 11.6)
* [Zerotier] Version 1.10.5 (Installed via `apt` from `http://download.zerotier.com/debian/bullseye bullseye InRelease`) and there is a system service for zerotier

## Issue

* For about 80-90% of occasions, after completely powering on the Debian system, zerotier system service shows running as below but it's actually not working. (*Waiting for several minutes without actions doesn't solve the issue.*)
```
$ sudo systemctl status zerotier-one.service 
● zerotier-one.service - ZeroTier One
     Loaded: loaded (/lib/systemd/system/zerotier-one.service; enabled; vendor >
     Active: active (running) since Wed 2023-03-22 10:09:48 HKT; 1min 12s ago
   Main PID: 650 (zerotier-one)
      Tasks: 5 (limit: 28672)
     Memory: 8.7M
        CPU: 30ms
     CGroup: /system.slice/zerotier-one.service
             └─650 /usr/sbin/zerotier-one
```

* At this time, communications (`ping`, `http`, `samba`...) based on zerotier are not working. Also in the web panel (https://my.zerotier.com/network/xxx) it shows this Debian host is OFFLINE. And I'll have to **manually restart** the zerotier system service `sudo systemctl restart zerotier-one.service` to make it work...

Any ideas? Thanks!

**Comment by wxrl** [comment]
Yes I can talk with `zerotier-cli` when this problem happens.

There are some differences between the outputs of `zerotier-cli info -j` as listed below but none for `zerotier-cli listnetworks`

* Right after Debian system booted (zerotier system service showing active but zerotier not actually working, zerotier panel shows OFFLINE)

`~$ sudo zerotier-cli info -j
{
 "address": "********",
 "clock": 1680243906243,
 "config": {
  "settings": {
   "allowTcpFallbackRelay": true,
   "forceTcpRelay": false,
   "listeningOn": [
    "this-debian-host's-private-lan-ip/9993",
    "this-debian-host's-private-lan-ip/50068",
    "this-debian-host's-private-lan-ip/44193"
   ],
   "portMappingEnabled": true,
   "primaryPort": 9993,
   "secondaryPort": 32454,
   "softwareUpdate": "disable",
   "softwareUpdateChannel": "release",
   "surfaceAddresses": [],
   "tertiaryPort": 0
  }
 },
 "online": false,
 "planetWorldId": ********,
 "planetWorldTimestamp": 1644592324813,
 "publicIdentity": "********",
 "tcpFallbackActive": false,
 "version": "1.10.6",
 "versionBuild": 0,
 "versionMajor": 1,
 "versionMinor": 10,
 "versionRev": 6
}`


* After `sudo systemctl restart zerotier-one.service` (Everything works fine)

`~$ sudo zerotier-cli info -j
{
 "address": "a108feb2d1",
 "clock": 1680244048164,
 "config": {
  "settings": {
   "allowTcpFallbackRelay": true,
   "forceTcpRelay": false,
   "listeningOn": [
    "this-debian-host's-private-lan-ip/9993",
    "this-debian-host's-private-lan-ip/41070",
    "this-debian-host's-private-lan-ip/32395"
   ],
   "portMappingEnabled": true,
   "primaryPort": 9993,
   "secondaryPort": 0,
   "softwareUpdate": "disable",
   "softwareUpdateChannel": "release",
   "surfaceAddresses": [
    "this-debian-host's-public-wan-ip/41070",
    "this-debian-host's-public-wan-ip/1221",
    "this-debian-host's-public-wan-ip/32395"
   ],
   "tertiaryPort": 0
  }
 },
 "online": true,
 "planetWorldId": ********,
 "planetWorldTimestamp": 1644592324813,
 "publicIdentity": "********",
 "tcpFallbackActive": false,
 "version": "1.10.6",
 "versionBuild": 0,
 "versionMajor": 1,
 "versionMinor": 10,
 "versionRev": 6
}`

**Comment by wxrl** [comment]
I do have another **Raspberry Pi 4B** under the same LAN (router) with **Debian 11** `(6.1.19-v8+ #1637 SMP PREEMPT Tue Mar 14 11:11:47 GMT 2023 aarch64 GNU/Linux)`, but zerotier on this RPI doesn't seem having this issue.

**Comment by laduke** [comment]
Thanks. Interesting. Does `listnetworks` happen to say Port Error? 
I think zerotier must be trying to start before _something_ it assumes to be read is ready. 
Only guess right now is the tun module. You could dig through `journalctl --boot` or `dmesg` for clues? 
We have a similar report from a Windows user. Does the affected machine have multiple network interfaces?

**Comment by wxrl** [comment]
>> Does `listnetworks` happen to say Port Error?
No. The output of `zerotier-cli listnetworks` doesn't show differently when the Debian host is not actually connected.

The x86_64 Debian host (with this problem) has only 1 physical network IF (LAN-Cable connected directly from the router). It does not have on board Wi-Fi module:

```
$ ip addr
1: lo:
2: enp0s25:
3: ztyouxqhyd:
```

The RPI-4B (which doesn't reproduce this issue, under the same LAN/router) has both on board Wired LAN IF (**not** connected) and Wi-Fi (connected):

```
$ ip addr
1: lo:
2: eth0:
3: wlan0:
4: ztyouxqhyd:
5: docker0:
```

**Comment by wxrl** [comment]
In both situations (zerotier automatically brought up during system boot and failed to brought up during system boot), I am seeing the same boot msg with `zerotier-one[610]: sendto: Network is unreachable`

```
Apr 03 11:22:50 systemd[1]: Started ZeroTier One.
Apr 03 11:22:50 kernel: process '/usr/sbin/zerotier-one' started with executable stack
Apr 03 11:22:50 systemd[1]: Finished Permit User Sessions.
Apr 03 11:22:50 systemd[1]: Started Getty on tty1.
Apr 03 11:22:50 systemd[1]: Reached target Login Prompts.
Apr 03 11:22:50 kernel: capability: warning: `zerotier-one' uses 32-bit capabilities (legacy support in use)
Apr 03 11:22:50 zerotier-one[610]: sendto: Network is unreachable
```

**Comment by wxrl** [comment]
Also I'd say this is not a new issue for me ( = it's not a new issue in recent versions) - I've noticed it since at least 1.8.x but as I can always fix it by restarting the service after boot, it doesn't affect me seriously...

**Comment by erikh** [comment]
My guess is you need to adjust the systemd unit to add an After= clause to account for when your network comes up, it could be using a different name than the unit currently prescribes.

Alternatively, if you're on a wireless network something not-systemd could be initializing that -- e.g. NetworkManager, and causing this issue on boot, because until you get into your GUI the network will not be available.

A good solution for zerotier to implement, assuming I'm right, would be to loop slowly over "network unavailable" situations instead of terminating, but even if it does, systemd should try to respawn the process a number of times (it can be configured to loop endlessly, but it probably isn't right now). So assuming you get into your GUI fast enough, it should still work.

Can you give some perspective on how your network boots all the way until ping​ works?
------- Original Message -------

**Comment by erikh** [comment]
Another thing that might be happening is that nm or systemd hasn't created the interface yet, for whatever reason (e.g., a bridge needs to be created) and zerotier is trying to attach to a network that has no functional interface, gets fixated on that, so when your interface does come up, it doesn't know to look for it.

------- Original Message -------

**Comment by wxrl** [comment]
The "native" (generated by zerotier installation?) systemd service for zerotier contains `After=network-online.target network.target` already though...

```
[Unit]
Description=ZeroTier One
After=network-online.target network.target
Wants=network-online.target

[Service]
ExecStart=/usr/sbin/zerotier-one
Restart=always
KillMode=process

[Install]
WantedBy=multi-user.target
```

**Comment by wxrl** [comment]
The affected x86_64 Debian host is on wired LAN cable (no on-board Wi-Fi module or attached Wi-Fi dongle hardware installed on it.)
The non-affected RPI-4B (Raspbian) is on Wi-Fi.
They are under the same LAN (under the same router).

**Comment by erikh** [comment]
Ah. No idea, sorry. Hope it wasn't too much of a distraction!

------- Original Message -------

**Comment by wxrl** [comment]
Thanks! As said, it's not a serious issue for me (as of now) and there's already a "manual" fix whenever this happens.

I don't quite think this relates to hardware but just put my network hardware info here as the x86_64 Debian host is kinda old - 10 years+ but still working without noticeable hardware-related issues.

```
  *-network                 
       description: Ethernet interface
       product: 82579V Gigabit Network Connection
       vendor: Intel Corporation
       physical id: 19
       bus info: pci@0000:00:19.0
       logical name: enp0s25
       version: 04
       size: 1Gbit/s
       capacity: 1Gbit/s
       width: 32 bits
       clock: 33MHz
       capabilities: bus_master cap_list ethernet physical tp 10bt 10bt-fd 100bt 100bt-fd 1000bt-fd autonegotiation
       configuration: autonegotiation=on broadcast=yes driver=e1000e driverversion=5.10.0-21-amd64 duplex=full firmware=0.13-4  latency=0 link=yes multicast=yes port=twisted pair speed=1Gbit/s
```

**Comment by cmm** [comment]
I've started seeing this consistently just today (but today was the first time I've rebooted anything in a week or so).  My ZerotierOne version is 1.10.3, and has been for at least a month, so at first approximation this does not seem to be a client-side problem (apart from the client's failure to either recover or crash, that is, either of which would be an improvement).

I wish the system logs were more helpful, but "sendto: Network is unreachable" is all they offer.

**Comment by wxrl** [comment]
When zerotier meets `"zerotier-one[610]: sendto: Network is unreachable"` during boot (or anytime), my guess (in common sense) is that it's gonna retry after some time. But from the symptom, it seems that it fails to do so - not sure the client just went to halted state or was "killed" or just keeping failing to retry.

**Comment by laduke** [comment]
That message is from the upnp library. I don't think it's related to this issue. 

If anyone that can reproduce this can build zerotier `make ZT_DEBUG=1 ZT_TRACE=1 ZT_SSO_SUPPORTED=0` and copy the binary to /var/lib/zerotier-one, there will be more logs.

**Comment by Baloneo** [comment]
manjaro-kde has the same problem

**Comment by laduke** [comment]
Let us know if 1.12.1 didn't fix this. Thanks!
