### ISSUE TITLE
Synology

### ISSUE THREAD

**Issue by Elf36** [zerotier/ZeroTierOne#1935]
hi, I see the Official Synology Docker Image is quite old - I have installed it but it is at version 1.10.1 it is working - however is there any advantage to using a more up to date version ?

**Comment by joseph-henry** [comment]
Thanks. `1.10.6` image is up now.

**Comment by Elf36** [comment]
No it's very very slow - i have checked the Links with docker exec -it zt zerotier-cli peers and they all say DIRECT - but its terribly slow

**Comment by joseph-henry** [comment]
What model of device do you have? Many of of the processors Synology uses don't have HW crypto acceleration.

**Comment by Elf36** [comment]
it has this chip INTEL Xeon D-1521 model RS3618xs
