### ISSUE TITLE
Android App needs exclusion for Android Auto

### ISSUE THREAD

**Issue by jakevis** [zerotier/ZeroTierOne#1952]
In order to use Android auto, with VPN active, Android auto needs to be excluded. Right now, it is not, and as a result Android auto fails..

![Screenshot_20230402_155002_Android Auto.jpg](https://user-images.githubusercontent.com/10895705/229390203-644d36b2-e8ae-491e-a65c-95ad1536f710.jpg)

And config

![Screenshot_20230402_180414_ZeroTier One.jpg](https://user-images.githubusercontent.com/10895705/229390212-cb7471cc-d3b1-4d6f-afc3-a687ac464d39.jpg)

**Comment by jakevis** [comment]
Just bouncing this one to see if someone has a pointer as to the best way to get this fixed? 
Tailscale fixed this in their app last year... https://github.com/tailscale/tailscale/issues/3828

**Comment by bostick** [comment]
I will make sure that this is included in the next Android update, but there is currently no timeline for a release.

**Comment by jakevis** [comment]
> I will make sure that this is included in the next Android update, but there is currently no timeline for a release.

Guessing still no ETA yet?

**Comment by evzone** [comment]
Have had the same experience. Whenever I disable ZeroTier, Android Auto gets connected flawlessly.

**Comment by erikwachters** [comment]
+1

**Comment by michaelh99** [comment]
+1
The issue has been brought up repeatedly on the ZT forum with no replies

**Comment by luxdi** [comment]
+1
I used wireless Android Auto for the first time today and it took me quite a while to realise it was Zerotier that was causing the Error 21 VPN problem as highlighted by the OP. I even uninstalled OpenVPN and my VPN app until I figured out it was ZT (which I don't really see as a VPN) . I hope this can be sorted soon as I'm trying (and failing) to automate ZT disconnecting on AA start and reconnecting on AA exit. I access all my music remotely using ZT too, so now this won't work in AA in my car having to turn off ZT to get wireless AA to work.

**Comment by laduke** [comment]
We're working on it. Just waiting for the car to be delivered.

**Comment by comfuture** [comment]
Is there an update?

The Samsung Pay app also does not work when connected to a VPN.
Also, services that restrict GPS geolocation and Geo IP-based location will often refuse to run with a VPN running.
Google One VPN on Android, which is free for Google Storage purchasers, allows you to set certain apps to bypass the VPN.
You can use these apps without interference, even if you keep the VPN on all the time.

I would like to see Tailscale's Android app include a "VPN bypass feature".

**Comment by bostick** [comment]
The ZeroTier One Android app was updated back in October 2023 to exclude Android Auto.
