### ISSUE TITLE
ZT 1.10.6 Synology 7.1.1

### ISSUE THREAD

**Issue by Kente622** [zerotier/ZeroTierOne#1957]
Hi 

ZT for my NAS 

container keep loop below 
![ZT keep loops](https://user-images.githubusercontent.com/68109100/230212944-9f825eb9-bcab-49f9-bdd3-640ebfa5e39d.png)

and the status is offline 

please help 

Thanks
K

**Comment by pengjugame** [comment]
same problem

**Comment by joseph-henry** [comment]
Which models do each of you have?

**Comment by Kente622** [comment]
DS1621xs+

**Comment by Kente622** [comment]
> Which models do each of you have?

DS1621xs+

**Comment by joseph-henry** [comment]
From those logs it looks like ZT can't reach a root server. Make sure your firewall isn't blocking UDP/9993. Also when you run the container use `host` networking and make sure you give it sufficient privileges.

Also: new multi-arch images pushed: https://hub.docker.com/r/zerotier/zerotier-synology/tags

Please open a new ticket if you have any issues with these images.
