### ISSUE TITLE
Is Softonic APK download page legit?

### ISSUE THREAD

**Issue by kcpr** [zerotier/ZeroTierOne#1959]
Hi,

I was looking for a way to download the APK of latest version of the application without need to download it from Google. I stumbled upon this page and I wonder if it's legit and if You (as creators) approve it: https://zerotier-one.softonic.pl/android .

And, by the way, thank You for this software!

**Comment by joseph-henry** [comment]
No it is not an official download. We have no control over that so it could be tampered with in some way. Please only use our official APK found here:

http://download.zerotier.com/dist/

**Comment by kcpr** [comment]
Ok, thank You very much for the answer and also updating the APK available on the linked page. :)

Take care!
