### ISSUE TITLE
ZeroTier-API - online attribute disappeared

### ISSUE THREAD

**Issue by magynhard** [zerotier/ZeroTierOne#1960]
During the last few days, the `online` attribute has dissappeared when requesting all members of a network, e.g.:

```
GET https://api.zerotier.com/api/v1/network/<network-id>/member
```

Then i get

```json
[
  {
    "id": "xxx",
    "type": "Member",
    "clock": 1681146153942,
    "networkId": "xxx",
    "nodeId": "xxx",
    "controllerId": "xxx",
    "hidden": false,
    "name": "MemberName",
    "description": "",
    "config": {
      "activeBridge": false,
      "address": "xxx",
      "authorized": true,
      "capabilities": [],
      "creationTime": 1667841195856,
      "id": "xxx",
      "identity": "xxx",
      "ipAssignments": [
        "x.x.x.x"
      ],
      "lastAuthorizedTime": 1667841213505,
      "lastDeauthorizedTime": 0,
      "noAutoAssignIps": false,
      "nwid": "xxx",
      "objtype": "member",
      "remoteTraceLevel": 0,
      "remoteTraceTarget": "NULL      ",
      "revision": 14,
      "tags": [],
      "vMajor": 1,
      "vMinor": 10,
      "vRev": 2,
      "vProto": 12,
      "ssoExempt": false
    },
    "lastOnline": 1673112338790,
    "lastSeen": 1673112338790,
    "physicalAddress": "x.x.x.x",
    "physicalLocation": null,
    "clientVersion": "1.10.2",
    "protocolVersion": 12,
    "supportsRulesEngine": true
  }
]
```

I expect a boolean with the key `online` to be included as it was included around ten days ago.

So it is also still described in the docs:
https://my.zerotier.com/central-api.html#member-member-get

![image](https://user-images.githubusercontent.com/14541962/230957954-8076f7ff-295a-4f86-bd15-638a719ab36a.png)

I did not change anything on the clients or server.

**Comment by glimberg** [comment]
That is a very old version of the API docs that I didn't realize still existed.  Current up to date docs are [here](https://docs.zerotier.com/central/v1).  The "online" member was deprecated long ago and finally removed.    See our discussion board for more info https://discuss.zerotier.com/t/central-change-rollout-last-seen/12836
