### ISSUE TITLE
node/Utils.hpp:23:10: fatal error: 'string' file not found

### ISSUE THREAD

**Issue by gaochangw** [zerotier/ZeroTierOne#1966]
Got the following error message when run 'make' on Ubuntu 22.04 with clang installed for the 1.10.6 release.

clang++ -O3 -fstack-protector -Wall -Wno-deprecated -std=c++17 -pthread -Izeroidc/target -isystem ext -DNDEBUG -DZT_USE_MINIUPNPC -DMINIUPNP_STATICLIB -DMINIUPNPC_SET_SOCKET_TIMEOUT -DMINIUPNPC_GET_SRC_ADDR -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -DOS_STRING="\"Linux\"" -DMINIUPNPC_VERSION_STRING="\"2.0\"" -DUPNP_VERSION_STRING="\"UPnP/1.1\"" -DENABLE_STRNATPMPERR -DZT_SSO_SUPPORTED=1 -DZT_BUILD_PLATFORM=1 -DZT_BUILD_ARCHITECTURE=2 -DZT_SOFTWARE_UPDATE_DEFAULT="\"disable\"" -D_MT_ALLOCATOR_H -D_POOL_ALLOCATOR_H -D_EXTPTR_ALLOCATOR_H -D_DEBUG_ALLOCATOR_H -DZT_USE_X64_ASM_SALSA2012 -DZT_USE_FAST_X64_ED25519 -msse -msse2 -fPIC -fPIE   -c -o node/AES.o node/AES.cpp
In file included from node/AES.cpp:15:
In file included from node/AES.hpp:18:
node/Utils.hpp:23:10: fatal error: 'string' file not found
#include <string>
         ^~~~~~~~
1 error generated.
make: *** [<builtin>: node/AES.o] Error 1
xx@xx:~/Downloads/ZeroTierOne-1.10.6$

**Comment by glimberg** [comment]
For clang you may need to also install `libstdc++-12-dev`

**Comment by joseph-henry** [comment]
I also observed this on `Linux pop-os 6.2.6-76060206-generic`, your solution fixed my issue. I'm pretty confident it's the same for Ubuntu so I'm going to close this.
