### ISSUE TITLE
Healthcheck does not take into account  `ZEROTIER_JOIN_NETWORKS` variable, but only networks via args

### ISSUE THREAD

**Issue by stavros-k** [zerotier/ZeroTierOne#1977]
# Before filing a Bug Report

_Using these will ensure you get quicker support, and make this space available for code-related issues. Thank you!_

- [Docs Site](https://docs.zerotier.com/zerotier/troubleshooting) => Troubleshooting, quickstarts, and more advanced topics.
- [Discuss Forum](https://discuss.zerotier.com/) => Our discussion forum for users and support to mutually resolve issues & suggest ideas.
- [Reddit](https://www.reddit.com/r/zerotier/) => Our subreddit, which we monitor regularly and is fairly active.
- [Knowledge Base](https://zerotier.atlassian.net/wiki/spaces/SD/overview) => Older wiki.

If you are having a connection issue, it's much easier to diagnose through the discussion forum or the ticket system. 

# If you still want to file a Bug Report

## Please let us know

- What you expect to be happening.
- What is actually happening?
- Any steps to reproduce the error.
- Any relevant console output or screenshots.
- What operating system and ZeroTier version. Please try the latest ZeroTier release. 

https://github.com/zerotier/ZeroTierOne/blob/411e54023aa0b83d0c79ef91bbe2ddaec9422cd2/entrypoint.sh.release#L110

**Comment by erikh** [comment]
interpolating the variable in the template aughta work, you might have to double quote the "EOF" heredoc delimiter to get it to do so, however. I honestly can't remember with bourne shell now.

You won't be able to pass it, though. Just writing to make that clear.

Actually now that I think about it, it's probably already interpolating $@ so yeah, just including the var in the body of the template should work.
------- Original Message -------
