### ISSUE TITLE
ZeroTier Service delayed or failed Start on Windows 11 & Windows 10

### ISSUE THREAD

**Issue by tayvermtos** [zerotier/ZeroTierOne#1987]
Hi

The issue I'm experiencing is as follows:
When a Windows 10 or 11 machine is restarted, the zero-tier service starts automatically on startup. It shows in the GUI that it is connected to the relevant ZT network. However it isn't really connected. When checking via CMD (run as admin) what the status of zerotier is, it shows offline. The machine I'm testing with has got decent hardware, so startup of services wouldn't be delayed due to insufficient hardware resources. After around 5 minutes it shows as online.
On a different Windows 10 machine, zerotier wouldn't come online at all unless I manually restart the zerotier service. Both of these machines sit in a network which has got a draytek Vigor 2862 as a firewall and router. There are is a Synology NAS and a NVR in the same network which respective ports are opened to. 
I also tested this in a different network with multiple VMs (windows 10 and windows 11) which also show this kind of issue. In that network the VMs actually sit behind two firewalls, so main router for the building which is a microtic and then our own office one which is a old zyxel. The host of these VMs (in this case a windows 11 machine, powered by a solid ryzen 9 5950x) doesn't show any issues and is currently connected to 7 different networks. I do loose connectivity (for example in an active RDP session) when connecting, adding or disconnecting from or to a network. But I just have to reconnect and it works fine. I'm using the latest version of the zerotier windows client.

It seems that the restart of the zerotier service solves all issues and I'm not sure why. The problem is on remote machines where I haven't got an alternative access to that machine, restarting the service isn't an option unless you schedule a script to do so.

I'm happy to look into logs or participate into further testing so we can pin point and rectify the issue. 

Many thanks!

**Comment by wxrl** [comment]
The behavior looks similar as #1921 and  #1958

**Comment by goldenajj** [comment]
I have the exact same issue

**Comment by laduke** [comment]
Let us know if 1.12.1 didn't fix this. Thanks!
