### ISSUE TITLE
[Question] Synology already using /dev/net/tun for Docker image "gluetun", any possible work arounds?

### ISSUE THREAD

**Issue by ajtatum** [zerotier/ZeroTierOne#2015]
I've been using Tailscale for a while now but I recently discovered that with ZeroTier I get my own subnet, which would make whitelisting devices much easier than with Tailscale as the client IPs are all over the place. However, on my Synology (running DSM 7), I have a "gluetun" container running which connects to Mullvad VPN and in that Docker Stack for gluetun, I give it access to "/dev/net/tun". Reading about how ZeroTier works with Synology, it would seem that this would conflict with my gluetun container as they both would want access to "/dev/net/tun". Is there a way to create another tunnel such as /dev/net/tun02 for ZeroTier?

**Comment by joseph-henry** [comment]
Welcome. Seems like you could use `tunctl` to create another tunnel device but I haven't tried to do this myself. I'd look into that and if you get stuck come back and we can try to find a solution for you.

I think ZeroTier does specifically look for a `/dev/net/tun` in `osdep/LinuxEthernetTap.cpp` so making a new one with a different name might require a recompile.

**Comment by laduke** [comment]
multiple things can use `/dev/net/tun` at once though right?
