### ISSUE TITLE
[Feature Request] How to orbit moon on Mikrotik(rb5009) ? 

### ISSUE THREAD

**Issue by zikunh** [zerotier/ZeroTierOne#2021]
I have already created a moon on aliyun vps, and I have installed zerotier on my router mikrotik rb5009.

how can I orbit moon on my router? Thanks!

- **Device**: Mikrotik RB5009

- **OS Version**: v7.2.1

**Comment by laduke** [comment]
I think you will have to ask mikrotik. They maintain their own zerotier integration.

**Comment by yuwgle** [comment]
Can do  it now in 2026.
`/zerotier/import-moon moon=xxxxxxx zt1`

Then `xxxxx `should be a  `xxxxxx.moon`  file upload in routeros' file storage

**Comment by kostasoft** [comment]
RouterOs 7.23.1
Error: bad command name import-moon (line 1 column 11)
