### ISSUE TITLE
Zerotier shows offline in ubuntu 22.04 but windows works fine.

### ISSUE THREAD

**Issue by tarvfx** [zerotier/ZeroTierOne#2025]
# Before filing a Bug Report

_Using these will ensure you get quicker support, and make this space available for code-related issues. Thank you!_

- [Docs Site](https://docs.zerotier.com/zerotier/troubleshooting) => Troubleshooting, quickstarts, and more advanced topics.
- [Discuss Forum](https://discuss.zerotier.com/) => Our discussion forum for users and support to mutually resolve issues & suggest ideas.
- [Reddit](https://www.reddit.com/r/zerotier/) => Our subreddit, which we monitor regularly and is fairly active.
- [Knowledge Base](https://zerotier.atlassian.net/wiki/spaces/SD/overview) => Older wiki.

If you are having a connection issue, it's much easier to diagnose through the discussion forum or the ticket system. 

Yes, I searched all forums but the problem persists.

# If you still want to file a Bug Report

## Please let us know

- What you expect to be happening.

Zerotier is online

- What is actually happening?

With the same hardware configuration and the same operating system(`Ubuntu 22.04 64bit`) in the same LAN, only one computer works, and all other computers display offline. But if the operating system of those offline computers is replaced with windows10, it will work well. I also tried Ubuntu, Debian, Fedora but the result is the same. What can't be understood is that there is a computer that works just fine.

- Any steps to reproduce the error.

1. Install Ubuntu 22.04

Download ubuntu server version from Ubuntu official site

2. Turn off the ufw firewall

```shell
ufw disable
```

3. Install zerotier-one

```shell
curl -s https://install.zerotier.com | sudo bash
```

4. Detect whether zerotier is online

```shell
zerotier-cli info
```

- Any relevant console output or screenshots.

```shell
root@dev198:~# zerotier-cli info -j
{
 "address": "1b9eb172da",
 "clock": 1686646167395,
 "config": {
  "settings": {
   "allowTcpFallbackRelay": true,
   "forceTcpRelay": false,
   "listeningOn": [
    "192.168.0.198/9993",
    "192.168.0.198/35299",
    "192.168.0.198/26597"
   ],
   "portMappingEnabled": true,
   "primaryPort": 9993,
   "secondaryPort": 37789,
   "softwareUpdate": "disable",
   "softwareUpdateChannel": "release",
   "surfaceAddresses": [],
   "tertiaryPort": 0
  }
 },
 "online": false,
 "planetWorldId": 149604618,
 "planetWorldTimestamp": 1644592324813,
 "publicIdentity": "1b9eb172da:0:c9d9d2529fb3681d4be7b2567e6ed1b7f712a2af58eaf4bcc78205ad49f17021ea3309d1b2c0330c1af6c40ab81eedfaf71f33e7527e81d993a47eef24eb1889",
 "tcpFallbackActive": false,
 "version": "1.10.6",
 "versionBuild": 0,
 "versionMajor": 1,
 "versionMinor": 10,
 "versionRev": 6
}
root@dev198:~# zerotier-cli listpeers
200 listpeers <ztaddr> <path> <latency> <version> <role>
200 listpeers 62f865ae71 - -1 - PLANET
200 listpeers 778cde7190 - -1 - PLANET
200 listpeers cafe04eba9 - -1 - PLANET
200 listpeers cafe9efeb9 - -1 - PLANET
root@dev198:~# zerotier-cli peers
200 peers
<ztaddr>   <ver>  <role> <lat> <link>   <lastTX> <lastRX> <path>
62f865ae71 -      PLANET    -1 RELAY
778cde7190 -      PLANET    -1 RELAY
cafe04eba9 -      PLANET    -1 RELAY
cafe9efeb9 -      PLANET    -1 RELAY
```

- What operating system and ZeroTier version. Please try the latest ZeroTier release. 

operating system: Ubuntu 22.04 64bit (only one works well)
operating system: Windows 10 22H2 64bit (all works well)
ZeroTier : 1.10.6

**Comment by tarvfx** [comment]
After I have verified many times, in the same network environment, windows can work but Linux can't. Zerotier doesn't have any log output, so how do you determine the cause of the problem?

**Comment by laduke** [comment]
Hello. I made a fresh 22.04 vm and ran the zerotier install script, and it seems to work. 

Are the ubuntu computers clones, do they have the same zerotier identity? `/var/lib/zerotier-one` is where the identity is stored. 
Is the networking customized in any way on the ubuntus?

**Comment by tarvfx** [comment]
Hi, @laduke 

I'm not using a clone image. The OS is freshly installed and the IP and gateway are obtained automatically. There is only one network card onboard the motherboard. Zerotier has different identities, I can confirm that. I tried Ubuntu 22.04, Fedora 38 and debian 11, but the result is the same, but after I changed to Windows 10 it worked. I tried to build my own planet on Google Cloud, but the result is that Windows still works but Linux doesn't. I tested connectivity with `nc -vuz planetIP 9993` on Linux and it shows `Connection to planetIP 9993 port [udp/*] succeeded!`.

**Comment by laduke** [comment]
What type of router are you behind?

**Comment by tarvfx** [comment]
> What type of router are you behind?

The model of the router is ASUS AC86u.

I tried to use VMWare Workstation in Windows to install a virtual Ubuntu, but it also shows offline.

**Comment by tarvfx** [comment]
Zerotier display online under the OpenWrt system in vmware. 😂

**Comment by tarvfx** [comment]
Hi, @rcoder 

Thanks for following this question. I'm so sorry for the long delay. 

After I set my router to pppoe dialup all Linux systems work fine. But before that Zerotier was working fine on Windows, while it was offline on Linux.

> Can you confirm that you attempted to join the same network as you did on the Windows hosts

Yes, I'm sure both Linux and Windows are on the same network, I only have one router.

**Comment by MostHated** [comment]
I am having a similar issue. Only my Ubuntu desktop isn't working. Multiple phones, windows PC's and tablets, an Unraid server running ZeroTier in docker, as well as a Truenas system running zt in docker all work just fine, only my desktop isn't. I have has this network running just fine for about a year with no major changes to anything. Then all of a sudden the other day, I noticed I was offline for an hour. I tried restarting the services, etc, after a few minutes of fidgeting with it, it came back but this has seemingly been happening more often each day. Today, I have been in 'OFFLINE' status for 5 hours. I removed zerotier and reinstalled via the curl link, etc. Same thing, just shows 'OFFLINE' on Ubuntu while everything else is working as normal.

I am not sure if something changed with an update to Ubuntu, but I have been searching around different sites and noticed a number higher than none with the same symptoms. Can't say for sure it is completely related, but it feels like it might be.

**Comment by laduke** [comment]
Let us know if 1.12.x fixed this. Thanks!

**Comment by YRH0** [comment]
Check that firewall port 9993 is closed . sudo ufw allow 9993/udp

**Comment by joseph-henry** [comment]
Closing due to age, 1.12.X has connection related improvements and should fix this. If you're still experiencing issues please let us know and we can re-open this.
