### ISSUE TITLE
Wake from Sleep

### ISSUE THREAD

**Issue by DarkArc** [zerotier/ZeroTierOne#2026]
# What you expect to be happening.

When returning from sleep, ZeroTier quickly restores connectivity.

# What is actually happening?

ZeroTier is sluggish to reestablish connectivity, and displays something like the following (leaf IDs replaced with `X`s for privacy/security reasons):

```
XXXXXXXXXX 1.10.6 LEAF      -1 RELAY
XXXXXXXXXX 1.10.6 LEAF      -1 RELAY
XXXXXXXXXX 1.10.6 LEAF      -1 RELAY
62f865ae71 -      PLANET    -1 RELAY
778cde7190 -      PLANET    -1 RELAY
XXXXXXXXXX 1.10.6 LEAF      -1 RELAY
cafe04eba9 -      PLANET    -1 RELAY
cafe9efeb9 -      PLANET    -1 RELAY
```

# Any steps to reproduce the error.

This happens typically when a MacBook has been sleeping (I seem to notice this more when the Mac has been asleep longer, though I'm also seeing it if the Mac has been asleep for as little as a few hours). When it occurs, ZeroTier will take a while to reestablish connections (in the case of this computer boot somewhere between 1-2 minutes). It's often faster to restart the ZeroTier service on the CLI than wait for ZeroTier to recover normally, though this also doesn't always lead to an instantaneous recovery.

I think a close enough emulation is to disconnect from WiFi, restart ZeroTier so all connection information is lost/invalidated, then connect to WiFi.

# What operating system and ZeroTier version.

2017 Intel MacBook Pro - 2.8 GHz Quad-Core Intel Core i7 - MacOS 13.4
ZeroTier 1.10.6

**Comment by DarkArc** [comment]
So, this is related to https://github.com/zerotier/ZeroTierOne/issues/1779. I'm in a different hotel this time, and it's not really related to switching wifi or anything like that. I also noticed this at yet another hotel a few months ago.

This is somewhat of a bug report, and somewhat of a feature request. We're trying to use ZeroTier for remote work, and I really don't want to edit configuration files on folks computers to get a "snappy" experience with ZeroTier on the go.

I think what would make the most sense to _really_ address this is for the ZeroTier daemon to register event callbacks with MacOS so it's informed when the network state or the power state has changed (and then trigger it to check connections).

I _think_ how you'd want to do this is via the https://developer.apple.com/documentation/systemconfiguration/scnetworkreachability?language=objc API. However, that would require interfacing/using some Objective-C/Objective-C++ code on MacOS. There's also a much nicer type in Swift it seems, `NWPathMonitor`. Regardless... I'm not a Mac developer, but there's _got_ to be a way for a process to be informed that "the network connection is down -> the network connection is up", and react accordingly.

**Comment by laduke** [comment]
Thanks @DarkArc. This is somewhat of a known issue, and not just on macos. It's good to get some more traction on it. Part of the problem is the remote peer not knowing your IP address or port mapping has changed. 

If you look at `zerotier-cli info -j` you can see your "surfaceAddresses" These are the addresses:ports that the roots currently think you're reachable at. If that's interesting to you at all. 

The part where all your peers say RELAY is weird actually and may be a separate problem with sleep/wake.

**Comment by DarkArc** [comment]
So, looking at this a little further, it looks like https://github.com/zerotier/ZeroTierOne/blob/9b7d13476f2dd46a32ebbdaf051e92f0ba4c1702/osdep/MacDNSHelper.mm already provides an Objective-C++ precedent for MacOS specific compatibility.

Something similar should be possible for Linux I believe through notifier chains.

(Outside dev looking in quickly) I would expect, adding integration of these callbacks, followed by having ZeroTier check/rediscover connections would help immensely. I think ZeroTier does recover eventually, it's just not proactive enough as the usual checks just aren't quick enough.

----

@laduke to further this point, watching `zerotier-cli info -j` while doing the following:
- Stop networking
- Restart zerotier (everything is now clear, ZeroTier has no routes, no surface addresses, etc)
- Start networking

It takes zerotier a non-trivial amount of time before it even assigns (likely before it realizes it can assign) `surfaceAddresses` and then start restoring connections.

----

For fun I asked Google's Bard if it could help out 😅 (crazy times).

### MacOS

Sure, here is a callback for network up/down using SCNetworkReachability:

```c
void networking_callback(SCNetworkReachabilityRef target, SCNetworkReachabilityFlags flags, void *info) {
  // Check if the network is reachable.
  if (flags & kSCNetworkReachabilityFlagsReachable) {
    // Network is up.
  } else {
    // Network is down.
  }
}

int main() {
  // Create a reachability reference for the default network service.
  SCNetworkReachabilityRef reachability = SCNetworkReachabilityCreateWithName(NULL, "www.google.com");

  // Set the callback function.
  SCNetworkReachabilitySetCallback(reachability, networking_callback, NULL);

  // Start monitoring the network for changes.
  SCNetworkReachabilityScheduleWithRunLoop(reachability, CFRunLoopGetCurrent(), kCFRunLoopDefaultMode);

  // Do something else.

  // Unregister the reachability reference.
  SCNetworkReachabilityUnscheduleFromRunLoop(reachability, CFRunLoopGetCurrent(), kCFRunLoopDefaultMode);

  // Release the reachability reference.
  CFRelease(reachability);

  return 0;
}
```

This callback will be called whenever the network reachability changes. The flags argument will be a bitmask of the current network reachability flags. The info argument will be a pointer to the context information that was passed to SCNetworkReachabilitySetCallback().

The callback can be used to perform any necessary actions when the network reachability changes. For example, the callback could be used to start or stop a service that depends on the network being reachable.

### Linux

```c
void networking_callback(struct notifier_block *nb, unsigned long code, void *data) {
  if (code == NETIF_UP) {
    // Network is up.
  } else if (code == NETIF_DOWN) {
    // Network is down.
  }
}

int main() {
  struct notifier_block nb;

  // Initialize the notifier block.
  nb.notifier_call = networking_callback;
  nb.next = NULL;

  // Register the notifier block with the networking subsystem.
  notifier_chain_register(&notifier_chain, &nb);

  // Do something else.

  // Unregister the notifier block from the networking subsystem.
  notifier_chain_unregister(&notifier_chain, &nb);

  return 0;
}
```

This callback will be called whenever the network interface state changes. The code argument will be one of the following:

* NETIF_UP: The network interface is up.
* NETIF_DOWN: The network interface is down.

The data argument will be a pointer to the network interface structure.

The callback can be used to perform any necessary actions when the network interface state changes. For example, the callback could be used to start or stop a service that depends on the network interface being up.

**Comment by laduke** [comment]
Let us know if 1.12.1 didn't fix this. 

We didn't do the mac specific reachability testing yet. someday maybe
