### ISSUE TITLE
[Question] Where is the source of the file "planet"? 

### ISSUE THREAD

**Issue by cxzlw** [zerotier/ZeroTierOne#2035]
I have viewed the code "mkworld.cpp". But there are still two factors confusing me. 

1. There are some planet nodes that are not listed in the code "mkworld.cpp". Where can I find their identity like things in "mkworld.cpp"? 

2. If you delete the "planet" file, and restart the service, Zerotier will recreate a "planet" file. Where is it from (like a code generating them)?  

I would appreciate it if you could clear up my confusion.

**Comment by laduke** [comment]
Hello, 
basically, the output of mkworld is pasted into Topology.cpp 
What are you trying to do?
