### ISSUE TITLE
How to set up the moon node using the domain name but not the ip address？

### ISSUE THREAD

**Issue by mrppk** [zerotier/ZeroTierOne#2036]
How to set up the moon node using the domain name but not the ip address？

**Comment by mrppk** [comment]
I access the server through DDNS resolution and do not have a fixed ip address, so I need to consult this question？

**Comment by laduke** [comment]
Sorry, moons require an IP address. 
There may be some alternative in the future.

**Comment by ench2** [comment]
add a config file like config.json, {
   "server1":"http://xxx.com"
}
then change the node.cpp  read config.json,resovle domain to ip , connect
