### ISSUE TITLE
`secondaryPort` doesn't match `listeningAddresses`

### ISSUE THREAD

**Issue by laduke** [zerotier/ZeroTierOne#2039]
If you do `zerotier-cli info -j` you will see something like 

```
   "secondaryPort": 42955,
   "surfaceAddresses": [
    "192.168.82.207/9993",
    "192.168.82.207/58922",
    "192.168.82.207/51910",
   ],
   "listeningOn": [
    "192.168.82.207/9993",
    "192.168.82.207/58922",
    "192.168.82.207/51910",
    ]
```

The secondaryPort should match one of the ports in listeningOn/surfaceAddresses

On 1.10.6. I've looked at mac and linux. 

on mac:
`sudo lsof -aP -iUDP -iTCP -p $(cat /Library/Application\ Support/ZeroTier/One/zerotier-one.pid) `
I don't see "42955"

**Comment by joseph-henry** [comment]
I can't replicate this in linux or macOS. The ports match on my machine. Anything I should do to trigger this?

**Comment by laduke** [comment]
you on dev? mine actually says "0" for both now instead of a random wrong number. Do you have local.conf you need to remove?
