### ISSUE TITLE
Can't install without Windows Firewall

### ISSUE THREAD

**Issue by Vorshim92** [zerotier/ZeroTierOne#2057]
Hello! I'm sorry but I don't know how to bypass this...
I don't have a firewall right now on my Windows distro so I can't install it. Is there a way?
![image](https://github.com/zerotier/ZeroTierOne/assets/7747380/a433e798-e6f9-4eb1-b590-e6ec4123d49c)

**Comment by laduke** [comment]
why do you not have windows firewall?

**Comment by Vorshim92** [comment]
> why do you not have windows firewall?

It's just a gaming distro of windows without that. I just use it for gaming, nothing more.

**Comment by laduke** [comment]
Hey sorry we won't be able to work on this any time soon. You might be able to work around it somehow.
