### ISSUE TITLE
Provide easier access to zerotier-cli on Windows for systems that lack IE / can't run GUI wrapper.

### ISSUE THREAD

**Issue by adamierymenko** [zerotier/ZeroTierOne#206]
Add a rule to the MSI installer to warn Windows users if IE is too old -- if possible. A few Windows systems with 'broken Windows Update', etc., have ancient IE that won't work with our GUI.

**Comment by adamierymenko** [comment]
Retitled this issue since the interim solution is to provide easier access to the CLI for these (typically server oriented) Windows 'spins'. In the longer term we might look at moving away from the IE WebControl-based GUI wrapper, though I am hesitant to bundle 50mb+ of Chrome web code just to present a simple UI.

**Comment by maci0** [comment]
+1

**Comment by adamierymenko** [comment]
Done a while ago, now in current MSI.
