### ISSUE TITLE
iOS app connection issues on ZeroTier private networks

### ISSUE THREAD

**Issue by pirafrank** [zerotier/ZeroTierOne#2067]
**- What you expect to be happening.**
I expect devices on my ZeroTier private network to be reachable.

**- What is actually happening?**
Devices are not reachable on my ZeroTier network. The network is private and set to allow devices only when approved on the web admin GUI on my.zerotier.com. The devices in question have already been approved. 

**- Any steps to reproduce the error.**
1. connect to a private zerotier network using the latest version of zerotier for iOS (1.8.10 at the time of writing)
2. zerotier connects and VPN is displayed in iOS status bar
3. try to ping, ssh, reach an HTTP server or anything else exposed by one of the devices on the network, it doesn't work.

After many trials and errors, as workaround to make them connect:
1. disconnect iOS from the ZeroTier app
2. disable and re-enable the iOS devices from the web admin GUI
3. connect iOS from the ZeroTier app.

Unfortunately, this lasts until the client disconnects, which could happen for many reasons, which may not be in user control (e.g. iOS suspends VPN connections to save battery when in standby / screen goes off).

As further note I can say that Linux, OPNsense and Windows clients connect and are reachable on the same private network without any issues, even leaving zerotier enabled across reboots.

I have also noticed that the ZeroTier iOS app has not been updated in more than a year and that it is the only platform with core version on the 1.8.x branch. All others platforms have engines at version 1.10.x.

**- What operating system and ZeroTier version. Please try the latest ZeroTier release.** 
- iOS 16.5.1(c), but it's been like this since 16.4 at least.
- ZeroTier 1.8.10

note: updated to add timeout feedback.

**Comment by pirafrank** [comment]
**update** on this

It *seems* to be fixed by latest ZeroTier iOS app update.
No steps made on the my.zerotier.com dashboard. Everything still as stated above.
No steps made on iOS apart from updating the app from App Store while being disconnected from ZeroTier.
Details below.

ZeroTier app 1.12.0
iOS 17.0.2

Testing still going on. I'll report later on if the update fully resolves this issue.

**Comment by gbdrbob** [comment]
Thank you for the advice! I was experiencing exactly the same symptoms (no route from iOS device to other zerotier hosts) when connected using the lastes 12.10.0 version on iOS 16.7.1

Disabling and  re-enabling the phone in the my.zerotier.com control panel seems to have solved the issue, including across several disconnection/reconnection cycles, though it still takes some time (up to a minute) after the app says the zerotier connection is established before I can reliably connect to other hosts on the private network.

**Comment by pirafrank** [comment]
> **update** on this
> 
> It _seems_ to be fixed by latest ZeroTier iOS app update. No steps made on the my.zerotier.com dashboard. Everything still as stated above. No steps made on iOS apart from updating the app from App Store while being disconnected from ZeroTier. Details below.
> 
> ZeroTier app 1.12.0 iOS 17.0.2
> 
> Testing still going on. I'll report later on if the update fully resolves this issue.

Considering what's above and the amount of time passed, I think it is safe to close the issue.
