### ISSUE TITLE
Install script, building from source, joining networks/creating devices not working on Arch Linux

### ISSUE THREAD

**Issue by vanillyn** [zerotier/ZeroTierOne#2073]
Using ZeroTierOne on Arch Linux has been wildly confusing for me, pretty much none of the steps worked for me on a relatively clean install with all the dependencies.

First off, the install script doesn't work with Arch Linux at all, however there is an AUR package.
Using the AUR package works, however I am stuck at the common "`500 join{}`" error, for which none of the accepted fixes works. 
Using zerotier-one -U (fails with error `ERROR: unable to configure virtual network port: could not open TUN/TAP device: No such file or directory`, for which the proposed fix is to run chmod 777 /dev/net and chmod 777 /dev/net/tun, which doesn't work), zerotier-one -d, and running chmod on /dev/net and /dev/net/tun doesn't work.
Building from source fails with the error message seen below.

- What you expect to be happening: ZeroTier successfully creates the necessary devices for interfacing the networks and allows me to join, the install script successfully installs ZeroTier, the make script successfully builds ZeroTier
- What is actually happening? The result `500 join {}`, the install script not supporting Arch Linux and the make script seemingly not supporting it as well
- Any steps to reproduce the error. Follow the documentation on Arch Linux
- Any relevant console output or screenshots. 

error message seen when building ZeroTier
```
ext/prometheus-cpp-lite-1.0/core/include/prometheus/family.h:171:22: error: no member named 'invalid_argument' in namespace 'std'
          throw std::invalid_argument("Invalid metric name");
                ~~~~~^
ext/prometheus-cpp-lite-1.0/core/include/prometheus/family.h:176:24: error: no member named 'invalid_argument' in namespace 'std'
            throw std::invalid_argument("Invalid label name");
                  ~~~~~^
ext/prometheus-cpp-lite-1.0/core/include/prometheus/family.h:307:24: error: no member named 'invalid_argument' in namespace 'std'
            throw std::invalid_argument("Invalid label name");
                  ~~~~~^
ext/prometheus-cpp-lite-1.0/core/include/prometheus/family.h:309:24: error: no member named 'invalid_argument' in namespace 'std'
            throw std::invalid_argument("Label name already present in constant labels");
                  ~~~~~^
In file included from node/Metrics.cpp:13:
In file included from ext/prometheus-cpp-lite-1.0/simpleapi/include/prometheus/simpleapi.h:5:
ext/prometheus-cpp-lite-1.0/core/include/prometheus/registry.h:92:26: error: no member named 'invalid_argument' in namespace 'std'
              throw std::invalid_argument("Family name already exists with different type");
                    ~~~~~^
ext/prometheus-cpp-lite-1.0/core/include/prometheus/registry.h:97:30: error: no member named 'invalid_argument' in namespace 'std'
                  throw std::invalid_argument("Family name already exists");
                        ~~~~~^
ext/prometheus-cpp-lite-1.0/core/include/prometheus/registry.h:112:22: error: no member named 'invalid_argument' in namespace 'std'
          throw std::invalid_argument("Family name already exists with different labels");
                ~~~~~^
7 errors generated.
make: *** [<builtin>: node/Metrics.o] Error 1
```

- What operating system and ZeroTier version. Please try the latest ZeroTier release. 
ZeroTier One version 1.10.6 build 0 (platform 1 arch 2) (latest version on AUR)
Arch Linux, linux-6.4.4-arch1-1

I do not often see many issues from Arch Linux, perhaps its a unique distro issue

**Comment by vanillyn** [comment]
Though, there may be some fixes for some of the issues.
The ArchWiki simply mentions that restarting should work for fixing the TUN/TAP issue, and while it works in some cases, sometimes it doesn't and I haven't found out why yet.
The AUR package is on the latest version, so it may sometimes just be the repo itself being outdated.
As far as I know for the build errors, it may just not be build for Arch yet, I don't know.

**Comment by laduke** [comment]
It's in the arch repos. You can install with pacman. I'm not sure if you just want to install zerotier easily, or you want to build for a specific reason. 
It sounds like you `tun` module isn't loaded for some reason. `lsmod` `modprobe tun` 
Once it's installed you should start it with the systemd service

**Comment by laduke** [comment]
Let us know if the latest doesn't build. Thanks!
