### ISSUE TITLE
Document new controller metrics

### ISSUE THREAD

**Issue by rcoder** [zerotier/ZeroTierOne#2076]
We need to write up a short guide to using the new Prometheus metrics + scraper endpoint.

Metrics definitions are collected here: https://github.com/zerotier/ZeroTierOne/blob/dev/node/Metrics.hpp

**Comment by glimberg** [comment]
see here: https://github.com/zerotier/ZeroTierOne#prometheus-metrics

**Comment by rcoder** [comment]
Aha! Excellent. :)

I think it probably warrants a separate writeup in a more "HOWTO" style, but that shouldn't block anything.
