### ISSUE TITLE
Remote Access to IP Cameras

### ISSUE THREAD

**Issue by mpdog** [zerotier/ZeroTierOne#2077]
I'm not sure if I'm doing something wrong.

I need help for accessing IP cameras remotely, from another network.

I have an IP camera at home. I want to access it through my laptop.

I downloaded the ZeroTier client both on my home PC and on my laptop. Also, both devices are connected to my ZeroTier network and running Windows 11 (and both are authorized).

Then I tried to add the following route:
Destination: CameraIPv4/23 (I don’t know why I chose /23 but I guess it doesn’t matter)
Via my Home PC’s Zero Tier Managed IP.

Also, I used this commands on CMD to enable IPv4 forwarding on my home PC:
netsh interface ipv4 set interface "ZeroTier One [<peer id>]" forwarding=enabled
netsh interface ipv4 set interface "Ethernet" forwarding=enabled

What am I supposed to do now?
How can I check if it’s working?
How can I connect to the camera (and which ip should I connect to)?

**Comment by laduke** [comment]
https://discuss.zerotier.com/t/remote-access-to-ip-cameras/14727/2
