### ISSUE TITLE
Option to change default port on windows

### ISSUE THREAD

**Issue by maci0** [zerotier/ZeroTierOne#208]
Hi,

is there an option to change the default port on windows?
Setting -pXXXXX in services.msc and starting from there has no effect.

A friend of mine is getting connectivity issues with the default port 9993 looks like the isp (sonera) is messing up the udp traffic on that port. So the connection get established partially. but it never finds a datapath but also doesnt try https fallback either..
After he manually ran the client with -p69 -C it works like a charm.
We first suspected NAT issues but were able to pin it down to the port.

Maybe adding another API call to change the port setting and an option in the GUI would be good.
Making changes in the registry to pass parameters is not very user friendly

**Comment by adamierymenko** [comment]
ISPs mangling ports? Can't say I'm surprised. Adding to feature queue... just need to add awareness of the port flag to the service or some other method.

**Comment by adamierymenko** [comment]
This may be obviated by the binding of a secondary port, which is now in `dev`. Closing for now.

I also think it's possible to do this by editing the zerotier-one service and adding the -p argument there.
