### ISSUE TITLE
what happened when i stuck in REQUESTING_CONFIGURATION status ?

### ISSUE THREAD

**Issue by pikeai** [zerotier/ZeroTierOne#2087]
My zerotier client on my windows laptop seemed abnormal in last days like:
1. the status is "OK", but i cannot ping successfully with another linux server which running zerotier commonly
2. when i try to disconnect and reconnect to my network, the status changed to REQUESTING_CONFIGURATION and i can never never never get my private ip any more. Even though my laptop is seen online LESS THAN A MINUTE in my zerotier central

I tried reinstall zerotier,restart zerotier service , get another zerotier address,set a secondary port manually .However, nothing changed after doing these. By the way,all udp packets is allowed both in and out from my laptop.My gateway is an AC device and i permit any udp interact with my laptop,the NAT type is port restict cone NAT.

The only effect way is connecting to my phone hotspot. After doing this, if i switch to wired network environment above,things may be normal in half an hour to one hour even if my nat type is original symmetic NAT(modify the rule in AC device). After this time , it is still abnormal like my word above, unless i connect to hotspot again.

I captured packets on my laptop during this time. UDP 9993 ,the second and third port seemed common both in and out  with planet.
My question is : 
1. why client stuck in REQUESTING_CONFIGURATION status
2. what will client do when it stuck in REQUESTING_CONFIGURATION status ?reconnect?
3. what packet can i capture when it stuck in REQUESTING_CONFIGURATION status(if reconnect ,which protocol and port will use) ?
4. if ISP firewall intercept z0 packet，why anything is normal about half an hour after i disconnect to my mobile hotspot?

One probably reason i thought is : one authrorization step is timed out if i use CMCC ipv4 environment, and it is normal in ipv6, the authorization period is about half an hour.

**Comment by rust17** [comment]
Same with me.

**Comment by ZuozuoDev** [comment]
我的也是这样

**Comment by wongsyrone** [comment]
If all planets cannot be connected (shows RELAY), try `zerotier-cli leave <NET_ID>` , exits ZT service, deletes network.d and peer.d folders,  and `zerotier-cli join <NET_ID>`. Sometimes you have to setup a ZT TCP relay.

**Comment by rust17** [comment]
I think it has to do with the network line. It has been fixed automatically.

**Comment by laduke** [comment]
glad it's working
https://docs.zerotier.com/zerotier/troubleshooting#router-configuration-tips

**Comment by pikeai** [comment]
> glad it's working https://docs.zerotier.com/zerotier/troubleshooting#router-configuration-tips

no effect

**Comment by zrc0622** [comment]
When I connected to IPv6, I was able to connect to my server

**Comment by hiBlunt** [comment]
if you use linux, you can run `sudo apt purge zerotier-one -y && sudo rm -rf /var/lib/zerotier-one`, then reinstall zerotier. I fixed by this way
