### ISSUE TITLE
ZeroTier 1.12.0 Fails to Work on primary UDP port

### ISSUE THREAD

**Issue by DarkArc** [zerotier/ZeroTierOne#2105]
Once updating to ZeroTier 1.12.0, a Debian 11 Linux node (which cannot use port mapping) no longer functions.

Upon inspecting the `zerotier-cli info -j`, this seems to be because the primary port is not being added to the "listeningOn" IPs & ports.

When setting "portMappingEnabled" to `false` as a diagnostic step, the "listeningOn" ports curiously go to the value of "secondaryPort", primary port remains unlisted.

Downgrading to ZeroTier 1.10.6 (thank you for keeping the binaries in the repos), fixes this issue.

An alternative workaround is to force the "secondaryPort" to the port you need, and move "primaryPort" to something else (`/var/lib/zerotier-one/local.conf`):
````
{
  "settings": {
    "portMappingEnabled": false,
    "primaryPort": <random port you don't care about>,
    "secondaryPort": <desired port to listen to>
  }
}
````

**Comment by DarkArc** [comment]
I also anecdotally am seeing a higher time for ZeroTier to rediscover peers on the same LAN (which I recall being near instant). I suspect this is impacting (though not completely breaking) broadcast based peer discovery.

**Comment by wongsyrone** [comment]
https://github.com/zerotier/ZeroTierOne/commit/27a9cc6254304c318be0f1b75fddff47210c1d2f works well

**Comment by DarkArc** [comment]
> [27a9cc6](https://github.com/zerotier/ZeroTierOne/commit/27a9cc6254304c318be0f1b75fddff47210c1d2f) works well

What does that have to do with this issue?

**Comment by GreatMichaelLee** [comment]
Same issue +1, have to downgrade to 1.10.6 for workaround now, hope the fix ASAP. thanks.

**Comment by rcoder** [comment]
Thanks for the quick report! We're taking a look at this now.

**Comment by joseph-henry** [comment]
We've been able to replicate this and have a fix in the works.
