### ISSUE TITLE
1.12.0 on Raspbian includes unavailable `iproute` dependency

### ISSUE THREAD

**Issue by rcoder** [zerotier/ZeroTierOne#2106]
Originally reported here: https://discuss.zerotier.com/t/version-1-12-0-require-iproute-instead-of-iproute2-on-raspbian/15385

We've confirmed that the fix is simply dropping this dependency from the deb control file, since it isn't actually used in the ZT1 service any more.

Update is in progress and slated for the next patch release.

**Comment by glimberg** [comment]
Fixed
