### ISSUE TITLE
Authorization token or passphrase for networks

### ISSUE THREAD

**Issue by adamierymenko** [zerotier/ZeroTierOne#211]
Add a WiFi-style authentication token or passphrase -- or something like it -- to networks for auto-authorize.

**Comment by maci0** [comment]
+1

**Comment by mikebutash** [comment]
Some sort of lightweight captive portal http page to request information (who are you?) and hostname info, add to an approval queue of sorts (or auto-grant) would be nice for the controller function.

**Comment by adamierymenko** [comment]
Done in controller in `dev`.

**Comment by mrbluecoat** [comment]
Can you provide more detail on this capability? I'm also interested in the lightweight captive portal capabilities described above.
