### ISSUE TITLE
What kind of inbound firewall rules should I set? 

### ISSUE THREAD

**Issue by zhj9709** [zerotier/ZeroTierOne#2113]
Now there is no listening port 9993/udp

![image](https://github.com/zerotier/ZeroTierOne/assets/13991774/db288280-80a2-434b-9c99-6cab4c187962)
![image](https://github.com/zerotier/ZeroTierOne/assets/13991774/c0b139b9-3624-4b25-8551-84cb2725e9a9)

**Comment by glimberg** [comment]
What OS and version of ZeroTier are you running?  (There are reasons for the template we ask you to fill out to report bugs)

I'm assuming you're on Linux and version 1.12.0.  A fix for #2105 was rolled out today in 1.12.1

**Comment by zhj9709** [comment]
> What OS and version of ZeroTier are you running? (There are reasons for the template we ask you to fill out to report bugs)
> 
> I'm assuming you're on Linux and version 1.12.0. A fix for #2105 was rolled out today in 1.12.1

Linux，1.12.0
I will upate to 1.12.1，thanks。
