### ISSUE TITLE
1.12.1 Change in returned data type for fetching network members

### ISSUE THREAD

**Issue by sinamics** [zerotier/ZeroTierOne#2114]
### Description
The controller API used to return an Object with key-value pairs when fetching all members on a network. The latest version is returning an Array of objects instead. This conflicts with the existing API documentation.
https://docs.zerotier.com/service/v1/#operation/getControllerNetworkMembers

```bash
curl http://127.0.0.1:9993/controller/network/{network_id}/member \
-H 'Content-Type: application/json' \
-H 'X-ZT1-Auth: $Token'
```

## Please let us know
What operating system and ZeroTier version. Please try the latest ZeroTier release. 
- **Operating System**: Debian
- **ZeroTier Version**: 1.12.1

### Suggested Actions
If the change to an Array of objects as the return type was deliberate, then updating the API documentation to reflect this alteration is crucial for avoiding confusion.

Could you kindly clarify if the Array of objects is now the expected return format, or if this discrepancy is a bug that will be rectified?

**Comment by U11Leung** [comment]
I am coupling zt with ZeroUI, even on updated zt 1.12.1, members section is still not usable, but I see just blank response from zt backend api
