### ISSUE TITLE
Multiple managed routes cause connection to drop

### ISSUE THREAD

**Issue by bigzdog** [zerotier/ZeroTierOne#2124]
Network 1
10.0.0.0/24
10.0.0.55 Windows 10 running ZT 1.12.1
10.7.0.1 ZT address

Network 2
192.168.101.0/24
192.168.101.55 Windows 10 running ZT 1.12.1
10.7.0.5 ZT address

I have OpenVPN setup between these networks and it is working well however it is difficult to use on mobile so I am testing ZeroTier.

All my configuration, OpenVPN is disabled to avoid conflict. Also Win firewall is disabled

Initial config works fine. I can ping between ZT IP no problem.

I want to be able to access devices on either network so I setup managed routes.

10.0.0.0/23 via	10.7.0.1	
10.7.0.0/24 (LAN)	
192.168.100.0/23 via	10.7.0.5	

After setting up routes above, everything works for about 30 seconds. I can ping ZT IP, I can ping between devices on both networks then all pings drop for about 10 seconds then start for about 10 seconds on repeat

I found if I remove either route, then the connection is stable indefinitely, but obviously I can't access devices besides the one running ZT. I can have either one individually without issue, but if I add both I have huge packet loss.

**Comment by laduke** [comment]
Windows is acting as the router on both ends? We don't have much experience with that. 
There is a similar sounding issue on Opnsense/Freebsd. ZeroTier starts sending ZeroTier traffic over via the managed routes. 

Let us know if adding the local.conf file listed here helps:
https://docs.zerotier.com/devices/opnsense/

The location of local.conf is documented here https://docs.zerotier.com/zerotier/zerotier.conf

**Comment by bigzdog** [comment]
It definitely looks like the same issue. Watching the network traffic on ZeroTier interface will spike to 200mbps when the pings drop which is much higher than WAN speed.

Adding that local.conf to C:\ProgramData\ZeroTier\One prevents any traffic from passing, so now off to find out why that is.

**Comment by laduke** [comment]
Hmm. That config assumes the node is running on a router. So ZeroTier will connect with the WAN IP. 

You probably need to take out the 192.168.101 block on one side, and the 10.0.0.0/24 on the other?

**Comment by bigzdog** [comment]
Yup you are right. Take out the 10.0.0.0/8 on 10.0.0.0/24 side and take out 192.168.0.0 on 192.168.101.0 side. Thanks for the guide
