### ISSUE TITLE
Feature request: names in listpeers/listnetworks

### ISSUE THREAD

**Issue by prutschman** [zerotier/ZeroTierOne#213]
When I'm troubleshooting a connectivity issue I spend a lot of time comparing the output of listpeers or listnetworks to the admin panel. It would be helpful to (optionally) display friendly names. I would also find it helpful to (optionally) perform reverse lookup on the IP addresses shown in a routing path list.

**Comment by adamierymenko** [comment]
Where would the friendly names come from? DNS lookups are possible, but right now there's no support for names within the protocol itself. I've considered such meta-data, but wondered if it's something that should instead be handled by other services/protocols.

**Comment by prutschman** [comment]
The user-centric answer is "from the admin panel," but I appreciate that that's architecturally hairy. zerotier-cli name <nodeid> "Friendlyname"  could in principle be an entirely local option, though probably not one with wide enough utility to be useful. (At the moment I just have a sed script I pipe the zerotier-cli output through.)

In networks with zerotier managed IP addressing the DHCP server is in a position to know the hostname provided by the device when it requested a lease. Down that path lies reverse lookups of nodeid.networkname.zt and other such madness.

**Comment by adamierymenko** [comment]
Closing since this is out of scope and should be handled via ZeroTier Central and APIs, command line interfaces, etc.

**Comment by mrexodia** [comment]
I found this issue because I wanted to list all my networks with the client names/ip addresses, I forked a project [gozer](https://github.com/mrexodia/gozer) that does just this:

```bash
> gozer
1234567890abcdef network1 
     	mba_osx                   1111111111 [10.242.52.135]	
     	mba_windows               2222222222 [10.242.190.139]	 Offline
     	pizerow                   3333333333 [10.242.34.69]	
     	raspberrypi               4444444444 [10.242.227.38]	

fedcba0987654321 network2 
     	build_server              87e6c40c57 [192.168.193.2]	
     	mba_osx                   1111111111 [192.168.193.148]	
     	mba_windows               2222222222 [192.168.193.26]	 Offline
     	science                   5555555555 [192.168.193.218]	
     	thewolfgang               6666666666 [192.168.193.66]
```
