### ISSUE TITLE
ZeroTierOne in Docker with zerotier-cli 401 issue

### ISSUE THREAD

**Issue by hc8903** [zerotier/ZeroTierOne#2135]
In the file entrypoint.sh
there is an {echo} in mkztfile(), that cause the issue, should add "-n" to avoild add a new line to the auth file.

**Comment by joseph-henry** [comment]
I've replicated this and sure enough it can cause an issue if your provided environment variable has a newline in it but it should not since that is not part of the actual token per the spec. I think the problem lies elsewhere in your processing of the environment variable. Good luck!

**Comment by hc8903** [comment]
> I've replicated this and sure enough it can cause an issue if your provided environment variable has a newline in it but it should not since that is not part of the actual token per the spec. I think the problem lies elsewhere in your processing of the environment variable. Good luck!

I use the docker image (zerotier/zerotier:latest), when specify the ENV "ZEROTIER_API_SECRET" and run zerotier-cli CMD, I will get the 401 error.
