### ISSUE TITLE
zerotier-cli on Ubuntu 14.04: missing port and zerotier-one.port not found in /var/lib/zerotier-one

### ISSUE THREAD

**Issue by surfnet-niels** [zerotier/ZeroTierOne#214]
After installing zerotier-one_1.0.3_amd64.deb on ubuntu 14.04 LTS starting the cli client yields:

niels@M0ped:~$ zerotier-cli
zerotier-cli: missing port and zerotier-one.port not found in /var/lib/zerotier-one

contents of /var/lib/zerotier show:
niels@M0ped:/var/lib/zerotier-one$ ls -l
total 612
-rwxr-xr-x 1 root root   2461 jun  3 02:01 uninstall.sh
drwxr-xr-x 2 root root   4096 jul 22 23:26 updates.d
-rwxr-xr-x 1 root root 618304 jun  4 03:02 zerotier-one

Running cli client with the port parameter return expected output:
niels@M0ped:/var/lib/zerotier-one$ zerotier-cli -p auto
ZeroTier One version 1.0.3
(c)2011-2015 ZeroTier, Inc.
Licensed under the GNU General Public License v3

Usage: zerotier-cli [-switches] <command/path> [<args>]

Available switches:
  -h                 - Display this help
  -v                 - Show version
  -j                 - Display full raw JSON output
  -D<path>           - ZeroTier home path for parameter auto-detect
  -p<port>           - HTTP port (default: auto)
  -T<token>          - Authentication token (default: auto)

Available commands:
  info               - Display status info
  listpeers          - List all peers
  listnetworks       - List all networks
  join <network>     - Join a network
  leave <network>    - Leave a network

**Comment by adamierymenko** [comment]
The service probably isn't started. The package usually won't do that by default. Type "sudo service zerotier-one start" (I think).

**Comment by surfnet-niels** [comment]
thx, that solve the issue. Might be good to add this to the docs somewhere.

**Comment by mikebutash** [comment]
Same issue here, second the mention of adding to linux startup docs (ubuntu here), or have your package start the service on install.  Most packages tend to start if a service anyways, didn't expect to have to start this manually on install either, and error was cryptic to throw wtf's to start googling.

**Comment by lpflhh** [comment]
zerotier-one -d
