### ISSUE TITLE
rulesSource not save on POST

### ISSUE THREAD

**Issue by aruznieto** [zerotier/ZeroTierOne#2140]
- What you expect to be happening.
When I do a POST over {{baseUrl}}/network/:networkID, with body:
```
{
    "rulesSource": "accept;"
}
```

Controller should save this rulesSource and create the rules.

- What is actually happening?
The controller not save this options.

- Any steps to reproduce the error.
On Postman, try to save rulesSource on a self-host controller

- What operating system and ZeroTier version. Please try the latest ZeroTier release. 
1.12.2

**Comment by glimberg** [comment]
The self hosted controller is only a subset of the API provided at https://my.zerotier.com.  One of the things the self hosted controller does not have is the full rules compiler, or the `rulesSource` argument.  You can use the node.js based rule compiler [here](https://github.com/zerotier/ZeroTierOne/tree/dev/rule-compiler) and use the output `rules`, `tags`, etc in the post to `/controller/netowrk/${NETWORK_ID}`.  The OpenAPI spec for the self hosted controller can be found [here](https://docs.zerotier.com/openapi/servicev1.json)

**Comment by aruznieto** [comment]
> You'll have to define tags in the ruleset for tags to come out

Know, I´m doing it

**Comment by sinamics** [comment]
@aruznieto for info, you can see how i implemented it here.
https://github.com/sinamics/ztnet/blob/dc5ba24bd85bce79a3233892a8b57002a9d15075/src/server/api/routers/networkRouter.ts#L678
