### ISSUE TITLE
Android APK Update

### ISSUE THREAD

**Issue by mkyrd** [zerotier/ZeroTierOne#2142]
I see that the apk provided at http://download.zerotier.com/dist/ is from April. Are there any plans on updating this app to a newer build? As a de-googled phone user I appreciate you publishing the apk, I just am wary that it is so old.

Thanks!

**Comment by bostick** [comment]
The Android app was updated earlier today and https://download.zerotier.com/dist/ now has the latest (1.12.0-3)
