### ISSUE TITLE
Failed to find OpenSSL development headers

### ISSUE THREAD

**Issue by AhJi26** [zerotier/ZeroTierOne#2146]
I have already installed openssl but I still get a error when I make Zerotier.
How can I fix it?

Part of log:

      The following warnings were emitted during compilation:
      
      warning: In file included from /usr/include/openssl/opensslv.h:109,
      warning:                  from build/expando.c:1:
      warning: /usr/include/openssl/macros.h:14:10: fatal error: openssl/opensslconf.h: No such file or directory
      warning:    14 | #include <openssl/opensslconf.h>
      warning:       |          ^~~~~~~~~~~~~~~~~~~~~~~
      warning: compilation terminated.
      
      error: failed to run custom build command for `openssl-sys v0.9.91`
      note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true       environment variable to enable debug information generation.
      
      ...
      
       Header expansion error:
        Error { kind: ToolExecError, message: "Command \"cc\" \"-O3\" \"-ffunction-sections\" \"-fdata-sections\" \"-fPIC\" \"-m64\" \"-I\" \"/usr/include\" \"-Wall\" \"-Wextra\" \"-E\" \"build/expando.c\" with args \"cc\" did not execute successfully (status code exit status: 1)." }

        Failed to find OpenSSL development headers.
      
        You can try fixing this setting the `OPENSSL_DIR` environment variable
        pointing to your OpenSSL installation or installing OpenSSL headers package
        specific to your distribution:

      # On Ubuntu
      sudo apt-get install libssl-dev
      # On Arch Linux
      sudo pacman -S openssl
      # On Fedora
      sudo dnf install openssl-devel
      # On Alpine Linux
      apk add openssl-dev

**Comment by rcoder** [comment]
It sounds like your OpenSSL installation doesn't have all of the development headers included. What OS are you building on, and how did you install OpenSSL?

If you haven't already tried the instructions at the bottom of the error that are appropriate to your environment please do and let us know if that helps.

**Comment by joseph-henry** [comment]
Closing due to age. If you're still experiencing this issue please let us know.
