### ISSUE TITLE
Cannot ping idle machine under firewall

### ISSUE THREAD

**Issue by victorgveloso** [zerotier/ZeroTierOne#2147]
Context:

I have a computer in a university lab, a desktop at home, and a MacBook. The university's firewall prevents any requests to the machine in my office. In this case, I decided to use a private ZeroTier network to connect all these three machines.

Motivation:

A traditional VPN would not work for me because

1. I usually shut down my desktop at home when I stop using it (to save on energy bills).
2. I carry the MacBook everywhere and connect to different networks.
3. My lab's computer is unreachable outside.

This setting means I do not have any computer suited for being a VPN server. 

The problem:

Sometimes my lab computer loses connection to the other peers despite reporting an OK connection status with my network. That means I cannot access through SSH from either my MacBook or my Desktop. Yesterday, I executed "zerotier-cli peers" while that was happening, and the result showed four PLANETs and no LEAF. A few minutes later, I connected FROM my lab computer TO my home desktop and it worked. This time, re-running "zerotier-cli peers" showed a different result, all the same four PLANETs were there as well as three LEAFs.

My workaround:

Since this is my first experience with ZeroTier I could not fix this problem directly, which prevents me from connecting to my lab's computer. Alternatively, I configured a SystemD service in my lab's computer that starts an SSH tunnel to my home computer. It retries the connection forever until it succeeds. I use this connection to access my lab PC from my home desktop and do an ssh connection back to my desktop, which seems to temporarily fix my ZeroTier network peers connection.  I do not like this solution for two reasons
1. I need to turn on my desktop and wait a few minutes until the connection is made.
2. I need to be either at home or at my lab to fix the connection manually.
3. It relies on an SSH tunnel, which is also prone to fail and should not be required at all.

How do I prevent my computer from losing connection to the other peers in my ZeroTier network? Why is such a thing happening?

Computer specs:

- MacBook Air M2 macOS Ventura 13.5.1
  - ZeroTier v1.10.6
  - Suspend very often
  - No firewall, never fail to connect to home
- Desktop: Arch Linux (+ KDE)
  - ZeroTier v1.12.2
  - Shutdown/Suspend sometimes
  - No firewall, never fail to connect to mac 
- Lab: Arch Linux (+ Gnome)
  - ZeroTier v1.10
  - Network has a firewall that blocks inbound traffic in any port but enables both TCP and UDP outbound traffic.
  - Unreachable by home and Mac unless I ping them first, i.e., loses connection when idle
  - Always on, never suspends ([Auto suspend is disabled](https://wiki.archlinux.org/title/GDM#GDM_auto-suspend_(GNOME_3.28))).

**Comment by laduke** [comment]
first step is update zerotier to the latest version

**Comment by victorgveloso** [comment]
Came to my office today and updated the ZeroTier versions. 

I did a new test and the following thing happens:

<img width="562" alt="image" src="https://github.com/zerotier/ZeroTierOne/assets/11022419/3ea3a2a0-c1c1-4eee-aa08-afb2e888e7e0">

When my laptop and my lab computer are in the same network they can connect to each other. However, my home computer cannot see them. Conversely, both the laptop and the lab computer see the home computer.

The home computer starts to see any computer X as soon as I establish an SSH connection from X to the home computer.

**Comment by laduke** [comment]
Have the lab computer `ping` your other computers once every few seconds or minutes. 

We're always trying to improve and find new tricks for making connections, but we have no way to reproduce and then work on this specific scenario. So for now you're stuck with workarounds or making friends with the network people at your university.

**Comment by victorgveloso** [comment]
> Have the lab computer `ping` your other computers once every few seconds or minutes. 
> 
> We're always trying to improve and find new tricks for making connections, but we have no way to reproduce and then work on this specific scenario. So for now you're stuck with workarounds or making friends with the network people at your university.

Should I close this issue, then?

**Comment by laduke** [comment]
We're curious to know if the `ping` trick is helping.

**Comment by victorgveloso** [comment]
Yes, I did the cronjob that pings all the other machines every minute and it has worked so far.
