### ISSUE TITLE
Is there a way to specify a node to force TCP relay?

### ISSUE THREAD

**Issue by init-object** [zerotier/ZeroTierOne#2150]
I have some cross-border nodes
It is faster to use direct for vps in the same country
It is faster for multinational nodes to use tcp relay because udp will be speed limited by qos
If forceTcpRelay:true is used, all nodes will use tcp relay, causing nodes in the same area to use relays, increasing delay.

**Comment by laduke** [comment]
Sorry, tcp relay is a node setting, not a per peer setting. Eventually there will be more transports available.
