### ISSUE TITLE
GET http://localhost:9993/status X-ZT1-Auth:... fails over IPv4 but works over IPv6 

### ISSUE THREAD

**Issue by dch** [zerotier/ZeroTierOne#2151]
## Please let us know

There's a regression between 1.12.0 and 1.12.1 that breaks ipv4 localhost query
via `zerotier-cli info`. I've only just noticed while adding a new node that
this is broken.
 
Under v1.12.1:

```
# sudo zerotier-cli status
401 status {}

# zerotier-cli dump
Error connecting to the ZeroTier service: {}

Please check that the service is running and that
TCP port 9993 can be contacted via 127.0.0.1.

# sockstat -46lp 9993
USER     COMMAND    PID   FD  PROTO  LOCAL ADDRESS         FOREIGN ADDRESS
root     zerotier-o 85664 7   tcp4   *:9993                *:*
root     zerotier-o 85664 8   tcp46  *:9993                *:*
root     zerotier-o 85664 14  udp4   10.0.0.112:9993       *:*
```

But clearly the daemon *is* up, and listening.

We'd like to see, as under previous versions, the info.

Under v1.12.0:

```
> sudo zerotier-cli info
200 info 7c5005f22b 1.12.0 ONLINE
```

- environment is ansible-managed
- runs ZT since over a decade probably
- OS: FreeBSD (various versions)
- ZT: v1.12.2 (everywhere)
- `authtoken.secret` hasn't changed in years on nodes

Running the same thing using tcpdump/ngrep, we see that this is basically the same as running an HTTP `GET` to `http://localhost:9993/status` with header `X-ZT1-Auth:my_secret` so let's do that with curl:

```
$ curl -v http://localhost:9993/status -4HX-ZT1-Auth:...
< HTTP/1.1 401 Unauthorized
...
{}

$ curl -v http://localhost:9993/status -6HX-ZT1-Auth:...
< HTTP/1.1 200 OK
...
{"address":"9bbbdbfdd2","clock":1697648307359,"config":{"settings": ....}
```

The `-v4` version should be authorized correctly, but isn't, whether via `zerotier-cli` or `curl`.

**Comment by laduke** [comment]
Hello! Thanks for reporting. This isn't happening on my mac; both curl -4 and curl -6 work. So that's strange. 

Are there any error messages when zerotier is starting up?

**Comment by dch** [comment]
No, there's no error messages that I see running a `gmake -j debug` flavoured build. This only occurs on FreeBSD ofc. I'll throw some printfs in and see what happens. the only change beween 1.12.0 and 1.12.1 is this splitting of address functionality for linux.

**Comment by dch** [comment]
ok I think we can see why the auth fails :D but do the numbers here mean anything to you?

 if (remoteAddr.ipScope() == InetAddress::IP_SCOPE_LOOPBACK) { 
```
zt1flo98dm17np8
authCheck: /status
remoteAddr.ipScope() = 4
IP_SCOPE_LOOPBACK() = 2
```

**Comment by laduke** [comment]
> but do the numbers here mean anything to you?

Not really but they're in here 
https://github.com/zerotier/ZeroTierOne/blob/9ae8b0b3b60b27cf06d7e74629c17e4a0f248364/node/InetAddress.cpp#L29

I'm curious what remoteAddr actually is? I think you can print it like this:

```
char buf[64];
fprintf(stderr, "remoteAddr %s\n", remoteAddr.toIpString(buf));
```

**Comment by dch** [comment]
interesting:

```
$ doas ngrep -qid lo0 -W byline port 9993
interface: lo0 (127.0.0.0/255.0.0.0)
filter: (ip or ip6) and ( port 9993 )

T 127.0.0.1:10178 -> 127.0.0.1:9993 [AP]
GET /status HTTP/1.1.
X-ZT1-Auth: qrasbyedsabltduqypok8lqo.
.


T 127.0.0.1:9993 -> 127.0.0.1:10178 [AP]
HTTP/1.1 401 Unauthorized.
Content-Length: 2.
Content-Type: application/json.
Keep-Alive: timeout=5, max=5.
.


T 127.0.0.1:9993 -> 127.0.0.1:10178 [AP]
{}
```

```
$  doas ./zerotier-one /var/db/zerotier-one/
Starting Control Plane...
Starting V6 Control Plane...
ztagim5o45dhe4c
zt1flo98dm17np8
authCheck: /status
remoteAddr.ipScope() = 4
IP_SCOPE_LOOPBACK() = 2
remoteAddr ::ffff:127.0.0.1
```

something in between the IP stack (as seen by ngrep output) and zerotier turns this into a
v6v4 sort of thing.

**Comment by laduke** [comment]
That's really strange. I don't think we'll be able to do a fix and release in a timely fashion. You might be able to put `::ffff:127.0.0.1` in your [local.conf](https://github.com/zerotier/ZeroTierOne/tree/dev/service) `allowManagementFrom` as a work around.

**Comment by dch** [comment]
That specific pattern didn't work, in the end I used `::` and rely on the per-node authsecret and local firewall rules for security. Is that sufficient? It's certainly not ideal :-(

**Comment by laduke** [comment]
Seems like it to me, but I don't know the threat model, your requirements, etc...

remove `127.0.0.1       localhost` from /etc/hosts  :)

**Comment by dch** [comment]
This basically broke new zerotier installs on all FreeBSD and TrueNAS systems, you can't add nodes unless find this issue.

Any chance this could get addressed for [1.14](https://github.com/zerotier/ZeroTierOne/milestone/6)? The fix is likely to be quite trivial, to add the missing match to [InetAddress.cpp](https://github.com/zerotier/ZeroTierOne/blob/6be0e67a5cc147b6d0ca55cb91f923fdc73c69a3/node/InetAddress.cpp#L26-L153).

In [OneService.cpp#L1601-L1610](https://github.com/zerotier/ZeroTierOne/blob/dev/service/OneService.cpp#L1601-L1610) `
if (remoteAddr.ipScope() == InetAddress::IP_SCOPE_LOOPBACK) {`

is called with these values:

```
zt1flo98dm17np8
authCheck: /status
remoteAddr.ipScope() = 4
IP_SCOPE_LOOPBACK() = 2
remoteAddr ::ffff:127.0.0.1
```

According to [InetAddress.hpp#L67C1-L67C75](https://github.com/zerotier/ZeroTierOne/blob/6be0e67a5cc147b6d0ca55cb91f923fdc73c69a3/node/InetAddress.hpp#L67C1-L67C75) `::1` is a `IP_SCOPE_GLOBAL` which seems bizarre.

AFAICT this is an error in [InetAddress.cpp](https://github.com/zerotier/ZeroTierOne/blob/6be0e67a5cc147b6d0ca55cb91f923fdc73c69a3/node/InetAddress.cpp#L26-L153) which decides that `0xff_ff_7f_00_00_01` or something similar to that in whatever internal representation is used, is not local.

I will test on FreeBSD 13.x and 14.x again to see what I can track down, in particular what the memory representation of `::ffff:127.0.0.1` is, which is what is needed to check against.

**Comment by laduke** [comment]
yeah lets take a look

**Comment by dch** [comment]
OK it aint pretty, but it *does* fix the issue... over to you c++ gurus to make it pretty/correct:

```diff
diff --git a/node/InetAddress.cpp b/node/InetAddress.cpp
index da1c7294..7a786e49 100644
--- a/node/InetAddress.cpp
+++ b/node/InetAddress.cpp
@@ -112,6 +112,20 @@ InetAddress::IpScope InetAddress::ipScope() const
                }       break;

                case AF_INET6: {
+         // Check for IPv4-mapped IPv6 addresses (::ffff::/96 prefix)
+            const struct sockaddr_in6* sa6 = reinterpret_cast<const struct sockaddr_in6*>(this);
+            if (sa6->sin6_addr.s6_addr[0] == 0 && sa6->sin6_addr.s6_addr[1] == 0 &&
+                sa6->sin6_addr.s6_addr[2] == 0 && sa6->sin6_addr.s6_addr[3] == 0 &&
+                sa6->sin6_addr.s6_addr[4] == 0 && sa6->sin6_addr.s6_addr[5] == 0 &&
+                sa6->sin6_addr.s6_addr[6] == 0 && sa6->sin6_addr.s6_addr[7] == 0 &&
+                sa6->sin6_addr.s6_addr[8] == 0 && sa6->sin6_addr.s6_addr[9] == 0 &&
+                sa6->sin6_addr.s6_addr[10] == 0xff && sa6->sin6_addr.s6_addr[11] == 0xff) {
+                // next 4 bytes should be IPv4 address 0x7f000001 / 127.0.0.1
+                uint32_t ipv4Part = *(reinterpret_cast<const uint32_t*>(&sa6->sin6_addr.s6_addr[12]));
+                if (ipv4Part == htonl(0x7f000001)) {
+                    return IP_SCOPE_LOOPBACK;
+                }
+            }
                        const unsigned char *ip = reinterpret_cast<const unsigned char *>(reinterpret_cast<const struct sockaddr_in6 *>(this)->sin6_addr.s6_addr);
                        if ((ip[0] & 0xf0) == 0xf0) {
                                if (ip[0] == 0xff) {
diff --git a/service/OneService.cpp b/service/OneService.cpp
index b06bcb9b..8f52ce58 100644
--- a/service/OneService.cpp
+++ b/service/OneService.cpp
@@ -1697,8 +1697,14 @@ public:
                                bool ipAllowed = false;
                                bool isAuth = false;
                                // If localhost, allow
+                               char buf[64];
+                               fprintf(stderr, "remoteAddr %s\n", remoteAddr.toIpString(buf));
                                if (remoteAddr.ipScope() == InetAddress::IP_SCOPE_LOOPBACK) {
+                                       fprintf(stderr, "ALLOWED\n");
                                        ipAllowed = true;
+                               } else
+                               {
+                                       fprintf(stderr, "DENIED\n");
                                }

                                if (!ipAllowed) {
```

**Comment by dch** [comment]
was this perhaps a change in the underlying httplib that passes a different form of remote address through?

**Comment by laduke** [comment]
Not sure yet. Thanks for working on it. 
Even `curl -v -4 "http://127.0.0.1:9993/status` pops out as ::ffff:127.0.0.1 inside of zerotier-one, but not on other operating systems.

**Comment by laduke** [comment]
The httplib unsets the IPV6_V6ONLY socket option. 
https://github.com/yhirose/cpp-httplib/commit/b2203bb05aa241a3dd00719c8afd07d82900ba3d

This seems to make all IPv4 requests come in with the ::ffff:, as a v6 to 4 mapping thing. 

Making it parse ::ffff:127.0.0.1 as loopback works. 

But it also does the 6 to 4 thing to other ip addresses:

`curl -4 "http://45.32.69.185:9993/` -> `::ffff:45.32.69.185`
which might make configuring things like "allowManagementFrom" a little weird. 

[this patch](https://github.com/zerotier/ZeroTierOne/commit/0c194cb68b1aa614bf7c287cae252a169b19c867) also makes it work. Maybe we can make that a FreeBSD specific patch or something.

**Comment by dch** [comment]
Your improved version of my ugly hack looks great, let's roll - thanks!

BTW I tested [this patch](https://github.com/zerotier/ZeroTierOne/commit/0c194cb68b1aa614bf7c287cae252a169b19c867) and wasn't able to run `info` or `join ...`.

Perhaps, for a dual-stack address like `localhost` the AF_INET6 branch
never actually gets reached?

**Comment by dch** [comment]
thanks, works a treat. I pulled this into FreeBSD 1.12.2 as an upstream patch.
