### ISSUE TITLE
ZEROTIER + VPN SERVER in DSM 7.2.1 NOT WORKING

### ISSUE THREAD

**Issue by pitiriguisvi** [zerotier/ZeroTierOne#2153]
- What you expect to be happening: work together zerotier + vpn server on synology dsm 7.2.1
- What is actually happening? as soon as i enable the zerotier docker, the network interface inside vpn server disapears and im unable to use vpn server. 
- Any steps to reproduce the error: install zerotier via docker following the main manual and execute it. Open vpn server and go to general configuration: try to select some network interface
- Any relevant console output or screenshots.
- What operating system and ZeroTier version. Please try the latest ZeroTier release.: DSM 7.2.1-69057 Update 1. ZEROTIER-SYNOLOGY:LATEST

**Comment by joseph-henry** [comment]
When you run the container use `host` networking and make sure you give it `high privileges` if you're using `Container Station`.

Also: new multi-arch images pushed: https://hub.docker.com/r/zerotier/zerotier-synology/tags

Please re-open a ticket if you have issues with the new images.
