### ISSUE TITLE
ZeroTier does not work on Ubuntu 23.10 error while loading shared libraries: libssl.so.1.1

### ISSUE THREAD

**Issue by OscarParzon** [zerotier/ZeroTierOne#2154]
Ubuntu 23.10

install
installed with the recommended script

result when trying to run: 
"zerotier-one: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory"

**Comment by alatteri** [comment]
current work around below.  not ideal

```
wget -N -O /tmp/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
sudo -E apt-get -y reinstall /tmp/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
```

**Comment by adamierymenko** [comment]
We're adding this to our build set, so it should be fixed soon.

**Comment by Danathar** [comment]
I'm running Ubuntu 23.10. I had the same error. I changed the repository to bookworm. It had put in buster. Rebooted and it worked.

**Comment by Danathar** [comment]
> I don't know why no one is advising this option:
> 
> Snap Package "Snaps are containerised software packages that are simple to create and install. They auto-update and are safe to run. And because they bundle their dependencies, they work on all major Linux systems without modification."
> 
> https://docs.zerotier.com/snap/

Because of two reasons. The first and I've opened a separate issue, is that the snap on snapcraft store is almost a year out of date. Secondly, the snap account Zerotier has is not a verified account.

If you are security conscious those two reasons are enough not to recommend the snap for now.

**Comment by laduke** [comment]
give the installer a try now

**Comment by laduke** [comment]
🎉

**Comment by alatteri** [comment]
This is still a problem with Ubuntu 24.04
