### ISSUE TITLE
zerotier is not available on fedora systems

### ISSUE THREAD

**Issue by OoGod** [zerotier/ZeroTierOne#2160]
**Reproduction steps**(reproducibility rate 100%)
1. Install os using fedora 37/38 version
2. After the installation is complete, download zerotier and configure the zerotier service;
3. It cannot communicate with other devices after configuration; 

**resource link:**
fedora 38 link: 
https://fedoraproject.org/server/download/ 
qcow2: https://download.fedoraproject.org/pub/fedora/linux/releases/38/Server/x86_64/images/Fedora-Server-KVM-38-1.6.x86_64.qcow2

**Configure zerotier**
```
## install
curl -s https://install.zerotier.com/ | sudo bash
## config
zerotier-cli info
zerotier-cli join xxxxxxxxx
zerotier-cli listnetworks

```
**Check that the zerotier configuration is normal**
'zerotier-cli info' status is online
The result of 'zerotier-cli listnetworks' shows ok

**but ping check failed**
However, after configuration, the device cannot ping other devices, and other devices cannot ping the device; Other devices ping each other normally

**Comment by blwvirus89** [comment]
facing similar issues on Ubuntu containers. have tried several versions. this used to work fine.
ZT shows online
Dashboard sees client
BUT!!!
network traffic is not flowing
and ZT is NOT creating a virtual network adapter (ex ztxxxx)
I have failed to find a solution to this in my googling.

Cons to this issue no new linux systems can be introduced to the ZT network.

**Comment by inudev3** [comment]
@OoGod have you found any solutions?
my system does the same. 
fedora 39 asahi linux aarch64
zerotier-cli  info and status is online
and listnetworks show that ip is assigned
but it doesnt appear on dashboard.
@blwvirus89 any idea?

**Comment by joseph-henry** [comment]
> and listnetworks show that ip is assigned

...

> but it doesnt appear on dashboard.

You mean it doesn't show up in the ZeroTier central UI?

If you've got an IP assigned by the controller this should be showing up in the Central UI. I don't think I've ever seen a case where it wasn't.

If you can reproduce your error please open another ticket with the steps for us to try and we can work on it there. This is unlikely to be related to the existing ticket.

Good luck!
