### ISSUE TITLE
Will not run on Windows Server Core

### ISSUE THREAD

**Issue by electricduck** [zerotier/ZeroTierOne#217]
Installed ZeroTier onto Windows Server 2012R2 and it will not run; I presume to do with the fact quite a lot of core components found in the standard Windows Server are not available in Core.

Here's what happens when its ran...
![](http://z54314.bsx.fr/~/ducky/onedrive/screenies/%CE%A8200/Windows-6.1.7601.Pro/0959.png)

I'm guessing its going to have something to do with this bug: https://github.com/zerotier/ZeroTierOne/issues/206. As I said, IE is not available in WSC. Being able to use a CLI version from Windows would be a bonus, since Windows Server is heading in the direction of not having a GUI by default.

**Comment by adamierymenko** [comment]
You can use the command line interface for now:

    \ProgramData\ZeroTier\One\zerotier-one.exe -q help

That should display help. The -q option invokes the 'zerotier-cli' binary personality. This will need to be done from an administrator shell.

We're probably going to dump the embedded IE control in favor of something else. It isn't reliable.

**Comment by adamierymenko** [comment]
Closing since this is issue #206 -- need to provide easier access to CLI for Windows versions that cannot run the UI.
