### ISSUE TITLE
[Feature Request] Auto update moon to the latest one

### ISSUE THREAD

**Issue by basncy** [zerotier/ZeroTierOne#2170]
I have a script that re-generate the moon file when dynamic IP changes, and syncing the folder /var/lib/zerotier-one/moons.d 
 with syncthing on Linux/Windows.

zerotier do NOT update moon file once "orbit" it, can it auto-update when discover new one? This change won't introduce DNS.

Thank you!

**Comment by joseph-henry** [comment]
Moons are meant to have static IPs. I believe if you're using dynamic IPs you're going to need to `deorbit` and re-`orbit`.
