### ISSUE TITLE
System Service Error - ZeroTier-one not working on Intel Base MacOS

### ISSUE THREAD

**Issue by devopswe** [zerotier/ZeroTierOne#2171]
**What you expect to be happening.**
Running ZeroTier without any problems. 

**What is actually happening**

![image](https://github.com/zerotier/ZeroTierOne/assets/32529331/e1ef1239-2aec-4be1-98f4-535d286e4ce5)
"Waiting for ZeroTier System Service Error" and ZeroTier MacOS client not working. 

**Any steps to reproduce the error.**

While opening Zerotier Client only and show "Waiting for ZeroTier System Service Error"

**Any relevant console output or screenshots.**

My System Info: 
![image](https://github.com/zerotier/ZeroTierOne/assets/32529331/19379b1a-e4dc-4eb8-94ec-b478249ed52d)

Launchctl load and bootstrap tries: 
![image](https://github.com/zerotier/ZeroTierOne/assets/32529331/9d2b3616-891f-49c9-88b3-5e8f3b667c6e)

 /Library/LaunchDaemons/com.zerotier.one.plist launchctl commands got I/O Errors.

/Library/Application Support/ZeroTier/One directory not found error like above. 

**Tried Solutions;**

* Uninstall with script and reinstall Zerotier Client
* Remove everything about ZeroTier, reinstall again
* Same things and tried Zerotier reinstall with homebrew and with site installed package.  

**What operating system and ZeroTier version. Please try the latest ZeroTier release**

Using latest version for macOS and ZeroTier client. 

MacOS - Intel Based - Ventura 13.6.1 (22G313) - MacBook Pro 15-inch, 2017 
ZeroTier Version: zerotier-one: 1.12.2 - Version 1.0 

I've tried with these ways too: 
* https://download.zerotier.com/dist/ZeroTier%20One.pkg <- 
* with brew Downloading https://download.zerotier.com/RELEASES/1.12.2/dist/ZeroTier%20One.pkg <-

**Comment by laduke** [comment]
haven't seen that before. try rebooting. is the mac os firewall enabled?

**Comment by devopswe** [comment]
> haven't seen that before. try rebooting. is the mac os firewall enabled?

Yes I've already tried that things too. OS Firewall disabled and rebooted SMC + PRAM NRAM resetted etc.

**Comment by laduke** [comment]
is there any output when you start zerotier-one directly?

`sudo launchctl unload /Library/LaunchDaemons/com.zerotier.one.plist` (stop the service)

`sudo /Library/Application\ Support/ZeroTier/One/zerotier-one`

**Comment by devopswe** [comment]
> is there any output when you start zerotier-one directly?
> 
> `sudo launchctl unload /Library/LaunchDaemons/com.zerotier.one.plist` (stop the service)
> 
> `sudo /Library/Application\ Support/ZeroTier/One/zerotier-one`

Yes, I've got bootstrap failed Input/Output errors when I run that commands.

**Comment by laduke** [comment]
please post the output of `sudo /Library/Application\ Support/ZeroTier/One/zerotier-one`

**Comment by devopswe** [comment]
> sudo /Library/Application\ Support/ZeroTier/One/zerotier-one

![image](https://github.com/zerotier/ZeroTierOne/assets/32529331/954bfa9e-ad96-45a7-9a62-035550a85c3f)

Stuck like that and nothing happen.

**Comment by laduke** [comment]
It's possible it's running successfully if that's all you see. Try `zerotier-cli`  in a different terminal while that's going. 

Also please post `sudo lsof -aP -n -iUDP  -iTCP | grep zerotier`  when that is running. 

I'm not sure what would cause the service to not work. Some kind of apple security thing maybe.

**Comment by devopswe** [comment]
> It's possible it's running successfully if that's all you see. Try `zerotier-cli` in a different terminal while that's going.
> 
> Also please post `sudo lsof -aP -n -iUDP -iTCP | grep zerotier` when that is running.
> 
> I'm not sure what would cause the service to not work. Some kind of apple security thing maybe.

When I've run app with `sudo /Library/Application\ Support/ZeroTier/One/zerotier-one` only services start like that. Not working without opening app only. 

<img width="884" alt="image" src="https://github.com/zerotier/ZeroTierOne/assets/32529331/c98cf043-354b-4881-b53e-b25124ce9b7e">

but launchctl commands cause getting errors again while using different terminal :/ 

<img width="1132" alt="image" src="https://github.com/zerotier/ZeroTierOne/assets/32529331/8c798636-bfcd-43c4-90a3-1ecbd3a79ccd">

**Comment by devopswe** [comment]
Thanks for ZeroSupport. When I run that commands with `sudo su -` 

```
scandinavia:~ root# launchctl unload /Library/LaunchDaemons/com.zerotier.one.plist
scandinavia:~ root# killall zerotier-one
scandinavia:~ root# launchctl load -w /Library/LaunchDaemons/com.zerotier.one.plist
scandinavia:~ root# zerotier-cli listnetworks /*
200 listnetworks <nwid> <name> <mac> <status> <type> <dev> <ZT assigned ips>
``` 

When running launchctl load command with `-w` parameter, it works.

**Comment by badboy-tian** [comment]
+1
