### ISSUE TITLE
Many members with -1.-1.-1 version

### ISSUE THREAD

**Issue by spiderrr** [zerotier/ZeroTierOne#2179]
Hello, I would like to report a software bug that I encountered while using the app. When I open zerothier central I see many members with -1.-1.-1 version from one adress, .  Can you please check what is wrong and fix this issue? Thank you for your help.

- What you expect to be happening. -> Stop generating this records
- What is actually happening? -> They keep generating
- Any steps to reproduce the error. - log in to  zerothier central 
- Any relevant console output or screenshots. -> atached
- What operating system and ZeroTier version. Please try the latest ZeroTier release. -  version i used: 1.12.2 1.12.1
 
![image](https://github.com/zerotier/ZeroTierOne/assets/9446969/76e1ea42-f9d4-41db-9abe-4554843477ac)

**Comment by glimberg** [comment]
Those are unauthorized members attempting to join your network.  Once they're authorized the version will show up.

If you're not expecting these members, then either someone on your team is trying to join the network or has set up a script to do so.  Either that or your network ID has leaked and you have someone trying to join it.

This is working as expected, though.

**Comment by laduke** [comment]
We can probably make it say "unknown" or something 👍

**Comment by spiderrr** [comment]
ok I find one. Thanks.
