### ISSUE TITLE
Tunnelling not receiving any data

### ISSUE THREAD

**Issue by Pagghiu** [zerotier/ZeroTierOne#218]
I've been running some tests in a very restrictive network environment, knowing that the connection would have become tunnelled.
The problem is that I can't make anything work when the connection is tunnelled and if I go in the connection status I see zero bytes getting received.

Any hints?

<img width="1199" alt="wifirestrictive" src="https://cloud.githubusercontent.com/assets/5406873/9018590/8c37d954-37e0-11e5-8b78-64ce35e5aa4d.png">

**Comment by adamierymenko** [comment]
Where are you located and what is the external IP from which you're coming? I'd like to go log into the proxy server and see if it's receiving a TCP connection from you.

Tunneling occurs over TCP port 443, so if that is somehow blocked it's not going to work. That can happen in sites that have BlueCoat proxies trying to intercept SSL traffic.

Also you might try 1.0.4. It was just released and contains some fixes, though no changes to the tunneling code.

**Comment by Pagghiu** [comment]
I'm sorry but I will not be able to re-access the machine where I've been testing this before next month.
