### ISSUE TITLE
[Feature Request] How to use ZeroTier with ShadowSocks?

### ISSUE THREAD

**Issue by GermanAizek** [zerotier/ZeroTierOne#2180]
Is it possible to wrap zt tunnel in shadowsocks to hide fingerprints zt traffic? Some providers block zerotier traffic on VPS.

**Comment by joseph-henry** [comment]
This is not something we've tried but we'd be curious to know if you get it to work. Remember that you'll need to allow ZT to reach a root or a moon somehow. Closing this ticket since it's out of scope of our development but if you wish to discuss it further we can re-open it. Good luck!
