### ISSUE TITLE
Issue installing/joining ZT on ubuntu and fedora headless systems maybe others..

### ISSUE THREAD

**Issue by blwvirus89** [zerotier/ZeroTierOne#2184]
facing issues on Ubuntu containers. have tried several versions. this used to work fine.
ZT shows online, Dashboard sees client
https://prnt.sc/RqFNyHvg7z55
BUT!!!
-The service is showing an error 
( zerotier-one[182]: ERROR: unable to configure virtual network port: could not open TUN/TAP device: No such file or directory )
https://prnt.sc/LAQh57MXYS07

-Network traffic is not flowing

-ZT is NOT creating a virtual network adapter (ex ztxxxx)
https://prnt.sc/uM0ubXdRiSup

I have failed to find a solution to this in my googling.
I did find another open report for Fedora that i believe to be the same issue 
https://github.com/zerotier/ZeroTierOne/issues/2160#issue-1966944616

cli outputs
[ServiceStatus.txt](https://github.com/zerotier/ZeroTierOne/files/13494510/ServiceStatus.txt)
[ZT-cli listnetworks.txt](https://github.com/zerotier/ZeroTierOne/files/13494511/ZT-cli.listnetworks.txt)
[ZT-cli status.txt](https://github.com/zerotier/ZeroTierOne/files/13494516/ZT-cli.status.txt)

Extra info to reproduce the issue on Ubuntu CT 
host system = Proxmox ve 7.4 (fresh CT builds were tested on several hosts)
container system = Ubuntu Server (20.04, 22.04, 22.10, 23.04, 23.10)

also have several CTs running in this same config live as I post this so existing configs are unaffected this is strictly affecting new installs of ZT

**Comment by glimberg** [comment]
That error means either there is on `/dev/net/tun` device, or ZeroTier does not have access to read/write to it.  You mentioned containers, so you're probably not exposing the host OS's `/dev/net/tun` device to the container.  For Docker, the following command line options will allow it to work:  `--cap-add NET_ADMIN --device /dev/net/tun`.  Other container runtimes probably require something similar.

**Comment by blwvirus89** [comment]
running prox mox but that does give me a new path to investigate thank you.
 I will post new info as I find it.

**Comment by blwvirus89** [comment]
ok Thank you for your reply. here is my solution 
From the proxmox host shell 
`nano /etc/pve/lxc/101.conf`
add the following lines to bottom.
`lxc.cgroup2.devices.allow: c 10:200 rwm`
`lxc.mount.entry: /dev/net dev/net none bind,create=dir`
write out, exit and start the ct problem solved.
