### ISSUE TITLE
Zerotier-cli can't persist network settings

### ISSUE THREAD

**Issue by mtalexan** [zerotier/ZeroTierOne#2186]
**What you expect to be happening.**

Network configuration like:
```
allowDNS=1
```
Should have a way to persist the setting for the `zerotier-cli` since it has to be set before the network is joined/connected.

**What is actually happening?**  

The option can only be set (and take effect) if it's manually added to a `/var/lib/zerotier-one/network.d/{network_id}.local.conf` file before the network is joined.  But when the network is left (the only way to disconnect from the network), that file is deleted.

**Any steps to reproduce the error.**

```shell
cat << EOF
allowDNS=1
EOF | sudo tee /var/lib/zerotier-one/network.d/${network_id}.local.conf

sudo chown zerotier-one:zerotier-one /var/lib/zerotier-one/network.d/${network_id}.local.conf

sudo zerotier-one join ${network_id}

sudo zerotier-one leave ${network_id}

ls -la /var/lib/zerotier-one/network.d/
```
Notice at after the `leave`, the file gets removed.

**What operating system and ZeroTier version. Please try the latest ZeroTier release.**  
`ZeroTier One version 1.12.2 build 0 (platform 1 arch 2)`
Fedora 39 Kinoite x86_64

**Comment by glimberg** [comment]
Hello,

The removal of the network config & settings is working as designed.  You do not, however need to create the ${network_id}.local.conf file manually.  You can use the following to set DNS enabled after joining the network:

```bash
sudo zerotier-cli set ${network_id} allowDNS=1
```

**Comment by mtalexan** [comment]
> Hello,
> 
> The removal of the network config & settings is working as designed. You do not, however need to create the ${network_id}.local.conf file manually. You can use the following to set DNS enabled after joining the network:
> 
> ```shell
> sudo zerotier-cli set ${network_id} allowDNS=1
> ```

Hm, well I tried that first (it's not documented by the way, including in the help text) and it didn't set the option. The `sudo zerotier-cli -j listnetworks` shows it still as `false`. Only the file method worked to set it, or calling `sudo zerotier-cli set ${network_id} allowDNS=1` (but it can't take effect once the network is already running, so the latter isn't very useful).

Additionally, the documentation says that having a blank `/var/lib/zerotier-one/network.d/${network_id}.conf` file will automatically connect to that network when the service starts, which indicates some intention of supporting a daemon-based config. So how is a daemon supposed to be configured persistently if the config files get automatically deleted when disconnecting?

**Comment by mtalexan** [comment]
I should say that I understand the intent here. The `*.local.conf` files are used by the daemon itself as a way to track the status of the networks and manually configured settings. If the network is left, you need to update that staus. The problem is that there also needs to be a way to persistently configure the networks. So the documentation currently tells you to manually write to the (apparently ephemeral) status files before starting your network.

**Comment by didjeru** [comment]
In this case, how to save the network state for permanent use by the daemon from the console? The GUI crashed on my Mac after reinstall...

**Comment by joseph-henry** [comment]
As @glimberg previously mentioned this is working as intended. ZeroTier is designed to clean up any configuration data related to a network when you leave it. Nothing persists on disk. If you wish to configure the client locally for a specific network you should use the CLI after you join the network.

**Comment by glimberg** [comment]
Additionally, if you don't `leave` the network, the files remain on disk on system restart/shutdown.  It is the `leave` action that removes the configuration from disk; not shutting down or restarting the daemon.
