### ISSUE TITLE
ZeroTier does not work on Ubuntu 24.04dev error while loading shared libraries: libssl.so.1.1

### ISSUE THREAD

**Issue by alatteri** [zerotier/ZeroTierOne#2189]
Same error as in bug https://github.com/zerotier/ZeroTierOne/issues/2154 but happening in Ubuntu 24.04 dev as well.

**Comment by alatteri** [comment]
5 months later, and with Ubuntu 24.04 imminent release, this issue is still present.

`zerotier-cli: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
`

**Comment by brunosalezze** [comment]
I can confirm, this issue is also present on the 24.04 beta test yesterday.

CPU: AMD 7950x
MB: MSI B650i Edge Wifi
RAM: 2x48GB Corsair V RGB
SSD: WD Black SN770 500GB

**Comment by romankehr** [comment]
Ubuntu 24.04 LTS is released. Issue still exists.

**Comment by itskenny0** [comment]
Found a workaround:

```
wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.22_amd64.deb
dpkg -i libssl1.1_1.1.1f-1ubuntu2.22_amd64.deb
```

This will install libssl1.1 from the older Ubuntu repos. That fixes the issue. Zerotier should still compile against newer libssl to avoid this.

[Source](https://stackoverflow.com/a/72633324)

**Comment by arpagon** [comment]
The best thing to do is to use the Mantic version in /etc/apt/sources.list.d/zerotier.list because, by default, the installer thinks you are using Buster. This way, you don't have to install libssl externally, which would not be recommended for security reasons.

**Comment by laduke** [comment]
let us know if you're still seeing an issue

**Comment by danidak** [comment]
update repo:
http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.23_amd64.deb

**Comment by nerdCopter** [comment]
my solution for 24.04.01 which stopped working today after a `sudo aptitude full-upgrade`:
```
sudo aptitude remove zerotier-one                  #remove, don't purge
curl -s https://install.zerotier.com | sudo bash
```
prior to such, my `/etc/apt/sources.list.d/zerotier.list` referenced a very old distro, but changing it did not upgrade zerotier properly.

note: `apt` is appropriate as well rather than `aptitude`
