### ISSUE TITLE
the compilation does not complete ...

### ISSUE THREAD

**Issue by spaccabits** [zerotier/ZeroTierOne#2190]
... with this error
(last 3 lines of the compilation)

**export PATH=//home/_myAccount_/.cargo/bin:$PATH; cd rustybits && cargo build --release -p zeroidc
/bin/sh: 1: cargo: not found
make: *** [make-linux.mk:442: zeroidc] Error 127**

**clang** version 14.0.6
OS **Mint LMDE 6** (based on Debian 12)

Greetings

**Comment by glimberg** [comment]
You must have the Rust programming language toolchain installed.  See https://rustup.rs/ to install.
