### ISSUE TITLE
Can’t start zerotier-one on Ubuntu 

### ISSUE THREAD

**Issue by xFr0z3n** [zerotier/ZeroTierOne#2191]
christoph@christoph-ubuntu:~$ sudo zerotier-cli info
200 info 4c340f11a2 1.12.2 ONLINE

christoph@christoph-ubuntu:~$ sudo zerotier-one -d
christoph@christoph-ubuntu:~$ zerotier-one: fatal error: cannot bind to local control interface port 9993

as you can see o checked if it’s online and then started it and got the error cannot bind to local control interface port 9993

**Comment by laduke** [comment]
It's already running. There is a systemd unit that manages it.

**Comment by xFr0z3n** [comment]
> It's already running. There is a systemd unit that manages it.

What do I need to do how can I control the daemon

**Comment by laduke** [comment]
`zerotier-cli join <network_id>` mostly!

`zerotier-cli listnetworks` 

`zerotier-cli -h`  help


hope that helps

**Comment by xFr0z3n** [comment]
How can I make a network auto start ?

**Comment by rcoder** [comment]
The service automatically stores it's current state, including the list of networks you've joined, and will attempt reconnection each time it starts.

So e.g. `zerotier-cli join <nwid>` will attach[^1] to a network, after which the ZeroTierOne service will automatically reconnect.

[^1]: it will actually _request_ access; you still need to authorize the device, unless the network is public
