### ISSUE TITLE
mark ZT packets for firewall handling

### ISSUE THREAD

**Issue by mwarning** [zerotier/ZeroTierOne#220]
It would be nice if ZT would be able to mark its packets, so that the traffic can be handled using the firewall. E.g. so that alls packes go out on a specific interface.

This would do (with the mark to be configurable):
```
unsigned int mark = 1;
setsockopt(fd, SOL_SOCKET, SO_MARK, &mark, sizeof(mark));
```

**Comment by adamierymenko** [comment]
Is there a standard list of mark IDs that should be used to not step on others, or is this something that should be part of a local config?

**Comment by adamierymenko** [comment]
Agreed that this would be cool, would permit iptables mark rules to allow all ZeroTier traffic on a local host without caring about port (and without opening a port per se). Good for people who like to go crazy with iptables local firewall rules to harden a system.

**Comment by mwarning** [comment]
There is no standard (afaik), it has to be part of the local config.

**Comment by adamierymenko** [comment]
Are these hosts Linux? If so I think outbound packets can be marked with iptables. Maybe this could be done via a simple rule to mark outbound ZT packets.

This sort of feels like an out-of-scope feature.
