### ISSUE TITLE
Windows binary does not add driver to the system driver store if not present -- MSI or manual driver install required

### ISSUE THREAD

**Issue by anzz1** [zerotier/ZeroTierOne#221]
The new tap installation procedure does not work on Windows when starting ZeroTier from the command line (zerotier-one_x64.exe -C). port_error_log.txt is created with the following text:
************: unable to create new device instance: UpdateDriverForPlugAndPlayDevices() failed (made 60 attempts) 

An "Unknown Device" will be shown in Device manager under Network adapters.
![screenshot](http://i.imgur.com/9xcjN8r.png)
In properties the device status shows: "No drivers are installed for this device."

Previous method, using devcon worked just fine in seemingly any scenario.

Operating system: Windows 7 Ultimate 64-bit, up-to-date with latest updates from Windows Update.

**Comment by adamierymenko** [comment]
Is the command line running with full administrator privileges? (Right click -> run as administrator.) That's required to install devices, and the service runs that way.

If so, we'll try this ourselves. Didn't see any issues with it running as a service, but perhaps there's some weirdness around running it from a Windows app in console.

**Comment by anzz1** [comment]
Yes, I was running it as Administrator.

**Comment by adamierymenko** [comment]
K, we'll try this ourselves.

**Comment by adamierymenko** [comment]
You could still use devcon if you want -- here are the binaries. https://github.com/zerotier/ZeroTierOne/tree/bd7e4ab6955f838c3119fe1262901875345d8d43/ext/bin/devcon

If you use devcon to install an instance of the port driver, then start ZeroTier and join a network, it should discover this unused instance and use it.

**Comment by adamierymenko** [comment]
That's obviously a hack though. We'll try this and see if we can duplicate the problem.

**Comment by adamierymenko** [comment]
Just tried it and it worked on this end (fresh Windows 7 install in VM).

Did you install from the MSI? If not, it's possible that the new NDIS6 driver is not in the system driver store. If that's the case you can install it manually from the x64/ subfolder under tap-windows and then try. If the driver isn't in the driver store, devices can't be added.

**Comment by anzz1** [comment]
I didn't install it from MSI and that's exactly the point, it isn't loaded in the driver store. Yes, I can install manually too, but the previous way was superior as it did work in the same situation: It loaded the driver in the driver store and installed the driver without any problems. The new system requires the driver to be manually installed beforehand. Before, was the driver installed or not, you could just run zerotier.exe -C and it would automagically install driver and adapter if it's required.

**Comment by adamierymenko** [comment]
Will take a look at this in the next version. We can probably add additional code to install the driver if not present. In the meantime adding the driver to the system driver store will fix the problem. This can be done with the devcon binary or through the Windows UI.

**Comment by adamierymenko** [comment]
Closing as won't fix -- MSI is the preferred Windows installation method for now. If you must install manually the driver can be installed manually. Don't have the time to support alternative Windows packaging methods at the moment... Windows is bad enough as-is.
