### ISSUE TITLE
MIPS and ARM optimized Poly1305 and Salsa20

### ISSUE THREAD

**Issue by mwarning** [zerotier/ZeroTierOne#222]
The poly1305 algorithm has an optimized Assembler version for mips32:
https://github.com/cjdelisle/poly1305-mips32r2-donna/
(The ZT poly1305 selftest passes with this assembly version)

There are probably other optimized implementations available
It might be useful to use a local checkout of libsodium.
It is a maintained fork of nacl and also offers optimized implemtations.

**Comment by mwarning** [comment]
I also added a ticket there: https://github.com/jedisct1/libsodium/issues/289

**Comment by adamierymenko** [comment]
Closing this for now -- new version has an optimized Poly1305 that is much faster. Might add an option in the future to build against libcrypto++ on some platforms (Linux) which has even faster algos.
