### ISSUE TITLE
Join ok but no networks listed

### ISSUE THREAD

**Issue by DanielDC88** [zerotier/ZeroTierOne#2222]
Hi. I’ve got a pi running the mainsail distro from the raspberry pi imager. It’s essentially normal raspian.

For a while now I’ve not been able to connect to this device over ZTO. It shows as connected to the ZTO network on the ZTO web portal and when I manually reconnect it via zerotier-cli I get 200 join ok.

Even so, I see no ZTO ip in ifconfig and there are no networks listed when I run zerotier-cli listnetworks none are shown.

I’ve tried reinstalling ZTO and leaving and joining, updating everything else, rebooting, but still no luck.

This uses the latest version of mainsailOS and zerotier one.

**Comment by joseph-henry** [comment]
Hello. It sounds like maybe you have auto-assign IP turned off in the web UI?

**Comment by DanielDC88** [comment]
Hi, IP is assigned:
![image](https://github.com/zerotier/ZeroTierOne/assets/28685670/669c4145-f49f-4af7-b618-15848b07d0c3)

**Comment by joseph-henry** [comment]
Hmm, I've never seen anything like this before. Are you certain you don't have two instances of ZeroTier running? And so you have any other software installed that might interfere with network interfaces?

**Comment by laduke** [comment]
Maybe the `tun` module is not loaded or working. Or there is some other system permissions issue. Is `/var/lib/zerotier-one` mounted read-only?

`systemctl status zerotier-one` and `journalctl -u zerotier-one`  for possible clues. 

If you see `zerotier-one[2098212]: connect: Connection refused` that's UPnP  library and probably not related to this issue.

**Comment by joseph-henry** [comment]
Looks like this was [solved on the forums](https://discuss.zerotier.com/t/join-ok-but-no-networks-listed-attempt-2/18631), it was a missing `/dev/net/tun`. 

Solution was:

> does `/dev/net/tun` exist? If not, you’ll need to get the TUN/TAP module loaded in the linux kernel, likely via `sudo modprobe tun`
