### ISSUE TITLE
Web site needs more support/contact info

### ISSUE THREAD

**Issue by jefft** [zerotier/ZeroTierOne#223]
Hi,

I just want to ask a user-level question. There are no 'support', 'contact us' or 'get help' links on the website.  There used to be a forum, but that's disappeared.

**Comment by adamierymenko** [comment]
We eliminated the forum because it scattered support too much -- most users use GitHub, IRC (freenode), or e-mail. But you're right that the web site needs more information about where to go for support. This is a bit of an oversight, so I'm tagging this for attention. :smile_cat:
