### ISSUE TITLE
[Feature Request] Request for Pre-built Binary Packages for Windows on ARM to Facilitate ZeroTier Usage on ARM Devices

### ISSUE THREAD

**Issue by Waximell** [zerotier/ZeroTierOne#2239]
Could you please consider releasing pre-built binary packages for Windows on ARM? As the number of WOA devices increases, there are more and more people who need to use ZeroTier on ARM devices. Providing pre-built binary packages for WOA would greatly facilitate their usage. 
(Honestly, I spent a whole night trying to compile the source code to create an ARM package without success, and the x64 version I managed to create is also not clear to me how to use. Disappointed, I'm making this request. Or if anyone is willing to provide me with assistance, I would be deeply grateful.)

**Comment by glimberg** [comment]
Windows ARM64 is included in the 1.12.x series installer packages.

**Comment by Waximell** [comment]
I just realized in the community that the latest version of ZeroTier now supports WOA. I had previously provided my friend with an older package, which led him to tell me that he was unable to install it. I apologize for this issue and for any inconvenience it may have caused. Thank you for understanding.
