### ISSUE TITLE
Trouble Using a Self-Hosted Controller

### ISSUE THREAD

**Issue by dafyre** [zerotier/ZeroTierOne#224]
Hi All,
I am having an issue with ZeroTier and running my own Controller.  In order to get it to compile correctly, I first run make installer and run the installer that is built.  In then make clean; make ZT_ENABLE_NETWORK_CONTROLLER=1  in order to build the controller binaries (which then have to be manually copied into place on Ubuntu 14.04).

After doing so, and starting the controller, and using the API to create a network, everything registers on the controller, and as I join and authorize clients to the network, they are able to grab an IP address in the range that I specified...  My controller information and one client are attached as a text file 
![ztnetwork](https://cloud.githubusercontent.com/assets/13368910/9320306/4451fd06-4526-11e5-8e2c-8a38d0e58370.png)
![ztclient](https://cloud.githubusercontent.com/assets/13368910/9320308/466102ea-4526-11e5-9ffc-aa13084811eb.png)

The ZeroTier functionality actually works when I join my network that is hosted on your controller.

My Controller is currently hosting  an OwnCloud instance that is run on ports 80 and 443.  The other clients are two Windows 8.1 machines and one Fedora 22 laptop (installed form the 1.04 RPM available).

Are there any other ports besides 9993 that need to be allowed through the firewall?

**Comment by paulrd** [comment]
Can you specify what your problem is? From reading the above (several times) it seems that everything is working correctly ;-). Is the problem that you are not able to ping other clients on the local network? I have yet to fully test this controller myself (almost there). One idea I have is the "rules". Have you tried to write a json object to this yet? I have tried but something is not taking. From reading the docs it says you need to have an accept rule in there "To allow all traffic, create a single rule with all null fields and an action of 'accept'."

**Comment by dafyre** [comment]
Hey Paul,

I am unable to ping any of my clients on my ZT network.  Local network
connections are still fine...  It seems to me that you are probably right
about the "RULES" bit... Not sure how I missed that in the docs.  I am
going to tinker with that now and see what I can come up with.  I am using
the PHP cli to create the network...  and since you have pointed that out
to me, I've updated my PHP script, but it still doesn't seem to be taking.

I will let you know what I find out!

**Comment by dafyre** [comment]
Hey Paul,

I was able to get it working when creating a network (using my PHP
script).  I have not tried to modify the rules line or anything like that
yet, but at least it is working now!

Thanks for the pointers!
~Brant

**Comment by adamierymenko** [comment]
Hey, yes, sorry for being late to the party.

The default behavior with no rules would be 'drop all', so yes that wouldn't work. Also be sure to note that only etherType is currently used. The rest of them are waiting for the rules engine in the core.

Should probably post a JSON snippet of what a valid working network looks like.

**Comment by dafyre** [comment]
After adding in the rules block, I was able to get it working. :-)

I did have to create a new network for this to take though, so I am unsure
if modifying the rules block will work or not...  Thanks for the help in
getting this going!

Thanks!
~Brant

The code below is a snippet of a working network.
[CODE]
{
        "nwid": "<nwid>",
        "controllerInstanceId": "<instaceid>",
        "name": "MyTestNetwork",
        "private": true,
        "enableBroadcast": true,
        "allowPassiveBridging": false,
        "v4AssignMode": "zt",
        "v6AssignMode": "none",
        "multicastLimit": 32,
        "creationTime": 1440161932745,
        "revision": 4,
        "memberRevisionCounter": 6,
        "relays": [],
        "gateways": [],
        "ipLocalRoutes": ["192.168.251.0/24"],
        "ipAssignmentPools": [

{"ipRangeStart":"192.168.251.1","ipRangeEnd":"192.168.251.254"}],
        "rules": [
        {
                "ruleNo": 10,
                "action": "accept"
        }]
}
[/CODE]
