### ISSUE TITLE
[Feature Request] Make homeDir path absolute

### ISSUE THREAD

**Issue by joseph-henry** [zerotier/ZeroTierOne#2247]
I propose we make the new `homeDir` path output absolute and not relative. I feel it makes it easier for other tools to grab and use this field without needing to know where the `zerotier-one` binary is being run from.

This may not be an issue for system instances but if I run it like so `./zerotier-one ../id` I get back `../id`

This is low priority.

**Comment by laduke** [comment]
That's a nice idea. I just used the var that was already available. It looks like it's just directly the argument passed to zerotier-one. try `./zerotier-one $(pwd)/id` or something. 
path manipulation in c++ not something i'm familiar with yet

**Comment by joseph-henry** [comment]
That's probably a better approach.
