### ISSUE TITLE
[Feature Request] FR: Is it possible to add the ability to automatically change zerotier ports on a regular basis? Since network carriers in some regions will limit the speed of zerotier, or even go offline. or even use multiple zerotier ports?

### ISSUE THREAD

**Issue by masx200** [zerotier/ZeroTierOne#2249]
If there is something you'd like to have added to ZeroTier, to go to https://discuss.zerotier.com/c/feature-requests/ instead. Issues there can be voted on and discussed in-depth.

FR: Is it possible to add the ability to automatically change zerotier ports on a regular basis? Since network carriers in some regions will limit the speed of zerotier, or even go offline. or even use multiple zerotier ports?
Thank you!

突破运营商 QoS 封锁，WireGuard 真有“一套”！

https://cloud.tencent.com/developer/article/2153908

WireGuard 客户端魔改：对端节点动态更新

https://www.mazhangjing.com/blogs/2023-04-26-wireguard-gw-edition

udp2raw:

https://github.com/wangyu-/udp2raw-tunnel

Phantun:

https://github.com/dndx/phantun

[WireGuard](https://www.wireguard.com/) for Windows (Great Wall Edition)

https://github.com/corkine/wireguard-windows-great-wall-edition

https://github.com/wangyu-/udp2raw/issues/332

https://github.com/coolsnowwolf/lede/issues/4124

**Comment by laduke** [comment]
It's supposed to be changing the secondary port automatically if it can't make any connections. That is not working in the current release, but is fixed and will go out in the next release.

**Comment by masx200** [comment]
If you have multiple Internet lines, then using multiple ports in the private network will be mapped to multiple Internet ports by load balancing, which is also one of the important functions of SD-WAN.

使用多个服务端口也是能够提供负载均衡的能力的,如果拥有多条互联网线路,那么使用多个私网中的端口,就会被负载均衡映射到多个互联网的端口,这也是sd-wan的重要功能之一.

**Comment by masx200** [comment]
https://github.com/netbirdio/netbird/issues/1679


https://github.com/tailscale/tailscale/issues/11371

**Comment by laduke** [comment]
https://docs.zerotier.com/protocol#multipath

**Comment by masx200** [comment]
Can the settings for a multilink connection be set locally only?

Is it possible to configure it on a controller like SD-WAN and automatically deliver it to the device?

@laduke

**Comment by laduke** [comment]
> Can the settings for a multilink connection be set locally only? only.

locally only

the original issue is fixed in 1.14
