### ISSUE TITLE
Should allow for install on Kali

### ISSUE THREAD

**Issue by xelerated** [zerotier/ZeroTierOne#2264]
bash script command to pull and install from site should allow for Kali in its checking. Im trying to streamline this for IT to install for our remote testing VM's, otherwise I'm going to have to move to openziti. I cant hold IT"s hand every time we need to deploy a pen test VM.

Thank you!

**Comment by laduke** [comment]
hey thanks for writing. Just FYI it takes as long time for edits to the install script to be released. 

"all" the installer does is set up an apt repo. 

Here's an example from a debian 11 machine: 

```
cat /etc/apt/sources.list.d/zerotier.list 
deb http://download.zerotier.com/debian/bullseye bullseye main
```

I'm not sure which values to use for kali

**Comment by laduke** [comment]
please try again
