### ISSUE TITLE
ZTO does not allow data transmission over HTTP longer than one TCP packet

### ISSUE THREAD

**Issue by mister-proger** [zerotier/ZeroTierOne#2265]
- What you expect to be happening.
Successful execution of an HTTP request between a client and a server within the same ZTO network
- What is actually happening?
The connection is reset (it was established experimentally) if the entire response does not fit into one TCP packet
- Any steps to reproduce the error.
1) Create a test HTTP server (I tried Django and actix-web, [after discussing this error](https://github.com/ClickHouse/clickhouse-connect/issues/320)) that will return more than 1,500 bytes of data per request.
2) Make a request for it
- What operating system and ZeroTier version. Please try the latest ZeroTier release.
Have been tested:
1) Python clickhouse-connect (urllib3) {Windows 10} -> ClickHouse {WSL Ubuntu 22 on Windows 10} | Two devices
2) curl {WSL Ubuntu 22 on Windows 10} -> ClickHouse {WSL Ubuntu 22 on Windows 10} | Single Device
3) curl {Windows 10} -> ClickHouse {WSL Ubuntu 22 on Windows 10} | Two devices
4) curl {Windows 10} -> test the HTTP server (Django/actix-web) | Two devices
All requests went to the IP address inside the ZTO network, even if they were located on the same device. The connection was reset if the response size exceeded one TCP packet, and returned data successfully if the response fit into one packet.

**Comment by mister-proger** [comment]
It is worth adding that PostgreSQL queries worked quietly on much larger data, probably because it has its own low-level protocol.

**Comment by laduke** [comment]
I wasn't able to reproduce this. My guess is the nodes aren't directly connected. Check the output of `zerotier-cli peers`

**Comment by mister-proger** [comment]
Strangely, I couldn't reproduce the behavior. Maybe it was some kind of local bug with my router. Sorry to disturb.
