### ISSUE TITLE
Create a network every time you change ZeroTier One settings on Windows 11

### ISSUE THREAD

**Issue by filisdiez** [zerotier/ZeroTierOne#2267]
Hello!

Each time you change the settings and connect to a ZeroTier network, a new network is created. All this happens in Windows 11 Pro x64 23H2. I tried different versions of ZeroTier One 1.6.6, 1.12.1, 1.12.2 on all versions a new network is created and I already have 106 of them:). The problem is also indicated in the screenshot. Everything would be fine, but it clutters the Windows registry.

![zero](https://github.com/zerotier/ZeroTierOne/assets/31742254/edce4c75-aa19-470d-8bdc-810f17335218)

**Comment by laduke** [comment]
see #659
