### ISSUE TITLE
Option to pick a random port

### ISSUE THREAD

**Issue by zTrix** [zerotier/ZeroTierOne#228]
When multiple zerotier clients exist in a same NAT network, only one of them can operate successfully.

We tried to listen on different ports, and the problem is solved. I think this may be caused by a bad gateway router or ISP provider(UDP hole punching on 9993 at the same time caused the router to malfunction, or whatever reasons).

So maybe the simplest solution is to allow for listening on port 0? Or just offer a option to listen on random ports?

**Comment by Arffeh** [comment]
I just installed a new NAT/Firewall and am experiencing the same 
problem. One instance gets through, and the others output "Connection 
Refused" constantly on the CLI.

Haven't had much time to see what can be done about it though. :P

**Comment by adamierymenko** [comment]
We've thought about randomizing ports. It's an area where there's conflict between enterprise and end user use cases. Most enterprise users like a predictable port, but as you say some consumer NATs use a stupid mapping logic where they go by port number alone. As a result two more or things using 9993 won't work. These are not all that common but they do exist. :hanky:

**Comment by dafyre** [comment]
What about an option to specify a port in a configuration file...  If the
port = 0 or blank then use 9993 if the port is specified then use that
particular port number?

**Comment by adamierymenko** [comment]
Yeah, that's why I flagged this as backlog. Seems an easy feature to add.

**Comment by adamierymenko** [comment]
-p0 for random port is in -dev, closing
