### ISSUE TITLE
Set TAP adapter speed to 1Gbit or 10Gbit

### ISSUE THREAD

**Issue by Juniorsnet** [zerotier/ZeroTierOne#2285]
https://discuss.zerotier.com/t/is-there-a-way-to-force-gigabit-interface/15083
https://discuss.zerotier.com/t/zerotier-adapter-1gbps/2531
https://www.reddit.com/r/zerotier/comments/o6dtkv/zerotier_stuck_at_100mbps/

I got the same problem. The problem is only on windows, In linux I got 600Mbps Gigabit LAN conection, but on windows < 100Mbps.

Can you change the TAP_XMIT_SPEED and TAP_RECV_SPEED to 1Gbit or to 10Gbit to unlock the aparently limit on windows?

**Comment by glimberg** [comment]
zerotier is software, not hardware.  The reported speed of the TAP has nothing to do with the throughput speed.  It all comes down to how fast you can encrypt & send out packets, and receive replies.  If you're not making direct connections to peers, it will be slower. Period.
