### ISSUE TITLE
Site-To-Site Connection

### ISSUE THREAD

**Issue by dafyre** [zerotier/ZeroTierOne#229]
Hi All,

I am working on testing the bridging / site-to-site functionality using the 1.0.5 client...  My current setup looks like this.. 

(zt0)--ztRouter--(eth0)--(linksys)--(public internet)--(eth0)--ztController--(zt0)

ztRouter has:
192.168.10.10/24 (internal IP space, eth0)
192.168.251.179/24 (ZeroTier IP space, zt0)
Fedora 22
firewalld is off
sysctl net.ipv4.ip_forward=1
iptables flushed

ztController has:
Ubuntu 14.04 LTS
A public IP address
192.168.251.49/24 (Zero Tier IP Space, zt0)
*ztController is also a client on this network

Both ztController and ztRouter are running from git version:
commit 5db538d85ef739fa969a5b71d294501ac0bb5335
Author: Adam Ierymenko <adam.ierymenko@gmail.com>
Date:   Tue Aug 25 09:55:14 2015 -0700

Now, I can ping from ztController  all the way to a machine in my 192.168.10.0/24 range.  There are a few drops, but by and large they are successful.  Machines on my 192.168.10.10.0/24 network are able to ping to 192.168.251.49 (the ztController, at the other location) with no issue.  (I set up a static route on my Linksys to route 192.168.251.0/24 to 192.168.10.10/24 (ztRouter)

My most recent test included a mount from my ztController to a WIndows file share located on the 192.168.10.0/24 network

I was able to mount, browse, cd, and ls the folders with no problems.  It did seem abnormally slow;  however, as soon as I try any serious data transfer between the two systems, the ZeroTier daemon just crashes on ztRouter.  The zt0 interface is gone, and most of the time, I lose local network connectivity on the box as well, and have to restart it.  The ZeroTier client on ztRouter was *not* built with the controller bits turned on.  The system will try and try to restart the zerotier daemon, but it will continously crash and the system will give up, requiring me to reboot in order to restore any network connectivity.

Below are the zerotier-cli outputs from the ztController node.  If you see anything odd, or need more info, just let me know!

**edit** Is there any kind of log file produced by zerotier?

====================================
ZEROTIER NETWORK INFO
====================================
{
	"nwid": "**OMITTED**",
	"controllerInstanceId": "**OMITTED*",
	"clock": 1441083174587,
	"name": "WellstonTwo",
	"private": true,
	"enableBroadcast": true,
	"allowPassiveBridging": true,
	"v4AssignMode": "zt",
	"v6AssignMode": "none",
	"multicastLimit": 32,
	"creationTime": 1440161932745,
	"revision": 21,
	"memberRevisionCounter": 19,
	"authorizedMemberCount": 6,
	"relays": [],
	"gateways": [],
	"ipLocalRoutes": ["192.168.251.0/24"],
	"ipAssignmentPools": [
		{"ipRangeStart":"192.168.251.1","ipRangeEnd":"192.168.251.254"}],
	"rules": [
	{
		"ruleNo": 10,
		"action": "accept"
	}]
}
==========================================

ZEROTIER Network Member (ztRouter)
==========================================
{
	"nwid": "*OMITTED*",
	"address": "e8da581fee",
	"controllerInstanceId": "*OMITTED*",
	"authorized": true,
	"activeBridge": true,
	"memberRevision": 18,
	"clock": 1441083261238,
	"identity": "*OMITTED*",
	"ipAssignments": ["192.168.251.179\/24"],
	"recentLog": [{"ts":1441083221908,"authorized":true,"version":"1.0.5","fromAddr":null},{"ts":1441083220906,"authorized":true,"version":"1.0.5","fromAddr":null},{"ts":1441083215902,"authorized":true,"version":"1.0.5","fromAddr":null},{"ts":1441083212991,"authorized":true,"version":"1.0.5","fromAddr":null},{"ts":1441083211817,"authorized":true,"version":"1.0.5","fromAddr":null},{"ts":1441083204428,"authorized":true,"version":"1.0.5","fromAddr":null},{"ts":1441083202930,"authorized":true,"version":"1.0.5","fromAddr":null},{"ts":1441083200723,"authorized":true,"version":"1.0.5","fromAddr":null},{"ts":1441083193520,"authorized":true,"version":"1.0.5","fromAddr":null},{"ts":1441083186474,"authorized":true,"version":"1.0.5","fromAddr":null}]
}

**Comment by adamierymenko** [comment]
Is the router a small DD-WRT or similar device?

**Comment by dafyre** [comment]
Hey Adam,

My Home router is a Linksys EA6350 (firmware 1.0.4.164719).  My ztRouter
(Feodra 22) has 1vCPU, and 384 megs of ram.  I can bump that up if needs be.

Thanks!
~Brant

**Comment by adamierymenko** [comment]
That should be far more than enough, and crashes are pretty unheard-of these days on ordinary kinds of machines. Haven't seen one here on production code in a very long time, nor has one been reported.

If you built from source, could you build with:

    make ZT_DEBUG=1

... and then run the result in gdb or lldb and try to crash it? If it does can you post a "bt" or "backtrace" output of where it crashed?

Building with debug also enables tracing so you'll get a bunch of trace output.

**Comment by dafyre** [comment]
Yeah, I will do that in a few hours when I get home (busy at my day job
now)...  I should note that I have not had any problems at all with my
Ubuntu 14 box (also my controller) doing this.  The Fedora 22 is running on
the 4.1.x kernel series.  My Ubuntu 14 box is still on 3.x

I'll get the Backtrace for you as soon as I can.

Thanks!
~Brant

**Comment by adamierymenko** [comment]
Yeah, a crash is definitely strange and a trace would be very helpful. It's unlikely that the kernel version would matter.

**Comment by adamierymenko** [comment]
You could also try running it (in debug build) in *valgrind*, which is a really wonderful tool for detecting illegal accesses and similar errors. I always use that for testing after major changes and it can catch some very obscure problems.

**Comment by dafyre** [comment]
Hey Adam,

So I recompiled everything with ZT_DEBUG=1 as you recommended, and I
figured I'd head straight for valgrind.  I installed Valgrind and started
running it... (Output is going to my console)...  and Im copying a 4gb ISO
file from my home cable connection up to my remote client... and it seems
to be transferring just fine.  I'll see it pause (using pv /mnt/myfile.iso
> /root/myfile.iso from my remote client) and pick up and keep going.

My valgrind.log file isn't growing, and it just has the startup info in
it.  I've never had to dive in to debugging stuff at this level (usually,
the problem lies somewhere obvious in my code, lol)..  Are there any
special switches I need to send to valgrind?

Also, where would the coredumps go in the event that the system does crash?

Thanks!
~Brant

**Comment by dafyre** [comment]
It should also be noted that I am not doing any kind of NAT at the ztRouter.  I am beginning to wonder if my Linksys just may not be strong enough to handle the NAT for my internet connection as well as routing the zerotier stuff for it as well.
