### ISSUE TITLE
Unstable SSH connection although ping is ok

### ISSUE THREAD

**Issue by ahihi8z8z** [zerotier/ZeroTierOne#2291]
Hi, I have a problem with SSH between Zerotier machines. I  added my Windows laptop with ZeroTier 1.12.2 and some Linux virtual machines at my company's private cloud with ZeroTier 1.14.0 into a ZeroTier network. At company LAN, Zerotier connection is good for both ssh and ping. But when I use the laptop to connect to virtual machines from home, the ssh connection becomes unstable, often disconnected or experiencing connection timeout errors, although the ping test still gives stable results under 20ms.

ssh and ping test
![image](https://github.com/zerotier/ZeroTierOne/assets/60187487/99d681c1-6967-4f94-b47c-f6443999a5f1)

Zerotier central
![image](https://github.com/zerotier/ZeroTierOne/assets/60187487/b2a88be4-b6f3-446e-859c-cf3e9a34bbfe)

peers of a virtual machine when I connect from home
![image](https://github.com/zerotier/ZeroTierOne/assets/60187487/0ed7fb94-7c4e-4a63-8f42-9238ce2d8369)

peers of laptop when I connect from home
![image](https://github.com/zerotier/ZeroTierOne/assets/60187487/2a88050e-6efd-4b53-9b18-37c234914046)

**Comment by Spencer6-7** [comment]
upgrade ZeroTier on windows

**Comment by joseph-henry** [comment]
It does appear that the Windows machine is behind some sort of restrictive firewall which is causing it to relay. Try to address that issue and also upgrade your client.
