### ISSUE TITLE
The problem with the minecraft plasmo voice udp port

### ISSUE THREAD

**Issue by Ghoster12154** [zerotier/ZeroTierOne#2292]
Plasmo voice writes to my friends that it is not possible to connect via udp port, because it may be closed, but everything works for me in the firewall settings. I created rules for incoming connections and outgoing connections for all local ports, but anyway. Everything works through the radmin vpn program, but not through zerotier. 

Maybe it's not a bug or a problem, but just a single random case, and this problem will go away on its own, but I played with other friends and everything worked for them

**Comment by Ghoster12154** [comment]
After observations, it turned out that only one player had the problem so far, but the problem has not yet been solved, everything has also been checked in the firewall settings and all exceptions for zerotier are there

**Comment by laduke** [comment]
hey sorry, we can't really help troubleshoot here in the issues.
