### ISSUE TITLE
Zerotier Central down, unable to log in trough the web portal, and API requests are failing.

### ISSUE THREAD

**Issue by MarcellVokk** [zerotier/ZeroTierOne#2293]
Title. I might just be dumb, if I figure it out, I will delete this post...

Other information:
https://docs.zerotier.com/central/v1 seems to have an invalid SSL certificate?

**Comment by owopeachy** [comment]
It appears they have not renewed their certificates. Nothing we can do but wait for someone on their team to fix it

**Comment by MarcellVokk** [comment]
I hope they fix it very soon, this is a very big issue!

**Comment by glimberg** [comment]
I'm not sure what you guys were seeing.  None of our cert expiry alarms have gone off, cert-manager didn't rotate any certs in that timeframe, and our CDN didn't report any downtime or issues either.

**Comment by MarcellVokk** [comment]
Try to log into Zerotier Central, when clicking on login nothing happens, It's still not working...

**Comment by glimberg** [comment]
I logged in just fine with Firefox, Safari, and Chrome

**Comment by owopeachy** [comment]
I tried clearing site data for zerotier and using a private tab, as well as trying with my phone's mobile network. But it still gives a certificate error for the sites. 
Is there something i can send or show you for more information that could help figure this out?

**Comment by MarcellVokk** [comment]
The apears to be valid now, but for me the login still doesn't work.

https://github.com/zerotier/ZeroTierOne/assets/40302952/cc7dc9e3-8e7c-44ab-99a8-a2766e0b4361

**Comment by someara** [comment]
What does openssl cli say?

```
foxtrot:~$ openssl s_client -connect my.zerotier.com:443
Connecting to 2a04:4e42:9::347
CONNECTED(00000005)
depth=2 OU=GlobalSign Root CA - R3, O=GlobalSign, CN=GlobalSign
verify return:1
depth=1 C=BE, O=GlobalSign nv-sa, CN=GlobalSign Atlas R3 DV TLS CA 2024 Q1
verify return:1
depth=0 CN=*.zerotier.com
verify return:1
---
Certificate chain
 0 s:CN=*.zerotier.com
   i:C=BE, O=GlobalSign nv-sa, CN=GlobalSign Atlas R3 DV TLS CA 2024 Q1
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Mar  6 21:58:23 2024 GMT; NotAfter: Apr  7 21:58:22 2025 GMT
 1 s:C=BE, O=GlobalSign nv-sa, CN=GlobalSign Atlas R3 DV TLS CA 2024 Q1
   i:OU=GlobalSign Root CA - R3, O=GlobalSign, CN=GlobalSign
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Oct 18 04:09:32 2023 GMT; NotAfter: Oct 18 00:00:00 2025 GMT
---
```

**Comment by owopeachy** [comment]
`C:\Users\User>"C:\Program Files\OpenVPN\bin\openssl.exe" s_client -connect docs.zerotier.com:443
CONNECTED(000001D0)
depth=1 C = US, O = Let's Encrypt, CN = R3
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = accounts.zerotier.com
verify error:num=10:certificate has expired
notAfter=May 12 21:15:16 2024 GMT
verify return:1
depth=0 CN = accounts.zerotier.com
notAfter=May 12 21:15:16 2024 GMT
verify return:1
---
Certificate chain
 0 s:CN = accounts.zerotier.com
   i:C = US, O = Let's Encrypt, CN = R3
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Feb 12 21:15:17 2024 GMT; NotAfter: May 12 21:15:16 2024 GMT
 1 s:C = US, O = Let's Encrypt, CN = R3
   i:C = US, O = Internet Security Research Group, CN = ISRG Root X1
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Sep  4 00:00:00 2020 GMT; NotAfter: Sep 15 16:00:00 2025 GMT
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFhDCCBGygAwIBAgISAzdoZJ10EYkDh3su8KbkQubEMA0GCSqGSIb3DQEBCwUA
MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
EwJSMzAeFw0yNDAyMTIyMTE1MTdaFw0yNDA1MTIyMTE1MTZaMCAxHjAcBgNVBAMT
FWFjY291bnRzLnplcm90aWVyLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
AQoCggEBAKR7Ou0EocTmJn6g9OHrXAAFHAtB8fipjTWXAExqB5+ut8q2kf44Rbef
i2nsMyOEPo+bEDHSGFJwUf7zhuO2u0aZKZpVIyzGYC3odIih7lsSJWNI8Hhbrxgf
bqoZntYHpI3zhvlT2mJnt7ZhbBat/1VCRdHb5DE5l363Njbd/vDU51i6+jWMIt1G
ZyOsfYGZrFolClMgItjPhH6s4Y+SAgs1WmI0H+MlwIdZLbzI9HmlyB4lROcHM4zx
2mXs1SHNsUTkkQJe7nJZQxj9zOEQN7Uvk0Na8UJ4g8hL5OIisCVh1U64ZKLDVXc/
SPD30CV/oY+TFuUoqh4EZ2PO+bzrULsCAwEAAaOCAqQwggKgMA4GA1UdDwEB/wQE
AwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIw
ADAdBgNVHQ4EFgQUdnjVq/DpvYBZB0V8Hae9FGORyqUwHwYDVR0jBBgwFoAUFC6z
F7dYVsuuUAlA5h+vnYsUwsYwVQYIKwYBBQUHAQEESTBHMCEGCCsGAQUFBzABhhVo
dHRwOi8vcjMuby5sZW5jci5vcmcwIgYIKwYBBQUHMAKGFmh0dHA6Ly9yMy5pLmxl
bmNyLm9yZy8wgawGA1UdEQSBpDCBoYIVYWNjb3VudHMuemVyb3RpZXIuY29tghBh
cGkuemVyb3RpZXIuY29tghRhcGlkb2NzLnplcm90aWVyLmNvbYIWY29sbGVjdG9y
Lnplcm90aWVyLmNvbYIRZG9jcy56ZXJvdGllci5jb22CFGluc3RhbGwuemVyb3Rp
ZXIuY29tggpqb2luenQuY29tghNtYXRvbW8uemVyb3RpZXIuY29tMBMGA1UdIAQM
MAowCAYGZ4EMAQIBMIIBBAYKKwYBBAHWeQIEAgSB9QSB8gDwAHUAouK/1h7eLy8H
oNZObTen3GVDsMa1LqLat4r4mm31F9gAAAGNn2OJkAAABAMARjBEAiAZ7GAnFMPQ
iUf9ymcnqnUHbA0+2/iaHRj03rrQQo5dKQIgK5dh0ySrLDJ6fJSl84rn1/MRLMHU
JezcIWTdMO+0914AdwB2/4g/Crb7lVHCYcz1h7o0tKTNuyncaEIKn+ZnTFo6dAAA
AY2fY4ncAAAEAwBIMEYCIQC+olvRMGGMiz+3Y4KzFMjeJvaPJGl9yStwzTn8Ee4F
FQIhAODTzTiREZHcThljzk+bwoNqQDipXyAVXBPHfG0b5EbwMA0GCSqGSIb3DQEB
CwUAA4IBAQCW86YwteFRvWb4FMLQ5owvqfxKpKeNr82CAVXpemnsDM3vswWkTzmC
lmMxKuUYfpu+1ekNCIohgDhqwhbjuMwHsbD4oywkiJFbNH7Mil25RK37DB69K1z1
IouodUze/TJfubaorm79j75dXFFCSn2U2PxQOpMwWuI14mC/oSpV87k8MnyTz0l0
baBYgzzUIj0veaxoGC14TJGmJVYWcfPProgyJaTC2OgK86hGBxa7i/YwIGOTx+PK
2Gq2MYq5C2HQDdT6PrFUcMzAg8g8BhV4n5/eatyyQME+mNM9+pLt/iaURFPvaMMV
Xh6872Z9v2tzLxK6ASqM8ilW4F09c8my
-----END CERTIFICATE-----
subject=CN = accounts.zerotier.com
issuer=C = US, O = Let's Encrypt, CN = R3
---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 3217 bytes and written 399 bytes
Verification error: certificate has expired
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 2048 bit
This TLS version forbids renegotiation.
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 10 (certificate has expired)`

**Comment by wurst44** [comment]
same, cert expired
![image](https://github.com/zerotier/ZeroTierOne/assets/2656697/6825aa5e-cc52-4d75-9f39-dd1052f63f6c)

**Comment by MarcellVokk** [comment]
The login issue also seems to be related to the certificate issues, here is dev tools open, this is what hapens when I click login:
![image](https://github.com/zerotier/ZeroTierOne/assets/40302952/6684926b-2e2f-471f-8ceb-f38208f8fe87)

This is what openssl says:
```
C:\Users\Marcell>"C:\Program Files\Git\usr\bin\openssl.exe" s_client -connect my.zerotier.com:443
CONNECTED(00000004)
depth=2 OU = GlobalSign Root CA - R3, O = GlobalSign, CN = GlobalSign
verify return:1
depth=1 C = BE, O = GlobalSign nv-sa, CN = GlobalSign Atlas R3 DV TLS CA 2024 Q1
verify return:1
depth=0 CN = *.zerotier.com
verify return:1
---
Certificate chain
 0 s:CN = *.zerotier.com
   i:C = BE, O = GlobalSign nv-sa, CN = GlobalSign Atlas R3 DV TLS CA 2024 Q1
 1 s:C = BE, O = GlobalSign nv-sa, CN = GlobalSign Atlas R3 DV TLS CA 2024 Q1
   i:OU = GlobalSign Root CA - R3, O = GlobalSign, CN = GlobalSign
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIGXzCCBUegAwIBAgIQAaL/eZdULgk6LOPWTbuiTzANBgkqhkiG9w0BAQsFADBY
MQswCQYDVQQGEwJCRTEZMBcGA1UEChMQR2xvYmFsU2lnbiBudi1zYTEuMCwGA1UE
AxMlR2xvYmFsU2lnbiBBdGxhcyBSMyBEViBUTFMgQ0EgMjAyNCBRMTAeFw0yNDAz
MDYyMTU4MjNaFw0yNTA0MDcyMTU4MjJaMBkxFzAVBgNVBAMMDiouemVyb3RpZXIu
Y29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAn/joY54sTTDT2aRW
6ZV9aO9lE0zK1a5bCRfzrS2ylpipZCs0LjLjsgXvYdo8vAfIj5Dp7oIr9dQ8aqp8
zloOcN4eq7vbGOEL9j3T6ZxISLSSNKwzG8VfG/si36FvvLDpGGoSYc6XkqWKqNbQ
0EnTP5tWIh1kEy/l0tMISkipAZXDTQoEYktPVP7McSwlFbS/ToPMY3hH5MiCxmeU
7H9VFuPe9xatdZZhM1aRC2jI7CiShKGwZ4axa8yI0enWTcGWFjp+RGgMAD8bpuV8
wPGDskbuXBYG7wCJZUHD0n+JF5EmnS91d0AeZrZaJEgJ1T4IMZqrvn6/2obJJZFX
EigYEwIDAQABo4IDYjCCA14wGQYDVR0RBBIwEIIOKi56ZXJvdGllci5jb20wDgYD
VR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAdBgNV
HQ4EFgQUd/HZnDDBp3ZrRJYcUzblGkLrw2QwVwYDVR0gBFAwTjAIBgZngQwBAgEw
QgYKKwYBBAGgMgoBAzA0MDIGCCsGAQUFBwIBFiZodHRwczovL3d3dy5nbG9iYWxz
aWduLmNvbS9yZXBvc2l0b3J5LzAMBgNVHRMBAf8EAjAAMIGeBggrBgEFBQcBAQSB
kTCBjjBABggrBgEFBQcwAYY0aHR0cDovL29jc3AuZ2xvYmFsc2lnbi5jb20vY2Ev
Z3NhdGxhc3IzZHZ0bHNjYTIwMjRxMTBKBggrBgEFBQcwAoY+aHR0cDovL3NlY3Vy
ZS5nbG9iYWxzaWduLmNvbS9jYWNlcnQvZ3NhdGxhc3IzZHZ0bHNjYTIwMjRxMS5j
cnQwHwYDVR0jBBgwFoAUZsDHo5rN/vPqzktTC2FerzMFs+EwSAYDVR0fBEEwPzA9
oDugOYY3aHR0cDovL2NybC5nbG9iYWxzaWduLmNvbS9jYS9nc2F0bGFzcjNkdnRs
c2NhMjAyNHExLmNybDCCAX4GCisGAQQB1nkCBAIEggFuBIIBagFoAHYATnWjJ1ya
EMM4W2zU3z9S6x3w4I4bjWnAsfpksWKaOd8AAAGOFcZVOwAABAMARzBFAiBpg925
YuDOMHcWrybkewhZIrJP9fn9cIAMzfc+nxFh0wIhAOcPd79Zmt2sddIuCD+pXgqz
MYluUI8bAUgAwR7aWBZMAHYAfVkeEuF4KnscYWd8Xv340IdcFKBOlZ65Ay/ZDowu
ebgAAAGOFcZVqwAABAMARzBFAiA3XiacXhBe6csVTmFZ8ksRZkx/YFNMmaX5CtZF
xCnI4gIhALuWVyqIKUZvMIjV/jWYI74LVokgpu9YFwUe3cmNl2RXAHYAouMK5EXv
va2bfjjtR2d3U9eCW4SU1yteGyzEuVCkR+cAAAGOFcZWzwAABAMARzBFAiEAjmfL
hm6KFdHjNUC4Cw3gFHgiSaI4TU0PYG/OfQxjCWICIFUAIHJvrQE8SfcMoPL6Rvt8
C/cXB5YcYcVayH0F8cxsMA0GCSqGSIb3DQEBCwUAA4IBAQBh3pjgjwkx2tTm1zEv
5N9ainZ2gRHlY4wCmygCeBu3jeQ8I7iKn9cFr3Nyv73D8qste9fD93AM4MGWVw8I
HBUHjs4lcTT9iuVjnu+FDQnQa9Z9m66kLJvv7EzikHkSWoH9Eg4c1binwLWk7mg2
I0KSTbdO+TNew5lTb14Fl5o+/24RTxqGSTLxmgfQE3jsl8FY08iuoxlS3y7PWG6d
1gQa4hs1D32QMh+UFk+uDTuN2qCWCr9XXclbpBR7HdMdLjkCrI9iAJr//KnXIliZ
C+k5AlX6hrJcxlY/oqEW9zLvJQaABW3QvnbhSRcUCqqrSF4Ai+MYUXpXClWDtS6H
ej3X
-----END CERTIFICATE-----
subject=CN = *.zerotier.com

issuer=C = BE, O = GlobalSign nv-sa, CN = GlobalSign Atlas R3 DV TLS CA 2024 Q1

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 3355 bytes and written 381 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_128_GCM_SHA256
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_128_GCM_SHA256
    Session-ID: FD859A7688252B8453673AE680F2F94C0B99536AF50AC2DE4B058EBD9246DCE6
    Session-ID-ctx:
    Resumption PSK: 71A764566D002F45CDB9C26284DDEDCAED5814F5E02D1815C127573D86DD3A1C
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 3600 (seconds)
    TLS session ticket:
    0000 - 00 25 4a e2 6e e2 a0 65-63 e2 ee dd 7d 46 cd 61   .%J.n..ec...}F.a
    0010 - 33 3e 67 0f b0 c2 63 ad-ec 9a ab 5c d6 05 76 f8   3>g...c....\..v.
    0020 - 98 4c 33 a7 f3 4c 09 99-73 69 55 4a 48 f8 3d e1   .L3..L..siUJH.=.
    0030 - 42 5f 6d ae 0c 7a 53 f2-b1 95 e1 bc b0 d0 91 aa   B_m..zS.........
    0040 - 64 fb 51 3d fa c8 d6 2b-47 cf a9 69 8d 41 24 7d   d.Q=...+G..i.A$}
    0050 - 37 28 08 fc bb 22 5f e4-01 4f fa c7 51 55 60 fe   7(..."_..O..QU`.
    0060 - 3e 6a 68 99 4c 03 9f 9c-a6 1a 91 4f 60 10 85 41   >jh.L......O`..A
    0070 - 43 f0 5c 5d 56 40 5c 0d-29 d5 10 e7 ff 87 de d5   C.\]V@\.).......
    0080 - 1d 14 28 31 a1 fe 9c 82-2a d2 19 e6 0c 82 25 f5   ..(1....*.....%.
    0090 - 9c 5b e1 65 b9 c1 59 3d-c0 53 88 6d 6c e8 ba 31   .[.e..Y=.S.ml..1

    Start Time: 1715614880
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
    Max Early Data: 8192
---
```

**Comment by someara** [comment]
Okay should be fixed up now.
Thanks everyone for the openssl output
-s

**Comment by MarcellVokk** [comment]
Thanks for the fast help, I apreciate it!
