### ISSUE TITLE
Version Naming inconsistency issue

### ISSUE THREAD

**Issue by cody151** [zerotier/ZeroTierOne#2297]
Hi there, there is a problem with the versioning system, I have version 1.6.5 installed from 2021 and now it is year 2024 and I installed the latest version which is somehow now "1.14.0", this is problematic because 1.6.5 is supposed to be higher than 1.14.0 I think the version "1.6.5" from 2021 should've been called 1.06.5 for example as this might be causing issues going forward now. Maybe it's best to switch to verion 1.2 after v 1.19 otherwise the versioning system will break.

**Comment by glimberg** [comment]
Version 1.2 came out many many years ago.  I assure you we won't be releasing another 1.2

**Comment by cody151** [comment]
Sure but version 1.14 is lower than version 1.6.5 which came out many years ago

**Comment by glimberg** [comment]
Only if you sort alphabetically. Version numbers aren't sorted alphabetically. 14 is higher than 6

**Comment by cody151** [comment]
Sorry I'm not trying to be rude just a genuine misunderstanding (plus maybe some dyslexia acting up?). I was under the impression version 1.6 is version 1.60 for example which would make it higher than v1.14 atleast in my head, again I apologise if I am wrong, did not expect the sarcasm/rudeness.

**Comment by glimberg** [comment]
Didn't intend any sarcasm or rudeness. 

Version 1.6.0 is exactly that. 1.6.0. Version 1.60.0, if we get there, would be exactly 1.60.0. There's no implied extra 0's anywhere in a version number.  Just exactly what's written. 

Version numbering isn't sorted as a string as a whole. You break them apart at the dots and then just treat each part as individual integers and sort that way.  

MAJOR.MINOR.PATCH

We haven't released anything above major version 1 yet. And we're up to 14 in minor versions so far.
