### ISSUE TITLE
Zerotier Central down

### ISSUE THREAD

**Issue by MarcellVokk** [zerotier/ZeroTierOne#2299]
It seems like Zerotier Central is down again. I am getting "500 Internal Server Error" back from API requests, and I am unable to open networks on the web UI.

![image](https://github.com/zerotier/ZeroTierOne/assets/40302952/209c4a75-2bc5-4503-b4e7-1c3b21fe5c13)

**Comment by MarcellVokk** [comment]
Additional info

![image](https://github.com/zerotier/ZeroTierOne/assets/40302952/e3a84f03-0561-443e-9b70-cd09ba1f90f6)

**Comment by MarcellVokk** [comment]
Apears to be fixed now, might have just been an issue on my end. Leaving this open until a moderator closes it in case it hapens again.

**Comment by laduke** [comment]
Sorry about that. A little hiccup in the webserver. It should be back now. The network itself wasn’t changed.
