### ISSUE TITLE
Enable SAML or OpenID Connect based AuthN to WebGUI

### ISSUE THREAD

**Issue by surfnet-niels** [zerotier/ZeroTierOne#230]
I would like to leverage SAML of OpenID Connect based authN to the https://www.zerotier.com/admin/admin.html interface. I cannot however find the code for the central admin environment in the source. Am I missing something?

**Comment by adamierymenko** [comment]
The central admin environment isn't open source at the moment, and we're working on a new version in any case. Try out the new version here:

https://my.zerotier.com/

The new version will have a better documented API, and we'll be adding new features such as this to that code base. In a week or so it will be replacing the existing site.

**Comment by adamierymenko** [comment]
Looks like this isn't too difficult. Added to backlog for ZeroTier Central.

**Comment by surfnet-niels** [comment]
Nice!
Please let me know if you need some resources to test against. I would be happy to assist.
