### ISSUE TITLE
Hello, I would like to customize the PLANET node

### ISSUE THREAD

**Issue by rabbbbit3** [zerotier/ZeroTierOne#2302]
I have custom added my customize PLANET node in the mkworld.cpp file, but I still want to keep ZEROTIER's public node. Is it compatible? At present, it seems that I am unable to connect to the public PLANET node properly due to my inability to obtain the key within the authtoken of the public PLANET node. Due to UDP blocking in my work area, I am unable to connect to the public PLANET server in the work area. However, I can connect normally elsewhere. I not only need to achieve interconnection between PCs, but also between PCs and mobile phones. May I ask if there is a solution?

**Comment by laduke** [comment]
To add roots on top of the default roots, use "moons". These are not well supported. 
Consider using your own tcp relay instead of moons.

**Comment by rabbbbit3** [comment]
At present, it seems that my work area network has a very strict UDP blocking, so usually I cannot even connect to the public PLANET node, which results in the inability to connect through P2P. In principle, it needs to be forwarded through the MOON node.
However, in recent days, it has been found that although MOON is configured, there is still a relatively high connection failure rate. I regenerated the PLANET file by modifying the mkworld.cpp file. After modifying my original MOON node to a PLANET node, it usually connects normally, but this has caused my handheld network connection to fail. Therefore, I would like to know if there are any corresponding solutions.
By querying the source code of the mkworld file, it appears that the purpose of connecting to the public LANET can be achieved by obtaining the IP address of the public node and the content of roots. back(). identity. Is it possible to have both personal and public LANETs in this way?

**Comment by rabbbbit3** [comment]
> To add roots on top of the default roots, use "moons". These are not well supported. Consider using your own tcp relay instead of moons.

At present, it seems that my work area network has a very strict UDP blocking, so usually I cannot even connect to the public PLANET node, which results in the inability to connect through P2P. In principle, it needs to be forwarded through the MOON node.
However, in recent days, it has been found that although MOON is configured, there is still a relatively high connection failure rate. I regenerated the PLANET file by modifying the mkworld.cpp file. After modifying my original MOON node to a PLANET node, it usually connects normally, but this has caused my handheld network connection to fail. Therefore, I would like to know if there are any corresponding solutions.
By querying the source code of the mkworld file, it appears that the purpose of connecting to the public LANET can be achieved by obtaining the IP address of the public node and the content of roots. back(). identity. Is it possible to have both personal and public LANETs in this way?
