### ISSUE TITLE
No route to host

### ISSUE THREAD

**Issue by Steven11q** [zerotier/ZeroTierOne#2308]
# Before filing a Bug Report

_Using these will ensure you get quicker support, and make this space available for code-related issues. Thank you!_

- [Docs Site](https://docs.zerotier.com/zerotier/troubleshooting) => Troubleshooting, quickstarts, and more advanced topics.
- [Discuss Forum](https://discuss.zerotier.com/) => Our discussion forum for users and support to mutually resolve issues & suggest ideas.
- [Reddit](https://www.reddit.com/r/zerotier/) => Our subreddit, which we monitor regularly and is fairly active.
- [Knowledge Base](https://zerotier.atlassian.net/wiki/spaces/SD/overview) => Older wiki.

If you are having a connection issue, it's much easier to diagnose through the discussion forum or the ticket system. 

# If you still want to file a Bug Report

## Please let us know

Proper connectivity after fresh install.
zerotier-cli status shows "tunneled," but systemctl status zerotier-one shows "no route to host" and i'm unable to ping/ssh other members of network. 
Ive installed multiple different os's trying to diagnose this issue and they have all had this same issue. Ive tried Tuxos, and Kubuntu both with the same issue, and tried installing through snap, the curl command, and compiling from source. Same issue. I dont have a firewall running. 
`systemctl status zerotier-one
● zerotier-one.service - ZeroTier One
     Loaded: loaded (/lib/systemd/system/zerotier-one.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2024-06-09 14:16:56 EDT; 1min 7s ago
   Main PID: 22527 (zerotier-one)
      Tasks: 23 (limit: 13844)
     Memory: 4.2M
        CPU: 117ms
     CGroup: /system.slice/zerotier-one.service
             └─22527 /usr/sbin/zerotier-one

Jun 09 14:16:56 hunter-20bfs0ec00 systemd[1]: Started ZeroTier One.
Jun 09 14:16:56 hunter-20bfs0ec00 zerotier-one[22527]: Starting Control Plane...
Jun 09 14:16:56 hunter-20bfs0ec00 zerotier-one[22527]: Starting V6 Control Plane...
Jun 09 14:18:01 hunter-20bfs0ec00 zerotier-one[22527]: connect: No route to host
Jun 09 14:18:04 hunter-20bfs0ec00 zerotier-one[22527]: connect: No route to host
`

`sudo zerotier-cli status
200 info 08f72d664f 1.14.0 TUNNELED
`
(this was after I tried manually adding this node through the web interface, in the past it just said "connected" after i used the join commands) 
Tuxos 2, zt 1.14.0

**Comment by laduke** [comment]
It must be something like your ISP or internet router blocking UDP or doing something else weird.
