### ISSUE TITLE
Zerotier keep requesting netconf for network but dont work

### ISSUE THREAD

**Issue by pandada8** [zerotier/ZeroTierOne#231]
I am using 1.0.5 with debug enabled version, and i can not connect anyone in my zt network.
the log is full of  requesting netconf  but none of success info.
could the controller be blocked in china?

ping other nodes shows `Destination Host Unreachable`

**Comment by pandada8** [comment]
Could we using a proxy when fetching the network info?

**Comment by whlspacedude** [comment]
Where in China is your node? I had a test user in Shanghai and he was able to use It across his home internet connection pretty well. Unfortunately he has moved and at his current apartment he is unable to use the node I sent him.

**Comment by pandada8** [comment]
@whlspacedude 
it's quite strange and i don't know why
I run some node in some complex NATed network, some are in the public vps(aliyun), the node in the aliyun runs well. but the node NATed was quite unstable. i could see them flaged as online in the panel. but i cannot ping them.
I could see many netconf requests in the NATed log, much more than other node.
the IPS is Sichuan Telecom mixed with CERNET.

**Comment by pandada8** [comment]
Log pastebin here: http://pastebin.com/2FcZnMnG
