### ISSUE TITLE
Cannot change login details

### ISSUE THREAD

**Issue by michailsideris-gvf** [zerotier/ZeroTierOne#232]
I have a account with ZeroTier which uses Google to login. I would like to change that to another email provider and add a password. I can successfully change the email address (though on the login ID it still says 'google') and set a password. But when I logout to see if I can login with the new email and the newly set password it never works. I can still login via Google, though.

**Comment by adamierymenko** [comment]
Please e-mail support@zerotier.com and we can manually change your login details. Also set your display name to 'CHANGE-PLS' to prove control of the account.

**Comment by michailsideris-gvf** [comment]
I have already sent an email (twice) regarding this issue and received no response whatsoever. Is there any problem?

**Comment by adamierymenko** [comment]
Where did you send the e-mail? contact@zerotier.com is the usual.

**Comment by michailsideris-gvf** [comment]
I sent it to support@zerotier.com as requested.



Von: Adam Ierymenko
Gesendet: Montag, 19. Oktober, 17:53
Betreff: Re: [ZeroTierOne] Cannot change login details (#232)
An: zerotier/ZeroTierOne
Cc: Michail Sideris

Where did you send the e-mail? contact@zerotier.com<mailto:contact@zerotier.com> is the usual.

-
Reply to this email directly or view it on GitHub<https://github.com/zerotier/ZeroTierOne/issues/232#issuecomment-149256334>.



-----------------------------------------------------

[Nie mehr umsonst melken dank der Milchkasko! Berechnen Sie Ihr pers?nliches Angebot bei den Erfindern der Milchkasko.]<http://www.gvf.de/milchkasko-rechner/>

gvf VersicherungsMakler AG
Wir sichern Landwirtschaft.

www.gvf.de<http://www.gvf.de>

Tel.: +49 371 27830
Fax: +49 371 27832000

gvf VersicherungsMakler AG
An der Wiesenm?hle 13
09224 Chemnitz

Vorstand: Christoph Herrmann (Vorstandsvorsitzender), Michael Herbst, Dieter Herrmann, Harald Herrmann, Alexander Kohl, Sebastian Mahler
Vorsitzender des Aufsichtsrats: Clas-Erik von Nottbeck
Sitz der Gesellschaft: Chemnitz
Registergericht Chemnitz - HRB 18512
