### ISSUE TITLE
docker zerotier-synology 1.14.0 not working

### ISSUE THREAD

**Issue by BradCOnGitHub** [zerotier/ZeroTierOne#2324]
I've been successfully running zerotier-synology 1.10.6 on a Synology DS1618+ with DSM 7.1.1-42962 Update 6

Recently attempted to upgrade the docker image using :latest and it went to 1.14.0. Everything appears working except when I do a listnetworks nothing is there, and there is no connectivity

```
root@DiskStation:~# docker exec -it zt zerotier-cli listnetworks
200 listnetworks <nwid> <name> <mac> <status> <type> <dev> <ZT assigned ips>
root@DiskStation:~# 

```

my.zerotier.com always showed the member as connected and zerotier-cli status always showed ONLINE

Rebooting the NAS didn't help. Wiping out the entire config and starting over didn't help. Finally just downgraded the image back to zerotier/zerotier-synology:1.10.6 and everything was fine again.

**Comment by joseph-henry** [comment]
Thanks for the report. I was able to replicate this. Not sure why it didn't show up in my testing but I'll take a look and update this ticket once I have a new version pushed.

**Comment by joseph-henry** [comment]
On further testing I'm seeing the same issue on 1.10.6 (which worked previously for me as well) so I think it's something else.
