### ISSUE TITLE
error while loading shared libraries: libminiupnpc.so.17 (Arch Linux)

### ISSUE THREAD

**Issue by EyBmr** [zerotier/ZeroTierOne#2325]
Arch Linux recently updated "miniupnpc" to 2.2.8-1.

Please update zerotier-one to use the new version of miniupnpc.

zerotier-cli: error while loading shared libraries: libminiupnpc.so.17: cannot open shared object file: No such file or directory

**Comment by EyBmr** [comment]
Sorry, I forgot to add the temporary solution for those who want to get zerotier-one working again without downgrading the miniupnpc package.

Run this in your terminal:
`sudo ln -s /usr/lib/libminiupnpc.so.18 /usr/lib/libminiupnpc.so.17`

**Comment by cavaros** [comment]
> Sorry, I forgot to add the temporary solution for those who want to get zerotier-one working again without downgrading the miniupnpc package.
> 
> Run this in your terminal: `sudo ln -s /usr/lib/libminiupnpc.so.18 /usr/lib/libminiupnpc.so.17`

Thank you!!! I noticed the problem when my Sunshine crashed, and your solution fixed it!

**Comment by EyBmr** [comment]
The temporary fix is no longer needed for zerotier-one. It has been updated to use the new version of the miniupnpc library.

Delete the symbolic link with `sudo rm /usr/lib/libminiupnpc.so.17`

**Comment by kane-thornwyrd** [comment]
Not directly related to zerotier, but I've found this while searching for this error when launching Godot after installing the godot-export-templates-git-4.3.r65912.3e0c10d3931-1  godot-git-4.3.0.r6067.g4ab8fb809396-1 packets… And the symbolic link is a valid solution that solved my issue too. So I'm thankful for this, and hope it might help more people.

**Comment by MissingTwins** [comment]
**Temporary Workaround for ZeroTier Crashing (Entware/OpenWrt with miniupnpc 2.2.8 and ZeroTier 1.14.1)**

If you're experiencing crashing issues with ZeroTier 1.14.1 on your Entware/OpenWrt system with miniupnpc 2.2.8, you can temporarily mitigate this by downgrading ZeroTier to version 1.12.2 and manually installing miniupnpc 2.2.3.

**Steps:**

1.  **Download miniupnpc 2.2.3:**
    ```
    wget <url>/libminiupnpc_2.2.3-1_aarch64-3.10.ipk
    ```
    *(Replace `<url>` with the actual download link for the `libminiupnpc` package.)*

2.  **Extract the necessary library:**
    ```
    tar zxvf libminiupnpc_2.2.3-1_aarch64-3.10.ipk data.tar.gz
    tar -zxf data.tar.gz opt/lib/libminiupnpc.so.*
    ```

3.  **Move the extracted library to the Entware library directory:**
    ```
    mv opt/lib/libminiupnpc.so.* <your path>/entware/lib/
    ```
    *(Assuming `/entware` is your Entware mount point. Adjust the path if necessary.)*

Afterward, your Entware library directory should contain both versions of the `libminiupnpc.so` files, similar to this:

```
# ls -al /tmp/mnt/GBDISK/entware/lib/libminiupnpc.so.*
lrwxrwxrwx    1 router   root            21 Apr  4 01:01 /tmp/mnt/GBDISK/entware/lib/libminiupnpc.so.17 -> libminiupnpc.so.2.2.3
lrwxrwxrwx    1 router   root            21 Apr  3 23:06 /tmp/mnt/GBDISK/entware/lib/libminiupnpc.so.18 -> libminiupnpc.so.2.2.8
-rw-r--r--    1 router   root         55192 Feb 23  2024 /tmp/mnt/GBDISK/entware/lib/libminiupnpc.so.2.2.3
-rw-r--r--    1 router   root         55192 Jan  9 03:16 /tmp/mnt/GBDISK/entware/lib/libminiupnpc.so.2.2.8
```
