### ISSUE TITLE
zerotier-cli set <my_network_id> mtu=1300 does not apply

### ISSUE THREAD

**Issue by nszceta** [zerotier/ZeroTierOne#2326]
- What you expect to be happening.

```sh
$ sudo zerotier-cli set <my_network_id> mtu=1300
$ sudo zerotier-cli get <my_network_id> mtu
1300
$ ip link show ztbpamon2r
4: ztbpamon2r: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1300 qdisc pfifo_fast state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether <censored>
```
- What is actually happening?

```sh
$ sudo zerotier-cli set <my_network_id> mtu=1300
$ sudo zerotier-cli get <my_network_id> mtu
2800
$ ip link show ztbpamon2r
4: ztbpamon2r: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2800 qdisc pfifo_fast state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether <censored>
```

- Any steps to reproduce the error.

```
sudo zerotier-cli set <my_network_id> mtu=1300
```

- Any relevant console output or screenshots.

No

- What operating system and ZeroTier version. Please try the latest ZeroTier release. 

```sh
$ zerotier-one --version
ZeroTier One version 1.14.0

$ zerotier-cli --version
ZeroTier One version 1.14.0 build 0 (platform 1 arch 4)

Linux raspberrypi 6.6.28+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.28-1+rpt1 (2024-04-22) aarch64 GNU/Linux
```

My current workaround:

```
$ cat /etc/systemd/system/zt-mtu-monitor.service 
[Unit]
Description=Monitor and set MTU for ZT interfaces
After=network.target
StartLimitIntervalSec=0

[Service]
Type=simple
ExecStart=/bin/bash -c 'while true; do for i in $(ip -o link show | awk -F": " \'/zt/  {print $2}\'); do ip link set $i mtu 1300 || true; done; sleep 5; done'
Restart=always
RestartSec=5
StartLimitBurst=0

[Install]
WantedBy=multi-user.target
```

**Comment by nszceta** [comment]
This workaround is 100% necessary for certain endpoints to be reachable at all behind certain hotspots. They are connected to the hotspot over an ethernet connection which may be why ZT erroneously believes the connection is capable of a high MTU. Unless MTU is 1300 connections completely stall out to these endpoints. This is a critical problem.

**Comment by nszceta** [comment]
Sweet I'll give it a shot

**Comment by nszceta** [comment]
What are the consequences of having MTU set to 1300 for my devices behind a hotspot and 2800 for everything else on that network?

**Comment by joseph-henry** [comment]
I think you might just see some difference in throughput performance. Depending on what type of traffic you're sending an MTU *difference* of even `1` could radically change performance if the packet division point isn't optimal. I'd play around with the number to find what's right for you.
