### ISSUE TITLE
Installation error : "Make sure enough disk space" on Win11,but I did have enough extra space

### ISSUE THREAD

**Issue by InfinitIC123** [zerotier/ZeroTierOne#2331]
Installation failed on my laptop,error info like below:

"An error occurred while writing installation information to
disk. Check to make sure enough disk space is available,
and click “Retry”, or “Cancel” to end the install."

However I already make sure I have enough space.I have the sceenshot,the error and my system info both in it
![zerotier](https://github.com/zerotier/ZeroTierOne/assets/118709344/4cf32a6f-6f5a-47dd-9072-e9e15124a7c9)

But it’s only occures on my laptop.
I have 2 devices,one of them is my PC and the other is laptop,The PC can install it successfully, but my laptop can’t,both of them are in win11,even have the same os system version number ,so I’m so confused.Ineed help,@dear developers

**Comment by joseph-henry** [comment]
This is most certainly some sort of OS issue, possibly a hardware issue with your drive. Have you tried installing on each drive? What type of drives are they?

**Comment by InfinitIC123** [comment]
Hi,@joseph-henry ,
     Thanks for your reply.I tried to install it to other drives,but unfortunately there is no select option after I clicked  the installer named "ZeroTier One.msi",Just an install button with my administration request.
![image](https://github.com/user-attachments/assets/a982d276-dbe3-4d3a-ae01-77c501d5e6cb)

My main drive section C and D are splited from a physical drive,it's an SSD drive from sumsung.
![image](https://github.com/user-attachments/assets/2bc9c52f-daf9-4170-83b0-63aadd8bce6f)

**Comment by InfinitIC123** [comment]
Hi，@joseph-henry ，
Thanks for your patient replys.I have tried to install some of exe installers,and they all work well,but I did not try the msi type installes,I will try some of msi installers as you told me.And I think check my ssd healthy is a good idea,I will try it too. thanks for the tips.

It did Looks like an OS problem.as I mentioned before,this software works well in my PC,only my laptop has this issue.So I will close this issue request for now,but you should know no matter what,I appreciate your patience and efforts for me and other guys like me.Thank you for developing this software,it's really helpful.

Thanks again.
Best wishes.

**Comment by InfinitIC123** [comment]
PS:
I reinstall the OS eventually,And all the problems solved aumatically,LOL.
Tips:
Don't test any dangerous activities like me,learn to use vitual machines like vmware.
