### ISSUE TITLE
Adding Zerotier-Synology for ARM64 machines

### ISSUE THREAD

**Issue by dengzeyu** [zerotier/ZeroTierOne#2335]
Hi I'm using Synology DS120j as a remote backup machine. However, there is no official support of the Zerotier-Synology for the ARM64 machines (https://hub.docker.com/r/zerotier/zerotier-synology). I can only find the linux/amd64 version. Could you please add the ARM64 version of the docker image? Thanks!

**Comment by joseph-henry** [comment]
New multi-arch images pushed: https://hub.docker.com/r/zerotier/zerotier-synology/tags When you run the container use `host` networking and make sure you give it `high privileges` if you're using `Container Station`.

I'll close this ticket but please re-open if you have issues. Thanks!
