### ISSUE TITLE
How to handle the situation when root server is down

### ISSUE THREAD

**Issue by bitxel** [zerotier/ZeroTierOne#234]
Hi all, I have compiled zerotier from source with network controller. I created  2 root servers, and a private network using one of it. I config these root servers as relay server as well. Then I join the network using another two PCs, they can successfully ping each other and the root server.  
After that, I shutdown the zerotier on network controller server, then PCs can't ping each other. The relay node doesn't seem to work.
I'm wondering if there is configuration or fallback solution under this circumstance.

Here is the my networks configuration.

```
{
        "nwid": "f69b09ca04000000",
        "controllerInstanceId": "57b6f8fe57c821470d32b31e9cb816c3",
        "name": "test",
        "private": true,
        "enableBroadcast": true,
        "allowPassiveBridging": false,
        "v4AssignMode": "zt",
        "v6AssignMode": "none",
        "multicastLimit": 32,
        "creationTime": 1439528623066,
        "revision": 100,
        "memberRevisionCounter": 280,
        "relays": [
                {"address":"06e898016a","phyAddress":"a.b.c.d\/9993"},
                {"address":"f69b09ca04","phyAddress":"a.b.c.d\/9993"}],
        "gateways": ["25.25.0.1/32"],
        "ipLocalRoutes": ["25.25.0.0/16"],
        "ipAssignmentPools": [
                {"ipRangeStart":"25.25.0.1","ipRangeEnd":"25.25.255.255"}],
        "rules": [
        {
                "ruleNo": 1,
                "action": "accept"
        }]
}
```

**Comment by adamierymenko** [comment]
Let me clarify a bit--

You created your own controller, then created a network on it. For that network you specified two relays, one of which is the controller (which is fine) and another is a third party node. Then you shut down both relays.

After sufficient time (usually two minutes), it should fall back to using the global root servers as relays and connection-establishment nodes. If it doesn't, then that's a bug (per-network relays is not heavily tested yet, as most users don't use them and they're not exposed in the UI yet).

Also if the nodes were able to connect directly they should continue talking even if their relays are all gone. If you get /peer on the nodes (or zerotier-cli listpeers) do you see direct paths between them or are they behind NATs/firewalls that do not allow this?

**Comment by bitxel** [comment]
@adamierymenko I get what you mean and I have a rough idea of the problem. 

I create my own root server because latency is a little bit high (on average over 300ms) and not stable ( so I generate root-topology-authority.secret and create new root server using mktopology.cpp, then replace the global root servers.) 

I am wondering if the controller can be another node different from root node. From what you said, I think answer is true. 

Thus,  I think a feasible solution to `low latency` is that I create my server, and add it to root servers rather than replace root servers. So if  my root server is down, zerotier client will fall back to using the global root servers.

What do you think of that? I will try it later :)

**Comment by adamierymenko** [comment]
Where are you physically located?

What you did will work for a closed deployment, but we've actually just changed how root topologies (now called worlds) are done in -dev. You could still do what you did but you'd have to re-do it.

But instead, maybe we can get a root server closer to you? We're preparing to expand our network and make it easier to expand further in the future.
