### ISSUE TITLE
at 12:23 pm on weekends zerotier stops working!

### ISSUE THREAD

**Issue by nullequal** [zerotier/ZeroTierOne#2341]
only in piss country

**Comment by MACOSLOVER30000000000** [comment]
Can Confirm! On M1 MacBook Air! I Love apples SO MUCH!

**Comment by MACOSLOVER30000000000** [comment]
![image](https://github.com/user-attachments/assets/28bcbb7b-4279-4602-8ad4-6761f5534de1)
![image](https://github.com/user-attachments/assets/bde4aa54-9460-4506-aefa-f1d5ad460cb6)
![image](https://github.com/user-attachments/assets/57adbf64-2a18-4ef7-816c-72c5615079fb)
![image](https://github.com/user-attachments/assets/b3621285-68fa-4c8d-b0ba-9daefae96761)

**Comment by nullequal** [comment]
wtf why is it not working

**Comment by MACOSLOVER30000000000** [comment]
![image](https://github.com/user-attachments/assets/e84aa7c3-847d-4bc4-b51e-261b803a0cd7)
![image](https://github.com/user-attachments/assets/6a58152c-0416-42f4-a0a6-ffbe0736c568)
![image](https://github.com/user-attachments/assets/345fdc5c-4812-4ac2-9967-ea38a99c5eb3)
![image](https://github.com/user-attachments/assets/a31e610e-2530-4322-b2cb-38967518102d)
![image](https://github.com/user-attachments/assets/62fc38bd-735d-4079-a424-21886f1072a0)
![image](https://github.com/user-attachments/assets/fa77ab48-7de6-4878-8308-f0ca70a4b3db)
![image](https://github.com/user-attachments/assets/506d02ea-813b-4eb9-8f80-3157803d86cb)

**Comment by MACOSLOVER30000000000** [comment]
![image](https://github.com/user-attachments/assets/f6b1899c-714b-4bed-8ee4-6a67ed0d37de)

**Comment by MACOSLOVER30000000000** [comment]
![image](https://github.com/user-attachments/assets/ba5268f7-da9e-4b71-81cf-660ba4283511)
![image](https://github.com/user-attachments/assets/58c60e4b-df09-4ace-9d04-70e077dbdc3c)
gru zerotier

**Comment by MACOSLOVER30000000000** [comment]
Contact me on Discord for more information! My discord is @fedya126

**Comment by MACOSLOVER30000000000** [comment]
PLZ

**Comment by MACOSLOVER30000000000** [comment]
![image](https://github.com/user-attachments/assets/7ace46f6-8e86-4300-8ba7-21ac05366e32)

**Comment by glimberg** [comment]
Hello,  Sorry you're having issues.  Please include deals like OS, OS version, version of ZeroTier, and any other relevant information that can be used to help reproduce the issue.

**Comment by nullequal** [comment]
OS: MacBook Air OS,
M1, 
MacOS Version 13
Apple

**Comment by nullequal** [comment]
pls respond fast! i need zerotier UREGENLY

**Comment by laduke** [comment]
This doesn't happen to anyone else, so it's hard to guess what it could be. 

Try the [emergency instructions](https://docs.zerotier.com/troubleshooting#emergency-instructions) to get running again

**Comment by nullequal** [comment]
Ben a week! No emergency success. I must ask for the help. 😭 I need 0tier!

**Comment by joseph-henry** [comment]
We've never heard of anything like this before. It sounds like a network problem on your end (something possibly blocking traffic after a certain time?) Do you have any software that starts at that tie on your system?

You can send us the output of `zerotier-cli info` and `zerotier-cli peers` (redact as you see fit) when it isn't working. But it would be better if you created a ticket by logging into your account and sent us the output of `zerotier-cli dump` privately there.

**Comment by nullequal** [comment]
now zerotier doesnt work on holidays oh come on man gru despicable me is going to be so angry

**Comment by laduke** [comment]
unplug it and plug it back in

**Comment by joseph-henry** [comment]
Sorry but this is not a ZeroTier issue and the information we requested to help diagnose was not provided. Closing ticket.

If you want to provide the information we requested I'd suggest logging into Central and sending us the outputs of the commands there.
