### ISSUE TITLE
   missing  /etc/init.d/zerotier-one

### ISSUE THREAD

**Issue by Mareckil** [zerotier/ZeroTierOne#2355]
Hi there, I just installed Zerotier on my Linux Mint. All compilation went well, but I cant run a service of zerotier-one. As above /etc/init.d/zerotier-one is missing.

I did run it with following command:
sudo zerotier-one -d

And then get this:

sudo systemctl status zerotier-one
Unit zerotier-one.service could not be found.

sudo zerotier-cli status
200 info 46763d79e2 1.14.0 ONLINE

**Comment by joseph-henry** [comment]
Compiling will only build the binary. It doesn't modify anything in the system. You'd have to run `make install` to actually install it. Also, `zerotier-one -d` merely runs ZeroTier as a daemon. Good luck!

**Comment by Mareckil** [comment]
Thank you for your answer, I understand that compiling doesn't install software, so just after that I did run make install as you've mentioned. Also as I showed in my message I can run daemon, but I can't set it up as a service. That is my problem.

**Comment by laduke** [comment]
https://www.zerotier.com/download/ will set it up
then if you want to use your compiled version, you can copy it over what's installed in /var/lib/zerotier-one

**Comment by Mareckil** [comment]
Once again thanks for your assistance. To be honest it was my first attempt to download precompiled package unfortunately installation fails with following message:

Unsupported distribution linuxmint 21.3

**Comment by laduke** [comment]
sorry about that. When it fails it prints instructions for how to help us fix it.
