### ISSUE TITLE
Connection

### ISSUE THREAD

**Issue by NDG312** [zerotier/ZeroTierOne#2358]
I host my own minecraft server and I use zerotier, but one of my friends who uses a computer, connects to zerotier always has a ping above 500 even though our houses are no more than 1km apart and our network is fine. Another friend of mine uses a phone but the ping is only around 60. Is there any way to fix this?
My friend uses windows and just installed zerotier then used it without changing anything.

**Comment by laduke** [comment]
- Upgrade everyone to the latest version.
- https://docs.zerotier.com/routertips/
- https://docs.zerotier.com/corporate-firewalls/

sorry can't really help in depth. maybe the forum can help
