### ISSUE TITLE
v1.14.1 does not build on FreeBSD

### ISSUE THREAD

**Issue by tinola** [zerotier/ZeroTierOne#2370]
Hi,

I can't build zerotier-one, please take a look on attached log

OS: FreeBSD 14.1-RELEASE-p4
ZT: latest dev or 1.14.1 tag

Version 1.14.0 is building fine.
[build.log](https://github.com/user-attachments/files/17026918/build.log)

**Comment by joseph-henry** [comment]
@tinola Thanks for reporting. See if that PR fixes your issue.

**Comment by tinola** [comment]
@joseph-henry Thanks, your changes did the trick! There're still some warnings, but the binary is building just fine.
You can marge PR in dev.
Thank you.
