### ISSUE TITLE
Update repo website link

### ISSUE THREAD

**Issue by fulldecent** [zerotier/ZeroTierOne#2381]
Currently it links to zerotier.com (apex domain) which is a broken link. 

The correct link is www.zerotier.com which is the working website. 

This is in the GiHub project config and I can't send a PR. The admin needs to do this.

**Comment by laduke** [comment]
ummm... thanks. we'll fix the apex domain.

**Comment by laduke** [comment]
thanks 

https://zerotier.com

**Comment by fulldecent** [comment]
Cool, thanks, working. Rock on.
