### ISSUE TITLE
Can't remove members of public networks

### ISSUE THREAD

**Issue by CTassisF** [zerotier/ZeroTierOne#240]
Hello.

In the old web interface we could remove members from public networks, but it seems that we can't do this anymore in the new web interface.
I used this feature not to "block" devices from public networks (because I know this isn't the purpose of public networks), but to remove old devices that didn't connect after a while to keep the devices list clean.
Can you please re-implement the "remove device" feature on public networks (or, at least, automatically hide/remove devices after a few weeks/months since the last time online)?

Thanks in advance.

**Comment by adamierymenko** [comment]
Removal of members from public networks in the old UI was itself a bit of a bug. While you could remove a member's IP address, a public network is just that -- public. It has no access control and issues no certificates. So there would be nothing stopping someone from just statically setting their IP or deleting their identity and rejoining with a different one.

**Comment by adamierymenko** [comment]
Think of a public network as an open Ethernet-based IRC channel. A private network is like an invite-only channel, or more like a keyed channel where the key you need is a certificate.

**Comment by konrad-zielinski** [comment]
What about members that just do not exist anymore? I deleted an experimental VM because it ceased to be accessible and I would just like to get rid of it's traces on a ZT network. How do I do that?

**Comment by adamierymenko** [comment]
That's a UI issue -- we need to implement a member cleanup feature. Will add to Central queue.

**Comment by questionaut** [comment]
How do you remove a member from the Zerotier web user interface?

**Comment by konrad-zielinski** [comment]
After three years the functionality is still not there (or maybe is not easily discoverable). @adamierymenko?

**Comment by glimberg** [comment]
You can't delete members of a public network as they'd just show up again if still joined to a network.

**Comment by konrad-zielinski** [comment]
@glimberg Please see my [comment](https://github.com/zerotier/ZeroTierOne/issues/240#issuecomment-285766863) from 2017.

I would like to delete members from a public network that I know for sure will never show up again as they do not exist anymore.

**Comment by ChaosJohn** [comment]
@konrad-zielinski 
That's also what I mean. 
I'm sure the member will never be back again so I decide to delete it.
