### ISSUE TITLE
Docker image release of v 1.14.2 / Release cycle of docker images

### ISSUE THREAD

**Issue by umarhussain15** [zerotier/ZeroTierOne#2401]
Hi,
We have a new release of zerotier version 1.14.2 which is available in Linux distributions, but the docker image is still not available in docker registry: https://hub.docker.com/r/zerotier/zerotier/tags (as of writing this ticket)
## Please let us know

- What you expect to be happening.
The docker image is released at the same time as a new version is available to Linux distributions
- What is actually happening?
The new version is not availabe in the registry. For version 1.14.1 it was[ released on GitHub on September 13 2024](https://github.com/zerotier/ZeroTierOne/releases/tag/1.14.1) and the Docker image was [released on October 2nd 2024](https://hub.docker.com/layers/zerotier/zerotier/1.14.1/images/sha256-7f42b7e05190797b5fb77856da28780d7ea2acdeff631ca434c3281573bef946?context=explore)
- Any steps to reproduce the error.
This mismatch is causing an issue where our Moon nodes are on version 1.14.1 as they are running in docker but most of our clients are on version 1.14.2. So the clients are not seeing these moons as MOON but LEAF with no connection to them

**Comment by glimberg** [comment]
Whoops.  Forgot to push that out.   It's up there now
