### ISSUE TITLE
get link status with other nodes via API (like zerotier-cli peers)

### ISSUE THREAD

**Issue by kohlersDagger** [zerotier/ZeroTierOne#2404]
In the `zerotier-cli peers` command, I get a column called `<link>` and use `DIRECT/RELAY` to indicate whether the two nodes are directly connected to each other or not, but with `http://localhost:9993/peer` I can't get the information like `DIRECT/RELAY` or something like that. Can you please add this response field in subsequent versions of zerotier? Or is there any other way I can determine the link status?

**Comment by laduke** [comment]
I think it's just that the `paths` array is empty when it's relaying

**Comment by kohlersDagger** [comment]
> I think it's just that the `paths` array is empty when it's relaying

you're concrete, this works for me. thanks a lot.
