### ISSUE TITLE
Unable to Create UPnP Mapping for Temporary Lease

### ISSUE THREAD

**Issue by bleppard** [zerotier/ZeroTierOne#242]
I have been eagerly looking forward to ZeroTier implementing UPnP support, but it looks like my router is incompatible with ZeroTier's implementation. 

I use a MikroTik RouterOS based router and it appears to not support the NewLeaseDuration feature. The following error is received back from the router when the UPnP mapping is requested:
```
<UPnPError xmlns="urn:schemas-upnp-org:control-1-0">
  <errorCode>725</errorCode>
  <errorDescription>OnlyPermanentLeasesSupported</errorDescription>
</UPnPError>
```
Googling the `OnlyPermanentLeasesSupported` error message, it seems that although this error isn't common other products have experience this error. At least one other UPnP client has set `NewLeaseDuration` to 0 upon the receipt of `OnlyPermanentLeasesSupported`.

The full network pcap file is available upon request.

Running ZeroTier One 1.0.5 on Windows 8.1 64 bit.

![networkerrormessage](https://cloud.githubusercontent.com/assets/2224704/10747944/42af4c82-7c31-11e5-9a17-df529bfff5a4.png)

**Comment by bleppard** [comment]
It looks like the standard practice[1] is to set the lease duration to 0. 


[1] - https://searchcode.com/?q=UPNP_AddPortMapping&p=1&loc=0&loc2=10000

**Comment by bleppard** [comment]
Just tried it, changing the duration form "3600" to "0" does allow the mapping to be established.

**Comment by adamierymenko** [comment]
K, this will get changed in the next version -- thanks!

**Comment by heri16** [comment]
Really looking forward to next version or a hotfix as I am also experiencing the same issues with Mikrotik RouterOS (a popular low-cost business-class router).

**Comment by adamierymenko** [comment]
Fixed in -edge which will become -dev shortly. (Don't use edge now... it connects to a test net!)

**Comment by heri16** [comment]
I am sorry, but this issue should be re-opened as I last tested the solution and still no ports were opened. Using miniupnpc command line interface works with Mikrotik RouterOS, and the ports were opened.
Zerotier One will not even correctly send an AddPortMapping xml according to Wireshark captures on my end.

**Comment by adamierymenko** [comment]
Is this a miniupnpc version issue?

**Comment by adamierymenko** [comment]
Definitely looks like we should update: http://miniupnp.free.fr/files/changelog.php?file=miniupnpc-1.9.20151026.tar.gz

Updated to latest version and changed the makefiles for Mac and Linux to build from source. Will still keep the blob around for Windows but will rebuild and update that too.

**Comment by adamierymenko** [comment]
Updated in edge... we'll try using the latest in this version and see if it makes any difference.

**Comment by heri16** [comment]
Hi @bleppard , does the latest version of zerotier work for you yet? On my version 0.1.0 it does not seem to successfully open port mapping on Mikrotik RouterOs v6.27

**Comment by bleppard** [comment]
Version 1.1.0 on Windows 8.1 isn't working for me. This new version does behave very differently for upnp. I do see it making a lot of upnp calls, but I don't ever see it making the AppPortMapping call, which could explain why no port mapping takes places.

**Comment by heri16** [comment]
Exactly the same behaviour observed here.

**Comment by heri16** [comment]
Exactly the same behaviour observed here.

**Comment by adamierymenko** [comment]
Retitling and escalating since other issues with UPnP have been noted. Going to overhaul that subsystem and also probably add NAT-PMP support.

UPnP and NAT-PMP and... wow... what a mess endpoint networking is.

**Comment by janjaapbos** [comment]
It does work for me, but not always reliably. I have the following suggestions:

1. Taking into account that there are multiple ZT devices on the same host ip behind the same NAT router, it would be good to be able to uniquely refer to the created mapping, e.g. adding the device id to the service name. 

2. When starting up, ZT should check whether a mapping has already been created. Otherwise, mappings get added all the time, but never deleted by the NAT router (mappings do not expire?)

3. Once in a while ZT should check whether the mapping is still present on the NAT router (e.g. in case of a router reboot).

4. Try to deal with situations where peers behind the same router are not able to access the mapping on the external interface of the NAT router.

**Comment by adamierymenko** [comment]
It does appear that uPnP has issues in 1.1.0. Just did a rework of it that should hopefully fix several of them, and also added NAT-PMP support which is common on Apple devices like the Airport Express and is quite a bit cleaner than uPnP. There will be a 1.1.2 relatively soon that will include this.

**Comment by adamierymenko** [comment]
1.1.2 is out now with a redesigned UPnP implementation and NAT-PMP support.

**Comment by heri16** [comment]
Tried 1.1.2 and the UPnP does not work at all. I see NAT-PMP discovery packets in wireshark, but none at all for UPnP. Shouldn't there be beta user testing before an official release?
