### ISSUE TITLE
Allow IP to be copied

### ISSUE THREAD

**Issue by surfnet-niels** [zerotier/ZeroTierOne#244]
In ZeroTier Central the I of the nodes is shown as 4 seperate numbers, which cannot be copied easily all at once
Please allow some way to copy the whole IP addres of the node easily

![selection_296](https://cloud.githubusercontent.com/assets/1491826/11029331/87b0a034-86c6-11e5-9342-9750ad91c139.jpg)

**Comment by adamierymenko** [comment]
Should probably re-do this control to use a single form element. Will do on next web rev.

**Comment by jdrews** [comment]
I believe this is completed in the new ZeroTier Central

**Comment by adamierymenko** [comment]
Yes. Closing.
