### ISSUE TITLE
Admin API: DELETE a network/device works but return a 500

### ISSUE THREAD

**Issue by edouardswiac** [zerotier/ZeroTierOne#245]
I am working on a java lib for the admin REST API (https://github.com/edouardswiac/zerotier-api-java), and I noticed that DELETE'ing a network or a device succeeds but return a 500. it's a minor glitch which is also responsible for having the loading spinner run indefinitely (at least for me) after clicking on delete.

If I have time this week I will look into it myself. @adamierymenko where should I start looking?

**Comment by adamierymenko** [comment]
SqliteNetworkController.cpp

**Comment by adamierymenko** [comment]
Is anyone still seeing this? I can't seem to reproduce it.

**Comment by advanderveer** [comment]
I'm having this issue, also when using the API programmatically; should be easy to produce:

(session and zt network id removed)
```
curl 'https://my.zerotier.com/api/network/<zt_network_id>' -X DELETE -H 'origin: https://my.zerotier.com' -H 'accept-encoding: gzip, deflate, sdch' -H 'x-requested-with: XMLHttpRequest' -H 'accept-language: en-US,en;q=0.8,de;q=0.6,fr;q=0.4,nl;q=0.2' -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36' -H 'accept: application/json, text/javascript, */*; q=0.01' -H 'referer: https://my.zerotier.com/' -H 'cookie: _ga=GA1.2.705202904.1438355347; zt.central.session=<zt_session>; zt.central.ui.lastActiveTab=1' --compressed
```
