### ISSUE TITLE
Starting ZeroTier via ssh script hangs

### ISSUE THREAD

**Issue by naasking** [zerotier/ZeroTierOne#246]
I have a shell script that connects to a few Raspberry Pis running Rasbian using ssh, and tries to start ZeroTier, but ZeroTier's init script hangs on start/restart. For example, this is the core idea behind the script I have:

    #!/bin/bash
    sshpass -p 'some-password' ssh pi@192.168.1.111 'service zerotier-one start'

Running init start/restart interactively works fine, and control is returned to the command prompt. Running the zerotier init start/restart script non-interactively seems to hang. It just prints out "Starting ZeroTier One..." and never returns.

**Comment by adamierymenko** [comment]
Probably some kind of console/tty thing... is this a SysV-init based system or a systemd based system?

**Comment by naasking** [comment]
It's Rasbian Wheezy, which hasn't yet switched to systemd, so it still uses the standard Debian setup.

**Comment by bonki** [comment]
Shouldn't the initscript complain about you not invoking it as `root` (since you're `ssh`-ing in as user `pi`)?

Does the same happen without the use of `sshpass`?

What happens when you run `ssh -ttt [...]` instead?

**Comment by adamierymenko** [comment]
Ahh... didn't see the part about no sudo -- this might not be a bug at all. I'm not sure init will work this way.

I know with pssh you have to cause it to pass -t through to ssh to do things like this, since a tty must be created. I had to figure this out recently to pssh 'service docker start' on a bunch of test nodes.

Closing since I think this is a SysV init limitation, not a ZeroTier bug.

**Comment by naasking** [comment]
@bonki The issue you note was a failure of copy-paste. My actual restart scripts use sudo and the issue is as I described. I can amend the top post to clarify if you think that's an issue going forward.

Passing "-t" directly to ssh does solve the problem, so I'm satisfied with that as a workaround if you don't think this represents a deeper issue that needs addressing.

**Comment by naasking** [comment]
Just FYI, the final solution works for the one-liner, but not as part of a larger script:

    #!/bin/bash
    ZT=zerotier-one_1.1.2_armhf.deb
    sshpass -p 'some-password' ssh -t pi@192.168.1.111 <<ENDSSH
    wget --no-check-certificate https://download.zerotier.com/dist/$ZT
    sudo dpkg --install $ZT
    sudo service zerotier-one restart
    ENDSSH

Script hangs on the zerotier-one restart. So I can't execute this script in a loop to upgrade a set of devices, for instance.

**Comment by naasking** [comment]
The following script works as expected to run commands using a separate script file that's passed in:
```
#!/bin/bash

if [ "$1" == "" ]
then
  echo "Usage: $0 command"
  exit 1
fi
sshpass -p 'some-password' ssh -q -t pi@192.168.1.111 "$( cat $1 )"
```
If the script file passsed in contains "sudo service zerotier-one restart", then this actually works if you're looping over a set of devices.

**Comment by Fizzadar** [comment]
I'm also seeing this issue - on any SysVInit system - the init script simply hangs at the end.

**Comment by adamierymenko** [comment]
Hmm... does adding `disown` to the front of the command help?

**Comment by adamierymenko** [comment]
Seems strange that this is still happening because we totally reworked the init script in 1.1.6.

**Comment by Fizzadar** [comment]
@adamierymenko it now seems to be working as expected - we were running `1.1.6` so that explains it, thanks!
