### ISSUE TITLE
Review path ranking to avoid using tunnels in preference to direct routes if a direct route exists

### ISSUE THREAD

**Issue by surfnet-niels** [zerotier/ZeroTierOne#247]
I have my openvpn setup so that all my data gets routed trough the VPN.
If I now start Zerotier, my clients external IP is the endpoint of the VPN

If I now try to use SCP to move some files for my client to a 'server' which is directly linked to the Zerotier vLAN, I note the SCP connection starts stalling.

Although I cannot reproduce the proposed solutions, this is reported as being a MTU problem commonly. As soon as I drop the VPN, coping with ZT using SCP works just fine.

**Comment by adamierymenko** [comment]
What's the MTU on the OpenVPN tun device?

**Comment by adamierymenko** [comment]
ZeroTier is very aggressive about finding ways to communicate, so if you have VPN links up it will try to use them. If they have small MTUs though packets should fragment in worst-case scenario.

**Comment by surfnet-niels** [comment]
Loopback UP LOOPBACK RUNNING  MTU:65536  Metric:1
Tun0        UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1
Wlan1      UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
ZT0          UP BROADCAST RUNNING MULTICAST  MTU:2800  Metric:1
ZT2          UP BROADCAST RUNNING MULTICAST  MTU:1492  Metric:1

Problems are when accessing ZT2 vlan

**Comment by surfnet-niels** [comment]
ZT0 MTU seems a bit weird also I guess..

**Comment by surfnet-niels** [comment]
ZT over VPN is a good thing I think as that will help avoiding NAT issues.

**Comment by surfnet-niels** [comment]
Confirming the MTU issue: when I lower the MTU on ZT2 to 1300 the issues no longer exists, regardless if underlying VPN is in place.

**Comment by adamierymenko** [comment]
That's odd... tun0 has a 1500 MTU, which is generally the default and no different from wlan1.

Can you send large pings over the OpenVPN interface e.g. "ping -s 1492 (something across tun0)"?

**Comment by adamierymenko** [comment]
Can you post a full list of IP addresses and netmasks on this system? I'm wondering if maybe there is some sort of conflict. I just remembered that we hypothesized MTU as a cause but it may not be. It might be some sort of routing conflict.

Right now ZeroTier does not handle such conflicts, and joining a ZT network that has overlapping numbering with another network you're on can cause various strange things to happen: route "flapping," one of the networks not working, certain addresses not working, etc. We've considered either warning the user, refusing to init conflicting IPs, or implementing some kind of on-demand NAT. This is obviously only a problem for IPv4.

**Comment by surfnet-niels** [comment]
Well we do not actually have NAT here, only 'real' IPs so it is unlikely that ip range will overlap with ZT subnets I think.

**Comment by surfnet-niels** [comment]
Large pings work with no problem:
niels@Einstein:~$ route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         129-utr.vpn.sur 128.0.0.0       UG    0      0        0 tun0
default         surroute.surfne 0.0.0.0         UG    0      0        0 eth1
10.147.20.0     *               255.255.255.0   U     0      0        0 zt0
128.0.0.0       129-utr.vpn.sur 128.0.0.0       UG    0      0        0 tun0
survpn.surfnet. surroute.surfne 255.255.255.255 UGH   0      0        0 eth1
192.87.118.0    *               255.255.255.0   U     1      0        0 eth1
192.168.192.0   *               255.255.255.0   U     0      0        0 zt2
194.171.172.0   *               255.255.252.0   U     9      0        0 wlan1
195.169.126.128 *               255.255.255.128 U     0      0        0 tun0

traceroute info2.surfnet.nl
niels@Einstein:~$ traceroute info2.surfnet.nl
traceroute to info2.surfnet.nl (145.100.185.184), 30 hops max, 60 byte packets
 1  129-utr.vpn.surf.nl (195.169.126.129)  2.674 ms  2.688 ms  2.715 ms
 2  surroute.surfnet.nl (192.87.108.1)  3.929 ms  3.947 ms  3.962 ms
 3  xe6-1-3.2192.jnr01.asd002a.surf.net (145.145.17.13)  15.381 ms  15.428 ms  15.460 ms
traffic to info2.surfnet.nl is pushed over tun0

niels@Einstein:~$ ping -s 1492 info2.surfnet.nl
PING info2.surfnet.nl (145.100.185.184) 1492(1520) bytes of data.
1500 bytes from info2.surfnet.nl (145.100.185.184): icmp_seq=1 ttl=60 time=6.81 ms
1500 bytes from info2.surfnet.nl (145.100.185.184): icmp_seq=2 ttl=60 time=7.17 ms

**Comment by surfnet-niels** [comment]
Indeed delivering v4 subnets that are the same as the local network is trouble waiting to happen. I think an OpenVPN tunnel terminates as soon as this is detected, also it will of cause have issue with finding the default GW.
I would think providing some warning would indeed be a good idea, especially for the GUI versions of the client.

**Comment by adamierymenko** [comment]
I suspect that the fundamental problem here is that it has a global IP address, so it doesn't *need* to go through the OpenVPN tunnel. You don't have NAT.

Going to retitle this, since I think a policy change in terms of route ordering might be the real solution.

**Comment by adamierymenko** [comment]
New title means this:

If I'm talking to peer X and X reports my external address as class/scope "global," then I should favor global paths above all when talking to X. That way if I have a real public IP (no NAT) but also have some tunnel that can reach X, I will go direct using my global IP if possible.

Have to think through the implications with regard to the same network problem though... make sure that we still prefer local addressing over global addressing to avoid using a NAT hairpin in preference to the local LAN.

Maybe a better option is to look at our local addresses and if we have a global one, use that. Actually, going to retitle again. :)

**Comment by surfnet-niels** [comment]
Sounds good. And I can certainly live with my current workaround of lowering the MTU manually

**Comment by adamierymenko** [comment]
In re this: I don't think it's possible (or at least easy) to over-complicate the path selection logic for this, and I don't want to potentially damage general use cases for an edge case. But I did add the above commit.

I can't think of a situation where you'd want ZeroTier to use a tun/tap device as a route to another peer. Can you? These are likely other VPN links, and it would be better to use ZeroTier's own best-route-finding logic vs. going over some other VPN... both for reliability and possible recursion reasons.

**Comment by surfnet-niels** [comment]
The only thing I can think of is a scenario where there is NAT and I do not want the central ZT to be used to pass traffic through (perhaps my understanding of how this works in the NAT case is wrong by the way). In that case a VPN could be used to move out of the NAT and then route ZT trough that. Also in case the other VPN is the default route, your would need to have ZT route some subnets outside of the VPN. I could imagine some might consider that a security issue

**Comment by heri16** [comment]
The current path selection logic is very unresponsive to changes in connectivity of underlying network. Could you explain the logic and how long is it expected to failover?
