### ISSUE TITLE
ZeroTier randomly goes offline after WAN IP changes

### ISSUE THREAD

**Issue by electricduck** [zerotier/ZeroTierOne#248]
I've noticed the past few days ZeroTier will show and "Offline" status after my "outside" WAN IP changes. It also sometimes affects the VMs running on the same system (each using seperate ZeroTier clients), and causes them to go offline. Weirdly, I am able to ping the peers. Restarting the ZeroTier service also has no effect.

The only way round this problem I've found is to restart the entire OS.

Host OS is running **ZeroTier 1.0.5** on Windows 10.0.10586. VMs are running a mix of OSes, all using ZeroTier 1.0.5.

**Comment by adamierymenko** [comment]
It's typical for changing WAN IPs to cause any form of connectivity to have to reset or renegotiate, but the symptoms you describe are very strange. Restarting the service causes it to renegotiate everything. I fail to see how restarting the OS could have any effect that differs from that, but apparently it does.

Is this Windows system acting as some sort of NAT router or firewall itself and does it actually hold the WAN IP? If so maybe it's not resetting its external idea of its own IP, making it impossible for it to communicate.

**Comment by electricduck** [comment]
Hm, strange. After a few hours it suddenly connected back online. Windows doesn't have its firewall enabled for any networks. The VMs running on Hyper-V are using an "External Network Switch", using a subdivided VLAN, instead of using the host OS as a NAT.

Does ZeroTier create any logs anywhere? Couldn't find any in the obvious locations.

**Comment by adamierymenko** [comment]
It's possible to build ZeroTier with ZT_TRACE defined in which case it will log a lot, but the main build doesn't log much at all.

It is possible to query its state. On Windows this is a bit harder than on Linux or Mac, but can be done from the command line. This works on Windows 7, 8, and 10 from an administrator-access command line (right click on command, launch as administrator):

    cd \ProgramData\ZeroTier\One
    .\zerotier-one.exe -q help

The 'listpeers' command is useful for diagnostics.
