### ISSUE TITLE
Changing IP netmask on an existing network causes IP address to vanish on Macs

### ISSUE THREAD

**Issue by adamierymenko** [zerotier/ZeroTierOne#249]
:beetle: is buggy

Linux seems fine. Will have to try Windows.

**Comment by heri16** [comment]
I can verify this does happen on Mac OS X (just haven't reported in this big the last time I saw it).

**Comment by adamierymenko** [comment]
Quick fix:

    sudo launchctl unload /Library/LaunchDaemons/com.zerotier.one.plist
    sudo launchctl load /Library/LaunchDaemons/com.zerotier.one.plist

**Comment by adamierymenko** [comment]
Closing since this is confirmed fixed in dev (will be in 1.1.2)
