### ISSUE TITLE
"Managed"-mode fails to set IP-address(es)/route

### ISSUE THREAD

**Issue by bonki** [zerotier/ZeroTierOne#253]
I compiled `v1.1.0` locally and am having troubles with Managed-mode resulting in no IPv4/IPv6 being set and no route being created.

    # zerotier-cli listnetworks

successfully lists the assigned IPv4/IPv6-addresses as per the controller configuration but the network interface never gets configured accordingly. However, if I manually set an IP-address everything works.

I don't see `zerotier-one` logging anything anywhere, how can I properly debug this problem?

**Comment by bonki** [comment]
Found `ZT_TRACE`, will recompile and investigate.

**Comment by adamierymenko** [comment]
This is now fixed in -dev -- turns out it's a problem with some distros putting the ip command elsewhere. Eventually we should probably do it programmatically and ditch exec() entirely. Thanks to Adrian Frühwirth!
