### ISSUE TITLE
Service Error (identity.secret not being written)

### ISSUE THREAD

**Issue by softwarez** [zerotier/ZeroTierOne#255]
Hello, after being unable to start ZeroTier I've checked the event logs to see why.
Turns out my event page was filled with service errors. 

They all said: "ZeroTier node encountered an unrecoverable error: could not write identity.secret (home path not writable?) (restarting in 5 seconds)"

Any suggestions on how to fix this? Thank you!

**Comment by adamierymenko** [comment]
What OS is this?

**Comment by softwarez** [comment]
This is Windows 7 Pro x64

**Comment by adamierymenko** [comment]
That's a strange error... it typically would indicate that the destination is not writable. Did you install from the regular MSI installer?

**Comment by softwarez** [comment]
I've been using an application that makes a Offline game Online. Using what seems to be a portable version of the CLI version of ZeroTier. Version 0.9.4.

**Comment by adamierymenko** [comment]
That's a very, very old version, and typically we can only provide support for Windows MSI installs since manually installing on Windows is somewhat complex.

You can get the latest here: https://www.zerotier.com/download.shtml
