### ISSUE TITLE
ZeroTier window larger than screen on 13" MacBook

### ISSUE THREAD

**Issue by Caerostris** [zerotier/ZeroTierOne#257]
I've just upgraded ZeroTier on OSX to the latest version.
It was built from source and installed using `make mac-dist-pkg`.
Unfortunately, the installation changed the old UI.
The new vertical layout is larger than my screen, and there is no way to resize the window.
Should be an easy fix.

System:
OSX El Capitan Version 10.11.1 (15B42)
MacBook Pro (Retina, 13-inch, Mid 2014)
Display: 13.3-inch (2560 x 1600)

**Comment by adamierymenko** [comment]
Yeah, seems the resize capability vanished too. Will fix in 1.1.2.

**Comment by adamierymenko** [comment]
1.1.2 is on the docks, but I wanted to add that *zerotier-cli* can be used from the terminal as a workaround in the short term.
