### ISSUE TITLE
ARMv7 NEON Salsa20 (?)

### ISSUE THREAD

**Issue by adamierymenko** [zerotier/ZeroTierOne#263]
See: https://github.com/JoshuaKolden/libgcrypt/blob/master/cipher/salsa20-armv7-neon.S

Apparently takes Salsa20 on the Pi 2 from about 40mb/sec to 150-200mb/sec. Of course both are faster than 100mbps Ethernet and/or WiFi so maybe it doesn't really matter much in practice. But on phones I could see an ARM NEON crypto core reducing battery use so it might be good there. Could be a compile option.

**Comment by heri16** [comment]
NEON everywhere would be really great. :+1:

**Comment by deltaindiatango** [comment]
I see ~200 megabit per sec on an Allwinner A20, less than half of what I get via iperf on physical interfaces across the same machines.

It appears like the Salsa20 class is pretty straight forward, and currently implements SSE which is selectively compiled via ifdef.

The implementation linked by OP is GPLv2+ licensed, anyone know if a PR adding the ASM implementation along with mods to the CPP (ifdefs for NEON) would be accepted?

**Comment by adamierymenko** [comment]
Decided to knock this one out. In `dev`

**Comment by adamierymenko** [comment]
Almost 2X speedup on a Raspberry Pi 3.
