### ISSUE TITLE
website down

### ISSUE THREAD

**Issue by maci0** [zerotier/ZeroTierOne#267]
As of today I can't reach the zerotier.com website anymore
my.zerotier.com still works tho

**Comment by maci0** [comment]
ok, seems to be an issue with your ssl cert

```
Secure Connection Failed

The connection to the server was reset while the page was loading.

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
```

**Comment by Caerostris** [comment]
Both https://zerotier.com and https://my.zerotier.com work fine for me, on Firefox & Safari / OSX.

**Comment by maci0** [comment]
working again here..
strange

**Comment by adamierymenko** [comment]
Closing but we are monitoring the site... we just pushed out two fixes so that may hopefully fix things.

Note that our cert is newer and SHA-256 and that might cause issues if you try to access from a very old browser.
