### ISSUE TITLE
Bring back monitoring of local interfaces and reset on local IP change

### ISSUE THREAD

**Issue by adamierymenko** [zerotier/ZeroTierOne#269]
ZeroTier once monitored local interfaces to detect network changes. Now it does so empirically based on a special extra payload in HELLO and OK(HELLO).

It might make sense to bring back the former method and *also* do that, since it will detect changes the latter method might not.

In re: comments to closed issue #180

**Comment by heri16** [comment]
Agreed. The BGP Dead Peer Detection Algorithm should be considered also.

**Comment by adamierymenko** [comment]
Closing since this duplicates discussion elsewhere and in 1.1.3 (current dev) there's a greatly improved dead path detection algorithm that does a lot better than just pings and ping timeouts.
