### ISSUE TITLE
Long-duration IPv4 ARP caching

### ISSUE THREAD

**Issue by heri16** [zerotier/ZeroTierOne#276]
Initially concerned that ARP problems within my zerotier network are affecting connectivity, and our recent troubleshooting rounds proved that our concerns were indeed true. Simply adding static ARP cache (via a netsh-neighbors ui wrapper) seem to have solved much of our typical connectivity problems with ZeroTier that users were having on Windows machines.

An easy to use GUI to freeze ARP records would help resolve issues for a significant amount of users having problems with multicastLimit 32 causing erratic bandwidth and ARP miss-rates due to recipient randomisation algorithm. Would also help reduce battery life on mobile devices significantly, and rule out a slew of connectivity issues (and corner cases), if the user could freeze the ARP cache like seen here: http://www.irongeek.com/i.php?page=security/arpfreeze-static-arp-poisoning

It is a small amount of UI that would go a long way in making zerotier feel more reliable to the end-user. Source code is provided with the link above. Related: #275

**Comment by adamierymenko** [comment]
I could see this possibly being a network-level option to enable long-term ARP caching, with the caveat that this means that if you reassign an IP address your reassignment might take a long time to become effective.

The ultimate solution is IPv6 which allows this problem to be elegantly and completely eliminated.

**Comment by heri16** [comment]
Should caching be done in the OS or Zerotier? WHat are the Pros and Cons of each option? This would be a good discussion to have.

**Comment by adamierymenko** [comment]
OSes already do cache ARP, but usually not for long. Usually the TTL is 60-120 seconds, sometimes shorter.

**Comment by heri16** [comment]
For windows vista (and above) it is a short 30 seconds.

In the scenario that zerotier does the long-term caching, and we reassign an IP address, that means the IP address is still mapped to the old MAC address inside the zerotier long-duration cache on some nodes.

When these nodes (with outdated records) send any handshake packet to the old MAC address, the zerotier on the old MAC address could reply with a special VERB message such that the outdated records on the long-duration cache would be cleared on those nodes. This assumes that zerotier on the old MAC address has received the new IP address from the network controller, and actively refuses to reply to old ip address.

However, we still need to look into the corner cases like bridging.

**Comment by adamierymenko** [comment]
We could implement a smarter ARP cache that caches ARP records for a long time but that also periodically re-verifies them. This is not particularly hard. We already have an ARP cache implemented in Arp.cpp/hpp for use on mobile devices and embedded, so that could be used as a base.

This could definitely be added as a per-network configurable option. Might improve performance too. I'm not sure why OSes don't do it this way, since it's rather easy. Of course maybe Linux does. As a general rule everything network-related on Windows is either horribly broken or at least one generation behind all other OSes.

**Comment by heri16** [comment]
Yeah, I think this will be a great addition, since I recently discovered many agent-less network inventory software like Spiceworks which does network discovery refuse to work on Zerotier, likely due to ARP issues. Some parts of Windows receive very little love and attention. Some of the current networking technology in Windows 10 is still based on Windows Vista, for example the DNS AAAA-lookup behavior: https://technet.microsoft.com/library/bb727035.aspx .
