### ISSUE TITLE
Windows 10 64bit, lots of cpu usage when network was down, and lots of memory usage when the network came back

### ISSUE THREAD

**Issue by kangjianbin** [zerotier/ZeroTierOne#277]
Hi, I found ZeroTier wasted too many CPU when network was down (> 30%) and after the network came back again, it allocated memory more than 1.2GB.
Platform: Windows 10 64bit

Reproduce:
1. Use wifi as the network connection
2. close Wifi. The cpu usage of ZeroTier was above 30% in 'Task manager'
3. Wait for 10 seconds
4. Re-open wifi. Now ZeroTier allocated more than 1.2GB memory and system hang.

**Comment by adamierymenko** [comment]
Will investigate. Sounds like some sort of loop attempting to establish connectivity on a non-existent connection.

**Comment by adamierymenko** [comment]
Tried today and could not reproduce... will leave open for now.

**Comment by adamierymenko** [comment]
Does this box have HyperV on it or is it a HyperV guest?

**Comment by kangjianbin** [comment]
No. It has virtualbox(which installs a Host-Only Ethernet adapter) and winpcap.

**Comment by adamierymenko** [comment]
Closing since #308 is almost certainly a duplicate...
