### ISSUE TITLE
UDP issues

### ISSUE THREAD

**Issue by faddat** [zerotier/ZeroTierOne#279]
No firewall, but having UDP issues running consul.  Happy to provide all ofthe logs, etc that you may need.  Thank you!

**Comment by adamierymenko** [comment]
Are these UDP issues over a virtual network? Is the network able to carry normal traffic just fine and what does ping show?

**Comment by faddat** [comment]
Yes, the difficuties were over a ZeroTier virtual network.  Let you know
what ping shows when I open those VMs up again, hopefully later today :).

Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +84 167 789 6421

**Comment by adamierymenko** [comment]
Pull down 1.1.2 first, there are some improvements that may help.

**Comment by faddat** [comment]
:), thanks for the heads up, I'll do that and let you know if I'm still getting funny messages from nomad & consul
