### ISSUE TITLE
Readme seems a little out of date for Mac

### ISSUE THREAD

**Issue by maxogden** [zerotier/ZeroTierOne#280]
I installed using the mac .pkg from https://www.zerotier.com/download.shtml, and then consulted [the readme on github](https://github.com/zerotier/ZeroTierOne/tree/6f16f4443833917f9c70de924c818431b1ec64da) for usage.

The readme references both `zerotier-one` and `zerotier-cli`. However, the mac installer only symlinked `zerotier-cli` into my path:

```
🐈  ls -alh $(which zerotier-cli)
lrwxr-xr-x  1 root  admin    54B Dec 21 10:38 /usr/local/bin//zerotier-cli -> /Library/Application Support/ZeroTier/One/zerotier-one
```

What's the difference between `zerotier-one` and `zerotier-cli`?

It says "On Linux and BSD you can start the service with..." but then later it says "Running ZeroTier One on a Mac is the same, but OSX requires a kernel extension". But I tried to start a zerotier service (`sudo ./zerotier-one -d`) and it just showed me the CLI usage so I'm guessing that means the `zerotier-one` CLI is different on mac.

Running `zerotier-cli join` resulted in a `zerotier-cli: missing authentication token and authtoken.secret not found (or readable) in /Library/Application Support/ZeroTier/One` error. When I use `sudo` it works. However, after an `authtoken.secret` is created, I no longer need `sudo`. This makes sense, as the `~/Library` folder requires `sudo` to modify. Wouldn't it make more sense to put the secret in a non-sudo folder? IIRC signed TUN/TAP code doesn't require sudo (or am I wrong)?

Lastly, it says "Running ZeroTier One on a Mac is the same, but OSX requires a kernel extension. ". Is this only necessary if you are building ZeroTier One for Mac from source? Did ZeroTier install a kernel extension when I installed it?

**Comment by adamierymenko** [comment]
It's a multiple-personality binary -- it runs as zerotier-cli or zerotier-one depending on argv[0]

The README instructions are really geared toward pulling and building the source, not installing the binary .pkg. In the latter case the service is expected to be started by launchd and zerotier-cli is symlinked into /usr/local/bin to allow CLI use.

**Comment by adamierymenko** [comment]
Oh, and the kernel extension is in ext/bin/tap-mac -- move tap.kext into

    /Library/Application Support/ZeroTier/One

... and make sure it's owned by root:root (0:0).

The command line will require root unless you've run the GUI, which will install a copy of the auth token in your home folder the first time you run it (with auth).
