### ISSUE TITLE
How should new networks be configured? IPv4 or IPv6?

### ISSUE THREAD

**Issue by gradha** [zerotier/ZeroTierOne#282]
After reading https://www.zerotier.com/blog/?p=226 I feel a sudden ambition to protect kittens. Now I have a small four device network of zerotier devices, all OSX running latest versions. Given that all of these should be able to cope with IPv6, would it be better if I disabled IPv4 for all in the zero tier panel and change them to IPv6? As weird as it sounds, IPv6 seems to be unmanaged now and all devices are in the IPv4 zerotier managed section. Shouldn't that be the other way round?

Also, is preparation needed at each machine for the switch from IPv4 to iPv6 or just changing the setting in the zerotier panel is enough?

**Comment by adamierymenko** [comment]
Are you talking virtual or physical? For virtual it's entirely up to you, though we like IPv6 and the IPv6 numbering scheme we use lets you have more efficient connection setup. For physical networks we currently recommend IPv4/IPv6 dual-stack with a "full cone" or "port restricted cone" (but not symmetric) NAT for optimal performance (and preferably no IPv6 NAT).

**Comment by adamierymenko** [comment]
Not sure why V6 would be left unmanaged. Send the network ID (or e-mail it to contact@zerotier.com) and I can check it.

**Comment by gradha** [comment]
Network id ``8056c2e21c1043a7``.

**Comment by adamierymenko** [comment]
Yes, those are the current settings. They only affect addressing *within* the virtual network, not what physical network connections are used.
