### ISSUE TITLE
Inbound Multicast bug on Windows Driver

### ISSUE THREAD

**Issue by heri16** [zerotier/ZeroTierOne#285]
Windows zerotier interface can send multicast packets out into the zerotier network, but cannot receive multicast packets from anywhere. This was tested using tcpdump and wireshark to verify this behaviour on a new Zerotier private network (ID: e5cd7a9e1cdaa2a5). 

When multicast packets are sent, Linux and MacOS X zerotier nodes on the network would receive the multicast packets via the zerotier interface. However, none would be detected on other Windows nodes on the zerotier interface. Timing analysis suggests that encrypted packets containing the multicast packets are received on the Ethernet/Wi-Fi real-interface on Windows, (but these same packets disappear on its way to the virtual-interface).

This meant that a "ping -S \<zt-local-link ipv4> 224.0.0.1" from Windows node could be detected by Mac OS X and Linux nodes, but not by other Windows nodes. This breaks Bonjour/mDNS and LLMNR and all other multicast dependent technology.  Netbios is not affected as it uses broadcast, not multicast.

Here are other options that were tested:
- Windows ALL IPv6: "ping -S \<zt local-link ipv6> ff02::1"
- Windows LMNR IPv6: "ping -S \<zt local-link ipv6> ff02::1:3"
- Windows Bonjour IPv4: "ping -S \<zt local-link ipv4> 224.0.0.251"
- Windows LMNR IPv4: "ping -S \<zt local-link ipv4> 224.0.0.252"
- Mac OS X ALL IPv4: "ping -I \<zt local-link ipv4> 224.0.0.251"
- Mac OS X ALL IPv6: "ping6 ff02::1%zt1"

Multicast Address Reference: https://en.wikipedia.org/wiki/Multicast_address
To check multicast membership:
```
# Windows
netsh interface ipv4 show joins
netsh interface ipv6 show joins

# Mac OS X
netstat -g
```

Versions of ZeroTier tested to be affected by this bug:
- v1.1.2 on Windows 8, 8.1, and Windows 10
- v1.1.0 on Windows 8, 8.1, and Windows 10

(Windows 7 untested, but likely to be affected too.)

**Comment by heri16** [comment]
Can anyone else help verify that they are experiencing the same bug also?

**Comment by adamierymenko** [comment]
So far we are able to get and send multicasts on Windows.

I seem to recall some strangeness around multicasts on Windows and binding, and that this is a feature of the Windows TCP/IP stack. It was something like "multicast/broadcast to/from generic sockets bound to 0.0.0.0 or ::0 only make use of the primary interface". The primary interface would *not* be the ZeroTier virtual port but would be the Windows Ethernet or WiFi card-- whatever the default route is via.

**Comment by heri16** [comment]
Oh my... Have LMNR been tested on zerotier? Things like http://sharedrop.io don't work too.

**Comment by adamierymenko** [comment]
Hmm... will have to try again in more depth then. I'll try that specific app.
