### ISSUE TITLE
Linking ZeroTier to my own-hosted Controller

### ISSUE THREAD

**Issue by C1NEMA** [zerotier/ZeroTierOne#286]
Hello,

First of all. Thank you for ZeroTier itself. It solved many problems I had in the past and I'm just happy that I found it.

But I also got a little question:

I was able to host a Controller without any big problems but I would like to know how can I tell the ZeroTier Application (on my PC for example) to connect to my own Controller instead of the default ones?

Is there a place in the code where I have to change this (defining IPs)?

Thank you in advance.
Have a great new year 2016

Dominik

**Comment by adamierymenko** [comment]
You don't have to.

A network ID is the controller's address + a number identifying the network on the controller. So when you join this network it connects to your controller automatically.

You may be thinking of root servers, which are a different thing entirely. Controllers issue network certificates and configuration, while roots anchor the global network and permit instant connection setup and provide free relay fallback when direct p2p links can't be established. Right now roots are provided by ZeroTier and are kind of hard-coded into the app (see World). In the future we plan to offer some form of delegated or federated roots as an 'enterprise' feature so people can have their own root on site or in their own cloud.
