### ISSUE TITLE
Implement path MTU discovery for more efficient operation over low-MTU links

### ISSUE THREAD

**Issue by mhw** [zerotier/ZeroTierOne#287]
I've noticed that connections between machines on my home network and a machine at a different location are often bursty, in that running a command that produces a reasonable amount of output (`ps -ef` for example) will stall after the first few lines. Large file transfers will also exhibit similar behaviour.

After noticing https://github.com/zerotier/ZeroTierOne/issues/74 I thought I'd try tweaking the MTU setting on the zt0 interfaces at either end. If I drop the MTU to 1400 the problem remains, but dropping to an unscientific 1300 causes the bursty behaviour to stop: file transfers use the full bandwidth of the ADSL connection to the home network. The MTU of the ADSL connection is 1432, so I'm suspicious that larger packets are getting fragmented and lost somewhere, leading to the stalls I see.

I also noticed http://forums.whirlpool.net.au/archive/2160834 which makes me wonder whether something is going wrong with MTU discovery between zerotier and the Billion 7800N router that connects the home network to the ADSL line, assuming that zerotier would normally be expected to adjust MTU. How would I go about diagnosing what zerotier is doing?

**Comment by adamierymenko** [comment]
*1432*?!?!

What kind of protocol does your DSL use? That's a very low MTU and it probably is causing packet fragmentation. ZT currently assumes an MTU no lower than 1492 on WAN links. We haven't yet implemented PMTU detection/tuning but likely will at some point.

**Comment by adamierymenko** [comment]
1500 is "normal", while 1492 is common on PPPoE (PPP over Ethernet) links.

**Comment by adamierymenko** [comment]
Retitled this issue appropriately.

**Comment by mhw** [comment]
PPP over ATM, which is pretty much standard for ADSL connections in the UK. Talk Talk, the ISP I use and one of the larger ones, has 1432 as their default MTU: http://help2.talktalk.co.uk/what-mtu

**Comment by adamierymenko** [comment]
Good to know. I've never personally seen one that low. We'll try to bump this up in priority since this is likely found in other markets too.

**Comment by mhw** [comment]
Great; that would be useful. That said, shouldn't the effect of packet fragmentation just be reduced throughput rather than the long periods of no packets getting through at all that I'm seeing? I'm wondering if there's something else going wrong that the MTU issue is making visible.

**Comment by kraney** [comment]
Most TCP stacks do path MTU detection, which means that the TCP packets all have the 'don't fragment' bit set. They _want_ the oversized packet to get dropped and to get back an ICMP message indicating 'would fragment', which makes the TCP stack react by tweaking downwards the MTU to try and fit.

I'm not sure whether ZeroTier carries the DF flag over when it encapsulates and encrypts a packet. If it does, you're not really dealing with fragmentation per se. Your big delays are probably delays caused by path MTU detection followed by a retransmit. It might take mutliple retries to get all the way from 2800 down to 1432.
