### ISSUE TITLE
OSX after sleep loses routing for Zerotier network

### ISSUE THREAD

**Issue by dkruyt** [zerotier/ZeroTierOne#288]
When my laptop (OSX El Capitain) resumes one of my bridged Zerotier network, it comes up but without any routes on the ZT interface. So all traffic is then routed via default route instead the ZT interface.

I can fix it by leave/join again the zerotier network.

**Comment by adamierymenko** [comment]
What's your configuration? It sounds (bridging, default route) like you're doing something a little different from the normal simple p2p VPN use case with the Mac client.

**Comment by dkruyt** [comment]
At home I have an RaspBerry Pi running as my Zerotier bridge. And my Laptop is just joining the ZeroTier network at work. This works fine. When I come home and then my home network works fine to.

I let my laptop sleep then resume at works I dont have any routes on the zt interface. Has it some thing todo the ZeroTier thinks I am still in my home network?

**Comment by adamierymenko** [comment]
After your laptop sleeps and resumes, can you open a terminal and post the result of 'ifconfig'?

If this is something you don't want to post in a public forum e-mail it to adam.ierymenko@zerotier.com

**Comment by alax** [comment]
This is still an issue for me. ZeroTier will randomly stop passing traffic on OS X El Capitan after sleep/resume, although my routes look fine.

**Comment by adamierymenko** [comment]
I use El Capitan and never see this... can you provide some info about: routes, network environment(s) where you use your Mac, etc.?

Also next time it happens can you grab the output of:

    zerotier-cli listpeers
    zerotier-cli listnetworks
    ifconfig

??

**Comment by alax** [comment]
So it seems like, even after a reboot, ZeroTier traffic is still dead. I'll send you those details via email right now.

**Comment by alax** [comment]
Also, I've seen this happen on two different MacBook Pros over the last two days, so I don't think it's an isolated issue. I am trying to reproduce the issue now so I can get you some information, but repeatedly sleeping/resuming doesn't trigger it (yet).

**Comment by adamierymenko** [comment]
If you wait a while does it eventually work? If so how long?

**Comment by alax** [comment]
Nope, waited at least four hours last time, nothing helped. The only anomaly was that the hardware address of the host I was trying to connect to was missing from the routing table. ZeroTier reported that it was connected, interfaces looked good, etc.

**Comment by alax** [comment]
Looks like the issue was unrelated to ZeroTier. It was a faulty UPnP config on our router (EdgeRouter). Everything seems to be working now.
