### ISSUE TITLE
Implement Encrypt then MAC

### ISSUE THREAD

**Issue by heri16** [zerotier/ZeroTierOne#290]
http://blog.djm.net.au/2013/11/chacha20-and-poly1305-in-openssh.html
http://bxr.su/OpenBSD/usr.bin/ssh/cipher-chachapoly.c

**Comment by adamierymenko** [comment]
That's already how it works. It encrypts then MACs.

**Comment by adamierymenko** [comment]
MAC is computed with Poly1305 on the cipher text using the first 32 bytes of the Salsa20 key stream as the one time use Poly1305 key. This is the same construction used by NaCl and OpenSSH's implementation.
