### ISSUE TITLE
Running in SteamLink gets connection failed.

### ISSUE THREAD

**Issue by jackygurui** [zerotier/ZeroTierOne#293]
After built from source with the [Valve's SteamLink SDK](https://github.com/ValveSoftware/steamlink-sdk), and copied to my SteamLink. I always get connection failed errors. 
```
# ./zerotier-cli info
0 info connection failed
# ./zerotier-cli join 8056c2e21c000001
0 join connection failed
```
I have tried both dev and master branch and both gave the same error. Any ideas?

**Comment by adamierymenko** [comment]
Control of the local service is via local loopback HTTP to the ZeroTier port, usually 9993. It's possible to access the local API via 'curl' if you send the right auth header.

Does the Valve StreamLink SDK get in the way of this? Or does it prohibit it? If so it might require binding to a different address or some other mechanism for IPC to control the service in that environment.

What are you trying to accomplish here?

**Comment by adamierymenko** [comment]
BTW we now have a community section live: https://www.zerotier.com/community/

It's new and just getting started.

**Comment by jackygurui** [comment]
Thanks for getting back to me. 

I have reposted it to the [community](https://www.zerotier.com/community/topic/7/getting-zerotier-magic-works-in-steamlink) with updated information.

**Comment by adamierymenko** [comment]
Moved to community

**Comment by hzeroo** [comment]
Did you gusy ever made this to work? Community link is down and cannot find any information about this topic anywhere, so i guess not?
