### ISSUE TITLE
Unikernel (language specific) node implementations

### ISSUE THREAD

**Issue by asbjornenge** [zerotier/ZeroTierOne#294]
Hi! 

I've started thinking about how to connect a [runtime.js](http://runtimejs.org/) unikernel to a ZeroTier network. I think this would require a node (as in ZeroTier node) implementation in JavaScript, since I have no tun/tap device or any other way to run a standard ZeroTier node.

Am I correct in this assumtion? 

Would something similar to the [Android SDK](https://github.com/zerotier/ZeroTierOne/tree/master/java) implementation be the correct way to go about this?

As unikernels (and ZeroTier) grow in popularity, I think this might be something to consider having a good roadmap / guide for. With a little help perhaps I can pave some way here and contribute both a JavaScript implementation and some documentation around the process.

Related; is there some more detailed documentation around ZeroTier's technical aspects anywhere? Or is digging through the code the current best approach?

**Comment by adamierymenko** [comment]
You could in theory cross compile it with Emscripten into ASM.JS.

We've got a community, so maybe consider the general forum here: https://www.zerotier.com/community/

**Comment by asbjornenge** [comment]
@adamierymenko That is a super cool idea! I'll give that a try :tada: I could also compile it as part of a custom runtime.js build I guess. I'll close this issue and rather report back on the forum :wave:

**Comment by adamierymenko** [comment]
Closing since this should go over to community... questions are better there because they are searchable and become a knowledge base. This is more for TODOs and bugs.
