### ISSUE TITLE
Allow DHCP to assign fixed IP addresses

### ISSUE THREAD

**Issue by eXeC64** [zerotier/ZeroTierOne#295]
I'd like to manually configure the ip addresses of my zero-tier clients, but be able to do it centrally. Ideally this would mean setting the network to auto ipv4 and the controller assigning specific peers specific ip addresses, and other peers being assigned addresses from a range.

**Comment by adamierymenko** [comment]
You can do this already. Just edit the assigned IP address. It will 'stick.'

**Comment by adamierymenko** [comment]
Be sure to save after edit. Some people get confused about this in the current UI.
