### ISSUE TITLE
Crash: "Bus Error" on FreeBSD ARM

### ISSUE THREAD

**Issue by Caerostris** [zerotier/ZeroTierOne#297]
I'm trying to get ZeroTier to run on a Raspberry Pi 2 and / or a BeagleBone Black running FreeBSD.
On both systems, ZeroTierOne starts sucessfully, and can configure the `zt<id>` network interface with an IP address.

However, SSH'ing into the box via the new ZeroTier IP fails (SSH just says 'operation timed out').
After a ~14 seconds of running, the ZeroTierOne daemon crashes with the message `Bus error (core dumped)`
This happens on the Raspberry Pi 2 running FreeBSD 11, as well as the BeagleBone Black running FreeBSD 10.2.
ZT1 runs fine on my Raspberry Pi 1 running Raspbian.

**Comment by glimberg** [comment]
@adamierymenko I wonder if this is another type punning issue.  Bus error is what we were getting on Android hardware.

**Comment by adamierymenko** [comment]
Maybe. Are you able to build in debug mode and gdb or lldb it?

**Comment by Caerostris** [comment]
Yup.

    make ZT_DEBUG=1
    ./zerotier-one
    # wait till it crashes
    gdb zerotier-one zerotier-one.core

Is showing the following:

    #0  0x00056c08 in ZeroTier::InetAddress::set (this=0xbffdbf20, ipBytes=0x20d95027, ipLen=4, port=9993) at node/InetAddress.cpp:131
    131			reinterpret_cast<struct sockaddr_in *>(this)->sin_addr.s_addr = *(reinterpret_cast<const uint32_t *>(ipBytes));

**Comment by adamierymenko** [comment]
:+1:

Will fix soon.

**Comment by adamierymenko** [comment]
Try the dev branch -- should be fixed.

**Comment by Caerostris** [comment]
Seems fixed :+1:
Thanks!
