### ISSUE TITLE
ARM port does not seem to travel through my (non firewalling) NAT

### ISSUE THREAD

**Issue by mcondarelli** [zerotier/ZeroTierOne#300]
I am trying to port zerotier-one to a custom ARM board.
Unfortunately it works only partly.
I can join my own private test net (or the default public one, for that matter) with no apparent error.
It appears in my.zerotier.com page.
I when I "Allow" it a new IP address is generated and I can see it in my target (via ipconfig).
**But** "Most Recent Real IP" remains unknown ("--") and I cannot ping/ssh the new IP **from outside**.

I have several clients both internal to my LAN and external (win7, linux debian, win10) using the standard binary distribution. They communicate with no problem.

Clients in my local LAN are able to communicate with Target (mostly, sometimes I get long delays).
Clients outside my local LAN cannot contact Target (unsurprisingly, since "Real IP" is unknown!).

I tried compiling with debug activated (no change in behavior), but I don't understand if something is actually wrong in the messages.

Note I have a self-compiled kernel/RootFS, so something might be missing (e.g.: I do **not** have support for IPv6 compiled in), but I do not know what would be relevant.

How can I debug this stuff?
Should I post (or pastebin) the debug trace?

**Comment by adamierymenko** [comment]
What OS does this run and do you have any tooling available on the system such as tcpdump or iptables?

Also do you know what your edge router is and what its actual settings are?

**Comment by adamierymenko** [comment]
Is this you over at community? If so we should move there: https://www.zerotier.com/community/topic/9/porting-to-embedded-arm

Like to keep Q&A there so it's searchable/indexable.
