### ISSUE TITLE
allow leaving all networks

### ISSUE THREAD

**Issue by surfnet-niels** [zerotier/ZeroTierOne#301]
The current CLI client only allows to leave named networks as per 
"zerotier-cli leave foobar"

When I want to use a deployment script to reset the ZT network this is rather cumbersome, as I now first need to get a list of all networks, handle that output with e.g. bash/perl/python and then issue multiple leave commands

Please allow some generic way for leaving all networks at once, e.g. "zerotier-cli leave all"

**Comment by janjaapbos** [comment]
For this particular use case you might just stop the zerotier service, and do rm -f /var/lib/zerotier-one/networks.d/*

Otherwise you have to keep track of what is targeted by "all". For instance, may new networks be joined during this operation?

**Comment by surfnet-niels** [comment]
Thanks for the suggestion.
For my use case removing the networks like described would indeed work, though it seems a bit crude ;)
