### ISSUE TITLE
[Feature request] A version check function would be nice. Auto update is a bonus. 

### ISSUE THREAD

**Issue by jackygurui** [zerotier/ZeroTierOne#303]
It would be nice to have a notice of some sort to notify the release of a new version. If it can have an option to auto update itself would be better.

**Comment by adamierymenko** [comment]
We're working on this.

Mac and Windows versions already have a good secure auto-update mechanism but we've been gun-shy about using it, especially on Windows. There are many users who don't like random interruptions in connectivity. So far we've left it alone but kept it around in case we ever have a critical security vulnerability that we need to patch in the field ASAP. (We'd also mass e-mail in that case.)

For Linux the best thing to do would be to get us into the Linux repos, but that seems very hard to accomplish. They seem like closed clubs with esoteric undocumented requirements.

**Comment by adamierymenko** [comment]
Closing since (1) Mac and Windows have AA though we've been gun-shy about using it as mentioned above and (2) the right way to do this on Linux is with packages. We are currently working to get ZeroTier into Debian and RedHat/EPEL/Fedora distros.
