### ISSUE TITLE
Provide link to "latest" client

### ISSUE THREAD

**Issue by surfnet-niels** [zerotier/ZeroTierOne#304]
When installing/upgrading zerotier client, currenlty one must know what the latest version is as the links with version numbers are provided like so:
https://download.zerotier.com/dist/zerotier-one_1.1.4_amd64.deb
This means that each time a new version is released, I need to my current scripts break and I must update my install/update scripts manually.

Please provide a "simlink" to the latest version, so I can always point to the latest and greatest version without having to update my install/update scripts

**Comment by adamierymenko** [comment]
IMHO the real solution is to get this into distributions or set up our own apt and yum repos, but leaving it here for now.

**Comment by lewisl9029** [comment]
A [Chocolatey](https://chocolatey.org/) package for Windows would also be nice if possible.

**Comment by surfnet-niels** [comment]
+1 for repos in apt/yum
