### ISSUE TITLE
GPG signatures and hashes of downloadable binaries on the web

### ISSUE THREAD

**Issue by surfnet-niels** [zerotier/ZeroTierOne#305]
Zerotier is enabeling virtual lan access into devices that would otherwise be shielded. At least in my case, it is part of a security fabric, just like the firewalls, and other VPN-ish solutions.

It is therefore absolutely critical that I can trust the software that I install. As patr of that trust I need to verify if the file I download is actually not tampered and provided by Zerotier as intended. A common way for doing this is signing the package with e.g. an md5 hash which can be validated independently.

**Comment by adamierymenko** [comment]
The Mac and Windows binaries are signed as well as the installers, but you're right that GPG signatures on the web would be nice. We will try to do this with the next release.

**Comment by surfnet-niels** [comment]
Great!
