### ISSUE TITLE
SAML or OIDC login into ZeroTier Central / my.zerotier.com

### ISSUE THREAD

**Issue by surfnet-niels** [zerotier/ZeroTierOne#306]
I think this is on the list already, but I would really like to login with our company IDM/SSO solution. I suggest using SAML or OIDC for that.
I would be more then happy to provide test SAML IdPs or OIDC OPs if needed.

**Comment by adamierymenko** [comment]
Technically this is a ZeroTier Central issue but I'm leaving it here for now. We're currently in the midst of a refactor of Central so this is a good time. Please e-mail about test endpoints.

**Comment by adamierymenko** [comment]
Closing since this exists in the internal Central issue tracker.

**Comment by rokello1** [comment]
Any updates on this thread.
