### ISSUE TITLE
[Feature Request] Please support ARQ

### ISSUE THREAD

**Issue by sbilly** [zerotier/ZeroTierOne#307]
https://en.wikipedia.org/wiki/Automatic_repeat_request

and an C implement: https://github.com/skywind3000/kcp

**Comment by adamierymenko** [comment]
What would the purpose of this be and how would we support it per se?

**Comment by sbilly** [comment]
It improves network latency by using 20% ~ 50% network flow, especially for mobile.

Here is some benchmark testing result. https://github.com/libinzhangyuan/reliable_udp_bench_mark

**Comment by adamierymenko** [comment]
Closing since "support ARQ" doesn't really make sense. ZeroTier emulates layer 2 and relies upon inner L3 protocols like TCP to implement this kind of behavior. It does not itself guarantee packet delivery, and shouldn't. That would be out of scope.
