### ISSUE TITLE
segfault on alpine linux

### ISSUE THREAD

**Issue by Caerostris** [zerotier/ZeroTierOne#310]
I'm getting a segfault on alpine linux right after starting zerotier.
```node/Network.cpp:232 requesting netconf for network xxx from controller yyy```
```Segmentation fault```

gdb says it's in node/Switch.hpp line 198, TXQeueEntry.
I am running in VMWare, but as far as I can tell that should not make a difference...

**Comment by adamierymenko** [comment]
That should not make a difference, and that's an exceedingly strange place to get a segfault. Is this a clean build? (make clean / make)

**Comment by adamierymenko** [comment]
Also very strange because that code is very old. It hasn't changed significantly in a long time and it runs everywhere under lots of stress.

**Comment by Caerostris** [comment]
Yeah, I must have screwed something up about the build. make clean && make and now it works. Sorry about this, and thanks a lot!

**Comment by adamierymenko** [comment]
Yeah, the current build / makefile does not unfortunately handle dependencies in .hpp files well. If you updated and rebuilt without cleaning gremlins will fly out of your monitor.

**Comment by Caerostris** [comment]
That's probably what happened... I'm actually amazed by how portable ZT1 is! The only system I couldn't get it to run on so far was OpenBSD. And to be honest, something not compiling on OpenBSD doesn't come as a big surprise ;)

**Comment by adamierymenko** [comment]
It was written to "directly connect the world's devices" meaning everything: apps, mobile, desktop, server, etc. Portability was a goal from line one.

I played with OpenBSD a bit. It will need a fork of (or ifdefs in) BSDEthernetTap and a few other tweaks but it wouldn't be too bad. Just not something on our radar at the moment.
