### ISSUE TITLE
Terminology issue 

### ISSUE THREAD

**Issue by feliksik** [zerotier/ZeroTierOne#313]
We are working in Go so made a quick go-client for zerotier. It's work in progress, but I'm happy to inform you about it; https://gitlab.com/nerdalize/go-zerotier

It's not documented yet, but it's pretty straightforward if one reads the code. If you know of other projects that already do this, I'd be happy to know. Otherwise, I'd be happy to improve this project. 

A few questions: 
* we see the terms 'node', 'endpoint', 'member' used interchangable in the ZT context. Are they semantically equivalent? I'm confused trying to use the correct words
* how stable to you think the json format for e.g. 'zerotier-cli -j listnetworks' is? 
* I see the API is versioned. Obviously ZT is work in progress and being slowed down by backwards compatibility requirements can be annoying, but can you say something about how to deal with API version? Do you intend so support old API versions with you my.zerotier.com controller? Should the client specify the API versions it assumes?

**Comment by adamierymenko** [comment]
Question #1: A member is a node/endpoint that is approved on a network. Other than that, the rest are identical. Endpoint is probably the best to use but we've used device, node, and endpoint interchangeably.

Question #2: Fairly stable. New fields may be added but huge changes are unlikely.

Question #3: Same with the API-- we *want* to avoid breaking it if possible. We may break it if doing so brings about a substantial benefit but we'll try to tell people first.

**Comment by feliksik** [comment]
Thanks!
