### ISSUE TITLE
Instability of links after ROOT servers version up to 1.1.5

### ISSUE THREAD

**Issue by heri16** [zerotier/ZeroTierOne#315]
I am experiencing instability of links for the past 3 days, likely due to Global root server regression.

My setup that fails which used to work flawlessly:

PC A -> NAT router with UPnP -> Public IP on Internet Link at Site A -> Public IP on Internet Link at Site B -> NAT router -> NAT router -> PC B

Note: The NAT routers are likely symmetric.

**Comment by adamierymenko** [comment]
There's been no root server changes for quite some time. Did you update to -dev perchance or are you running 1.0.4?

**Comment by adamierymenko** [comment]
Closing as duplicate of #296
