### ISSUE TITLE
Use higher metrics by default in Linux and OS X

### ISSUE THREAD

**Issue by adamierymenko** [zerotier/ZeroTierOne#316]
Wired connections, if available, should be preferred.

**Comment by donald-tt** [comment]
Note that on my laptop (Debian Jessie), in the routing table:

Wireless links have a metric of 1024
Wired links have a metric of Zero

A Wifi link to the same subnet as the ZeroTier interface should be preferred.  I suggest setting the default route metric to >1024, and ideally configurable for people with overcomplicated networks.

**Comment by adamierymenko** [comment]
Good catch. Might default to something like 4096

**Comment by adamierymenko** [comment]
Closing since this overlaps with #320 and #178 work and will get done along with refactor of tun/tap implementation to support those.
