### ISSUE TITLE
Huge speed loss UDP/TCP in performance test

### ISSUE THREAD

**Issue by mbalcaen** [zerotier/ZeroTierOne#324]
I have a huge loss of speed when I do a performance test between two nodes with iperf.
When I do the test in TCP, than I have a speed of 11,6 MBytes/sec. With UDP the speed drops to a poor 0,13 MBytes/sec. 

I have two networks 192.168.20.0/24 and 192.168.80.0/24 that are connected and routed over a virtual 10.10.10.0/24 network.
If one of the clients in the network 20.0 want's to send a 300 MB file to another client at the 80.0 side, than I have a poor speed around 662 kB/sec.

Is this a problem of Zerotier or a problem with my network setup? I have a pfSense firewall where I alredy dit a port forward on 9993/udp and also I did configured this port to a NAT static port.

![schermafbeelding 2016-05-03 om 09 34 32](https://cloud.githubusercontent.com/assets/1210283/14977368/852f808c-1113-11e6-945f-4c2f9d100885.png)
![schermafbeelding 2016-05-03 om 09 40 32](https://cloud.githubusercontent.com/assets/1210283/14977369/85301632-1113-11e6-9672-1e8e9bde46ad.png)

Thx a lot for the feedback!!

**Comment by adamierymenko** [comment]
Seeing this kind of speed difference between TCP and UDP is puzzling. Do you know if iperf is implementing any rate control with UDP? If not and it's flooding UDP as fast as possible it could just be causing whole lot of UDP packet loss over the WAN.

Also -- on the ZeroTier endpoints can you 'listpeers' and see if there is a direct path to the other peer?

**Comment by adamierymenko** [comment]
We did some of our own testing here between two large DigitalOcean VMs and using iperf3 we weren't able to see this kind of variation. The results we got were slightly faster than OpenVPN with full compression/encryption enabled.

Right now disabling encryption and compression requires editing the code, but we did that too. It resulted in speeds within about 8% of 1gbps LAN wire speed.

**Comment by adamierymenko** [comment]
Apparently iperf3 is much more highly regarded than the original iperf:

http://www.exogeni.net/2014/06/lies-damn-lies-and-iperf-dataplane-network-tuning-in-exogeni-today/
