### ISSUE TITLE
DNS fails on Android Client

### ISSUE THREAD

**Issue by nsymms** [zerotier/ZeroTierOne#325]
I know this has yet to be reproduced and may only affect a few of us unlucky Android users, but I thought I'd open up an issue so we could track progress and testing if that's okay.

I'm testing this on a Samsung Galaxy S4 running stock Android 5.0.1.
When the ZT client is connected to a VPN Netowrk, any calls to DNS will fail immediately with "Host not found." No packets are sent anywhere, the call for name lookup simply returns the error. I tested this using iptables logging and other network monitoring tools including tcpdump.

Everything else appears to work fine. That is, any network activity initiated via an ip address has no issue. And I can even use nslookup to do DNS lookups manually, so the DNS packets are actually making it where they need to go.

Given the above, the problem would appear to be with the library calls that do name resolution. Somehow, when the ZT client is active, they are unable to open a connection and send data for DNS queries.

**Comment by dafyre** [comment]
So you can't browse any website at all when ZT is active?

**Comment by nsymms** [comment]
@dafyre that's correct. At least that used to be the behavior.

The new Android client (1.1.12 I think) never connects. It tries and appears to connect, but then crashes. I've tried lots of things, but no joy.

**Comment by adamierymenko** [comment]
What revision of Android are you using?

**Comment by adamierymenko** [comment]
We've been completely unable to duplicate the DNS issue as well. If you can give us the exact version and device we might actually go out and get one.

**Comment by nsymms** [comment]
I'm using a Samsung Galaxy S4, Android v5.0.1.

I've recently installed OpenVPN, which may be related to the ZT client crashing. Of course I made sure they weren't running at the same time.

OpenVPN works fine without issues.

**Comment by nsymms** [comment]
After about 4 rounds of "start ZT -> join network -> crash" it finally connected to the network and was stable. But the DNS issue still remains. This is with ZT client v1.1.12. Not sure of the build number of the android client itself.

**Comment by pelrun** [comment]
I'm seeing the DNS issue on Android here as well. Samsung Note 3, running 4.4.2.

I can definitely ping IP addresses everywhere (LAN, internet, VPN), but all DNS queries fail. If I do a DNS lookup in PingTools (which talks directly to the DNS server, rather than asking the OS to do it) then that also succeeds.

**Comment by adamierymenko** [comment]
We still can't reproduce this but I am leaving open... sigh...

**Comment by pelrun** [comment]
Did a quick search for "android vpn dns bug" and found this: https://github.com/schwabe/ics-openvpn/issues/345

So looks like a Samsung specific bug. There's an generic Android bug that affects pre-4.2 versions as well; may be a regression on Samsung's part.

**Comment by nsymms** [comment]
I came to the same conclusion about buggy Samsung Android as well. But OpenVPN eventually solved the problem in their client somehow, because OpenVPN works without issues on my Galaxy S4.

So @adamierymenko if you want to close this, that's fine with me. I never got around this on my Samsung, but ZT works well on my tablet, so I've been using that when I need the VPN.

I can only assume that people with later versions of Samsung's Android are not having any issues. And as Android marches on and all of us upgrade, this issue will die anyway.

**Comment by sk22** [comment]
same here. i'm using zerotier-dns (a dns server that maps the zerotier device names to dns entires) tho, so maybe android uses only zerotier's dns server and nothing else? (i'm getting a `DNS_PROBE_FINISHED_BAD_CONFIG` from chrome for every domain that's not defined by zerotier-dns)
