### ISSUE TITLE
Is there a way to force tcp only connections?

### ISSUE THREAD

**Issue by alxbob** [zerotier/ZeroTierOne#332]
I know it will be slower but is there a way?

**Comment by pandada8** [comment]
+1 also good for testing custom  TCP relay  status

alxbob <notifications@github.com>于2016年5月31日周二 22:54写道：

**Comment by adamierymenko** [comment]
I'm closing this because we plan on bringing TCP (HTTP actually) back to the core in some form in the future, since not all routers/gateways provide reliable UDP. So this is already backlog.

**Comment by sbilly** [comment]
[Reliable User Datagram Protocol](https://en.wikipedia.org/wiki/Reliable_User_Datagram_Protocol) for this case.
