### ISSUE TITLE
my.zerotier.com incorrectly shows members ONLINE

### ISSUE THREAD

**Issue by jdrews** [zerotier/ZeroTierOne#333]
In my.zerotier.com I have members shown as ONLINE however I know they should be shown as OFFLINE. 

To recreate follow these steps:
1. Create Network at my.zerotier.com
2. Add members and confirm my.zerotier.com shows members as ONLINE
3. On a member, use Leave button to leave network.
4. my.zerotier.com should show member as OFFLINE, however it still shows member as ONLINE

Note that I have left members offline for a week and they still show as ONLINE.

**Comment by jdrews** [comment]
Below is what I'm talking about. 
![screenshot_060516_021207_pm](https://cloud.githubusercontent.com/assets/172766/15807272/7bd71350-2b27-11e6-8b76-318087806987.jpg)

Further information: If I use "Display Filter" to show only Online nodes, all incorrectly ONLINE nodes disappear.

**Comment by whlspacedude** [comment]
I can confirm that what jdrews is seeing is also happening to my networks and that the display filter seems to mask the issue.

**Comment by nsymms** [comment]
I also see the same thing reported above. I'm using Chrome v50.

**Comment by adamierymenko** [comment]
Will take a look. Next web rev is coming soon.

Since the filter removes it it looks like a pure UI layer issue.

**Comment by adamierymenko** [comment]
Fixed.
