### ISSUE TITLE
Official download for Synology NAS?

### ISSUE THREAD

**Issue by dalanmiller** [zerotier/ZeroTierOne#337]
Saw this thread from awhile back - https://www.zerotier.com/community/topic/13/zerotier-and-synology-device.

Attempted to build on my own Synology but my DS215j needs a hacky way to install `ipkg` so I can get the proper tools for building from source AFAICT. 

Any solutions to this?

**Comment by keekerdc** [comment]
Just wanted to add a +1 here. I'm fully in love with my new Synology NAS unit, and a seamless zerotier integration would be incredible.

**Comment by adamierymenko** [comment]
This is done in 1.2.0 and shipping with new site rev!

**Comment by joseph-henry** [comment]
For anyone arriving here from a search engine, here's our NAS package repo: https://github.com/zerotier/ZeroTierNAS
