### ISSUE TITLE
Dockerize ARM cross-compile support for easier ARM builds without an actual Pi

### ISSUE THREAD

**Issue by Split7fire** [zerotier/ZeroTierOne#342]
Checked "build farm" but can not find anything related to arm-based linux distributions (i.e. raspbian), but in "Download" section there is Raspbian deb file. (outdated at the moment :D)
What is the "official" way to crossbuild zerotier for arm-based linux?

**Comment by adamierymenko** [comment]
We build on an actual Pi, but cross compiling is not out of the question. Just tried installing the compilers in our debian:stretch Docker image and they basically work but the build process would need some tweaks.

**Comment by adamierymenko** [comment]
http://hackaday.com/2016/02/03/code-craft-cross-compiling-for-the-raspberry-pi/

**Comment by adamierymenko** [comment]
Closing since we have a way to do this now.
