### ISSUE TITLE
Controller / authorizedMemberCount broken in 1.1.6?

### ISSUE THREAD

**Issue by pkpowell** [zerotier/ZeroTierOne#343]
Just upgraded some devices to 1.1.6 and noticed that 'authorizedMemberCount' always returns 0 for controller networks, no matter how many members are authorized. 
The connections are all up so I guess this is just a minor bug, or have things changed re authorizing?

**Comment by adamierymenko** [comment]
You are correct! Our UI does not use that field, but it's definitely broken. Will get fixed in dev.

**Comment by pkpowell** [comment]
awesome, thanks.
Fantastic project btw.

**Comment by adamierymenko** [comment]
Fixed in -dev
