### ISSUE TITLE
Document 1.1.6 changes to controller API and improve controller docs

### ISSUE THREAD

**Issue by fkooman** [zerotier/ZeroTierOne#344]
Hi,

I tried to add a network in 1.1.6, similar to how it worked in 1.1.4. It seems to work fine for IPv6 connectivity, but for IPv4 the nodes don't get any IP(v4) address.

```
$ curl -H "X-ZT1-Auth: tnkwysav58ya1khkxn6oyscc" http://localhost:9993/controller/network/ba4afcd82e7bd2be
{
	"nwid": "ba4afcd82e7bd2be",
	"controllerInstanceId": "5493f0e1360b54a6e5e1ddb2716670d6",
	"clock": 1467630474002,
	"name": "foo_new",
	"private": true,
	"enableBroadcast": true,
	"allowPassiveBridging": false,
	"v4AssignMode": "zt",
	"v6AssignMode": "rfc4193",
	"multicastLimit": 32,
	"creationTime": 1467629997713,
	"revision": 3,
	"memberRevisionCounter": 7,
	"authorizedMemberCount": 0,
	"relays": [],
	"routes": [],
	"ipAssignmentPools": [
		{"ipRangeStart":"10.197.230.0","ipRangeEnd":"10.197.230.127"}],
	"rules": [
	{
		"ruleNo": 10,
		"etherType": 2048,
		"action": "accept"
	},{
		"ruleNo": 20,
		"etherType": 2054,
		"action": "accept"
	},{
		"ruleNo": 30,
		"etherType": 34525,
		"action": "accept"
	}]
}
```

I tried to change the 1.1.4 `ipLocalRoutes` to `routes`, but that does not seem to help... is that a clue that there are no routes defined anymore for the IPv4 IP address assignment to clients not working?

**Comment by adamierymenko** [comment]
You need a route -- and we need to update the docs! :frown:

    "routes": { "target": "10.197.230.0/24",via: null }

via: null means route via local LAN. You can also route via **other things**.

We're still working on 1.1.6 release documentation, announcements, UI support, etc.
