### ISSUE TITLE
ZT iOS client only shows 9 digits of client ID

### ISSUE THREAD

**Issue by fkooman** [zerotier/ZeroTierOne#347]
It seems the iOS ZeroTier client only shows 9 digits instead of 10 for the client identifier.

**Comment by adamierymenko** [comment]
How big is your screen? Probably a formatting thing.

**Comment by glimberg** [comment]
It's likely not left padding the client ID with 0's.

**Comment by adamierymenko** [comment]
That would be it. We should fix along with rev'ing the core to 1.1.6.

**Comment by glimberg** [comment]
Will do

**Comment by fkooman** [comment]
There are two other small issues, not sure if I should open a new issue for them though, or if they should go somewhere else?

1. on a fresh install of ZT for iOS the identifier is not visible, you first have to join (any) network before the ID becomes visible in the UI, this is a bit confusing, it would be easier to show it immediately as in private network scenarios one has to be able to add the identifier before the client can join;
2. entering a network ID doesn't always work, the UI is a bit unresponsive when trying to select the box to enter the network ID;

By the way, I'm using an iPod touch A1574 running iOS 9.3.2

**Comment by adamierymenko** [comment]
Should be fixed... let me know otherwise.
