### ISSUE TITLE
Red Hat 6.7/6.8 yum repo

### ISSUE THREAD

**Issue by oneguynick** [zerotier/ZeroTierOne#349]
On a RHEL 6.7/6.8 machine the automation detection of the install script does not point to the correct repo. I have attempted to browse to the repo so that I can correct, but the NGINX config on install.zerotier.com does not allow.

**Comment by adamierymenko** [comment]
Here is a `find` on download.zerotier.com/htdocs/redhat:

`redhat/
redhat/fc
redhat/fc/22
redhat/fc/22/zerotier-one-1.1.6-0.1.fc22.i686.rpm
redhat/fc/22/repodata
redhat/fc/22/repodata/3c00f703f7a429c29001006b0b64ba68438e9fad0c61e4558e3bcf2f797415bf-filelists.xml.gz
redhat/fc/22/repodata/55427a0f6fd657cdbc6ffda277cb069f200f2abac69e13eb05e6c0047a03d06c-filelists.sqlite.bz2
redhat/fc/22/repodata/24e4f7359adb2216bfc53dd668fa221dd3565b9e618dd702ac7e14b4dcd7daeb-primary.sqlite.bz2
redhat/fc/22/repodata/212bba4d77010ea92fd4c8e2f30472b2f524613e97263b5256c9052bce1021a5-primary.sqlite.bz2
redhat/fc/22/repodata/1bdb2c3d2f15f42bd13b46b9a25210b7365875f29a3f1803ed6c47c71da22cfd-other.sqlite.bz2
redhat/fc/22/repodata/515c9717eeb6a01a68ffa9071c36d6062c3a302b74a51173a3834fcd68e64802-other.xml.gz
redhat/fc/22/repodata/b29d7611ccd12639d6ad7893ab76bb220a586048facab38f8d9cba2c9d78de57-primary.xml.gz
redhat/fc/22/repodata/repomd.xml
redhat/fc/22/repodata/574950c358db8caf5d954961eefc002d0d7ce85b82984d9e21af602e57a4a93e-primary.xml.gz
redhat/fc/22/repodata/6cbb9ec1967d35fb77f6ac6b1127c695e7b6bbdaa8158b4a1713facd6aea88a8-other.sqlite.bz2
redhat/fc/22/repodata/09a259d3cd76f7bb9c91417d3d1b3bbd7b0ad8318ded198ade346fabecf6294e-other.xml.gz
redhat/fc/22/repodata/6df205c87dff8601f3e04415daa07e48b4bbc432ce7a08459bd22af4e51a1566-filelists.xml.gz
redhat/fc/22/repodata/f7a7b474cc3fc2a4bf24c1f3886e642153d8a7b8a95de571b2e7455ef4f08382-filelists.sqlite.bz2
redhat/fc/22/zerotier-one-1.1.6-0.1.fc22.x86_64.rpm
redhat/fc/22/zerotier-one-1.1.6-0.1.fc22.src.rpm
redhat/el
redhat/el/7
redhat/el/7/zerotier-one-1.1.6-0.1.el7.centos.x86_64.rpm
redhat/el/7/zerotier-one-1.1.6-0.1.el7.centos.i686.rpm
redhat/el/7/repodata
redhat/el/7/repodata/a5a3083940e6a97c3d59718e94a432a63b0f831c209340bcd672cd087ffd8b67-primary.xml.gz
redhat/el/7/repodata/e1810e4a03a85362ec3c39ee04b235387c9d04511a529cdc538ed6896b6fc920-primary.xml.gz
redhat/el/7/repodata/a8d1370d56e92431b391e4a31254827dcc1092408702b2337b74876f73bbb298-other.sqlite.bz2
redhat/el/7/repodata/156d4a1b778bf6f6f8a3954fcfb4b8481147a00e48e00d16ec7e4e1a16a479eb-other.sqlite.bz2
redhat/el/7/repodata/db55be83272380413a600c59febd1329d0ce92703c33c5a2025f07595a0107c3-other.xml.gz
redhat/el/7/repodata/repomd.xml
redhat/el/7/repodata/a0ea824f9ef6036fee498e7f7b7f3576a556a9ed547b467d7cfccd3f1465d200-filelists.sqlite.bz2
redhat/el/7/repodata/3d494600f9bee5b28c3e2527dbe625743e7fb01380826fa9e114fcb731dc257d-primary.sqlite.bz2
redhat/el/7/repodata/e028bf7caa1c1450eb212e224be3f67939e020f9760655d7809d8d5f66b1dc1b-other.xml.gz
redhat/el/7/repodata/309cc6ab96bcb4782d63b5737cccbf06b86c4db8af1f2634ef70fb52ec97ed49-filelists.sqlite.bz2
redhat/el/7/repodata/f5ddf739f8ea7547f07a92b50358e158138f3e15fb16785da2241f728c2591f3-primary.sqlite.bz2
redhat/el/7/repodata/55b46695235700e6e88377e256d65e351c95791acdb875c66ca5a4bf8e3d2383-filelists.xml.gz
redhat/el/7/repodata/ee0aff6508ac5a432b75af4671cdc5a0afbcffa626c1dca152a7d30b41cc2505-filelists.xml.gz
redhat/el/7/zerotier-one-1.1.6-0.1.el7.centos.src.rpm
redhat/el/6
redhat/el/6/repodata
redhat/el/6/repodata/703e0ddcf1e5753880990195e0647d4167f05644a841f2ac2e1ca6812a9d69f7-other.sqlite.bz2
redhat/el/6/repodata/39152fd2b71d04fd71b66a680586365dbfdde4e689b990d5ee5128d6f5a36356-other.xml.gz
redhat/el/6/repodata/40f1c669938ca7a2440f2bd4f461355817e0805ab942a252ed4d4570f0bb369f-other.sqlite.bz2
redhat/el/6/repodata/repomd.xml
redhat/el/6/repodata/ca8a9b0b70bce18772e5844ae7ec77fceb3d94627f101d6f732a38f8d27cb83b-filelists.sqlite.bz2
redhat/el/6/repodata/6a82e5be597730b7a7a3b512a21caa3d9118678b229c77daab948c41d23bd5a2-other.xml.gz
redhat/el/6/repodata/290cb4705d5e7140769b1e276fe9dc89f75df84650d3431551feadb704ced01f-primary.xml.gz
redhat/el/6/repodata/35df02f739fdb43a200045aac6caef16fbaf21e2e53b811e2a072351cb2437bc-primary.sqlite.bz2
redhat/el/6/repodata/2024ac4212e56ec59b3de64e57e212f69ec4ad513b5b791e795926049431603c-primary.xml.gz
redhat/el/6/repodata/55a8e67c7c22d3803ce6504d397ae3399812ec57f86f7045c5df96431e0ad1d9-filelists.sqlite.bz2
redhat/el/6/repodata/087ebf677d1791f97ebe613dd8c0a67080b068273f31a21c736b89963faf72b8-primary.sqlite.bz2
redhat/el/6/repodata/9db43917a55fe8354338818a306acbd401eecd6176a2b52041601a8ea2853858-filelists.xml.gz
redhat/el/6/repodata/91c45d57361311feccca6548cb391d417b64907f714445a8f6f18209c0cf7769-filelists.xml.gz
redhat/el/6/zerotier-one-1.1.6-0.1.el6.src.rpm
redhat/el/6/zerotier-one-1.1.6-0.1.el6.i686.rpm
redhat/el/6/zerotier-one-1.1.6-0.1.el6.x86_64.rpm
redhat/amzn1
redhat/amzn1/2016.03
redhat/amzn1/2016.03/zerotier-one-1.1.6-0.1.amzn1.x86_64.rpm
redhat/amzn1/2016.03/repodata
redhat/amzn1/2016.03/repodata/91c6459b2ba86387b6e819f8b9f030811149c5517e96b89b966059ca0e1a21c0-other.xml.gz
redhat/amzn1/2016.03/repodata/04307924b5501d233b4d974a6536078e36a13611894975cbe3a1f87acdb0180f-primary.xml.gz
redhat/amzn1/2016.03/repodata/ed32c68b8cb2bd9b9bd827fb4ecea4f77eb4fe220767d74dee74d528ba90059e-primary.sqlite.bz2
redhat/amzn1/2016.03/repodata/e6c5b868c9818085a7c3e090ee334281457c0687c5010264cf26d162408154d0-primary.xml.gz
redhat/amzn1/2016.03/repodata/06e9cb06d8179f38ed667409e4759d9d4e4920ee4b0f2ede89f9a534a68dc9a7-other.sqlite.bz2
redhat/amzn1/2016.03/repodata/8d80ba7d7b36039f5425d65d413f21bf87af8f8a3d64fe28d76bf4716efa166b-other.sqlite.bz2
redhat/amzn1/2016.03/repodata/repomd.xml
redhat/amzn1/2016.03/repodata/a872972993028c213200f6c5da50f3d6e00d1b7bc0b108e34bf5e75dd5d0f251-filelists.xml.gz
redhat/amzn1/2016.03/repodata/2cf391b1b2652d9fdbb0895fae5fb879ebc685ccc1c12ab8e2ba7877c218b1bb-primary.sqlite.bz2
redhat/amzn1/2016.03/repodata/17d3e6422d67f9a3e84c853e1cecae6d57c50ab30aa3016d47d8fbda39ed5f72-filelists.sqlite.bz2
redhat/amzn1/2016.03/repodata/5a032dabea55b055a0f376a47364112f6e45a5502970990c09b59a3547eeed92-filelists.sqlite.bz2
redhat/amzn1/2016.03/repodata/ac7e28595cdac7cadbfc7cc21707e7eab8872295d8c461f159dc728ddc6dd347-other.xml.gz
redhat/amzn1/2016.03/repodata/72d9ddec8decc08fb1d39ea99cd5e134816a9e2314134976e081690d19b6a6bb-filelists.xml.gz
redhat/amzn1/2016.03/zerotier-one-1.1.6-0.1.amzn1.src.rpm`

**Comment by adamierymenko** [comment]
el/6 is the correct repo

**Comment by oneguynick** [comment]
It is being detected as el/6Server. Is this from the uname or is the script looking for /etc/redhat-release?

**Comment by adamierymenko** [comment]
You can see with:

    curl -s https://install.zerotier.com/ | less

It's looking at /etc/redhat-release. Can you post what you got in /etc/yum.repos.d/zerotier.repo ? We don't have a RHEL image to test with, only CentOS 6.

**Comment by oneguynick** [comment]
Red Hat Enterprise Linux Server release 6.8 (Santiago)

**Comment by adamierymenko** [comment]
What exactly does it put in /etc/yum.repos.d/zerotier.repo and what's the result?

**Comment by oneguynick** [comment]
[zerotier]
name=ZeroTier, Inc. RPM Release Repository
baseurl=http://download.zerotier.com/redhat/el/$releasever
enabled=1
gpgcheck=1

**Comment by adamierymenko** [comment]
Is there some way you can see what it's putting for $releasever?

**Comment by adamierymenko** [comment]
I would think that would be 6, which should work.

**Comment by oneguynick** [comment]
After install yum-utils:

[dudeadminbubba@noyb ~]# python -c 'import yum, pprint; yb = yum.YumBase(); pprint.pprint(yb.conf.yumvar, width=1)'
Loaded plugins: product-id
{'arch': 'ia32e',
 'basearch': 'x86_64',
 'releasever': '6Server',
 'uuid': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}

**Comment by adamierymenko** [comment]
ahh... so RHEL does '6Server' instead of just '6'... should be able to fix that with a symlink on the web server but WHY???? sec.

**Comment by adamierymenko** [comment]
Done... try it again.

**Comment by oneguynick** [comment]
Works like a champ 👍 

Welcome to the world of RHEL. Wait till some Oracle guy shows up ;)

**Comment by adamierymenko** [comment]
It's now like this (minus 4 and 5 which we don't support): http://download.virtualbox.org/virtualbox/rpm/el/
