### ISSUE TITLE
Network specific settings do not persist on client when leave/join

### ISSUE THREAD

**Issue by jdrews** [zerotier/ZeroTierOne#353]
If I join a network and then run the following command:
```zerotier-cli set <NETWORK_ID> allowManaged=0```

Then I leave the network and join the network:
```zerotier-cli leave <NETWORK_ID>```
```zerotier-cli join <NETWORK_ID>```

The setting is enabled again per
```zerotier-cli -j listnetworks```

Is there a way to store network specific settings in a file somewhere? 

Debian 8 and zt 1.1.8

I'm trying to disable managed routes on this machine as it's a gateway into other networks (see #352)

**Comment by adamierymenko** [comment]
This is also by design -- but should it be?

Still seems like #352 is the fundamental issue.

**Comment by jdrews** [comment]
Agreed. allowManaged is enabled by default which will suit my current use case if #352 is fixed. 

In the future, I could see use cases where a user may want to store settings for a specific network. Especially if we implement Client UI updates to support Join/Leave + Connect/Disconnect #326.

In my vision of ZeroTier I could see a user dropping in and out of a network depending on their situation (e.g. on a cell phone hotspot and don't want to burn data, or only connecting to zerotier network when working remotely and business hours, etc). When that happens, the user wouldn't want to reset all their settings each time.

**Comment by adamierymenko** [comment]
I think this is a UI issue.

We are working on a new command line interface, and in that we'll allow such options to be specified on the 'join' command line so they don't have to be reissued as separate commands.
