### ISSUE TITLE
Setting allowManaged to 0 removes ip on interface zt0

### ISSUE THREAD

**Issue by jdrews** [zerotier/ZeroTierOne#354]
If I run the following command to remove managed routes on a zt member, it correctly removes the managed routes on the client. But it also removes the ip address on the zt0 interface. 

```zerotier-cli set <NETWORK_ID> allowManaged=0```

Debian 8, zt 1.1.8

I'm attempting to make this member a gateway into other networks. See #352

**Comment by adamierymenko** [comment]
That's because no distinction is made between routes and IPs -- allowManaged controls both. (When you think about it, there really isn't much distinction when it comes to the security implications.)

Seems like #352 is the actual issue.

**Comment by adamierymenko** [comment]
Closing since not-a-bug -- see #352

**Comment by jdrews** [comment]
Ok yeah I agree. If we fix #352 then we can leave allowManaged enabled, the gateway node will get it's IP, and no routes will be applied. All should be well.
