### ISSUE TITLE
Don't auto connect to Earth network on install

### ISSUE THREAD

**Issue by jdrews** [zerotier/ZeroTierOne#356]
When installing 1.1.12 on CentOS 6.7 I see this message. 

```
*** Success! You are connected to port  of Earth's planetary smart switch.
```

Should it be automatically adding me to the Earth network? Seems like that's something a user would opt into...

Furthermore when I do 
```
[root@services1 ~]# zerotier-cli listnetworks
200 listnetworks <nwid> <name> <mac> <status> <type> <dev> <ZT assigned ips>
```
 I see no networks connected. Perhaps this is something left over from a while back?

Further logs here: 
[zerotier-centos-install.txt](https://github.com/zerotier/ZeroTierOne/files/360417/zerotier-centos-install.txt)

**Comment by adamierymenko** [comment]
It doesn't, as listnetworks will confirm. That's just a confusing message. We'll change it.
