### ISSUE TITLE
Mac OS X Client About screen has incorrect dates, version num, and MacGap project info

### ISSUE THREAD

**Issue by grempe** [zerotier/ZeroTierOne#366]
The 'About ZeroTier One' screen in OS X client version 1.1.14 contains several errors.

1. The version info does not match the version of the software downloaded. It shows `Version 1.0 (1)` for software version `1.1.14`
2. The copyright dates only reflect up to 2015, not the 2016 release of the software.
3. The MacGap project is not copyright Twitter according to its license, although some files within are marked copyright Twitter in their headers, likely due to the fact that this project was forked/ported from PhoneGap. See copyright notice from the LICENSE linked to below.
4. The URL for the MacGap project you provide (`http://macgap.com`) is incorrect (and does not function). It should be `https://macgapproject.github.io` I believe.

```
# https://github.com/MacGapProject/MacGap1/blob/master/LICENSE
...
Copyright (c) <2012> <Nitobi Software Inc., et. al., >
...
```

**Comment by adamierymenko** [comment]
The OS X GUI is going to get completely replaced in a future (probably next) version. We're working on a totally new Mac GUI in Swift that looks a bit like the OS X WiFi pulldown. It's very nice.

Closing since the old GUI is on death row.

**Comment by grempe** [comment]
I look forward to it. :)
