### ISSUE TITLE
Android App on F-Droid

### ISSUE THREAD

**Issue by fkooman** [zerotier/ZeroTierOne#369]
Is it possible to make the Android application available outside the Google Play store? For example on https://f-droid.org/?

**Comment by Mirodin** [comment]
I would love to see this happen.

**Comment by Adonai** [comment]
BTW is ZT android app FLOSS? Because if it is we can add it to F-Droid Submission Queue by ourselves.

**Comment by glimberg** [comment]
No. Neither the Android nor iOS apps are open source.

**Comment by marek22k** [comment]
It is still closed source? On https://github.com/kaaass/ZerotierFix there seems to be a fork of the closed source app. If yes, please reopen the issue. If no, close it as not planed as it is not resolved.

**Comment by PizzaProgram** [comment]
It seems the SDK itself is closed source.
ZerotierFix is using that too, so it will not be possible for them either. See issue about it:
https://github.com/kaaass/ZerotierFix/issues/17#issuecomment-2029553032
