### ISSUE TITLE
ZeroTier package in Alpine

### ISSUE THREAD

**Issue by ramarnat** [zerotier/ZeroTierOne#370]
Creating this here for tracking purposes. 

ZeroTier should be available in the Alpine Linux Repo (especially for docker installations). 

https://pkgs.alpinelinux.org/packages

**Comment by kyleparisi** [comment]
Absolute noob about this but I gave it a shot and got the following error after running `make`:

```bash
osdep/LinuxEthernetTap.cpp:35:22: fatal error: linux/if.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'osdep/LinuxEthernetTap.o' failed
make: *** [osdep/LinuxEthernetTap.o] Error 1
```

Probably not a great idea to do it in the alpine docker image?  If not, I can image an old computer I have with alpine at some point.

**Comment by adamierymenko** [comment]
There is a package in Alpine with kernel headers like this. Forget what it is called.

**Comment by adamierymenko** [comment]
Alpine is designed to be super minimal and does not install such things by default, while other distros do.

**Comment by kyleparisi** [comment]
Ok, I'll try to look those up after the holiday.

**Comment by kyleparisi** [comment]
Got slightly further this time.  Needed to install `linux-headers`, `bash`, `man-pages` (maybe?), `nodejs`.  I ran `make selftest` and didn't see any problems.  I presume all I need to do now is to finish following [this wiki](http://wiki.alpinelinux.org/wiki/Creating_an_Alpine_package).  

I'm thinking I'll start with the init.d script part.  Is there something I can reference for this?

**Comment by kyleparisi** [comment]
Does anyone know OpenRC (Alpine init system)?  Struggling at getting the init script in.

**Comment by adamierymenko** [comment]
You're telling me Linux now has **another** init system?

I've got the solution! (goes off to write yet another init system)

**Comment by dafyre** [comment]
You can call it  YAInit!

**Comment by bonki** [comment]
> You're telling me Linux now has another init system?
> 
> I've got the solution! (goes off to write yet another init system)

You need not worry, OpenRC is ~10 years old already :-) (primarily developed for and by a then-Gentoo developer but it's used by other Linux and even BSD distributions IIRC).

> Does anyone know OpenRC (Alpine init system)? Struggling at getting the init script in.

That's what I use on Gentoo, couldn't be more basic:

```
#!/sbin/runscript

ZEROTIERONE_PIDFILE="/var/run/${SVCNAME}.pid"

depend() {
        need net
}

start() {
        ebegin "Starting zerotier-one"
        start-stop-daemon --start \
                --exec /usr/bin/zerotier-one --make-pidfile --pidfile "${ZEROTIERONE_PIDFILE}" --background
        eend $?
}

stop() {
        ebegin "Stopping zerotier-one server"
        start-stop-daemon --stop --quiet --pidfile "${ZEROTIERONE_PIDFILE}"
        eend $?
}
```

**Comment by kyleparisi** [comment]
@bonki I tried something similar but I'll give what you posted a try.  Thanks.

**Comment by kyleparisi** [comment]
@bonki Looks like that worked.  My issue was trying to run it on a docker alpine.  Works fine on a vm.  

Just need to button up the package.  I'll post back here when you can view it in my fork for any feedback.

**Comment by kyleparisi** [comment]
https://github.com/kyleparisi/aports/commit/e12828dccdf5b3d79904aee7531109c544328bf9

Feedback welcome.  Will create PR after a few days.

**Comment by kyleparisi** [comment]
Just waiting on the PR to be merged or rejected: https://github.com/alpinelinux/aports/pull/344

**Comment by kyleparisi** [comment]
So it ended up being this PR instead: https://github.com/alpinelinux/aports/pull/533

I'm not entirely sure when I can have the package be part of the main apk.  If you want to test/start using in the mean time it'd be something like 

```bash
vi /etc/apk/repositories
apk update
apk add zerotier-one@testing
/etc/init.d/zerotier-one start
```

**Comment by kyleparisi** [comment]
@ramarnat, @adamierymenko has taken over via: https://github.com/alpinelinux/aports/pull/1379 

You think it possible to also close: https://www.bountysource.com/issues/36370440-zerotier-package-in-alpine 😀

**Comment by zar3bski** [comment]
> Got slightly further this time. Needed to install `linux-headers`, `bash`, `man-pages` (maybe?), `nodejs`. I ran `make selftest` and didn't see any problems. I presume all I need to do now is to finish following [this wiki](http://wiki.alpinelinux.org/wiki/Creating_an_Alpine_package).
> 
> I'm thinking I'll start with the init.d script part. Is there something I can reference for this?

Experienced similar issue: `linux-headers` should become a reflex while building alpine based image
