### ISSUE TITLE
Regression: Windows Connections stuck in ESTABLISHED state

### ISSUE THREAD

**Issue by heri16** [zerotier/ZeroTierOne#371]
Windows connections going over zerotier one interface are stuck in ESTABLISHED state, when the remote peer dies.

Tested on v1.1.14 .
Was using v1.1.4 previously with no such problem.

**Comment by heri16** [comment]
This needs fixing as not all programs have built-in heartbeat to detect that the connection is blackholing.

**Comment by adamierymenko** [comment]
I am not sure this is a ZT problem.

TCP has (in most cases unless special socket options are set) no built-in mechanism for detecting if the other side is dead. That's the job of the protocol. Most protocols do occasionally send some kind of heartbeat or keepalive/ping message to do this, but if they don't they will have absolutely no way of detecting a dead peer on the other side.

**Comment by adamierymenko** [comment]
Are you sure nothing else changed between 1.1.4 and 1.1.14? ZT emulates L2 Ethernet and this basic behavior has not changed. The Windows tap device driver also has not changed between these versions.
