### ISSUE TITLE
/etc/init.d/zerotier-one file missing

### ISSUE THREAD

**Issue by rebroad** [zerotier/ZeroTierOne#373]
for some reason this file has disappeared, and an apt-get reinstall zerotier-one doesn't recreate it...!

**Comment by dafyre** [comment]
What linux distro are you running?  I thought many of them had switched from init.d to the newer...  Umm...    systemd ?

**Comment by rebroad** [comment]
raspbian

**Comment by adamierymenko** [comment]
Circling back... this is strange. We have our package on a lot of Pis and don't have this issue.

What version of Raspbian? `/etc/debian_version`

**Comment by Mareckil** [comment]
Hi there, I just installed Zerotier on my Linux Mint. All compilation went well, but I cant run a service of zerotier-one. As above /etc/init.d/zerotier-one is missing.

sudo systemctl status zerotier-one
Unit zerotier-one.service could not be found.

sudo zerotier-cli status
200 info 46763d79e2 1.14.0 ONLINE

**Comment by laduke** [comment]
compiling just compiles the program. It doesn't add things to your system. 
If you run the installer it will add all the extra files like the service. https://www.zerotier.com/download/
