### ISSUE TITLE
install.zerotier.com script / packages will not install on Linux Mint

### ISSUE THREAD

**Issue by adamierymenko** [zerotier/ZeroTierOne#379]
Or at least some versions...

Technically this is an install.zerotier.com / packaging problem, not a bug in the code at all.

**Comment by jonathonf** [comment]
Is this a tracking bug item or is there error text to go with it?

**Comment by psy0ch** [comment]
same problem currently.
zerotier-one depends on libtdc++6 (>=4.9) but 4.8.42ubuntu~14.04.3 should be installed
zto depends on it-ytem-helpers (>1.18~) but 1.14 should be installed
(i translated it now, i have the output in german..
the exact i: Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 zerotier-one : Hängt ab von: libstdc++6 (>= 4.9) aber 4.8.4-2ubuntu1~14.04.3 soll installiert werden
                Hängt ab von: init-system-helpers (>= 1.18~) aber 1.14 soll installiert werden
E: Probleme können nicht korrigiert werden, Sie haben zurückgehaltene defekte Pakete.
)

**Comment by adamierymenko** [comment]
Seems fixed.

**Comment by DiogoAbdalla** [comment]
having this same issue in Mint 17:
` zerotier-one : Depends: init-system-helpers (>= 1.18~) but 1.14ubuntu1 is to be installed`

does anyone knows a fix to that?

**Comment by jonathonf** [comment]
Mint 17 is based on Ubuntu 14.04 which is EOL in four months (April 2019). The easy fix is to upgrade - you're going to have to do it very soon anyway.

Or, just install the `trusty` package directly from http://download.zerotier.com/debian/trusty/pool/main/z/zerotier-one/
