### ISSUE TITLE
Reject duplicated paths

### ISSUE THREAD

**Issue by kraney** [zerotier/ZeroTierOne#381]
I described a connectivity problem I was having on the Forums, at https://www.zerotier.com/community/topic/89/connectivity-issue

The final diagnosis was a bad NAT - two docker containers were being mapped by the NAT to the same UDP source port. Under that circumstance, it's not possible for the NAT to direct reply packets back to the correct container.

I believe ZeroTier can and should detect this situation.

I believe ZeroTier should not accept as valid a path that is identical to a path for another, separate node. In fact, when seeing a second node arriving by a path that is considered valid for a different node, the path should be invalidated for the first node as well.

In the scenario described on the forum, if the UDP path was not considered valid, perhaps the two nodes would fall back to a TCP-based connection, and connectivity would be achieved (at the cost of performance.)

**Comment by adamierymenko** [comment]
We're going to be reworking paths a bit in the next version or shortly thereafter. This will include a number of improvements to how paths are handled, and it should make this issue go away in most cases.

Note that there are limits to how "heroic" ZT can be in the presence of flat out broken NATs and other fundamental network problems. Sometimes broke is broke.

**Comment by adamierymenko** [comment]
Am actually going to close this since path reworking is already on the slate.
