### ISSUE TITLE
Debian packages for ARM64 and other architectures (and more distros)

### ISSUE THREAD

**Issue by ndrego** [zerotier/ZeroTierOne#382]
@adamierymenko Was wondering about an `arm64` build, particularly for Ubuntu 14.04 LTS. I managed to compile and create a .deb. The only change I had to make was getting the `make-linux.mk` to use `g++-4.9` (after installing that version of gcc). In particular, gcc/g++ < 4.9 doesn't support `-fstack-protector-strong` or `nlohmann::json`.

Any chance this could become part of the normal build process?

**Comment by adamierymenko** [comment]
We're going to be doing Debian builds for lots of architectures in the next release. Just discovered some stuff that makes this easier.

In some cases we will have to obtain a newer GCC/G++ and/or use CLANG. The latter is available in many distributions and works much better for C++ in general in my experience. (At least vs. older G++ versions... newer G++ may be better.)

**Comment by niv** [comment]
Can you add a statically linked package tgz package too, for use on non-debian or custom/embedded distros (my case in point: qnap NAS boxes)?

**Comment by janjaapbos** [comment]
Yes, that would be nice, perhaps put everything in the same root and not installing system init stuff.

**Comment by Qonstrukt** [comment]
Would be great if we could have support for EdgeOS by Ubiquity which is based on Debian Wheezy and runs on MIPS CPU's.

**Comment by ptman** [comment]
I found that there are no armhf builds for debian stretch, even though those are available for debian jessie. Also, would it be possible to have a statically linked binary in a .tar.gz distribution for various arm routers (maybe mips also, I'm not sure what is most common)?

**Comment by adamierymenko** [comment]
Closing since 1.2.0 has arm64, and more are coming.
