### ISSUE TITLE
Create un-bifurcated route when there is no default route

### ISSUE THREAD

**Issue by fschulze** [zerotier/ZeroTierOne#385]
As discussed in https://www.zerotier.com/community/topic/69/default-route-override-a-k-a-full-tunnel-in-1-1-6 ZeroTier should create a normal default route instead of a bifurcated one if no default route exists. This should make Safari and other Apps work on OS X, where currently only command line tools and Chrome work.

**Comment by adamierymenko** [comment]
This looks like it's not too hard to implement, and it's working in `dev` on OSX. (Windows and Linux will need a bit of extra code.)

It does not however seem to force Safari to use IPv6. Chrome, *yes*, Safari, no. Not sure why but I don't think there's anything we can do as this is Apple code.

But yeah this is a good idea.

We changed the general route logic so that it now creates a bifurcated route any time there is a route being *replaced*, and creates a straightforward route otherwise.

**Comment by adamierymenko** [comment]
It seems likely that Safari only checks system interfaces (e.g. en0) for IPv6 addresses to decide whether to enable V6, while Chrome looks at other interfaces.

This kind of hard-coded interface restriction is common in Apple stuff.

**Comment by adamierymenko** [comment]
Okay, yes, this is done for Mac in `dev` and will get done for Windows before we ship.

Linux I may leave as-is for now... depends on how easy it is.

**Comment by fschulze** [comment]
Great!

I tried to test it, but the installed ZeroTier seems to be in the way. How can I temporarily stop it, or install the dev version?

**Comment by adamierymenko** [comment]
Turns out this is problematic as-is as it seems to prevent the OS from creating a route when you switch networks. Have to test and work on this some more.

**Comment by adamierymenko** [comment]
Yeah I think we're going to back that one out *for now*, but I do thing this is nice so it is staying in backlog. Will have to figure out how to avoid banging up against OS management of routes.

**Comment by adamierymenko** [comment]
Unfortunately I am going to have to set this to wontfix. Here's the problem. If such a route is present when the laptop wakes from sleep, it won't set its new route properly when joining an IPv6-enabled network. So if I go from work (no IPv6) to home (IPv6) my IPv6 is dead with this enabled.

I've done some research and I can't find a good solution for this. MacOS's network services assume they are the ones managing the route table, and don't seem to play nice if someone else is sticking conflicting routes in there.

The bifurcation technique is a hack to avoid this by making ZT's routes highly unlikely to conflict with OS routes. So the OS just ignores them and manages its own routes normally.

I agree that this feature would be cool, but I don't think it's cool enough to merit introducing something that might render the user's Internet connection unstable when switching networks. 😞

**Comment by fschulze** [comment]
Since it didn't work with Safari anyway, I concur.
