### ISSUE TITLE
Windows installer should warn if user is logged in via remote desktop

### ISSUE THREAD

**Issue by adamierymenko** [zerotier/ZeroTierOne#386]
"Anyway, to resolve the issue open gpedit.msc (or create a GPO, whatever you prefer) . Browse to Computer Configuration\Administrative Templates\Windows Components\Remote Desktop Services\Remote Desktop Session Host\Application Compatibility. Set Turn off Windows Installer RDS Compatibility to Enabled. Now run the installer again."

This is a gotcha that occurs if installing any Microsoft MSI package over a remote desktop session... for some bizarre reason.

**Comment by rebroad** [comment]
gpedit.msc isn't available on Windows 10 single language...
