### ISSUE TITLE
Android app build recepie

### ISSUE THREAD

**Issue by leni536** [zerotier/ZeroTierOne#388]
I can't find the build recipe for the Android app that can be downloaded from Google Play. I'm not familiar with Android development and your source tree though. Is it available in this source tree?

**Comment by glimberg** [comment]
The android app is not open source.  The JNI code to expose the ZeroTier API in Java/Android can be found here:  https://github.com/zerotier/ZeroTierOne/tree/master/java

**Comment by leni536** [comment]
Are there any plans to release the app's source in the future?

**Comment by glimberg** [comment]
Not at this time.
