### ISSUE TITLE
Crash on startup because of missing fonts (Windows Embedded)

### ISSUE THREAD

**Issue by ttyler777** [zerotier/ZeroTierOne#390]
I'm installing ZeroTier onto Windows Embedded machines 64-bit.  These embedded machines have a windows OS that has had a lot of the "Fluff" stripped away, including most of the fonts.  After installing, if I try to run ZeroTier One, it crashes with this event log error:
[event_log_error.txt](https://github.com/zerotier/ZeroTierOne/files/474950/event_log_error.txt)
Now, the way I've got around this is to copy all of my fonts from a normal Windows 7 machine to the embedded machine.  But that takes up space.  Is there anything that can be done about this?

EDIT:

Looks like this is a normal thing:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/fc2c9a54-8f66-4f1a-82be-cb40ada5fba5/systemwindowsmediafontfamily-crash-net-35-sp1-systemexecutionengineexception?forum=wpf

I don't know if its even possible to do something on ZeroTier's end.  Might just be a windows thing.

**Comment by adamierymenko** [comment]
Can you give me a list of what fonts *are* installed on Windows Embedded? Maybe we can go with one of those in the future for the app.

**Comment by adamierymenko** [comment]
Will fix by adding fonts to Advanced Installer MSI

**Comment by adamierymenko** [comment]
Fixed in `dev` by ensuring that fonts are installed if not present.
