### ISSUE TITLE
Allow interface blacklisting to be configured locally

### ISSUE THREAD

**Issue by CkNoSFeRaTU** [zerotier/ZeroTierOne#394]
1) Zerotier blacklisting interfaces which starts with tun/tap. That's a bad decision and must be at least configurable if not removed. In my case these interfaces are the shortest path.
2) How p2p addresses exchange actually works? Because there a couple of problems:
  a) If there are multiple path to the same destination ip address zerotier often choose not optimal outgoing interface. Latency looks like wrongly calculated also as it seems latency check goes though different path than actual traffic.
  b) Peers not using local addresses for example in these schemes:
same segment: zerotier->ipip tunnel->bridge->zerotier
different segment: zerotier->gw->gw->zerotier

**Comment by adamierymenko** [comment]
I've retitled this, and here's a few responses:

1. Yes, this should probably be configurable. We did this because in many cases people *don't* want routing this way.

2. This could also be solved by allowing local configuration of interface blacklists.

**Comment by adamierymenko** [comment]
Done in 1.2.0 -- see local.conf
