### ISSUE TITLE
Zerotier 1.1.14 on ubuntu shows up as offline in my.zerotier.com

### ISSUE THREAD

**Issue by rebroad** [zerotier/ZeroTierOne#396]
sudo zerotier-cli info shows ONLINE but my.zerotier.com shows OFFLINE.

Trying to debug and will report back when I have more info.

a sudo /etc/init.d/zerotier-one restart usually fixes this.

**Comment by edtjones** [comment]
@rebroad did you get anywhere with finding out why this happens? I saw a similar thing today (although I didn't check to see if my.zerotier.com had ONLINE).

**Comment by sbilly** [comment]
#406 is the same.

**Comment by adamierymenko** [comment]
Is #406 and this still happening? If so please e-mail contact@zerotier.com with more info.

**Comment by rebroad** [comment]
@adamierymenko Is this fixed now?

**Comment by adamierymenko** [comment]
We aren't seeing any service issues anywhere. What's the device ID?
