### ISSUE TITLE
Long recovery after switching public IPv4 address

### ISSUE THREAD

**Issue by zielmicha** [zerotier/ZeroTierOne#397]
I have a scenario where:
1) I run ZT on cloud VM ("A") with public IP
2) send packets between A and other host behind NAT ("B")
2) shutdown and destroy A
3) launch another VM ("C") with same `/var/lib/zerotier-one` and different public IP
In about 2/3 of cases, this causes loss of all ZT traffic between B and C lasting from 30 seconds to 5 minutes.

I'm using 6PLANE addresses, so this problem shouldn't be caused by ARP. And after step 3 on host B `zerotier-cli listpeers` shows:

```
200 listpeers <ztaddr> <paths> <latency> <version> <role>
200 listpeers (zt address of A/C) - 42 1.1.14 LEAF
```

It would be great if the connectivity between A and C could be restored faster. Is there a way to force reconnect/rediscovery manually either from A or C?

**Comment by adamierymenko** [comment]
This is a bit better in the new version. It's actually a hard problem, especially with a NAT in the way.

The only way (in a hard information theoretic sense) to actually detect physical topology changes is by looking at traffic, and therefore the only way to do it fast is with keepalives or heartbeats. BGP does this on LAN "carrier hotel" interconnects by doing a lot of very frequent keepalive, but that's among hosts that are physically L2 adjacent and the packets are tiny so who cares.

Problem is that for this doing constant keepalives like BGP does is incredibly wasteful over WAN and is particularly awful for mobile peers on things like LTE.  Hulk drain battery.

The new version has refactored the way we manage paths so we can use NAT keepalives to detect this a little tighter. It *should* usually be <30s now. Doing it even faster would require... well... it's an engineering tradeoff like everything else.

**Comment by sbilly** [comment]
Maybe ARP cache TTL is helpful.

**Comment by adamierymenko** [comment]
Would have no effect, since ZT is a total encapsulation protocol. It's not just a thin route management layer on top of what's already there.

**Comment by zielmicha** [comment]
In most cases ZT can easily detect that the topology has changed (e.g. internal IP address of the machine has changed) - the node could then reestablish all "connections" to peers in at most few seconds. 

This approach requires "push notifications" from the node which knows about topology change (I don't is possible using current protocol).
