### ISSUE TITLE
How to use ZeroTierOne server on my own VPS?

### ISSUE THREAD

**Issue by Hirozy** [zerotier/ZeroTierOne#398]
I building ZeroTierOne/controller from source and install it on my VPS, but I don't know how to control or use it.
I have google this question, and get nothing.

**Comment by jdrews** [comment]
Use the Network Controller API documented here: https://github.com/zerotier/ZeroTierOne/tree/master/controller#network-controller-api

Lots of other good documentation on that page too.

**Comment by jdrews** [comment]
If you don't want to run your own controller, you can just use https://my.zerotier.com/. It's dead simple.
It's good for up to 100 devices for free.

Just make a new network and use the network ID to join your VPS to that network.
