### ISSUE TITLE
migrate-sqlite not present in dev yet (TODO)

### ISSUE THREAD

**Issue by pkpowell** [zerotier/ZeroTierOne#399]
The dev branch references `migrate-sqlite` in /controller/README.md but I can't find it in the repo.
I found `db-migrate-sqlite3` on npm, but have a feeling that's not what the docs are referring to.
I'd really like to test the new builds on my controllers, is it still too early for that? (btw the more recent devs work great on my test clients).

**Comment by adamierymenko** [comment]
This is not done yet! Sorry. Will be done before `dev` gets released of course.

**Comment by adamierymenko** [comment]
Yeah we are even rev'ing the way the `dev` controller stores its JSON a bit... so that code is *definitely* not production ready yet.

**Comment by adamierymenko** [comment]
In dev now.

**Comment by pkpowell** [comment]
Awesome! 
Migrated successfully except that no members show up via the curl api.
I get network info, but 
````
curl  -H 'X-ZT1-Auth:[secret]' http://127.0.0.1:9993/controller/network/[nwid]/member/
````
 returns `{}`
`"totalMemberCount"` in network info is `0`which is a bit weird.
The connections seem to be up, so I'm probably doing something wrong...

the network info:
````
{
 "activeMemberCount": 5,
 "authTokens": [],
 "authorizedMemberCount": 9,
....
"totalMemberCount": 0,
````
