### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by jernst** [zerotier/ZeroTierOne#404]
Attempting to build https://github.com/zerotier/ZeroTierOne/archive/1.1.12.tar.gz:

Towards the end:
```
cd doc ; ./build.sh
Installing npm package "marked-man" -- MarkDown to ROFF converter...
.../ZeroTierOne-1.1.12/doc
+-+ marked-man@0.1.5
  +- marked@0.3.6

npm WARN enoent ENOENT: no such file or directory, open '..../ZeroTierOne-1.1.12/doc/package.json'
```

**Comment by adamierymenko** [comment]
This is a problem trying to build the man pages... try just `make one` to make the service alone.

We're going to change this in the next version. BTW 1.1.14 is the latest tagged release.
