### ISSUE TITLE
REQUESTING_CONFIGURATION long time on MACOSX

### ISSUE THREAD

**Issue by sbilly** [zerotier/ZeroTierOne#406]
REQUESTING_CONFIGURATION long time on MACOSX. https://my.zerotier.com/ is offline status while:

uname -a

```
Darwin xxxxxxxx 16.1.0 Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64 x86_64
```

zerotier-cli status

```
200 info xxxxx ONLINE 1.1.14
```

zerotier-cli listnetworks

```
200 listnetworks <nwid> <name> <mac> <status> <type> <dev> <ZT assigned ips>
200 listnetworks xxxxx - xx:xx:xx:xx:xx:xx REQUESTING_CONFIGURATION PRIVATE zt0 -
```

**Comment by adamierymenko** [comment]
Hmm... is this still happening? If so can you e-mail contact@zerotier.com with more detail?

**Comment by sbilly** [comment]
It happened again. I have already wrote a mail to contact@zerotier.com.

**Comment by johanbaath** [comment]
I have the same issue. Stuck on:

```REQUESTING_CONFIGURATION PRIVATE zt0 -```

Latest version of OS X.

What should I do?

**Comment by vikaskedia** [comment]
I have the same issue. Stuck on:

REQUESTING_CONFIGURATION PRIVATE zt0 -

Latest version of OS X.

What should I do?

**Comment by lqhl** [comment]
How to fix this issue?
Seems like I get the same problem on my macOS:
```
[~]$ sudo zerotier-cli listnetworks
200 listnetworks <nwid> <name> <mac> <status> <type> <dev> <ZT assigned ips>
200 listnetworks XXXXXXXXXXXX  XXXXXXXXXX REQUESTING_CONFIGURATION PRIVATE zt0 -
[~]$ sudo zerotier-cli status
200 info XXXXXXX 1.2.4 ONLINE
```

**Comment by joseph-henry** [comment]
Can you try building and running from the `dev` branch? We have seen this as recently as a month ago but are unable to reproduce it right now. Can you tell us the (first four) digits of your network ID? This information will only tell us what controller you're running on.

And do you see this on all networks or just some?

**Comment by lqhl** [comment]
@joseph-henry My network ID is `17d7...`. We didn't run our own controller, and we are using the client of version 1.2.4.  I find that this was not a problem of macOS, my Android phone had the same issue. The connection resumed after around 12 hours.
I think the reason may be the network disturbance caused by Chinese great firewall, because when the issue happened, my servers in other areas in the same network can connect to zerotier normally. Is there any way that I can test the connection between my client and the controller?

**Comment by jrz** [comment]
Still happening.. Trying to join a new network. Other networks (already connected) work properly. From a different machine I can connect.. I don't want to reboot my laptop

**Comment by jrz** [comment]
Also.. I just got soe popups about request time out.  I press quit. and now all my networks are removed from my laptop.

**Comment by jrz** [comment]
Had to kill the zerotier-one process (not the UI).  Things are working now
