### ISSUE TITLE
Controller downtime should not lead to edge/edge connectivity loss... pretty much ever.

### ISSUE THREAD

**Issue by adamierymenko** [zerotier/ZeroTierOne#409]
We've had a few sporadic issues with SaaS hosted controllers lately and have both witnessed ourselves and received reports of this disrupting the edge, which should not happen.

This is almost certainly a cert timing issue, and *might* be fixed in `dev` already since we have adjusted these parameters. This issue is to make sure we test this heavily prior to 1.2.0 and rev'ing the entire Central infrastructure.

**Comment by adamierymenko** [comment]
Note #1: the only time this should occur is if the controller is down and a node has not been online for quite some time. In that case it's going to have an off-horizon cert and this is "not a bug, but a feature."

Note #2: the 1.2.0 controller uses a simple in-filesystem JSON tree to store its state instead of SQLite. This makes it easier to implement reliable HA failover and/or clustering using everything from rsync to distributed filesystems to Amazon Elastic Filesystem. (We plan to use the latter in our new deployment.)

**Comment by peterkeen** [comment]
Have you looked into using BedrockDB for SQLite HA? It looks pretty interesting.

**Comment by adamierymenko** [comment]
All the refactoring for the new way of storing data is done, so that's moot at this point.

Another advantage of storing it in filesystem as JSON is that you can check it into git, tar it up, etc. It makes it very workable. Finally the last advantage is that it makes the controller code smaller and dependency-free. In 1.2.0 we are building the controller by default in Windows, Mac, and Linux, which will make it easy to offer an ad-hoc networking feature in the future if people want it (and simplifies the docs, etc.).

The controller's DB needs are pretty minimal. It's a minimal microservice that acts as a CA and issues member configs. If we find ourselves wanting advanced SQL queries in the controller, we are probably implementing something too complex there that belongs in Central instead. :)

**Comment by adamierymenko** [comment]
Oh... and last but not least... the new Central uses RethinkDB. It would be fairly easy to implement ReDB connectivity for the controller given that it's now written to store everything as JSON docs. So this would open yet another HA replication avenue if we want it.

**Comment by adamierymenko** [comment]
Did a lot of 1.2.0 testing with the partially rewritten controller and this seemed fine. Closing for now.
