### ISSUE TITLE
Get and use system HTTP proxy settings on Linux and Macintosh

### ISSUE THREAD

**Issue by adamierymenko** [zerotier/ZeroTierOne#41]
Get and use system proxy settings for HTTP download of software updates on Linux and Macintosh systems. For Linux we'll probably just support the most common mechanisms... GNOME and KDE?

**Comment by Jamesits** [comment]
Please fix this... I'm unable to download the components required on OS X without a proxy.

**Comment by adamierymenko** [comment]
Closing since (1) Mac installer now bundles everything, and (2) World updates are now in-band.
