### ISSUE TITLE
Expose allowGlobal in UI

### ISSUE THREAD

**Issue by r04r** [zerotier/ZeroTierOne#410]
I want to replace my OpenVPN setup with ZeroTier but for that I need to be able to tell my users how they can enable the allowGlobal setting. It is possible to do this using the CLI: `zerotier-cli set networkId allowGlobal=1` but telling end-users to do this is problematic, especially for Windows, Android and iOS users.

**Comment by glimberg** [comment]
Android and iOS always allow global IP addresses.  Updated UIs with support for allowGlobal/allowDefault for Mac and Windows are coming soon with the 1.2.0 release.  Also coming with the 1.2.0 release is default route support on iOS and Android.

**Comment by r04r** [comment]
That's great news, thanks!
