### ISSUE TITLE
Repeated failures to start service

### ISSUE THREAD

**Issue by nzjrs** [zerotier/ZeroTierOne#411]
Ubuntu 14.04 installed from deb package (1.1.14)

no feedback other than

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  cannot bind to local control interface port
```

when calling the cli client to see what is going on

**Comment by adamierymenko** [comment]
Looks like it can't bind to 127.0.0.1:9993. Are you using SELinux?

**Comment by nzjrs** [comment]
Nope, its disabled. I'm confused because it doesn't happen every time, only
on some networks.

**Comment by nzjrs** [comment]
this has rendered zerotierone unusable for me on two computers.

**Comment by ramtej** [comment]
same issue on ubuntu 16.04

xxx:~$ sudo zerotier-one status
zerotier-one: fatal error: cannot bind to local control interface port

**Comment by nzjrs** [comment]
Mine was pebkac. try $zerotier-cli

On 14 May 2017 16:02, "Jiri Jetmar" <notifications@github.com> wrote:

same issue on ubuntu 16.04

xxx:~$ sudo zerotier-one status
zerotier-one: fatal error: cannot bind to local control interface port

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/zerotier/ZeroTierOne/issues/411#issuecomment-301315404>,
or mute the thread

**Comment by ramtej** [comment]
Thank you - works for me !

**Comment by adwindy** [comment]
how to slove this problem???

**Comment by huangsijun17** [comment]
```
modprobe tun
killall zerotier-one
zerotier-one -d
```

**Comment by cjd400** [comment]
tried huangsijun17's solution didn't work still getting cannot bind to local control interface port 9993 - this is happening since I switched to Vodafone tsp with new router that has renamed .local to .broadband everywhere - but only seems to be affecting my linux machine all other windows, Mac, iOS machines working without problem connecting happily
