### ISSUE TITLE
API to get member list with full details

### ISSUE THREAD

**Issue by r04r** [zerotier/ZeroTierOne#412]
I'm reading the docs at https://github.com/zerotier/ZeroTierOne/tree/master/controller and can not find a single API call that would provide me with a list of all members and their details, such as those that are shown on `https://my.zerotier.com/network/<id>` (auth, address, name, managed ips, status, version, physcal ip, bridge).

I'm assuming there must be a single API call to retrieve this information, otherwise I would wind up doing a *lot* of API calls for my in-house dashboard.

**Comment by adamierymenko** [comment]
The new version has this, but isn't ready for production yet.

**Comment by r04r** [comment]
Great, looking forward to trying that out. Right now I'm getting the list of networks, then requesting each network. Ditto for the members of a network.

**Comment by tartavull** [comment]
+1
