### ISSUE TITLE
Dashboard should show IPv6 addresses

### ISSUE THREAD

**Issue by dharriganlh** [zerotier/ZeroTierOne#415]
Hi,

Just as the network dashboard shows the IPv4 addresses of a member, I believe it would be very useful if IPv6 addresses assigned by nodes could be shown as well. Perhaps ULA and/or GUA - even Link-Local perhaps?

Thanks.

-=david=-

**Comment by adamierymenko** [comment]
Yep. This is web and is part of the next release.

We are getting ready to rev basically everything in the universe. :)

**Comment by dharriganlh** [comment]
Awesome! :+1: Looking forward to it.

**Comment by adamierymenko** [comment]
In ZeroTier central 1.0.0, which is going live in 45 minutes.
