### ISSUE TITLE
Census: steps toward mesh-like routing and privacy improvements

### ISSUE THREAD

**Issue by adamierymenko** [zerotier/ZeroTierOne#416]
(backlog, not for 1.2.0)

1.2.0 will introduce basic upstream designation, which allows what amounts to root federation to eliminate hard dependency on ZT roots. You can designate any node as a trusted upstream peer.

This is also step one toward a more mesh-like networking paradigm that is more fault tolerant and more decentralized and could support some level of meta-data privacy.

The next step is to allow nodes (especially federated upstreams) to report to other nodes (such as roots or *their* upstreams) who they can reach, but not how they can reach them. That way nodes could find paths to hidden nodes, allowing for stealth modes of operation where nodes hide behind their designated upstreams and opt out of the root system. This would also allow hybrid meshnet behavior in which ZT falls back to being a full mesh (slower but more resilient) when roots and upstreams are both unavailable.

But it must be done securely to prohibit sybils and cache poisoning. Otherwise you could DOS a node by falsely attesting reachability.

The current idea is to leverage signatures for this to allow endpoint nodes to control precisely who they approve to route for them. Here's how it would work:

 1. Alice sends a TAKE CENSUS request to Bob. Alice is asking Bob to take a census of the nodes Bob can reach. This request contains a random token to serve as both a unique identifier and an authentication token.

 2. Bob sends a CENSUS FORM to all peers it can directly reach. Let's call them Clyde, Doug, and Emily. This message contains Alice's address and the token originally sent by Alice. Bob also sends an OK(TAKE CENSUS) message to Alice listing all the peers (Clyde, Doug, and Emily) it can reach.

 3. If Clyde, Doug, and Emily approve of Bob as a router to reach them, they send a CENSUS REPORT directly to Alice containing Alice's supplied token. Because all ZT messages are MAC'd, Alice therefore knows that these messages were not forged by Bob and can use the token both to match the request and to authenticate it. Alice can also check Bob's list of reported peers and only include those that have been reported by both Bob and by themselves.

This allows Alice to build an authenticated list of nodes reachable by Bob.

**Comment by aw** [comment]
Could this just be replaced with a TLS handshake and client certificates? It seems like a very similar concept, with the benefit of having already been tested - among other things.

**Comment by adamierymenko** [comment]
Yes, certificates are another way. I was thinking simple. One of our goals is IoT so I want to minimize the amount of heavy crypto required to get routine things done. MAC is cheap.

**Comment by misuzu** [comment]
#380 would also be nice to have for mesh networks.

**Comment by adamierymenko** [comment]
Yes #380 would also be very good for in-data-center SDN use.

**Comment by adamierymenko** [comment]
Closing since CertificateOfRepresentation provides a more manageable and secure way of achieving this kind of thing and opens the door to auto-meshification by federated roots later.
