### ISSUE TITLE
Windows 10 routes with via field set disappearing

### ISSUE THREAD

**Issue by r04r** [zerotier/ZeroTierOne#417]
Using the ZeroTier One client on Windows seems to have the global routes disappear occasionally. This specifically hits me after a reboot, but a reboot is not always necessary for the routes to disappear.

I add a network using `zerotier-cli set $ID allowGlobal=1` which works great for Linux, and for Windows as well at first.

Removing the network, waiting a few moments and adding it back usually resolves the problem, until the next reboot.

In case it matters, my routes are `/32` routes, so for example `8.8.8.8/32`

**Comment by blurredpixel** [comment]
I am seeing this same issue, as well. Glad I'm not the only one having it. It seems to not have the issue on other operating systems, mainly just Windows.

**Comment by adamierymenko** [comment]
Hmm... so you are effectively piecemeal routing certain IPs through ZeroTier? That's a case I'm not sure we've tested, but will do so!

**Comment by blurredpixel** [comment]
So basically I have 3 different sites, each having a virtual gateway that has an interface to zerotier, and a lan and wan interface. I then route between the interfaces with iptables rules, 

So in zerotier, I have 192.168.3.0/24 via 192.168.10.181 
etc. etc.

so for those routes from zerotier to be active after a reboot, I have to leave and re-join the network.

**Comment by r04r** [comment]
> Hmm... so you are effectively piecemeal routing certain IPs through ZeroTier? That's a case I'm not sure we've tested, but will do so!

Yes, that is exactly what I'm doing. Though I'm not sure if I'm doing exactly the same as @blurredpixel 

I have a private lan /24 route which persistently works well, but the global /32 route is the one that randomly disappears.

**Comment by blurredpixel** [comment]
> I have a private lan /24 route (with empty via field) which persistently works well, but the global /32 route (with filled via field) is the one that randomly disappears.

Yeah that's the exact same issue I'm having. My ZT lan is 192.168.10.0/24 with an empty via field, and then all my other routes point to other routers. The non-empty routes disappear, but I can still ping my ZT subnet.

**Comment by r04r** [comment]
So it looks like it doesn't matter whether the route is global or not. So far it seems narrowed down to all routes that have the via field set.

**Comment by blurredpixel** [comment]
On my laptop it seems if I leave the ZT network and put it to sleep, and then rejoin when it wakes up, the routes show up. 

If I leave it connected, put it to sleep, and wake it up the routes are not there. 
Steps I take to resolve this issue:

- Leave network
- Close ZT
-Open services and restart zerotier-one service
-Open zerotier and re-join network

**Comment by adamierymenko** [comment]
I think this is fixed in `dev` and will be fixed with 1.2.0.

**Comment by blurredpixel** [comment]
I'm so excited and I will buy you a virtual beer somehow.

**Comment by r04r** [comment]
I can confirm this seems fixed

**Comment by blurredpixel** [comment]
Can you provide your testing steps so I can test, as well? I was trying with 1.1.17 last night and it stopped advertising routes all together.

**Comment by glimberg** [comment]
@blurredpixel The fix came after the 1.1.17-pre 1.2.0 beta was released.  It's in the dev branch, but a compiled release has not been put out

**Comment by blurredpixel** [comment]
@glimberg  ah okay that makes sense. I've only ever compiled ZT on Linux.
