### ISSUE TITLE
VyOS support? (Debian fork)

### ISSUE THREAD

**Issue by adamierymenko** [zerotier/ZeroTierOne#418]

**Comment by nate8199** [comment]
Would this be an internal interface in VyOS?  any chance of something similar in pFsense?

**Comment by Arffeh** [comment]
Nate, come join us at https://forum.pfsense.org/index.php?topic=102404.0
For a pfsense zerotier package :D

**Comment by blurredpixel** [comment]
Arffeh, I've followed that thread for awhile. I've been using ClearOS for my Zerotier edge routers. I had to setup it all up manually, but since it's Debian based, it installs with their install script super easily. It's the only "router distro" that ZeroTier works with out of the box.

**Comment by 007au** [comment]
the PFSense package is all released into the wild and working.

**Comment by adamierymenko** [comment]
It's Debian "squeeze" based. Added that and now it should work (in next version).

**Comment by jdrews** [comment]
@adamierymenko Looks like the VyOS guys tried to link up with your team to get this working but you didn't respond. Any chance you could respond? Looks like they need some assistance in getting ZeroTier integrated. 

https://phabricator.vyos.net/T465

**Comment by jdrews** [comment]
I did some investigation on how ZeroTier would work on a VyOS box. Running into some problems getting the VyOS console to pick up the interfaces. I'm talking to the VyOS maintainers for help over here: https://phabricator.vyos.net/T465#18733

**Comment by jothoma1** [comment]
@jdrews @adamierymenko it would be great to see zerotier on VyOS !!

**Comment by jdrews** [comment]
ZeroTier was added to the Ubiquiti EdgeRouter (which runs a vyatta fork) as a demo. Relevant to this thread:
https://blog.kruyt.org/zerotier-on-edgerouter-p2/

**Comment by incube8r** [comment]
@jdrews the Part 1 of that blog uses Firmware version 2.0.8, and this Part 2 uses Firmware version 2.0.8 does it mean the 

https://github.com/dkruyt/resources/raw/master/zerotier-edgeos.tgz

does not work with 2.0.8 only the older firmware?

**Comment by theonemcdonald** [comment]
Can the ZT team please reach out to the VyOS guys and discuss integration?
