### ISSUE TITLE
Devices disappear and show offline

### ISSUE THREAD

**Issue by blurredpixel** [zerotier/ZeroTierOne#419]
I had 14 devices in my network, and now it's down to 4 with none online. Has anyone else experienced this? Could it be related to the outage in November?

**Comment by blurredpixel** [comment]
As a follow-up, I've deleted the original network and created a new one. I've started adding devices to it, but none are showing up automatically. I changed IP subnets completely for this network. I had to manually add the device IDs for them to show up. They show up as offline under ZT Central.

**Comment by blurredpixel** [comment]
![editedzt](https://cloud.githubusercontent.com/assets/12002376/21013700/19e658ba-bd29-11e6-804f-d4acecd0a7fe.png)

**Comment by adamierymenko** [comment]
I believe this is fixed. It was a web issue, so closing here.

**Comment by blurredpixel** [comment]
I'm now seeing no devices on the web, but traffic and hosts are still connected.

**Comment by adamierymenko** [comment]
Hit refresh... do you still not see them?

**Comment by adamierymenko** [comment]
The new web UI updates more dynamically but the existing one requires a refresh to show new members, etc.

**Comment by blurredpixel** [comment]
I just tried from a different browser and still nothing. 

![zt2](https://cloud.githubusercontent.com/assets/12002376/21023102/1a724d60-bd4d-11e6-8ea4-5d586aa6fa48.png)

**Comment by adamierymenko** [comment]
Seems fixed now... I re synced the controller DB with the web backend. Investigating to make sure there are no others with this issue.

**Comment by blurredpixel** [comment]
Yep that did it! Thanks for your help, it is much appreciated!
