### ISSUE TITLE
Managed route (not default gateway) not working for Android

### ISSUE THREAD

**Issue by RatedDS** [zerotier/ZeroTierOne#420]
I have set up a network using 172.16.28.0/24 and have connected a router running OpenWrt with IP 172.16.28.8.The router is connected to the 10.0.5.0/24 LAN, which I want to be able to access from other devices connected to the ZeroTier network, so I set up a route for 10.0.5.0/24 via 172.16.28.8.If I connect from my PC or Raspberry Pi the route gets pushed and I can access the network, but it doesn't seem to work in my Android Phone even if I add the route manually.

I read that Android doesn't support default route override, but I don't know if it should work with "normal" routes.

**Comment by glimberg** [comment]
Managed and default route support is coming for iOS and Android with the 1.2.0 release.

**Comment by mkruyswijk** [comment]
Hi @glimberg 
is there any idea when 1.2.0 will be released?
kind regards
maarten

**Comment by glimberg** [comment]
Beta is up now in the google play store.  Follow this link if you'd like to access it:  https://play.google.com/apps/testing/com.zerotier.one

**Comment by mkruyswijk** [comment]
Can't wait for the IOS version :)

**Comment by glimberg** [comment]
@mkruyswijk shoot us an email at contact@zerotier.com and we can get you added to the iOS TestFlight beta

**Comment by mkruyswijk** [comment]
Done! thanks!

**Comment by jdrews** [comment]
I gave the new beta Android app a try. It worked great for managed routes.

I don't have zerotier setup with a default route in my deployment so I can't test that.

**Comment by jdrews** [comment]
There was two strange behaviors that did not affect functionality. But they may cause user confusion. 

1. Cannot add a network (via + button) until the user clicks connect button at bottom. A user would expect to add the network before they connect, right? Not sure why you have to click connect first... This is a common complaint on Google Play for the Android app. 

2. After joining a network, the key icon shows up in androids top task bar (near clock) showing that we are connected to a VPN. However if I leave the network, this icon is still present. Then if I click disconnect the icon is still present. I have to go to settings -> VPN and disconnect zerotier before this key icon disappears

Using Android 7.0 on a Nexus 6.

**Comment by Arffeh** [comment]
Just chiming in on something I've noticed. after upgrading from android 6.x to 7.1, downloads (Download Manager) refuses to work unless I completely disconnect from my ZT1 network.
After disconnecting, Download Manager is fine again.

**Comment by adamierymenko** [comment]
@Arffeh what Android version?

**Comment by adamierymenko** [comment]
Is this still happening with the latest?

**Comment by alpharde** [comment]
I still cannot see managed routes, only the default route for tun0, so this is not fixed.
Do I need something else for it to work? If not, please reopen.
