### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by r04r** [zerotier/ZeroTierOne#421]
I see a lot of mentions of the 1.2.0 release on the tracker, blog, etc. I was just wondering if there was any kind of roadmap? Would love to know what's coming and how it's coming along.

**Comment by adamierymenko** [comment]
We're in testing right now. The `dev` branch is 1.2.0 to be. We're targeting before Christmas for a release, so at this point a big road map post would be moot.

**Comment by r04r** [comment]
I saw [the blog](https://www.zerotier.com/blog/) has some juicy details which satisfy my curiosity, so I'll be closing this issue :)
