### ISSUE TITLE
Client on network1 can't connect client on another network

### ISSUE THREAD

**Issue by bruno-imasdetres** [zerotier/ZeroTierOne#422]
I don't know if this is possible using "Managed routes" (I can firnd any doc how to use it).

I want to add special clients to "Net1" (range 172.30.1.1-172.30.1.254) and the rest of them to "Net2" (range 172.30.2.1-172.30.2.254). Now I want to allow clientes from "Net1" (say 172.30.1.31) to connect to any client on "Net2" (say 172.30.2.66).

Is this possible now with any kind of configuration?

Very thanks in advance and best regards!

**Comment by adamierymenko** [comment]
You could set up a router between the two nets and create managed routes, but that's ugly. This sort of thing would be a lot easier after 1.2.0 release using our rules engine. Closing for now since this isn't an issue per se.
