### ISSUE TITLE
Is 1.1.17 a 'stable' release in its own right, or is it 1.2.0-beta?

### ISSUE THREAD

**Issue by jonathonf** [zerotier/ZeroTierOne#425]
Basically, pick a side. 😝 

I can't tell if 1.1.17 is also a stable release of the 1.1 series. For example, while there's no pre-release tag on the releases page there isn't yet an updated Linux package in the ZT repos (at least for jessie and xenial).

If it's 1.2.0-beta it would make sense to label it as such, rather than being a point-release/bugfix-release of the 1.1 series.

**Comment by glimberg** [comment]
1.1.17 is not a stable release of the 1.1 series.  Thats why there's no official distributions for linux, and the only links for the Windows & Mac packages are in the blog post.

**Comment by jonathonf** [comment]
Great, thanks for the clarification.

If you do future releases in a similar way, could you please look at how you increment version numbers? Having an unstable release numbered as a point-release breaks, for example, the fairly well-established 'semantic versioning' scheme: http://semver.org/

**Comment by adamierymenko** [comment]
Our current scheme is this:

Major (1): we only increment this when a significant change happens that may impact future protocol backward compatibility.

Minor (2): incrementing this indicates a major milestone release that may add or modify core functionality.

Revision (17): odd revisions are development or beta releases, even are official stable releases.

**Comment by jonathonf** [comment]
Right. Well, my question has been answered. :)
