### ISSUE TITLE
ZT versions between dev & pre-release

### ISSUE THREAD

**Issue by jungle-boogie** [zerotier/ZeroTierOne#426]
Hello,

On machine A:
```
% bin/ZeroTierOne/zerotier-cli -v
1.1.15
```

On machine B:
```
$ bin/ZeroTierOne/zerotier-cli -v
1.1.15
```

Both are from the dev branch and compiled identically. 

In https://my.zerotier.com, the top one (machine a) the version displayed is 1.1.17 and on machine b the version displayed is 1.1.15.

Machine A is registered in both https://my.zerotier.com and http://my-beta.zerotier.com

What's the most recent version: 1.1.15-dev or 1.1.17-pre?

Thanks!

**Comment by adamierymenko** [comment]
1.1.17 is the latest, and is a bit of a moving target (though we did tag one for beta before the holidays).

Scheme is:

Odd revision: BETA or dev

Even revision: RELEASE
