### ISSUE TITLE
mosh connections?

### ISSUE THREAD

**Issue by jungle-boogie** [zerotier/ZeroTierOne#427]
Hello,

What's the trick to get mosh working with ZT?

I'm using the android app called juicessh: https://play.google.com/store/apps/details?id=com.sonelli.juicessh
along with the ZT app: https://play.google.com/store/apps/details?id=com.zerotier.one

A system at home is running version 1.1.15-dev of ZT and connected to a network I created; the phone is also connected to the same network and yet, I can't establish a mosh connection to the system at home. 

On https://my.zerotier.com, I have the box checked that says "Allow Any Protocol" and I can establish a connection this way:
**machine A** version 1.1.15-dev of ZT to **machine B** version 1.1.15-dev of Z:
`mosh user@10.147.17.201`

Juice attempts to make the connection, but dies shortly after 'connecting' because it doesn't see any response. I see mosh server starting up on machine A and B, but that's all.

Is this a problem with juice itself, something in zerotier's backend, desktop app or mobile app, or mosh?

Thanks!

**Comment by adamierymenko** [comment]
Can you ping hosts over the ZT virtual network? If so it's probably not a ZT problem.

**Comment by jungle-boogie** [comment]
Sorry, forgot this was still open.

Mosh + zerotier work great and are a great pair.

mosh with juicessh and ZT is a problem but I haven't heard from the developers yet.
