### ISSUE TITLE
SIOCGIFADDR doesn't detect all IP addresses on Linux

### ISSUE THREAD

**Issue by zielmicha** [zerotier/ZeroTierOne#430]
For example, in configuration like this:
```
auto eth0:0
iface eth0:0 inet static
	address XXX
        gateway XXX
```
ZeroTier doesn't detect any address, so it won't attempt any UDP communication on eth0 interface. I'm working on a patch for this.

**Comment by adamierymenko** [comment]
Fixed by PR, thanks!
