### ISSUE TITLE
Unable to read ZeroTier One authtoken on 1.1.17

### ISSUE THREAD

**Issue by Tinytimrob** [zerotier/ZeroTierOne#432]
I'm trying to migrate from Hamachi to ZeroTier.

Two of my users so far have reported the issue of "Unable to read ZeroTier One authtoken" when opening the GUI on version 1.1.17. Neither of them were able to get this version working. One is my brother's computer (Win7 x64) and the other is a computer owned by one of my associates (Win10 x64). For both of those users the stable release 1.1.14 was working OK (other than the previously known and fixed issues with the Windows adapter). I've also installed 1.1.17 on several other systems without encountering this issue.

I spent about an hour trying to mess around with disk permissions and tried everything including giving the authtoken and its containing directory R/W access by 'Everyone' but wasn't able to find any solution or obvious reason why the authtoken was not readable. Running the GUI as an administrator also did not fix the issue.

The only thing I found which may be related is that the username on both systems which were broken contains a space. None of the working systems have a space in their usernames. Although this could plausibly be a coincidence.

**Comment by glimberg** [comment]
It could be due to a space in the username.  I'll check into it.  Thanks for the report.

**Comment by glimberg** [comment]
Just to be clear, the path to the home directory is something along the lines of `/Users/firstname last name/`?

**Comment by Tinytimrob** [comment]
Yes

**Comment by Tinytimrob** [comment]
Although it's on Windows so the path started C:\Users\.

**Comment by glimberg** [comment]
OK.  I've got this fixed internally.  It was an issue with the space in the path.

**Comment by Tinytimrob** [comment]
That's great news, I hope to see this fix in a release of ZeroTier soon 👍

**Comment by adamierymenko** [comment]
Closing since fixed in `dev`
