### ISSUE TITLE
unable to leave 8056c2e21c000001[bug?]

### ISSUE THREAD

**Issue by sequencer** [zerotier/ZeroTierOne#435]
Find in `OpenWrt Chaos Calmer 15.05.1`
tried to `zerotier-cli leave 8056c2e21c000001`
tried to `rm -rf /tmp/lib/zerotier-one/networks.d/8056c2e21c000001.conf`
everytime i start it I should type `zerotier-cli leave 8056c2e21c000001`

**Comment by zielmicha** [comment]
Look at `/etc/config/zerotier`. The configuration for ZeroTier is stored there, `/tmp/lib/zerotier-one/networks.d/` etc is generated from it on every boot.
