### ISSUE TITLE
Android Beta for 1.1.17 (1.2.0 beta) - Very slow speeds when using Full Tunnel/Gateway?

### ISSUE THREAD

**Issue by xcellardoor** [zerotier/ZeroTierOne#437]
Hello Developers,

I use one of my VPS' as a gateway and when using my laptop it works amazing, very little to no reduction in throughput. I'll put about 40Mb/s, for example, which is accurate. For some reason when using my phone or tablet and the new 'full tunnel' mode, I'll only pull something insane like 60KB/s which is way lower than 1Mb.

Has anyone else had similar problems? I will say though that it is the new 1.1.17 client against the last stable release of ZT, so they gateway and Zerotier.com are not on the beta...

Happy to run any and all tests.

**Comment by glimberg** [comment]
There's an issue with current 1.1.17 client that's in the beta stream on the app store.  It tears down and reconfigures the tunnel adapter quite often which can definitely reduce throughput drastically.  I have the issue fixed internally, but haven't pushed it up into the Google Play Store Beta stream yet.

**Comment by xcellardoor** [comment]
Okeydokey, thanks very much for the quick feedback and for making the app in the first place. Damned good service.

If you're after some alpha-testing, send an APK by all means.

**Comment by glimberg** [comment]
I just pushed up a new build in the Android beta channel.  Let me know if it works better for you.
