### ISSUE TITLE
IRC channel abandoned?

### ISSUE THREAD

**Issue by r04r** [zerotier/ZeroTierOne#438]
It seems the IRC channel is abandoned? Perhaps update the channel topic (currently: `⏁ support channel`) to direct users to create a ticket on the github, as there seems to be no other support venue. An example from the IRC channel (I am not haploid, don't know who they are) that I've noticed which went unanswered:

```
<haploid> Is there any known way of getting more verbose information out of zerotier-cli? We are getting "0 join connection failed" and no additional details
<haploid> We are a paid customer but it looks like there's no actual support ticketing system, so we're trying irc.
<haploid> Ok, so is it safe to assume there is no realistic hope for support response? Would we need to upgrade to enterprise plan in order to have access to support?
<haploid> Can someone at least give us an estimate for how long one can expect a response from contact@zerotier.com?
<haploid> Ok well this is very urgent, so we have no choice but to upgrade to enterprise and hope for the best. Problem is that in the account portal, there doesn't appear to be any way of upgrading. It displays "Subscription
<haploid> [ ZeroTier Basic ]    "
<haploid> but no option to change that to Enterprise
```

Though as someone who is thinking of soon becoming a paying customer, this does raise some questions.

**Comment by adamierymenko** [comment]
We just set up a Slack<>IRC bridge that will let us see when people are on the channel and allow us to chat via Slack if we are not on IRC.

It's neat, check it out!

https://github.com/ekmartin/slack-irc
