### ISSUE TITLE
[RFC] allowManaged for specific IP networks

### ISSUE THREAD

**Issue by zielmicha** [zerotier/ZeroTierOne#440]
Sometimes, I don't trust the person having control over the network settings - I'd like to able to restrict the IPs that can by assigned by the network controller to the local `ztX` device. 
I would like to implement an extension to the current `allowManaged` syntax which would limit which IPs can be assigned and which routes can be added. For example:
```
# only allow addresses from 10.1.0.0/16 and 10.2.0.0/16 networks
allowManaged=10.1.0.0/16,10.2.0.0/16
```
(The same would apply to allowGlobal)

**Comment by adamierymenko** [comment]
Hmm... interesting. I could see this being nice. Let's wait a bit but I'd like to add to backlog. Don't do it against master since that code has changed a bit.
