### ISSUE TITLE
FreeBSD/ARM: Undefined symbol "__aeabi_uldivmod"

### ISSUE THREAD

**Issue by jungle-boogie** [zerotier/ZeroTierOne#441]
Hi All,

So I was able to build without any errors on freebsd -current (12 head) but when attempting to run
`zerotier-one -d` this happens:
```
% sudo ./zerotier-one -d
Password:
/home/freebsd/bin/ZeroTierOne-dev/zerotier-one: Undefined symbol "__aeabi_uldivmod"
```

Building on beagle bone back with gcc49 and gmake with this compile option:
`gmake CXX=g++49 CC=gcc49`

Any clues?

**Comment by adamierymenko** [comment]
Not sure... we've only tried FreeBSD on AMD64. This could be some kind of ARM architecture setting issue.

**Comment by jungle-boogie** [comment]
Hi @adamierymenko,

This commit builds and runs without issues on the BBB:
https://github.com/zerotier/ZeroTierOne/commit/35174a8766471db92528f7ba2877e7f07ea8ed52
(built with just `gmake`)

This commit builds but fails with what I reported above:
https://github.com/zerotier/ZeroTierOne/commit/3b0969e3a5ff3ca37832446b2647e9fbf81fddbc
(built with `gmake CXX=g++49 CC=gcc49`)

**Comment by jungle-boogie** [comment]
Any suggestions on what would be the cause?

**Comment by hellyberry** [comment]
ARM (and MIPS,..) support is very important for IoT-security in my opinion.

**Comment by adamierymenko** [comment]
Hmm... no, unfortunately not and we don't have a FreeBSD/ARM device to test. We do have some extra pi's so when I get back to LA maybe I'll hook one up. I did play with FreeBSD/ARM a while ago and I remember it working but it's been some time. (in SF right now)

Did find this... not sure if it's relevant but I just googled the symbol. Maybe we will need to include a stub.

https://codereview.chromium.org/5302007/

**Comment by jungle-boogie** [comment]
@adamierymenko,

It was working just up to commit https://github.com/zerotier/ZeroTierOne/commit/3b0969e3a5ff3ca37832446b2647e9fbf81fddbc which is where you made many changes for gcc49

**Comment by adamierymenko** [comment]
Is this still happening?

**Comment by jungle-boogie** [comment]
I'm building again and I'll know soon.

**Comment by jungle-boogie** [comment]
yes.

./zerotier-one
/home/freebsd/bin/ZeroTierOne/zerotier-one: Undefined symbol "__aeabi_uldivmod"

**Comment by adamierymenko** [comment]
Still happening in 1.2.4? `dev` branch? Unfortunately we don't have a FreeBSD/ARM device to test with. If you want to take a shot at it, do a PR against the `dev` branch.

**Comment by jungle-boogie** [comment]
hi @adamierymenko,

Something happened to my BBB uboot partition, and I can't load freeBSD onto it. I'll close this issue in hopes that the good work you've done recently corrected the build.
