### ISSUE TITLE
No devices are pulling IP addresses

### ISSUE THREAD

**Issue by blurredpixel** [zerotier/ZeroTierOne#444]
None of my ZT clients are pulling managed IPs anymore. Web GUI says they're online and have IPs, but they're all showing up blank on each client. Leaving and re-joining hasn't solved the issue.

**Comment by blurredpixel** [comment]
Update: It seems to only be my ZT network as I created a new one and it pulled an IP address fine.

**Comment by adamierymenko** [comment]
Hmm... this is on the live site right? If so we're going to be upgrading everything there very soon.

**Comment by blurredpixel** [comment]
@adamierymenko yeah it was on the live site. I just created a new network and switched everything over to it so i'm good to go. Excited for 1.2!
