### ISSUE TITLE
Android client - "Join Network" is greyed out

### ISSUE THREAD

**Issue by Sageth** [zerotier/ZeroTierOne#446]
I'm using a Google Pixel phone and am unable to "Join Network" because it's greyed out.  This occurs on cellular or wifi, but works on my tablet in landscape mode only.  This issue also affected my previous phone (Nexus 6).

This seems to be a UI issue, so I'm not sure I can provide any specific logs.  Please let me know if there is more information that I can provide to help troubleshoot.

**Comment by glimberg** [comment]
It sounds like you haven't hit the Connect button in the lower right corner of the screen yet.  Once the status shows as Online, the join network button will be enabled.

We have plans to update the UI in the future to make things a bit more intuitive.

**Comment by Sageth** [comment]
Hi, thanks for your reply. I am on cellular at the moment and confirmed that I have "Enable Cellular Data" checked in the client settings.  Clicking connect keeps me offline and shows no error or feedback on why. I also tried connecting to wifi and had the same experience.  Any other ideas?

**Comment by adamierymenko** [comment]
What cell network are you on? Does it work on WiFi?

**Comment by Sageth** [comment]
Hi - it does not work on WiFi (again, only on my Pixel and Nexus 6 -- it works on my Pixel C tablet).  I clear the Connect button 'click' but I remain offline. 

I am currently using Google Fi, but as I am on WiFi now, I don't _think_ it's about the cellular network.

**Comment by Sageth** [comment]
Just wanted to update this as I've been trying to figure this out for months.  Using Google Fi (I'm not sure if it's Fi-specific or if it's to Google phones in general), there is an option in Settings -> More -> VPN -> WiFi Assistant.  That was set to "Always on VPN."  As soon as I turned that off, ZeroTier was able to connect. 

Issue resolved.  Hope it helps someone else.

**Comment by soakes** [comment]
I am also having the same problem running Nexus 6P on Android N version 7.1.2 which is the latest non-beta.  

I have tried to do landscape mode as suggested as well as togged on/off the Always on VPN (mine was off initially) and this has not helped.  I have also cleared cache/data as well as uninstalled and reinstalled and neither has helped.

Does anyone have any further ideas?

![screenshot_20170620-233421](https://user-images.githubusercontent.com/813389/27359244-a9819f66-5612-11e7-8e0a-f4712077bac8.png)

**Comment by soakes** [comment]
Found a work around, switched to 4G, then it came online and then allowed me to enter network ID.

**Comment by Soren-Nordstrom** [comment]
I'm actually having this same issue right now, LG G5 Android 7.0.  None of the aforementioned solutions have worked.

**Comment by bertramforer** [comment]
same issue...

**Comment by jddcef** [comment]
The network ID is the longer ID, not the shorter 8 digit one which is the machine's ID or My Address. I confused the two at the beginning, causing the connect button to just stay grayed out.
