### ISSUE TITLE
Windows driver code compile

### ISSUE THREAD

**Issue by SanjayC** [zerotier/ZeroTierOne#447]
I try to compile windows source using vs2012+wdk8 on win7, but driver sys can not install on win server 2008 r2 x64. I ask for your advice  about my question.
  1, what'is the vs and wdk version?
  2, have some special configue for muti targets

Thank you

**Comment by adamierymenko** [comment]
Hmm... most recently we used Visual Studio 2015 and WDK 10.

**Comment by SanjayC** [comment]
OK,thks, i will try it
