### ISSUE TITLE
zerotierone doesn't create dev zt0 on Centos 7

### ISSUE THREAD

**Issue by amosbird** [zerotier/ZeroTierOne#448]
zerotier-one is installed via `curl -s https://install.zerotier.com/ | bash`.

**Comment by glimberg** [comment]
Have you joined a network?  There's a `/dev/zt*` device created for each network joined.

**Comment by amosbird** [comment]
Thanks @glimberg 

join gives `0 join connection failed`.

Here is the output of listnetworks.
```
0 listnetworks invalid JSON response (parse error - unexpected 'c')
```

udp 9993 port is open and firewall is down.

**Comment by janjaapbos** [comment]
Sounds like the service is not running.

As root try: service zerotier-one restart

And watch for errors. Also check with ps -ax|grep zerotier-one to see if the process is there.

**Comment by amosbird** [comment]
zerotier-one is running. I even did a `strace -f` which gave [this](https://paste.wentropy.com/kDjm)

**Comment by janjaapbos** [comment]
Ok. The trace looks normal. The network timeouts could be regular (e.g. if you're not IPv6 connected). Could you verify the service interface is working? 

E.g. check the the result of:
run as root: zerotier-cli info

If that gives an error, do a telnet to local port 9993. E.g. something like this:

telnet 127.0.0.1 9993
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
GET /networks

HTTP/1.1 401 Unauthorized
Cache-Control: no-cache
Pragma: no-cache
Content-Type: text/plain
Content-Length: 0
Connection: close

Connection closed by foreign host.

**Comment by amosbird** [comment]
zerotier-cli info yields `0 info invalid JSON response (parse error - unexpected 'c')`

telnet shows the same result you gave,
```
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
GET /networks

HTTP/1.1 401 Unauthorized
Cache-Control: no-cache
Pragma: no-cache
Content-Type: text/plain
Content-Length: 0
Connection: close

```

**Comment by janjaapbos** [comment]
As root do the following:

curl -H "X-ZT1-Auth: $(cat /var/lib/zerotier-one/authtoken.secret)" http://localhost:9993/status

Does that give a valid json response?

**Comment by amosbird** [comment]
yes,
```
{
	"address": "b1f83f2aac",
	"publicIdentity": "b1f83f2aac:0:7f12c46f5d999c59bff6326e545fe610acdd1a40002af5e068ca0ade323fcb5b1e5e15490bb23f14dc7a0f985d102c1159ca882d46effde65a7460aa66ef2473",
	"worldId": 149604618,
	"worldTimestamp": 1452708876314,
	"online": true,
	"relayPolicy": "trusted",
	"tcpFallbackActive": false,
	"versionMajor": 1,
	"versionMinor": 1,
	"versionRev": 17,
	"version": "1.1.17",
	"clock": 1487667042256,
	"cluster": null
}
```

**Comment by janjaapbos** [comment]
Ok. But I see version 1.1.17, while above you mentioned that you installed zerotier with curl -s https://install.zerotier.com/ | bash

As far as I know, that would install 1.1.14 and not a development version.

I think you have a broken (mixed) install.
If you verified that, you can reinstall as follows.

To reinstall, first cleanup: 

service zerotier-one stop

yum remove zerotier-one

Then remove possible leftovers:
rm -rf /var/lib/zerotier-one
rm -f /usr/sbin/zerotier*

Then install current stable:
curl -s https://install.zerotier.com/ | bash

**Comment by amosbird** [comment]
well, I thought I should mention more about the versioning stuff :smiley: 

I've tried `curl -s https://install.zerotier.com/ | bash` first. After failing that, I gave `1.1.7` version a shot. Well, this still doesn't work.

**Comment by janjaapbos** [comment]
I installed it on a clean Centos 7 image and it worked ok. Installing gave met the following output:

[root@centos7 ~]# curl -s https://install.zerotier.com/ | bash

*** ZeroTier One Quick Install for Unix-like Systems

*** Supported targets for this script:
***    MacOS (10.7+) on x86_64 (just installs ZeroTier One.pkg)
***    Linux / Debian (wheezy or newer) on i386, x86_64, and armhf (Raspbian/jessie only)
***    Linux / Ubuntu (trusty or newer) on i386 and x86_64
***    Linux / SuSE (12+) on i386 and x86_64
***    Linux / CentOS (6+) on i386 and x86_64
***    Linux / Fedora (22+) on i386 and x86_64
***    Linux / Amazon (2016.03+) on x86_64

*** Please report problems to contact@zerotier.com and we will try to fix ASAP!

*** Detecting Linux Distribution

*** Found RHEL/CentOS, creating /etc/yum.repos.d/zerotier.repo

*** Installing zerotier-one package...
Loaded plugins: fastestmirror
base                                                           | 3.6 kB  00:00:00
extras                                                         | 3.4 kB  00:00:00
updates                                                        | 3.4 kB  00:00:00
zerotier                                                       | 2.9 kB  00:00:00
(1/5): extras/7/x86_64/primary_db                              | 121 kB  00:00:00
(2/5): base/7/x86_64/group_gz                                  | 155 kB  00:00:00
(3/5): zerotier/7/primary_db                                   | 3.8 kB  00:00:00
(4/5): updates/7/x86_64/primary_db                             | 2.2 MB  00:00:00
(5/5): base/7/x86_64/primary_db                                | 5.6 MB  00:00:02
Determining fastest mirrors
 * base: ftp.ciril.fr
 * extras: centos.mirrors.ovh.net
 * updates: centos.mirror.fr.planethoster.net
Resolving Dependencies
--> Running transaction check
---> Package zerotier-one.x86_64 0:1.1.14-0.1.el7.centos will be installed
--> Finished Dependency Resolution

Dependencies Resolved

======================================================================================
 Package             Arch          Version                      Repository       Size
======================================================================================
Installing:
 zerotier-one        x86_64        1.1.14-0.1.el7.centos        zerotier        267 k

Transaction Summary
======================================================================================
Install  1 Package

Total download size: 267 k
Installed size: 736 k
Downloading packages:
zerotier-one-1.1.14-0.1.el7.centos.x86_64.rpm                  | 267 kB  00:00:00
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : zerotier-one-1.1.14-0.1.el7.centos.x86_64                          1/1
  Verifying  : zerotier-one-1.1.14-0.1.el7.centos.x86_64                          1/1

Installed:
  zerotier-one.x86_64 0:1.1.14-0.1.el7.centos

Complete!

*** Enabling and starting zerotier-one service...
Created symlink from /etc/systemd/system/multi-user.target.wants/zerotier-one.service to /usr/lib/systemd/system/zerotier-one.service.

*** Waiting for identity generation...

*** Success! You are ZeroTier address [ 8d24352e35 ].

[root@centos7 ~]# zerotier-cli info
200 info 8d24352e35 ONLINE 1.1.14

**Comment by amosbird** [comment]
Well, here is what I got,
```
Loading mirror speeds from cached hostfile
 * epel: mirrors.neusoft.edu.cn
 * epel-debuginfo: mirrors.neusoft.edu.cn
 * sl-softwarecollections: ftp.scientificlinux.org
 * sl-softwarecollections-debuginfo: ftp.scientificlinux.org
Resolving Dependencies
--> Running transaction check
---> Package zerotier-one.x86_64 0:1.1.14-0.1.el7.centos will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===============================================================================================================================================================================================================================================
 Package                                                   Arch                                                Version                                                             Repository                                             Size
===============================================================================================================================================================================================================================================
Installing:
 zerotier-one                                              x86_64                                              1.1.14-0.1.el7.centos                                               zerotier                                              267 k

Transaction Summary
===============================================================================================================================================================================================================================================
Install  1 Package

Total download size: 267 k
Installed size: 736 k
Downloading packages:
zerotier-one-1.1.14-0.1.el7.centos.x86_64.rpm                                                                                                                                                                           | 267 kB  00:00:07     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : zerotier-one-1.1.14-0.1.el7.centos.x86_64                                                                                                                                                                                   1/1 
  Verifying  : zerotier-one-1.1.14-0.1.el7.centos.x86_64                                                                                                                                                                                   1/1 

Installed:
  zerotier-one.x86_64 0:1.1.14-0.1.el7.centos                                                                                                                                                                                                  

Complete!

*** Enabling and starting zerotier-one service...
Created symlink from /etc/systemd/system/multi-user.target.wants/zerotier-one.service to /usr/lib/systemd/system/zerotier-one.service.

*** Waiting for identity generation...

*** Success! You are ZeroTier address [ b1f83f2aac ].

[root@office ~]# zerotier-cli info
0 info 
```

**Comment by janjaapbos** [comment]
Wow. This is a persisting thing...

Does this work?
/usr/sbin/zerotier-cli -j info

**Comment by amosbird** [comment]
No, it gives the same result.

**Comment by adamierymenko** [comment]
What's in `/var/lib/zerotier-one`? Maybe for some reason the files are elsewhere?

**Comment by amosbird** [comment]
```
[root@office ~]# ls /var/lib/zerotier-one
authtoken.secret  controller.d  identity.public  identity.secret  zerotier-cli  zerotier-idtool  zerotier-one  zerotier-one.pid  zerotier-one.port
[root@office ~]# 
```

**Comment by adamierymenko** [comment]
Are you running SELinux? Maybe it's disallowing something zerotier-cli is doing.

**Comment by amosbird** [comment]
No, it's disabled.

**Comment by adamierymenko** [comment]
Hmm... so `http://127.0.0.1:9993/` works but CLI doesn't. Is that right?

**Comment by amosbird** [comment]
well, curl test works. dev zt0 never shows up.

**Comment by adamierymenko** [comment]
are there any .zeroTierAuthToken files in /root ?

**Comment by amosbird** [comment]
@adamierymenko No, no file has a name containing subtring `zerotier` in /root.

**Comment by amosbird** [comment]
Hmm, I tested two more machines. One with openvpn installed ( service is stopped) , the other not. The one installed openvpn has the same problem I encountered before while the other works fine.

**Comment by glimberg** [comment]
Is OpenVPN installed and configured as a server or a client?

**Comment by amosbird** [comment]
It's acting as an openvpn server.  CentOS 6 also faces the same issue.
