### ISSUE TITLE
[RFC] Make sure ZT networks are up, before continuing startup

### ISSUE THREAD

**Issue by makersphereLabs** [zerotier/ZeroTierOne#451]
As described in PR #450 , `systemd` (tested on **Ubuntu 16.04**) starts `zerotier-one.service` without any problems but does not wait for the ZT networks to become available. This is especially annoying when you're binding to a specific `zt* interface` using e.g. SSH or Docker.

**Comment by atommixz** [comment]
U can add easy hack in service files where u want zerotier
```
Restart=always
RestartSec=10
```
It will be always restart service if it is not starts properly.

**Comment by adamierymenko** [comment]
Will check out the PR, thanks! This would be a nice feature.

**Comment by makersphereLabs** [comment]
@atommixz Yeah, your hack works for **some services but unfortunately not for all**... (like #450). Services like e.g. _Docker_, don't fail (in a systemd way), if a container cannot be started properly.

@adamierymenko Yey! Feel free to improve/comment the PR. ✌️

**Comment by zielmicha** [comment]
I think this should be optional feature. For example, network controller being not available should not halt whole boot.

**Comment by makersphereLabs** [comment]
@zielmicha Well, this tweak **doesn't check if a network controller is reachable**.
It just makes sure that the _virtual network interfaces_ are available.

Although, it's not really clear if these virtual interfaces `zt0, zt1, etc.` are added **before or after** ZeroTier One successfully contacted the root/controller nodes. If so, you would be kinda right.
Maybe @adamierymenko can tell us more. 😅

**Comment by adamierymenko** [comment]
Closing since this is something that should really be handled via systemd, the OS, or other scripts/daemons and not ZeroTier itself.
