### ISSUE TITLE
ZeroTier extremely slow on Android (1.2.0 full release) 

### ISSUE THREAD

**Issue by xcellardoor** [zerotier/ZeroTierOne#452]
Hi again!

I've got the official version now and using the fully routed methodology. Works fine on my desktop but on my phone the speed is coming down at 40kB/s max.... This is on both LTE and WiFi.

Is there anything going on that might cause this? Happy to do lots of diagnostics and debugs!

**Comment by PtDragon** [comment]
Hello! I have same problem with 1.2.4-5. Maximum i get is 256kB/s(very short bursts) and main is around 30-40kB/s. 
Did not test on LTE, only WiFi and WiFi+vpn on router. 
Looks like packet decoding takes lot of CPU time on Android.

**Comment by glimberg** [comment]
Fixed in current Beta release
