### ISSUE TITLE
member listing on 1.2 broken

### ISSUE THREAD

**Issue by trobotham** [zerotier/ZeroTierOne#460]
I converted my controller to 1.2 however, the network member listing (which worked pre-1.2) now appears to be broken:

root@zt:/var/lib/zerotier-one# curl -H "X-ZT1-AUTH: $(cat /var/lib/zerotier-one/authtoken.secret)" 127.1:9993/controller/network/43......./members
{}

**Comment by pkpowell** [comment]
Same here. 
One can edit members once they've joined and you know their id, but `http://127.0.0.1:9993/controller/network/xyz/member` always remains empty.

**Comment by adamierymenko** [comment]
Yes this is a bug. You can list the directory under controller.d for now. :(
