### ISSUE TITLE
multicast issues with 1.2.0

### ISSUE THREAD

**Issue by grawity** [zerotier/ZeroTierOne#461]
As I was upgrading some of my hosts to 1.2.0, I noticed that they cannot send multicast packets anymore – everything seems to just disappear into the ether.

 My network currently has 5 active nodes (7 total), "multicast limit" is set to 32, and the only flow rule is `accept`. Yet, multicast packets sent from 1.2.0 nodes never show up on _any_ other node most of the time. Occassionally they reach one host out of 3-4.

(If I downgrade the sending host to 1.1.14, everything starts working within a few seconds.)

**Edit:** For the record, the specific kind of multicast is OSPF hellos to `224.0.0.5` and `ff02::5`.

**Comment by adamierymenko** [comment]
What's the OS, network ID, etc.?

**Comment by grawity** [comment]
It's Arch Linux (4.9.7, 4.9.8), network `8056c2e21c288b81`.

**Comment by adamierymenko** [comment]
These wouldn't happen to be pi's would they? We're chasing an ARM compilation problem.

**Comment by grawity** [comment]
No, they're both x86_64.

**Comment by adamierymenko** [comment]
did you build from source?

**Comment by grawity** [comment]
Yes, from the [AUR package](https://aur.archlinux.org/packages/zerotier-one/). I'm going to test the host running Debian though.

**Comment by grawity** [comment]
Looking at it closer, multicast _does_ work to a point, but 1.2.0 senders only deliver multicast to only 1 or 2 subscribers. (There are 4 nodes speaking OSPF – so 3 subscribers for every sender, which really isn't that much...)

Anyway, same issue with Debian (official binaries from the zerotier repo) as far as I can see.

**Comment by adamierymenko** [comment]
hmm... strange... will try to test internally

**Comment by adamierymenko** [comment]
Ahh... yes... I think we have something. 1.2.2 pretty shortly with this and probably an ARM build fix.

**Comment by adamierymenko** [comment]
I think it would work if you wanted long enough, but there's a bit of code that was removed that should not have been.

**Comment by adamierymenko** [comment]
Fixed. 1.2.0 tonight.

**Comment by adamierymenko** [comment]
Err 1.2.2 that is.

**Comment by adamierymenko** [comment]
Little bug fix release.
