### ISSUE TITLE
Managed routes lost after windows sleep

### ISSUE THREAD

**Issue by gy6221** [zerotier/ZeroTierOne#465]
The problem is like #417 

After upgrade to 1.2.0, the managed routes still exists after system reboot. But when turn the computer into sleep and then wake it up, the route disappears. I need to add the route manually or uncheck the "Connected" checkbox and check it again to add the route again.

OS: Win10 Pro 1607
Zerotier-One Client: 1.2.0

**Comment by adamierymenko** [comment]
We've done a 1.2.2 upgrade. Does this still happen? (My guess is yes since 1.2.2 didn't touch that code, but want to check.)

**Comment by gy6221** [comment]
Yes, this problem exists in 1.2.2.

**Comment by blurredpixel** [comment]
I was just coming here to re-open the last thread we had on this subject. I am also getting this bug in 1.2.2

**Comment by adamierymenko** [comment]
Found it. Fixed in `dev`. will be in 1.2.4 soon

**Comment by r04r** [comment]
Awesome!
