### ISSUE TITLE
Path Link Quality Awareness?

### ISSUE THREAD

**Issue by luckman212** [zerotier/ZeroTierOne#472]
I noticed in 1.2.0 a new feature was added - **Path Link Quality Awareness** (details in the [release notes](https://github.com/zerotier/ZeroTierOne/releases/tag/1.2.0))

As far as I understand it, this is supposed to adjust a value from 0 to 1 that reflects packet loss to a specific ZT peer. If all is perfect, the value would be 1.00; at 50% packet loss the value would be 0.50 and so on.

In my testing, I could not get this to "work". The value was always 1.00. Am I mis-understanding the feature, or is it not fully enabled yet?

My method of testing was:
- disconnect the parent (physical) interface on the source peer
- start a simple `ping 10.147.x.x` command towards the target peer and let it run for about 30 seconds (it was printing `request timeout` on the console...)
- run `zerotier-cli listpeers` on the source peer
- The target peer still reported a reachability of 1.00

The 2 peers in the test were running ZT v1.2.2. Am I doing it wrong?

**Comment by adamierymenko** [comment]
No, you're misinterpreting the result. 😄 

If you unplug, you've simply killed the path. The path is now in a coma. Eventually it will expire and be completely deleted (or at least considered inactive and then purged).

Path link quality measures packet loss passively. To do that there must be some traffic. Try using iptables to randomly drop packets and you will see it work.

Path link quality will be used together with dead path detection to implement SD-WAN type features in the future. (We'll be working to improve dead path detection too.)

**Comment by adamierymenko** [comment]
The idea is to be able to detect *marginal* paths to prioritize traffic a QoS scenario. Packet loss indicates a saturated or poor quality path, so QoS logic would then send that traffic over another path.

Imagine you have two different commodity Internet connections: a cable line and a DSL line. You can see where this is going.

**Comment by luckman212** [comment]
Ah ok I see. Thanks for the explanation. The future sounds very promising.

So, just to confirm: assuming there may be dead links/paths on a system, there is presently no way to programmatically detect when a peer will be reachable through the ZT network or not?

**Comment by adamierymenko** [comment]
Here's the thing: the only way to actually detect a dead path is to test it by trying to send data over it. That's a law of nature, not our limitation.

ZeroTier periodically pings paths, but we only do so about every 15 seconds. Even this is a little bit more frequent than we like and is a result of many iterations of compromise between dead path detection and traffic optimization. The pings are small but they do impact mobile battery life a little. We may figure a way to disable them on mobile, but that would of course make mobile take longer to detect dead paths.

**Comment by adamierymenko** [comment]
It may look like connections detect it instantly when you unplug a cable, but that is because your OS is receiving a link down notification from the network card. If the path is interrupted along the way *between* the hosts, there is no way to detect this except to check the link actively.

**Comment by luckman212** [comment]
Understood - I guess I assumed that lack of response to the normal control/protocol messages being exchanged among peers (are those TCP based?) would trigger a path down signal without need for additional ping etc.

**Comment by adamierymenko** [comment]
Paths do eventually time out.

It's not TCP based. It's its own protocol.
