### ISSUE TITLE
IPAD Connects for a few seconds and then disconnects

### ISSUE THREAD

**Issue by dafyre** [zerotier/ZeroTierOne#473]
Hi All,

I'm running with an Apple iPad 2, on IOS 9.35 and it has the Zero Tier client 1.2.2-1 as reported by the App store.  When I launch the ZeroTier app and connect to the network, ZeroTier will show that I am connected.

After a few seconds, the iPad will disconnect from the ZT network -- even if I leave the ZeroTier app on the screen.  My Android 6.0 device, also running 1.2.2-1 works fine -- both are connected to the same Wireless network.

I have uninstalled & re-installed the ZT App, as well as left, and rejoined the ZT Network.

Is there anything else I can check on the iPad?

**Comment by adamierymenko** [comment]
Hmm... I think this may be a memory use issue in our latest release, which should be fixed by our next release. That will be coming shortly as it's just a bug fix release.

Problem is that older iDevices have stricter memory use limits on background services.

**Comment by adamierymenko** [comment]
Likely fixed in `dev`

**Comment by dafyre** [comment]
Thanks. Can I get the iOS developer version somewhere?  If not, I can wait
for the release.

Thanks!
~Brant

**Comment by adamierymenko** [comment]
Not at the moment. 1.2.4 is coming pretty soon, likely next week.

**Comment by adamierymenko** [comment]
There is a potential path stability issue we want to investigate first.

**Comment by dafyre** [comment]
That's cool.  My iPad is a backup unit anyhow.  I'll watch for it to
release and then update and see what happens.

**Comment by dafyre** [comment]
Tested 1.2.4-1 from IOS App store.  It is definitely fixed. 

Thanks!
