### ISSUE TITLE
[Feature Request] Policy Route.

### ISSUE THREAD

**Issue by Catofes** [zerotier/ZeroTierOne#474]
It's very useful that we can push route to all members via controller. But I wonder if we can push routes to partial members using some selectors like tags. In that way we can redirect all phone's traffic to zerotier network while not influence other members. 

For example, I have 3 members: `a: Phone, b: Server, c: Laptop`. If I want my phone to use Server as network gateway, I can add a policy route like "devices==a, 0.0.0.0/0, via Server". In that way my Laptop will not influence by that route. 

For another example, I have some routers:
```
Router Name        Router Ip          Router sub-network  
A               10.0.0.1                10.0.1.0/24      
B               10.0.0.2                10.0.2.0/24      
C               10.0.0.3                10.0.3.0/24      
D               10.0.0.4                10.0.4.0/24     
....
``` 
The `b,c,d,....` routers have stable network connections while A only have a direct connection with B. In that way I expect `c,d,...` access 10.0.1.0/24 via router B. It would be very helpful if I add router like:  
```
Selector                    Network                     Gateway
devices!=B || devices !=A     10.0.1.0/24      10.0.0.2
devices==B                   10.0.1.0/24         10.0.0.1
```

Of course I can set the route manually, but it will be better if I can add via web controller.  Thank you.

**Comment by adamierymenko** [comment]
Hmm... that's kind of interesting.

Could this be implemented at the UI level using tags? Like attach routes to tags such that certain members with a certain tag value or tag value mask get certain routes?

**Comment by adamierymenko** [comment]
This is more a UI features so I'm going to add this to our internal repo issue list for Central.

**Comment by adamierymenko** [comment]
Closed since moved to internal Central issue list.
