### ISSUE TITLE
There is no uninstall.sh (Ubuntu 16.04 LTS)

### ISSUE THREAD

**Issue by kbumsik** [zerotier/ZeroTierOne#476]
AFAIK the uninstall script is in `/var/lib/zerotier-one`, but there is no uninstall.sh in that directory.
How can I uninstall Zerotier One then?
My operating system is Kubuntu 16.04.2 LTS x64 and the Zerotier One version is 1.2.0.

Thank you.

**Comment by glimberg** [comment]
`apt-get remove zerotier-one`

**Comment by kbumsik** [comment]
Thanks for a quick reply. I installed it by using `curl -s https://install.zerotier.com/ | sudo bash` but `apt remove` still works! The documentation is a bit confusing. Thanks a lot anyway :)
