### ISSUE TITLE
Generate a new address using cli?

### ISSUE THREAD

**Issue by kbumsik** [zerotier/ZeroTierOne#477]
Hello, I am using Zerotier One on Ubuntu virtual machine.
I duplicated the VM to another computer. The problem is that the duplicated VM still have the same address. I tried re-installing to get a new client address but it still gets the same address. Is there any way to generate a new address for the duplicated VM?

**Comment by glimberg** [comment]
delete `/var/lib/zerotier-one/authtoken.secret` and `/var/lib/zerotier-one/authtoken.public`

**Comment by kbumsik** [comment]
I deleted `/var/lib/zerotier-one/authtoken.secret` but there is no `/var/lib/zerotier-one/authtoken.public`. After deleting `authtoken.secret` and restarting `zerotier-one` service it still gets the same address.

**Comment by glimberg** [comment]
sorry, I mis-spoke.  It's `/var/lib/zerotier-one/identity.public` and `/var/lib/zerotier-one/identity.secret`

**Comment by audiotecnicality** [comment]
What's the similar process for Windows 10?
