### ISSUE TITLE
How  can I  disable ipv6  ra  or ICMPv6?

### ISSUE THREAD

**Issue by nkcfc** [zerotier/ZeroTierOne#478]
I bridge zt0 to a physical network which has ipv6   ra.On other nodes, I do not want recive ra packet.I  want manual set  its ipv6 ip when I need it.
So, How can I  disable ipv6  ra ?
Does ZeroTierOne can do this ?

**Comment by adamierymenko** [comment]
You could do it with rules. Find out the ICMPv6 type of these messages and write a rule in your network's base rule set that drops them.

You could also do it on the bridge using ebtables I think, and I think there's also an option to run bridge traffic through iptables/ip6tables. Not sure how. I think it's a sysctl.

**Comment by nkcfc** [comment]
Thank you. But I don't want do this  by  iptables/ip6tables/ebtables.
I have try ipprotocol icmp6 .But where ICMPv6 type will be filled in? 
I know icmp <type> <code>  in the help of my.zerotier.com .
But there is not  icmp6 <type> <code> .

**Comment by adamierymenko** [comment]
The `icmp` match matches either V4 or V6 depending on packet type. You can restrict it to one or the other by ethertype like this: `ethertype ipv6 and icmp ...`.

**Comment by okletgo64** [comment]
@nkcfc @adamierymenko 
Hey, guys. I am also looking for the answer to the question. My devices receive both 2408 and 240e IPv6 that annoy me. Your discussion leave me to come up with a solution.
Here is the correct rule:
drop ethertype ipv6
    and ipprotocol icmp6
;
