### ISSUE TITLE
ping reports: DUP!

### ISSUE THREAD

**Issue by glycerine** [zerotier/ZeroTierOne#479]
I made a network to experiment with ZeroTier for the first time. I started a centos7 node in EC2, and then also on my osx laptop.

When I try to ping EC2 from my laptop, ping reports duplicate response packets:

~~~
$ ping 10.243.65.75
PING 10.243.65.75 (10.243.65.75): 56 data bytes
Request timeout for icmp_seq 0
64 bytes from 10.243.65.75: icmp_seq=0 ttl=64 time=1123.260 ms
64 bytes from 172.30.2.151: icmp_seq=0 ttl=128 time=1123.293 ms (DUP!)
64 bytes from 10.243.65.75: icmp_seq=1 ttl=64 time=778.737 ms
64 bytes from 172.30.2.151: icmp_seq=1 ttl=128 time=778.751 ms (DUP!)
64 bytes from 10.243.65.75: icmp_seq=2 ttl=64 time=1238.596 ms
64 bytes from 172.30.2.151: icmp_seq=2 ttl=128 time=1238.617 ms (DUP!)
64 bytes from 10.243.65.75: icmp_seq=3 ttl=64 time=500.436 ms
64 bytes from 172.30.2.151: icmp_seq=3 ttl=128 time=500.475 ms (DUP!)
64 bytes from 10.243.65.75: icmp_seq=4 ttl=64 time=64.046 ms
64 bytes from 172.30.2.151: icmp_seq=4 ttl=128 time=64.468 ms (DUP!)
64 bytes from 10.243.65.75: icmp_seq=5 ttl=64 time=62.099 ms
64 bytes from 172.30.2.151: icmp_seq=5 ttl=128 time=62.269 ms (DUP!)
64 bytes from 10.243.65.75: icmp_seq=6 ttl=64 time=63.596 ms
64 bytes from 172.30.2.151: icmp_seq=6 ttl=128 time=64.440 ms (DUP!)
64 bytes from 10.243.65.75: icmp_seq=7 ttl=64 time=62.533 ms
64 bytes from 172.30.2.151: icmp_seq=7 ttl=128 time=62.549 ms (DUP!)
  C-c C-c
--- 10.243.65.75 ping statistics ---
~~~

Version on OSX 10.11.6 El Capitan:

~~~
MacBook-Pro ~ $ zerotier-cli --help
ZeroTier One version 1.2.2 build 0 (platform 3 arch 2)
Copyright (c) 2011-2017 ZeroTier, Inc.
~~~

Version on linux:

~~~
$ zerotier-cli --help
ZeroTier One version 1.2.2 build 0 (platform 1 arch 2)
Copyright (c) 2011-2017 ZeroTier, Inc.
~~~

**Comment by adamierymenko** [comment]
Try `zerotier-cli info` and see if shows TUNNELED.

Right now TCP tunneling can cause this. UDP is the preferred transport for several reasons and TCP is a fallback engaged if UDP doesn't appear to be working. But to quickly "fail forward" to UDP it keeps sending UDP packets also. If UDP is marginally working, you can get this behavior when in TCP fallback mode.

We don't have any plans to fix this immediately, but in the longer term we plan to retire the current TCP fallback mode in favor of making TCP a first class transport option.

**Comment by glycerine** [comment]
That makes perfect sense. My current setup doesn't show TUNNELED, but then again it also doesn't show the DUP on ping either.  Since this is working as planned, I'm inclined to close it.
