### ISSUE TITLE
Q: restrict docker network to just zerotier?

### ISSUE THREAD

**Issue by glycerine** [zerotier/ZeroTierOne#480]
Is there a way to require that my docker container only use zerotier? I'd like to sandbox all network access of a container, and allow it to only use zerotier.

It would be especially interesting if I could use https://hub.docker.com/r/zerotier/zerotier-containerized to run zerotier in a completely different container, and still share the ZT network with (and insist that it be the only network for) other containers.

**Comment by adamierymenko** [comment]
The simplest way I can think of would be to use iptables/ip6tables on the host, but I'm sure there are others. This is really a Docker question more than a ZT question.
