### ISSUE TITLE
zerotier service is stopped after upgrading to 1.2.4 on ubuntu 16.04

### ISSUE THREAD

**Issue by janjaapbos** [zerotier/ZeroTierOne#481]
The service is running before upgrading, but no more after upgrading.

After apt-get update:
[...]
Preparing to unpack .../zerotier-one_1.2.4_amd64.deb ...
Unpacking zerotier-one (1.2.4) over (1.2.2) ...
[...]
Setting up zerotier-one (1.2.4) ...
The system user `zerotier-one' already exists. Exiting.
[..]

zerotier-cli info
0 info invalid JSON response (parse error - unexpected 'c')

service zerotier-one start

zerotier-cli info
200 info xxx 1.2.4 ONLINE

**Comment by janjaapbos** [comment]
Also, the zerotier-cli could give a better error msg when the service is not running / available.

**Comment by janjaapbos** [comment]
This seems to be random behaviour. The service does not always end up stopped when upgrading from 1.2.2 to 1.2.4 and getting the same exit message from the system user zerotier-one check.

**Comment by paulfurley** [comment]
Do you see anything in `/var/log/syslog` or `/var/log/kern.log`?

Wondering if this is related to my issue #489

**Comment by janjaapbos** [comment]
Let's close it, and open a new one if it reoccurs in a new version.
