### ISSUE TITLE
zerotier cannot bind to local interface port

### ISSUE THREAD

**Issue by vostok4** [zerotier/ZeroTierOne#482]
This recently started happening to me on Archlinux after a large update of packages. If I try to run any zerotier-one tool I always get:

```
# zerotier-one info
zerotier-one: fatal error: cannot bind to local control interface port
```

However, if I look at netstat output, I can see that zerotier-one is listening just fine:
```
# netstat -lp --numeric-ports --numeric-hosts | grep zero 
tcp        0      0 127.0.0.1:9993          0.0.0.0:*               LISTEN      527/zerotier-one    
tcp6       0      0 ::1:9993                :::*                    LISTEN      527/zerotier-one    
udp        0      0 10.0.0.11:45086         0.0.0.0:*                           527/zerotier-one    
udp        0      0 10.0.0.11:45087         0.0.0.0:*                           527/zerotier-one    
udp        0      0 10.0.0.11:9993          0.0.0.0:*                           527/zerotier-one    
```

Also, I can confirm that zerotier is connected, and functioning properly on this host. It doesn't matter if I restart the service or the machine, and there is no SELinux here.

**Comment by misuzu** [comment]
Try ```zerotier-cli info```.

**Comment by vostok4** [comment]
Sweet mother of #$%. I'm sorry.

**Comment by reconciliation777** [comment]
any solution? i met the same problem

**Comment by cjd400** [comment]
same problem :(

**Comment by evren320** [comment]
same problem, just after arch system update, also updated zerotier-one version, problem was not exist before update

**Comment by joseph-henry** [comment]
@reconciliation777 @cjd400 @evren320 If this is really the same problem the solution is in the second comment above. If it's not, then you should probably open a different ticket and we can help you there. Be sure to include a description of what you tried.

**Comment by someara** [comment]
"zerotier-one" vs "zerotier-cli"

**Comment by engureguo** [comment]
`zerotier-cli info`, not `zerotier-one info`

**Comment by Future-Jim** [comment]
> > 
> 
> How is 'zerotier-cli info' a solution?

its a passive aggressive solution

**Comment by mierzejk** [comment]
Check if the service is running
```
systemctl status zerotier-one
```
If it is, use `zerotier-cli` to configure your VPN connection.
