### ISSUE TITLE
zerotier stops working after 1 week

### ISSUE THREAD

**Issue by glycerine** [zerotier/ZeroTierOne#485]
I set up a three node test network in EC2.

The internal vpn ip addresses are:

~~~
10.147.17.79 ztk0
10.147.17.210 ztk1
10.147.17.240 ztk2
~~~

It worked last week. I left the VMs up and running on EC2. This week, when I come back to it, it appears that in the interim the zerotier network has died. I can no longer ping from any machine to any other over the zerotier interface.

~~~
[root@ztk0 ~]# ping ztk2
PING ztk2 (10.147.17.240) 56(84) bytes of data.
From ztk0 (10.147.17.79) icmp_seq=1 Destination Host Unreachable
From ztk0 (10.147.17.79) icmp_seq=2 Destination Host Unreachable
From ztk0 (10.147.17.79) icmp_seq=3 Destination Host Unreachable
  C-c C-c
--- ztk2 ping statistics ---
10 packets transmitted, 0 received, +3 errors, 100% packet loss, time 9193ms
pipe 8
[root@ztk0 ~]# zerotier-cli  info
200 info 0b6c6afc06 1.2.2 ONLINE
[root@ztk0 ~]#
~~~

I saw this before, but I think we closed that earlier issue as hard to reproduce (I think I just restarted the zerotier-one processes to get it to come back). Now that I've reproduced it on each of three nodes, perhaps there is some troubleshooting that can be done.

**Comment by janjaapbos** [comment]
Looks familiar. Restarting service will often bring back the connection. (depending on which node(s) were actually causing the issue).

Hopefully this solved or the cause has disappeared in the latest version of zerotier (1.2.4). Please upgrade to that.

Next time if you do get this issue again, try to troubleshoot without restarting a node as this will often restore the service.

You can e.g. try to create a new network and have the nodes join that, try to see if that will have the same issue. Verify the remote peer addresses (zerotier-cli listpeers) at all nodes. 

Add a new node to the network that is not yet known to the group of nodes and try if that has the same issue.

**Comment by glycerine** [comment]
> Hopefully this solved or the cause has disappeared in the latest version of zerotier (1.2.4). Please upgrade to that.

I haven't restarted these, so we can still troubleshoot. I'm running 1.2.2

>[root@k0 jaten]# zerotier-cli -v
.1.2.2

The 1.2.4 release notes have this:
> Reworked and simplified path selection and priority logic to fix path instability and dead path persistence edge cases. There have been some sporadic reports of persistent path instabilities and dead paths hanging around that take minutes to resolve. These have proven difficult to reproduce in house, but hopefully this will fix them. In any case it seems to speed up path establishment in our tests and it makes the code simpler and more readable.

@janjaapbos is there anyway to view logs and see if that is indeed the issue?

I'll try your other steps as soon as possible.

**Comment by glycerine** [comment]
`zerotier-cli listpeers` shows the peers that are expected. Some IPs elided for privacy:

~~~
[root@k1 system]# zerotier-cli listpeers
200 listpeers <ztaddr> <path> <latency> <version> <role>
200 listpeers 07409a4005 77.x.y.z/60759;5629;6663;1.00 132 1.2.2 LEAF
200 listpeers 0b6c6afc06 54.x.y.z/9993;14;14;1.00 0 1.2.2 LEAF
200 listpeers 7c7d9b3d5d 52.x.y./9993;5629;10628;1.00 1 1.2.2 LEAF
200 listpeers 8841408a2e 45.32.198.130/9993;10629;10590;1.00 179 1.1.5 PLANET
200 listpeers 93afae5963 149.x.y.z/59948;5629;8033;1.00 163 1.2.5 LEAF
200 listpeers 9d219039f3 107.170.197.14/9993;5629;5626;1.00 164 1.1.5 PLANET
200 listpeers e2e2082a79 - 0 - LEAF
[root@k1 system]#
~~~

However, importantly, restarting the `zerotier-one` processes *did not* restore connectivity.

@janjaapbos is there any other troubleshooting I can do before upgrading to the latest?

**Comment by glycerine** [comment]
I created a new network, and joined all three nodes to it. But still no ping.

~~~
sh-4.2# zerotier-cli join 93afae5963b71414
200 join OK
sh-4.2# ping tkz0
ping: tkz0: Name or service not known
sh-4.2# ping ztk0
PING ztk0 (10.147.17.79) 56(84) bytes of data.
From ztk2 (10.147.17.240) icmp_seq=1 Destination Host Unreachable
From ztk2 (10.147.17.240) icmp_seq=2 Destination Host Unreachable
From ztk2 (10.147.17.240) icmp_seq=3 Destination Host Unreachable
From ztk2 (10.147.17.240) icmp_seq=4 Destination Host Unreachable
~~~

**Comment by glycerine** [comment]
I'll try upgrading.

**Comment by glycerine** [comment]
Sadly, upgrading to 1.2.4 did not resolve the problem. 

I still cannot ping.

~~~
[root@k1 system]# ping 10.147.17.79
PING 10.147.17.79 (10.147.17.79) 56(84) bytes of data.
From 10.147.17.210 icmp_seq=1 Destination Host Unreachable
From 10.147.17.210 icmp_seq=2 Destination Host Unreachable
~~~

It does look like the problem is on the return trip. Notice how the host unreachable message lists .201 (the IP for ztk1 itself) rather than .79

**Comment by glycerine** [comment]
Contact me directly by email if you want to get a login to debug; these are on EC2.

**Comment by glimberg** [comment]
Is your firewall configuration in AWS blocking UDP traffic on port 9993?

**Comment by glimberg** [comment]
I think that's "Security Group" configuration in AWS/EC2 lingo

**Comment by glycerine** [comment]
@glimberg There is no opening in the firewall for port 9993. It worked fine last week without one. Is this some kind of new requirement?

**Comment by glimberg** [comment]
Unless you're allowing all traffic inbound and outbound to pass in the Security Group, then yes this is likely the issue.  ZeroTier defaults to communicating via UDP port 9993.  For our AWS instances we usuay set:

```
UDP    9000 - 10000    0.0.0.0/0
UDP    9000 - 10000    ::/0
```

As ZeroTier can talk on other ports in that range at times.

**Comment by glycerine** [comment]
Hmmm.... That doesn't make sense because it working last week, without firewall adjustments.

Nonetheless, I tried it. I opened up UDP 9000-10000, but still no pings on the return path, from any of the three nodes to either of the other two.

~~~
[root@k2 ~]# ping ztk1
PING ztk1 (10.147.17.210) 56(84) bytes of data.
From ztk2 (10.147.17.240) icmp_seq=1 Destination Host Unreachable
From ztk2 (10.147.17.240) icmp_seq=2 Destination Host Unreachable
~~~

**Comment by glimberg** [comment]
Can you ping the individual hosts from each other via their public IP addresses?

**Comment by glimberg** [comment]
Just looked at your network configuration in the database.  You have no authorized members on the network.  We did have an issue in Central over this past weekend that caused some spurrious deauthentication of network members.  It looks like that hit you as well.

Go to https://my.zerotier.com and re-authorize the members and you should be good to go.

**Comment by glycerine** [comment]
> We did have an issue in Central over this past weekend that caused some spurrious deauthentication of network members. It looks like that hit you as well.

oh my. okay! that makes so much more sense.

**Comment by glycerine** [comment]
Yep. Somehow the authorization checkboxes had gotten deleted.

Good to know the network de-authorization actually does work :-)

I removed all firewall holes around 9993 and 9000-10000, and pings still work fine.
