### ISSUE TITLE
Does ZeroTierOne   compatible with Hurricane Electric's IPv6 Tunnel Broker?

### ISSUE THREAD

**Issue by nkcfc** [zerotier/ZeroTierOne#486]
I have a kvm vps which do not have ipv6. So I use Hurricane Electric's IPv6 Tunnel Broker. But ZeroTierOne does not use  it for communication with other nodes , including   another vps with ipv6 and   my workstation with native ipv6.
Here is "zerotier-cli listpeers"(only show ipv6 info):

200 listpeers 8841408a2e 2001:19f0:6400:81c3:5400:00ff:fe18:1d61/9993;1478;26761;1.00 182 1.1.5 PLANET
200 listpeers 9d219039f3 2604:a880:0001:0020:0000:0000:0200:e001/9993;6812;11790;1.00 317 1.1.5 PLANET

**Comment by adamierymenko** [comment]
If I remember correctly we have code in there to explicitly blacklist the he.net IPv6 range. Ugly, yes, but we had all kinds of sporadic problems with it that were reported as bug reports.

Try searching for 2001:19f0 to find it. You could comment it out and rebuild.
