### ISSUE TITLE
gray on black website is impossible to read

### ISSUE THREAD

**Issue by glycerine** [zerotier/ZeroTierOne#487]
Example:

https://support.zerotier.com/hc/en-us/articles/115001048727-Bridging-Ethernet-to-ZeroTier-Virtual-Networks-on-Linux

The web page above is impossible to read because the text is gray on a black background. Screenshot:

image:https://drive.google.com/file/d/0BxpncsKbxeGWbWRXeDRTRjA3UEU/view?usp=sharing

**Comment by glimberg** [comment]
Looks like there's something funky in the CSS if the screen is too narrow that turns the background black.  We'll take a look

**Comment by glycerine** [comment]
good diagnosis. zooming out does offer a temporary fix.

**Comment by glimberg** [comment]
Reload the page.  Should be fixed now

**Comment by glycerine** [comment]
Yep! Thanks.
