### ISSUE TITLE
zt0: Invalid MTU 2800 requested, hw max 68

### ISSUE THREAD

**Issue by paulfurley** [zerotier/ZeroTierOne#489]
Hi,

I'm on a fresh install of Ubuntu 16.04: `Linux xps 4.8.0-49-generic #52~16.04.1-Ubuntu SMP Thu Apr 20 10:55:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux` and I'm getting the above error when starting ZeroTier One version 1.2.4 build 0 (platform 1 arch 2):

`/var/log/syslog`:
```
Apr 28 16:14:50 xps systemd[1]: Stopping ZeroTier One...
Apr 28 16:14:50 xps systemd[1]: Stopped ZeroTier One.
Apr 28 16:14:50 xps systemd[1]: Started ZeroTier One.
Apr 28 16:14:50 xps kernel: [22574.980808] zt0: Invalid MTU 2800 requested, hw max 68
Apr 28 16:14:50 xps NetworkManager[1033]: <info>  [1493392490.6062] devices added (path: /sys/devices/virtual/net/zt0, iface: zt0)
Apr 28 16:14:50 xps NetworkManager[1033]: <info>  [1493392490.6062] device added (path: /sys/devices/virtual/net/zt0, iface: zt0): no ifupdown configuration found.
Apr 28 16:14:50 xps NetworkManager[1033]: <info>  [1493392490.6091] devices removed (path: /sys/devices/virtual/net/zt0, iface: zt0)
Apr 28 16:14:50 xps zerotier-one[24011]: ERROR: unable to configure virtual network port: unable to configure TAP MTU
```
`var/log/kern.log`:
```
Apr 28 16:14:50 xps kernel: [22574.980808] zt0: Invalid MTU 2800 requested, hw max 68
Apr 28 16:14:50 xps NetworkManager[1033]: <info>  [1493392490.6062] devices added (path: /sys/devices/virtual/net/zt0, iface: zt0)
Apr 28 16:14:50 xps NetworkManager[1033]: <info>  [1493392490.6062] device added (path: /sys/devices/virtual/net/zt0, iface: zt0): no ifupdown configuration found.
Apr 28 16:14:50 xps NetworkManager[1033]: <info>  [1493392490.6091] devices removed (path: /sys/devices/virtual/net/zt0, iface: zt0)
```

Done a fair bit of Googling but haven't seen this elsewhere.

`/dev/net/tun` exists (altho doing `cat /dev/net/tun` results in `cat: /dev/net/tun: File descriptor in bad state` - not sure what that's about?

**Comment by paulfurley** [comment]
Thanks @kees-j-bot, that's helpful.   
 
 
 

 
Possibly this bug?   https://bugs.launchpad.net/ubuntu/+source/linux-hwe-edge/+bug/1679823
 
 
 
>  
>  
>    
>    
>

**Comment by adamierymenko** [comment]
Kernel bug. Not ours. Won't fix. :)

**Comment by carsontang** [comment]
Ran into the same issue with the symptom of PORT_ERROR after updating to 4.8.0-49-generic. Rebooting with 4.8.0-46-generic fixed the problem.

**Comment by rtucker** [comment]
The kernel linked from https://bugs.launchpad.net/ubuntu/+source/linux-hwe-edge/+bug/1679823/comments/38 fixes this for me.

**Comment by rkrzr** [comment]
I ran into this same bug on a new 16.04 box on GCE. It was running kernel 4.8.0-52-generic.
After upgrading to the latest kernel (4.8.0-54-generic) and rebooting the `zt0` network interface was created correctly.
