### ISSUE TITLE
Add command and UI function to enable/disable networks without having to join/leave

### ISSUE THREAD

**Issue by adamierymenko** [zerotier/ZeroTierOne#49]
As requested by a user or two.

**Comment by heri16** [comment]
Nice feature and well overdue.

**Comment by adamierymenko** [comment]
The plumbing is already there. This is just one of those little useful features that's been sidelined for bigger stuff so far.

**Comment by janjaapbos** [comment]
What is the difference with join & leave? That takes care of device (de)initialisation. The membership / authorisation remains valid.

**Comment by feliksik** [comment]
My experience matches that of @janjaapbos ; possibly this functionality is already effectuated. If a user leaves and joins again, his authorization remains valid. 

A possibly related issue (or possibly it is a separate discussion): If an admin removes a member from the list, this has the same implications as unauthorizing, with the additional effect that it will not show up in the list again. You *could* say it is useful to make the user show up in the admin list again as soon as the user decides to leave the network and joins again. But this seems more of a usability issue than a technical one, as the admin can also add the member again, manually.

**Comment by jdrews** [comment]
:+1:

**Comment by jdrews** [comment]
@janjaapbos @feliksik I believe this is targeted towards the client software. Users expect a simple way to connect and disconnect from a ZeroTier network without having to reenter the hexadecimal network id. A simple Enable/Disable or Connect/Disconnect button would be greatly appreciated.

**Comment by adamierymenko** [comment]
Closing since we're going to address this at the UI layer, not the service layer.

**Comment by jdrews** [comment]
Is this in 1.1.6?

**Comment by glimberg** [comment]
@jdrews Not yet. I'm still working on that in the UI.

**Comment by jdrews** [comment]
@glimberg How's it going with this task?

**Comment by Silex** [comment]
Was this feature abandoned?

**Comment by glimberg** [comment]
It's part of the Mac and Windows UI's.  Not available from the command line

**Comment by Silex** [comment]
Alright, I guess I'll write my own wrapper that `join` and `leave` network with some associative array based on the network name. It's a shame that `zerotier-cli` does not have native support for that.
