### ISSUE TITLE
Build failed, my system is LEDE-X64. Error Message: / usr / bin / ld: -lpthread not found

### ISSUE THREAD

**Issue by turing-king** [zerotier/ZeroTierOne#490]
Build failed, my system is LEDE-X64.
Error Message: `/ usr / bin / ld: -lpthread not found`
`root@LEDE-X64:~# find / -name "*pthread*"`
`/overlay/upper/usr/include/pthread.h`
`/rom/usr/lib/opkg/info/libpthread.control`
`/rom/usr/lib/opkg/info/libpthread.list`
`/usr/lib/opkg/info/libpthread.control`
`/usr/lib/opkg/info/libpthread.list`
`/usr/include/pthread.h`

Installed from the official source version is 1.2.2, I would like to install 1.2.4

**Comment by adamierymenko** [comment]
You're missing the pthread library. If it's part of your libc you'll have to edit make-linux.mk and remove it.

**Comment by turing-king** [comment]
I have solved this problem, see https://github.com/mwarning/zerotier-openwrt
