### ISSUE TITLE
New ZeroTier 1.2.4 on Synology x86-64

### ISSUE THREAD

**Issue by naasking** [zerotier/ZeroTierOne#495]
It all seems to work, but running the zerotier-cli prints out some errors:

    ~# zerotier-cli -v
    zerotier-cli: /lib/libstdc++.so.6: no version information available (required by zerotier-cli)
    zerotier-cli: /lib/libstdc++.so.6: no version information available (required by zerotier-cli)
    zerotier-cli: /lib/libstdc++.so.6: no version information available (required by zerotier-cli)
    zerotier-cli: /lib/libstdc++.so.6: no version information available (required by zerotier-cli)
    zerotier-cli: /lib/libstdc++.so.6: no version information available (required by zerotier-cli)
    zerotier-cli: /lib/libstdc++.so.6: no version information available (required by zerotier-cli)
    1.2.4

**Comment by naasking** [comment]
I should note that this is running DSM 6.0.2-8451 Update 11 on a DS3615xs.

**Comment by adamierymenko** [comment]
That's a known issue. It works fine but prints that nonsense. Will fix in a future release.

**Comment by adamierymenko** [comment]
We'll probably build static for Synology using our alpine/musl static build images.

**Comment by joseph-henry** [comment]
For anyone arriving here from a search engine, here's our NAS package repo: https://github.com/zerotier/ZeroTierNAS
