### ISSUE TITLE
The device can not ping through the device

### ISSUE THREAD

**Issue by turing-king** [zerotier/ZeroTierOne#496]
I am in my three devices: windows10, ubuntu, LEDE-x64 above are installed the latest zerotier 1.2.4 version. In the console page, they are displayed online, can be assigned to ip. But can not ping successfully.
What should I do, who will help me?

**Comment by turing-king** [comment]
and , all Physical IP is unknown!

**Comment by turing-king** [comment]
I found this on the site: "Multicast Recipient Limit" This is the subnet mask? I modified it to "24" and then Managed Routes set to "192.168.192.0/24 - lan". My device will be able to ping the normal success

**Comment by turing-king** [comment]
Now and fail! It can not be used normally.

**Comment by adamierymenko** [comment]
Do these devices run local firewalls that might block ping?

**Comment by turing-king** [comment]
@adamierymenko Ok, I found the problem with my device, I changed the new equipment, they can work.
