### ISSUE TITLE
zerotierone doesn't create dev zt0 on debian 8

### ISSUE THREAD

**Issue by Madji** [zerotier/ZeroTierOne#497]
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.7 (jessie)
Release:	8.7
Codename:	jessie
3.16.0-4-amd64

after curl -s https://install.zerotier.com/ | bash
.......
*** Success! You are ZeroTier address [ 4bdc19c630 ].

root@tex-host:/home/biodamage# zerotier-cli info
401 info invalid JSON response (parse error - unexpected end of input)
....

curl -H "X-ZT1-Auth: $(sudo cat /var/lib/zerotier-one/authtoken.secret)" http://localhost:9993/status

 "address": "4bdc19c630",
 "clock": 1493885318064,
 "cluster": null,
 "config": {
  "physical": null,
  "settings": {
   "portMappingEnabled": true,
   "primaryPort": 9993,
   "softwareUpdate": "disable",
   "softwareUpdateChannel": "release"
  }
 },
 "online": true,
 "planetWorldId": 149604618,
 "planetWorldTimestamp": 1452708876314,
 "publicIdentity": "4bdc19c630:0:75057953437fffbb947db31ff6516f6baedd415fc3842e099a35835a81ae4267a7d5abf82090cc9f450fda14555eb5b3b554f030e54778e613d0581989fc58ca",
 "tcpFallbackActive": false,
 "version": "1.2.4",
 "versionBuild": 0,
 "versionMajor": 1,
 "versionMinor": 2,
 "versionRev": 4
.......
root@tex-host:/home/biodamage#ifconfig
eth0     Link encap:Ethernet  HWaddr e8:de:27:a7:48:d5  
          inet addr:192.168.1.100  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::eade:27ff:fea7:48d5/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1252 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2816 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:126231 (123.2 KiB)  TX bytes:654487 (639.1 KiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:100099 errors:0 dropped:0 overruns:0 frame:0
          TX packets:100099 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:32185975 (30.6 MiB)  TX bytes:32185975 (30.6 MiB)
.......
I see  [#448](https://github.com/zerotier/ZeroTierOne/issues/448)
Tried to remove and install again, with the removal of directories, but this does not help.
 ls -l /var/lib/zerotier-one
-rw------- 1 root root  24 май  4 10:52 authtoken.secret
drwx------ 1 root root   0 май  4 10:52 controller.d
drwxr-xr-x 1 root root  40 май  4 10:52 iddb.d
-rw-r--r-- 1 root root 141 май  4 10:52 identity.public
-rw------- 1 root root 270 май  4 10:52 identity.secret
-rw-r--r-- 1 root root 634 май  4 10:59 planet
lrwxrwxrwx 1 root root  22 апр 25 08:16 zerotier-cli -> /usr/sbin/zerotier-one
lrwxrwxrwx 1 root root  22 апр 25 08:16 zerotier-idtool -> /usr/sbin/zerotier-one
lrwxrwxrwx 1 root root  22 апр 25 08:16 zerotier-one -> /usr/sbin/zerotier-one
-rw-r--r-- 1 root root   4 май  4 10:59 zerotier-one.port
firewall disabled
Tell me how to make it work?

**Comment by adamierymenko** [comment]
What kernel version are you running? Is this in a container? Does `/dev/net/tun` exist?

**Comment by Madji** [comment]
biodamage@tex-host  $ sudo ls /dev/net
tun
biodamage@tex-host  $ uname -r
3.16.0-4-amd64
it's desktop distributiv

**Comment by adamierymenko** [comment]
Hmm... this is pretty odd. Are you perhaps running with SELinux enabled and some kind of rule prohibiting ZT from doing this?

**Comment by Madji** [comment]
SELinux enabled ... not install

**Comment by Madji** [comment]
know . I made easier. from the production server with ubuntu 16. I copied the /usr/lib/zerotier-one/* on Debian . restarted the service and... it works. strange..

**Comment by typcn** [comment]
I also have this issue 
the zerotier-cli program is connecting to 127.0.0.1:9993 , and curl connect to localhost(ipv6):9993

![image](https://user-images.githubusercontent.com/8022103/27319132-8df1d5ee-5555-11e7-89b1-72ba11645fe0.png)

**Comment by glimberg** [comment]
Try updating your kernel.  There have been some issues in recent linux kernel versions with MTU settings.  Especially with MTU's over 1500.  We've mostly heard about it on Ubuntu, but it also happening on Debian isn't very far fetched.

**Comment by typcn** [comment]
I'm already using the latest kernel ( 3.16.0-4-amd64 #1 SMP Debian ), do I need to install 4.x ?

**Comment by glimberg** [comment]
4.8.0-49 is one of the kernel versions we were seeing this issue on with Ubuntu 16-04. Check your logs for `zt0: Invalid MTU 2800 requested`

**Comment by typcn** [comment]
My zerotier-one is working, just can't use zerotier-cli to manage it , because it's return 401 on ipv4 127.0.0.1 , but works fine with curl ipv6

**Comment by glimberg** [comment]
@typcn You should probably open a new issue rather than taking over an unrelated one.

are you using `sudo` when calling zerotier-cli?  zerotier-cli talks to the zerotier-one service via HTTP.  401 error means you're not authorized which usually means the auth token is not readable.

**Comment by quetsch** [comment]
Hi!
There is definitely an issue with creating a zt0 interface on Debian 8 with openvpn server installed. The error message in /var/log/syslog is as follows:
 zerotier-one[378]: ERROR: unable to configure virtual network port: could not open TUN/TAP device: No such file or directory.

I installed zerotier-one freshly on two machines, a local LAN server and on a virtual server, both running debian 8 (uname -r):
LAN-Server: 3.16.0-5-amd64
vServer: 3.16.0
The vServer is configured as openvpn server with both a tun and a tap interface. However, joing my private network works on both machines, no traffic to the vServer however (PORT_ERROR)
sudo zerotier-cli listnetworks
200 listnetworks <nwid> <name> <mac> <status> <type> <dev> <ZT assigned ips>
200 listnetworks a09acf02333f90c3 Quetsch c2:26:be:0f:c7:29 PORT_ERROR PRIVATE  fc93:a55f:c1b6:813c:c5e6:0000:0000:0001/40,10.100.79.1/24

Any help would be appreciated.
BTW: No change when I shut down openvpn and the tun/tap interfaces go down. Seems like an issue in coexisting with openvpn.

**Comment by sarnold** [comment]
These symptoms appear for me on Gentoo with kernel 4.14.29 (running a hardened/musl/selinux profile, with selinux currently disabled).  I forgot to add the "tun" module to conf.d/modules so it looks like it's working (zerotier-cli info, etc) but no zt0 interface.  After loading the module and restarting zerotier service, the zt0 interface comes up fine.
