### ISSUE TITLE
[Question] Is that possible to make controller API compatible with ZeroTier Central API?

### ISSUE THREAD

**Issue by sbilly** [zerotier/ZeroTierOne#498]
[Network Controller Microservice](https://github.com/zerotier/ZeroTierOne/tree/master/controller) API does not compatible with [my.zerotier.com's API](https://my.zerotier.com/help/api).

Is that possible to make Controller API compatible with ZeroTier Central API ?

**Comment by adamierymenko** [comment]
That would require a redesign of one or possibly both. It would not be hard however to make a shim -- a small bit of code to adapt Central and controller APIs.
