### ISSUE TITLE
can`t remove on windows10 

### ISSUE THREAD

**Issue by kevinzhwl** [zerotier/ZeroTierOne#499]
Windows 10 pro,x64, 1730 , os verison 15063.250
zerotier one v1.24 
I can run the cmd " msiexec /X ....."  (from cmd line or GUI).
service is removed ,the files are removed.
but after the process finished ,all files come back;
I had shutdown the windows recovery/restore.
Please give me some tips .Thanks

**Comment by adamierymenko** [comment]
We will have to try this internally. We've never observed nor heard of such a thing.

**Comment by Aranjedeath** [comment]
I DM'd y'all on twitter about this recently. Can confirm. Let me know what I can do to help diagnose. 

Differently, I just hit uninstall in windows' add/remove programs menu. Zombie app :)

**Comment by adamierymenko** [comment]
We can't reproduce this. Any news?

**Comment by adamierymenko** [comment]
I tested this a while back several times on a Win10 VM.

**Comment by Aranjedeath** [comment]
Does the uninstaller log anywhere? I can reproduce this every single time, without fail.

**Comment by Aranjedeath** [comment]
https://imgur.com/a/GHBxw Here's an in-order photo album of what happens.

**Comment by Opfes** [comment]
Bump XD

**Comment by ShoryuKyzan** [comment]
Having worse issues. There's no entry in Add/Remove Programs for zerotier. I can't uninstall on windows.
