### ISSUE TITLE
zt controllers freeze after updating to 1.2.4

### ISSUE THREAD

**Issue by pkpowell** [zerotier/ZeroTierOne#500]
If `controllers.d/network` has any previous content when updating to 1.2.4 zt will freeze, i.e. `zerotier-cli info` or `curl -H 'X-ZT1-Auth:xyz' http://127.0.0.1:9993/controller/network` will timeout, and connections will drop. If I `rm -rf controllers.d/network` zt recovers right away.

I can create and join new networks in v1.2.4, but I've had to disable automatic updates on my controllers to keep them running (v1.2.2 works fine).

The json files created in controllers.d/network look identical. Any idea what could be causing this?

**Comment by adamierymenko** [comment]
Eww.

Can you try current `dev` and let me know? We haven't seen this one but there are a bunch of controller improvements in current `dev` that were made to help us scale. Would love to know if it's fixed.

**Comment by pkpowell** [comment]
Gladly!
So with current dev it doesn't freeze anymore, but a network created under 1.2.2 comes up with the nwid `0000000000000217` - not its original nwid!
`curl -H 'X-ZT1-Auth':'xyz' http://127.0.0.1:9993/controller/network/0000000000000217`reveals its proper name and nwid etc! 
`curl -H 'X-ZT1-Auth':'xyz' http://127.0.0.1:9993/controller/network/original_id` returns `{}`.
The contents of `controller.d/network` looks ok. No sign of `0000000000000217`.
I did this a second time (new network in v1.2.2 with new nwid) and got the same bogus id `0000000000000217`...

Connections to other networks work fine.

btw, the v1.2.5-dev installer (made with `make mac-dist-pkg`) generates this error message: 
`installer: The upgrade failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)`
But the install appears to succeed. I get 
`zerotier-cli info 200 info xyz 1.2.5 ONLINE`

**Comment by adamierymenko** [comment]
Will check into both these issues. Thanks!

**Comment by adamierymenko** [comment]
This should be fixed in `dev`.
