### ISSUE TITLE
Creating a bridged network on the Mac

### ISSUE THREAD

**Issue by dragonfax** [zerotier/ZeroTierOne#501]
Any examples or documentation of creating a bridged network on Macos.

I'd love to use Zerotier to connect my Paperspace VM to my entire home network.

I've found only Linux examples, and one Mac bug with MTUs
#383

**Comment by adamierymenko** [comment]
OSX's native bridging can't handle differing MTUs (I don't think). Next version has MTU configurability, but then you'd have to set the whole ZT network to 1500. Better to use a Linux device.

**Comment by adamierymenko** [comment]
Linux bridging is much, much better than any other OS that I'm aware of.

**Comment by dragonfax** [comment]
Well this is a little disappointing. @adamierymenko You closed the issue without a real answer, or even a real reason for closing it.

1. Sure, there is the MTU issue. But as you said, its mitigable by using the same MTU on both interfaces.

2. The other comment you made just said "linux is better". But that has nothing to do with what I asked. I asked about using the Mac, not using Linux. I also didn't ask which was better for this purpose. I asked if it was possibe on the Mac, and if so, how to do it.

Maybe someone knows the commands to do this sort of bridging.  I've seen bits of them on the other issue. Clearly, some people have gotten this working. so I suspect its possible. Perhaps they can chime in. You could have left the issue open to give them the chance to.

Maybe its not possible to do this sort of bridging on the mac. Do you know if its not possible, as a fact? You could have said so, if thats why you closed it.

Do you not know, and your closing it because you don't know the answer? Again wouldn't it be prudent to leave it open for someone else to try and answer it?

**Comment by dragonfax** [comment]
@consultantRR @pkpowell @jurgen-kluft Any of you guys know how to make this work?

**Comment by adamierymenko** [comment]
Closed it because it's not a bug, and because bridging on Mac is dependent on MTU configurability which has not shipped yet. Linux's bridging is better as it handles MTU mismatch elegantly. It even (by default I think) works with TCP to negotiate a common MTU via PMTU discovery. So I'd strongly recommend Linux for bridging anything in production.

**Comment by dragonfax** [comment]
Thanks for the answer!

**Comment by dragonfax** [comment]
Followup question! Do you think I could do this with VirtualBox on the mac running a copy of linux? I.e. run linux in virtualbox. Set virtualbox up to use 'bridged-networking', so the guest has full control of the network interface on the host. And then in the vm linux guest, setup zerotier, and do zerotier bridged networking.

**Comment by pkpowell** [comment]
This works for me (really well I should add). It's basically the same info you'll find in https://github.com/zerotier/ZeroTierOne/issues/383 
````
ifconfig en0 mtu 2800
ifconfig bridge0 create
ifconfig bridge0 addm zt0 addm en0 ....
ifconfig bridge0 up
````
originally I also had
````
sudo sysctl -w net.inet.ip.forwarding=1
````
but don't believe it's necessary.

caveats:
- your nic may not support high mtus, in which case wait until zt supports other mtus(?)
- bridge0 may already exist, if so try bridge1...

The whole thing is easy to setup but difficult to automate, i.e. on boot, as bridgex is an unknown, and zt may not be ready (I think). Some zt actions (like restarting the service e.g when updating zt) will remove zt from the bridge and you'll have to re-add the zt interface

**Comment by dragonfax** [comment]
I did get it to work, thanks. the mac wifi interface doesn't support mtu over 1500, but I have a thunderbolt ethernet adapter that does.

Also, the ZeroTier android app works well too.
