### ISSUE TITLE
More examples for rules engine

### ISSUE THREAD

**Issue by SystemZ** [zerotier/ZeroTierOne#502]
Hi, I love ZeroTier idea but I have a hard time setting flow rules to my liking.

I need a simple block all traffic except one case - port 80 to one of the hosts in network and allow ping.
I can't use `accept;` at the end of the config because I can't trust other hosts in network and I want to isolate from themselves like in WiFi hotspot.

Current examples that I found are only permissive ones.
Can you make more? :)

**Comment by adamierymenko** [comment]
Yes, we need that and more. We're planning a webinar series on rules among other things.
