### ISSUE TITLE
ZeroTier Central API section doesn't show /member

### ISSUE THREAD

**Issue by sekjun9878** [zerotier/ZeroTierOne#504]
The ZeroTier Central API docs doesn't show that `/api/network/.../member` is possible. It only shows the `/api/network/../member/...` to fetch a specific member. I had to guess the API call to figure that one out!

**Comment by sekjun9878** [comment]
The controller GitHub repository does have that API call.

**Comment by laduke** [comment]
Thanks @sekjun9878 

`/api/network/.../member` will be in the next release
