### ISSUE TITLE
Windows UI crashes when user clicks on "Node ID" menu item

### ISSUE THREAD

**Issue by ElTopo** [zerotier/ZeroTierOne#505]
Zerotier One version: 1.2.4
Windows version:  Windows 10 version 1703 (OS Build 15063.296)

Right click on Zerotier trayicon, the first entry of pop-up menu is "Node ID: XXXXXXXXXX", clicking on it causes "Zerotier One has stopped working".

However, the Zerotier One service continues working.

**Comment by glimberg** [comment]
First I've heard of this ever happening.  I'm using the same version of Windows.  Clicking it copies the node ID to the clipboard as expected.

**Comment by ElTopo** [comment]
@glimberg OK I don't know clicking on Node ID actually copies the ID to the clipboard.

I am using a clipboard manager (which captures copied items), so if I quit that software, Zerotier UI does not crash anymore. 

So this has to be something between Zerotier UI and the clipboard manager. The clipboard manager does not seem to have this problem with other software (Windows explorer, chrome, etc.)

**Comment by glimberg** [comment]
More likely an issue with the your clipboard manager and interacting with WPF applications.  

Just submitted a change to `dev` that *could* fix the issue.  How the nodeId would be null is currently unknown, though.

https://github.com/zerotier/ZeroTierOne/commit/e9b956ed71b435bc279fe176d99b10c55a531200

**Comment by ElTopo** [comment]
I tried another clipboard manager, got same "Zerotier UI has stopped working" problem.

So 2 different clipbard managers have this issue.

**Comment by glimberg** [comment]
Which clipboard manager are you using?

**Comment by ElTopo** [comment]
@glimberg I use Ethervane Echo:
http://www.tranglos.com/echo/

the other one is a built-in from a text-editor (only works when the editor is running)

**Comment by ElTopo** [comment]
According to MSDN, there are more exceptions for Clipboard::SetText Method

https://msdn.microsoft.com/en-us/library/ydby206k(v=vs.100).aspx?cs-save-lang=1&cs-lang=cpp#code-snippet-1

**Comment by glimberg** [comment]
And none of those are the problem. 

```
Exception thrown: 'System.Runtime.InteropServices.COMException' in PresentationCore.dll
System.Runtime.InteropServices.COMException (0x800401D0): OpenClipboard Failed (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Windows.Clipboard.Flush()
   at System.Windows.Clipboard.CriticalSetDataObject(Object data, Boolean copy)
   at System.Windows.Clipboard.SetDataInternal(String format, Object data)
   at System.Windows.Clipboard.SetText(String text, TextDataFormat format)
   at System.Windows.Clipboard.SetText(String text)
   at WinUI.ToolbarItem.ToolbarItem_NodeIDClicked(Object sender, RoutedEventArgs e) in C:\dev\ZeroTierOne\windows\WinUI\ToolbarItem.xaml.cs:line 116
```

In searching around a bit, this appears to be a bug in Clipboard.SetText().  Changing to Clipboard.SetDataObject() appears to do the trick.

Fixed in dev.  https://github.com/zerotier/ZeroTierOne/commit/2fac693243dc3b6673be104b206bc82f46f0f70c
