### ISSUE TITLE
1.2.4 precompiled binary incompatible with Pi Zero and other older / smaller ARM32 chips (fix inside)

### ISSUE THREAD

**Issue by Mifulapirus** [zerotier/ZeroTierOne#510]
Hello, after cloning the repo and sudo make, I can `sudo ./zerotier-one -d` and so on, but I've noticed how the service doesn't run on boot.
I've looked in `/lib/systemd/system` and there are no zerotier services at all.

Am i missing something after just `sudo make`?

Here is my name os info:
`PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"`

Thanks!

**Comment by nate8199** [comment]
You would have to run,

sudo systemctl enable zerotier*
sudo systemctl start zerotier*

**Comment by Mifulapirus** [comment]
I just get 
`$ sudo systemctl enable zerotier*
Failed to execute operation: No such file or directory`

The service files are not there, am I missing a step where I gotta create them?

**Comment by adamierymenko** [comment]
Do you have a Pi version 1 or other older ARM processor? The current version has a known issue with older ARM chips that will be fixed in the next. I can give you a working binary for now if you want.

**Comment by Mifulapirus** [comment]
I have a [Pi Zero W](http://www.raspberrypi-spy.co.uk/2017/02/introducing-the-raspberry-pi-zero-w/) with an ARM11.
This seems to be one of the older processors, so you might be right about this.
I'll be happy to try whatever you have, if it helps :)

**Comment by adamierymenko** [comment]
Try the attached binary. Replace `/usr/sbin/zerotier-one`. Tell me if it works.

[zerotier-one.gz](https://github.com/zerotier/ZeroTierOne/files/1023887/zerotier-one.gz)

**Comment by Mifulapirus** [comment]
Hey @adamierymenko, I didn't even have a zerotier-one file in /usr/sbin
I've put it there and made it executable, but still get the same result when I run:
`$ sudo systemctl enable zerotier* Failed to execute operation: No such file or directory`
I tried `$ sudo systemctl daemon-reload ` but nothing changes.

**Comment by adamierymenko** [comment]
How was it installed originally?

**Comment by Mifulapirus** [comment]
I just cloned the repo and `sudo make`.
Running `sudo ./zerotier-one -d` manually works fine, so it seems to be only related to the service.

**Comment by adamierymenko** [comment]
Ahh... the `make install` command doesn't install service files. There are three different init systems on Linux (at least), so packages do that.

**Comment by Mifulapirus** [comment]
&*%$#@ Linux and their init systems!
Good to know. how should I install the services then?

**Comment by adamierymenko** [comment]
The file templates are in `ext/installfiles/linux` and `debian/` and if you're using systemd can be dropped in the right place... which may differ by distribution.

**Comment by Mifulapirus** [comment]
That did the trick!
1. Copy the service file: `$ sudo cp /YOUR_ZERO_TIER_FOLDER/debian/zerotier-one.service /lib/systemd/system/`
2. Change permissions: `$ sudo chmod 644 /lib/systemd/system/zerotier-one.service`
3. Reload services: `$ sudo systemctl daemon-reload`
4. Start the service: `$ sudo systemctl start zerotier-one.service`

DONE!
Thanks, @adamierymenko!

**Comment by paulrd** [comment]
I may be running into the same issue. Trying to install on old raspberry pi gen 1. (armv6). It hangs at *** Waiting for identity generation...

Going to try build and install.

**Comment by paulrd** [comment]
Build succeeded and @Mifulapirus instructions worked like a charm!

**Comment by Mifulapirus** [comment]
I'm glad it worked for you, @paulrd!

**Comment by paulrd** [comment]
One last step was to do:
```
 sudo systemctl enable zerotier-one.service
```
to have it work after reboot.

**Comment by Mifulapirus** [comment]
Thanks for the note, @paulrd. I added it to the instructions.

**Comment by kbumsik** [comment]
This didn’t work for me. I am using the latest version of RPi debian on Zero W.
I did the following:
```bash
$ make all
$ make install

 ....The same commends on the instruction above...
```

What did I miss? Is there a specific branch or tag working for the RPi?

**Comment by timothy-gibson** [comment]
@kbumsik, the complete solution which worked for me on Zero W was:

- grab the working binary from @adamierymenko above and put it in `/usr/sbin/`
- clone the repo (master branch) and follow @Mifulapirus instructions above

**Comment by mrexodia** [comment]
For me this worked nicely on a Raspberry Pi B and Raspberri Pi Zero W:

1. `curl -s https://install.zerotier.com/ | sudo bash`
2. `Ctrl+C` when it freezes at `Waiting for identity generation`
3. `wget https://github.com/zerotier/ZeroTierOne/files/1023887/zerotier-one.gz` (patch from @adamierymenko above)
4. `gzip -d zerotier-one.gz`
5. `chmod +x zerotier-one`
6. `sudo chown root:root zerotier-one`
7. `sudo mv zerotier-one /usr/sbin/zerotier-one`
6. `sudo systemctl start zerotier-one`

If everything went okay `sudo zerotier-cli status` should now say `200 info XXXXXXXXXX 1.2.5 ONLINE`

**Comment by adamierymenko** [comment]
Fixed in `dev`

**Comment by unpluggedcoder** [comment]
works on Raspberry Pi 1
Thanks all!

**Comment by reluctantgithubuser** [comment]
Is this solved in the most recent release?
I have  Raspberry Pi Zero W running Stretch and when I run:
curl -s https://install.zerotier.com | sudo bash
it still hangs at:
*** Waiting for identity generation...

**Comment by laduke** [comment]
@reluctantgithubuser, can you make a new issue for 1.4.2 ?

**Comment by Dax911** [comment]
Was there a new issue for this? I am encountering a similar issue with `Unknown or unsupported distribution! Aborting.`
