### ISSUE TITLE
make ios_app_framework, Link command error In Xcode 8.3.2,macOS 10.12

### ISSUE THREAD

**Issue by weibo3721** [zerotier/ZeroTierOne#512]
At first the when make ios_app_framework,it not works,about 20 compile error.
I add #define ZT_SDK and change some code
Now there is no complie errors.
But some Link command error happend.

Undefined symbols for architecture arm64:
  "ZeroTier::Membership::Membership()", referenced from:
      ZeroTier::Hashtable<ZeroTier::Address, ZeroTier::Membership>::_Bucket::_Bucket(ZeroTier::Address const&) in Network.o
  "ZeroTier::CertificateOfOwnership::_owns(ZeroTier::CertificateOfOwnership::Thing const&, void const*, unsigned int) const", referenced from:
      ZeroTier::CertificateOfOwnership::owns(ZeroTier::InetAddress const&) const in Network.o
      ZeroTier::CertificateOfOwnership::owns(ZeroTier::MAC const&) const in Network.o
  "ZeroTier::Membership::addCredential(ZeroTier::RuntimeEnvironment const*, ZeroTier::NetworkConfig const&, ZeroTier::Revocation const&)", referenced from:
      ZeroTier::Network::addCredential(ZeroTier::Address const&, ZeroTier::Revocation const&) in Network.o
  "ZeroTier::Membership::addCredential(ZeroTier::RuntimeEnvironment const*, ZeroTier::NetworkConfig const&, ZeroTier::CertificateOfMembership const&)", referenced from:
      ZeroTier::Network::addCredential(ZeroTier::CertificateOfMembership const&) in Network.o
  "ZeroTier::Membership::getTag(ZeroTier::NetworkConfig const&, unsigned int) const", referenced from:
      ZeroTier::(anonymous namespace)::_doZtFilter(ZeroTier::RuntimeEnvironment const*, ZeroTier::NetworkConfig const&, ZeroTier::Membership const*, bool, ZeroTier::Address const&, ZeroTier::Address&, ZeroTier::MAC const&, ZeroTier::MAC const&, unsigned char const*, unsigned int, unsigned int, unsigned int, ZT_VirtualNetworkRule const*, unsigned int, ZeroTier::Address&, unsigned int&, bool&) in Network.o
  "ZeroTier::Membership::addCredential(ZeroTier::RuntimeEnvironment const*, ZeroTier::NetworkConfig const&, ZeroTier::CertificateOfOwnership const&)", referenced from:
      ZeroTier::Network::addCredential(ZeroTier::CertificateOfOwnership const&) in IncomingPacket.o
  "ZeroTier::Membership::addCredential(ZeroTier::RuntimeEnvironment const*, ZeroTier::NetworkConfig const&, ZeroTier::Capability const&)", referenced from:
      ZeroTier::Network::addCredential(ZeroTier::Capability const&) in IncomingPacket.o
  "ZeroTier::Membership::pushCredentials(ZeroTier::RuntimeEnvironment const*, unsigned long long, ZeroTier::Address const&, ZeroTier::NetworkConfig const&, int, bool)", referenced from:
      ZeroTier::Network::pushCredentialsNow(ZeroTier::Address const&, unsigned long long) in IncomingPacket.o
      ZeroTier::Network::filterOutgoingPacket(bool, ZeroTier::Address const&, ZeroTier::Address const&, ZeroTier::MAC const&, ZeroTier::MAC const&, unsigned char const*, unsigned int, unsigned int, unsigned int) in Network.o
      ZeroTier::Network::filterIncomingPacket(ZeroTier::SharedPtr<ZeroTier::Peer> const&, ZeroTier::Address const&, ZeroTier::MAC const&, ZeroTier::MAC const&, unsigned char const*, unsigned int, unsigned int, unsigned int) in Network.o
      ZeroTier::Network::_sendUpdatesToMembers(ZeroTier::MulticastGroup const*) in Network.o
      ZeroTier::Network::gate(ZeroTier::SharedPtr<ZeroTier::Peer> const&) in Network.o
      ZeroTier::Network::addCredential(ZeroTier::CertificateOfMembership const&) in Network.o
  "ZeroTier::EmbeddedNetworkController::handleControlPlaneHttpPOST(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)", referenced from:
      ZeroTier::(anonymous namespace)::OneServiceImpl::handleControlPlaneHttpRequest(ZeroTier::InetAddress const&, unsigned int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in OneService.o
  "ZeroTier::EmbeddedNetworkController::handleControlPlaneHttpGET(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)", referenced from:
      ZeroTier::(anonymous namespace)::OneServiceImpl::handleControlPlaneHttpRequest(ZeroTier::InetAddress const&, unsigned int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in OneService.o
  "ZeroTier::Membership::addCredential(ZeroTier::RuntimeEnvironment const*, ZeroTier::NetworkConfig const&, ZeroTier::Tag const&)", referenced from:
      ZeroTier::Network::addCredential(ZeroTier::Tag const&) in IncomingPacket.o
  "ZeroTier::SoftwareUpdater::handleSoftwareUpdateUserMessage(unsigned long long, void const*, unsigned int)", referenced from:
      ZeroTier::(anonymous namespace)::OneServiceImpl::nodeEventCallback(ZT_Event, void const*) in OneService.o
  "ZeroTier::SoftwareUpdater::check(unsigned long long)", referenced from:
      ZeroTier::(anonymous namespace)::OneServiceImpl::run() in OneService.o
  "ZeroTier::EmbeddedNetworkController::handleControlPlaneHttpDELETE(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)", referenced from:
      ZeroTier::(anonymous namespace)::OneServiceImpl::handleControlPlaneHttpRequest(ZeroTier::InetAddress const&, unsigned int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in OneService.o
  "ZeroTier::EmbeddedNetworkController::EmbeddedNetworkController(ZeroTier::Node*, char const*)", referenced from:
      ZeroTier::(anonymous namespace)::OneServiceImpl::run() in OneService.o
  "ZeroTier::SoftwareUpdater::apply()", referenced from:
      ZeroTier::(anonymous namespace)::OneServiceImpl::run() in OneService.o
  "ZeroTier::(anonymous namespace)::StapFrameHandler2(void*, void*, unsigned long long, ZeroTier::MAC const&, ZeroTier::MAC const&, unsigned int, unsigned int, void const*, unsigned int)", referenced from:
      ZeroTier::(anonymous namespace)::OneServiceImpl::nodeVirtualNetworkConfigFunction(unsigned long long, void**, ZT_VirtualNetworkConfigOperation, ZT_VirtualNetworkConfig const*) in OneService.o
  "ZeroTier::SoftwareUpdater::~SoftwareUpdater()", referenced from:
      ZeroTier::(anonymous namespace)::OneServiceImpl::run() in OneService.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

environment:
Xcode Version 8.3.2 (8E2002)
macOS:10.12
git tag:ixia-1.9

**Comment by joseph-henry** [comment]
Hello @weibo3721 We will soon have an updated `ios_app_framework` over on the experimental branch of the [libzt](https://github.com/zerotier/ZeroTierSDK) repo. Thanks for bringing this to our attention.
