### ISSUE TITLE
Windows driver 100mbit limit

### ISSUE THREAD

**Issue by PtDragon** [zerotier/ZeroTierOne#513]
Sadly on Windows it is impossible to reach over 100Mbit with ZeroTier.
Without ZeroTier: 180-200Mbit. (I have 2x100Mbit internet)
With ZeroTier 100Mbit. (And it does split to both interfaces equally so it could theoretically reach 200Mbit if driver did support it).

**Comment by adamierymenko** [comment]
There are no bandwidth limits in the Windows driver. The driver may report that it's a 100mbps port, but it's lying -- it just puts that number in because it has to put something there. In reality the tap device is a software virtual port with no speed limit other than what your CPU will handle.

**Comment by PtDragon** [comment]
CPU on host is at 46%
CPU on client at 10-15%
Weirdly i have exactly 100mbit(of raw traffic) limit when using ZeroTier on windows which is split around 50/50mbit on my two connections.
Where can be bottleneck then?

**Comment by adamierymenko** [comment]
ZeroTier doesn't currently round-robin between multiple interfaces. Do you actually have two WAN connections?

The ability to round-robin and load balance like this is coming in a future release.

**Comment by PtDragon** [comment]
Yeah, i do. 2x100mbit on different cables.
But my router does round-robin balancing.
