### ISSUE TITLE
Windows 7 x64 crash when connecting to network

### ISSUE THREAD

**Issue by VcSaJen** [zerotier/ZeroTierOne#515]
Windows 7 x64 SP1, UI crashes when clicking "Join" button on "Join a Network" window. Network displays as connected and everything is fine when restarting ZeroTier One UI, the only problem is that it crashes. Tested with both own public network and Earth network.

Version: 1.2.4
Crash report: https://pastebin.com/BQzLSwC1
Mini-dump file: https://yadi.sk/d/kZhQ7m-b3JiZtn

**Comment by glimberg** [comment]
fixed in dev
