### ISSUE TITLE
No network connectivity on Windows since 1.24

### ISSUE THREAD

**Issue by williamparry** [zerotier/ZeroTierOne#516]
I'm trying to ping a Windows 2016 box (fresh install) from macOS Sierra with both computers on the same ZeroTier network, but it looks like the Windows network has no connectivity?

![Network and Sharing Center](https://user-images.githubusercontent.com/348091/26917647-764079b4-4c72-11e7-9227-f1f244380d11.png)

It was working with 1.14 - just wondering what could have changed, and how I can go about debugging.

**Comment by dafyre** [comment]
Double check that the Windows Firewall is set to allow ICMP from a public
network?

**Comment by williamparry** [comment]
I just tried [this guide](https://technet.microsoft.com/en-us/library/cc749323(v=ws.10).aspx) with no luck.

**Comment by adamierymenko** [comment]
Take a look at the virtual network device ZeroTier creates. Is it 'operating normally'?

**Comment by williamparry** [comment]
Looks like it. I've attached some screen shots:

![ZeroTier One Virtual Port Properties -> Events ](https://user-images.githubusercontent.com/348091/26917545-02162d86-4c72-11e7-8c4b-721659aaa731.png)

![ZeroTier One Virtual Port Properties -> Details](https://user-images.githubusercontent.com/348091/26917539-ff6a108e-4c71-11e7-89d4-36ff72f17b1e.png)

![ZeroTier One Virtual Port Properties -> Driver](https://user-images.githubusercontent.com/348091/26917536-fc82a872-4c71-11e7-8f62-f05dab35dc1d.png)

![ZeroTier One Virtual Port Properties -> General](https://user-images.githubusercontent.com/348091/26917534-fa1c5f88-4c71-11e7-8f8d-8ff06336150c.png)

![Ethernet 4 -> Properties](https://user-images.githubusercontent.com/348091/26917528-f6d742fc-4c71-11e7-97a3-2b8c0b4d7bec.png)

![Network Connections -> Ethernet 4 Status](https://user-images.githubusercontent.com/348091/26917524-f09e0a7e-4c71-11e7-8e38-042fe7b2e3c4.png)

**Comment by williamparry** [comment]
It was an issue with the VPN creation script here:

https://github.com/cloudRIG/CLI/commit/b3d66ad6681c172134766943f9b85ab173f07690

Looks like with the upgrade to 1.24 it requires a different packet
