### ISSUE TITLE
mdns/bonjour on windows

### ISSUE THREAD

**Issue by berot3** [zerotier/ZeroTierOne#517]
hi,

I installed zt on a linux machine and on a windows PC, each on different sites.

I have mdns working on both machines.

what works: ping windows-pc.local from linux
what does not: ping linux.local from windows-pc
I mean, of course I can use the IP to ping/access the linux-machine from windows, but it would be great to have mdns working!

I guess that something is miss-configured in windows?

thx

**Comment by adamierymenko** [comment]
It's likely a configuration issue on the Linux machine. It may not be advertising to the ZT interface.

**Comment by berot3** [comment]
is there anything I can check/verify/configure?

**Comment by adamierymenko** [comment]
You could try using a sniffer like tcpdump on the Linux system to see if packets are being sent.

**Comment by adamierymenko** [comment]
This is likely related:

https://support.zerotier.com/knowledgebase.php?entry=show&search-for=&article=Y2E2MjYzMTk0MjRjZDM3YThlNjkzNDRkZjY5MTg4Y2U_
