### ISSUE TITLE
[Feedback] 2FA support on my.zerotier.com 

### ISSUE THREAD

**Issue by soakes** [zerotier/ZeroTierOne#522]
Hi,

Due to my.zerotier.com has control over approving/setting up new networks and firewall rules, I think it would be very wise if you would consider adding in 2FA support as password only auth is too weak these days.

Google authenticator support should be fairly easy to implement and I am sure a lot of us would very much appreciate this.

Also I noticed that you can't update your email address, thats also another small thing you might want to allow.

**Comment by glimberg** [comment]
2 factor auth is already in the feature queue

**Comment by soakes** [comment]
My apologies, I didn't notice there was a feature queue else I would of checked first.

Thanks for the update and the consideration.
