### ISSUE TITLE
[Q] Moons custom port?

### ISSUE THREAD

**Issue by soakes** [zerotier/ZeroTierOne#525]
Hi Guys,

I have gone though all documentation that I can find, but no where says if and how you can run moons on different ports.

I have tried adjusting the init script and adding -p 9995 option but for moons (dedicated node, no connection to ZT or controller) but it seems to ignore it and adds in what seems to be fairly random ports.

So my question first is, can you change the ports to what you like?  I have changed the moons.json file before signing it with the 9995 port and placed it in the moons.d dir but again it seems to ignore it.

Below is what ports its running on..  

I really need to adjust the ports to something that I can define because the machine is natted and thees only a handful of available ports per machine.  

```
udp        0      0 172.30.50.68:23449      0.0.0.0:*                           5824/zerotier-one
udp        0      0 172.30.50.68:23450      0.0.0.0:*                           5824/zerotier-one
udp        0      0 172.30.50.68:23457      0.0.0.0:*                           5824/zerotier-one
```

I also noticed after putting in 9995 in the init script, the directory structure changed slightly to..
```

/var/lib/zerotier-one/
|-- 9995
|   |-- 0000006cb27343d90.moon
|   |-- 9995
|   |   |-- authtoken.secret
|   |   |-- controller.d
|   |   |-- iddb.d
|   |   |   |-- 1641458a6e
|   |   |   `-- 8d112019f3
|   |   |-- identity.public
|   |   |-- identity.secret
|   |   |-- planet
|   |   |-- zerotier-one.pid
|   |   `-- zerotier-one.port
|   |-- authtoken.secret
|   |-- controller.d
|   |-- iddb.d
|   |   |-- 3441508a1e
|   |   `-- 1d513034f3
|   |-- identity.public
|   |-- identity.secret
|   |-- moons.d
|   |-- planet
|   `-- zerotier-one.port
|-- authtoken.secret
|-- controller.d
|-- iddb.d
|   |-- 1942108a2e
|   `-- 9d769019f3
|-- identity.public
|-- identity.secret
|-- moon.json
|-- moons.d
|   `-- 0000006cb27343d90.moon
|-- planet
|-- zerotier-cli -> /usr/sbin/zerotier-one
|-- zerotier-idtool -> /usr/sbin/zerotier-one
|-- zerotier-one -> /usr/sbin/zerotier-one
`-- zerotier-one.port

10 directories, 28 files

```

NOTE: The ID numbers on moon and iddb.d files have been changed/masked and don't reflect the live/real details.

You can see I copied the moon file (signed) into the new dir it created as well as left it in the place, is this correct?

TIA

**Comment by LFlare** [comment]
Not sure if this is the case but to my knowledge, the moons/root servers operate strictly on 9995 as it's main port but it _may_ negotiate separate ports down to 443 as part of the TCP relay port, I'm not too sure about this so don't take me as the official word on it.

**Comment by soakes** [comment]
@LFlare thanks for that.  From what i've seen is that they run on port 9993 UDP plus two to three random(ish) UDP ports on top.  These randomish ports gets generated on the first time its ran (based of key ID) so if you restart the daemon/server, you will still have the same set of ports.

**Comment by adamierymenko** [comment]
ZeroTier binds to three ports. The first is the primary port. The second two are... well... look at the comments in `OneService.cpp`.

Only the first port must be accessible.

**Comment by adamierymenko** [comment]
Basically these are workarounds for buggy NATs.

**Comment by soakes** [comment]
@adamierymenko Thank you for explaining that and it also does make more sense now as the main machines which have been having issues in connecting was machines hosted on Microsoft Azure platform.  All these machines had to have all three ports open at the very least or machines connecting to them were struggling in getting a direct p2p connection.

What i've now done is added every machine manually to each firewalls so whatever their defined ports are now open.  This has now resolved all my issues as I was having my OSPF sessions going up and down due to some nodes kept connecting to rely servers which had significant packet loss and most of these were if they were on Azure.

Seems if your hosting on Azure platform to make sure all the assigned ports are open on Azures firewall or expect to have issues.
