### ISSUE TITLE
Improve ability to measure and audit direct connectivity and efficiency on a network

### ISSUE THREAD

**Issue by soakes** [zerotier/ZeroTierOne#526]
Just food for thought as I have noticed as the network grows, it starts getting harder and harder to make sure that all the nodes are connected correctly (direct).

I was thinking that if you had a flag or even set it as the default to do reverse DNS checks on the IP's and any which does have rDNS (most/all should if your good) then it should display these instead.

The reasoning behind my thinking is that most people set the reverse to the machines fqdn so you will know what machine or network has a problem.  I found after you get quite a few machines (about 20+ or so servers), it starts getting confusing whether X IP is one of your servers and what server it is or if its one of yours.  If its yours then it means its likely gone via relay which IMO are very unreliable as they either work good with no loss and fairly decent speeds or really bad where massive packet loss to the point that your whole network then becomes unusable.  I will be fixing mine soon by adding more and more moons which should help the finding of the nodes and after that I plan to add my own controller/relay then PL etc will be a thinking of the past.
 
This change is minor but would save heaps of time when diagnosing connections.

Or you could just add it to the output to show both IP and rDNS but I suspect that may break other scripts/things so maybe a new flag would be the better route.

Just my two cents.

Regards,

Simon

**Comment by adamierymenko** [comment]
I'm not sure about DNS as an answer, but I'm going to retitle this and backlog it as a general need.

**Comment by soakes** [comment]
Just a random idea with regards to this, maybe even if you just added a flag to the interface (icon of sorts) which just says/shows if that node is relayed so people can see if a node has "potential" issues.  Or list both DIRECT and NON-DIRECT via icons or a column.  

You should be able to do this quite easily by just having an if statement looking though an array of IP's and if its one of them are your servers IP's then its relayed and if its anything else then it must be direct. 

Just a thought.

**Comment by joseph-henry** [comment]
In the years since this ticket was opened we've introduced `zerotier-cli peers` which adds a bit of formatting and a new column containing `DIRECT` or `RELAY` depending on whether at least one direct path is known.

I'm going to close this ticket due to age but if you have any issues with this feature please re-open.

Thanks.
