### ISSUE TITLE
Make Android APK available on web

### ISSUE THREAD

**Issue by adamierymenko** [zerotier/ZeroTierOne#527]

**Comment by LFlare** [comment]
@adamierymenko, perhaps like zt0, the android application can be made open source? There's so many issues with it that I would try to work on it if it were open sourced.

**Comment by lramage94** [comment]
I would like to see this application on fdroid.

**Comment by glimberg** [comment]
@lramage94 F-Droid isn't likely to happen unless we decide to open source the Android app.  As it is right now, it is not open source.

**Comment by glimberg** [comment]
It's the rules of F-Droid.  Can't put it up there unless it's open source.

**Comment by lramage94** [comment]
@glimberg I know, I meant the proprietary part.

**Comment by tulsileathers** [comment]
I'll second this. I've recently de-googled my android phone. Not having ZT as an open source app is going to keep me from using it on my phone.

**Comment by scoronado12** [comment]
I would like to bump this as well as I was disappointed to find that I can only grab the apk from unofficial/sketchy sources to sideload it on my Shield TV. Other than the software being proprietary, I fail to see the problem with putting a direct download on zerotier.com/download

**Comment by joseph-henry** [comment]
The Android package will be available here going forward: http://download.zerotier.com/dist/ZeroTierOne.apk

**Comment by git70** [comment]
> The Android package will be available here going forward: http://download.zerotier.com/dist/ZeroTierOne.apk

I came across this information completely by accident.
It will be useful to put this information on the official website https://www.zerotier.com/download/ for people not using Google Play Store (for example Grapheneos).

> As it is right now, it is not open source.

We all love Zerotier, but many people also love Open Source. Will apk ever be available as OSS?
