### ISSUE TITLE
ZeroTier can't establish direct connectivity on NAT routers

### ISSUE THREAD

**Issue by zielmicha** [zerotier/ZeroTierOne#528]
When ZeroTier is installed on host that does NAT (e.g. using `-j MASQUERADE`) and on one of the devices behind this NAT, the NAT gateway won't establish non-tunneled connections to other hosts.

As soon as you change port on one of these instances, ZeroTier begins to work normally (e.g. by passing `-p9991` to zerotier-one).

This problem existed in past versions too (from at least 1.1.14).

**Comment by janjaapbos** [comment]
I don't see this issue. We have a lot of containers on different ubuntu hosts with multiple nat layers, and they usually can establish direct connection regardless of the nat layers in between.

Perhaps it is something else besides NAT in you config that is the issue.

**Comment by zielmicha** [comment]
I had this problem on multiple configurations (both real hardware, containers and virtual machines), so I'm fairly confident this is a problem.

Repro would be like this:

- create a VM/container "B" on host A
- enable IPv4 forwarding on host
- route traffic from the B with `iptables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE` (change `wlan0` to real upstream device name) on host A
- install ZeroTier on host A and the VM B
- attempt to contact some other host C from the host A

If either C or A are themselves behind NAT, the connectivity won't be established.

**Comment by zielmicha** [comment]
There also must be some ZeroTier traffic from VM B (of course, if the ZeroTier service is disabled on VM B it won't interfere).

**Comment by janjaapbos** [comment]
Perhaps it is not host NAT related, but related how the gateway router does NAT. If all hosts go through the same gateway and the gateway does also NAT, then perhaps the gateway cannot deal with multiple instances on the same host.

So to replicate, we must use the same gateway router...

**Comment by zielmicha** [comment]
In one instance I'm using Mikrotik as a gateway NAT and in another unknown router from my ISP.

I'll try to replicate this issue in a more controlled environment (e.g. maybe with moons and Internet access disabled).

**Comment by janjaapbos** [comment]
Yes, moons may help. One issue with multiple NAT is that the usual assist in connection setup from root may not yield something that can be used by the hosts behind the first NAT layer. If these hosts act as the moon for their downward NAT instances, they will be able to assist in local connection setup between the instances.

**Comment by janjaapbos** [comment]
But again, I do not experience this, and have a lot of external / internal NAT layers between the containers.

**Comment by Arffeh** [comment]
Adding 2 cents, have had this issue happen as well. Generally where
multiple ZT1 instances are virtualized on the same machine with the adaptor
bridged to a network.
