### ISSUE TITLE
enable debug / tracing on FreeBSD 11.0R / 12.0-CURRENT

### ISSUE THREAD

**Issue by dch** [zerotier/ZeroTierOne#529]
While trying to debug why no tap interface is created on 12.0-CURRENT, I couldn't get
debug/tracing working after recompiling the package, even on 11.0R. 

According to https://github.com/zerotier/ZeroTierOne/blob/master/make-bsd.mk#L16 a simple
`-DZT_DEBUG` should be sufficient.

- port diff: https://github.com/skunkwerks/ports/commit/b516c1dd368a633f8535f381a3da25368cfe5bbd
- build log: https://pkg.skunkwerks.at/poudriere/data/11_amd64-default/2017-06-16_12h55m45s/logs/zerotier-1.2.4_1.log

However running `/usr/local/sbin/zerotier` in foreground shows nothing except the tap interface
name being displayed, and I see no additional log files etc being displayed. I assume debug
output comes via stdout/stderr. Any suggestion what I can change to get this working?

**Comment by joseph-henry** [comment]
Try compiling with `make one ZT_DEBUG=1`. Running it in the foreground will output logs to `stderr`.

And, when you're observing there's no tap can you also verify that `zerotier-one` is indeed running?

**Comment by dch** [comment]
Just confirming the `gmake one ZT_DEBUG=1` works - thanks. I'll find out how to roll this into the port myself.
