### ISSUE TITLE
default route overriding doesn't work

### ISSUE THREAD

**Issue by amosbird** [zerotier/ZeroTierOne#531]
Hi, I just followed this [guide](https://support.zerotier.com/hc/en-us/articles/115001080628-Default-Route-Override-a-k-a-Full-Tunnel-in-1-1-6-) to set up a zerotier default route. I've done `allowDefault=1` however my members still don't get the default route. I tried to manually add the route by hand but it grabs all the traffics and those members become offline in zerotier network. What should I do?

**Comment by janjaapbos** [comment]
Can you post your network config? Including the IP / routing config at central.

**Comment by amosbird** [comment]
@janjaapbos um, this issue is partially solved by @dharrigan in zerotier irc, although the route push down is still working on my nodes.  Here is the full consulting log https://la.wentropy.com/dM9X
