### ISSUE TITLE
[Feature Request] Notifications when node is Offline

### ISSUE THREAD

**Issue by soakes** [zerotier/ZeroTierOne#534]
Hi Guys,

It would be great if you could "in the future" add a feature which could monitor the my.zerotier.com controller and if any of the nodes goes offline that it could send an email alert to us after a certain amount of time.

Would be great if you could also add pushover support as well while your at it :)

I guess you would need to have a toggle on each ID so that if you want them monitored then you would need to tick a tick box as some nodes would not necessary be online 24/7 i.e. laptop/mobile etc. 

I only suggest this as I have found that on the client side "sometimes" when a node goes offline, your not aware of it and secondly that the client I've found can lie.  It can say that its online, you even have all your managed routes but its not actually working.  Most times if you log into the web portal you will see it shows offline where the client says its on.  

Im sure the client would be a better method of monitoring but in the meantime, going to knock up a script to keep an eye of all the links and makes sure they are up.

**Comment by adamierymenko** [comment]
This is harder than it sounds.

There's no way to determine whether something is online without pinging it. This is physics and math, not a ZeroTier limitation. Having the controller constantly ping would use too much bandwidth and would drain mobile devices.

What we do now is a compromise. We refresh configs every 60 seconds, and consider things offline after 120.
