### ISSUE TITLE
iTunes Home Sharing HOWTO

### ISSUE THREAD

**Issue by luckman212** [zerotier/ZeroTierOne#539]
https://github.com/zerotier/ZeroTierOne/wiki/AppsForVirtualLANs#itunes says that iTunes Home Sharing should work with Virtual LANs.

I have iTunes running on my Mac at home along w/ ZeroTier1.2.4 and no matter what I tried, I could not get iTunes on my Windows PC at work to "see" the shared library. I can ping, ssh, VNC to the Mac from work via the zt0 interface, so I know the traffic is flowing nicely.

I beleive this has to do with broadcast traffic/bonjour? I have the "broadcast" traffic checkbox enabled for my network.

Any tips, or does this no longer work?

**Comment by laduke** [comment]
I see a shared library in my iTunes client, but don't know who's it is, so I'm not sure if it's windows or mac. 

In my experience, Apple apps are finicky about versions sometimes. I couldn't Airdrop unless my phone and Mac were on close enough versions. Airdrop is currently working for me though!

But my phone can't find my mac for Home Sharing, even though they are on the same wifi(?)

To troubleshoot, just bring your Mac to work or your work PC home ;) 

Alternatively, use something like https://github.com/Libresonic/libresonic and re-export your music.
