### ISSUE TITLE
How it works with Symmetric NAT?

### ISSUE THREAD

**Issue by dfc643** [zerotier/ZeroTierOne#542]
I have tried to use ZT1 connect two hosts which both behind Symmetric NAT.
It was so magically!! the two hosts communicate directly...

I confirmed the two hosts type is Symmetric NAT by STUN servers.
And I have tried ZT1 between Port Restricted Cone and Symmetric NAT,
It works directly.

I can understand how to work between Cone-NAT and Symmetric-NAT, but both Symmetric-NAT.
I'm interested in how to work between both Symmetric-NAT. thanks

**Comment by dfc643** [comment]
Hello, here is a topology about my test environment,
I think the LTE tower may not be support NAT-PMP.   XD

![test](http://i.imgur.com/zBpAvHO.jpg)

**Comment by Arffeh** [comment]
You are the best kind of user.  :)
Nice diagram.

**Comment by dfc643** [comment]
I has been test again just yet.

```
Left PC <-> Top Right PC:   turn off upnp on all routers, sometimes directly, sometimes cannot.
Left PC <-> LTE PC:         cannot connect directly.
```

**several days ago**
I do the STUN test between Left PC and LTE PC.
STUN server reports local port on LTE PC and external port on Gateway are the same.
maybe it works with 1:1 NAT

**but today,** I just did the test again,
STUN server reports local port and external port are NOT same.
and I cannot connect Left PC and LTE PC directly.

And I think the reason about sometimes directly between Left PC and Top Right PC,
may same as "Left PC and LTE PC"

---

**UPDATE:**
I did the NAT test via STUN server on Top Right PC,
The result is same as LTE PC,
sometimes local port same as external port,
but sometimes are not.

I think here is the reason why sometimes can connect directly but sometime cannot.

---

And is there any way do a UDP punching between both Symmetric NAT?
just like guess port?
I found a lot of times, the port mapping just like:

| Internal IP | Internal Port | External IP | External Port |
| ----- | ----- | ----- | -----|
| 10.1.1.1 | 5900 | 113.1.1.1 | 10000 |
| 10.1.1.1 | 5901 | 113.1.1.1 | 10001 |
| 172.16.1.1 | 1234 | 58.1.1.1 | 20000 |
| 172.16.1.1 | 1235 | 58.1.1.1 | 20001 |

And here is a PDF about [guess port](https://www.goto.info.waseda.ac.jp/~wei/file/wei-apan-v10.pdf)

---

Thank you and your nice tool, its very helpful for me.  :D
Norckon
