### ISSUE TITLE
Init.d script not starting at boot on Raspberry Pi

### ISSUE THREAD

**Issue by RatedDS** [zerotier/ZeroTierOne#543]
I had a manually compiled previous version of ZeroTier One running on my Raspberry Pi 2 running Raspbian Wheezy without a problem, and today I removed it and installed 1.2.4 using the repository.I forgot to remove the previous init.d script so dpkg kept it, I didn't know if there were any differences but to be sure I replaced it with the one from the package and made sure that it was set to start at boot.However, for some reason it doesn't and a `service zerotier-one status` returns `[FAIL] zerotier-one is not running ... failed!`.I can start the service just after boot and it runs and connects fine.

**Comment by timothy-gibson** [comment]
I'm having this same issue on Raspberry Pi 3. Tried a complete reinstall and this is still not working at boot. RatedDS did you come up with a solution?

**Comment by timothy-gibson** [comment]
@adamierymenko Just wondering why this issue is closed? Has a fix now been identified?

**Comment by adamierymenko** [comment]
Sorry we can't reproduce this, and if it is time related is superseded by #634
