### ISSUE TITLE
ZeroTier Hub-Spoke VPN How To

### ISSUE THREAD

**Issue by dimasahmad** [zerotier/ZeroTierOne#544]
I am new to ZeroTier and have limited knowledge on routing. How can I set up a hub-spoke VPN?

**Comment by jdrews** [comment]
ZeroTier is not a hub spoke VPN but a mesh SDN. However you can adapt it to do hub spoke VPN. I actually use it to link up a bunch of virtual servers in the cloud to our office. You've got three options: 
1. Install ZeroTier on every computer that needs access to network. This is probably the easiest, depending on the size of your network. 
2. Use bridging support in ZeroTier to expose ZeroTier network to a office. 
3. Setup a gateway machine running ZeroTier. Install a routing platform such as quagga on it and run a IGP (RIP, OSPF, etc) to route the ZeroTier network into your internal network. This is what we do in our office and it works well.

**Comment by dimasahmad** [comment]
So basically all nodes _can_ connect to each other, and there's no way to prevent them to talk to each other?

What I wanted to achieve is something like a WiFi client isolation, that nodes cannot talk to each other but the gateway (one special node).

**Comment by glimberg** [comment]
You can use the [Rules Engine](https://zerotier.com/manual.shtml#3) if you want to implement something like that on a network.

**Comment by dimasahmad** [comment]
I'm using this rule but it doesn't seems to work:
```
tag nodetype
	id 1
	enum 0 client
	enum 1 server
	default 0
;

break
	not tor nodetype 0
;

accept;
```

I can't reach another client nodes nor server nodes. I'm still confused of the Rules Engine.

**Comment by janjaapbos** [comment]
Do you also have a general rule before final accept to allow established traffic? Such as:

# Drop TCP SYN,!ACK packets (new connections) not explicitly whitelisted above
break                     # break can be overridden by a capability
  chr tcp_syn             # TCP SYN (TCP flags will never match non-TCP packets)
  and not chr tcp_ack     # AND not TCP ACK
;

See manual https://www.zerotier.com/manual.shtml#3_4_1

Regarding  this:

accept
	not tor nodetype 0
        and not
;

Not sure what you are trying to do. Also keep in mind that the general rules (unlike capabilties) are evaluated from both perspective (both sides see themselves as sender and the other other as receiver).

It is probably easier for use a different comparison, checking the tag of only the sender. 

E.g. to only allow initiation from client to server, and not from client to client, server to server or server to client:

accept
   tseq nodetype 0
   and treq nodetype 1
;

(tseg = tag sender equals, and treq  = tag receiver equals, this is not yet described as an option in the manual. 

Again keep in mind to have your rules end with:

# Drop TCP SYN,!ACK packets (new connections) not explicitly whitelisted above
break                     # break can be overridden by a capability
  chr tcp_syn             # TCP SYN (TCP flags will never match non-TCP packets)
  and not chr tcp_ack     # AND not TCP ACK
;
accept

**Comment by luckman212** [comment]
@jdrews wrote:

> _"Setup a gateway machine running ZeroTier. Install a routing platform such as quagga on it and run a IGP (RIP, OSPF, etc) to route the ZeroTier network into your internal network. This is what we do in our office and it works well."_

I would really love to learn more about how you set that up (gateway/quagga/zerotier). Do you have a write-up with a bit more detail somewhere?
