### ISSUE TITLE
What is the UDP packet size for ZeroTier

### ISSUE THREAD

**Issue by dragonfax** [zerotier/ZeroTierOne#545]
What maximum UDP packet size does ZeroTier use? Is there a way to configure that? And will ZeroTier take a larger UDP packet and break it up into multiple smaller packets before sending it through the VPN?

I ask because I find that my ISP has issues with large (>500b) UDP packets at high bandwidths. I get massive packet loss if I have larger packets and I'm trying to send them at, say, 30Mbps. (re: video streaming).

ZT could solve a number of problems for me if I can have it stick to a max packet size of 500 or less bytes for the UDP packets it sends across the internet.

**Comment by LFlare** [comment]
I believe it cycles through a configured set of MTUs until it gets a connection...

**Comment by zielmicha** [comment]
Maybe just set MTU to 500 on the physical interface (e.g. `eth0` or `wlan0`)? That way ZeroTier won't be able to send bigger packets.

**Comment by LFlare** [comment]
@zielmicha Absolutely bad idea, limiting to 500 creates all sorts of packet fragmentation on the protocol level during the tunnelling. I agree with the current setup of having it start from the highest 2800 which then slowly cycles down.

**Comment by zielmicha** [comment]
If MTU >500 causes packet loss for @dragonfax  setup, it's reasonable to set it to 500 (only for him, not for everyone using ZeroTier!). TCP, at least, should cope.

**Comment by glimberg** [comment]
MTU is not currently customizable in ZeroTier, but is a planned feature for the future.  It will be on a per-network basis.

**Comment by dragonfax** [comment]
I didnt' seem to have any problem setting the MTU on its interface down. I
actually used it to test out some various UDP speeds.

**Comment by adamierymenko** [comment]
Setting MTU to 500 isn't something you can currently do. PMTU discovery might be implemented in the future. The current MTU is set to work over a variety of links including PPPoE/IPv6 (which is the worst case).

**Comment by adamierymenko** [comment]
It also enables fragment, which some paths will allow and allows it to work over some lower-MTU links.

**Comment by laduke** [comment]
I had this request from someone using ZT on AWS & Azure GPU instances for gaming 

> Either auto-config bandwidth/route/MTU optimizations, or let the user do it. Would be helpful to squeeze out the most bandwidth at the lowest latency for gaming and other latency+bandwidth dependent applications.

**Comment by dragonfax** [comment]
Thats what I'm using it for. It turns out lowering the MTU is just a weird
work-around for my real issue. Here's whats going on for me. And why this
really isn't a good solution anyways.

If I want to stream a game at 1080p and 30fps, then that manes I'm pushing
30Mbps of UDP. With a default packet size of, say, 1400 bytes. Thats a
frame every 16ms and 46 packets per frame.

Some router out there in between me and the rest of the world drops half of
these packets, if all 46 try to come through in just a millisecond or two.

On the other hand, if the packets are spread out over 5-10ms then they all
come down just fine. Not a single packet lost.

Dropping the MTU down low, forces a smaller packet size from the app, and
the more packets take a little longer to send. I'm not sure exactly why or
where, its just what happens in practice. That slowdown lets all the
packets through, just as before.

But of course, the proper solution, isn't to reduce the packet size, but
just have the client slow down a little bit. Not be in such a hurry to
deliver all those packets of each frame, within a millisecond.


interestingly, Parsec (the remote desktop client thats popular for this
kind of thing) does something slightly different. It still bursts all the
packets at once, with no rate limit. But implements a quick DTLS style
retransmit system, so it can retransmit the lost packets, a few
milliseconds later. This makes up for the packet loss as well. But is
unrelated to ZeroTier, of course.

**Comment by dragonfax** [comment]
Now a millisecond scale rate limit in Zerotier. that might be useful.
