### ISSUE TITLE
very unreliable behavior

### ISSUE THREAD

**Issue by bobbyvinon** [zerotier/ZeroTierOne#554]
i've created 3 virtual machines in parallels workstations for playing with zerotier (OS is ubuntu 16.04, all VMs are using bridged interface and have LAN ips).
one VM is configured as controller, and two VMs - clients (controller configured as moon for each client). i've created net on controller, added and authorized clients, they are received ip addresses. i've able to ping one client from another. but this configuration can work for 5 minutes and then stop working (client VMs can't ping each other), and after 10 minutes it can work again, etc. underlying network works without problems. i've built zerotier with ZT_DEBUG, but it doesn't give any errors to me. (in moments, when i can't ping another client, zerotier-cli shows that all is ok). i've built zerotier with ZT_TRACE, but it doesn't add any messages to debug output.

**Comment by LFlare** [comment]
Well, Moons should have static publicly faceable IPs as well as open `9993/udp` ports. You also need a minimum of `2` moons. You might want to just forsake the idea of running your own moons, if air gapping isn't your priority.
