### ISSUE TITLE
FreeBSD: ZT connection not re-established after killing & restarting ZT process

### ISSUE THREAD

**Issue by jungle-boogie** [zerotier/ZeroTierOne#555]
Hi,

I frequently build zerotier from the dev branch on FreeBSD/openBSD. After the build is complete, I would like to use the new binary so I perform the following:

1. Find zerotier process. this is reported in `ifconfig` so I can just run that.
2. kill the pid with sudo/doas
3. call the `zerotier -d` comamnd
4. check `ifconfig` and see if it's back online.

The last one is what usually fails for freeBSD.

The interface is created but it will eventually fail to connect:

just after `zerotier-one -d`:
```
zt000: flags=8842<BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 5000 mtu 2800
        options=80000<LINKSTATE>
        ether 5e:ee:cc:f1:47:2f
        inet6 fe80::2bd:8bff:feb4:6409%zt000 prefixlen 64 tentative scopeid 0x3
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
        media: Ethernet autoselect
        status: active
        groups: tap
        Opened by PID 60640
```

a few minutes later:
```
zt000: flags=8842<BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 5000 mtu 2800
        options=80000<LINKSTATE>
        ether 5e:ee:cc:f1:47:2f
        inet6 fe80::2bd:8bff:feb4:6409%zt000 prefixlen 64 tentative scopeid 0x3
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
        media: Ethernet autoselect
        status: no carrier
        groups: tap
```

just after `zerotier-one -d`:
```
% sudo zerotier-cli info
200 info aec9edd955 1.2.5 ONLINE
```

A few minutes after calling `zerotier-one -d`:
```
% sudo zerotier-cli info
0 info invalid JSON response ([json.exception.parse_error.101] parse error at 1: parse error - unexpected 'c')
```

Restarting the network with `service netif restart zt000` doesn't resolve this, either.

**Comment by jungle-boogie** [comment]
See similar issue:
https://github.com/zerotier/ZeroTierOne/issues/530

I am running
```
11.0-RELEASE-p9
11.0-RELEASE-p10
```

**Comment by jungle-boogie** [comment]
After rebooting my computer and running the process again, I see this:

```
% sudo zerotier-cli listnetworks
200 listnetworks <nwid> <name> <mac> <status> <type> <dev> <ZT assigned ips>
200 listnetworks eee  5e:1a:dc:f3:74:aa REQUESTING_CONFIGURATION PRIVATE ztebjbqjoe0ag2v -
```

Are there logs anywhere that can show what's actually happening?
Running `zerotier-one` in the foreground doesn't seem generate any logs.

**Comment by jungle-boogie** [comment]
Similar issue here: https://github.com/zerotier/ZeroTierOne/issues/406
Of course they're using a mac.

**Comment by jungle-boogie** [comment]
I have a feeling this either has something to do with zerotier queuing 
connections/rate limiting something, or it's a recent commit to dev.

I think this commit started causing the problems:
https://github.com/zerotier/ZeroTierOne/commit/a83c7c0d07d52027893b0676d4d8e1aa0426b5fd

Downgrading to these I was able to kill and start zerotier-one quickly with the 
connection being established each time. I killed/started about 6 times each within 
just a few minutes.

good:
https://github.com/zerotier/ZeroTierOne/commit/dab0fb9e05677bdc6294f196fcf8234892c582c1
https://github.com/zerotier/ZeroTierOne/commit/4cc773ec1bd768e8bc318135c548f94ae270e959
https://github.com/zerotier/ZeroTierOne/commit/ba6fd168235fac1c2ec029a49616510da56efe0f

**Comment by jungle-boogie** [comment]
I don't know what to tell you!
I'm back on the latest commit and I can connect.

Is it an issue with the ZT network at different times of the day?

**Comment by jungle-boogie** [comment]
Hi @dch, have you seen this problem before?

**Comment by dch** [comment]
On Fri, 14 Jul 2017, at 03:17, jungle-boogie wrote:
> After rebooting my computer and running the process again, I see this:
> 
> ```
> % sudo zerotier-cli listnetworks
> 200 listnetworks <nwid> <name> <mac> <status> <type> <dev> <ZT assigned
> ips>
> 200 listnetworks eee  5e:1a:dc:f3:74:aa REQUESTING_CONFIGURATION PRIVATE
> ztebjbqjoe0ag2v -
> ```
> 
> Are there logs anywhere that can show what's actually happening?
> Running `zerotier-one` in the foreground doesn't seem generate any logs.

jungle-boogie for debugging, I added this to the port but haven't done a
PR for it yet:

https://github.com/skunkwerks/ports/commit/3e25d95e10b2ec28a8503d4d34569498e3e0dbde
Once 11.1 is released I will wrap this in daemon(8) with the new options
to capture stdio and have it logged, but for the moment, just run in the
foreground aka without the `-d` flag. Copious output appears.

if you're building from source, use `gmake debug` as your target.

**Comment by jungle-boogie** [comment]
Thanks for the `gmake debug` trick. I'll start building from git dev like that going forward.

Although I don't use it, thanks for maintaining the zerotier port/package!

**Comment by jungle-boogie** [comment]
It seems that on a different system than what I was report about yesterday, I can only get connected to the ZT network with the debug version.

When it's made with debug, I can't really put ZT in the background, so what happens are all the debug statements are printed to standard out.
