### ISSUE TITLE
BUG bridge interface stops working after a few seconds after adding zt0 to it

### ISSUE THREAD

**Issue by bobbyvinon** [zerotier/ZeroTierOne#557]
i'm using small script to create linux bridge br0 and attach zt0 to it.
after creating br0 and attaching zt0 to it, it works for 10-20 seconds - then
bridged interface stops to answer for ping (but it still receives and routes packets to bridged interfaces). i've found that if i restart zerotier-one service after creating a bridge, it works without problems.

**Comment by bobbyvinon** [comment]
it's strange - but after restarting zerotier-one service br0 continues to answer on it's internal zerotier-ip even when zt0 not attached to it. if i attach zt0 again, br0 stops working in 10-20 seconds

**Comment by glimberg** [comment]
Hi Bobby,

I have some questions about your network.  It may be easier to figure this out if you hop on the chat widget on https://www.zerotier.com, or jump in the community chat room at the Community tab on https://my.zerotier.com

**Comment by bobbyvinon** [comment]
I've contacted Adam. We've discovered that zerotier corrupts routing table after zt0 attached to bridge.

**Comment by alpharde** [comment]
Umm I'm having this same problem (with openwrt).
What can I do to fix it?
