### ISSUE TITLE
Update Controller API documentation to reflect the current API

### ISSUE THREAD

**Issue by paulrd** [zerotier/ZeroTierOne#558]
I'v been trying to use the controller endpoint above. I have an active member count of 2, but I get 404 "Not Found" when I use the above endpoint. I'm using zerotier version 1.2.4 on Ubuntu.

**Comment by glimberg** [comment]
It looks like you've hit an issue where the documentation hasn't kept up with the code.  There's no code path in the controller to handle the `/active`  portion of the GET request.  Hence the 404.

Looks like we need to update the controller docs!

**Comment by paulrd** [comment]
Ah! Thanks. I might as well mention here that the 'routes' object format needs to be documented.

**Comment by blurredpixel** [comment]
@paulrd Yeah I agree I had to ask on the IRC about the format
