### ISSUE TITLE
Trusted path does not work for public ip's

### ISSUE THREAD

**Issue by janjaapbos** [zerotier/ZeroTierOne#561]
It appears that trusted paths only work for private ip ranges. Is this a bug or intentional? 

In case it is intentional: it should be documented, however there is a need to be able to define trusted paths for public ranges in a datacenter / vlan.

**Comment by adamierymenko** [comment]
I think it's a feature, not a bug, but I will check.

Planning to add encryption levels to networks that would obsolete this. You could set a network to not encrypt actual frame traffic, which would trade encryption for performance. It would partially obsolete trusted paths, though we'd leave them for cases where you also want to eliminate authentication on a private LAN.

Problem is that trusted paths over the Internet are extremely unsafe. Anyone could spoof, DOS, etc. you trivially.

**Comment by janjaapbos** [comment]
In this particular case it would be a public subnet that is located in our
own datacenter. Spoofing etc would be prevented by access list on our
router I would think.

Op 14 aug. 2017 20:48 schreef "Adam Ierymenko" <notifications@github.com>:

**Comment by adamierymenko** [comment]
I think I might take the training wheels off. If you define a trusted path over the public net then it's up to you to know what you're doing. :)

**Comment by janjaapbos** [comment]
Would be great if this can be done before the next release.

**Comment by adamierymenko** [comment]
Done in `dev`
