### ISSUE TITLE
bug with Display Filter in web UI

### ISSUE THREAD

**Issue by ronzil** [zerotier/ZeroTierOne#567]
Opened the "Members" part of my network in the web UI. 
Pressed the rightmost button (Hide? Tooltips would be helpful).

Can't see the computer again by pressing "Hidden" in the Display Filters. 
Furthermore, pressing and depressing the filters has a buggy beheviour that depends on the order on the pressed filters.
For example: Starting with no filters. Selecting "Authorized" then "Not Authorized" shows my computers. However selecting "Not Authorized" and then "Authorized" does not. (Also note that in the first example, the computer is Authorized but is displayed only after selected "Not Authorized").

**Comment by adamierymenko** [comment]
I wasn't able to duplicate any of these issues. What browser are you using?
