### ISSUE TITLE
Doesn't work when tethering?

### ISSUE THREAD

**Issue by jb55** [zerotier/ZeroTierOne#568]
For some reason zerotier never seems to work when wifi tethering with my phone (android 7.1.2, pixel xl, vpn turned off on the phone). Although it works fine when I'm connected to non-tethered wifi? Does anyone else have this problem?

Version: `1.2.4`

**Comment by jb55** [comment]
Hmm but seems to work when tethered with iphone...

**Comment by nate8199** [comment]
I've never had an issue with a nexus5x on ATT or and iPhone 5,5s,7 on VZW,
with Windows, Linux, or a chromebook(crouton)

**Comment by jb55** [comment]
now it's working ... ¯\_(ツ)_/¯
