### ISSUE TITLE
Running binary differs from the one on disk, firewall doesn't like it

### ISSUE THREAD

**Issue by mikaeleiman** [zerotier/ZeroTierOne#570]
Running on macOS using the Little Snitch firewall, I get this message about connection attempts made by zerotier:

"The running process differs from the version on disk. 
They both have a code signature, but they use different identifiers. 
This means that the running process was possibly maliciously modified."

I haven't upgraded Zerotier while running it, so this seems like something that shouldn't happen. Is there anything "creative" the zerotier program does that could cause this?

**Comment by adamierymenko** [comment]
I don't know how this could be happening. The binary doesn't self-modify. Can you provide a little more info?

**Comment by mikaeleiman** [comment]
I happened to read this in the Little Snitch documentation:

"When a rule is matched against a process, the in-memory code signature of the process is used, not the code signature on disk. This has two consequences:

    Modifications of the process are detected, even if they have been made dynamically in-memory only, e.g. by loading an untrusted library or by code injection.
    Application resources are not checked, only the code executed. Verifying an application‘s resources may take minutes to complete for large applications such as Xcode. Doing that on every data packet transferred is simply not possible. Verifying the executable code costs no time because the macOS kernel caches this information anyways."

So perhaps it's some lib you're loading that causes the problem.

**Comment by adamierymenko** [comment]
Which binary is it? The UI or the service?

**Comment by mikaeleiman** [comment]
I assume it's the service, since it wants to connect to random things on random ports.

**Comment by adamierymenko** [comment]
Any more info about this? The binary doesn't self-modify, so it's rather puzzling.
