### ISSUE TITLE
Issue with Port!!

### ISSUE THREAD

**Issue by Syntist** [zerotier/ZeroTierOne#572]
I am facing issue with port, my friend router doesn't have upnp support so i need to port forward the port manually, But the problem is i can't change the port.

For Example:

On My Computer
![image](https://user-images.githubusercontent.com/24858150/29750778-7f543776-8b5f-11e7-950a-c06e70d19427.png)

But according to zerotier-one
my default port is 9993
![image](https://user-images.githubusercontent.com/24858150/29750791-b2475d8e-8b5f-11e7-80e9-f4b2f3190ba8.png)

So when i try to change the port
`C:\ProgramData\ZeroTier\One>zerotier-one_x64.exe -p 8999
zerotier-one_x64.exe: unable to start service (try -h for help)`

If i am able to change the port will zerotier service upnp the given port? or still random?

**Comment by adamierymenko** [comment]
You can change the port by creating a local.conf file, but I'm not sure why this is needed. Is it unable to cross the router without a rule?

**Comment by Syntist** [comment]
I don't know but he was able to ping me but i can't, i am trying to play online game through virtual lan, Evolvehq works fine don't know what the problem here.

**Comment by laduke** [comment]
Hi @Syntist,  hop in our chat https://my.zerotier.com/ -> Community
