### ISSUE TITLE
Support pluggable synchronization methods

### ISSUE THREAD

**Issue by gdamore** [zerotier/ZeroTierOne#574]
This relates to the libzerotiercore stuff in the dev branch.

It turns out that for some platform ports, or even particular applications, it would be desirable to make use of alternate application-supplied synchronization methods.  This would allow application ports to operating systems that are far outside of the current supported set (think systems without pthreads primitives, like VxWorks), allow the use of alternative debugging primitives, or in the case where the application guarantees single-threaded access to ZeroTier (e.g. via an external lock), for the primitives to simply be NO-OPs.

I believe the best way to do this is to extend the current ops vector for this with entry points for lock and unlock, but also lock allocation/deallocation.  This might be something to look at while you are working on #573

**Comment by adamierymenko** [comment]
If this is done it should be done at compile time, not run time, since the latter imposes an indirection for every single lock/unlock.

**Comment by gdamore** [comment]
Agreed!

**Comment by gdamore** [comment]
Although, compared to the cost of almost everything else including the
underlying atomic op the indirection hurts far less. zerotier itself has
far worse performance problems (including lack of separation of send and
receive side locks leading to increased contention. )

**Comment by adamierymenko** [comment]
Closing because the only synchronization in the core is `Mutex.hpp` and this could easily be special-cased. If an `#ifdef` is wanted to include e.g. an external `Mutex` implementation, this is an easy PR. Otherwise having Mutex be inline is important for performance and we don't want it to be e.g. a function pointer.
