### ISSUE TITLE
Recently older (<= 1.1.4) versions of Zerotier unable to get network configuration

### ISSUE THREAD

**Issue by cyph84** [zerotier/ZeroTierOne#576]
I noticed that recently (probably happening for 1 - 2 weeks before today) that older versions of Zerotier are unable to join or re-connect to networks. This is happening to hosts that were not upgraded since they were installed and setup (and working) years ago.

The breakage seems to happen between commits eb4a78bc (good) and f41ea24e (bad). 

Symptoms are:

```
# ./zerotier-cli info
200 info XXXXXXXXXX ONLINE 1.1.5

```

```
# ./zerotier-cli listnetworks
200 listnetworks <nwid> <name> <mac> <status> <type> <dev> <ZT assigned ips>
200 listnetworks 93afae5963XXXXXX - XX:XX:XX:XX:XX:XX REQUESTING_CONFIGURATION PRIVATE zt1 -
```

Compiling f41ea24e with debugging produced the following suspicious lines in the log:
```
[Thu Aug 31 15:02:16 2017] node/IncomingPacket.cpp:671 dropped NETWORK_MEMBERSHIP_CERTIFICATE from ecfeb6549b(45.32.248.87/9993): unexpected exception
[Thu Aug 31 15:02:16 2017] node/IncomingPacket.cpp:671 dropped NETWORK_MEMBERSHIP_CERTIFICATE from 3f39df0c9a(45.32.248.87/9993): unexpected exception
```

**Comment by Arffeh** [comment]
Can confirm, unfortunately. :)

**Comment by laduke** [comment]
@cyph84 @Arffeh please check again :)

**Comment by cyph84** [comment]
Older versions working again. Thanks!
