### ISSUE TITLE
Unexpected results when using flags with certain rules

### ISSUE THREAD

**Issue by ghost** [zerotier/ZeroTierOne#577]
The following rule does not behave as I would expect it:

```
tag tag_1
	id 2000
	default 1
	
	flag 0 A
	flag 1 B
	flag 2 C
	flag 3 D
;

accept
  not tor tag_1 0
  and not tand tag_1 0
;

drop;
```

The goal is to let two machines communicate if they have an overlapping bit for `tag_1`. So if one machine has a decimal value 3 (flag A+B) for tag_1, and one has decimal value 1 (flag A), they should be able to communicate. However, they should not be able to communicate if either of them have any bits set.

I have written the following javascript which attempts to assert that the above rule does what I expect, which it seems to:

```javascript
function check(A, B, expected) {
    var c1 = !((A|B)==0); // not tor tag_1 0
    var c2 = !((A&B)==0); // not tand tag_1 0

    var R = c1 && c2;
    console.log(expected == R ? "OK" : "FAIL", A, B, R, c1, c2);
}

check(0b0001, 0b0001, true);  // OK 1 1 true true true
check(0b0011, 0b0001, true);  // OK 3 1 true true true
check(0b0010, 0b0001, false); // OK 2 1 false true false
check(0b0000, 0b0000, false); // OK 0 0 false false false
```

The problem is when I change the flags that are assigned to a machine. The application of the rules does not seem to change, or it takes 12-24 hours. Or sometimes it seems to change for some machines, yet not others. The behavior is quite unpredictable.

I have discussed this on the IRC before:

* https://hastebin.com/amomadacuf.txt

* https://hastebin.com/apipididop.txt

**Comment by r04r** [comment]
@adamierymenko Since this got tagged as a question, can you confirm I am not running into any bugs?

**Comment by AlessandroPerucchi** [comment]
links in hastebin not working anymore.

**Comment by r04r** [comment]
@AlessandroPerucchi Yikes, sorry about that. I've dug through my IRC logs and reuploaded here: https://gist.github.com/r04r/5dea46110f28b7ef9bc906ac5a9c5fc3

**Comment by joseph-henry** [comment]
@r04r sorry this has taken so long, we aren't ignoring it. I'll try to dig into this next week. I know this issue has been outstanding for some time now.

**Comment by adamierymenko** [comment]
Flagging as potential bug so we look at it before 1.2.6

**Comment by joseph-henry** [comment]
@r04r I know we were able to replicate this once before a couple months ago but it seems to work well now. 

After updating the bit flags, give it up to 1 minute to propagate through the network.

If you experience this issue again please let us know which controller your network is on. It might be a performance issue we can look into.

**Comment by r04r** [comment]
@joseph-henry This appears to still be an issue. Just tried again on a newly created network. How do I tell what controller it is on? The steps I take are:

1. Create a new network

2. Paste in the ruleset from above

3. Join three machines to the network, and have them ping each other while occasionally clicking a checkbox on the network overview page on my.zerotier.com

**Comment by joseph-henry** [comment]
Closing due to age. We will likely revamp the rules engine sometime after the 2.0 release. If it continues to be a problem after that point feel free to reopen this issue. Thanks.
