### ISSUE TITLE
FreeBSD Zerotier intermittently trying to use route which crosses ZeroTier interface

### ISSUE THREAD

**Issue by obrienmd** [zerotier/ZeroTierOne#579]
***Edited*** After quite a bit of flailing, connection loss seems to be caused by ZeroTier trying to send ZeroTier traffic to a peer using a route which has a next hop inside the ZeroTier tunnel itself. The fact that connections were dying under load may simply have been easier detection with constant traffic running, but I was never able to reproduce it with constant pings, even for hours at a time.

Hardware: Virtual Machine (Hyper-V), Xeon E3-1245v5 and E5-2670 (tried both), 4GB RAM
FreeBSD 11.0-RELEASE-p12 (OPNSense 17.7.1 distribution)
Zerotier One 1.2.4 (OPNSense Zerotier plugin 1.0.0)

When the Zerotier network between two of these boxes is under heavy load (100+ mbps, large packets):
- After between ~1 and ~3 minutes (seems different each time)
- All traffic stops (in iperf3, manifests as 'connection reset by peer' or 'control socket has closed unexpectedly')
- The zerotier-one process goes from 20-40% (normal) CPU to 99% CPU on the device originating connection (other side seems fine)
- Connections across the zerotier network between these two hosts does not work for about 30 seconds, then all is well again

Also reported in OPNSense plugin: https://github.com/opnsense/plugins/issues/251

**Comment by obrienmd** [comment]
Looks like @dch is adding a debug option for zerotier-one running in the foreground:
https://github.com/skunkwerks/ports/commit/e9582cd4
https://github.com/opnsense/plugins/issues/251

I'm going to give it a shot as soon as it's available in binary form (in ports or on its own).

**Comment by obrienmd** [comment]
Installed @dch's debug port. After a few tests, it looks like I'm getting **massive** repetitions of these messages on their respective sides when connections break:

**On sending side:** 
[Tue Sep 12 16:17:24 2017] node/Peer.cpp:190 got HELLO via unknown path {{other side ZT id}}({{other.side.ip.address}}/64130), confirming...
**On receiving side:** 
[Tue Sep 12 16:17:24 2017] node/IncomingPacket.cpp:485 {{other size ZT id}}
({{other.side.ip.address}}/37530): OK(HELLO), version 1.2.4, latency 72

**Comment by obrienmd** [comment]
Let me know if there's anything else I can provide that would be helpful. I have two OPNSense boxes right now that are basically dedicated to being able to troubleshoot this.

**Comment by obrienmd** [comment]
More debugging of my personal Moby Dick today.

This time I was running tcpdump on the interfaces. Interestingly, when I see the connections "die", it looks like Zerotier is trying to make Zerotier connections over IPs which are only able to connect to each other over the Zerotier tunnel:

18:57:33.158371 IP {{private IP of this side}}.9993 > {{private IP of the other side}}.9993: UDP, length 1444
18:57:33.158386 IP {{private IP of this side}}.9993 > {{private IP of the other side}}.9993: UDP, length 1444
18:57:33.158400 IP {{private IP of this side}}.9993 > {{private IP of the other side}}.9993: UDP, length 1444
18:57:33.158414 IP {{private IP of this side}}.9993 > {{private IP of the other side}}.9993: UDP, length 1444
18:57:33.158429 IP {{private IP of this side}}.9993 > {{private IP of the other side}}.9993: UDP, length 1444
18:57:33.158443 IP {{private IP of this side}}.9993 > {{private IP of the other side}}.9993: UDP, length 1444
18:57:33.158457 IP {{private IP of this side}}.9993 > {{private IP of the other side}}.9993: UDP, length 1444

I'm routing traffic between LANs either dynamically or statically (have tried both) over the ZT tunnel. So, my ZT endpoints are all routers. That a tcpdump normally showing "real" traffic over the ZT tunnel would start showing ZT connection attempts strikes me as incredibly weird, as ZT traffic is normally just sent WAN to WAN, and of course LAN to LAN isn't going to work (and why is it trying).

I can't quite get my head around this yet... Pointers in the right direction encouraged :)

**Comment by obrienmd** [comment]
More testing - after removing any routes for internal traffic, the link performs perfectly. I'm not actually sure it was load condition, just perhaps more detectable under load, or perhaps it was load causing some packet loss (i.e. good TCP behavior somewhere) and causing ZeroTier to look for a new path, which it "found" across the tunnel link across the route to the other LAN network.

I'm going to link this back up with the OPNSense ticket - I think it makes sense to have that package (by default or option), given it's meant specifically for routers, and this seems a likely use-case for routers, use local.conf to blacklist LAN networks.

**Comment by janjaapbos** [comment]
I think the zerotier service prevents the use of tap and zerotier devices for communication with peers using a device name filter somewhere in the code. This might need to be adapted for freebsd, if the naming is different? Meanwhile using local.conf to blacklist networks is a good workaround.

**Comment by obrienmd** [comment]
That makes sense, but does/can it go so far as to say "if the path to this network crosses this interface, drop the packet"? It's sending from an IP on the local LAN interface, but the next hop into the far-side local LAN interface is the Zerotier device.

**Comment by janjaapbos** [comment]
No I don't think so. Though at the other end it would see a local zerotier interface and drop it. Anyway, have to check how and whether this is actually is done in the code.

**Comment by obrienmd** [comment]
I added a local.conf in /var/db/zerotier-one in OPNSense (based on FreeBSD 11). I would expect it to get picked up by the zerotier-one daemon, but either it's not, or that's not fixing the problem. I still get 9993 traffic traversing the zerotier tunnel between two 192.168.x.0/24 LANs, though I have RFC1918 space completely blacklisted in local.conf (I think):

{
    "physical": {
        "10.0.0.0/8":
            "blacklist": true
        },
        "192.168.0.0/16":
            "blacklist": true
        },
        "172.16.0.0/12":
            "blacklist": true
        }
    }
}

**Comment by obrienmd** [comment]
Fixed previous comment, was incorrect as my initial config had a mistype.

**Comment by obrienmd** [comment]
Another update - the intermittent usage of the wrong route indeed looks corrected with the local.conf file, but high load still shows major packet loss and TCP resets. I believe it might be something going on in packet processing on the routers (which are connected via ZT), which I'm chasing on the OPNSense side:

https://github.com/opnsense/plugins/issues/251
