### ISSUE TITLE
Cannot connect two apps on host when on mobile network

### ISSUE THREAD

**Issue by gdamore** [zerotier/ZeroTierOne#583]
This past weekend I was trying to debug my ZeroTierOne app while in a car using a mobile network (tethered).  The app runs using it's own ZT node (via ZT_node_create()), and I was trying to send L2 hosts to the hypervisor.  I noticed that none of the packets seemed to get through.  I was using an iPhone 7 on Verizon's network as the tether device (WiFi access point).  I did have outside network connectivity (verified by accessing external web pages, etc.)

The same configuration works fine on my home network.  (Was in a car on the way to vegas, working enroute. ;-)

**Comment by gdamore** [comment]
This is still happening -- noticed while trying to test remotely again today. :(

**Comment by adamierymenko** [comment]
It's possible that your WiFi hotspot implements 'local isolation' -- forbids peer to peer communication over WiFi. Try direct pings.
