### ISSUE TITLE
Want opportunistic node deletion hint

### ISSUE THREAD

**Issue by gdamore** [zerotier/ZeroTierOne#584]
For various reasons (testing mostly), it would be convenient to be able to delete nodes from a network and have the controller (ZeroTier Central) remove the record of the node's existence.

Background: We create ephemeral nodes (no backing store) each time we run our test app.  This works, but would be great to strip the record of those nodes when the app shuts down, since the keys won't persist.

Alternatively, would be nice to be able to delete nodes that are not active (online, or at least not recently online) from the ZeroTier central page.

**Comment by themisanthrope** [comment]
This or something like it would be really useful.

I can think of two ways to do this;
- Have the ability for a client to tell the controller it is leaving and will never return (ephemeral OS instances, etc.); maybe have an option on the controller to allow the network owner to choose whether these messages are acted upon
- Make the controller able to optionally prune entires for devices that haven't been seen for `x` amount of time; hours or days, depending on the use case (in corporate SDN or VPN setups, admins don't always remember to remove decommissioned, lost or stolen devices)

**Comment by adamierymenko** [comment]
The node view is being redone.
