### ISSUE TITLE
Missing Tools - Windows Binaries

### ISSUE THREAD

**Issue by tberto** [zerotier/ZeroTierOne#587]
I've scoured the documentation, but I cannot find the "Zerotier-idtool" executable on windows, nor can I find references to the controller SQL script.  It looks like Mac and Linux have these. 

Are the Windows tools missing?  I'm looking to create controllers and moons on Windows devices but cannot figure out how to.

**Comment by janjaapbos** [comment]
For windows, there is one cli executable in c:\ProgramData\ZeroTier\One called zerotier-one_x64.exe

It must be run as administrator. To see the options, use the -h switch.

With the -i switch it functions as the idtool.

**Comment by tberto** [comment]
@janjaapbos thank you for the quick response!  It does work too!  How about the controller scripts?  Can you make a Windows PC a controller as well?

**Comment by janjaapbos** [comment]
Yes, I think so. But there is no cli / script for the controller bundled. You can use JSON REST calls. See https://github.com/zerotier/ZeroTierOne/tree/master/controller

Since you are on windows, perhaps look at using Powershell for these calls. Something like https://www.lavinski.me/calling-a-rest-json-api-with-powershell

**Comment by tberto** [comment]
You're a steely eye'd missile man!  I also found http://www.swensensoftware.com/im-only-resting which looks like it would work.

Is it safe to assume, if I'm trying to create a standalone deployment, I'd need to create a moon and that moon would know where the controller is for a certain network?  Meaning if I'm in an air-gapped environment, the public root servers wouldn't know about my controller or network.

**Comment by janjaapbos** [comment]
Air-gapped Windows? Just kidding... ;-)

Not sure how far you will get with no connection to public roots at all. I think for sure all the clients and controllers involved would then at least need to reference the same moon.

Just post again at Github when you encounter issues.

**Comment by fathermrsing** [comment]
@tberto @janjaapbos  hello,for windows,i tried generate identity.public file with the way  "With the -i switch it functions as the idtool",but nothing output  ,could you please give me a hand and tell me how to do details ?thank you !!

**Comment by fathermrsing** [comment]
@tberto @janjaapbos  hello,for windows,i tried generate identity.public file with the way "With the -i switch it functions as the idtool",but nothing output ,could you please give me a hand and tell me how to do details ?thank you !!in the cmd ,my command :
zerotier-one_x64.exe -i generate identity.secret
