### ISSUE TITLE
PORT_ERROR on MacOS

### ISSUE THREAD

**Issue by lqhl** [zerotier/ZeroTierOne#591]
I installed ZeroTier v1.2.4 on MacOS 10.12.6, and got`PORT_ERROR`.
It works fine on my Ubuntu and Android phone.

**Comment by lqhl** [comment]
I uninstall zerotier using `/Library/Application Support/ZeroTier/One/uninstall.sh` and reinstall it. Then it works fine.
Maybe the problem is that I upgrad zerotier from an old version.

**Comment by gsomoza** [comment]
I had a similar issue but uninstalling didn't help. Here's what helped: https://github.com/zerotier/ZeroTierOne/issues/467#issuecomment-365861944

**Comment by EskelCz** [comment]
Check out security preferences, it may need a permission to open the port
