### ISSUE TITLE
TX scatter / zero-copy networking

### ISSUE THREAD

**Issue by gdamore** [zerotier/ZeroTierOne#595]
I have a message (possibly a large one) made of up of many subordinate parts -- for example I may a have a 10 MB message, that I'm going to send as a bunch of "fragments" -- where one part is a user payload and the other part is my fragmentation / protocol header.

It would be helpful (faster!) if I didn't have to submit the data I'm sending as a single chunk, but could instead use an iov style approach.  (Note that in order to be portable ZT should define its own IO vector, rather than just using POSIX or Windows scatter structures.)

This would eliminate an entire data copy for my application.

**Comment by gdamore** [comment]
It strikes me that this may be difficult, because zero copy would also need to have support from the bottom half of the API -- i.e. we would need to support scattering in the underlying UDP transport.  Most systems can do this, but the support is absent in the physical frame API.

**Comment by adamierymenko** [comment]
Yes, and we have other interest in this too. I think we should look at this but not for the next version.

**Comment by adamierymenko** [comment]
Much of this is in 2.x
