### ISSUE TITLE
CMake FTW!

### ISSUE THREAD

**Issue by gdamore** [zerotier/ZeroTierOne#596]
Building on Windows or other systems is a bit byzantine, and its made somewhat more complex by the different makefiles.

It would be really really useful to me if I could build at least the libzerotier.a bits using a CMake... heck it would make it easier to make this project a subordinate project.  Please?!!??

**Comment by adamierymenko** [comment]
We're considering this, so maybe so. The existing makefile system is there because I loathe autoconf, but cmake is a bit cleaner and is becoming kind of standard in the C++ world.

**Comment by joseph-henry** [comment]
I've written a pretty simple CMake script to build just `libzerotiercore.a` and put it in `dev`. We'll expand its set of targets later.
