### ISSUE TITLE
ZeroTier one may be leaking sockets

### ISSUE THREAD

**Issue by alexforencich** [zerotier/ZeroTierOne#597]
I recently installed ZeroTier One on a VPS that's running under OpenVZ.  Shortly after, the server started ending up in an unusable state - fastcgi and sshd complaining about not being able to open sockets:

    2017/09/30 17:43:09 [alert] 21870#0: *94759 socket() failed (12: Cannot allocate memory) while connecting to upstream, client: xxx.xxx.xxx.xxx, server: xxxxxx.com, request: "GET /xxx/xxx/xxx HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "xxxxxx.com"

and

    sshd[459]: error: reexec socketpair: Cannot allocate memory

I ended up leaving a mosh session open with a root shell running (I tried without a root shell running, but PAM was failing and preventing console logins, sudo, and su) and I finally traced the issue back to a limit issue.  Apparently the instance has a limit 'numothersock' of 500, with all 500 used.  Upon killing zerotier-one, the number dropped to 70.  I presume that zerotier-one doesn't need 430 sockets open at once with a network with less than 10 nodes, so my conclusion is that zerotier-one may be leaking sockets.

**Comment by adamierymenko** [comment]
It really should not use that many sockets. What does `lsof` show for the ZeroTier process?

**Comment by alexforencich** [comment]
Let me check.  Reinstalling it now, may have to wait a day or two to see what happens.

**Comment by alexforencich** [comment]
After running for a few hours, lsof seems to show a bunch of these stacking up:

    zerotier- 16951 root   19u  sock       0,6      0t0 729706119 can't identify protocol 
    zerotier- 16951 root   20u  sock       0,6      0t0 729766216 can't identify protocol 
    zerotier- 16951 root   21u  sock       0,6      0t0 729826446 can't identify protocol 
    zerotier- 16951 root   22u  sock       0,6      0t0 729882892 can't identify protocol 
    zerotier- 16951 root   23u  sock       0,6      0t0 729937746 can't identify protocol 
    zerotier- 16951 root   24u  sock       0,6      0t0 729987816 can't identify protocol 
    zerotier- 16951 root   25u  sock       0,6      0t0 730038757 can't identify protocol 
    zerotier- 16951 root   26u  sock       0,6      0t0 730084218 can't identify protocol 
    zerotier- 16951 root   27u  sock       0,6      0t0 730130972 can't identify protocol 
    zerotier- 16951 root   28u  sock       0,6      0t0 730177242 can't identify protocol 
    zerotier- 16951 root   29u  sock       0,6      0t0 730221712 can't identify protocol 
    zerotier- 16951 root   30u  sock       0,6      0t0 730264273 can't identify protocol 
    zerotier- 16951 root   31u  sock       0,6      0t0 730310323 can't identify protocol 
    zerotier- 16951 root   32u  sock       0,6      0t0 730354919 can't identify protocol 
    zerotier- 16951 root   33u  sock       0,6      0t0 730402132 can't identify protocol 
    zerotier- 16951 root   34u  sock       0,6      0t0 730455191 can't identify protocol 
    zerotier- 16951 root   35u  sock       0,6      0t0 730510973 can't identify protocol 
    zerotier- 16951 root   36u  sock       0,6      0t0 730561408 can't identify protocol 
    zerotier- 16951 root   37u  sock       0,6      0t0 730608384 can't identify protocol 
    zerotier- 16951 root   38u  sock       0,6      0t0 730660413 can't identify protocol 
    zerotier- 16951 root   39u  sock       0,6      0t0 730708924 can't identify protocol 
    zerotier- 16951 root   40u  sock       0,6      0t0 730760319 can't identify protocol

**Comment by janjaapbos** [comment]
It would be good to see in what state the sockets are. Perhaps they are not cleaned up by the OS. 

E.g. netstat -aA inet

**Comment by alexforencich** [comment]
Today it's up to file descriptor 337.  Still hasn't hit the limit yet, but it's getting there.  

The 'leaked' sockets do not appear in netstat -aA inet (there are far less than 300 entries in that list, anyway)

**Comment by adamierymenko** [comment]
It looks as if it's building up UDP sockets, but the "can't identify protocol" descriptions make me wonder. In any case I think we'll take a look at the possibility of UDP sockets not being closed.

**Comment by joseph-henry** [comment]
I suspect it might have to do with our usage of libnatpmp. I've committed a patch to make sure the socket that libnatpmp opens upon initialization is closed in the event of failure.

Try pulling latest `dev` and giving that a shot.

**Comment by adamierymenko** [comment]
Closing since I think this is fixed in `dev`.
