### ISSUE TITLE
Missing rpm for aarch64

### ISSUE THREAD

**Issue by leleobhz** [zerotier/ZeroTierOne#598]
Hello,

I'm testing Fedora 27 with http://dl.fedoraproject.org/pub/fedora-secondary/releases/test/27_Beta/Spins/aarch64/images/ ( Docs in https://fedoraproject.org/wiki/Architectures/ARM/Raspberry_Pi ) but from repository, I see the following issue:

```
[root@haslam ~]# curl -s https://install.zerotier.com/ | sudo bash

*** ZeroTier One Quick Install for Unix-like Systems

*** Tested distributions and architectures:
***   MacOS (10.7+) on x86_64 (just installs ZeroTier One.pkg)
***   Debian (7+) on x86_64, x86, arm, and arm64
***   RedHat/CentOS (6+) on x86_64 and x86
***   Fedora (16+) on x86_64 and x86
***   SuSE (12+) on x86_64 and x86
***   Mint (18+) on x86_64, x86, arm, and arm64

*** Please report problems to contact@zerotier.com and we will try to fix.

*** Detecting Linux Distribution

*** Found Fedora, creating /etc/yum.repos.d/zerotier.repo

*** Installing zerotier-one package...
Failed to set locale, defaulting to C
ZeroTier, Inc. RPM Release Repository                                                                                 2.9 kB/s | 1.5 kB     00:00    
Last metadata expiration check: 0:00:02 ago on Fri Oct  6 20:36:46 2017.
Error: 
 Problem: conflicting requests
  - package zerotier-one-1.2.4-1.el7.centos.i686 does not have a compatible architecture
  - package zerotier-one-1.2.4-1.el7.centos.x86_64 does not have a compatible architecture

*** Package installation failed! Unfortunately there may not be a package
*** for your architecture or distribution. For the source go to:
*** https://github.com/zerotier/ZeroTierOne

```

Here is my specs:

```
[root@haslam ~]# hostnamectl 
   Static hostname: haslam.<hidden>
         Icon name: network-server
           Chassis: embedded
        Deployment: development
        Machine ID: e32acc66546946d9a3725d23510bdb1a
           Boot ID: 8181c13eb3a7431c8cee17eaadddf1bd
  Operating System: Fedora 27 (Twenty Seven)
       CPE OS Name: cpe:/o:fedoraproject:fedora:27
            Kernel: Linux 4.13.3-300.fc27.aarch64
      Architecture: arm64

[root@haslam ~]# uname -a
Linux haslam.<hidden> 4.13.3-300.fc27.aarch64 #1 SMP Wed Sep 20 16:36:35 UTC 2017 aarch64 aarch64 aarch64 GNU/Linux
```

Thanks!

**Comment by leleobhz** [comment]
P.s: I see Debian does have an aarch64 package, so this is why Ive decided to open the bug report.

**Comment by adamierymenko** [comment]
We'll be updating these with the next release, which will be pretty soon.

**Comment by leleobhz** [comment]
Hello,

Just a note about the importance of this issue: https://docs.fedoraproject.org/f27/release-notes/sysadmin/ARM_Architectures.html

> Fedora now includes disk images for 64 bit ARM (aarch64) Single Board Computer (SBC) devices, for example the Pine64 or Raspberry Pi 3. In the same manner as for the ARMv7 SBC images, there will be a single disk image for each of Fedora’s Minimal, Server and Workstation Editions that will cover all supported devices.

So now we have for aarch64:

* ArchLinux (And I've fixed the PKGBUILD for it in https://github.com/leleobhz/archlinux-zerotier-one/blob/master/PKGBUILD (And sent for upstream in https://aur.archlinux.org/packages/zerotier-one/ comments)
* SuseLinux
* Fedora 27

I think the last two, can be easly built and can share same spec. Its important to depend on system miniupnpc/natpmp with patch Ive sent in https://github.com/zerotier/ZeroTierOne/issues/617 to allow a lower fingerprint and performance)

Thanks!

**Comment by bartmichu** [comment]
Hello. Still no rpms for aarch64, tested on openSUSE Leap 15.2. Any chance you would add these packages?
