### ISSUE TITLE
Too long delay to working

### ISSUE THREAD

**Issue by jackyzhao010** [zerotier/ZeroTierOne#599]
I have setup my_network and configured without any problem.  I can use my laptop to communicate with the workstation with low delay (about 5ms) in the same Local Area Network (LAN). However, the delay is too long (about 1000ms), when the laptop and the workstation in the different network.
 Could anyone give me some suggestions?
Now, I can use teamviewer with a faster response in the same different network.

<img width="1280" alt="2017-10-09 4 33 51" src="https://user-images.githubusercontent.com/32634018/31330688-f500ac1a-ad11-11e7-8f31-a312bcfddaae.png">

**Comment by laduke** [comment]
How long are you at the second location before you try pinging? Do you now anything about how the second network is configured?
