### ISSUE TITLE
Doesn't Build on Raspberry Pi3 Arch

### ISSUE THREAD

**Issue by Choco31415** [zerotier/ZeroTierOne#601]
I've tried searching Google and this repository's issues for anything similar. I've found nothing.

When I download this repo and run makepkg -si on it, I get this output:

```
make-linux.mk:162: *** FATAL: architecture could not be determined from gcc -dumpmachine: C_MACH. Stop.
==> ERROR: A failure occurred in build()
    Aborting...
```

Running gcc -dumpmachine yields:

```armv7l-unknown-linux-gnueabihf```

Looking at make-linux.mk, it appears armv7 is supported. armv7l stands for "ARMv7 VMSA Long Descriptor Translation Table Format", which adds extra features on top of armv7 for virtual machine usage [docs](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dai0425/BABCDECH.html). It appears my setup is supportable too.

**Comment by laduke** [comment]
@Choco31415 What if you `make linux` ? Isn't `makepkg -si` for when you have an Arch Linux PKGBUILD ? Or use the curl | bash script on the downloads page? 

I'm running this on a Pi3, but just using the curl | bash. I've also used the arch package, but on x86.

**Comment by Choco31415** [comment]
@laduke:

The download page curl/bash script points me to the AUR repository:

```
*** Package installation failed! Unfortunately there may not be a package
*** for your architecture of distribution. For the source go to:
*** https://github.com/zerotier/ZeroTierOne
```

Yes, I was originally building from AUR. However, using just "make" with the Github repo has the same error. "make -f make-linux.mk" fails too.

"make linux" fails differently:

`make: *** No rule to make target 'linux'. Stop.`

**Comment by laduke** [comment]
sorry, I was thinking about a different repo... `make one`

**Comment by Choco31415** [comment]
The command generates a bunch of output, as with a usual `make` command; and ends with:

```
...
strip --strip-all zerotier-one
ln -sf zerotier-one zerotier-idtool
ln -sf zerotier-one zerotier-cli
```

Running `make install` and restarting shows that ZeroTier is installed.

**Comment by zscorpio** [comment]
It seems still not solved?
Linux centos-rpi3 4.9.80-v7.1.el7 #1 SMP Thu Mar 15 13:29:03 UTC 2018 armv7l armv7l armv7l GNU/Linux

make run
```
make-linux.mk:211: *** FATAL: architecture could not be determined from clang -dumpmachine: C_MACH
```
