### ISSUE TITLE
Zerotier on Chromebook 

### ISSUE THREAD

**Issue by plieningerweb** [zerotier/ZeroTierOne#602]
I installed zerotier for Android on Chromebook.
I Can go online and join the network, but ping will not work to other computers in network.

How can I get access to my zerotier network on a Chromebook?

**Comment by nate8199** [comment]
My method was through crouton, install it in there, it won't run
automatically, have to manually start it after entering chroot, and then go
back to chromeos and assign a static IP to the ethernet device that shows
up.

**Comment by plieningerweb** [comment]
I don't agree to close it without full answer. Crouton should not be the
goto solution on a Chromebook, it is essentially installing a second os and
less secure / good than a native solution. So if you are not willing to
support it, it's also fine with me. But I would expect a decision here.

**Comment by interoperate** [comment]
Agree with @plieningerweb 

Installing Crouton is a kludge workaround that is not suitable for the vast majority of Chromebook users, nor is the Android app that is still not supported on the vast majority of Chromebooks.

Given the massive uptake of Chromebooks in the education market, a "native" ChromeOS solution for Zerotier will be necessary. Therefore it would be useful to have an official statement on support plans for ChromeOS.

**Comment by laduke** [comment]
@plieningerweb @interoperate do you know if any other VPN software works on ChromeOS? ZeroTier needs access to low level system/network stuff that I'm not clear (not being an android dev) ChromeOs allows.

**Comment by plieningerweb** [comment]
I am not sure how it works. I only remember that a quick Google search
revealed that Chromebook only supports two kinds of vpn, whereas Android
supports much more.
The zerotier android app on Chromebook did not crash and showed online, but
no connection to the network was possible. I assume that the vpn api /
something else is different on the android apps on Chromebook.
Unfortunately, no idea what exactly. But I think, fixing the Android app
for Chromebook should be the fastest way to go. (or a custom vpn config?)

**Comment by interoperate** [comment]
The high-level steps to setup OpenVPN on a Chromebook that I have used are:

ChromeOS requires client certificate in pkcs12 format
Add public key of certificate server as an authority, e.g. **ca.crt**

> chrome://settings/certificates

Click on:

> Authorities > Import > ca.crt

Ensure that **Trust this certificate for identifying websites** is selected

Go to:

> chrome://settings/certificates

Click on: **Your certificates**

> Import and Bind to Device

Choose the relevant pkcs12 file

Configuring an ONC file that requires two different UUIDs as well as the relevant configuration settings. Once configured, go to:

> chrome://net-internals/#chromeos

Import the ONC file

**Comment by ChrisMagnuson** [comment]
@laduke Cisco has the [Cisco Anyconnect](https://chrome.google.com/webstore/detail/cisco-anyconnect/jacdijibdjifphcecdielmekkmfdpgee?hl=en-US) app in the chrome websore which is a very nice full featured VPN client that supports ipsec on ChromeOS.

**Comment by joseph-henry** [comment]
Reopened due to sufficient interest. This isn't on our backlog yet, but there's no harm in discussing further.

**Comment by glimberg** [comment]
Looks like ChromeOS does have a VPN API and it's not compatible with Android's VPN API.  We'll have to take a look at it.

https://developer.chrome.com/apps/vpnProvider

**Comment by adamierymenko** [comment]
We ordered a Chromebook, so this will be happening eventually.

**Comment by pandada8** [comment]
actually there is a flag called chrome://flags/#arc-vpn which can make the vpn app in android part take over the outside chrome, haven't tested the official zerotier android app though.

**Comment by arnevanbalgoijen** [comment]
Great idea!

**Comment by Lucaacer** [comment]
Just to report that zerotier for android works fine for my Lenovo yoga thinkpad 11e 4th gen.

I can connect to my remote webserver through chrome. I can browse the folders of any device which is connected to the network with total commander plus samba plugin. I can even add samba connections to chrome os default file manager though browsing folders this way looks slower (but it might depend on the connection).

A very little masterpiece:)

**Comment by adamierymenko** [comment]
I think we're closing this one as wontfix. Chromebooks that can install Android apps will work, but we looked into it and building a native Chromebook package for this looks unbelievably painful... too painful for the relatively small user base and without someone supporting it financially. It may not even be possible.

**Comment by chauffer** [comment]
ZeroTier on ChromeOS is unusable as ChromeOS kills background apps. Is there a way around this?

**Comment by Lucaacer** [comment]
In my experience it works very well, unless you change your network connection.

It works even in crostini but not by sharing the same android vpn, you have to set up a separate vpn connection by installing the software for linux (crostini 75.0.3761.0, dev channel).

**Comment by denzuko** [comment]
> I think we're closing this one as wontfix. ... without someone supporting it financially. It may not even be possible.
Da Planet Security and Majordomo.fund has some strong efforts behind tooling which leverages ZeroTeir. We're also going full chromebook/android internally. 

So, lets grab a meeting and see if there's an alignment in goals. https://calendly.com/denzuko/virtual-coffee

**Comment by anthonyheckmann** [comment]
> Just to report that zerotier for android works fine for my Lenovo yoga thinkpad 11e 4th gen.
> 
> I can connect to my remote webserver through chrome. I can browse the folders of any device which is connected to the network with total commander plus samba plugin. I can even add samba connections to chrome os default file manager though browsing folders this way looks slower (but it might depend on the connection).
> 
> A very little masterpiece:)
@Lucaacer 
I have a yogabook C630 and zerotier connects but DNS is messed up and I'm still learning crosh commands to debug the problem (can ping 8.8.8.8 and zerotier ips, but names won't resolve). Any suggestions?

**Comment by ckwe** [comment]
When the thread was first opened, I agree many Chromebooks did not have Android apps but now it's the inverse. Now depending on what folks want to connect, there are uses for both an Android as well as Crostini-based Zerotier, either shared between two accounts or on a same-account connection.

I stumbled upon this for a Crostini-based Zerotier connection specifically, but I'd be perfectly okay if the Android connection also works for Linux apps. Now, could different Zerotier networks be set-up on Android and Crostini? I also wanted to see if doing this could potentially cause network problems with both being on the same device.

I am playing with some really fun, LAN-based Windows apps, including a chat app and games running on Wine and the ultimate connectivity factor would be networking my Chromebook and a device at home remotely! In fact, my home device is older so I will likely use the steps for a router setup found at the link below and I really hope it works!

https://forum.openwrt.org/t/access-lan-devices-from-zerotier-router-across-different-networks/157487/2

Also, for configuring Crostini, using the method described by Nate8199 is the proper way of configuring Zerotier, or are there updated directions on doing this? Some of the steps weren't completely clear, so that's why I'm asking about it.
