### ISSUE TITLE
NAT through ZeroTier [Question]

### ISSUE THREAD

**Issue by blurredpixel** [zerotier/ZeroTierOne#604]
Network Setup:

Public IP> Gateway> lan 192.168.2.0/24
                 |   2.208  | >zt0 192.168.11.0/24    ------------------ 192.16811.0/24 zt0 gw2 > LAN 192.168.5.0/24 
                 |route 192.168.5.0/24 via 192.168.2.208                   192.168.5.0/24 via 192.168.11.200

Would it be possible to send traffic coming in on a public IP and NAT it to an address that is reachable via ZeroTier? Obviously you would need SRC/DST NAT rules on each gateway, but has anyone else done this?

**Comment by glimberg** [comment]
This is very much doable.  Or you could set a ZeroTier device as a bridge and just make it one big LAN.  Then you won't need SRC/DST NAT rules at all.

This link is OpenWRT/LEDE specific, but it gives you an idea:  https://support.zerotier.com/knowledgebase.php?entry=show&search-for=&article=MzM0YjEyOGIwOGFlYzQwZDgxOTFmNzI2ZDM5M2JmZTE_

**Comment by blurredpixel** [comment]
@glimberg 
I have my 'gateways" on ZT set in bridge mode. 
On the side with the public IP it goes Modem > Router > ubuntu running zt in bridge mode with appropriate static routes
