### ISSUE TITLE
Android app doesn't start after reboot

### ISSUE THREAD

**Issue by Yury-MonZon** [zerotier/ZeroTierOne#606]
Hi! I'm having a problem with the android app on android 4.1.2 - it doesn't start automatically on boot, I've even installed vpn trust dialog patch, so it would be permanently allowed to create vpn network. If I run it manually - it works great. But no autorun, even though I have checked those ticks.

**Comment by glimberg** [comment]
That feature is being phased out in the next version

**Comment by ndarilek** [comment]
Out of curiosity, why? I thought I'd use this to connect my phone to services running behind a home firewall, and it works nicely *when I remember to start it*, but essentially if I forget to do that then things break. Was hoping to use my phone for location-tracking to update my thermostat, but if I reboot my phone and forget to start the client, or if it reboots on its own, my automation breaks. I'm now looking for another solution, and may just set up a VPN. :( I remember there being an option to do this at one point, and then this setup was completely fire-and-forget, but when I rebuilt it recently the option went away.

**Comment by NuruNabiyev** [comment]
Is this feature available now? Indeed, even on android 8.0 if Always-On is enabled, ZeroTier won't autostart after reboot. This breaks all the automation

**Comment by gustavokei** [comment]
Also interested in this

**Comment by mccoychang** [comment]
Hi ,  
Is this feature available now?  Thanks.
