### ISSUE TITLE
Ubuntu 17.10 (Artful Aardvark) packages needed

### ISSUE THREAD

**Issue by shvchk** [zerotier/ZeroTierOne#607]

**Comment by cormacrelf** [comment]
I've been running xenial, the downloads page has a `curl|bash`-style one-liner with gpg that works pretty well.

```sh
if command -v zerotier-cli >/dev/null 2>/dev/null; then
  echo "zerotier-cli already installed, skipping"
else
  # install zerotier-cli
  curl -s 'https://pgp.mit.edu/pks/lookup?op=get&search=0x1657198823E52A61' | gpg --import && \
    if z=$(curl -s 'https://install.zerotier.com/' | gpg); then echo "$z" | sudo bash; fi
fi

# start it up (may be noop, but who cares)
sudo service zerotier-one start

# join a network
sudo zerotier-cli join "${zt_network_id}"
```

**Comment by shvchk** [comment]
Yeah, it will use `stretch` repo, which will probably work fine, I just noticed that there were repos for other Ubuntu releases, but not for Artful.

**Comment by adamierymenko** [comment]
Next version will have more repos. We'll have to add an Aardvark image to our build farm.

**Comment by adamierymenko** [comment]
Closing since this is in our build farm now

**Comment by Fastidious** [comment]
@adamierymenko the install still fails. Are you sure `artful` is on the build farm?

**Comment by shvchk** [comment]
Installer script adds "deb http://download.zerotier.com/debian/artful 
artful main" repo, but it gives 404 error, as there is no artful folder 
on http://download.zerotier.com/debian

**Comment by dudeisbrendan03** [comment]
`E: The repository 'http://download.zerotier.com/debian/artful artful Release' does not have a Release file.
`

No artful directory, going to have to build it myself (some users aren't going to be able to).

**Comment by gsomoza** [comment]
Bump

**Comment by Plantain** [comment]
Still an issue...

**Comment by dvteixeira24** [comment]
bump

experiencing the same issue
