### ISSUE TITLE
POST on existing network including "rulesSource" key => 500 "Internal error loading network."

### ISSUE THREAD

**Issue by cormacrelf** [zerotier/ZeroTierOne#608]
## Smallest repro:

`req.json`

```json
{
  "rulesSource": "accept;"
}
```

```sh
< req.json curl -H "Authorization: Bearer $ZEROTIER_API_KEY" -d @- https://my.zerotier.com/api/network/ -o net.json

# get the id from the output using https://stedolan.github.io/jq/
ID=$(jq -r .id < net.json)

# verify there's exactly one rule compiled
jq .config.rules < net.json

# update the network
< req.json curl -H "Authorization: Bearer $ZEROTIER_API_KEY" https://my.zerotier.com/api/network/$ID
# fails
# {"type":"internal","message":"Internal error loading network."}
```

The smallest repro doesn't require changing the "rulesSource" key between create and update, but doing so is no different.

Edit: added `-r` for raw jq output on id

Edit 2: I made a [gist](https://gist.github.com/cormacrelf/b4a3d2a3626e05813637f15290d9dc95) for a test case that changes the rulesSource and checks if the rules have changed. It also cleans up after itself so you can run it 1000x.

## Expected behaviour:

The network should compile the new ruleset and respond without error including the new rules and metadata.

**Comment by laduke** [comment]
Thanks. I'll be taking a look.

**Comment by laduke** [comment]
@cormacrelf thanks for the script. Fix should be in the next release of Central.

**Comment by cormacrelf** [comment]
Lovely! How frequent are those?

**Comment by laduke** [comment]
@cormacrelf this one took longer than usual, but the update went out.

**Comment by cormacrelf** [comment]
Awesome! Test passes. I'll exercise a bit more with my Terraform plugin.
