### ISSUE TITLE
ZT and local network routes / Best practice for laptops?

### ISSUE THREAD

**Issue by StrikerTwo** [zerotier/ZeroTierOne#613]
I have a few "road warrior" laptops running OpenVPN that I would like to migrate to ZeroTier. First tests are all looking good. One question however:
What happens if a laptop with ZeroTier running and providing a route to the corporate network (say, 10.5.0.0/16) is connected to that same network via a LAN cable? Will packets still go the ZeroTier path (with added encryption overhead and maybe making the central ZeroTier router at that location a bottleneck)?
Or will the route metrics take care of that automatically, so the direct LAN path is used?

Are there any other ideas or issues to consider in this scenario?

**Comment by adamierymenko** [comment]
That's a tough question. :) You have a few options and the results may vary a bit by operating system.

From your OS's point of view it looks like you have multiple network cards plugged into the same LAN. Now what?

ZeroTier sets a higher metric for its own interfaces. On most OSes this will cause traffic to prefer the physical LAN unless other things intervene.

If you want traffic to prefer ZT you can do this by designating your physical network as a "public" or "untrusted" network and the virtual network as "trusted" or "private."

**Comment by StrikerTwo** [comment]
> That's a tough question. :)
Those are the best :)

But it sounds like ZT is doing everything right already. I just wasn't sure if the higher metrics were by coincidence or intentional. 
Thank you!

**Comment by StrikerTwo** [comment]
Feedback from the first user I migrated from SoftEther to ZeroTier:
"Wow, I really like the new system you installed. My laptop finally feels snappy again and reacts instantly when I click on something."
Not sure what the problem was exactly, but she is happy :)
