### ISSUE TITLE
[UPNP] make-linux.mk wrong pattern

### ISSUE THREAD

**Issue by leleobhz** [zerotier/ZeroTierOne#617]
Hello!

When I packed Zerotier for both Alpine and ArchLinux, i found a regex mismatch I've patched and its in the link https://github.com/leleobhz/aports/blob/master/testing/zerotier-one/miniupnpc-system.patch

In https://aur.archlinux.org/packages/zerotier-one/ I've posted it also works with system library for natpmp and miniupnp if I apply this patch.

Can you please validate it and apply the patch?

Thanks!

**Comment by adamierymenko** [comment]
Fixed in `dev`
