### ISSUE TITLE
my.zerotier.com not working

### ISSUE THREAD

**Issue by z0id** [zerotier/ZeroTierOne#618]
New user. Can't create account:
1. Google account login is not working, throws an "Uncaught/unexpected internal error."
2. Signup is not working, says already registered no matter the input. 
3. Reset password link does not link to anything. 
4. On refresh it gets stuck on spinning wheel.

**Comment by tiernano** [comment]
noticed this just now too... to make things even worse, it seems that my ZT clients are not connecting either... they are stuck on "REQUESTING_CONFIGURATION"...

**Comment by glimberg** [comment]
Our hosting provider is experiencing some issues tonight.  We're working on it.

**Comment by tiernano** [comment]
@glimberg is this related to the OVH servers being down?

**Comment by glimberg** [comment]
Yes.  Central is hosted at OVH

**Comment by glimberg** [comment]
Yeah. OVH is having some major issues tonight.  Routers down due to power outage

https://twitter.com/olesovhcom/status/928535264057839616

We'll get things back as soon as we can

**Comment by tiernano** [comment]
yea, thats not looking good on their end... good luck!

**Comment by adamierymenko** [comment]
Fixed. It was mostly an OVH issue but we'll be working to make sure it doesn't happen again. Apparently 3 different data centers several hundred km apart is not good enough.
