### ISSUE TITLE
Outbound IP flapping

### ISSUE THREAD

**Issue by StrikerTwo** [zerotier/ZeroTierOne#619]
I have a ZT device with two WAN addresses.
Is there any way to make ZeroTier One use one address and stick to it? I don't care much which one it chooses as long as it doesn't change again, but right now it constantly switches between the two addresses if I watch in Central or run `listpeers` in a loop. This can't be good for connection stability.

I already created https://github.com/opnsense/plugins/issues/363 (because the device in question is an OPNsense box), but I suspect the problem lies on the ZT side.

**Comment by adamierymenko** [comment]
There are some fixes for this kind of thing in 1.2.6 (soon), and we're going to be doing a lot more in this area in the run-up to the ZeroTier Edge release. That's going to have more advanced SD-WAN features and will demand much better path management.

**Comment by adamierymenko** [comment]
Flagging as a reminder to others -- but AFIAK probably fixed in `dev`

**Comment by StrikerTwo** [comment]
Understood. I'll move the ZT client to another box with only one IP until then.

Thanks for answering and nice to see you found some time for Github after the OVH drama today ;)

**Comment by adamierymenko** [comment]
an ugly hack would be to use iptables to block it from talking on one interface

**Comment by StrikerTwo** [comment]
Thanks, I'll try that first.

**Comment by StrikerTwo** [comment]
Well, now my firewall log is full and my ZT connection is even more unstable ;)

**Comment by laduke** [comment]
Would `interfacePrefixBlacklist` help? 
https://github.com/zerotier/ZeroTierOne/tree/master/service

**Comment by adamierymenko** [comment]
Closing since I believe this is fixed in `dev` with new path selection logic. We will test more prior to 1.2.6.
