### ISSUE TITLE
mDNS emulation

### ISSUE THREAD

**Issue by orent** [zerotier/ZeroTierOne#621]
ARP emulation... NDP emulation... how about mDNS emulation?

Listen on the multicast dns address for queries of the form zt0123456789.local or zt0123456789abcdef.local and return the IP of the target.

**Comment by adamierymenko** [comment]
This is a really fascinating idea, but I'm not sure if it would work. Systems route .local to mDNSResponder and similar services, and Windows does not (AFIAK) ship with mDNS support.

Still... it's food for thought. Leaving it up.

**Comment by mrexodia** [comment]
Just a quick update, Windows 10 appears to support mDNS now https://stackoverflow.com/a/41019456/1806760
