### ISSUE TITLE
FITM (Friend in the Middle) pattern for local root servers

### ISSUE THREAD

**Issue by adamierymenko** [zerotier/ZeroTierOne#622]
One of the advertised features of the [Edge](https://www.indiegogo.com/projects/zerotier-edge-open-source-enterprise-vpn-sd-wan/x/17167082) is "local root server" capability. We don't want you to have to do the "set up a moon" dance for this. We want it to just work.

I've got an idea for how to do this that I wanted to write down so I don't forget.

Typically a man-in-the-middle or a sniffer is an adversary, but it doesn't have to be. ZeroTier is end-to-end encrypted and authenticated so a MITM just sees noise and can't modify packets, but the source and destination ZeroTier addresses are visible.

When you don't have a direct path you send your packets upstream, but the destination ZT address is the end destination not the upstream hop. That means that anyone watching knows the ZT address of the destination and the source as well as the physical IPs of both. (ZT is a secure link protocol but is not an anonymity protocol like Tor.)

This means nothing stops an observer from chipping in and saying "hey Alice! I know Bob! He's over there!"

The question is how to make this secure. Anything that lets another device hint about where to connect is a magnet for potential abuse in the area of hostile forensics, DDOS amplification attacks, and other shenanigans.

The intended use case is for local routers and/or things on your local LAN to be able to do this. As such they're going to be able to observe your traffic and they're going to be close.

Maybe there could be a way for them to send such a hint along with some observed data and maybe the receiver could only accept the hint if the observed data matches a packet sent less than, say, 5ms ago. This would make it impossible for a naive third party to send these as they would not have any legit sniffed packet data, and it would also be impossible for someone far away to send hints because Albert Einstein.

**Comment by adamierymenko** [comment]
Let me add that other than a special heuristic for these hints this would require basically no special protocol support.

**Comment by StrikerTwo** [comment]
Could you please elaborate what the exact use case would be? I thought the point of an Edge was to act as a central ZT gateway so individual devices don't need to run ZT themselves.

The only thing I can see is a LAN without internet access but so large that multicast discovery does not work anymore. But why would I use ZeroTier there? 

I think that's a lot of effort for an edge case :drum:

**Comment by adamierymenko** [comment]
The use case would be making ZeroTier operation at a single site reliable if the Internet goes down. Otherwise if you can't find the roots you can't build new links.

**Comment by adamierymenko** [comment]
Devices behind the Edge don't *have* to run ZT themselves but they could, and there are other cases where zero-conf deployment of on-site roots would be desirable.

**Comment by StrikerTwo** [comment]
> The use case would be making ZeroTier operation at a single site reliable if the Internet goes down. 

Why would I need ZeroTier connections inside my LAN?
Maybe I'm totally missing the obvious...

**Comment by StrikerTwo** [comment]
And wouldn't the Edge then need to be the default gateway for all devices and all traffic, in order to see the ZT traffic and act as a Root-in-the-Middle? Can the Edge hardware push that kind of speed and basically analyse ("observe") every packet if it is ZT traffic or not?

**Comment by adamierymenko** [comment]
ZeroTier is a general purpose network virtualization / SDN platform. It works just as well inside a LAN as outside, and indeed secure virtualization *inside* a LAN is one use case. We have users who use their ZeroTier network as their "real" network and use physical LAN as a dumb pipe.

... and yes the Edge is relatively fast. It's a dual core 1.2ghz ARM64 with crypto acceleration and NEON. (Marvell Armada) It can do 1gbps full-duplex ZeroTier and can do some basic DPI as well.

**Comment by sbilly** [comment]
does it integrated into main repo ?
