### ISSUE TITLE
Issues with Scaleway?  Physical IP address showing as "unknown"

### ISSUE THREAD

**Issue by bodleytunes** [zerotier/ZeroTierOne#623]
Hi All,

Just started using Zerotier after hearing about it on Packet Pushers podcast, brilliant stuff!

Anyway decided to move my various cloud machines over from FRR DMVPN to this, but I'm having an issue with a single Ubuntu 17.04 server running on scaleway (arm64)

I can connect to this device but it seems to be going through a relay and not direct.  I have opened up the port 9993 udp on the Scaleway firewall also.

I've noticed this single node isn't giving my.zerotier UI its physical IP address, it shows "unknown" and I'm guessing this could be the issue.

The scaleway VM has a public IP address that (afaik) is one to one natted to an internal address similar to how an elastic IP nat's into an Amazon EC2 instance.

At first I tried running ZT on an LXD container within the scaleway VM with an IP on an internal OVS bridge that was then NAT overloaded as it egressed the VM nic, so at first I thought this might be an issue, but even after installing ZT directly on the VM itself its still not reporting back its IP.

I also thought about the arm64 being an issue but I'm running it on my raspberry pi at home with no issues.

Just wondering what could be causing this or if I'm doing something daft and missed something obvious?

![image](https://user-images.githubusercontent.com/619239/32699064-8cf50fca-c7a7-11e7-829b-22623fee42f2.png)

Cheers!

Jon.

**Comment by bodleytunes** [comment]
Just to also show the list-peers output on the scaleway server if its of any help:

![image](https://user-images.githubusercontent.com/619239/32699095-f7840c92-c7a7-11e7-824e-d4f751dbcc85.png)

**Comment by bodleytunes** [comment]
Kind of got this working by forcing it to go direct 

`root@-1:/var/lib/zerotier-one# cat local.conf    
{
        "virtual": {
                "XXYYYYYYY": {
                        "try": ["138.201.XX.XX/9993"]
                },
                "XXYYYYYYY": {
                        "try": ["138.201.XX.XX/9993"]
                },
                "XXYYYYYYY": {
                        "try": ["138.201.XX.XX/9993"]
                },
                "XXYYYYYYY": {
                        "try": ["81.107.XXX.XX/9993"]
                },
                "XXYYYYYYY": {
                        "try": ["104.199.XX.XXX/9993"]
                },
                "XXYYYYYYY": {
                        "try": ["78.148.XXX.XXX/9993"]
                }
        }
}`

**Comment by bodleytunes** [comment]
![image](https://user-images.githubusercontent.com/619239/32917243-789c4990-cb16-11e7-8b5c-8c0daeeb0797.png)

**Comment by adamierymenko** [comment]
This really looks like a local firewall issue on the local machine preventing automatic negotiation of direct links. I'm not sure if we've tested with LXD and I'm not sure how iptables is configured with LXD by default. If it's in symmetric NAT mode by default this may be the problem.

**Comment by bodleytunes** [comment]
Works fine with LXD in other scenarios, I think the issue is with Scaleway
and the way they do the NAT on your servers.

There are no such issues with Google cloudor other providers that NAT to
your server though.

Also no issues when I do NAT through my own firewalls to ZT boxes.

Cheers,
Jon.

**Comment by lunarthegrey** [comment]
I had issues with zerotier-one and Scaleway too. Except I thought it was due to Scaleway's kernels not having the TUN/TAP module. https://github.com/scaleway/kernel-tools/issues/367

**Comment by bstin** [comment]
Just to note, I have problems where I can't get scaleway to show physical IP as well.

I think I'm going to jump ship from scaleway since I already have an infrastructure in AWS where things seem to work better. However, would be nice to know how to sort it out incase I need to revert back to them.

If I understand, I would need to edit local.conf on every machine to point to the proper IP of scaleway host? Or is it enough to just make this entry on the scaleway host local.conf file itself?

**Comment by bodleytunes** [comment]
I think it might be enough to just edit the local.conf on the scaleway
node.

Cheers,
Jon.

**Comment by Adonai** [comment]
@bodleytunes if I fix it in `local.conf` on scaleway, how will this information be useful to other peers? It's only applied to local node.

So if I want other peers to "see" the Scaleway host directly, I have to add `"virtual": {...}` section to each and every of them.
