### ISSUE TITLE
Zerotier relaying between macs and mobile devices on the same LAN

### ISSUE THREAD

**Issue by chetstone** [zerotier/ZeroTierOne#624]
Zerotier can directly connect between my two macs, but it relays to the ZT server when connecting to my iphone and android devices on the same LAN. 

The mac firewalls are off, I've checked that I'm using the latest available versions of ZT on all devices.
The LAN router is running asuswrt-merlin firmware. I've tried turning off the router firewall, and installing a port trigger on 9993. Neither step helped.

iperf between the mac and android shows a data rate of 1-2 Mbps. Between the two macs it's ~ 250 Mbps. Ping times also indicate relaying.

```
$ zerotier-cli listpeers
200 listpeers <ztaddr> <path> <latency> <version> <role>
200 listpeers 09b95608dc 192.168.1.137/9993;8051;7083;1.00 115 1.2.4 LEAF
200 listpeers 14007ff17d 192.168.1.241/9993;8051;4950;1.00 30 1.2.4 LEAF
200 listpeers 565799d8f6 37.59.34.61/54871;1053;1053;1.00 209 1.2.5 LEAF
200 listpeers 8841408a2e 45.32.198.130/9993;11136;11136;1.00 174 1.1.5 PLANET
200 listpeers 9d219039f3 107.170.197.14/9993;11203;11126;1.00 217 1.1.5 PLANET
200 listpeers ce2c5a2168 192.168.1.127/9993;5258;5258;1.00 2 1.2.4 LEAF
200 listpeers eba37cb906 66.243.197.144/9993;733;733;1.00 76 1.2.4 LEAF
```

192.168.1.137 (10.147.17.195) is the android, 192.168.1.241 (10.147.17.221) is the iphone, and 192.168.1.127 (10.147.17.178)is the other mac.

```
iperf -s
------------------------------------------------------------
Server listening on TCP port 5001
TCP window size:  128 KByte (default)
------------------------------------------------------------
[  4] local 10.147.17.144 port 5001 connected with 10.147.17.195 port 44234
[ ID] Interval       Transfer     Bandwidth
[  4]  0.0-12.6 sec  2.62 MBytes  1.75 Mbits/sec
$ ping 10.147.17.195
PING 10.147.17.195 (10.147.17.195): 56 data bytes
64 bytes from 10.147.17.195: icmp_seq=0 ttl=64 time=251.554 ms
64 bytes from 10.147.17.195: icmp_seq=1 ttl=64 time=256.217 ms
64 bytes from 10.147.17.195: icmp_seq=2 ttl=64 time=159.670 ms
64 bytes from 10.147.17.195: icmp_seq=3 ttl=64 time=606.649 ms
64 bytes from 10.147.17.195: icmp_seq=4 ttl=64 time=103.373 ms
64 bytes from 10.147.17.195: icmp_seq=5 ttl=64 time=143.810 ms
```

```
PING 10.147.17.221 (10.147.17.221): 56 data bytes
Request timeout for icmp_seq 0
64 bytes from 10.147.17.221: icmp_seq=1 ttl=64 time=80.712 ms
64 bytes from 10.147.17.221: icmp_seq=2 ttl=64 time=105.998 ms
64 bytes from 10.147.17.221: icmp_seq=3 ttl=64 time=22.919 ms
64 bytes from 10.147.17.221: icmp_seq=4 ttl=64 time=43.319 ms
64 bytes from 10.147.17.221: icmp_seq=5 ttl=64 time=66.198 ms
64 bytes from 10.147.17.221: icmp_seq=6 ttl=64 time=86.761 ms
64 bytes from 10.147.17.221: icmp_seq=7 ttl=64 time=110.543 ms
64 bytes from 10.147.17.221: icmp_seq=8 ttl=64 time=29.073 ms
64 bytes from 10.147.17.221: icmp_seq=9 ttl=64 time=48.503 ms
64 bytes from 10.147.17.221: icmp_seq=10 ttl=64 time=71.883 ms
```

```
PING 10.147.17.178 (10.147.17.178): 56 data bytes
64 bytes from 10.147.17.178: icmp_seq=0 ttl=64 time=7.302 ms
64 bytes from 10.147.17.178: icmp_seq=1 ttl=64 time=2.119 ms
64 bytes from 10.147.17.178: icmp_seq=2 ttl=64 time=2.985 ms
64 bytes from 10.147.17.178: icmp_seq=3 ttl=64 time=1.996 ms
64 bytes from 10.147.17.178: icmp_seq=4 ttl=64 time=2.100 ms
64 bytes from 10.147.17.178: icmp_seq=5 ttl=64 time=3.717 ms
64 bytes from 10.147.17.178: icmp_seq=6 ttl=64 time=2.771 ms
64 bytes from 10.147.17.178: icmp_seq=7 ttl=64 time=7.861 ms
64 bytes from 10.147.17.178: icmp_seq=8 ttl=64 time=3.113 ms
64 bytes from 10.147.17.178: icmp_seq=9 ttl=64 time=3.250 ms
64 bytes from 10.147.17.178: icmp_seq=10 ttl=64 time=1.782 ms


$ iperf -c 10.147.17.178
------------------------------------------------------------
Client connecting to 10.147.17.178, TCP port 5001
TCP window size:  129 KByte (default)
------------------------------------------------------------
[  4] local 10.147.17.144 port 51484 connected with 10.147.17.178 port 5001
[ ID] Interval       Transfer     Bandwidth
[  4]  0.0-10.0 sec   290 MBytes   243 Mbits/sec
```

**Comment by glimberg** [comment]
Your list peers output does not indicate relaying at all.  If it were relaying, there wouldn't be an IP address listed for a peer.

The fact is, unfortunately, that Android and iOS are just slower at this for a few reasons:

1.  Mac, Windows and Linux allow us to install TAP devices to emulate an ethernet card.  iOS and Android do not.  The best we can get there is a TUN device which means we have to add extra code to run when sending/receiving any packet to bridge between ethernet frames and IP packets.

2. Because of said TAP device on moble and our bridge between ethernet frames and IP packets, we also have to handle ARP and NDP in user space.  If we could use a TUN device, that would be handled by the kernel in a much more efficient manner.

3. WiFi chips in mobile devices are *very* aggressive with power saving and this causes additional latency.

**Comment by chetstone** [comment]
Thanks for the reply. However, I know this used to work much, much, better. Unfortunately it's been many months since I've cared about this so I wouldn't be able to identify what changed. Perhaps the major ZT update last February. I remember iperf measurements in the 100 Mbps range. It could have been a year or two ago. Different iOS versions certainly. (now on iOS 11), not sure about Android (6.0.1, I've been using that since not long after I got the device)

**Comment by glimberg** [comment]
I'm not sure how you've ever gotten 100 Mbps on the mobile apps.  That's far greater than I've ever seen in development of them.  My only thought is that you were seeing that when transferring a very compressable payload as ZeroTier uses LZ4 compression on the data.

**Comment by chetstone** [comment]
OK, well, perhaps my memory is faulty. I would have been using the default iperf or iperf3 payload, same as now. 

Since you're the mobile app developer, are you aware of an issue on iOS where the connection drops frequently? This also seems like a regression since the big upgrade last winter. Android doesn't have the problem.

Thanks.
