### ISSUE TITLE
Android client: network is extremely slow

### ISSUE THREAD

**Issue by miegl** [zerotier/ZeroTierOne#625]
Hello,
I'm experiencing a bunch of network performance problems with the Android ZT app. I've tried the stable 1.2.4 and the 1.2.5-5 beta however it's not better even with the beta version.

The Linux and Windows versions work quite well, but the Android app is unusable.
I've tried connecting to my ZT connected device on the same LAN from the Android app and the maximal throughput I was able to get is like 5 Mbit/s. Second test was even worse tho, I've only got 3 Mbit/s. But the latency was even worse, I got 100 ms ping (average!). Remember, this was all done in a LAN! (so normal ping would be bellow 1ms).
It worked perfectly with the desktop client tho.

**Comment by glimberg** [comment]
Copypasta from another response

> The fact is, unfortunately, that Android and iOS are just slower at this for a few reasons:
> 
> 1. Mac, Windows and Linux allow us to install TAP devices to emulate an ethernet card. iOS and Android do not. The best we can get there is a TUN device which means we have to add extra code to run when sending/receiving any packet to bridge between ethernet frames and IP packets.
> 
> 2. Because of said TUN device on moble and our bridge between ethernet frames and IP packets, we also have to handle ARP and NDP in user space. If we could use a TUN device, that would be handled by the kernel in a much more efficient manner.
> 
> 3. WiFi chips in mobile devices are very aggressive with power saving and this causes additional latency.

**Comment by Miegl** [comment]
So it just can't be better? I think my Android device (galaxy s7 - exynos 8890) should be able to perform at least better even in user space. And yes, I understand WiFi powersaving, but this just doesn't add 100ms to the latency.

Thanks.

**Comment by glimberg** [comment]
It's the same on iOS.

**Comment by Miegl** [comment]
Is there a possibility to make the performance better with root rights?

**Comment by Miegl** [comment]
Some VPN apps for Android have TAP support. Why it isn't possible in this case?

Thanks!

**Comment by glimberg** [comment]
Android APIs only allow TUN style tunnels, so I have no idea how other apps are getting TAP support as you claim.  If the API did support TAP devices, I'd be all over it because it would make my life *so* much easier!

I suppose it would be possible to use a TAP device on a rooted system.  However, it's not likely something that we're going to spend the resources required to look into given the limited audience for such an endeavor.

**Comment by bodleytunes** [comment]
My Android OpenVPN client uses TUN routed interfaces and mine 10+ MBits/sec no issues over OpenVPN. (Routed Mode AES256).  

Getting about 0.3Mbit using ZT tunneling all my traffic through the same cloud server via a default.

**Comment by glimberg** [comment]
The OpenVPN client on Android does not support TAP.

https://docs.openvpn.net/faqs/faq-regarding-openvpn-connect-android/
> Why doesn't the app support tap-style tunnels?
> A: The Android VPN API supports only tun-style tunnels at the moment. This is a limitation of the Android platform. If you try to connect a profile that uses a tap-based tunnel, you will get an error that only layer 3 tunnels are currently supported.
> If you really want to see tap-style tunnels supported in OpenVPN Connect, we would encourage you to contact the Google Android team and ask that the VpnService API be extended to allow this. Without such changes to the VpnService API, it is not possible for non-root apps such as OpenVPN Connect to support tap-style tunnels.

**Comment by Miegl** [comment]
One OpenVPN has tap support even without root. Don't know how that is done though.

**Comment by Miegl** [comment]
But honestly it should be better even with tun.

**Comment by glimberg** [comment]
Actually TUN is harder for us because ZeroTier's virtual network is a Level 2 based network.  It's a virtual ethernet device.  TUN operates at Level 3 so we had to write a bridge on Android and iOS to fill in that gap.

And here's my `iperf` output on the current Beta version for Android (running on a Galaxy S8+):

```
------------------------------------------------------------
Server listening on TCP port 5001
TCP window size: 64.0 KByte (default)
------------------------------------------------------------
[308] local 10.6.6.246 port 5001 connected with 10.6.6.164 port 52546
[ ID] Interval       Transfer     Bandwidth
[308]  0.0- 5.0 sec  17.5 MBytes  29.4 Mbits/sec
[308]  5.0-10.0 sec  13.4 MBytes  22.5 Mbits/sec
[308] 10.0-15.0 sec  5.13 MBytes  8.61 Mbits/sec
[308] 15.0-20.0 sec  15.3 MBytes  25.7 Mbits/sec
[308] 20.0-25.0 sec  18.5 MBytes  31.0 Mbits/sec
[308] 25.0-30.0 sec  19.6 MBytes  32.9 Mbits/sec
[308] 30.0-35.0 sec  21.0 MBytes  35.2 Mbits/sec
[308] 35.0-40.0 sec  19.8 MBytes  33.2 Mbits/sec
[308] 40.0-45.0 sec  17.7 MBytes  29.7 Mbits/sec
[308] 45.0-50.0 sec  21.4 MBytes  35.9 Mbits/sec
[308] 50.0-55.0 sec  20.5 MBytes  34.4 Mbits/sec
[308] 55.0-60.0 sec  21.3 MBytes  35.7 Mbits/sec
[308]  0.0-60.5 sec   213 MBytes  29.6 Mbits/sec
```

**Comment by Miegl** [comment]
Well my iperf looks like this...
```
Accepted connection from 10.0.15.63, port 56726                  
[  5] local 10.0.15.10 port 5201 connected to 10.0.15.63 port 567
27                                                               
[ ID] Interval           Transfer     Bitrate                    
[  5]   0.00-1.00   sec   503 KBytes  4.12 Mbits/sec             
                                                                 
[  5]   1.00-2.00   sec   259 KBytes  2.12 Mbits/sec             
                                                                 
[  5]   2.00-3.00   sec   358 KBytes  2.93 Mbits/sec             
                                                                 
[  5]   3.00-4.00   sec   358 KBytes  2.93 Mbits/sec             
                                                                 
[  5]   4.00-5.00   sec   515 KBytes  4.22 Mbits/sec             
                                                                 
[  5]   5.00-6.00   sec   602 KBytes  4.93 Mbits/sec             
                                                                 
[  5]   6.00-7.00   sec   704 KBytes  5.77 Mbits/sec             
                                                                 
[  5]   7.00-8.00   sec   550 KBytes  4.51 Mbits/sec
```

**Comment by Miegl** [comment]
I don't get why your S8+ has so much better throughput. Or maybe its something with system?

**Comment by Miegl** [comment]
OK, so I somewhat doubled ZT throughput.
I set the TCP Congestion Algorithm from Westwood to bic.

```
[  4] local 10.0.15.10 port 5001 connected with 10.0.15.63 port 4
1853                                                             
[  4]  0.0-62.9 sec  97.8 MBytes  13.0 Mbits/sec
```

**Comment by adamierymenko** [comment]
I wonder about your wireless access point. What kind of AP are you connected to with your Galaxy?

**Comment by adamierymenko** [comment]
Of course ours is nothing special, just an old Airport Express 802.11n.

**Comment by bodleytunes** [comment]
I'm also getting pretty shocking speeds on my Android OnePlus Two phone.

I'm routing through my Hetzner server with a 500Meg pipe and the local internet is 200Meg.  I'm struggling to get above 3mbits and browsing pages is pretty slow too.

With OpenVPN I get 30Meg+ 

I'm using routing and not bridging any of the ZT interfaces.

Cheers,
Jon.

**Comment by Miegl** [comment]
@adamierymenko Well my wireless AP is a standard consumer grade 802.11n router but it's able to reach like 100 mbps with my Exynos S7. So yeah, ap shouldn't be the issue.

It has probably something to do with kernel. Otherwise I'm not sure how @glimberg managed to reach 35 mbit with S8+

**Comment by tomschlenkhoff** [comment]
I'd like to chime in here, making the same observations. I measured extensively, all on the same WLAN with the same cable provider behind it. One device is my MacBook Pro with the latest 10.12.6, all patches with the stock ZT app (1.2.4, I think). The second device is a OnePlus 5 with the latest Android 8.0, unrooted, all plain vanilla.
I repeated a few measurements using the Online Speed Test of Deutsche Telekom. As backend I set-up a new Digital Ocean Droplet with either the latest ZeroTier download (1.2.4 as well) or the latest OpenVPN package from apt.

All adblockers where deactivated, no (meaningful broadcast), no other service was using the pipes. Default route was set to the backend. Traffic could be observed via tcpdump.

MacBook Pro
down (Mbit/s) Up (Mbit/s) Ping (ms)
234		16		15 (native IP)
203		13		18 (ZT)
48		12		22 (OpenVPN)

OnePlus 5
down (Mbit/s) Up (Mbit/s) Ping (ms)
45		11		32 (native IP)
10		6			74 (ZT)
18		9			45 (OpenVPN)

All measurements averaged out over 3 tests. So **on this laptop ZT hands-down beats OpenVPN** and is surprisingly **close to native performance** (As Adam compared as well a few months ago).
**On mobile** this is totally different (at least on Android). **OpenVPN beats ZT by 1,5-2**, especially the **latency goes way up**. What can this be?

It most probably is not broadcast (no other services, no other clients on this net), OpenVPN is required to work with TUN as well, no TAP available on stock Android.

**Comment by BBenni** [comment]
Same here:
I ran tests in Chrome on my mobile device (LG G4 Android 6.0) and a desktop Windows PC (i5-7200 / 8 GB RAM).

On the mobile device both down and up speed were extremely low when using ZeoTier while on the desktop machine there was basically no difference.

## LG G4
down (Mbit/s) | Up (Mbit/s) | Ping (ms) | Transport
-- | -- | -- | --
43|26|37 |native IP
38|25|39|OpenVPN
2|2|69|ZeroTier

## Windows PC
down (Mbit/s) | Up (Mbit/s) | Ping (ms) | Transport
-- | -- | -- | --
266|25|11 |native IP
n.a.|n.a.|n.a.|OpenVPN(*)
264|28|14|ZeroTier


(*) Not possible at the moment due to some Windows / OpenVPN issue I'm experiencing.

**Comment by adamierymenko** [comment]
Is this with the current Android beta or the current Android release? The beta program is public so you're welcome to try the beta. Beta will become release pretty soon.

**Comment by alpharde** [comment]
Afaik one of the Tinc apps does tap by sticking a binary somewhere, also yeah, it does require root.
In the same spirit I also compiled the full zerotier binary for my cellphone, but it eats the battery too fast to be of any real use...

**Comment by sbilly** [comment]
> Afaik one of the Tinc apps does tap by sticking a binary somewhere, also yeah, it does require root.
> In the same spirit I also compiled the full zerotier binary for my cellphone, but it eats the battery too fast to be of any real use...

You can do some compare without root.  @alpharde 

http://www.tinc-vpn.org/pipermail/tinc/2010-April/002304.html

> > is there a way to run tinc on a (linux) box, with a public ip,
> > but on which i don't have root privileges ?
> 
> Yes, you start tinc as a normal user or let tinc drop root privileges after
> starting with the --user option.

**Comment by Mercurial** [comment]
I am also noticing this

**Comment by alpharde** [comment]
So uhhh I dunno if I should make a separate issue for this but is there any hope of getting zerotier over tap on (rooted) android?

**Comment by glimberg** [comment]
> So uhhh I dunno if I should make a separate issue for this but is there any hope of getting zerotier over tap on (rooted) android?

Not likely unless someone wants to create & support it.  It's not a big enough market for us to consider going after.
