### ISSUE TITLE
Hanging on identity generation during install

### ISSUE THREAD

**Issue by norn93** [zerotier/ZeroTierOne#626]
EDIT: This looks like #566, I'm trying that now.

I know this appears to be a duplicate of #367 and #355, but I don't think it is.

I'm trying to install ZeroTier on a Raspberry Pi Zero W.

Using `curl -s https://install.zerotier.com/ | sudo bash`, it seems to be installing correctly until it hangs at the bit where it tries to do identity generation.

After exiting with CRTL+C, any kind of call to `zerotier-cli status` etc. result in a Segmentation Fault.

Checking the status of the service:

pi@birdrecorder-2:~ $ service zerotier-one status
? zerotier-one.service - ZeroTier One
   Loaded: loaded (/lib/systemd/system/zerotier-one.service; enabled; vendor preset: enabled)
   Active: failed (Result: signal) since Fri 2017-11-17 13:29:06 AWST; 8min ago
  Process: 466 ExecStart=/usr/sbin/zerotier-one (code=killed, signal=SEGV)
 Main PID: 466 (code=killed, signal=SEGV)

Nov 17 13:29:06 birdrecorder-2 systemd[1]: zerotier-one.service: Failed with result 'signal'.
Nov 17 13:29:06 birdrecorder-2 systemd[1]: zerotier-one.service: Service hold-off time over, scheduling restart.
Nov 17 13:29:06 birdrecorder-2 systemd[1]: Stopped ZeroTier One.
Nov 17 13:29:06 birdrecorder-2 systemd[1]: zerotier-one.service: Start request repeated too quickly.
Nov 17 13:29:06 birdrecorder-2 systemd[1]: Failed to start ZeroTier One.
Nov 17 13:29:06 birdrecorder-2 systemd[1]: zerotier-one.service: Unit entered failed state.
Nov 17 13:29:06 birdrecorder-2 systemd[1]: zerotier-one.service: Failed with result 'signal'.

Now I am unable to re-install with `curl -s https://install.zerotier.com/ | sudo bash` since ZeroTier thinks it's already installed.

**Comment by norn93** [comment]
I compiled and ran from source, as described, and it works fine, with some help from #510. I also needed to run `sudo systemctl unmask zerotier-one.service` to get my service running properly.

**Comment by czarau** [comment]
Same issue Rpi Model B Revision 2.0 512MB
I'm guessing its a "Raspbian GNU/Linux 9 (stretch)" issue?

**Comment by norn93** [comment]
I wasn't able to work it out. Instead, I found it easier and more reliable to compile and install from source. But, have another look at #510, it looks like some people might have recently fixed this problem.

**Comment by czarau** [comment]
Thanks for your help. Compile and zerotier-one binary seems to be easiest method for me too. working now.
