### ISSUE TITLE
MFA on ZeroTier Central?

### ISSUE THREAD

**Issue by dragon2611** [zerotier/ZeroTierOne#627]
Given that if anyone gets access to a ZeroTier Central account they essentially get control of all of the users networks would it be possible to get some kind of MFA (Multi factor auth) on the login process.

Maybe something like the TOTP tokens or even a confirmation email.

**Comment by joseph-henry** [comment]
Yes. This is an upcoming feature.

**Comment by laduke** [comment]
Closing because #109  
Thanks!
