### ISSUE TITLE
port error without firewall in Ubuntu Linux

### ISSUE THREAD

**Issue by talentyang** [zerotier/ZeroTierOne#628]
Ubuntu 14.04 64bit without installating firewall

$ sudo /etc/init.d/zerotier-one start
Starting ZeroTier One zerotier-one
   ...done.
/usr/sbin/zerotier-one: WARNING: failed to drop privileges (kernel may not support required prctl features), running as root
ERROR: unable to configure virtual network port: could not open TUN/TAP device: No such file or directory

$ zerotier-cli listnetworks
200 listnetworks 8056c2e21c000001 earth.zerotier.net 02:9c:10:39:d2:f0 PORT_ERROR PUBLIC  fd80:56c2:e21c:0000:0199:939c:1025:3032/88,28.37.48.75/7

I tried to modify port of Zerotier One, still not work.

**Comment by adamierymenko** [comment]
PORT_ERROR nearly always means `/dev/net/tun` doesn't exist (on Linux). This is the kernel tun/tap driver. Maybe you don't have the module installed? Or is this a container? In containers usually this has to be enabled by the container engine.
