### ISSUE TITLE
textrel check failed for alpine linux

### ISSUE THREAD

**Issue by kyleparisi** [zerotier/ZeroTierOne#629]
I was working on updating the alpine linux package of zerotier.  Seemingly there is a problem

```
scw-d2ff74:~/aports/testing/zerotier-one/pkg$ scanelf --recursive --textrels .
 TYPE   TEXTRELS FILE
  zerotier-one: (memory/data?) [0x766EC] in (optimized out: previous IGDdata) [0x6EEA4]
ET_DYN  ./zerotier-one/usr/sbin/zerotier-one
```

I got this check via: https://github.com/alpinelinux/abuild/blob/master/abuild.in#L711

I have no idea what it means.  I've confirmed that this is not a problem in 1.1.14 version.

**Comment by adamierymenko** [comment]
I also have no idea what that means. 😦 

Bueller? Bueller?

**Comment by adamierymenko** [comment]
Do you have clang installed? Try building with clang? We usually built with clang internally since we tend to get slightly better performance, except for architectures where clang has issues.

**Comment by kyleparisi** [comment]
I think I did.  So I accidentally was doing the build on an arm cpu.  I switched to x86 and things are good.  Sorry about that.
