### ISSUE TITLE
Unable to connect from UDP to TCP

### ISSUE THREAD

**Issue by vvs-** [zerotier/ZeroTierOne#63]
I'm not able to connect from a UDP capable node to a TCP only node. It has TCP connections to supernodes, ARP cache shows that MAC is there, but any connection attemp times out. If I force a TCP mode by filtering UDP then everything is working as expected.

0.8.1 version from GitHub on Linux.

**Comment by heri16** [comment]
Is two-way confirmation implemented yet?
