### ISSUE TITLE
Getting Started -> Linux (DEB and RPM distributions) assumes Bash

### ISSUE THREAD

**Issue by jfdhuiz** [zerotier/ZeroTierOne#631]
On Getting Started -> Linux (DEB and RPM distributions) [1] you're giving these instructions:

> curl -s 'https://pgp.mit.edu/pks/lookup?op=get&search=0x1657198823E52A61' | gpg --import && \
> if z=$(curl -s 'https://install.zerotier.com/' | gpg); then echo "$z" | sudo bash; fi
> 

They work, but did not work with my default shell (Fish). You have a note up about gpg and gpg2 which is fair enough. You might wanna add you're assuming the user uses bash.

Btw, I wasn't sure where to file this ticket.

[1] https://zerotier.com/download.shtml

**Comment by laduke** [comment]
Thanks. We'll note it in our internal tracker for the website.
