### ISSUE TITLE
no option to get config or inspect network settings

### ISSUE THREAD

**Issue by JakeDEvans** [zerotier/ZeroTierOne#635]
I'm trying to troubleshoot some issues with assigning globally rotatable IPv6 addresses and the only option I have is to `set` a property, however there is not an `inspect` option to display the configuration of a network without setting a config.

Please add this.

**Comment by laduke** [comment]
`zerotier-cli listnetworks -j`  might help for now

**Comment by joseph-henry** [comment]
@JakeDEvans I've added a `get` command (https://github.com/zerotier/ZeroTierOne/commit/98b07f7f3c100bce017669f6a904ee5dace47412) in the `dev` branch to the cli that will now let you single out specific fields of the JSON output. Hopefully this will make it a bit easier to deal with.

Use it like so:

```
zerotier-cli get <nwid> allowDefault
0
zerotier-cli get <nwid> mtu
2800
...
```
