### ISSUE TITLE
Getting 405 on install.zerotier.com 

### ISSUE THREAD

**Issue by roman-cnd** [zerotier/ZeroTierOne#636]
Hi,

I'm getting 405 with httpie utility, in a bash install script
Any idea why nginx doesn't like it?

```
+ http https://install.zerotier.com/
<html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

PS Shouldn't all these distro/packages/keys be in CDN?

**Comment by glimberg** [comment]
What method/command line are you using to hit https://install.zerotier.com/ ?

**Comment by dch** [comment]
use curl or wget - don't overcomplicate it

```sh
curl -o installer.sh https://install.zerotier.com/
```

FWIW plain `http http://install.zerotier.com/ > installer.sh` works fine here too, try adding `-4vsSL` to curl for more debug output if that fails.

**Comment by dch** [comment]
maybe there's some local internet breakage between zt.com and you?

**Comment by roman-cnd** [comment]
Back to old good curl, httpie that I tried initially seems unreliable.
