### ISSUE TITLE
Windows : BSOD on wake from standby

### ISSUE THREAD

**Issue by n0xew** [zerotier/ZeroTierOne#637]
Hi ! 
I have installed ZeroTier One yesterdays on Windows (10, 64-bit) and since I'm having BSOD every time I wake the PC, no matter if it was in standby or was shutdown. 

I wanted to upload the content of the Minidump file but there was none, and the Windows\Memory.dmp is corrupted, I'll try to fix those issues later to provide you more information.

For now I can say that when waking up (from either standby or sleep), the (not connected) wifi icon first appears, connects for 0.5 sec to a wifi and BSOD. Also, rebooting into Safe Mode and disabling the laptop's Wifi adapter makes it work for the reboot, I can then enable it again and use Internet and ZeroTier correctly, but if I put the laptop to standby it will crash in the same manner on its next wake.
I have updated the Wifi adapter's drivers, same thing happens.

Uninstalling ZeroTier gets rid of all those BSOD, but damn I'm sad to say goodbye to this beautiful tool !

**Comment by n0xew** [comment]
Alternatively, any way to connect under Windows as a VPN ? If I understood well this how the Android app works ?

**Comment by joseph-henry** [comment]
We've never heard of anything like this happening due to ZT before. But if you can provide us more information about exactly what hardware you're running on and maybe getting us that dump file we can help you troubleshoot.

**Comment by adamierymenko** [comment]
Also let us know any other software you are running that installs anything similar to our driver such as other VPN, network virtualization, or host virtualization (e.g. VMWare) software.

**Comment by n0xew** [comment]
Okay so after some investigations it looks like the wireless driver was to be blamed, along with the bloatware suite that with included with it.
Wifi card is "Killer Wireless-n/a/ac 1535 Wireless Network Adapter", coming bundled with the "Killer Performance Suite" 🤦‍♂️ ... Anyway uninstalled it fully, and installed only the driver version 1.5.1608, which seems to fix it. 
Do you still want any other info on this ? It really seems to me that this wifi driver was the culprit, but also it did only crash when ZeroTier was installed :/

**Comment by adamierymenko** [comment]
Gotta love Windows bloatware.
