### ISSUE TITLE
Use uPnP to open ports and help facilitate direct connections, including TCP, also detect if we are not behind NAT.

### ISSUE THREAD

**Issue by vvs-** [zerotier/ZeroTierOne#64]
If one of the nodes is not firewalled then the other one should be able to open direct connection to it. Unfortunately it is not using this opportunity yet. It would be nice if this will become possible.

**Comment by heri16** [comment]
After many months, has there been something done for when one node is behind a symmetric NAT and the other has a Public Routable Internet Address?

**Comment by adamierymenko** [comment]
uPnP support is now in -dev
