### ISSUE TITLE
LEDE/Openwrt generates new ZT address with each reboot

### ISSUE THREAD

**Issue by improv-dev** [zerotier/ZeroTierOne#643]
Hi, I followed the KB [article](https://support.zerotier.com/knowledgebase.php?entry=show&search-for=&article=MzM0YjEyOGIwOGFlYzQwZDgxOTFmNzI2ZDM5M2JmZTE_) and each time I reboot I get a new network id, so each time I need to authorize it.  The filesystem on the router seems to be writable, because the /etc/config/zerotier was modified and saved.  Is there something else I can look at? Thanks.

My Setup:
LEDE/Openwrt: LEDE Reboot SNAPSHOT r5465-98fb380 / LuCI Master (git-17.341.69632-b7906fc)
firmware: brcm47xx-mips74k-linksys-e2000-v1-squashfs.bin
ZeroTier One version 1.2.4 build 0 (platform 1 arch 5)
Router is behind modem/router

/etc/config/zerotier
```
config zerotier 'default'
	option enabled '1'
	option interface 'wan'
	list join 'my network address'
	option secret 'long string'
```
interface zt0, allow unmanaged
interface lan general setup: 10.99.5.1 255.255.254.0 / physical: zt0 enabled/checked

**Comment by janjaapbos** [comment]
Copy from community response:
I think you are regenerating a zerotier id everytime. You should only generate a new identity if there is no existing /var/lib/zerotier-one/identity.secret and public

Each new identity will result into a new zerotier device id that needs to be authorized for the network.

**Comment by improv-dev** [comment]
Thanks janjaapbos

It seems /var is symlinked to /tmp with each reboot and so it will be emptied accordingly.
Also there is no /etc/init.d/rcS anymore, but procd see this [discussion](https://forum.turris.cz/t/etc-init-d-rcs-is-missing-what-gives/4745/9)

For now this is my dirty solution:
save the generated files to /etc
```
mkdir -p /etc/zerotier-one
cp -ar /var/lib/zerotier-one/. /etc/zerotier-one/

```
edit the /etc/init.d/zerotier
added the following lines at top: 
```
mkdir -p /var/lib/zerotier-one
cp -ar /etc/zerotier-one/. /var/lib/zerotier-one/

```
after reboot i checked, the files are copied.

**Comment by mwarning** [comment]
@improv-dev on OpenWrt/LEDE, /var/lib/zerotier-one/identity.secret is restored from /etc/config/zerotier on startup. This means the id should be preserved between reboots.

**Comment by improv-dev** [comment]
@mwarning sorry, as you already had pointed out, that it has something with `option secret` in `/etc/config/zerotier` i should not have modified this hex string, this has led to the consistent regeneration of new zt address with each reboot.

i found out when i reset the modem to default settings and reinstalled zerotier, but this time i didnt modify the hex string.
