### ISSUE TITLE
Stuck on REQUESTING_CONFIGURATION on dev branch

### ISSUE THREAD

**Issue by joseph-henry** [zerotier/ZeroTierOne#644]

**Comment by jungle-boogie** [comment]
I don't know what's happening, but the latest commit is working for me.

```
git bisect start
# good: [aeb1794be19904ca8a2ff2fb7d1307d4b8d24031] Comment out storage of secret ID in RethinkDb.
git bisect good aeb1794be19904ca8a2ff2fb7d1307d4b8d24031
# good: [38cc89b2ca4c3bf1a794da59e49251aedf72ee52] Add time to rethinkdb message output in controller.
git bisect good 38cc89b2ca4c3bf1a794da59e49251aedf72ee52
# good: [249c27afd5b4e7c68aada0dd1cbf963ba1352bf2] Fix old bug invoking idtool personality with -i
git bisect good 249c27afd5b4e7c68aada0dd1cbf963ba1352bf2
# good: [e4a10cc5105eb78eafe028052ba629e7e0ec2171] Member commit bug fix.
git bisect good e4a10cc5105eb78eafe028052ba629e7e0ec2171
```

**Comment by joseph-henry** [comment]
It seems like it's only have an issue with networks on certain controllers. Try attempting to join a network prefixed with `a09acf0233`.

**Comment by joseph-henry** [comment]
From what I can tell 459f1e7bfb50eb7b491940b7106d8788a7a5e11f is the breaking commit.

**Comment by jungle-boogie** [comment]
hi @joseph-henry,

I don't have a network with that prefix, and I'm able to join the earth network fine (8056c2e21c000001)

459f1e7bfb50eb7b491940b7106d8788a7a5e11f is a pretty old commit. Are you saying that commit plus network a09acf0233 causes the requesting config?

**Comment by joseph-henry** [comment]
Correct.

And I can join `8056c2e21c` networks as well.

**Comment by joseph-henry** [comment]
@jungle-boogie Are you still observing this issue? We haven't issued a fix yet but it seems like it works for me. Just wanted to check with you before I close this ticket.

**Comment by jungle-boogie** [comment]
@joseph-henry, I haven't seen this issue in sometime. if it does occur again, what are some troubleshooting steps to identify if this is an issue with the dev branch of `zerotier` vs. a network problem with zerotier?

I typically roll back a few commits, but that doesn't always show a problem.

**Comment by pellet** [comment]
I've had this issue occur to me when using 1.4.6 on macOS recently, I downgraded back to 1.4.0 and it works without this issue.
