### ISSUE TITLE
configuration balks on unknown architectures

### ISSUE THREAD

**Issue by jduerstock** [zerotier/ZeroTierOne#646]
Would it be possible to have the pack build a "generic" version with no asm optimizations when it doesn't detect any specifically known architectures or CPUs?  I tried building it on  an ia64 machine I have (with ZT_ARCHITECTURE=0) and it appeared to at least build and run, but I got several alignment errors along the way.  I don't want specific ia64 support, but I would at least like it to see it be more friendly/useful when compiled on unknown systems.

Thanks.

**Comment by adamierymenko** [comment]
If you want to do another architecture please do a pull request for it. I think we have defines in the architecture enum for every architecture and these numbers can be found in include/ZeroTierOne.h.
