### ISSUE TITLE
no support for building with uCLibC++

### ISSUE THREAD

**Issue by alon** [zerotier/ZeroTierOne#647]
Hi,

 I'm trying to fit zerotier together with a bunch of other packages on a 4 MB Flash with LEDE and libstdc++ is the biggest hog in the requirements by far. But the alternative STL implementation uCLibC++ (https://cxx.uclibc.org/) is missing a number of requirements used by ZeroTierOne, namely

array, initializer_list - ext/json/json.hpp
mutex, condition_variable - osdep/BlockingQueue.hpp

(and probably more, that's where I stopped and decided to write this issue).

 Is there any interest in supporting a different STL implementation? specifically uCLibC++?

 Thanks for the great work,

Alon

**Comment by alon** [comment]
Just wanted to update that most of the requirements are actually json.hpp requirements, and I've given up on this for now since that (nifty for sure) project is over my current time/knowhow budget. Would a patch replacing the json library be accepted? or reducing its features to the set actually used by ZeroTierOne? (which may reduce the STL requirements, which may make it easier to support UClibC++ and my original aim of having a small sized ZTO LEDE installation).

**Comment by joseph-henry** [comment]
Sorry for the late response here.

We have floated the idea of performing a C-- on the code and moving away from C++ in the core in the future, at the same time we would likely remove dependencies on stuff like `json.hpp` in the service code but honestly this would require a lot of time and effort and would require some deep architectural changes. I don't see us getting to it anytime soon.

That being said, if you do work on this project, keep us informed and if you have specific questions we will absolutely try to help when we can.

**Comment by adamierymenko** [comment]
Closing since this is currently not a priority. If you want to fix this feel free to submit a PR.

It sounds like there are C++11 issues here.

**Comment by alon** [comment]
That's fine by me. It seems to be mostly an issue with json.hpp support, or on the flip side uclibc++ implementation. Meanwhile I solved my own problem by increasing the flash (4 MiB is too small for many things, and newer routers have more, plus openwrt allows using a usb storage device as well)
