### ISSUE TITLE
breaks default route on Android 4.4.2

### ISSUE THREAD

**Issue by hc2hunter** [zerotier/ZeroTierOne#648]
Zerotier 1.2.4 client on Android 4.4.2 adds 2 routes while connect:
0.0.0.0/1 and 128.0.0.0/1
this prevents the default route from working :(

ps. checkbox "Route Via ZeroTier" is NOT checked

**Comment by janjaapbos** [comment]
If you want a default route through zerotier, you should enable "Route via ZeroTier".
The two routes you mention are required for using a default route over zerotier.

**Comment by janjaapbos** [comment]
Further, this route must be defined on the network, and it must point to a configured gateway.

**Comment by hc2hunter** [comment]
Thank you, but I do not need these 2 routes )))
...and they do not appear on other similar devices (for example, Cyanogen 4.4.4)

**Comment by glimberg** [comment]
Are those two routes configured on your ZeroTier network at https://my.zerotier.com?

**Comment by hc2hunter** [comment]
no
![zt](https://user-images.githubusercontent.com/34680888/34174590-86f6aea0-e50a-11e7-9270-f28f0ee2d528.png)

**Comment by glimberg** [comment]
No idea on this one.  If "Route via ZeroTier" is not set, then it's not ZeroTier adding the 0.0.0.0 route.

It's possible that the particular vendor distribution of Android you're using there assumes you want a default route set when using the VpnService API, but that's not standard behavior on Android, and unfortunately there's not much we can do about that.
