### ISSUE TITLE
ZeroTier Synology fails

### ISSUE THREAD

**Issue by plieningerweb** [zerotier/ZeroTierOne#652]
synology zerotier-one prints the error defined in 
https://github.com/zerotier/ZeroTierOne/blob/master/service/OneService.cpp#L1615

related issue: https://github.com/zerotier/ZeroTierNAS/issues/7

What is the reason for the failure? Why was the error message introduced?

**Comment by joseph-henry** [comment]
That error is designed to report that adding a route to the native OS's routing table has failed for one reason or another.

Which model are you using and which DSM version are you running?

Ticket #7 does have that error text in the log but it's due to an entirely different problem (which still exists).

**Comment by plieningerweb** [comment]
Info about model: 
Modell name: DS418j
Processor: Realtek RTD1293 SoC
DSM-Version: DSM 6.1.4-15217 Update 5

**Comment by joseph-henry** [comment]
Setting this error aside for a moment, does it join a network successfully?

Can you verify that the watchdog and the zerotier-one process are running?

`ps aux | grep zerotier`

**Comment by plieningerweb** [comment]
Screenshot: 
![image](https://user-images.githubusercontent.com/481107/34829847-4be05afc-f6e2-11e7-92a1-5473c9152f96.png)

After installing, it was connected for a short time. After rebooting, it could not connect anymore (says offline...)

```
setup@emu:~$ ps aux | grep zerotier
setup     6908  0.0  0.2  16612  1920 pts/2    S+   15:14   0:00 grep --color=auto zerotier
root      7765  0.2  0.1   3332  1664 ?        S     2017  66:20 /bin/bash /usr/local/zerotier/bin/ztui_watchdog.sh -daemon
setup@emu:~$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
   ... (removed)
       valid_lft forever preferred_lft forever
3: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1
    link/sit 0.0.0.0 brd 0.0.0.0
6: tun1000: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1400 qdisc pfifo_fast state UNKNOWN group default qlen 100
    link/none 
    inet 169.254.83.42 peer 169.254.83.41/32 scope global tun1000
       valid_lft forever preferred_lft forever
    inet6 2001:db8:b::10c9/64 scope global 
       valid_lft forever preferred_lft forever
setup@emu:~$ sudo /usr/local/zerotier/bin/zerotier-one -q listnetworks
0 listnetworks invalid JSON response (parse error - unexpected 'c')
setup@emu:~$ ls -alh /dev/net/tun
crw------- 1 root root 10, 200 Dec 23 11:11 /dev/net/tun
```

Unfortunately i do not now the location of the log file of the daemon script. It uses pwd...

**Comment by joseph-henry** [comment]
Try the latest [Realtek](https://download.zerotier.com/dist/zerotier-1.2.4-syn-rtd129x-6.1.spk?pk_campaign=github_zerotiernas) package. I've updated it today.

If that doesn't work, I'll have one more package for you to try. We don't have one of these devices in-house so we can't really test it here.

The GUI works for some models and not others, so try using zerotier's `zerotier-cli` interface instead.

**Comment by joseph-henry** [comment]
If you're still experiencing GUI problems can you provide me with the following information:

 - Browser (version if possible)
 - Specific errors from your Browser's console
 - Extensions installed (try disabling them to see if that helps)
 - Any information about how you're remotely connecting to your NAS
 - Whether you have a firewall enabled
 - Any non-default settings on the NAS

Thanks for your patience.

**Comment by adamierymenko** [comment]
Will reopen if feedback comes in. Otherwise cant reproduce or fixed. We use this on Synology.
