### ISSUE TITLE
Stuck on: REQUESTING_CONFIGURATION PRIVATE zt0 -

### ISSUE THREAD

**Issue by vikaskedia** [zerotier/ZeroTierOne#653]
I am on latest version as of date of this post:
Zerotier: 1.2.4
OS X: 10.13.2 High sierra

Stuck on:
REQUESTING_CONFIGURATION PRIVATE zt0 -

What should I do?

Some trouble shooting steps I tried:
1. Left the network from the command line and then  joined the network again: Did not help.

2. Rebooted the computer: This made it work.

**Comment by laduke** [comment]
Thanks, @vikaskedia. Probably related to new macOS kernel extension security. 

https://support.zerotier.com/knowledgebase.php?entry=show&search-for=&article=NDI4MWE1YTY1MDEzMGIyNDY0M2M5YzFhNGFiMjVjYjQ_

**Comment by jojo195** [comment]
Zerotier service in China is said to be banned. The VPN relay server is shut down. So just use alternatives of it.
