### ISSUE TITLE
ZeroTier routes disappear on MacOS

### ISSUE THREAD

**Issue by pjurg** [zerotier/ZeroTierOne#660]
This has been verified by 2 users that use a similar configuration: A /24 (or probably any) network with a ZT bridge, where part of the address space is used for the physical network and part for ZT clients. If a MacOS client joins the physical network and then moves to another location (getting an IP address outside the /24) and uses ZT to access the network, the ZT routes for the /24 network have disappeared (this is checked with netstat -rn).  You have to leave and join the ZT network to have the routes appear again. 

We did not check this with other ZT clients than for MacOS.

**Comment by laduke** [comment]
hi @pjurg!  See #600 I thought I was the only one experiencing this. Thanks for reporting. 
Fix coming soon.

**Comment by adamierymenko** [comment]
We think this is fixed in `dev`

**Comment by pjurg** [comment]
Great!
