### ISSUE TITLE
Need a way to troubleshoot connections

### ISSUE THREAD

**Issue by prutschman** [zerotier/ZeroTierOne#661]
I have two hosts, A and B, on a zerotier network. They're on disparate physical networks. Both show up as online according to the management interface.

Sometimes if I try to ping from A to B over the zt interface, I get latencies in the 150-300 ms range. It will stay like this for several minutes, or more, then will start dropping packets for 15-120 seconds, before resuming packet transmission.

Other times I won't be able to ping between them at all.

Both A and B show up as 'online' in the management interface. `zerotier-cli status` shows `ONLINE` for both.

It's not clear to me how to track down what the problem is.

**Comment by laduke** [comment]
We're working on features to make this easier

`zerotier-cli status -j` has a `tcpFallbackActive` field. If that's true, the host is relaying over tcp (slower). You can also look at `zerotier-cli listpeers` and see if the physical IP is known for a peer. 

Most of the time, it's just that port 9993/udp is blocked on the router or the host's firewall. 

https://support.zerotier.com/knowledgebase.php?entry=show&search-for=&article=ZGFmNzQyYjgzOTJhNWZhYWFkODk0Zjg3MTAxY2JkZWE_

**Comment by prutschman** [comment]
Would firewall rules explain excess latency and sporadic packet drops as well? It sure looks like the traffic is getting (sometimes) routed by one of your forwarding boxes, but then it drops out from time to time.

**Comment by joseph-henry** [comment]
Yes firewall rules could have that effect. Try temporarily disabling your firewall and see if that helps at all.

**Comment by adamierymenko** [comment]
The next version is going to have some remote diagnostics capabilities that will also make this easier, and better troubleshooting is an ongoing project.
