### ISSUE TITLE
local controller setup not working (LEDE) and other questions

### ISSUE THREAD

**Issue by boschkundendienst** [zerotier/ZeroTierOne#664]
I am running ZeroTier V1.2.4 on a TP-Link TL-4300 router with LEDE.

Client works out of the box and can be configured.

**So I wanted to setup my own controller.**
First thing I had to do was to change the init script for zerotier so that it points to a "real" folder instead of a folder in tmpfs by doing some minor changes to `/etc/init.d/zerotier`.

Client now runs reboot resistent with its config in folder `/zerotier`.

I added an alias to `/etc/profile` to be able to use the client without manually specifying the configuration directory all the time like this:

~~~
alias zerotier-cli='zerotier-cli -D/zerotier'
~~~

### setup environment

~~~
zerotierfolder=/zerotier
secret=$(cat /zerotier/authtoken.secret)
mynetworkname=ledecontrollertest
clientid=<my10digitclientid>
nwidbase="$clientid""______"
~~~

then I created the network with the following command executed directly on the router via SSH.

~~~
curl -H "Content-Type: application/json" -s -X POST -H "X-ZT1-Auth: $secret" -d " { \"name\":\"$mynetworkname\" }" http://127.0.0.1:9993/controller/network/$nwidb
ase
~~~

and received

~~~
{
  "activeMemberCount": 0,
  "authTokens": [],
  "authorizedMemberCount": 0,
  "capabilities": [],
  "clock": 1516354766654,
  "creationTime": 1516354766654,
  "enableBroadcast": true,
  "id": "<my 16 digit network id>",
  "ipAssignmentPools": [],
  "lastModified": 1516354766654,
  "multicastLimit": 32,
  "name": "ledecontrollertest",
  "nwid": "<my 16 digit network id>",
  "objtype": "network",
  "private": true,
  "revision": 1,
  "routes": [],
  "rules": [
    {
      "not": false,
      "or": false,
      "type": "ACTION_ACCEPT"
    }
  ],
  "tags": [],
  "totalMemberCount": 0,
  "v4AssignMode": {
    "zt": false
  },
  "v6AssignMode": {
    "6plane": false,
    "rfc4193": false,
    "zt": false
  }
}
~~~

I put my network id and the id of a client I wanted to joing in a variable for later use:

~~~
fullnetworkid=$(curl -s -X GET --header "X-ZT1-Auth: $secret" http://127.0.0.1:9993/controller/network/ | awk -F '"' '{print $2}')
clientid=<a valid 10 digit client id, in my case my iPhone>
~~~

### adding a client to my network
Next step was to add my iPhone (client) to the network with

~~~
curl -H "Content-Type: application/json" -s -X POST -H "X-ZT1-Auth: $secret" -d '{ "authorized": "true" }' http://127.0.0.1:9993/controller/network/$fullnetworkid
/member/$clientid 
~~~
**This does not work!** I also tried it with different tools like [postman](https://www.getpostman.com/) while mapping the 9993 port via SSH to my localhost but the only response I get from the controller is:

~~~
{}
~~~

As 

~~~
curl -s -X GET --header "X-ZT1-Auth: $secret" http://127.0.0.1:9993/controller/network/$fullnetworkid
~~~

shows, my network is running:

~~~
{
 "activeMemberCount": 0,
 "authTokens": [],
 "authorizedMemberCount": 0,
 "capabilities": [],
 "clock": 1516356956409,
 "creationTime": 1516354766654,
 "enableBroadcast": true,
 "id": "<16digitnetworkid>",
 "ipAssignmentPools": [],
 "lastModified": 1516354766654,
 "multicastLimit": 32,
 "name": "ledecontrollertest",
 "nwid": "<16digitnetworkid>",
 "objtype": "network",
 "private": true,
 "revision": 1,
 "routes": [],
 "rules": [
  {
   "not": false,
   "or": false,
   "type": "ACTION_ACCEPT"
  }
 ],
 "tags": [],
 "totalMemberCount": 0,
 "v4AssignMode": {
  "zt": false
 },
 "v6AssignMode": {
  "6plane": false,
  "rfc4193": false,
  "zt": false
 }
~~~

 and also the files

~~~
/zerotier/networks.d/<16digitnetworkid>.conf
/zerotier/networks.d/<16digitnetworkid>.local.conf
~~~

indicate that the network is working somehow.

**Another problem is present**, as long as any configuration file exists in `/zerotier/controller.d/`, when rebooting the router ZeroTier will not start correctly. The process of `zerotier-one` is present but hangs, no zt0 interface is present and `zerotier-cli` does not work because it can not connect.

My questions are:

 - Am I doing something wrong, what?
 - Why is ZeroTier no longer starting after reboot or when manually restarted when a controller configuration is present?
 - Why is there no clear documentation about the controller?
 - Why is there no picture that clearly shows how moons, earth, planets, leafs etc. work together?

**Comment by laduke** [comment]
Hi! 
Re: re-starting the controller: #553 

The curl to add a member looks ok at first glance. What happens if you tell your phone to join your network? Hop into https://my.zerotier.com/community if you want to chat about this stuff.

**Comment by glimberg** [comment]
You probably don't want to run a controller on LEDE.

Most of LEDE's filesystem is completely reset upon reboot.  Therefore nothing in /var/lib/zerotier is saved between restarts.  That's why your private key is stored in `/etc/config/zerotier`.  That small area of the filesystem is persisted between reboots.  You'll either need to edit scripts to point to an external drive plugged into the router via USB, or figure out some other way to persist data.  I don't think LEDE does much for wear leveling on flash, either, so with the amount of data writes it needs to do (depending on network size) may end up killing the flash memory on the device fairly quickly.

Second, that router has a pretty puny CPU for running a controller (Atheros AR9344 running at 560MHz).  ZeroTier controllers do a *lot* of crypto. That CPU is just going to get destroyed with work and will be slow.

At the least, get a RPi 3, or maybe a small $5/month VPS.  Raw CPU speed will be your most important factor with a controller.

**Comment by glimberg** [comment]
Oh and as for why it's not starting up correctly, that's probably because you need to edit the `/etc/init.d/zerotier` script to include `-D/zerotier`

**Comment by boschkundendienst** [comment]
@glimberg I agree about chip degration but I also tried on my local machine now and ZeroTier will no longer restart after controller is configured. So this could be a generic ZeroTier problem or an error I make. For testing purpose I think I could use my router (while keeping a look at degration).
A router costs 40 Euros and LEDE is ideal for testing. Of course when it works and is tested more suitable hardware is the best choice.

On a different github thread @warning is already implementing the option to change the configuration path via uci so if somone (like me) wants to change it, it will work.

**Comment by boschkundendienst** [comment]
@glimberg Thread about the implemenation of a custom configuration path:

https://github.com/mwarning/zerotier-openwrt/issues/25

and updated init script and a new configuration option called `config_path`

https://github.com/mwarning/zerotier-openwrt/blob/master/zerotier/files/zerotier.init
https://github.com/mwarning/zerotier-openwrt/blob/master/zerotier/files/zerotier.config
