### ISSUE TITLE
cannot execute any commands on Zerotier client

### ISSUE THREAD

**Issue by helenked** [zerotier/ZeroTierOne#665]
I install zerotier-cli using official guide, then its work properly, but some times ago I can't do any actions:

[root@]# zerotier-cli info
0 info invalid JSON response (parse error - unexpected 'c')

**OS Centos 7**

[root@]# zerotier-cli -h
ZeroTier One version 1.2.4 build 0 (platform 1 arch 2)
Copyright (c) 2011-2017 ZeroTier, Inc.
This is free software: you may copy, modify, and/or distribute this
work under the terms of the GNU General Public License, version 3 or
later as published by the Free Software Foundation.
No warranty expressed or implied.

Usage: zerotier-cli [-switches] <command/path> [<args>]

Available switches:
  -h                      - Display this help
  -v                      - Show version
  -j                      - Display full raw JSON output
  -D<path>                - ZeroTier home path for parameter auto-detect
  -p<port>                - HTTP port (default: auto)
  -T<token>               - Authentication token (default: auto)

Available commands:
  info                    - Display status info
  listpeers               - List all peers
  listnetworks            - List all networks
  join <network>          - Join a network
  leave <network>         - Leave a network
  set <network> <setting> - Set a network setting
  listmoons               - List moons (federated root sets)
  orbit <world ID> <seed> - Join a moon via any member root
  deorbit <world ID>      - Leave a moon

**Comment by laduke** [comment]
Hi @helenked, hop in https://my.zerotier.com/community and we can figure it out. 
It's usually, for some reason the zerotier-one service is stopped, or a firewall is blocking localhost:9993
