### ISSUE TITLE
Port-dependent connectivity failures on reboot

### ISSUE THREAD

**Issue by andrewgdotcom** [zerotier/ZeroTierOne#667]
Yesterday I rebooted a malfunctioning server. After it came back up, I found that only some of its peers could connect to its zerotier interface. It turns out that all the peers that could connect had a peers list that included the following entry:

> 200 listpeers 9fc3aa7661 x.x.x.x/60046;1050;259;1.00 14 1.2.4 LEAF

Whereas the peers that could not connect had this entry:

> 200 listpeers 9fc3aa7661 x.x.x.x/9993;2026;2026;0.83 21 1.2.4 LEAF

Where 'x.x.x.x' is the correct IP address in both cases. Checking netstat on the newly rebooted server gave the following:

> tcp        0      0 127.0.0.1:9993          0.0.0.0:*               LISTEN      1076/zerotier-one
> tcp6       0      0 ::1:9993                :::*                    LISTEN      1076/zerotier-one
> udp        0   1280 172.17.0.1:60046        0.0.0.0:*                           1076/zerotier-one
> udp        0      0 x.x.x.x:60046   0.0.0.0:*                           1076/zerotier-one
> udp        0      0 172.17.0.1:60047        0.0.0.0:*                           1076/zerotier-one
> udp        0      0 x.x.x.x:60047   0.0.0.0:*                           1076/zerotier-one
> udp        0      0 172.17.0.1:9993         0.0.0.0:*                           1076/zerotier-one
> udp        0      0 x.x.x.x:9993    0.0.0.0:*                           1076/zerotier-one

At this point I guessed that the problem was most likely in the zerotier daemon on the rebooted server, so I restarted the service. Netstat now gives:

> tcp        0      0 127.0.0.1:9993          0.0.0.0:*               LISTEN      17314/zerotier-one
> tcp6       0      0 ::1:9993                :::*                    LISTEN      17314/zerotier-one
> udp        0      0 x.x.x.x:60046   0.0.0.0:*                           17314/zerotier-one
> udp        0   3584 172.17.0.1:60046        0.0.0.0:*                           17314/zerotier-one
> udp        0      0 x.x.x.x:60047   0.0.0.0:*                           17314/zerotier-one
> udp        0      0 172.17.0.1:60047        0.0.0.0:*                           17314/zerotier-one
> udp        0      0 x.x.x.x:9993    0.0.0.0:*                           17314/zerotier-one
> udp        0   2048 172.17.0.1:9993         0.0.0.0:*                           17314/zerotier-one

Note that the only substantial difference is the count in the Send-Q column.

And now all the peers can connect! They seem to have a freshly-randomised distribution of 9993 and 60046 in their peer listings, but it doesn't seem to affect functionality.

I have noticed similar problems on occasion with a laptop ever since I started using zerotier, but they all went away within 24h without my intervention. That was a mere inconvenience, but in this instance it was an important server.

The question is a) what might cause the failure of zerotier on only one of its listening ports? And b) if there are multiple redundant ports open, why does it take hours and not minutes for a remote peer to fail over?

**Comment by adamierymenko** [comment]
That's very strange indeed. I don't think the send-q column is relevant since if you're transferring a lot of traffic send-q is going to be something non-zero.

One thing I did notice is that there are multiple 172.x.x.x addresses. What are these? Is there more than one LAN connection?

**Comment by andrewgdotcom** [comment]
The 172.17 addresses are Docker.

**Comment by adamierymenko** [comment]
What's in iptables?

**Comment by andrewgdotcom** [comment]
Quite a bit, but it's mostly a basic ufw config with some SSH and HTTP(S) holes. There's an outgoing NAT on the docker interface. I can send the full output to you if you like (don't want to dump it here).

**Comment by joseph-henry** [comment]
@andrewgdotcom is this an issue you're still experiencing as of `1.2.12`?

**Comment by andrewgdotcom** [comment]
It was only ever an intermittent error, so I can't be sure. But I don't remember it happening recently.

**Comment by joseph-henry** [comment]
Ok, thanks for reporting in on this. I'll close this ticket for now but feel free to request we reopen it if the issue pops up again.
