### ISSUE TITLE
REQ: zerotier on ESP32 or other 'arduino' like hardware

### ISSUE THREAD

**Issue by syadnom** [zerotier/ZeroTierOne#668]
I would like to see a zt client on ESP32 or similar 'high powered' arduinos.

The idea is to make a private IoT cloud instead of using https 'bare' over the public internet.  Ideal target would be the cellular connected ESP variants.

**Comment by adamierymenko** [comment]
We've actively researched this but it would likely require a lighter weight build. Unfortunately I don't think we have the time/bandwidth to work on this unless someone sponsors it via enterprise support or a donation for this port.

**Comment by syadnom** [comment]
I'm one, but I'd need to basically crowdfund it 'cause I can't drop big money on this feature.

**Comment by brendantay** [comment]
this would be awesome!
Would be interested in pushing crowdfunding campaigns :D

**Comment by jharsem** [comment]
Make that 9 =)

**Comment by ggarza78** [comment]
10!!!

**Comment by fpalen** [comment]
What is the status of this? because I would be 11

**Comment by ts-sz** [comment]
Hello,
I am 12!

**Comment by Arffeh** [comment]
So young to be using GitHub :)

**Comment by ts-sz** [comment]
I am the 12th! ;-)

**Comment by ts-sz** [comment]
for my devices i use 4G sticks E3372H, anyone try to port ZT to android (Android 2.3 )

Thanks

**Comment by kg9316** [comment]
Status om this one. Also willing to pay

**Comment by adamierymenko** [comment]
I don't think this is a high priority unless someone wants to put forward significant funding. It would require a lot of work and there isn't a lot of interest.

**Comment by Mifulapirus** [comment]
Also interested here, in case this ever needs support

**Comment by kg9316** [comment]
If we leave out arduino and just focus on Espreiff C for the ESP32 this would be much easier to achieve for the developers.

**Comment by alpharde** [comment]
Does the ESP32 even have enough horsepower to properly handle a VPN tunnel on the top of network connectivity? Even routers will sometimes struggle with this.
I believe it's better to just leave this task to (strategically placed) gateways.

**Comment by theronic** [comment]
@alpharde throughput would be lower, but I think it would be possible. Timely cryptography would be the main challenge.

**Comment by ukd1** [comment]
> I don't think this is a high priority unless someone wants to put forward significant funding. It would require a lot of work and there isn't a lot of interest.

@adamierymenko how much would this be? I'm also interested!

**Comment by dmotte** [comment]
I am interested too! I think that this is a great idea

**Comment by alireza787b** [comment]
Why not using ZeroTier Edge?
This way you can connect the Arduino via ethernet shield easily 
https://www.open-electronics.org/zerotier-edge-connect-all-the-things/

**Comment by chapiosh** [comment]
Count me in

**Comment by jimthedj65** [comment]
I have been working on espressif for some tiime now and have had some success with AI and vpn connectivity, I am also looking at porting libzt over to espressif range and hope to push some PR over to zerotier.  It can be done, just needs a lighter library to achieve the end goal.  will try and keep this group posted.

**Comment by Spaceinvaderz** [comment]
c’mon guys, wireguard has esp32 support so why zt not. pls count me in for croudfounding

**Comment by jbnetwork-git** [comment]
If is still under consideration.. im in too..

**Comment by beniroquai** [comment]
Would be great! :-)

**Comment by bmedici** [comment]
Would be a great feature for ESP32 !

**Comment by jaumarasigan** [comment]
This would be a great addition. I have a personal project using ZeroTier network and I have one web server in it. I would like to be able to add embedded devices such as ESP8266/ESP32.

**Comment by ukd1** [comment]
> I have been working on espressif for some time now and have had some success with AI and vpn connectivity, I am also looking at porting libzt over to espressif range and hope to push some PR over to zerotier. It can be done, just needs a lighter library to achieve the end goal. will try and keep this group posted.

Did you ever get a chance here?

**Comment by Derek-K** [comment]
While I was googling ZT and ESP I landed here... Yes, this would be a nice feature to have on ESP8266/32 development, and it will be great for many IoT devices behind router/firewall where users want to access them from the internet.

Also great to unify IoT devices across multiple locations/networks on the same ZT network range.

**Comment by zhzhzhy** [comment]
I've spent my time porting the zerotier(Libzt) on ESP32 using ESP-IDF framework these days.But I've enconunter serveral problems on CMake cross compile for this project.
I've finish the component with some struggling & debuging on CMake.Everything goes fine(ESP-IDF built finish) until cross build for libzt(100ERROR,36WARNING!)..haha
The compile says **'Mutex' does not name a type ‘**(Maybe The thread lock in FreeRTOS is't compatible with libzt itself)
Anyone can help me these errors?OR you can go on for my works on the project,maybe we can work together...
![Screenshot from 2022-08-29 21-46-59](https://user-images.githubusercontent.com/36782632/187216306-a3279a06-0263-4399-9c9f-ba860b52b184.png)

**Comment by zhzhzhy** [comment]
> 

the project is [https://github.com/zhzhzhy/Zerotier-Espressif](https://github.com/zhzhzhy/Zerotier-Espressif)

**Comment by jimthedj65** [comment]
> > I have been working on espressif for some time now and have had some success with AI and vpn connectivity, I am also looking at porting libzt over to espressif range and hope to push some PR over to zerotier. It can be done, just needs a lighter library to achieve the end goal. will try and keep this group posted.
> 
> @jimthedj65 did you ever get a chance here?

I actually built a gateway and routed it then I went down the pki route and blockchain and as adam mentioned this is a significant amount of work.  You can encapsulate ESP32 with a gateway if you have a small enabled zerotier pi.

After digging deep into the code am not sure zerotier or LWIP is the right horse, a library for ESP32 might be a step too far with little upside.

**Comment by mrarmyant** [comment]
What about looking at the client from Husarnet?  If they figured it out...

https://husarnet.com/business/open-source
https://github.com/husarnet/husarnet-esp32

I am currently using the ESP32 as a 4-Axis CNC controller.  It's got some oomph. (https://github.com/bdring/FluidNC)
