### ISSUE TITLE
Installing the network controllor on ubuntu

### ISSUE THREAD

**Issue by amoyer2** [zerotier/ZeroTierOne#669]
Is there little more detailed steps on installing the network controller? for Ubuntu to make the controller portion as well as the client the step I found are as follows and they don't make the installer.

make ZT_ENABLE_NETWORK_CONTROLLER=1 installer 

the terminal just kicks out make: *** No rule to make target 'installer'. Stop

**Comment by glimberg** [comment]
The network controller is included in the standard binary. There's nothing you need to build to enable it.
