### ISSUE TITLE
'-U' does not prevent zerotier-one from dropping privileges on Linux

### ISSUE THREAD

**Issue by Kassec** [zerotier/ZeroTierOne#671]
Hello,

I'm trying to run a moon on a privileged port and can't find out what's going on.

Running
```
root@x:/var/lib/zerotier-one# ./zerotier-one -p1024
```
is ok.
But:
```
root@x:/var/lib/zerotier-one# ./zerotier-one -p1023
./zerotier-one: fatal error: cannot bind to local control interface port
```
is not.
I even tried to assign id 0 to zerotier-one user in /etc/passwd, it doesn't change anything. Adding "-U" switch on cmd line doesn't do it either.

The system is a fresh stretch:
```
# uname -a
Linux xxx 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux
# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.3 (stretch)
Release:	9.3
Codename:	stretch
```
zerotier is installed through provided script:
```
# ./zerotier-one -v
1.2.4
```
Install is pretty minimalistic, nothing but sshd:
```
# netstat -putan
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      918/sshd            
tcp        0      0 x.x.x.x:22              x.x.x.x:29449           ESTABLISHED 20270/sshd: root@pt 
tcp6       0      0 :::22                   :::*                    LISTEN      918/sshd            
udp        0      0 0.0.0.0:68              0.0.0.0:*                           833/dhclient        
```
Selinux is not around either.
Even if not relevant here, iptables rules are empty and default policies are set to ACCEPT.

**Comment by glimberg** [comment]
By default, ZeroTier drops it's privilege level on Linux to be as low as possible.  Even when run as `root`.  This operation happens before ports are opened.  If you don't want this behavior, you can add the `-U` flag

      -U                - Skip privilege check and do not attempt to drop privileges

**Comment by Kassec** [comment]
As I wrote ```Adding "-U" switch on cmd line doesn't do it either.```
I just tried again:
```
root@x:~# zerotier-one -U -p1023
zerotier-one: fatal error: cannot bind to local control interface port
```

**Comment by glimberg** [comment]
Looks like there's a bug where the `-U` flag isn't working.  Going to edit the title of this issue and we'll get to work on it.

**Comment by Kassec** [comment]
I saw comments in code (One.cpp, line #888) then did another test: I removed user ```zerotier-one``` from ```/etc/passwd```. This way, it works and ```zerotier-one``` binds to privileged port.

Question: shouldn't privilege drop happen **after** binding ports ? Server apps usually do use their launch privileges (ie root) to bind (ie to privileged ports), then drop them for normal execution. If zerotier-one does not need root privilege for normal operations, why should we launch it with "-U" and have it keep unneeded root access on the system ?

**Comment by Kassec** [comment]
ByPass firewalls ;) ... ie running tests targetting udp/53 ...

Btw, where can I learn more about zerotier's fallback mecanisms ? When running on ZT roots, what's going on between the point where udp/9993 doesn't work and the point it switches to TCP/443 ? What's the protocol on those TCP/443 connections I see between endpoints and moons ? HTTPS ?

**Comment by glimberg** [comment]
Just added the CAP_NET_BIND_SERVICE permission for the service in the `dev` branch.  You'll be able to specify whatever port, even with the privilege drop.  

See https://github.com/zerotier/ZeroTierOne/commit/4878d8ec15892f2a14b4737d57864e2c34197507

As for the `-U` flag bug.  That appears to be a bug in 1.2.4, but its working in `dev`.  

As for your TCP fallback question, it just forwards the packets through one of our servers that's listening on TCP/443. It uses the ZeroTier protocol still, but disguised to look like a TLS connection to get around nosy deep packet inspection systems.  Everything is still encrypted end to end and we can't see the contents of your packets.
