### ISSUE TITLE
Using 100.64.0.0/10 for the ZT subnet doesn't work.

### ISSUE THREAD

**Issue by nolanl** [zerotier/ZeroTierOne#675]
I've always used subnets from the RFC6598 Shared Address space for my VPNs to avoid the usual "hotel wifi uses an overlapping subnet" problem.

This is technically allowed by RFC6598:
"Shared Address Space is IPv4 address space designated for Service Provider use with the purpose of facilitating CGN deployment. Also, Shared Address Space can be used as additional non-globally routable space on routing equipment that is able to do address translation across router interfaces when the addresses are identical on two different interfaces."

The only case where it can cause problems is if you (or your default route router, if you're routing via ZT) are plugged directly into an ISP doing CGNAT without an intermediate CPE doing RFC1918 NAT.  A CPE of that sort is "required" for customers of ISPs doing CGNAT, so that case is technically unsupported anyway, though in theory someone could do it.

Also, having to allowGlobal on windows/mac/linux hosts for a subnet that isn't global is annoying.  Android (and possibly IOS, not sure) seem to default to allowGlobal=true, so that isn't an issue there.

**Comment by adamierymenko** [comment]
CGN spaces are now considered private, which looking at the RFC looks correct.
