### ISSUE TITLE
 warning: `zerotier-one' uses 32-bit capabilities (legacy support in use)

### ISSUE THREAD

**Issue by flantel** [zerotier/ZeroTierOne#679]
Hi

Why do I see the error  _warning: `zerotier-one' uses 32-bit capabilities (legacy support in use)_  on various Linux 64bit installs?

Thanks

**Comment by adamierymenko** [comment]
For some reason the use of the Linux privilege configuration calls triggers this warning. It contains no 32-bit code so I'm not sure why, but I don't think it's a problem.

**Comment by leleobhz** [comment]
Just a reference in a dead thread: https://talk.plesk.com/threads/warning-about-in-proftpd-is-it-a-problem.342030/#post-820514

May zerotier suffer this 'issue" about old libcap? If yes, its just a cosmetic change to depend on libcap2?

**Comment by bish0polis** [comment]
Yeah, it seems to suggest it needs linking against a newer libpcap to make it stop complaining.

**Comment by dec0dOS** [comment]
<img width="952" alt="Screenshot 2022-08-24 at 00 48 12" src="https://user-images.githubusercontent.com/14824142/186272524-1b3f1b8a-598b-4297-bed6-b0564a6a9a0b.png">
This warning is still presented in 1.10.1 in 2022. Any updates?

**Comment by glimberg** [comment]
@dec0dOS As last stated in this closed issue, this is not a bug, problem or anything to worry about.

**Comment by bish0polis** [comment]
> @dec0dOS As last stated in this closed issue, this is not a bug, problem or anything to worry about.

I didn't see the 'stated' part.  I see speculation it's not serious, and I see someone asking whether it's a cosmetic change, but I don't see anyone stating it's a non-issue.  MMMV I guess.
