### ISSUE TITLE
BRIDGING!

### ISSUE THREAD

**Issue by adamierymenko** [zerotier/ZeroTierOne#68]
Add support for bridging ZT1 virtual LANs with real ones.

**Comment by JimmyAstle** [comment]
Any documentation for bridging? Have Zerotier on a Ubuntu machine who's interfaces I want to bridge. I have tried all different configuration combos but nothing seems to work. On the Ubuntu machine I see the arp requests but noone is answering.

**Comment by adamierymenko** [comment]
There isn't much yet, unfortunately -- partly because we're working on new features and a new control panel that will make bridging simpler.

The best way to think of it is that it's *exactly* like bridging two standard Ethernet segments. All the same caveats around IP addressing apply.

For example: let's say you have two sides. One has addressing scheme 10.0.0.0/8, the other has 10.1.1.0/8.

If a bridge is created between them, packets will traverse but a machine at 10.0.0.1 will *not* automatically see 10.1.1.1. Why? Because 10.0.0.1 doesn't know 10.1.1.0/8 is on its local LAN segment. It's going to try to route that via 'default', which will fail.

But if you add a route on 10.0.0.1 via the device (a local route) to 10.1.1.0/24, it will work. Now 10.0.0.1 knows that 10.1.1.1 is on its local LAN rather than reachable via a gateway.

The second caveat is DHCP: be sure you set up rules on the bridge to block DHCP packets, or hosts might get DHCP from the far side of the bridge. (Unless of course this is what you want.)

**Comment by feliksik** [comment]
>For example: let's say you have two sides. One has addressing scheme 10.0.0.0/8, the other has 10.1.1.0/8.

Do you mean /16 or /24? You are speaking about two sides with /8 subnets, but these are the *same* subnet (i.e. same addressing scheme). To me, this only makes sense when the bridging interface is doing Proxy ARP, in which case no special routes are necessary; both sides should have a route like 

    Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
    10.0.0.0        0.0.0.0         255.0.0.0       U     0      0      0   zt0

> If a bridge is created between them, packets will traverse but a machine at 10.0.0.1 will not automatically see 10.1.1.1. Why? Because 10.0.0.1 doesn't know 10.1.1.0/8 is on its local LAN segment. It's going to try to route that via 'default', which will fail.

This suggests you are connecting 2 subnets with ZeroTier as a L3 router (i.e. it is routing, not briding?), which which case I would expect the subnets to be non-overlapping, i.e. /16 or /24 in this example. 

Or am I completely wrong? @adamierymenko , can you explain?

**Comment by feliksik** [comment]
I figured it out and am now able to use ZeroTier in bridge modes. There are different ways to do it, but I documented mine on https://www.zerotier.com/community/topic/5/how-to-use-zerotier-with-bridge-mode . Hope this helps others, too!
