### ISSUE TITLE
Need an updated zerotier image on docker hub

### ISSUE THREAD

**Issue by ghost** [zerotier/ZeroTierOne#682]
current image "hangs" indefinitely when run in Kubernetes containers on aws, happens when running various commands like "netstat -a", "docker ps", etc.

**Comment by OmgImAlexis** [comment]
@adamierymenko could you please setup auto building on Docker Hub.

**Comment by bltavares** [comment]
I would be interested in helping with this, and also to provide support for Docker on ARM (useful for raspberry-pies)

It would be interesting to see if we could have support from https://github.com/docker-library/official-images to build a official zerotier image, and take advantage of the ARM and x86 build agents to push it there. What do you think?

**Comment by rwv** [comment]
Is there any plan to update the image on [Docker Hub](https://hub.docker.com/r/zerotier/zerotier-containerized)?

**Comment by bltavares** [comment]
I'm still available to help with the multi-arch official image as proposed a while ago.

**Comment by adamierymenko** [comment]
Closing since it's easy enough to add it via a Dockerfile from packages and this is yet another thing for us to maintain. We're already stretched a little thin in that respect.
