### ISSUE TITLE
user-mode TCP stack, runs in browser, webassembly, websockets

### ISSUE THREAD

**Issue by unicomp21** [zerotier/ZeroTierOne#684]
Create a user-mode TCP stack using something like lwip, which can run in a web browser using webassembly.  Comms to zerotier server use websocket or long polling https.

**Comment by adamierymenko** [comment]
We have actively researched this. Closing because it's sort of on the long term road map.

**Comment by aarlt** [comment]
Any news on this? What is the current state?

**Comment by unicomp21** [comment]
@adamierymenko is there a tracker somewhere for this stuff which I can watch?

**Comment by unicomp21** [comment]
@adamierymenko i'm also thinking there might be synergy w/ the team at leaningtech?

**Comment by p10tyr** [comment]
bump

**Comment by maci0** [comment]
@unicomp21 seem that team decided to go with tailscale instead and compile their go client to wasm

**Comment by unicomp21** [comment]
Yeah, it's a shame Zerotier doesn't have the same support, right?  Huge
opportunity?
