### ISSUE TITLE
Next stable release?

### ISSUE THREAD

**Issue by apognu** [zerotier/ZeroTierOne#687]
The last stable release has been out since April, 2017. There are some changes on dev/edge that fix some nasty issues related to controller operations (#553). And running dev/edge brings in new issues (#680, #644), which is to be expected since those branches are not supposed to be stable.

Do you have any idea when the next stable release of ZeroTier One will be out?

**Comment by adamierymenko** [comment]
Very soon. We have no more blocking issues and are updating docs, etc. for 1.2.6.
