### ISSUE TITLE
Finer grained control on route handout by network controller: selective omission, geoIP-based handout, etc.

### ISSUE THREAD

**Issue by ramcq** [zerotier/ZeroTierOne#688]
Hi there, I've got a VPN which offers both routed IPv4 and IPv6 to client end-points. ZeroTier is awesome and is working very well. One use-case it'd be cool if you could consider would be to have ZeroTier use a network-provided default route only in the case that the OS doesn't have one for that stack. Quite commonly I am on IPv4-only networks, so having IPv6 connectivity through the VPN is really helpful - but I can imagine the reverse has value too, having the VPN provide an IPv4 default route to a v6-only host. Alternatively, and possibly simpler to implement, would be having an allowDefaultV6 option that would only apply the IPv6 default route.

**Comment by adamierymenko** [comment]
Just add a V6 default gateway on the network but not a V4 one?

**Comment by ramcq** [comment]
Right - but ideally I'd have one network to join all of the end clients to, allowing them to communicate with each other on IPv4 and IPv6, with consistent/predictable addressing, rather than handling switching them between two networks depending on whether they needed IPv4 routing or not.

**Comment by adamierymenko** [comment]
Hmm... I'm backlogging this. I think it should be done not via client permissions but finer grained control on routes, etc. at the controller.

**Comment by adamierymenko** [comment]
Retitled to also capture the idea of geoIP-based handout of gateways which others have mentioned and suggested.

**Comment by adamierymenko** [comment]
I think this is way beyond scope unless someone wants to sponsor it...

**Comment by ramcq** [comment]
This is a slightly unusual journey for what was originally a relatively simple request - you substantially increased the scope and complexity last year by adding various other requirements, and then came back this year and said the scope of the request was too great. Can I re-file the original request for some super-dumb client side filtering of routes? :) Or a way to achieve similar?
