### ISSUE TITLE
Zerotier-one was always crashed with error "Bus Error" on android linux (linux deploy ubuntu)

### ISSUE THREAD

**Issue by firefly917** [zerotier/ZeroTierOne#692]
My system is ubuntu deployed on an android chroot (linux deploy).
The program of zerotier-one was obtained by compiling the source code on githut.
But when the command of zerotier-one starting, the program would be crashed with error  "Bus Error".
How to fix this problem?

**Comment by glimberg** [comment]
I seriously doubt that is going to work in any way, shape or form.  ZeroTier for Linux requires a TAP driver to be installed on the system, which 1) Android doesn't have and 2) android doesn't allow.  A chroot environment isn't going to change that either as you'll still be running under the device's default kernel.  Only a rooted phone could potentially allow this, but it's not a configuration that we support.

Your best bet will be to use the Android app on the Play store.
