### ISSUE TITLE
Possible NAT traversal issue

### ISSUE THREAD

**Issue by blurredpixel** [zerotier/ZeroTierOne#693]
I have found something interesting and in-case anyone else is having the same issue.

I have two zerotier clients on my network, one is a physical computer and one is a hyperv VM running on that computer connected to an external virtual switch, I.e it is on the same network. The physical machine peers correctly with all nodes on the zerotier network, but the hyperv VM is not peering directly and falling back to TCP. I use the VM to route to other subnets across zerotier, and my physical machine is just acting as another client receiving those routes directly. I have noticed that a firmware update to my router resolved the issue for a few days, but now this issue has returned. Could be it be some sort of NAT setting on my router? I read in the docs about Cone NATing but I'm not sure if that would apply here.

**Comment by blurredpixel** [comment]
As an update sometimes my clients are peering correctly, and sometimes they aren't.

**Comment by adamierymenko** [comment]
(1) Does the hyperVM have any local firewalls or firewalls in the VM software?

(2) Does your router have "local isolation?" This is a (mis)feature on some wireless access points. It makes sense for public access points in coffee shops and such but is usually a bad thing on private networks as it prevents just about anything local from working.
