### ISSUE TITLE
ZeroTier substantial data usage on Raspberry Pi

### ISSUE THREAD

**Issue by timothy-gibson** [zerotier/ZeroTierOne#694]
Hi. I have multiple raspberry pi's deployed to the field connected to the internet via 4G dongles. After doing some digging into the cause of a big data bill with iftop, it appears that ZeroTier uses a substantial amount of data per month. I thought this was probably reasonable due to the amount of infrastructure that is running on my ZeroTier network. However, after leaving my ZeroTier network (`using zerotier-cli leave __networkID__`), I found that the ZeroTier servers were still sending a substantial amount of data to my device. This seemed to be on average 3-4kbps which equates to around 1GB per month - with no ZT network joined. 

Is that data usage reasonable? If so, is there any way I can adjust settings to reduce that down for devices which have low data limits? Thanks very much in advance.

**Comment by jungle-boogie** [comment]
> with no ZT network joined.

The pi wasn't connected to a network, but the process was still alive and sending data?

**Comment by timothy-gibson** [comment]
@jungle-boogie, yes that’s correct, the service was still active. What I’m wondering though, is that data usage expected for ZeroTier and is there any way I can reduce it to fit low data requirements for the Pis I have deployed to the field?

**Comment by joseph-henry** [comment]
Hi @timothy-gibson that definitely doesn't sound like it should be happening. Can you email us your device ID to contact@zerotier.com? We can take a look.

**Comment by timothy-gibson** [comment]
Thanks @joseph-henry I've emailed you IDs of some of the devices exhibiting the problem.

**Comment by adamierymenko** [comment]
The core issue here is that the desktop/server versions are not optimized for reduced bandwidth use in the idle case because usually this isn't an issue. 1GB of traffic on a cable, DSL, or data center link is trivial. It's not on LTE though, which is why the mobile versions fully shut down when no network is joined.

We are working on some improvements and changes that might greatly reduce idle bandwidth consumption and reduce protocol traffic in general but these will not appear until the 1.4.x branch.

In the meantime I'd suggest stopping the service when you are not using it.

**Comment by PilotAware** [comment]
Could you provide an update here
Has the issue been investigated/ improved ?
If so which version git hash related to any fixes

**Comment by PilotAware** [comment]
Adding some more context
I have been analyzing using tcpdump
With virtually no data going through the vpn tunnel/ zt interface, the overhead of traffic vast majority on port 9993 is
140 MB per day

wow!
So on a cellular connection that is 4GB of data with no payload whatsoever 
There must be a way to improve this ?

**Comment by Balipeace** [comment]
I agree, there is a ridiculous amount of overhead traffic from Zerotier. Leave won't stop it. Only removing Zerotier from your system will stop this.

**Comment by jmorris644** [comment]
We just got our first monthly LTE bill with zerotier running. Holy crap!!! What a terrible surprise!!!

IMO, this is an unworkable solution for cellular based deployments.

**Comment by bam80** [comment]
In my experience Tailscale showed better results

**Comment by jmorris644** [comment]
Thanks. It would have to be a LOT better. Zerotier used on average 54Mb per day!!

**Comment by bam80** [comment]
It's not negligible for LTE still but a lot better. Try it yourself and report here :)

**Comment by jmorris644** [comment]
I am reviewing a few options. Tailscale being one of them.

Before zerotier I had developed a homegrown dynamic network using openVPN, MQTT, and node-red. I may dust off that code.

**Comment by emonindonesia** [comment]
I can confirm the high data use of Zerotier. I switched to Wireguard a long time ago. Only 512kB/day

**Comment by jmorris644** [comment]
Agreed. I just installed tailscale (wireguard) and the traffic dropped immensely.
