### ISSUE TITLE
Enable for ppc64le

### ISSUE THREAD

**Issue by mksully22** [zerotier/ZeroTierOne#701]
This patch was integrated into Alpine to enable zerotierone to be supported on ppc64le.  Can this be integrated here to also add support...
https://github.com/alpinelinux/aports/pull/3542

`--- a/make-linux.mk
+++ b/make-linux.mk
@@ -154,6 +154,11 @@
         ZT_ARCHITECTURE=6
        override DEFS+=-DZT_NO_TYPE_PUNNING
 endif
+ifeq ($(CC_MACH),powerpc64le)
+        ZT_ARCHITECTURE=7
+        override DEFS+=-DZT_NO_TYPE_PUNNING
+endif
+

 # Fail if system architecture could not be determined
 ifeq ($(ZT_ARCHITECTURE),999)`

**Comment by mksully22** [comment]
Patch got mangled, reposting, 

```diff
--- a/make-linux.mk
+++ b/make-linux.mk
@@ -154,6 +154,11 @@
         ZT_ARCHITECTURE=6
        override DEFS+=-DZT_NO_TYPE_PUNNING
 endif
+ifeq ($(CC_MACH),powerpc64le)
+        ZT_ARCHITECTURE=7
+        override DEFS+=-DZT_NO_TYPE_PUNNING
+endif
+

 # Fail if system architecture could not be determined
 ifeq ($(ZT_ARCHITECTURE),999)
```

**Comment by adamierymenko** [comment]
Done.
