### ISSUE TITLE
zt1 ip is assigned as 169.254.x.x

### ISSUE THREAD

**Issue by yeyichao** [zerotier/ZeroTierOne#703]
zt1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 2800
        inet 169.254.71.21  netmask 255.255.0.0  broadcast 169.254.255.255
        inet6 fe80::431d:f97d:1f3a:d75f  prefixlen 64  scopeid 0x20<link>
        ether e6:e9:60:28:17:ac  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 43  bytes 8957 (8.7 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

I run zerotier in my raspberry pi, sometimes zt1's ip is normal,. but this probability is small. zerotier in my ubuntu 14.04 vm is working.

**Comment by laduke** [comment]
Hey @yeyichao hop in https://my.zerotier.com/community and we can trouble shoot

It sounds like it's not getting an IP from the controller/my.zerotier.com 
First guess is: Check your ubuntu firewall and your internet router for port 9993/udp being allowed.
