### ISSUE TITLE
Mapping specific dev (i.e. network interface) to network

### ISSUE THREAD

**Issue by obadz** [zerotier/ZeroTierOne#705]
Are networks mapped to interfaces in a deterministic order? I worry that if they're networks are randomly mapped to `zt0`, `zt1`, etc. it makes device firewalling hard to do reliably.

**Comment by glimberg** [comment]
In the current release they're mapped in the order joined.  From then on, each network will always be assigned the same device.

In the next release, if the OS supports it, each network is given a unique device name.

**Comment by obadz** [comment]
Answered in https://github.com/zerotier/ZeroTierOne/issues/161#issuecomment-376711423
Thanks!

**Comment by obadz** [comment]
> In the next release, if the OS supports it, each network is given a unique device name.

@glimberg, is there a PR or commit I can read? Will the interfaces basically contain the network names?
