### ISSUE TITLE
Windows client memory usage grows to several GB

### ISSUE THREAD

**Issue by hannesbe** [zerotier/ZeroTierOne#706]
We're experiencing a problem on a specific ZeroTier network: the memory usage of the Windows service grows to several GB. All clients connected to this network show similar behaviour. 

It looks to be related to this specific network only, because when only connecting such a problem client to a test network, the situation resolves to normal. 

--
Regards,
Hannes

**Comment by glimberg** [comment]
Hi Hannes,

Can you shoot us an email to `contact@zerotier.com` with the network ID you're seeing this on?  Thanks!

**Comment by hannesbe** [comment]
Hi Grant,

I mailed you on March 31 the network ID. Did you got this and did you already have a chance to have a look? Thx!

**Comment by adamierymenko** [comment]
We still can't reproduce this here. I think the best course of action is for us to release 1.2.6, which contains a number of bug fixes and other improvements, and to see if the issue persists. If it does we'll know it's not something we've fixed as a consequence of fixing something else.

**Comment by hannesbe** [comment]
Thx, are there binaries available for 1.2.6 yet, so we can test?

**Comment by joseph-henry** [comment]
@hannesbe Do you still see this as of `1.2.10` ?

**Comment by hannesbe** [comment]
We are running a bridge using OPNsense on this network. Updating OPNsense to the latest version seemed to be related somehow: the issue disappeared completely after this update.
