### ISSUE TITLE
Zerotier interface restricting / ARP

### ISSUE THREAD

**Issue by costpermille** [zerotier/ZeroTierOne#707]
The zerotier application appears to be sending arp requests out through all/incorrect interfaces (this is particularly bad for me to the point where I've had to uninstall to not get my switchport disabled) and binding to every IP on the machine. 

How can I stop or restrict this behaviour? I can't seem to find anything in documentation that lets me lock down zerotier to only listening on a single ip:port combination.

OS: Ubuntu 16 LTS
HW config: 3 physical adapters, one internet/WAN (let's call it eth0) that I want to bind zerotier to. It should not touch or go near any other adapter; but it is sending arp requests out of eth0, eth1, and eth2.

**Comment by laduke** [comment]
You can blacklist interfaces

https://github.com/zerotier/ZeroTierOne/tree/master/service

**Comment by costpermille** [comment]
My apologies, I've missed that then. Is there any way to force it to only pipe all access through a single IP though and not listen on *?

**Comment by laduke** [comment]
I don't think so (?) 
A whitelist would be better than a blacklist for some uses I guess. 
I guess there's an `arptables` package for ubuntu, not sure if that'd do it.
