### ISSUE TITLE
Join network OK but there shows PORT_ERROR when list networks

### ISSUE THREAD

**Issue by qqlovekerry** [zerotier/ZeroTierOne#708]
Hello, I want to let the VPS join one network with my PCs. I have installed ZeroTier on VPS and use `zerotier-cli join Network_ID` to let VPS join my private network, it shows `200 join OK` after the command is typed in the terminal. However, I found the PC and the VPS cannot ping each other and when I used `zerotier-cli listnetworks` on the VPS to see the information about the networks, the line prompted in the terminal contains `PORT_ERROR` in it. It is something like `200 listnetworks Network_ID Network_name ae:f7:f1:ad:xx:xx PORT_ERROR PRIVATE fca2:xxxx:6de2:32a7:afce:0000:0000:0001/40,172.27.xx.xxx/16`. And when I use `ifconfig` in the terminal, there is no networks named like `zt0` in VPS. Is there some problem with ZeroTier? Could you please tell me how to solve this issue?
Any help would be much appreciated!

**Comment by glimberg** [comment]
It's possible you don't have the kernel TAP driver installed, thus it can't be loaded.  (I'm assuming you're on Linux)

**Comment by qqlovekerry** [comment]
Thanks very much for your reply! I am using Ubuntu 16.04 on VPS but I am not an expert. I am sorry I do not quite understand the kernel related concepts. If it is reasonable and not a bug, I think I should give up using ZeroTier on the VPS. Maybe I will try it on some other VPS later. Anyway, thanks very much for your help!

**Comment by jamiechoi1995** [comment]
@qqlovekerry I meet the same issue, 

I solve it by opening TUN/TAP on the setting page of the VPS

**Comment by qqlovekerry** [comment]
@jamiechoi1995 Thanks very much for sharing your solution! I will try that later.
I faced this problem several months ago, at that time, I want to speed the connection between my PC and the VPS since Resilio Sync is installed on both of them and the connection to some server of Resilio Sync is banned in mainland China. However, I found that since the VPS has a public IP address, it seems there is no need to install ZeroTier One on the VPS.
I am kind of curious that why do you install ZeroTier One on your VPS. If it is possible, could you please share the purpose to install it on the VPS?
Any help would be much appreciated!

**Comment by jamiechoi1995** [comment]
@qqlovekerry 
Well, I need to connect to the computer in my lab from my PC or my cell phone, to monitor my deep learning training.

**Comment by qqlovekerry** [comment]
@jamiechoi1995 Thanks for your reply! That sounds cool.
It seems you need to install ZeroTier on the computer and other PCs and phones. But I do not quite understand why you need to install the software on your VPS. Could you please explain more?

**Comment by jamiechoi1995** [comment]
@qqlovekerry I install it on VPS to speed up my connection, that's called "MOON server" in ZeroTier

**Comment by qqlovekerry** [comment]
@jamiechoi1995 Thanks very much for your sharing! That is fantastic. I think I need that too, I will try that.

**Comment by qqlovekerry** [comment]
@jamiechoi1995 Thanks very much for your sharing! That is fantastic. I think I need that too, I will try that.

**Comment by qqlovekerry** [comment]
@jamiechoi1995 Thanks to your information I have set my VPS as the MOON server. Can I ask you one more question? How do I know whether the connection is not going through the PLANET server or the MOON server?

**Comment by jamiechoi1995** [comment]
@qqlovekerry I don't know if there is an official method for this question,
but I think you can scp a file between two planet and log in the monitor page of the VPS to watch the bandwidth usage.

**Comment by qqlovekerry** [comment]
@jamiechoi1995 Thanks very much for all your help! That's very clever.

**Comment by GregHilston** [comment]
> @qqlovekerry I meet the same issue,
> 
> I solve it by opening TUN/TAP on the setting page of the VPS

@jamiechoi1995 can you explain this a bit more? Having this exact issue on default install of Linux Mint

**Comment by jamiechoi1995** [comment]
> 
> 
> > @qqlovekerry I meet the same issue,
> > I solve it by opening TUN/TAP on the setting page of the VPS
> 
> @jamiechoi1995 can you explain this a bit more? Having this exact issue on default install of Linux Mint

That depends on the VPS you used. I use HostUS and it has an option of opening TUN/TAP on the setting page.

**Comment by GregHilston** [comment]
Wish I wrote down how to solve this a year ago, as I'm back one year later! This time on Pop OS

If I figure it out, I'll document not only for the future other individuals, but the future me as well ;)
