### ISSUE TITLE
Unable to PING my DC via ZeroTier Network

### ISSUE THREAD

**Issue by franbotha** [zerotier/ZeroTierOne#709]
Hi all.

I am having an issue where I am just not able to ping my DC on its ZT IP. I can do this with every other machine in my network but not this one. 

I need to find a way to fix the DNS issue as currently my client computers are not able to authenticate from home or other networks but I can't even ping the IP of my DC (also DNS server).

Any ideas?

**Comment by glimberg** [comment]
Check your Windows firewall.  Often times windows blocks ICMP by default.

**Comment by franbotha** [comment]
Windows Firewall is down at the moment - thought it was that initially. Meh.

**Comment by franbotha** [comment]
Some feedback about this: I removed the interface and then also removed the IP that ZT reserved for my DC. I then reinstalled the interface onto the DC, removed the bridging option and assigned it a new IP. Reboot.

I could then ping the DC's ZT IP externally and internally. I then added the ZT IP of my DC into my ZT interface on my laptop and it started showing up as a domain network.

**Comment by laduke** [comment]
Feel free to re-opened. Not sure what happened or resolved it.
