### ISSUE TITLE
OSX zerotier daemon not stopping

### ISSUE THREAD

**Issue by fighne** [zerotier/ZeroTierOne#710]
OSX zerotier daemon when installed is configured to autostart, when preferences are changed it still autostarts.

**Comment by glimberg** [comment]
The preferences in the GUI are for starting the GUI program on startup/shutdown.  Additionally, any program running when MacOS is restarted, by default all programs that were running when previously shut down will start back up.

The zerotier-one service is separate and managed by launchd.  See here for how to unload the service: https://github.com/zerotier/ZeroTierOne/issues/157
