### ISSUE TITLE
High CPU usage when connected to Earth on Windows 10

### ISSUE THREAD

**Issue by Spass1966** [zerotier/ZeroTierOne#711]
Idles between 2 and 4 percent.

**Comment by adamierymenko** [comment]
What's the CPU architecture of this machine. That doesn't seem bug-high, maybe just inefficient-code-high. Flagging as a possible performance problem or regression on Windows.

**Comment by taohansen** [comment]
Intel i7-6820HQ, 4 cores

**Comment by joseph-henry** [comment]
@taohansen Do you still see this issue after upgrading to `1.2.10`?

**Comment by taohansen** [comment]
@joseph-henry I no longer have access to a Windows machine to test.
