### ISSUE TITLE
Bridging to docker virtual adapter (windows)

### ISSUE THREAD

**Issue by stevemk14ebr** [zerotier/ZeroTierOne#713]
I am using docker-for-windows and have a container inside a machine bound to localhost
![ombi](https://user-images.githubusercontent.com/6619205/38790854-e8b35a18-4111-11e8-904a-6d97cd66ee90.PNG)

With windows this all actually runs inside of a hyper-v vm. So to access i goto 10.0.75.2:3579. Here's the interface used from hyper-v and the ip via mac lookup with 'arp -a' command:
![hyper-v](https://user-images.githubusercontent.com/6619205/38790953-ac1f7be4-4112-11e8-9df6-75154b54f7fd.PNG)

Note that 10.0.75.1:port is how i access my localhost servers on the host, from within the dockerized containers. That is .2 gets into docker, .1 gets out of docker back to host.
![capture](https://user-images.githubusercontent.com/6619205/38791226-898b919c-4114-11e8-97e3-20417ac9503d.PNG)

I need to bridge the zerotier network i'm running, with the hyper-v virtual interface that i access via 10.0.75.2 so that my containers are accessible over my zt network, currently they are not and connections to $zt_ip:3579 fail to resolve (obviously). How do i do this?
![capture](https://user-images.githubusercontent.com/6619205/38791042-3ac49c58-4113-11e8-863f-3c1c43cf9c66.PNG)

**Comment by adamierymenko** [comment]
Are the MTUs the same? Linux can handle bridging different MTUs but neither Windows nor MacOS can handle this.

**Comment by stevemk14ebr** [comment]
No they are different, is it safe for me to modify zerotier's or dockers mtu size? 

>   1500                1  463574435091  328769242504  Wi-Fi 2
>   1500                5          0          0  Local Area Connection* 13
>   1500                1          0   16304818  VirtualBox Host-Only Network
>   1500                1          0    2512397  vEthernet (Default Switch)
>   1500                1          0   33120810  vEthernet (nat)
>   1500                1  1295006727719  789060196225  vEthernet (DockerNAT)
>   2800                1    5783881  175400922  Ethernet 3

**Comment by adamierymenko** [comment]
A better way to do this might be to just make a Docker container that runs ZT as a bridge.

**Comment by adamierymenko** [comment]
Also Windows is soon making WSL a real Linux kernel in a micro-VM.
