### ISSUE TITLE
Replace calls to /sbin/ip on Linux with direct programmatic configuration of network devices (was: "unable to add ip address" with unprivileged user on Manjaro)

### ISSUE THREAD

**Issue by jonathonf** [zerotier/ZeroTierOne#714]
_(Additions to the original are in italics)_

## Summary

_When there is an unprivileged user "zerotier-one" present on a Manjaro system,_ ZeroTier fails to add an IP address to a zt0 device with the message "ERROR: unable to add ip address 10.0.0.1/24" (where 10.0.0.1 is the IPv4 address assigned via the web dashboard). It is repeated for the assigned IPv6 address.

Manually adding the ZT IP and route via `ip` succeeds.

## Details

~~I run ZT on a variety of devices (Linux, Windows, Mac, Android) and this issue occurs on only one of my Linux machines. Configuration is pretty much identical to another machine which works perfectly. I can't see any reason for it, and I can't seem to find or generate any more logging output.~~

Manually running

```
sudo ip addr add 10.0.0.1/24 dev zt0
sudo ip route add 0.0.0.0/1 via 10.0.0.254 dev zt0
```
succeeds; the ZT network becomes accessible and traffic is routed over the global/managed route. Restarting the ZT service after this "loses" the IP and route.

## Log output

The output from `journalctl -u zerotier-one` shows:

```
Apr 16 09:33:28 box systemd[1] Started ZeroTier One.
Apr 16 09:33:28 box zerotier-one[5691]: ERROR: unable to add ip address 10.0.0.1/24
Apr 16 09:33:28 box zerotier-one[5691]: ERROR: unable to add ip address fde5:::1/88
```

Output from `zerotier-one` directly is:

```
$ sudo zerotier-one
ERROR: unable to add ip address 10.0.0.1/24
ERROR: unable to add ip address fde5:::1/88
```

_This also occurs when specifying not to drop privileges:_
```
$ sudo zerotier-one -U
ERROR: unable to add ip address 10.0.0.1/24
ERROR: unable to add ip address fde5:::1/88
```

## System details

OS: Manjaro Linux 64-bit
Tested kernels: 4.14.34, 4.15.17, 4.16.2
ZeroTier version: 1.24 (from https://www.archlinux.org/packages/community/x86_64/zerotier-one/)
systemd version: 238.76

~~(The same setup works perfectly on another machine)~~

**Comment by adamierymenko** [comment]
Are you using selinux?

**Comment by jonathonf** [comment]
No selinux or apparmor or any kernel hardening. I'm quite happy to admit it's _something_ I've done but I haven't yet found a way to work out what...

(I've also removed and reinstalled, as well as updating to 1.2.6, same end result ("unable to add ip address")).

Given that it worked previously something must have changed on this particular system that didn't change on my other systems. I'll have another dig through package update logs...

**Comment by adamierymenko** [comment]
It could be some issue with dropping privileges. There is a `-U` flag to not do this, or you can remove the `zerotier-one` user and it won't do it.

**Comment by adamierymenko** [comment]
It works on CentOS, Fedora, Debian, etc. but maybe something is different about your distribution.

**Comment by jonathonf** [comment]
Dropping privileges is the reason. The Arch package doesn't add a `zerotier-one` user, and after adding one manually the error manifests. Interestingly, however, running with `sudo zerotier-one -U` _also_ fails.

I'll do some more digging and ask around to see whether this is an isolated case.

**Comment by adamierymenko** [comment]
We did not change that code at all, so I'm curious to hear what you discover.

**Comment by adamierymenko** [comment]
We made a Manjaro VM and can duplicate this issue, but we're totally stuck. I tried giving all the requisite capabilities directly to /sbin/ip and that still doesn't work. Disabling the redirect-output-to-null code in LinuxEthernetTap I get:

`RTNETLINK answers: Operation not permitted`

... when we attempt to invoke /sbin/ip to add IP addresses.

This works on pretty much every other distribution AFIAK.

**Comment by adamierymenko** [comment]
My guess is that Manjaro is doing something really weird with permissions or other security settings. No idea what it could be.

**Comment by jonathonf** [comment]
I set up a plain Arch VM and have replicated the issue there, so it's likely something with Arch-like distros as opposed to specifically Manjaro.

An Arch user said they have had no issues so I'm not sure what the difference is (I suspect they haven't added the non-privileged user).

**Comment by adamierymenko** [comment]
Does Arch maybe set permissions differently? I know the `nosuid` bit in filesystems can do this but root does not seem to be mounted `nosuid`.

**Comment by adamierymenko** [comment]
Maybe the solution is not to create the special zerotier-one user on Arch and not drop privileges. We're definitely going to leave privilege drop in since the vast majority of Linux users want it, but if it's broken in Arch there's not much we can do. We can add a hack if it's something simple.

**Comment by laduke** [comment]
I had an system running an older kernel, and it still worked with the zerotier-one user. Then it broke when I upgraded. 
Somewhere between 4.14.23-1-lts and 4.14.35-1-lts something happened. Made a thread on the arch bbs. 
https://bbs.archlinux.org/viewtopic.php?pid=1781638#p1781638

**Comment by laduke** [comment]
Narrowed it down to iproute2-4.15 vs iproute2-4.16. With 16 you get the "unable to add ip address" messages.

**Comment by progandy** [comment]
Apparently iproute2 v4.16 drops all capabilities and only allows root/sudo access. It looks like this was done to allow setting capabilities for "ip vrf exec" that won't allow access to the rest of the multicall binary. Probably an example why multicall binaries are bad, since that broke running ip with reduced capabilities.

https://git.kernel.org/pub/scm/network/iproute2/iproute2.git/commit/?id=ba2fc55b99f8363c80ce36681bc1ec97690b66f5

**Comment by jonathonf** [comment]
OK, so a little progress. If I:

```
sudo setcap cap_net_admin,cap_net_raw+eip /usr/bin/zerotier-one
```

then this:

```
sudo zerotier-one -U
```
works as expected. This is progress at least.

```
sudo zerotier
```

still fails to `add ip address`.

**Comment by adamierymenko** [comment]
Okay, I'm re-titling this issue. It will not be blocking for 1.2.8 (a minor tag after 1.2.6 before we do binaries) but will get addressed eventually.

**Comment by progandy** [comment]
> Or is this a regression in iproute2?

@jonathonf You'd have to ask the maintainer [Stephen Hemminger](https://wiki.linuxfoundation.org/networking/iproute2) if this was intended.

**Comment by glimberg** [comment]
The `edge` branch now uses RTNETLINK instead of calling out to iproute2.  It's a bit noisy in the logging department and sometimes says there's an error when everything worked fine, but it appears to be working thus far.  Any testing & bug reports are much appreciated!

**Comment by boothead** [comment]
I think this might be affecting nixos users trying to join networks with managed routes too.

**Comment by boothead** [comment]
Possible same issue? https://github.com/zerotier/ZeroTierOne/issues/726

**Comment by boothead** [comment]
@jonathonf what's the work around you suggest? I can try adding that to the the nixos module in the linked issue to see if it works? Did you mean

```
sudo setcap cap_net_admin,cap_net_raw,cap_net_bind_service+ep /usr/bin/zerotier-one
```

**Comment by boothead** [comment]
I've fixed this on the nixos end here NixOS/nixpkgs#45022

**Comment by liquid-sky** [comment]
Same happened to us with recent ContainerLinux update `stable (2023.5.0)` (kernel `4.19.25-coreos`).

**Comment by liquid-sky** [comment]
Unfortunately, the workarounds provided here do not work on CoreOS, since Zerotier has to run in Docker container 😔

**Comment by liquid-sky** [comment]
Turned out to be related _not_ to recent CoreOS update, but to update of Ubuntu version (to `Xenial`) in our Zerotier Docker image. After downgrading it to `Trusty` it had no issues adding the IP and the route. Meanwhile, we'll pick an alternative OS for our Zerotier image.

**Comment by adamierymenko** [comment]
Done for a while.
