### ISSUE TITLE
Windows 10 IoT Support

### ISSUE THREAD

**Issue by oneguynick** [zerotier/ZeroTierOne#715]
I have attempted to compile the current Windows source-code in Visual Studio, but run into issues with the initial compile due to IoT constraints on app types. Are there any plan to include Windows 10 IoT support?

**Comment by adamierymenko** [comment]
We'd have to work on this. What precisely fails to build or run?

If the UI won't build you could still install it as a service and use the CLI.

**Comment by oneguynick** [comment]
Error MSB8022: Compiling Desktop applications for the ARM/ARM64 platform is not supported. 

The error is related to a short-coming in the current Project File after attempting to target Arm as outlined in this [blog post](https://pete.akeo.ie/2017/05/compiling-desktop-arm-applications-with.html).

It may simply be that the VS Project file needs to be modified. I am more than willing to debug and try some things to work through this.

**Comment by adamierymenko** [comment]
That would be awesome. PRs are welcome!
