### ISSUE TITLE
Windows 10: Unknown Node ID on multiple computers?

### ISSUE THREAD

**Issue by bstin** [zerotier/ZeroTierOne#718]
Hi All. 

I have a strange issue which is reproducible across multiple computers (these computers are all identical hardware, imaged copies, sysprepped of Windows 10 Pro with latest updates applied). 

Upon boot, the ZeroTier One applet shows "unknown" Node ID. In fact clicking on the "Unknown" causes the applet to crash and close. 

If I uninstall ZeroTie and manually delete "C:\ProgramData\ZeroTierOne" directory, then reinstall, then suddenly the NodeID is generated anew and can be seen, until next reboot where cycle this repeats. 

Even though the NodeID is inaccessible, I can still ping other members of the VPN network. (see screenshot). 

Can anyone help in further debugging this issue?

![screen shot 2018-04-18 at 8 46 40 am](https://user-images.githubusercontent.com/10012474/38936587-bbb8de58-42e6-11e8-8b2c-086d87accdcf.png)

**Comment by adamierymenko** [comment]
This sounds like a UI bug. If this is 1.2.4 maybe see if it's fixed in 1.2.6? Binaries coming today.

**Comment by bstin** [comment]
Thanks Adam, I will test new binaries and report back.

**Comment by bstin** [comment]
Just upgraded to 1.2.8 and this issue appears fixed. Please mark as closed.
