### ISSUE TITLE
Two default routes in Windows 10?

### ISSUE THREAD

**Issue by bstin** [zerotier/ZeroTierOne#719]
Hi All. 

I have a network in which both linux and Windows clients are present. 

For some reason, on every boot, the Windows 10 machine gets two default routes (one of which being the local LAN gateway as expected, but the other is 25.255.255.254 which is evidently a ZT address?)

Why is this the case and how do I prevent? I can manually remove the route but it always reappears (maybe this is some sort of Windows thing?)

See pic:

![screen shot 2018-04-19 at 6 41 24 am](https://user-images.githubusercontent.com/10012474/38989997-46df0a5e-439e-11e8-8545-84024090c27b.png)

**Comment by janjaapbos** [comment]
Why do you think 25.255.255.254 is a ZeroTier address?

I cannot see which interfaces on this host are on a zerotier network. 

You can double check that in the windows adapter properties of 172.27.26.20 no gateway is defined.

Also in your zerotier network you can check whether a default route is configured.

Further, on windows check that your zerotier client has not checked allow default for its connected zerotier network.

**Comment by adamierymenko** [comment]
This is normal.

(1) Two bifurcated routes are used to override the default route for normal traffic while allowing ZeroTier's p2p traffic to still use the physical default. This is a common VPN hack to avoid having to reprogram the parts of the routing table that are managed by the OS. In reality this is just one route in that both 'halves' of the twinned route go to the same place.

The 25.255.255.254 address is explained here:

https://github.com/zerotier/ZeroTierOne/blob/master/osdep/WindowsEthernetTap.cpp#L935

WARNING: mild profanity.

**Comment by bstin** [comment]
Thanks for the explanation Adam. 

And yes, I agree with the code comments that windows is insane ;)

This situation is causing a problem for a proprietary piece of software we need to use (a network style service that shuttles info back and forth between servers). Essentially, its causing the software to get confused and misreport information.

We created a workaround to this problem by creating login script in windows to manually remove this one route....all seems to be working fine with this workaround in place...do you see any specific ZeroTier services issues with us proceeding like this?
