### ISSUE TITLE
Support for lower MTU

### ISSUE THREAD

**Issue by Fizzadar** [zerotier/ZeroTierOne#720]
We're trying to run ZeroTier on GCP (to interface with our bare metal elsewhere) but sadly Google's dodgy networking breaks this: https://googlecloudplatform.uservoice.com/forums/302595-compute-engine/suggestions/8518300-support-for-mtu-1460-bytes

Would be nice if it were possible to drop the MTU for poorly implemented networks like this (:

**Comment by adamierymenko** [comment]
It is technically possible but it's not currently exposed in the Central GUI. You can set the network parameter `mtu`. You may have to leave and rejoin the network or restart the service, depending on the platform.

But there is another possible solution too: you can use the iptables TCP "clamp mss" rule in the FORWARD table. This overrides and clamps the TCP MSS field to a given value. I forget the actual argument but it's googlable. So if you have a router between a low-MTU and high-MTU network (such as GCP and ZeroTier) you can clamp the TCP MSS to prevent TCP from using larger frames than those of the smaller network.

**Comment by Fizzadar** [comment]
@adamierymenko interesting, looks like a good (although frustrating, @Google!) solution, thank you!

**Comment by Crest** [comment]
There are other protocols than TCP. What about UDP based protocols like DNS?
