### ISSUE TITLE
Fails to connect on boot

### ISSUE THREAD

**Issue by Aidoboy** [zerotier/ZeroTierOne#728]
I get this from ZeroTier on boot:
```console
$ sudo service zerotier-one status
● zerotier-one.service - ZeroTier One
   Loaded: loaded (/lib/systemd/system/zerotier-one.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2018-04-29 00:19:04 CDT; 5min ago
 Main PID: 801 (zerotier-one)
    Tasks: 3 (limit: 4915)
   CGroup: /system.slice/zerotier-one.service
           └─801 /usr/sbin/zerotier-one

Apr 29 00:19:04 Yamato systemd[1]: Started ZeroTier One.
Apr 29 00:19:04 Yamato zerotier-one[801]: sendto: Network unreachable
```
Running `zerotier-cli` with `sudo` or restarting the service make it work. Anyone know what's up?

**Comment by adamierymenko** [comment]
Does it work if you wait or do you have to restart? A network unreachable error may not be fatal since it keeps trying.

**Comment by Aidoboy** [comment]
It doesn't work until I manually interact with it by restarting or running
it with `sudo` from the command line.

**Comment by adamierymenko** [comment]
Can you tell me a little more about the system? Hardware, OS/distribution, etc.?

**Comment by Aidoboy** [comment]
It's a Dell Optiplex with an i7, Ubuntu 17.10.

**Comment by richarke** [comment]
I have the same issue on Raspbian (Stretch) with zt 1.2.8. Seems to be some kind of systemd race. I added this to the [Service] section of /lib/systemd/system/zerotier-one:

`ExecStartPre=/bin/sleep 10`

It fixes the problem for me. (There's probably a better way...)

**Comment by norn93** [comment]
I tried @richarke's solution:

> `ExecStartPre=/bin/sleep 10`

but it didn't work for me.

I fixed the same issue by adding the sleep in `/etc/rc.local`:

`sleep 60`
`sudo systemctl restart zerotier-one`

Very hacky, but hasn't given me any problems yet. The issue arose because I'm using a weird 3G/4G USB dongle as `eth1`.

**Comment by laduke** [comment]
There were some changes to the systemd units in the last couple releases.
Feel free to re-open if needed.

**Comment by AurevoirXavier** [comment]
Still got this problem in 2020.

Every 5 minutes it'll restart but still `sendto: Network unreachable`.

> It doesn't work until I manually interact with it by restarting or running it with `sudo` from the command line.

I'm on Arch Linux with latest update.

**Comment by laduke** [comment]
Is it version 1.5? https://bugs.archlinux.org/task/68177?project=5&string=zerotier-one

**Comment by AurevoirXavier** [comment]
> Is it version 1.5? https://bugs.archlinux.org/task/68177?project=5&string=zerotier-one

Yes

**Comment by alexacallmebaka** [comment]
Still having this problem in 2020. On Arch Linux, kernel 5.9.14, ZeroTier 1.6.2.
Can anyone help me out? I'm trying to auto-mount some SMB shares over ZT at boot, so this is fatal for my setup.
