### ISSUE TITLE
zerotier-cli info show me tunneled everytime.

### ISSUE THREAD

**Issue by leviacn** [zerotier/ZeroTierOne#729]
Zerotier 1.2.4-4 was installed on my LEDE X64 soft-route. Since the broadband provider will renew and update the public IP address every 48 hours, the zerotier on my router will change from a direct connection to a tunneled connection. Becomes slow and does not change back to direct connection. Checking with the zerotier-cli info command will show that the Online status is TUNNELED.

**Comment by leviacn** [comment]
*/5 * * * * /usr/bin/zerotier-cli info | grep 'ONLINE' || service zerotier restart

**Comment by Fizzadar** [comment]
We had this exact issue with an AWS instance; fixed by setting `echo 1 > /proc/sys/net/ipv4/ip_forward`.

Not sure this actually fixes as we have other boxes with IP forwarding disabled that work, but for this box it certainly made it work!

**Comment by joseph-henry** [comment]
You can force ZT to not use the TCP fallback relay with the following addition to your `local.conf`:

```
{
    "settings":
    { 
        "allowTcpFallbackRelay": false
    }
}
```

Let me know if this is still an issue and this doesn't fix your problem, we can then re-open this ticket.

Thanks.
