### ISSUE TITLE
Support 802.1q VLAN tagging

### ISSUE THREAD

**Issue by adamierymenko** [zerotier/ZeroTierOne#73]
Pretty easy but needs a bit of logic in etherType determination. Note that right now if you allow _all_ etherTypes then 802.1q should work. This is more important when bridging ( issue #68 ) is in, since people are probably going to want to use this for multi-site Ethernet L2 "stretching" and lots of such folks use VLANs.

https://en.wikipedia.org/wiki/IEEE_802.1Q

**Comment by adamierymenko** [comment]
Closing since this is a rules engine thing and will happen there. (Can kind of already be done.)

**Comment by adamierymenko** [comment]
Also not sure why people would run VLANs over a virtual network that is effectively a VLAN... except bridge scenarios in which case you probably want to just pass the VLAN Ethertype and be done with it.

**Comment by benoitc** [comment]
is there any doc about doing this ?
