### ISSUE TITLE
Assigning a publicly accessible node as a guard node.

### ISSUE THREAD

**Issue by lflare** [zerotier/ZeroTierOne#730]
This is completely theoretical but is it possibly to assign a node, that has a public static IP, to act as a guard/proxy node for the other nodes on the same network that do not have a public static IP? Essentially, like a fallback OpenVPN client-to-server-to-client topology, when direct client-to-client is not possible?

**Comment by adamierymenko** [comment]
This is something we'd like to be possible in the future, yes.

**Comment by prutschman** [comment]
I had thought private moons would do this. Is that not the case?

**Comment by KBrownConsulting** [comment]
I though so too...?

**Comment by lflare** [comment]
That is not the case. As of present, private moons act as secondary registries for peer discoveries. They currently do not facilitate the role of traffic transport, and thus, do not help in the above scenario.

**Comment by KBrownConsulting** [comment]
If that's the case then, respectfully, the [2.1.1. Network Topology and Peer Discovery](http://www.zerotier.com/manual.shtml#2_1_1) section of the user manual is very misleading since it specifically mentions moons in the context of relaying traffic... Can someone from zt confirm?

**Comment by glimberg** [comment]
Moons will do UDP-based packet forwarding in cases when it's needed.  They will not do TCP-based forwarding which is a special case that we have servers set up to do.

**Comment by KBrownConsulting** [comment]
Thanks for the reply glimberg. So am I correct to understand that as long as the client nodes are able to send outbound UDP then our moons WILL relay traffic for our clients as opposed to using zt roots? 

The idea being of course that if we setup a moon that has a fast internet connection & open port 9993 on the moon server, then in most circumstances where UDP traffic is allowed, our clients should have a decently fast connection to one another, even if they are relayed. (Taking into consideration the added latency of relaying of course.)

**Comment by sale2000** [comment]
> Moons will do UDP-based packet forwarding in cases when it's needed. They will not do TCP-based forwarding which is a special case that we have servers set up to do.

Hi 
Not being a expert dev, but just a mere-mortal sysadmin here. Does it mean if I set up 'rdp' or vnc:5900 moons will relay? Thanks
