### ISSUE TITLE
can we have a prebuild package for ar71xx openwrt?

### ISSUE THREAD

**Issue by walkerzhang** [zerotier/ZeroTierOne#731]
I saw latest prebuild ipk fo ar71xx is v1.1.4_2.  I tried to follow https://github.com/mwarning/zerotier-openwrt to compile from source for the latest version. But  no matter what target device I choose, the compile result is always mips_24kc not ar711xx. And when I try install that in my openwrt, it says arch not compatible.  Could you tell where might doing it wrong or help build a new version for ar71xx

**Comment by lramage94** [comment]
Did you use the version from the main tree?

https://github.com/openwrt/packages/blob/master/net/zerotier/Makefile

It's the latest version and it should compile on any arch?

**Comment by glimberg** [comment]
We don't build/distribute the LEDE/OpenWRT port of ZeroTier.  If you have issues, please leave one on the mwaring/zerotier-openwrt github project
