### ISSUE TITLE
Android client reliability issues

### ISSUE THREAD

**Issue by mishamosher** [zerotier/ZeroTierOne#735]
With newer versions (1.2.8-1 included) the Android client is extremely unreliable. Ping to other peers never works and can't connect with any IPv4/IPv6 TCP/UDP service that's running in any other peer. Randomly it works for small periods of time (like 2~5 minutes) and then stops working.

The last version that works 'OK-ish' for me is 1.2.4-5.

I've tested this in my Sony Tab Z (Android 5.1.1), Nexus 5X (Android 8.1), LG Leon (Android 5.0.1), Nexus 7 2012 (Android 6) and Xperia E1 (Android 4.4.4), via WiFi and cellular data.

**Comment by glimberg** [comment]
Bugfix release is rolling out

**Comment by mishamosher** [comment]
I've tried the bugfix release (1.2.8-2) and it shows HUGE improvements on all of my devices. It works way too good 👍

Appreciate A LOT the effort!
