### ISSUE TITLE
make-linux.mk cannot detect armv7hl

### ISSUE THREAD

**Issue by chotaire** [zerotier/ZeroTierOne#739]
make-linux.mk cannot detect armv7hl (Raspberry Pi 3 running on Fedora 28):

```
make-linux.mk:211: *** FATAL: architecture could not be determined from gcc -dumpmachine: C_MACH.  Stop.
#  gcc -dumpmachine
armv7hl-redhat-linux-gnueabi
#  uname -a
Linux blah 4.16.6-302.fc28.armv7hl #1 SMP Wed May 2 01:16:39 UTC 2018 armv7l armv7l armv7l GNU/Linux
```

When inspecting make-linux.mk I seem to find a typo aswell, as I see ifeq looking for the same architecture twice:

```
ifeq ($(CC_MACH),armv7l)
        ZT_ARCHITECTURE=3
        override DEFS+=-DZT_NO_TYPE_PUNNING
        ZT_USE_ARM32_NEON_ASM_CRYPTO=1
endif
ifeq ($(CC_MACH),armv7l)
        ZT_ARCHITECTURE=3
        override DEFS+=-DZT_NO_TYPE_PUNNING
        ZT_USE_ARM32_NEON_ASM_SALSA2012=1
endif
```
I am not familiar with the architecture so I decided for SALSA2012 and it compiled fine. Someone please give me a hint if I chose wrong.

**Comment by chotaire** [comment]
While at it, a build for Fedora (and Centos7) on armv7 would be really neat as the time of raspbian dominance is coming to an end.

**Comment by joseph-henry** [comment]
Fixed this in `dev`, will eventually be migrated into `master`, going to close this for now but let us know if this doesn't fix the issues you're experiencing.
