### ISSUE TITLE
iOS : App "turns off" / default route doesnt quite

### ISSUE THREAD

**Issue by darkorigins** [zerotier/ZeroTierOne#742]
Version: 1.2.8-1
iOS: 11.3.1

Moving the on/off toggle from off to on results in a delay of about 5 seconds and it turns itself off again.

Following suggest of zt_travis on community chat ( try going into Settings -> VPN and turning it on from there. Seems something weird with the recent update.)

Using the iOS vpn settings page does allow it to connect and see across the ZT network.

However the default route option seems to break routing. Non-default route network works as expected. Default route enabled network enables you to see the ZT network but no routing to the outside world.

(Default route network checked on desktop ZT client and works as expected)

As far as we know it was all working fine until last day or so

Mark

**Comment by ericse** [comment]
Same thing here: after upgrading 2 IOS devices on version 1.2.8-1, the existing network does not activate anymore. I had to remove, then add again, the network (witch reinstall the VPN profile) to make it work again.
So no big deal, thanks for the team for all your work, ZT is awesome!
Eric

**Comment by glimberg** [comment]
Found the issue and have submitted a fix.  Waiting for our Fruity Overlords to approve and it will begin rolling out.

**Comment by darkorigins** [comment]
Great, as always thanks for the quick turnaround !
Mark
