### ISSUE TITLE
mac OSX client error.

### ISSUE THREAD

**Issue by sbilly** [zerotier/ZeroTierOne#743]
I installed zerotier from the .pkg file from zerotier.com. It report : _The file “authtoken.secret” couldn’t be opened because you don’t have permission to view it. To view or change permissions, select the item in the Finder and choose File > Get Info._

Error message: https://s1.ax1x.com/2018/05/11/C0TanA.png

**Comment by glimberg** [comment]
You need administrative access the first time the UI is run to copy `authtoken.secret` to your local Libraries folder.  Without that, it doesn't have the token needed to authorize communication with the zerotier-one background service.

When you first start the UI, this should pop up:
![image](https://user-images.githubusercontent.com/54439/41001595-3bbc3e1a-68c6-11e8-8e5e-4d2b42cb5b87.png)

If you can't elevate your privileges to perform this, or hit cancel, you'll get an error.

**Comment by sbilly** [comment]
There is no pop up. Please tell me how to fix it .

**Comment by sbilly** [comment]
pop up error message every reboot. but sudo works.

```
sudo /Applications/ZeroTier\ One.app/Contents/MacOS/ZeroTier\ One
```

**Comment by sbilly** [comment]
@joseph-henry Yes, It still pop up error message.
