### ISSUE TITLE
zerotier-one v1.2.8 cannot orbit a MOON

### ISSUE THREAD

**Issue by mkmkwld** [zerotier/ZeroTierOne#744]
After upgrading to v1.2.8, my zt nodes can no longer orbit the MOONs that previously worked.

* Tried  to completely reinstall MOONs and regular nodes, no help.
* For the same MOON, v1.2.4 still works but v1.2.8 failed.
* For v1.2.4, previously `zerotier-cli oribit xxxxx xxxxx` simply worked, but after upgrading the MOON to 1.2.8, I have to manually copy the file xxxxx.moon to `/var/lib/zerotier/moon.d` to make it work.

### Details
`zerotier-cli oribit xxxxx xxxxx` reported OK, but `zerotier-cli listmoons` showed no result, and the MOON's ID is shown as LEAF after a while. The directory `/var/lib/zeroiter/moons.d` is empty. 

| Regular node version/ OS | MOON version| status |
|--------------------|--------------| ---------------------|
| 1.2.8 / ubuntu16.40 | 1.2.8 / ubuntu16.40 | No |
| 1.2.4 / ubuntu16.40 | 1.2.8 / ubuntu16.40 | Yes|

**Comment by laduke** [comment]
fixed in 1.2.10, coming soon. 
thanks!

**Comment by mkmkwld** [comment]
Thanks for the quick update. Looking forward to 1.2.10!

**Comment by aguegu** [comment]
wish it sooner
