### ISSUE TITLE
Anyone Have a Good Way To Diagnose Peer Connectivity Issues?

### ISSUE THREAD

**Issue by WilliamMiceli** [zerotier/ZeroTierOne#747]
My devices:
- Android Phone (On cellular network) with version 1.2.8-2
- Windows Laptop (On private network) with version 1.2.8
- FreeNAS Server (On same private network) with version 1.2.4

My private network is an Ubiquiti Networks 192.168.1.1/24
My ZeroTier network is a 10.0.0.0/16.

All of my devices previously worked fine when I was in my dorm room on the university, but coming home for the summer, and not changing anything that I can remember, setting up my private network underneath another private network 10.255.255.1/24. Now, none of my devices can contact each other. I can't get Remote Desktop working, CIFS/SMB, SSH, HTTPS, really anything working.
All devices can connect to ZeroTier Central and show online. My android phone and windows laptop show their public IP address correctly, however the FreeNAS server does not.

I'd consider myself "familiar" with networking, but no expert, so I don't doubt that this is some kind of user issue that I can't seem to figure out.

Any help is greatly appreciated!
Thank you!

**Comment by WilliamMiceli** [comment]
And like magic, after about a week and not messing with anything, it all works again, actually even quicker than before.

**Comment by michaelansel** [comment]
I would still love to hear about good solutions for debugging. I know 1.2.8 added some new remote tracing capabilities, but I haven't seen much in the way of documentation around that (and therefore still have no clue how to debug p2p issues).
