### ISSUE TITLE
zerotier: use own moon if no peer2peer connection can be established

### ISSUE THREAD

**Issue by plieningerweb** [zerotier/ZeroTierOne#748]
Issue: 
* In our setup, no peer2peer connection can be established, but we can not change that fact.
* The roots to relay data (as fallback if no peer2peer) from zerotier are quite slow when copying data (<1 MByte/sec). It's awesome they are there and for free, so big thanks!
* So we added our own moon using a VPS with public ip and added the moon to the clients using `sudo zerotier-cli orbit ...` and it shows up as moon in `listpeers`

Problem:
* even after a restart, copying is still slow
* no traffic routed over moon (as seen in `nethogs`)

How can I force the peers to use our own faster moon if no p2p connection is possible?

**Comment by plieningerweb** [comment]
1.2.4

**Comment by TuanWorkMail** [comment]
Yup it was not working in 1.2.8, I updated to 1.2.10 and it is working now.
For Ubuntu 18.4 you can download here: https://download.zerotier.com/RELEASES/1.2.10/dist/debian/bionic/pool/main/z/zerotier-one/
