### ISSUE TITLE
Requesting / from control API causes ZeroTier to crash

### ISSUE THREAD

**Issue by michaelansel** [zerotier/ZeroTierOne#751]
v1.2.8 on Mac OS X High Sierra and OpenWrt/LEDE latest snapshot

Expected behavior:
```$ curl -s -X GET --header "X-ZT1-Auth: ${authtoken}" http://127.0.0.1:9993/
{}
```
Response is undefined in the spec, so just "don't crash". Maybe the `/status` data or a 404?

Actual behavior:
```
$ curl -s -X GET --header "X-ZT1-Auth: ${authtoken}" http://127.0.0.1:9993/ -vvv
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 9993 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:9993
> User-Agent: curl/7.54.0
> Accept: */*
> X-ZT1-Auth: REDACTED
>
* Empty reply from server
* Connection #0 to host 127.0.0.1 left intact
```
At this point, the running process has crashed, and depends on an external system to restart it.

This looks like a missed case in `handleControlPlaneHttpRequest`:

https://github.com/zerotier/ZeroTierOne/blob/d32a26f780ce7222aa89af64abecf7044ce62327/service/OneService.cpp#L1053 -- check if `ps.size() > 0`, if not, fall though

https://github.com/zerotier/ZeroTierOne/blob/d32a26f780ce7222aa89af64abecf7044ce62327/service/OneService.cpp#L1130 -- access `ps[0]`, even though we have proven above that `ps.size() == 0`

**Comment by michaelansel** [comment]
Please advise on the desired behavior, and I'll put together a PR.

**Comment by laduke** [comment]
Fixed!
https://github.com/zerotier/ZeroTierOne/commit/5b114791e52c046be3b5db254566928ccc6c7a23#diff-6bd361de78e54e7db32d9b4e502a88b0
