### ISSUE TITLE
iphone 6 issues after 1.2.4 -> 1.2.9 upgrade

### ISSUE THREAD

**Issue by gsfjohnson** [zerotier/ZeroTierOne#752]
Several issues exist after upgrading ZeroTier iOS app from 1.2.4 -> 1.2.8, on iphone 6 (MG4N2LL/A, 11.3.1).  (1) default/managed routes no longer work.  (2) specifying dns prevents VPN activation.  (3) specifying dns during setup is difficult from an ui/ux standpoint. 

When default route is enabled, the safari app is unable to load any websites.  When default route is disabled safari works but only for public destinations - no managed routes configured via my.zerotier.com are accessible.  In both situations, the VPN icon appears next to the wifi strength indicator after enabling the network via zerotier.  Since both default and managed routes work fine from MacOS system running 1.2.8 build 0 - it seems to be either my iphone or the zt app changes since 1.2.4.

If a custom dns server of 8.8.8.8 (ipv4) is specified, the VPN icon does not appear next to the wifi strength indicator.    Access of myip.dnsomatic.com reveals actual ip-address, not ip-address of vultr vm where packets should be popping out. 

Specifying a custom dns server during network setup on the iphone 6 is difficult/not-intuitive.  The page will not scroll and therefore "Add network" remains hidden by the keyboard popup, when "Use Custom DNS servers" is activated and the cursor is in one of the text fields.  The only way around this is to deactivate/reactivate Use custom dns toggle - which takes the cursor out of the text field deactivating the keyboard.   Perhaps this is not an issue with larger screens of the more recent iphones.

**Comment by gsfjohnson** [comment]
@laduke Apologies for not including that detail - that is the version I am currently using.  However it's been broken since the updated to 1.2.8.  After noticing #745 and #742 - I waited for and updated to 1.2.9 in order to see if that fixed the issue.  It did not.

**Comment by gsfjohnson** [comment]
@laduke Currently using 1.2.9.

It appears the problem specifically is with dns packets, when they are sent through zt via a zt route.  In all situations, websites are accessible by ip-address.

**Comment by glimberg** [comment]
You can tap anywhere on the screen that's not an input field to hide the keyboard.  Next release should have some improvements on that UI so that you can scroll when the keyboard is up, though.

Also, lots of people complained about the default of using google public DNS so that was removed and the option is given to enter your own.  You have to specify DNS servers when enabling default route, because you likely won't be able to access the DNS servers on the local LAN anymore

**Comment by cabsandy** [comment]
Bumping this up-on a iPhone5SE. Does the manual setting of DNS servers work for people?-no matter what I try, I cannot use the phone as a default route to my Digital Ocean server.MacBook and Android phone from same wifi AP work great-only one that doesn't is the 5SE. Thanks!

**Comment by rokka-n** [comment]
1.2.12-1 version has the same issue, iphone6 as well
VPN icon is not shown with default route enabled, the actual IP address is revealed with online checkers. I've used 1.1.1.1 as custom DNS but it doesn't seem to matter.

Desktop client working fine with the same network, no additional tweaking.

**Comment by ShaunDwyer** [comment]
I can confirm behaviour described above. Tested with 2 iPhones( 6+ and 7+) and an ipad pro 9.7", all running latest IOS that we are observing the same problem described above.

When you set a custom DNS server address, the [VPN] icon does not appear and no traffic will pass.

I was TCPdumping on another working node on my network and saw no traffic. zerotier central shows an assigned IP to the client.

When I removed the custom DNS configuration on the IOS device config, the [VPN] icon appeared, and traffic passed. I was also able to ping the IOS devices from another host on my zt network.

Keen to have this problem fixed - I need to be able to resolve hosts with DNS on my network via ZT for IOS clients.

Happy to help with debugging for devs if needed.

**Comment by michaelfgeiger** [comment]
Regarding (3): Editing DNS settings after setup would be an UI improvement. Feature request for Android: #790

**Comment by gouldjames** [comment]
I have found a partial work around. I filled **both** IPs for the DNS server with the address of my DNS. iOS successfully connected to the ZeroTier VPN, however the DNS server was unreachable!

I looked at the VPN configuration in the **Settings** app and noticed that there is no entry for DNS (iPhone Xs / iOS 12.2 / ZeroTier One 1.2.12-1)

![IMG_1131](https://user-images.githubusercontent.com/49250355/55504971-ef5d9600-5649-11e9-9e9b-6e04573eb4ef.jpeg)

**Comment by ChaoshunZuo** [comment]
I just confirmed this on iphone 6 and ipad mini. In full tunl mod, I am able to open website by ip but not by domain name. Looks like the problem is related with DNS.

**Comment by rad182** [comment]
same here custom DNS isn't working :(

**Comment by rad182** [comment]
@adamierymenko not sure why is this closed? is a new iOS update coming?

**Comment by laduke** [comment]
@rad182 there is; not sure exactly when yet

in the current version, if you fill in all four dns fields, you may have better luck

**Comment by mniuop** [comment]
Still no news about this? I still cannot override iOS DNS by using the latest ZeroTier One 1.4.4-1 on iOS 13.3.
