### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Quemaster** [zerotier/ZeroTierOne#756]
On windows 10, when i try to run the app, it crashes and says "Zerotier has stopped working". I tried deleting „zerotier" folder in appdata/local, and reinstalling the program, but it ain't working. It worked perfectly in the past, i haven't been using it for about a month and then this happend. I don't even know where can i find any log.

**Comment by Quemaster** [comment]
when i try to access zerotier through the cmd, it says that it's unable to start the service.

**Comment by Quemaster** [comment]
when i use zerotier-one_x64.exe -C, the cmd window freezes.

**Comment by glimberg** [comment]
There are 2 parts to ZeroTier.  There's the background service `zerotier-one_x64.exe`, and there the GUI `ZeroTier One.exe`.

If you're running `zerotier-one_x64.exe -C` it's not "freezing up" the cmd window.  It's just running.

It sounds like you got a crash in the GUI portion of the app, but that's not something that I'm able to reproduce.

**Comment by Quemaster** [comment]
if that's right, then i should be able to at least list the networks from the terminal. I can't do that, it just says "unable to start service"

**Comment by glimberg** [comment]
you use `zerotier-cli.bat` to interact with the service.  Not call `zerotier-one_x64.exe` directly

**Comment by Quemaster** [comment]
Thanks men, i think it works.
