### ISSUE TITLE
Maintain old versions in debian repo

### ISSUE THREAD

**Issue by michaelansel** [zerotier/ZeroTierOne#757]
I've noticed a considerable amount of instability in 1.2.8 and would like to downgrade back to 1.2.4 on my most important systems. However, it appears that all old versions were purged from [the repo](http://download.zerotier.com/debian/stretch/pool/main/z/zerotier-one/) as soon as 1.2.8 was released. Please maintain at least one historical version to permit downgrades.

**Comment by michaelansel** [comment]
Aside from my other open issues (#746 #751), I've seen it just freeze up several times on both ARM and x86 hosts (strace shows it just stalled on futexes), but without enough information yet to file a useful bug report. I'm continuing to investigate, but would love to stabilize the more critical components of my network in the interim.

**Comment by michaelansel** [comment]
Not sure if this is new, or if I just missed it, but manual downgrades can be done by pulling the appropriate package from https://download.zerotier.com/RELEASES

That is sufficient for my purposes, though a single repo with all the versions would be more convenient.

**Comment by frankang** [comment]
Thanks, I didn't know that older version page before.  Zerotier should add it to the download page. Puzzled by the 1.2.8 orbit bug for a while...
