### ISSUE TITLE
Persistent config after reboot

### ISSUE THREAD

**Issue by Stabington** [zerotier/ZeroTierOne#761]
I've been testing how the zerotier client works in various conditions in our lab.

I hooked up 2 clients on the same LAN, connected to the controller to get the config, then removed the gateway. They could still communicate, so I tried changing the IP on one of the clients. It took a few seconds to discover again, but it still worked!
However, when I rebooted one of the clients, it lost its config. It doesn't work until it has connected to the controller at least once.

Can I make the config persistent, even if the client is offline?

Say, if a gateway is only available at certain times during the day. I'd want the LAN to still function over the VPN.

**Comment by laduke** [comment]
Hey @Stabington the nodes need to check in with the controller for cryptography stuff once in a while. 

You _can_ run a controller inside your LAN. See https://github.com/zerotier/ZeroTierOne/tree/master/controller for DIY.

my.zerotier.com pro to self-host Central

**Comment by Stabington** [comment]
Aight, guess it doesn't matter since it's on a LAN anyway.
Would just make my life easier ^^
