### ISSUE TITLE
Traffic stops after a couple of minutes

### ISSUE THREAD

**Issue by volfco** [zerotier/ZeroTierOne#763]
Here's my setup.

I got a VPS- **172.31.0.2**. This is out on the internet somewhere. I have another VM- **172.31.0.1**. This VM is on a local network with the address of **172.29.3.253**. "allowManaged": 0 is set to prevent routing issues and `sysctl -w net.ipv4.ip_forward=1` is set to allow routing. Here is a poor diagram of the design.

![image](https://user-images.githubusercontent.com/433045/40463356-6f90583e-5eda-11e8-8b4e-4e84779bb8a0.png)

My router is configured with a static route pointing to 172.31.0.0/24 via 172.29.3.253. ZeroTier is configured with the following route: 172.29.3.0/24 via 172.31.0.1. From my VPS (172.31.0.2), I can ping 172.29.3.2 for a minute or two before traffic stops. I can ping only 172.29.3.253 and 172.29.3.254 (and nothing else in 172.29.3.0/24) from 172.31.0.2 after traffic stops flowing to 172.29.3.2. From 172.29.3.2, I can ping 172.3.0.2 even after this happens. 

If I reboot 172.29.3.253/172.31.0.1, 172.31.0.2 -> 172.29.3.2 works for a brief period and then stops. Restarting zerotier does nothing. I have no idea what's happening here. Both hosts are Fedora 28 (this also happened on CentOS 7)

**Comment by volfco** [comment]
Well. I'm going to close this as I was running into a VirtIO bug as described [Here](https://stackoverflow.com/questions/26539130/linux-ip-forwarding-doesnt-work) and [Here](https://forum.proxmox.com/threads/network-card-virtio-bug.35029/).

**Comment by janjaapbos** [comment]
Thanks for the feedback! This is a nasty one.
