### ISSUE TITLE
Linux (possibly others) ZT does not add route to peers

### ISSUE THREAD

**Issue by dragon2611** [zerotier/ZeroTierOne#765]
Linux Mint 18.03 

It looks like if Zerotier is configured to take over the default route it adds routes for 0.0.0.0/1 and 128.0.0.0/1 however what it doesn't seem to do is add any more specific routes to the peer hosting the VPN gateway so of course networking dies because ZT is unable to reach any of the peers needed to actually route traffic via the zerotier network.

At the time Central was showing the IP of the peer as unknown so that may be why.
Currently central is only showing the V6 IP for that peer.

**Comment by dragon2611** [comment]
On Windows there appears to be internet access when the default route is via zerotier but it's not optimal, adding a route to public IP of the LEAF that's the default gateway for the zerotier network via the actual gateway on the real network allows a direct connection and has vastly improved speed and latency.

**Comment by dragon2611** [comment]
I think you are misunderstanding, say my network is 192.168.54.0/24 and my zerotier node running as the gateway hasreal external address of 1.2.3.4 and a zerotier address of 192.168.54.1.

Zerotier correctly adds a managed route for either 0.0.0.0/0 or 0.0.0.0/1 and 128.0.0.0/1 via 192.168.54.1.

However what it does not appear to do is add a route to 1.2.3.4 via the real network's gateway meaning I can't establish a direct connection to 1.2.3.4 to actually tunnel the other traffic unless I manually add a route in the route table of the machine running the client.

Most VPN services when they connect will add a /32 route for the VPN concentrator so that you don't try to route the traffic to the VPN endpoint down the VPN itself if there is a managed route for 0.0.0.0/0 Zerotier needs to ideally do this for the real address of the machine hosting the gateway.

**Comment by ericse** [comment]
Thanks for the explanation. I have the same setup as you, and it run fine without a zerotier route to the public IP of the gateway. 

In your network, it's the job of zerotier to route packets to 192.168.54.1, and it's the job of the gateway to route packets from 192.168.54.1 to 1.2.3.4. The rest of the network should not be aware of 1.2.3.4 (which could even be a dynamic IP, a load-balancing/fail-over group of IP or whatever).

**Comment by dragon2611** [comment]
you have to have a route (either directly or indirectly) outside of zerotier to the device acting as the gateway on the zerotier network.

Without such a route zerotier cannot form a tunnel.  It's actually worse on Linux as it looks like zerotier adds a default route via the 192.168.54.1 but doesn't add a route for any Leafs or even the Planets with the end result of the machine being unable to access anything other than it's local LAN.

**Comment by ericse** [comment]
Well I don't want to argue with you, I was just saying than I have a vpn-like setup with a gateway to Internet (as I understood you wanted to do), and it's working fine with zerotier 1.2.8.

**Comment by glimberg** [comment]
Try `sysctl -w net.ipv4.conf.all.rp_filter=2`

Step 3a from [here](https://support.zerotier.com/knowledgebase.php?entry=show&search-for=&article=ZWFhNWMyMTZjODY1ODcwNmFhZmJjYmRhN2I5MjRhOGQ_)

**Comment by dragon2611** [comment]
Looks like changing the reverse path filter did indeed fix the problem, so the solution is either add a route towards the peer address or easier option change RP filter ;-)

Is it maybe something you could look at setting automatically if joining a network where the default route is set?
