### ISSUE TITLE
Error response from daemon: Container xx is not running

### ISSUE THREAD

**Issue by turingking** [zerotier/ZeroTierOne#766]
I have to use docker to run ZT，But it can't work。
`
➜  ~ sudo docker exec zerotier-one /zerotier-cli info
Error response from daemon: Container 5e9091fcef83ab934c62a624d4d7bd8adc32a01d8895dd5d14d449f19a3350e8 is not running
`

**Comment by adamierymenko** [comment]
Does `/dev/net/tun` exist in the container?

**Comment by turing-king** [comment]
```shell
➜  ~ ls /dev/net/
tun
