### ISSUE TITLE
1.2.8-2 android client offline

### ISSUE THREAD

**Issue by marktheis** [zerotier/ZeroTierOne#767]
Android version: 8.1.0
OS: LineageOS 15.1
zerotier one: 1.2.8-2

Zerotier says it's offline in the bottom bar.

I've tried everything from this issue: https://github.com/zerotier/ZeroTierOne/issues/446,  but nothing seems to work.

There is no connect button at the bottom bar. I assume that's because it's offline.
the "Add Network" button is greyed out when I try to add a network.

**Comment by janjaapbos** [comment]
Did you try force restart of the client? (This option is visible once you hold the app icon for several seconds.

**Comment by marktheis** [comment]
Yes.

tried to: force restart, clear cache, uninstall and reinstall.

**Comment by marktheis** [comment]
So... I may or may not have miscopied the network ID, and missed the last character in the network ID...

Anyway, thanks for the help! I should double check my settings more.

**Comment by thestupendous** [comment]
I'm still having this issue on my Android 11. Tried with mobile internet and Wifi, restarting, reinstalling, didn't work.
