### ISSUE TITLE
More than 2 moons

### ISSUE THREAD

**Issue by d0wnblog** [zerotier/ZeroTierOne#775]
I think it would help for redundancy if there are more than only two moons are possible. I think if one moon is failling or not usable why doesn't another moon move to the failed moon position?

**Comment by janjaapbos** [comment]
This is something you can do from a system management / deployment perspective. You can deploy multiple moons and also move zerotier ID's around, to do high availability scenario's.

**Comment by dch** [comment]
is anycast for moons a possibility? i.e. more than 2 moons but made available via only 2 routed IP addresses via BGP.

**Comment by adamierymenko** [comment]
Closing since moons are going to die.
