### ISSUE TITLE
malformed json in member API

### ISSUE THREAD

**Issue by mvivaldi** [zerotier/ZeroTierOne#778]
I have a problem with a simple call api:
`
curl http://localhost:9993/controller/network/853a0a9c5b42e97f/member?auth=myauthtoken
{""327d2ecdf9":1}
`
the json is malformed because there are 2 " in the answer.
I have the same problem on an ubuntu 18 64bit and on a raspberry pi 3 
zerotier-one 1.2.8

**Comment by laduke** [comment]
happens on 1.2.10 also
