### ISSUE TITLE
Fails to install on Windows 2012 r2 Server ( virtual interface)

### ISSUE THREAD

**Issue by magadan** [zerotier/ZeroTierOne#780]
Hi,

ZeroTier is not working in my Windows 2012 r2 Server, the interface (port) is not created after the installer.

How to fix ?

thank you.

**Comment by adamierymenko** [comment]
Did you do the install via Remote Desktop? There are known Windows issues around this. I believe it can be worked around by using MSIEXEC silent install from the command line.

**Comment by JuniorGandara** [comment]
> Hi,
> 
> ZeroTier is not working in my Windows 2012 r2 Server, the interface (port) is not created after the installer.
> 
> How to fix ?
> 
> thank you.

There is a Loop in the Windows Installer Coordinator on Terminal Server, you have to enable "Turn off Windows Installer RDS Compatibility" in the local policy goups.

**Comment by wanjochan** [comment]
in case the later ones not knowing, let me take some notes here:

```
regedit.exe and change

HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows NT\Terminal Services\TSAppSrv\TSMSI\Enable 0

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\TSAppSrv\TSMSI\Enable 0

msiexec /quite /i zerotier.msi
```

hope it save the day

**Comment by raimundo-infraestrutura** [comment]
Irei fazer obrigado
