### ISSUE TITLE
First run bug on Raspberry Pi OctoPrint / OctoPi

### ISSUE THREAD

**Issue by jeffstreet** [zerotier/ZeroTierOne#782]
Trying to start zerotier-one for the first time doesn't work from the home directory. It does work from if  the command is run from `var/lib/zerotier-one`.

Fail:
```
cd ~
sudo zerotier-one -d

```
Success:

```
cd /var/lib/zerotier-one
sudo zerotier-one -d

```
When zerotier-one is configured to run automatically on boot it seems to start up okay. 

OctoPrint version: 1.3.8
OctoPi version: 0.15.1
Pi Hardware: 3B

More detail of issue and workaround here: https://discourse.octoprint.org/t/zerotier-one-on-octopi/2154/7

**Comment by laduke** [comment]
Hello. zerotier-one takes a home directory argument. When you cd to /var/lib/zerotier-one, it uses that. That's were the systemd service will run it. 

`cd ~`
`zerotier-one hello` 

should create a hello directory with a new identity in it.  (not sure why running it in home doesn't seem to work)

zerotier-cli has a home directory switch too. That's where it pulls authtoken.secret from. It defaults to /var/lib/zerotier-one

It's intended most people would use the systemd service. Is there a reason you can't on octoprint?

**Comment by laduke** [comment]
I think what's happening is zerotier is already running (via systemd) in /var/lib/zerotier-one and then doing `zerotier-one` with no args is trying to start another instance with that home directory. 

Is there a use-case for running multiple zerotier instances with the same identity? If not, maybe this should be an error(?). Right now it acts like it started normally.

**Comment by joseph-henry** [comment]
Looks like this issue was resolved (per the discussion in the OctoPi thread). Going to close this ticket.

**Comment by laduke** [comment]
I thought maybe it should bail out if if you try to start zerotier and zerotier-one.pid exists

**Comment by joseph-henry** [comment]
If we do that I'm thinking there may be situations where the process might be killed prematurely leaving behind the pidfile. Then unless that file was manually deleted it would prevent ZT from starting up in that location again. As inconvenient as it sounds I think leaving it alone is the best option. Unless we added some sort of `-force` option to starting ZT to overwrite pidfiles.

@adamierymenko thoughts?
