### ISSUE TITLE
"zerotier-cli listnetworks" displays network name as is (no double quotes)

### ISSUE THREAD

**Issue by bruno-imasdetres** [zerotier/ZeroTierOne#783]
If the network name have more than one word, the output from zerotier-cli listnetworks cannot be splitted in an easy way (e.g. processing output using bash scripting) beacuse the number of columns differ from first row:

`200 listnetworks <nwid> <name> <mac> <status> <type> <dev> <ZT assigned ips>`
`200 listnetworks 1234567890abcdef my full net name 00:11:22:33:44:55 OK PRIVATE ztd34db33f 10.11.12.13/16`

First row consists of 9 columns but the second row counts up to 12! I think it's much better to enclose network name in double quotes:

`200 listnetworks 1234567890abcdef "my full net name" 00:11:22:33:44:55 OK PRIVATE ztd34db33f 10.11.12.13/16`

This way is much easier to split/parse it.

**Comment by janjaapbos** [comment]
Then you also have to think about escaping the " in a name. It is already possible to get json output with the -j  switch. You can combine that with the jq json parser.

**Comment by janjaapbos** [comment]
E.g. zerotier-cli listnetworks -j | jq -r  '.[] | .name'

**Comment by bruno-imasdetres** [comment]
Thanks for the prompt response! This solves the issue in a better way than parsing the output that may change in future versions.
