### ISSUE TITLE
cmake exported project?

### ISSUE THREAD

**Issue by gdamore** [zerotier/ZeroTierOne#784]
For projects like NNG that want to tell folks how to integrate with ZT, its kind of awkward.   On make platforms they can just run `make core`, but on others they can use `cmake`.

What would be super cool is if we had an exportable cmake project, and even better a solution where `libzerotiercore.a` (or a dynamic version ala dylib, dll, etc.) setup (along with exported library dependencies if libzerotiercore has any, which I think it might.

This and your the necessary header files could be part of a "standard" installation too.

What I'm after is scaffolding to make using this stuff in 3rd party projects easier and more standard.

I can help with that if you like -- just let me know.

**Comment by adamierymenko** [comment]
Closing since we may port to cmake eventually but right now it's not a priority.
