### ISSUE TITLE
Managed Routes disappear on OPNsense

### ISSUE THREAD

**Issue by darkain** [zerotier/ZeroTierOne#785]
On at least one of my OPNsense boxes, all of the managed routes for one particular ZT network will disappear (managed routes for the second of two ZT networks remains)

In the web UI under VPN > Zerotier > Overview > Networks > [network name], the routes are properly listed.

Under "netstat -r" on the console, the routes are there when I first connect to my ZT network, however they're gone about 24-48 hours later. If I push a new route from the my.zt web interface, the existing routes will repopulate within "netstat -r"

For the time being just to maintain stability, I've had to manually configure these as static routes within OPNsense.

Are there any ways to debug what is going on with the Managed Routes using some sort of logging or checking statuses via zerotier-cli ?

**Comment by adamierymenko** [comment]
Could this be related to #786 ?

**Comment by darkain** [comment]
Its possibly related, but the issue I have is that the routes are never re-added again. The routes just disappear and never come back (waited multiple hours).

**Comment by laduke** [comment]
any idea if this still happens @darkain 
lots of changes since june

**Comment by darkain** [comment]
I'm not using managed routes anymore in my environment, they caused far too many issues (besides just this issue). I switched to using OSPF instead, because I needed multiple route-points per LAN segment, not just one. 

Also, I just checked, the FreeBSD package is still 1.2.12. Has there been any public releases since June?

**Comment by darkain** [comment]
I'm not sure why this issue was closed? Other people have mentioned this issue in other places and referenced this bug. I have no idea if it has been resolved or not, since there has not been an official new built of ZT in what... an entire year now?

**Comment by RobinBeismann** [comment]
Same issue here, I instead switched to OSPF over the Zerotier interface now, but I still need to add the routes within the Zerotier Console as managed routes..

**Comment by darkain** [comment]
FYI people are still experiencing this bug: https://forum.opnsense.org/index.php?topic=17254.0

This issue should be re-opened.
