### ISSUE TITLE
ZT interface routes flapping

### ISSUE THREAD

**Issue by yesbox** [zerotier/ZeroTierOne#786]
The ZT client keeps removing adding managed routes pointing to the interface ("LAN" in the controller UI).
Routes pointing to addresses does not appear to be affected.
This disrupts traffic which causes some applications to fail.

The following keeps executing at 2-30 second intervals:
```
[pid  2049] execve("/sbin/ip", ["/sbin/ip", "-4", "route", "del", "10.0.0.0/24", "dev", "zt0"], [/* 3 vars */]) = 0
[pid  2050] execve("/sbin/ip", ["/sbin/ip", "-4", "route", "replace", "10.0.0.0/24", "dev", "zt0"], [/* 3 vars */]) = 0
```

In addition to this issue, I don't see the point of "managing" the route to the interface from user space in the first place. When an interface is configured with an IP and the subnet mask, every OS will already set up a route to that subnet via the interface. Anything else would be broken and there is no extra step required.

Changing ZT_LINUX_IP_COMMAND* to something that doesn't exist confirms the above; this fixes basic functionality at the cost of breaking additional managed routes.

I've checked only on two very different Linux machines, no other operating systems.

**Comment by glimberg** [comment]
Just fixed this issue here:

https://github.com/zerotier/ZeroTierOne/commit/4dd093efc92055174ebb7388408db1ff9148d8b6

and here:

https://github.com/zerotier/ZeroTierOne/commit/62210e57f1c81aec43b714b22313f8c3a0569e2c

Will be in the next bugfix release
