### ISSUE TITLE
zerotier runs on ios9.3.1  cannot be turned on,and the numbers on the foot is   just "0000000000"

### ISSUE THREAD

**Issue by longalong** [zerotier/ZeroTierOne#791]

**Comment by longalong** [comment]
after click connect,it disconnect immediately

**Comment by glimberg** [comment]
Well both of your devices are capable of being updated to the latest iOS.  I'd recommend doing that.

We don't have any iOS devices running an iOS version that old and Apple makes it impossible to downgrade to older versions.
