### ISSUE TITLE
tap interfaces failed to be created on FreeBSD 12.0-CURRENT

### ISSUE THREAD

**Issue by dch** [zerotier/ZeroTierOne#792]
from irc discussion, sometime during FreeBSD commits ~ 1 month ago r334932 and  r335190, zerotier 1.2.10 is no longer able to correctly create tap interfaces. the zt side hasn't changed, and FreeBSD is definitely still able to create taps. BTW t looks a bit like zt should just create the required ifname directly with the correct name  rather than attempt a rename shortly afterwards, but I might be reading the zt code wrong.

I've tried dropping some `DEBUG_INFO(...)` calls in but get a compilation failure. tips welcomed on what I should do.

### code

- [zt BSD code](https://github.com/zerotier/ZeroTierOne/blob/1.2.10/osdep/BSDEthernetTap.cpp)
- BTW sleeping here seems risky https://github.com/zerotier/ZeroTierOne/blob/1.2.10/osdep/BSDEthernetTap.cpp#L408-L410
- [create tap](https://github.com/zerotier/ZeroTierOne/blob/1.2.10/osdep/BSDEthernetTap.cpp#L115-L150)

### docs

oldest supported FreeBSD version is 10.4
- [man ifconfig](https://www.freebsd.org/cgi/man.cgi?query=ifconfig&manpath=FreeBSD+10.4-RELEASE) &  [man if_tap](https://www.freebsd.org/cgi/man.cgi?query=if_tap)

### diffs

list of "recent" changes to if_tap and ifconfig.c look innocuous  and more to the point are *before* the last working version:
- [ifconfig.c](https://svnweb.freebsd.org/base/head/sbin/ifconfig/ifconfig.c?view=log) & [ifconfig](https://svnweb.freebsd.org/base/head/sbin/ifconfig/?view=log) in general &  [if_tap](https://svnweb.freebsd.org/base/head/sys/net/if_tap.c)

**Comment by dch** [comment]
my debug branch here https://github.com/zerotier/ZeroTierOne/compare/dev...skunkwerks:dev still working out how to get actual debug output to the console during https://github.com/zerotier/ZeroTierOne/blob/1.2.10/osdep/BSDEthernetTap.cpp#L115-L150

**Comment by dch** [comment]
as far as I can tell, code in `BSDEthernetTap.cpp` isn't getting called anymore. I can use `DEBUG_INFO("made it");` in `node/Trace.cpp` or `one.cpp` and see output, but in the BSD tap code, nothing is ever seen.

**Comment by adamierymenko** [comment]
We tested on 11, but not 12. Will have to make a 12 VM.

**Comment by dch** [comment]
I built the binary using my current /dev/ branch, and copied it to a system running r334932:

```
./zerotier-one 
INFO [0]:           one.cpp: 1310:               threadMain: new instance
INFO [0]:    OneService.cpp:  538:                      run: started
INFO [0]:    OneService.cpp:  667:                      run: search for ports
INFO [0]:    OneService.cpp:  691:                      run: bind control ports
INFO [0]:    OneService.cpp:  716:                      run: bind 2ndary port
INFO [0]:    OneService.cpp: 1941:nodeVirtualNetworkConfigFunction: taps on
INFO [0]: BSDEthernetTap.cpp:   98:           BSDEthernetTap: BSDTap
INFO [0]: BSDEthernetTap.cpp:  120:           BSDEthernetTap: loop over dev
zt1flo98dm17np8
INFO [0]: BSDEthernetTap.cpp:  169:           BSDEthernetTap: shouldnt get here without the previous ones
INFO [0]:    OneService.cpp:  792:                      run: main loop
requesting configuration for network 17d709436c13df28
learned new path 159.203.2.154/9993 to 8841408a2e (packet 1faadebb6a078643 local socket 34370868496 network 0000000000000000)
explicit redirect from 8841408a2e to path 46.101.160.249/9993
```

& works perfectly. On the newer system, r335190 that whole BSDTap stuff is skipped.

These boxes are using exactly the same debug binaries, built on r335190, and moved to the older box. I'm upgrading it tonight and will see if the same error returns.

**Comment by adamierymenko** [comment]
Take a look at the `#ifdef` blocks near the top of OneService.cpp. It uses OS defines to pick which tap to use. Could these defines be missing on FreeBSD 12?

**Comment by dch** [comment]
defines are definitely present. BTW I can't reproduce this anymore in latest FreeBSD releases including 12.0-ALPHA1-5 so we're all good now against latest released zerotier.
