### ISSUE TITLE
Very odd issues on Windows 10 clients

### ISSUE THREAD

**Issue by kevsterd** [zerotier/ZeroTierOne#795]
Anyone getting very odd issues using ZT on Windows 10 1803 or later builds ?
 
I have removed/added ZT a number of times on a couple of PC's and the device is registered/authorised the machines IP stack ends up a mess.

- For a start, the virtual NIC that gets added (initially called Ethernet then renamed to Zerotier [xxxx]) doesent appear correctly to the CLI.
- They never get the IP address assigned from Zerotier.   I have tried adding the IP/Mask etc to the NIC and this seems to work however.....
- Even when this is in place, the traffic that should of gone via the tunnel/ZT nic was being sent out of the standard LAN nic.

At the moment - for me - the Windows client is a non starter.    Not doing so well as had similar results with my Synology !

**Comment by glimberg** [comment]
> doesent appear correctly to the CLI.
What do you mean by this?

> They never get the IP address assigned from Zerotier
Is the machine authorized on https://my.zerotier.central?  Is "Allow Managed" set on the network?

**Comment by kevsterd** [comment]
Yeh sorry.

If you open powershell or a cmd session an ipconfig /all the nic is still known but the NIC name is shown as 

> Ethernet adapter Ethernet

Yes managed is set.   The GUI has the address allocated from my.zerotier.com but the OS fails to get it.  Not sure the mechanism but realise its not DHCP.   For instance the NIC appears as:

> Ethernet adapter Ethernet:
>
>   Connection-specific DNS Suffix  . :
>  Description . . . . . . . . . . . : ZeroTier One Virtual Port
>   Physical Address. . . . . . . . . : DA-13-44-xx-xx-xx
>  DHCP Enabled. . . . . . . . . . . : No
> Autoconfiguration Enabled . . . . : Yes
> Link-local IPv6 Address . . . . . : fe80::143:315fxxxxxxxx(Preferred)
> Autoconfiguration IPv4 Address. . : 169.254.83.208(Preferred)
> Subnet Mask . . . . . . . . . . . : 255.255.0.0
> Default Gateway . . . . . . . . . : 25.255.255.254
>  DHCPv6 IAID . . . . . . . . . . . : 4337xxxxx
>  DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-xxxxxxxxxxxxxxxxxxxx
>  DNS Servers . . . . . . . . . . . : fec0:0:0:ffff::1%1
>                                     fec0:0:0:ffff::2%1
>                                     fec0:0:0:ffff::3%1
> NetBIOS over Tcpip. . . . . . . . : Enabled
>

Device is authorised and even says ONLINE

Is there any more debugging/logging on a windows client ?

**Comment by glimberg** [comment]
Is it possible that your IP addresses & routes for the ZeroTier network overlap or conflict with those already configured on an existing network adapter on the system?  Windows likes to be "smart" sometimes and prevent things like that.

**Comment by Xachman** [comment]
I have this issue as well.  On my hostspot zerotier works fine then when im connected to a public wifi it assigns some random ip and the control panel at my.zerotier.com says im not connected.
