### ISSUE TITLE
Auth new peers on private network

### ISSUE THREAD

**Issue by srgl** [zerotier/ZeroTierOne#796]
I have a zerotier private network and I need to create VPS instances dynamically on my cloud provider. After the instance is provisioned I run `zerotier-cli join <NETWORK_ID>` but I do not get ip address on zt interface, I believe it is because it is private network. Do I need to use zerotier API (https://my.zerotier.com/help/api) to auth new peers? Or is there a better way to quickly attach new servers to my private network?

**Comment by laduke** [comment]
> Do I need to use zerotier API (https://my.zerotier.com/help/api) to auth new peers?
Yes. 
`https://my.zerotier.com/api/network/$NETWORK_ID/member` has the list of members, including unauthorized. 

Sometimes it's better to have one zerotier node be a gateway to your ephemeral VMs. 

https://support.zerotier.com/knowledgebase.php?entry=show&search-for=&article=OWZhOGU5NTYzZmFjMDlmZmIxNTQyNDVlZjRlYzI1MjI_

Here's an IPv6 way to do it. You can ignore the docker specific parts.
https://support.zerotier.com/knowledgebase.php?entry=show&search-for=&article=NjI2NGU4ZmRjZmExM2I0MTNiYWQ0ZmM4NTFkNzU5ODA_

**Comment by srgl** [comment]
I use hetzner cloud and they do not have any VPC-like isolation. That is why I use zerotier - as a VPC replacement. On top of it I am building a docker swarm cluster.
IPv6 way looks like an overkill but I'll take a look.

**Comment by janjaapbos** [comment]
The IPv6 6plane mode is actually the most efficient. No arp is needed, and NDP is emulated, ensuring the fastest mode of operation in a zerotier network.

**Comment by laduke** [comment]
thanks!
