### ISSUE TITLE
OSPF over ZeroTier

### ISSUE THREAD

**Issue by craig4who** [zerotier/ZeroTierOne#798]
Hi All,
Im hoping this issnt quite a NOOB question. But hi ho! hope someone can help me :-)

I have 3 edgemax Pro's that i want to do OSPF.

I have created on each router 1 interface for OSPF

R1 = 10.78.33.1
R2 = 10.78.33.2
R3= 10.78.33.3

These interfaces speak to one another using ZeroTier. 
All im doing to get this going is in the GUI (keeping it simple for now) adding the 10.78.33.0/24 (OSPF interfaces) and then the networks i want each router to announce and for the others to learn.

When i set this up for 2 Routers it works fine. When i add in the next router the existing connection breaks. And i think i am doing something wrong! Not sure if its OSPF or ZeroT? 

R1= 10.78.33.0/24, 10.49.97.0/24
R2= 10.78.33.0/24, 10.0.0.0/24
R3= 10.78.33.0/24, 10.0.1.0/24

so currently R3 and R2 are working perfectly. When i add in R! to the mix, R3 & and R2 break entirely. Cannot communicate at all.

Looking at documentation on UBNT i cant see anyone doing something similar to how i've set it up. Most people by the sounds of it. do this: 

get R1 to R2 and R2 to R3 so R1 can talk to R3 via R2. But ultimately i dont want to do that.

I want the 3 routers to talk in the ZeroTier chat room swapping links.

Please someone tell me this is possible? 

I have added 10.78.33.0/24 as a "LAN" under managed routes. 

each site has a linux box bridging the ZT* interface to a virtual interface. This is then in a VLAN to the edgemax router. So that each router can talk in the chat room. 

If dont implement OSPF all 3 routers speak fine. 

Hope someone can help.

**Comment by bodleytunes** [comment]
I'm thinking its not Zerotier as that will allow the multicast packets and just relay them to the right places assuming no acl's

I've tested OSPF over zerotier and it worked fine, although I never saw much point in it seeing as zt advertises networks of your choice from the controller more similar to BGP.

could it be overlapping router-id's 

Or even point2point ospf mode set instead of the standard mode, point2point the neighbors will form an adjacency but not with three of them.

**Comment by craig4who** [comment]
Hi Thanks for responding. 

I originally followed this guide to make a linux server to act as a bridge to my edgemax routers. 

https://0wned.it/2017/12/04/building-a-zerotier-bridged-network/

Something strange is going on. The 3 nodes seem to be very unstable even now without OSPF. I thought i had nailed this! 

The local.conf file for the network are all set to 0. On all 3 of the linux boxes. 
allowManaged=0
allowGlobal=0
allowDefault=0

There are not ACLs stopping and the broadcast should be picking up a response from the other end. If i untick in vmware the virtual NIC. both R2 and R3 start responding. I then tick the Nic to add it back, and they carry on working fine. Its only when i walk away everything stops. 

Are there any additional settings i need to look at for or set ? There is 100% no way a network clash or anything like that. Im just seeing odd behavior. 

I looked at the peers as well, and they are all public addresses, and i see all my network nodes public ips on port 9993 udp. So they would appear to be working fine. 

I dont know what is going on, can i give you anything?

**Comment by bodleytunes** [comment]
Not sure I've not done much bridging with Zerotier, I use it routed only, more like a centrally controlled DMVPN

Do you have to tick this in the control panel?  (allow ethernet bridging)

![image](https://user-images.githubusercontent.com/619239/42034979-a236c000-7ad9-11e8-964e-3c4b88ba6b2f.png)

**Comment by bodleytunes** [comment]
Also might be worth doing a tcpdump on there to see whats happening when you add the third node

**Comment by craig4who** [comment]
Hi Yes you do. And mine are ticked, and "Not not assign IP"

The reason im doing it as a bridge is save me on complexity. Ie installing  Qaga on a linux box in addition to the routers. I just wanted ZeroT to be be invisible, and just act as if its just put a cable from one router to another using layer2 over the internet.

Does that make sense? So when they hit the edge router it will in effect be layer 3 when i implement OSPF. 

I have been doing a tcp dump. When i add the 3rd i see a load of logs saying who is 10.78.33.3 or 2 and none of the hosts respond at all. 

![image](https://user-images.githubusercontent.com/40593188/42035688-798a6632-7adb-11e8-8dfc-dbdc22796baa.png)

**Comment by bodleytunes** [comment]
thats 10.78.33.2 replying .3 with his mac address via arp so thats normal
also you should see .1 on there if you are trying to send traffic to it.
Are you able to ping all 3 nodes when they are on the ZT subnet?
Also check if the linux bridge mac addresses may be clashing.
try an "arp -n" on each of the linux nodes.

**Comment by craig4who** [comment]
So this is R3 pinging R1 and R2 at the same time. I will confirm the ARP

![image](https://user-images.githubusercontent.com/40593188/42036531-af8e44f4-7add-11e8-928f-809aef82585f.png)

**Comment by bodleytunes** [comment]
so 2 is timing out?

can only see 1-3 have an icmp convo, 2 is replying with mac but seems to be being ignored ?

**Comment by craig4who** [comment]
Yea. So if i unplug R1 virtual NIC. then R2 and R3 start responding. Its so weird. Checking the arp clash now

**Comment by craig4who** [comment]
Literally not done anything. Now all of sudden its decided to respond.

![image](https://user-images.githubusercontent.com/40593188/42036780-6f668fb6-7ade-11e8-9796-1af85976c315.png)

**Comment by bodleytunes** [comment]
where do the edgerouters live with regards to this?  do they have ip addresses on this ZT segment i assume for OSPF to work?  I see br0 is there but normally wouldn't you have the linux bridge with no IP and the ip's are on the edgerouters, then you just bridge eth0 with ZT0, 

Also with vmware you also have the issue of arp/mac spoofing checks where you have to enable mac spoofing or promiscous mode not sure on the exact settings, im sure I've had to do things like that in the past when doing bridging..

**Comment by craig4who** [comment]
The edge routers live on 3 different locations. 

The linux box act as the bridge and are in a Vlan to the edge router itself (Isolated from LAN). Only the ER would have the 10.78.33.* address nothing else. No routes in the My ZT either. 

The linux box themselves have a nic NAT outbound to the internet. this is a completely different subnet and has a 192.168.193.1/30. 

so iv tried my best so make sure there are not subnet or clashes along the way. 

Anything with ZT doesnt have an ip and is litterally a bridge with a "Manual" ip with the bridge options. 

You are right about the MAC Spoofing in VMware. Thats all taken care of and is currently set. If they werent i wouldnt get a response at all. The guide i linked is exactly how i followed. And mentions about vmware/hyper V. So yes covered that. 

Any other suggestions? Appreciate your responses!

**Comment by bodleytunes** [comment]
hmmphhh maybe take simultaneous tcpdumps on all three bridges  tcpdump -i br0 -nn -w mycap.pcap then look at all three on wireshark and notice any differences what stands out when you put the third node on the ZT cloud.   do this while doing a ping from one of the edgerouters to the others. whatever it is, it will be solvable with much tinkering.  It might be something really daft in the end!

**Comment by bodleytunes** [comment]
I setup a basic testbed on my eve-ng server and it all works as expected, I can ping any of the other IP's in the ZT cloud.  Admittedly not simulating a full blown VMware setup and all the tweaks and pitfalls to be avoided with that, this is just three linux VM's acting as ZT nodes and three others hanging off them simulating the "edgerouters"


Also I'm using ifupdown2 and these shorter commands in /etc/network/interfaces:
```
auto ens3
iface ens3 inet static
  address 10.55.89.47/24
  gateway 10.55.89.1

auto ens4 
iface ens4 

auto br0
iface br0 
        bridge-ports ens4 ztwfuh43v6 
```
`
ens3 is internet facing
ens4 is inside / edgerouter facing
ztwfuh43v6 is the zt interface
ens4 and ztwfuh43v6 are bridged together.

![image](https://user-images.githubusercontent.com/619239/42065282-facc8a58-7b31-11e8-8625-5100592e4455.png)

**Comment by bodleytunes** [comment]
One other thought I had was something funky going on with Spanning-tree,
assuming its running on the bridge, to introduce a 3rd node and then for it
to stop working sounds like it could be detecting a loop and stopping
forwarding.  Clutching at straws now though!

**Comment by craig4who** [comment]
I think you onto something on your last comment! I will come back to you to confirm! Very good shout!

**Comment by craig4who** [comment]
Hi,

So I checked the switches for Spanning tree! one of them was enabled on a physical switch in one of the problem locations! turning this off hassnt really helped at all. I even gave it a reboot. 

One thing i did notice, was some options on my bridge NIC, which you didnt mention above.

Two things are enabled (apart from bridge ports)

bridge_fd 0 
bridge_maxage 0

So i have commented these out thinking this could be the issue.

Still this problem remains though! Its soo soo annoying! 

Are there any recommended switches i could apply to the bridge to help it?

Could this be MTU at all anything like that?

PS Appreciate your setting up a test lab!

**Comment by bodleytunes** [comment]
MTU it would either work or it wouldn't if you say you are pinging and then
it suddenly drops off when another node comes online that doesn't sound
like MTU type of problem.

Do all the ZT nodes have unique id's?  ie you didn't clone the nodes and
clone the id's or anything like that?

**Comment by craig4who** [comment]
Hi no the nodes were not cloned. 

Ubuntu was setup individually and was just joined to the ZT network as you would do normally. 

Would it not just be better for the routers to communicate over a /30 and not a /24? 

The reason for it being /24 was so that when OSPF is working the routers could exchange routes, but not need to go through an edge router creating additional hops.

**Comment by bodleytunes** [comment]
There are more than two routers that need to be on this segment for the OSPF though right?  So for everything to work it would have to be a /29 minimum.  they are on the same broadcast domain.  

If you want to use routing you could turn off bridging, then use OSPF or BGP from your linux ZT node inbound to the edgerouter and share the routes it learns from ZT that way?

Personally i would use BGP and use something like Bird or FRR.

**Comment by bodleytunes** [comment]
and with the above you would get the extra hop yes but it shouldnt impact performance, if anything i would have thought ethernet bridging has more of a performance hit?  although i could be wrong!

**Comment by jdrews** [comment]
For what it's worth, we've been running OSPF over ZeroTier for a few years now. No problems.
