### ISSUE TITLE
iOS can't join over cellular network

### ISSUE THREAD

**Issue by peewee5** [zerotier/ZeroTierOne#800]
I'm running into an issue where I can't connect to any other hosts on my network from my phone, (iPhone X), when I am on the cellular network (T-Mobile).  At first I wasn't able to connect even if I was on wifi but that was because my other VPN profiles were set to connect on-demand.  Now that I have altered that setting, I can access hosts as long as I am on a wifi network of some sort but the second I switch to 4G the connection now longer works.  I'm using Terminus and the only thing that it gives me is and invalid argument error.

**Comment by laduke** [comment]
I wonder if it's a IPv6 to IPv4 thing?
Hop in https://my.zerotier.com/community if you get a chance.

**Comment by laduke** [comment]
On my iPhone, I have one network that won't fully connect on AT&T. 

- It's a 93afae5963 network
- IPv6 physical IP shows up in Central
- No [VPN] icon shows up on the phone
- It's the only network I have with custom DNS servers set (1.1.1.1)

**Comment by tresni** [comment]
I was seeing what I think is a similar issue.  Using T-Mobile not AT&T, but the solution was to enter all 4 custom DNS servers.

OpenDNS:
* 208.67.222.222
* 208.67.220.220
* 2620:119:35::35
* 2620:119:53::53

Google
* 8.8.8.8
* 8.8.4.4
* 2001:4860:4860::8888
* 2001:4860:4860:8844

Cloudflare
* 1.1.1.1
* 1.0.0.1
* 2606:4700:4700::1111
* 2606:4700:4700::1001

See if that works for you?
