### ISSUE TITLE
Protocol needs to be written up in RFC form

### ISSUE THREAD

**Issue by coretemp** [zerotier/ZeroTierOne#810]
This is essentially a reopening of https://github.com/zerotier/ZeroTierOne/issues/34 in which @adamierymenko wrote: 

> Once out of beta, this will get done at some point.

I think it has been out of beta for quite some time and other than the heavily commented https://github.com/zerotier/ZeroTierOne/blob/master/node/Packet.hpp I was not able to find anything. I am quite happy to just operate with `Packet.hpp`, but this is certainly not the case for other people in our organisation.

**Comment by adamierymenko** [comment]
Yes it does. :)

**Comment by adamierymenko** [comment]
We've toyed around with things like GVSP: Global Virtual Switch Protocol.

There are three remaining issues that we'd like to address:

(1) We'll be introducing FIPS-certifiable crypto soon. The implementation for this might be closed source but it will be openly documented as part of the protocol. This is to support enterprise customers that require it. This is not necessarily stronger crypto, so people who don't require FIPS or other crypto certifications probably will not even care.

(2) We need forward secrecy. This will get implemented soon. We've been swamped with other concerns.

(3) The 'moons' thing needs to die in favor of something much simpler for federating VL1 infrastructure. VL2 (controllers) are of course already very easy to federate.

Once those things are put to bed we do want to do an RFC-style document, or maybe even an actual RFC.
