### ISSUE TITLE
how to uninstall ZeroTierOne for  RASPBIAN

### ISSUE THREAD

**Issue by moc375** [zerotier/ZeroTierOne#813]
1. My system environment, RASPBIAN STRETCH LITE (raspberry PI 3)

2. My ZeroTierOne version 1.2.8

how to uninstall  ZeroTierOne？

thanks！

**Comment by nate8199** [comment]
sudo apt remove zerotier-one

**Comment by adriel** [comment]
Kinda old, but the apt remove (or purge) leaves behind the user. `zerotier-one:x:999:996::/var/lib/zerotier-one:`

**Comment by DaniW42** [comment]
Even though this is an old thread and it is already closed. One should also consider to remove the corresponding sources.list:

```
sudo apt remove zerotier-one
sudo rm -f /etc/apt/sources.list.d/zerotier.list
```

**Comment by Narann** [comment]
Adding a note here: There are still a `zerotier-one` user and group after removing the package and source liste%.

**Comment by jerrychong25** [comment]
As of August 2022, need to use following commands for uninstalling Zerotier.
```
sudo apt remove zerotier-one
sudo rm -f /etc/apt/sources.list.d/zerotier.list
sudo rm -rf /var/lib/zerotier-one
```

Plus remove `zerotier-one:x:996:996::/var/lib/zerotier-one:/bin/sh` in `/etc/passwd`
