### ISSUE TITLE
REQUESTING_CONFIGURATION error (macOS)

### ISSUE THREAD

**Issue by ydakuka** [zerotier/ZeroTierOne#814]
Previously, everything worked well, but today I got:
```
YauheniD:~ ydakuka$ sudo zerotier-cli listnetworks
200 listnetworks <nwid> <name> <mac> <status> <type> <dev> <ZT assigned ips>
200 listnetworks ... REQUESTING_CONFIGURATION PRIVATE zt0 -
```

The tip on the [link](https://support.zerotier.com/knowledgebase.php?entry=show&search-for=&article=NDI4MWE1YTY1MDEzMGIyNDY0M2M5YzFhNGFiMjVjYjQ) did not help.

```
YauheniD:~ ydakuka$ sudo zerotier-cli -v
1.2.8
```

macOS HighSierra 10.13.6

**Comment by laduke** [comment]
Could have been an issue with my.zerotier.com. Are you back online now?

**Comment by ydakuka** [comment]
Yes, it's working now. Thank you.

**Comment by Tetetetetetetet** [comment]
Hello!

I came into the same error recent days and stuck here. How did you solve this exactly? I really hope someone can help me out!!! 

Thanks a lot!
