### ISSUE TITLE
Dropped and delayed packets while another network transfer is taking place

### ISSUE THREAD

**Issue by Intensity** [zerotier/ZeroTierOne#815]
Whereas my ping round-trip-time over ZeroTier averages <7ms between two connected hosts (Client and Gateway), whenever there is another data transfer taking place that involves those two hosts, I experience significant packet loss and ping delays. The ping packet loss is 29%, and with these stats: `rtt min/avg/max/mdev = 5.085/2301.156/9978.148/2866.061 ms`.

The Client and Gateway hosts are both Ubuntu 16. I've spun these up in two independent data centers that don't add any additional firewall restrictions (such as a security group), and the Linux firewall rules on both hosts are permissive (default ACCEPT). I've also experienced the same performance characteristics when the client is macOS, although that wasn't in a data center. Note that I'm using IPv4.

Both Client and Gateway belong to the same ZeroTier network. The Gateway host is also configured as an internet gateway (following the knowledge base instructions). On the Client, if I run two "speedof.me" internet tests while at the same time I ping the ZeroTier IP for the Gateway, I experience these dropped packets and delays.

The baseline ping round trip time (over ZeroTier, without the transfer taking place between the Client and Gateway) is <7ms and there is no packet loss. The ping connects the two hosts directly (that is, ZeroTier is able to send its encrypted packets directly between these two hosts over UDP at all time).

I'd like to confirm external reproducibility of this issue, and I'd also like to understand in the optimistic case, what is possible here? Is ZeroTier positioned to respond well to this situation in general? Are the performance characteristics coming up because of something specific?

I notice very little resource overhead (negligible CPU) on both hosts, so I'm wondering what might be going on. These concerns also include the case where more than one client (this time, behind a NAT - but with the same external egress IP) is connecting to the Gateway, but I've run the test just involving one connecting client.

**Comment by Intensity** [comment]
[ZeroTier-Performance-Test-20180717.txt](https://github.com/zerotier/ZeroTierOne/files/2211321/ZeroTier-Performance-Test-20180717.txt)

**Comment by adamierymenko** [comment]
Another transfer as in over ZeroTier or over the raw network? If it's outside ZeroTier it's possible that its packets are being prioritized higher. Will take a closer look though... that's just my first thought.

**Comment by Intensity** [comment]
Another transfer over the ZeroTier network.

One such transfer is from Client, naming Gateway's ZeroTier address as its default gateway, connects to speedof.me through Gateway (and over the ZeroTier network).

Another example might be a couple of sftp transfers, over ZeroTier, between Client and Gateway.

As a comparion (prior to my use of ZeroTier), when I have several (say for example ten) data transfers taking place between two servers, this hasn't resulted in ping packet loss. And so I assume that the kernel processes all packets. However, I'm wondering if I ought to have different expectations about potential packet loss when ZeroTier is multiplexing sessions (TCP and UDP). If they are TCP sessions, they'll end up retrying to achieve reliability (although if there is packet loss it can cause noticeable delays if packets need to be retransmitted frequently). But for UDP/ICMP, the data may be lost altogether. I wouldn't have expected such issues when all traffic is passing - over ZeroTier - between two hosts that more or less have a direct route to each other. But I do seem to be reproducing such loss and delays.

I hope this clarifies.

**Comment by joseph-henry** [comment]
I see that you've got instances in two separate datacenters but if it's one of those datacenters internally throttling ZeroTier's UDP packets we might need a third instance outside of both datacenters to test each against. Is this possible for you?

**Comment by Intensity** [comment]
I'll spin up further infrastructure to test. I'll keep you posted.

**Comment by typcn** [comment]
I have the same issue while sending the packet ( receiving packet is ok ), it can run at 50Mbps and normal latency in the first second, then the speed drops to 100Kbps and latency increase to 500+, CPU usage is very high.

Downgrade to 1.2.4. will fix this problem.

**Comment by joseph-henry** [comment]
Did you have any luck replicating this issue with a third instance? @Intensity

**Comment by Intensity** [comment]
@joseph-henry haven't looked at that yet. Hope to do so soon.

**Comment by dch** [comment]
I can replicate this pretty easily in following setup:

- OSX downloading something like Xcode bloatware 
- try ssh to FreeBSD (now at 12-ALPHA8 amd64), the whole connection keels over
- ping is dead
- there's a router, a switch, and a ubiquiti AP-AC-Pro in between

I recently updated OSX to Mojave as well, just re-installing ZT on OSX to make sure. It's all local network here so I can easily grab any info required.

**Comment by joseph-henry** [comment]
@dch in your example is Xcode being downloaded over a tunneled ZeroTier connection? If not, that behavior could be because non-ZT traffic is just being prioritized over ZT traffic.

One thing to try @Intensity: Disable encryption and use a trusted path as a test. If this improves things it would give us a better starting point to diagnose this.
