### ISSUE TITLE
ZeroTier Central Docker Image

### ISSUE THREAD

**Issue by paweljacewicz** [zerotier/ZeroTierOne#817]
Hi!

I've found the ZeroTier Central docker image on the Docker Hub (https://hub.docker.com/r/zerotier/central/), but it seems outdated comparing to the public my.zerotier.com. Do you plan to push the new image with more current version? I'd be nice to have it for testing.

Thanks!

**Comment by paweljacewicz** [comment]
Hi again,

@adamierymenko or maybe somebody else from the team - can I have any comments on the question I asked previously?

Thanks!

**Comment by laduke** [comment]
Hi @paweljacewicz the differences between that version and what would be current are pretty minor IIRC. Is there a specific feature you're looking for?

**Comment by paweljacewicz** [comment]
Hi @laduke 

Thanks for answering. I just wanted to test it out on the most current version, to be sure it is the same code and feature set as I get when buying. My team is thinking about getting a paid subscription, as we are already testing ZertoTier One. Managing networks without good controller software is troublesome... to say the least.

On the other hand, we're dockerizing whenever we feel it helps, so I was hoping also to get the current version of the controller as a docker image.

Thanks!

**Comment by adamierymenko** [comment]
I'm closing this one because we are fairly close to releasing a new version of Central that is much easier to deploy with or without Docker. For now we're going to leave the Docker image alone, and then we're going to release something a lot better. There will be migration instructions.
