### ISSUE TITLE
[Clarification] ZeroTier's handover mechanism

### ISSUE THREAD

**Issue by leleobhz** [zerotier/ZeroTierOne#818]
Hello!

A thing isn't clear and reliable for me is about how ZeroTier handles horizontal and vertical handover. In a symptomatic perspective, changing from a 802.11 to LTE can in worst case take more than 3 minutes to reach the network. Unlikelly I used to think, the worst case is when I change from NATed network to double NATed network (I think IPv6 to IPv4 may be worst, but no). Since my mobile carrier - as example - only uses CGNAT prefixes, if I need for some reason to exit a NAT to a CGNAT+Android Tether network it tooks a life to come back. I've already experimented this kind of issue on other network handover type.

Speculatively speaking, after read https://zerotier.com/manual.shtml#2_1_1 I conclude ZT does not implement something like HMAC to allow a changed-address peer to reuse a existent connection (Receiving a packet from other address and accepting it since its authenticated) and allow other peer to restablish the return path again (Using hole punch or other techniques).

This differ from a bug report because handover isnt a issue and its a predictable behaviour. Handover costs time and vertical handovers specially loss a lot of packets. But I think the network convergence of ZT takes too long, longer than Skype - as example - that also use techiniques to mitigate handover effects.

So, what ZT can explain or even change about the way it does handover?

Thanks!

**Comment by adamierymenko** [comment]
ZT just doesn't work this way. 1.4.0 contains some path discovery and changeover improvements, so closing for now.
