### ISSUE TITLE
zerotier-idtool genmoon moon.json Don't work

### ISSUE THREAD

**Issue by leviacn** [zerotier/ZeroTierOne#824]
zerotier-idtool genmoon moon.json Don't work when more than 1 Endpoints。
When my moon.json contains a node, moon.json can use the command: "zerotier-idtool genmoon moon.json" to successfully get the 000000xxxxxxx.moon file. But if I add more than one node to moon.json, the command will be invalid, prompt
"/var/lib/zerotier-one$ zerotier-idtool genmoon moon.json
Terminate called after throwing an instance of 'std::invalid_argument'
   What(): parse error - unexpected '{'; expected ']'
-bash: line 125: 8577 Aborted zerotier-idtool genmoon moon.json"

**Comment by leviacn** [comment]
Sorry, I made a small mistake myself. The reason is that there is no "," between the two nodes.

**Comment by laduke** [comment]
thanks!
