### ISSUE TITLE
Upgrade to 1.2.12 sometimes fails to restart service

### ISSUE THREAD

**Issue by grantstephens** [zerotier/ZeroTierOne#825]
We've been updating to 1.2.12 and have found that on a small number of machines the `apt install zerotier-one=1.2.12` fails to restart the zerotier-one service once it has complete. Unfortunately haven't been able to spot a trend as there is nothing in the apt output and the service log only shows the service being shut down. This has happened on Ubuntu 14, 16 and 18.

**Comment by JonatanAlonzoArt** [comment]
sudo systemctl restart zerotier-one
sudo systemctl status zerotier-one
sudo systemctl start zerotier-one
sudo systemctl stop zerotier-one
