### ISSUE TITLE
[Question] How bad would it be if I don't set zt0's mtu?

### ISSUE THREAD

**Issue by ElTopo** [zerotier/ZeroTierOne#827]
Hello,

One of my old ARM box (running Linux  2.6.22.18 with armv5tejl processor) does not allow me to set mtu at osdep/LinuxEthernetTap.cpp:198
```
...
if (ioctl(sock,SIOCSIFMTU,(void *)&ifr) < 0) {
...
```
zerotier-one quits if ioctl() fails. 

I modified the code to just printf a warning then continue, my version seems OK with mtu 1500:
```
$ ip addr show zt0
17: zt0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast qlen 500
```
On my other box that allows me to set mtu, it shows with mtu 2800:
```
# ip addr show zt0
8: zt0: <BROADCAST,MULTICAST,UP,10000> mtu 2800 qdisc pfifo_fast qlen 500
```

Since I mainly just ssh/sftp to the old ARM box, mtu 1500 seems to work without problems.
So my question is: is it really bad for zt0 with mtu set to 1500? will I get problems later with zerotier connections with mtu other than 2800?

Thanks.

**Comment by adamierymenko** [comment]
With the wrong MTU you're going to get a lot of lost packets if they're coming from other devices with higher MTUs. TCP may compensate with PMTU discovery but this isn't guaranteed. UDP-based protocols might have big issues.
