### ISSUE TITLE
Some devices get randomly denied

### ISSUE THREAD

**Issue by dec0dOS** [zerotier/ZeroTierOne#828]
Hello, I'm using ZeroTier Central to manage connected devices to my networks. But some devices that were approved before gets randomly denied after some time. It's really hard to reproduce, so I want to ask is there a way to debug this and fix it? I think that this is the problem is not on the client side but on the ZeroTier Central.

**Comment by adamierymenko** [comment]
Is this by any chance still occurring or occurring consistently?

**Comment by heydonovan** [comment]
This happened to us a few hours ago. Took down three clients. :(

**Comment by robricc** [comment]
I hate to be a "me too" without much to add, but this just happened to two networks of mine. Took out 10 of 27 clients on one, and 3 of 5 on the other. IP address reservations were also erased on affected nodes. Clients are a mix of Windows, Mac, Linux and Synology boxes. 

I am using my.zerotier.com as a subscriber.

**Comment by jdrews** [comment]
Happened to us today at around 4:06pm EST. It deauthorized around 10 devices. 

It also stripped out the managed IPs. 

When I went to add the IPs via central would take the IP and then clear out the ip again. After setting the IP a few times it took. This same behavior was noticed when attempting to check the Auth checkbox.

**Comment by dec0dOS** [comment]
Just happened again. This is really frustrating.

**Comment by user514** [comment]
This happens to me too some days ago. I thought that maybe I have forgotten to authorize them, but was almost sure that I did. Now reading this, I think I was one of the sufferers.

That happens some days after creating account. I then reauthorize them, and no problem since. Maybe one week after reauth now.

**Comment by adamierymenko** [comment]
I think this may be related to database issues we've had. We are almost ready to upgrade Central to a completely new version that uses a different database and is basically re-engineered from the ground up. Is anyone still seeing this?

**Comment by adamierymenko** [comment]
Closing since we have upgraded Central -- please re-open if you ever see this again
