### ISSUE TITLE
Enable environment to override default home path

### ISSUE THREAD

**Issue by themightychris** [zerotier/ZeroTierOne#829]
I'm [working on packaging zerotier with habitat](https://github.com/habitat-sh/core-plans/pull/1674), which creates can deploy services in isolated runtime environments. Habitat needs to control what directory the service runs out of, ideally being able to change it both at build time and at run time. I had to patch `osdep/OSUtils.cpp` to let habitat change it at build time, and it would be helpful to be able to change it at runtime too. I explored first creating wrapper scripts for all zerotier's commands that would pass the environmental home directory as a CLI argument, but that was messy and inhibited users from from using that CLI argument for their own purposes

It would be greatly helpful to my efforts and I believe useful for other novel deployment techniques if [`platformDefaultHomePath()`](https://github.com/zerotier/ZeroTierOne/blob/3de7691af306f86b5b3aa6fb15777841e9ba1388/osdep/OSUtils.cpp#L381) would use the value of an environment value like `ZEROTIER_HOME` if it's set

**Comment by laduke** [comment]
Thanks for working on this! 
The way things are right now, if zerotier did add this... it would take a while to get released. I hope it's not blocking you too bad. Maybe we can figure out a better way to wrap it.

**Comment by themightychris** [comment]
I'm just patching the sources right now and getting by: https://github.com/habitat-sh/core-plans/pull/1674/files#diff-f5d33f536a534bb8db9f39420b7234c1R7

**Comment by joseph-henry** [comment]
I've added the ability to specify the home directory via `ZEROTIER_HOME`. This feature is currently only available in the `edge` branch. 

When running you will need to use the `-E` flag to preserve your environment:

```
export ZEROTIER_HOME="/hab/svc/zerotier-one/data"
sudo -E ./zerotier-one -d
```

This feature will eventually make it into the `master` branch. Let me know if you have any questions.

**Comment by themightychris** [comment]
@joseph-henry

Perfect! Thanks!

**Comment by Teteros** [comment]
@joseph-henry Just a note for you and anyone else that `ZEROTIER_HOME` is not read on Windows.
![ss](https://user-images.githubusercontent.com/5067989/63631479-05331e00-c620-11e9-9826-f97fc9cf2a0d.png)
