### ISSUE TITLE
Disable binding random ports

### ISSUE THREAD

**Issue by yanggis** [zerotier/ZeroTierOne#831]
When I check the listening ports by ZeroTierOne, I find, excpet the port 9993, ZeroTierOne also listens some other random ports, such as, 51727, 51728 at present. 
Can I set ZeroTierOne listen some specific ports, instead random ports? I'm using the port range 20000-30000, once one or two ports are used by ZeroTierOne, my app cannot run successfully.

**Comment by adamierymenko** [comment]
We could make this more configurable. By default it does this to get around broken NATs, which are extremely common.

**Comment by joseph-henry** [comment]
@yanggis 

I've added the ability to manually set the secondary and tertiary ports via the `local.conf` file. For example:

```
{
        "settings": {
                "primaryPort":9993,
                "secondaryPort":20000,
                "tertiaryPort":21000
        }
}
```
The fields actually function as the starting point for a series of attempted bindings. For instance, if you use `20000` for your secondary port and it fails to bind, it will continue to try `20001`, `20002`, etc. So space out your secondary and tertiary ports accordingly.
 
This change is currently only available in the `edge` branch. Let me know if you have any questions or if this doesn't fix your issue.

**Comment by yanggis** [comment]
@joseph-henry thanks for your great work. May I know the path for the file local.conf?

**Comment by joseph-henry** [comment]
No problem, it's the same directory where your `identity.*` files are stored. If the file doesn't already exist, simply create it.

**Comment by yanggis** [comment]
OK, noted, thank you very much.
