### ISSUE TITLE
Windows: UI doesn't update without restart

### ISSUE THREAD

**Issue by theCalcaholic** [zerotier/ZeroTierOne#832]
For all tested Windows devices (6 PCs, Windows 7 and Windows 10), the UI doesn't update itself after performing any of the following actions (from the UI):

- Joining a network
- Leaving a network
- Deleting a network

The changes are only displayed after quitting and starting the program again. This does not only apply to the main menu, but also the "show networks" dialog, even when (re-)opened after a change (joining/deleting/creating a network).

**Comment by laduke** [comment]
What version of zerotier? 1.2.12 is the latest.

**Comment by theCalcaholic** [comment]
Yes, we all had 1.2.12.
Sorry, didn't see the answer until now.

**Comment by hangim** [comment]
Meet this problem too.

**Comment by kevingarman** [comment]
I see this as well...Windows 7.

**Comment by anfo55** [comment]
Moreover I can get "can't connect to ZeroTier service" error message when attempting, but can confirm a restart of the application fixes the multiple networks refresh.

**Comment by Bigbossbro08** [comment]
Same problem here. It seems it works good only on cmd...

**Comment by snadam** [comment]
Same behavior here.
Windows 10 pro and current version of ZTO

**Comment by Bombastisch** [comment]
Any chance that we get this fixed? I really love ZeroTierOne, but this drives me nuts.

**Comment by gak** [comment]
Same here...

**Comment by ertankucukoglu** [comment]
I confirm GUI network status information is not being updated.

I am on Windows 10 Pro 64Bit, version 1809, OS build 17763.316

I cannot see changes in GUI. It stays with the information at initial run time. Seemingly not doing any more updates after initial run.

**Comment by alexjhart** [comment]
Same

**Comment by spbogie** [comment]
This appears to have been fixed by a4b19173618756e1d0cee3339e6cde734d13abb7 in dev. 

Unsure what the current release schedule looks like, but a hotfix for WinUI might be nice.
