### ISSUE TITLE
Controller - Can sometimes give out duplicate v4 auto-assign addresses

### ISSUE THREAD

**Issue by laduke** [zerotier/ZeroTierOne#834]
Reported by self-hosted user; I tested again my.zerotier.com 

With a /24, at some point, it starts giving out already taken addresses. 

With just a /30, it just doesn't hand out any more addresses.

**Comment by jdrews** [comment]
Can confirm. I have seen this on my.zerotier.com

**Comment by adamierymenko** [comment]
Fixed in `dev` and the live running version (a while ago)
