### ISSUE TITLE
Android not setting default gateway (full tunnel mode)

### ISSUE THREAD

**Issue by maxogden** [zerotier/ZeroTierOne#835]
Hi, I am following this guide https://support.zerotier.com/knowledgebase.php?entry=show&search-for=&article=ZWFhNWMyMTZjODY1ODcwNmFhZmJjYmRhN2I5MjRhOGQ_

I have a network with a raspi, a mac laptop and an android. My raspi is setup as the gateway. I have full tunnel mode working successfully between my mac laptop and my raspi. To test, I tether my laptop through my android's AT&T hotspot, check my IP (shows AT&T), then join the zerotier network, check IP again, and it shows my home IP. `netstat -rn` on the mac laptop shows the correct `0/1` default gateway. Woohoo!

My problem is with Android (Using app version 1.2.12-2). When I join the network on Android over cellular data, I can ping my raspi but my external IP remains on AT&T. In adb shell it shows two routes:

```
bash-4.4$ ip route show
<at&t>/24 dev rmnet_data0  proto kernel  scope link  src <at&t gateway>
<zt>.0/24 dev tun0  proto kernel  scope link  src <zt android ip>
```

I also checked `ip route show table 0` and the first entry is `default dev tun0  table 1025  proto static  scope link`, and `ip route show table 1025` shows:

```
default dev tun0  proto static  scope link 
<zt>.0/24 dev tun0  proto static  scope link 
224.0.0.0/4 dev tun0  proto static  scope link 
```

I couldn't find any reference to my raspi IP (the gateway) in any of the output, so I tried adding a default gateway route myself:

```
$ ip route add default via <raspi> dev tun0
Cannot talk to rtnetlink: Permission denied
```

But apparently can't.... any ideas?

**edit**

Forgot to mention, I have 'Route Via Zerotier' enabled on my network

**Comment by glimberg** [comment]
I don't think Android will route tethered data through a VPN adapter even if a default route is set.  ZeroTier doesn't work the same on Android as it does on Windows/Mac/Linux, and we have to work within the restrictions of the Android OS.

**Comment by maxogden** [comment]
> I don't think Android will route tethered data through a VPN adapter even if a default route is set. 

Thanks for the quick reply. My description above is kind of long and confusing, but my issue isn't that Android isn't routing tethered data (I am not using tethering except to test Mac), it's that it isn't routing traffic over ZeroTier (using the phones cellular internet). 

I've been using the NordVPN app successfully, and when it's enabled (and tunneling over cellular) my routing table looks like this:

```
$ ip route show
<nordvpn>.0/24 dev tun1  proto kernel  scope link  src <nordvpn gateway>
<at&t>.0/24 dev rmnet_data0  proto kernel  scope link  src <at&t gateway>
```

That's what I was expecting to see when ZeroTier was enabled, but for some reason the default route is not getting set.

**Comment by glimberg** [comment]
And you've set the "Route via ZeroTier" option in the app?  If not, the default route won't be added.

**Comment by maxogden** [comment]
@glimberg Yes my settings look like this:

![7eb61f5e-520e-40d5-b5ff-dba168f72053](https://user-images.githubusercontent.com/39759/44548481-0d860f80-a6d3-11e8-95e7-c68dd2153ec0.png)

**Comment by glimberg** [comment]
I'll have to get a test environment set up and test some things out.  I had to do some black magic to get ZeroTier to work on Android (and iOS).  Both of them only give an L3 Tunnel adapter, but ZeroTier operates at L2 so some bridging between the two layers of the stack had to be done.  Forwarding from tethered devices has not been done in there for sure.

**Comment by maxogden** [comment]
@glimberg I just tested w/ my Android on some cafe wifi and:

- When connected over wifi (cellular data off), it works as expected (`curl ifconfig.io` returns my home IP from the raspberry pi)
- When I turn wifi off and turn cellular data back on, I get the same behavior as above (can ping raspberry pi but tunnel is not working)

Also, curiously, when on wifi w/ the full tunnel working, there is nothing in the `ip route` output referencing my raspi IP adddress (the gateway), so I guess the routing is being done via other means (the black magic you mentioned).

**Comment by glimberg** [comment]
It's just being set via the [VpnService.Builder](https://developer.android.com/reference/android/net/VpnService.Builder) interface on Android.  What Android does with it after that is a black box.

**Comment by glimberg** [comment]
I just thought of something on this.  I'm guessing the cafe's network you were on was IPv4 only.  Once you get into an IPv6 only setup (cellular network most likely), or are in a mixed IPv4/IPv6 setup, it's preferring IPv6.  With no IPv6 default route or router advertisements on the ZeroTier network, it just goes around that and uses the standard network interfaces on the device

**Comment by maxogden** [comment]
@glimberg Yes that is correct, the cafe wifi is ipv4 and my AT&T address is ipv6. Would setting up IPV6 on my raspi help?

**Comment by glimberg** [comment]
It probably would.

**Comment by maxogden** [comment]
@glimberg I found a quick hack/workaround. On my Android n Settings > Mobile network > Access Point Names I was able to change the APN protocol for AT&T from "IPv4/IPv6" to "IPv4". I then got an IPv4 address and everything started working over the cellular connection.

Closing this issue, but sounds like there should be a separate issue to address the mixed ipv4/ipv6 connectivity issue?

**Comment by maxogden** [comment]
P.s. thanks a bunch for the help!
