### ISSUE TITLE
Two computers with same NODE ID

### ISSUE THREAD

**Issue by chetstone** [zerotier/ZeroTierOne#839]
I used Migration Assistant to copy everything from my old mac to my new mac. Now they have the same Node ID and the new one cannot connect to zerotier. (I intend to keep the old mac online.) How can I reset the node ID to something unique? I tried running 
```
$ sudo /Library/Application\ Support/ZeroTier/one/uninstall.sh
Password:
Stopping any running ZeroTier One service...
Making sure kext is unloaded...
Removing ZeroTier One files...
Uninstall complete.

Your identity and secret authentication token have been preserved in:
  /Library/Application Support/ZeroTier/One

You can delete this folder and its contents if you do not intend to re-use
them.

$ 
$ sudo rm -fr /Library/Application\ Support/ZeroTier/One
$ sudo rm -fr ~/Library/Application\ Support/ZeroTier/One
```

Then I downloaded a new copy of zerotier one and installed it. After reboot it's still stuck with the old Node ID. How is the Node ID computed?

**Comment by chetstone** [comment]
Well trying this a few more times it finally worked. Perhaps the solution was completely uninstalling, then rebooting, then reinstalling. Once I had a valid Node ID there were still problems with the KEXT (Issue #467) but I finally got it working.

**Comment by laduke** [comment]
https://support.zerotier.com/knowledgebase.php?entry=show&search-for=&article=N2VhZDZkYWM2MDQzZjY0NmNiYmY0OTRkYTM2ZjgwMjk_
