### ISSUE TITLE
Synology not using default port

### ISSUE THREAD

**Issue by toasifali** [zerotier/ZeroTierOne#841]
I have issue with using my Synology NAS that isn’t using the default port, the UI keeps on saying that it is offline even though it is connected. As you can see from the attached screen shot it is trying to get to the default port 50001 instead of port 30451 that my NAS uses. Is there anything I can change that will point it to the correct port

<img width="956" alt="zerotier" src="https://user-images.githubusercontent.com/40306222/44680252-30822d80-aa0b-11e8-9a1e-12e045d2dab3.png">

**Comment by laduke** [comment]
Hi. Can you create an issue at https://github.com/zerotier/ZeroTierNAS/ ? Thanks!

**Comment by laduke** [comment]
I made this  issue https://github.com/zerotier/ZeroTierNAS/issues/32 @toasifali if you want to follow along

**Comment by toasifali** [comment]
Thanks for doin this

________________________________

**Comment by joseph-henry** [comment]
@toasifali I've updated the packages to include a fix for this issue. You can find them here: http://download.zerotier.com/RELEASES/1.2.12/dist/
