### ISSUE TITLE
Grammar error on the last line of installing the CLI client

### ISSUE THREAD

**Issue by electricduck** [zerotier/ZeroTierOne#843]
After installing ZeroTier One on Linux (using the commands listed on the install page), the last line of the install which says the install is successful doesn't make any sense grammar-wise.

```
*** Success! You are ZeroTier address [ XXXXXXXXXX ].
```

Surely it should be `Success! Your ZeroTier address is [ XXXXXXXXXX ]`?

Using _ZeroTier One **1.2.12**_ on _Ubuntu 16.04.3_.

**Comment by laduke** [comment]
https://github.com/zerotier/install.zerotier.com
