### ISSUE TITLE
High CPU usage under OpenWRT

### ISSUE THREAD

**Issue by neculaesei** [zerotier/ZeroTierOne#844]
**Scenario**

I have a router running OpenWRT with zerotier 1.12.2 that I use to connect devices I plug into the router (eth) wherever I am with my desktop machine at home.
This allows me to do incredibly good streaming of my desktop's screen and is a much better solution over any remote-controlling software (almost no input lag, watching videos doesn't drop frames, same for sound streaming).

The router is connected to a 1Gbps network, same for the desktop at home - internet speed is not an issue.

**Bug description**

The zerotier-one process (running on the router) struggles to keep up with the traffic, and spikes sometimes to 100% cpu, which creates lag. I have created a gif that shows the problem when there is sudden movement on the screen and the traffic increases.

Right now the only thing that limits my remote control solution is the cpu usage of ZT on the router. Everything else works perfectly, and it's as if I'm not even away from my home desktop.

What should I do?
Should I buy a better router?
Is it a broken configuration?

ZT is the only process eating up the CPU.

[GIF of the CPU usage going up with traffic](https://i.imgur.com/9kDCZLG.gif)

Thank you for taking the time to read this.

**Comment by janjaapbos** [comment]
I like your CPU video / GIF, nice way to show the issue...

I don't think the config is broken. What are the hardware specs of your router? (CPU) This is probably the bottleneck. So yes, perhaps get a better router with a faster CPU, or lmit the bandwidth, so it has to do less work?

**Comment by neculaesei** [comment]
Thank you for the quick response!
It's a TP-LINK TL-WR1043N v5 with a 750 MHz CPU.
I'll try to get the setup working on a Raspberry Pi 3 B+ (1.4GHz) to see if it can cope with the bandwidth.

Thanks for the help!

**Comment by nicedayever** [comment]
I got the similar situation. 
I am using the LEDE x64 (J1900 CPU), the process `zerotier-one` would use 13% of the CPU resource.
The zerotier version is 1.2.12
