### ISSUE TITLE
ZeroTier One Client issue on Windows 10 1809 (Build 17758.1)

### ISSUE THREAD

**Issue by tnewton1** [zerotier/ZeroTierOne#847]
**Describe the bug**
Windows 10 Pro 1809 (Insider build 17758.1) will not reconnect to ZeroTier network after machine is rebooted. The ZeroTier service does not start despite being marked as enabled. This issue isn't limited to ZeroTier. The same behavior is observed with another third party service. 

**To Reproduce**
1. Be running Windows 10 1809 (I've observed this on earlier 1809 Insider builds as well)
2. Install ZeroTier One client and join network and authorize device. Set ZeroTier One client to start with Windows.
3. ZeroTier One client will be fully functional - can access resources via ZeroTier network, ZeroTier Windows service will be running.
4. Reboot computer
5. Log back into Windows.
6. Observe ZeroTier One client will show node ID as unknown. ZeroTier service will not be running, still shows as automatic. 
7. Exit ZeroTier One client. Start ZeroTier service, start ZeroTier One client, device re-joins ZeroTier network.

**Expected behavior**
After reboot, ZeroTier One client should be running (with option to start with Windows enabled) along with the ZeroTier service.

**Desktop (please complete the following information):**
 - OS: Windows
 - OS/Distribution Version: 10 Professional 1809 (Build 17758.1)
 - ZeroTier Version 1.2.12
 - Hardware Lenovo ThinkCentre

**Additional context**
I'm running ZeroTier on a home network. I have other Windows 10 Professional devices joined to the same network, running the same client version. When these devices reboot, the ZeroTier One client works as expected. 

Similar behavior has been observed on Windows Server 2016, although it's more random. Sometimes the service starts as expected, other times after a reboot the service will not start automatically.

I have not seen any errors in the Event Viewer related to this issue.

I figured I would file a bug report about this now since Windows 10 1809 is expected out in about a months time or sooner.

**Comment by adamierymenko** [comment]
Merging with #849 since this is likely related -- we need to do a bit more Windows testing before the next release and will include this with #849 test/fix

**Comment by smallworld-network-wupeng** [comment]
me too
