### ISSUE TITLE
Display IPv6 addresses using condensed notation

### ISSUE THREAD

**Issue by darkain** [zerotier/ZeroTierOne#850]
Right now IPv6 addressed are displayed using their long-form notation, which takes up needless additional space on smaller console windows.

Example:
```
root@router-1:~ # zerotier-cli listpeers
...
200 listpeers e4da7455b2 2001:41d0:0001:4982:0000:0000:0000:0001/52203;7653;7653 3809 1.2.5 LEAF
```

That address should be condensed down to 2001:41d0:1:4982::1 - a 20 character reduction, making it fit on a 80 character width terminal.

Also, yes, I'm aware that not all addresses can be condensed, but this is common enough that it helps readability.

**Comment by glimberg** [comment]
We happily accept pull requests on the `dev` branch

**Comment by darkain** [comment]
When I get some time, I'll look into this. Right now, still working on getting various FreeBSD/ARM builds going!

**Comment by darkain** [comment]
Just glancing over the IPv6 string handling routines, I've found some bugs in them too where it'll parse some addresses wrong. Once I'm home from work tonight and on my free time, I'll put together a patch that handles both generating and parsing shorthand IPv6 notation.

**Comment by adamierymenko** [comment]
Initially it was done for portability and for small devices. We could use them but haven't needed to change.

**Comment by adamierymenko** [comment]
There was a goal of keeping any OS/platform specific functions out of the core.

**Comment by adamierymenko** [comment]
The core in particular is extremely dependency-phobic.

**Comment by darkain** [comment]
The reason I ask is because there is some bugs in your implementation. Also, the required dependencies are already part of your core, as seen here: https://github.com/zerotier/ZeroTierOne/blob/master/include/ZeroTierOne.h#L43

inet functions are pretty standard across the board in all OSes and IP implementations. Your code is already using the AF_INET/AF_INET6 defines, just not the inet_ functions.

Would you be opposed to a PR to switch these string functions over to use the provided standard ones?

**Comment by adamierymenko** [comment]
Go for it. We can always use our own if we need to port to some kind of tiny embedded device without these functions.

**Comment by adamierymenko** [comment]
Merged
