### ISSUE TITLE
In the Central & Controller API: 64-bit ints used in JSON

### ISSUE THREAD

**Issue by gdamore** [zerotier/ZeroTierOne#854]
The JSON API for Central and the Controller uses integers that are larger than 53 bits of precision for timestamps.  Unfortunately, in many languages and libraries, this means that these values will lose the low order bits of precision, because many libraries (and JavaScript itself) just use 64-bit floats for these values.  So, for example, the current values on my system are 56 bits wide, which means that the low order 3 bits are lost.

Really the only "safe" way to deal with this is to provide an alternate form of representation.  One option is to represent these as a string.  Another option is to break the value up (often into high and low 32-bit dword values.)

Right now this affects my ability to use these with the JavaScript library I've chosen (cJSON).  I will probably need to choose a different cJSON library for this, but the problem will affect others, and especially JavaScript users.

**Comment by gdamore** [comment]
@janjaapbos Filed at your request.

**Comment by gdamore** [comment]
Hmm... looking again maybe I miscounted bits badly.  JavaScript numbers for milliseconds from the epoch (1/1/1970) are 41ish bits today.

**Comment by glimberg** [comment]
We have June 5, 2255 until this is a problem :)
