### ISSUE TITLE
Diagnostic improvements / diagnostic system

### ISSUE THREAD

**Issue by adamierymenko** [zerotier/ZeroTierOne#86]
An automated diagnostic system will eventually be needed. It should be able to test basic connectivity and examine OS configuration to determine if there are any obvious problems like:

(1) Problem with IP configuration

(2) Conflicts in routing table

(3) Firewall rules preventing communication

(4) Network interface error or installation problem

Note that this shouldn't be like Microsoft's diagnostics wizards in that it should actually work or at least tell the user something useful.

**Comment by adamierymenko** [comment]
Closing since this is coming and the groundwork is already laid in the form of CIRCUIT_TEST, etc... watch this space.

**Comment by heri16** [comment]
Hopefully this feature is implemented asap, as currently having lots of path selection and packet-loss problems which we cannot report.
