### ISSUE TITLE
DPDK or packet processing performance (10Gb)

### ISSUE THREAD

**Issue by jothoma1** [zerotier/ZeroTierOne#861]
**Describe the solution you'd like**
Do you plan to support DPDK for high performance ? We have currently multisite in a MAN with 10Gb interconnect. We would like to be able to handle this sort of traffic.

Currently we are looking for ucpe white box like DELL VEP 4600 or Lanner NCA-2510C or something else but we would like to be able to have efficient 10Gb with ability to host something else on the box.

**Comment by adamierymenko** [comment]
We don't have any immediate plans but it's certainly something that could be done in the future. Right now it probably wouldn't be prioritized unless someone wanted to fund it.

**Comment by adamierymenko** [comment]
Closing since this isn't on our table right now and would likely only be done for an enterprise customer.
