### ISSUE TITLE
Unable to connect to a Moon with multiple IPs (one not assigned for the moon)

### ISSUE THREAD

**Issue by AlexisTM** [zerotier/ZeroTierOne#862]
Hey,

I would like to setup a moon which has multiple IPs:
- 192.168.1.51/9993
- 10.1.1.51/9993

Both IPs are pointing towards the same host but in some cases only one is valid.

When I use the moon with one of the two IP unavailable, the other hosts are not connecting. 

**Working configuration:**
```json
  "roots": [
   {
    "identity": "1234567890:0:123..",
    "stableEndpoints": [
     "192.168.1.51/9993"
    ]
   }
  ],
```

**Non working configuration (10.1.1.51 is not available for both the moon and the planet):**
```json
  "roots": [
   {
    "identity": "1234567890:0:123..",
    "stableEndpoints": [
     "10.1.1.51/9993",
     "192.168.1.51/9993"
    ]
   }
  ],
```

**Comment by AlexisTM** [comment]
Should I try with the same identity as two different root?

```js
  "roots": [
   {
    "identity": "1234567890:0:123..",
    "stableEndpoints": [
     "192.168.1.51/9993"
    ]
   },
   {
    "identity": "1234567890:0:123..",
    "stableEndpoints": [
     "10.1.1.51/9993"
    ]
   }
  ],
```

**Comment by AlexisTM** [comment]
Issue: 

With 192.168.5.51 the only moon configured:
Every system can ping 192.168.5.51.
Every system has the same moon configuration.

51 and 130 can ping each other on Zerotier network
42, 131, 132 and 133 can ping each other on Zerotier network

These two groups cannot ping the other group while they are all on the same Zerotier network.

**Comment by fakuivan** [comment]
@AlexisTM why did you close this? Were you able to find a solution?

**Comment by AlexisTM** [comment]
This was closed as stale (no reply) and we, therefore, moved away from the moons. This was 3 years ago.
