### ISSUE TITLE
In Linux zerotier-one.service can't be stopped, and drives one core to 100%

### ISSUE THREAD

**Issue by KyungWon-Park** [zerotier/ZeroTierOne#863]
**Describe the bug**

 When I try to stop zerotier-one daemon, it won't be stopped and drives one core to 100% loaded state.

**To Reproduce**

OS: Arch Linux
Zerotier-One: Installed by "sudo pacman -S zerotier-one" 

0. OS Shutdown when zerotier-one.service daemon is active
While shutting down, LINUX waits for zerotier to shutdown but it won't.
OS shuts down anyway after 1min 30s of wait for zerotier.
I can hear loud fan noise due to high usage of CPU

1. sudo systemctl stop zerotier-one.service
This command hangs indefinitely and one core of CPU skyrockets to 100%.
Core load was checked by htop

**Expected behavior**
Gracefully shutdown without stressing CPU

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - OS/Distribution Version: Updated to latest
 - ZeroTier Version: 1.2.12-1 (In Arch Linux repo)
 - Hardware: ASUS ROG Laptop
 
**Additional context**
- ZeroTier Network Configuration: Did not join any network
- Firewall Config: I use iptables, only established connections and dns are allowed inward
- General Network Environment: Laptop is connected to my home wifi

**Comment by laduke** [comment]
hrm, 
It worked very quickly; I just tried `systemctl restart zerotier-one` (remotely) on Arch with 1.2.12, but I'm joined to a network. 

Is your iptables config blocking 9993/UDP ? Probably unrelated, but you'll only get relayed TCP connections, not direct peer to peer, if zerotier can't talk over UDP.

**Comment by tmathews** [comment]
Have you tried this? https://github.com/zerotier/ZeroTierOne/issues/738#issuecomment-418460657

**Comment by KyungWon-Park** [comment]
Thank you
That fixed my issue
