### ISSUE TITLE
[Question] Do network controllers need to be reachable on port 9993 by roots or leafs? 

### ISSUE THREAD

**Issue by albertdb** [zerotier/ZeroTierOne#866]
Hi,

I have an easy question whose answer is unclear to me after reading docs. Let me put you in context:

I plan to deploy my own ZeroTier network controller. One of the possibilities is to deploy it in an environment that manages its availability for me, but doesn't allow me to expose (and to be reachable publicly on) port 9993.

So, do network controllers need to be reachable on port 9993 by roots or leafs? Or do they perform NAT punching like any other ZeroTier node and, in worst case get traffic relayed from roots?

Thank you very much.

**Comment by laduke** [comment]
Hi, 
Controllers are just regular nodes. They aren't usually joined to networks, but they do the same hole punching, discovery, etc...

**Comment by laduke** [comment]
re-open if you like, or join us in the chat.
