### ISSUE TITLE
OSX Mojave (10.14) IPv6 fragmentation issue

### ISSUE THREAD

**Issue by adamierymenko** [zerotier/ZeroTierOne#870]
MacOS Mojave (10.14) seems to exhibit some extremely strange MTU/fragmentation behavior on ZeroTier networks. It can cause IPv6 TCP connections to freeze. This issue doesn't appear on earlier MacOS, and nothing about ZeroTier or its Mac driver has changed.

We're investigating, but we're also tempted to wait for MacOS 10.14.1 to see if this is a MacOS bug that will get fixed. It doesn't happen on regular wired/wireless networks though, which causes us to think it might be an incompatibility with our kext.

We are researching two new avenues for kext-free tap networking on MacOS that have recently become available in the Darwin kernel. We may switch to one of these.

**Comment by adamierymenko** [comment]
This should be fixed by the removal of the kext dependency, but testing is needed before an interim release.

**Comment by adamierymenko** [comment]
We can confirm that the new no-kext-required code is stable and resolves this issue. Next major release will drop the OSX kext! Note that this might limit support for ancient MacOS versions, but we know support for feth goes back at least two major releases.

**Comment by EskelCz** [comment]
I just upgraded to Mojave and my Zerotier started acting up. It says it's connected but my http server under specific port is not reachable, as it was before. Is it possible it's related to this issue? My system is the only thing that changed.

When will this update hit? Also I can't find version number in my mac client app.
Thanks

**Comment by ashleeyoung** [comment]
How can we use this fix? Install the Mac app; checkout and compile this code; drag the build into Applications; delete tap.kext from /Library/Applications Support/Zerotier/One? 

When I do that, all of my networks show up as unauthorized. If I leave tap.kext in place, then they're authenticated, but I can't connect to IPv6 addresses still.

**Comment by laduke** [comment]
compiling will make a `zerotier-one`, put that in /Library/Applications Support/Zerotier/One after stopping the service

**Comment by ashleeyoung** [comment]
Thank you!!! It's working great again!

**Comment by adamierymenko** [comment]
Fixed in `dev`
