### ISSUE TITLE
Windows logout

### ISSUE THREAD

**Issue by nkay08** [zerotier/ZeroTierOne#873]
I have a friend who forgot his login e-mail an therefore cannot use ZeroTier central.
He made a new account and can login fine with that, but the windows client is still logged in as his old profile.
Is there a way to reset the windows client, so he can login with his new credentials and then join the network again?

**Comment by nkay08** [comment]
Found the necessary config files in C:\ProgramData\ZeroTier

**Comment by laduke** [comment]
@nkay08 FYI the client is linked to central with the API Token field in the preferences. You can create a token on the account page then paste it in there.
