### ISSUE TITLE
Suddenly can not ping anything except own ip

### ISSUE THREAD

**Issue by Shark1nat0r** [zerotier/ZeroTierOne#876]
**Alternative, faster ways to get help**
If you have just started using ZeroTier, here are some places to get help:
- my.zerotier.com has a _Community_ tab. It's a live chat with other users and the developers. 
- [ZeroTier Knowledge Base](https://support.zerotier.com/knowledgebase.php?s=MQ__)
- www.zerotier.com has a Contact Us button
- email contact@zerotier.com

**Describe the bug**
I created a simple network with 2 computers and 2 Android phones. These devices are connect to three different networks.
1: Computer A
2: Computer B
3: Android A and Android B
If I'm on Computer A I can only ping Computer A, if I am on Android B I can only ping Android B.

Strangely I was able to ping a computer of a friend a few days ago.

**To Reproduce**
1. Create a simple Network with default settings
2. Install zerotier-one on Computer and Android
3. Connect to Network and authenticate
4. Try to ping each other
5. See error

**Expected behavior**
As shown in the YouTube Demo, I should be able to ping each device with default settings.

**Desktop A/B (please complete the following information):**
 - OS: Windows 10
 - ZeroTier Version 1.2.12

 
**Smartphone A (please complete the following information):**
 - Device: Samsung Galaxy S5
 - OS: Android 6.0
 - Version 1.2.12

**Smartphone B (please complete the following information):**
 - Device: Samsung Galaxy S9
 - OS: Android 8.0
 - Version 1.2.12

**Additional context**
- ZeroTier Network Configuration: default
- Router Config: no access
- Firewall Config (try turning the firewall off): did not help (Androids couldnt ping each other too)
- General Network Environment: Home

**Comment by bankjaneo** [comment]
Same problem here. 4 devices cannot ping each other.

1. macOS ZeroTier 1.2.12
2. Windows 10 ZeroTier 1.2.12
3. iPad iOS 12.1 ZeroTier 1.2.12
4. iPhone iOS 12.1 ZeroTier 1.2.12

**Comment by flawiddsouza** [comment]
I have the same issue as well.

**Comment by huweijia** [comment]
same problem

**Comment by Shark1nat0r** [comment]
For computers (Windows) it seems to be a problem with new networks. I could join the Earth test network from ZeroTier and ping several other devices. I still can't ping other devices in my own network.
For mobiles (Android) I can't even ping devices in the Earth test network I could ping with my computer. They seem to be broken completely.

**Comment by jtrott** [comment]
Add a space to the flow rules then save. Seems to work around the issue.

**Comment by Shark1nat0r** [comment]
OMG jtrott you are my Hero!! Can confirm this is working for my computers and my android phones!

**Comment by bankjaneo** [comment]
jtrott solution works! I confirm too.

**Comment by darkorigins** [comment]
Where are people adding spaces?  Have tried several places and still not working :-(

**Comment by Shark1nat0r** [comment]
empty line under accept; in Flow rules then save changes

**Comment by darkorigins** [comment]
@Shark1nat0r  Thanks. Had one blank by default, added another. Unfortunately still now joy.  

Diags: Reboot of iPad, waited 2 mins on connect, app showing as connected as is ZT Central, but [VPN] symbol never arrives on iPad toolbar and cannot ping in/out.

**Comment by Shark1nat0r** [comment]
Unfortunately I have no Apple device to test it. But I had to reconnect my Android phone too for it to work. But the VPN symbol is showing on my device.

**Comment by bankjaneo** [comment]
@darkorigins If [VPN] symbol is not showing then ZT should not working properly on iPad. Have you try delete VPN profile and re-add it again?

My iPad and iPhone is working fine now with @jtrott trick.

**Comment by darkorigins** [comment]
@bankjaneo Connect time in ZT status increases but No [VPN] symbol, and it's not network connection.   

I've tried deleting and re-adding. I've even tried creating a new ZT network and joining that.  Occasionally it connects fully but mostly it doesn't.

Last lines of my flow rules are;
<snip>
accept;


<snip>

**Comment by unixfox** [comment]
This is a serious bug because a newly created network by default doesn't work and need the dirty fix of @jtrott to work.

**Comment by bankjaneo** [comment]
@darkorigins does the iPad get the IP from ZT network? If yes, have you try pinging between two other devices that are not iPad? What’s the result?

My flow rule is default one except added a space on the line 23 then save.

**Comment by darkorigins** [comment]
@bankjaneo Yes the iPad gets the network name, ip address, etc just not the network layer.  So ping to/from iPad/Server does nothing. Ping between two Ubuntu servers on the same ZT network is fine.

The flow rules I'm looking at currently are a copy'n'paste from a new network, empty line on lines 23,32,43,46. Where an empty line is completely empty, no spaces of other invisible chars. 

After some more digging this appears to be based around our use of 'custom dns servers' in the config.  If I re-create the network on the client without using custom dns it does eventually connect (anywhere from 30sec to  3mins to get [VPN]).  Tested with and without 'allow default route'. As soon as custom dns servers are set it fails to connect.

**Comment by LFlare** [comment]
Not certain if it pertains to the same issue, as I am running my own network controller, but I seem to be experiencing this issue at random also.

**Comment by laduke** [comment]
Closing because the original issue is gone
for the iOS / DNS issue see #800 and #901
