### ISSUE TITLE
ZT-One Controller "active" endpoint is not working

### ISSUE THREAD

**Issue by paweljacewicz** [zerotier/ZeroTierOne#880]
Hi!

I'm using ZeroTier One 1.2.12 as a controller for my small network and I cannot get a list of active members of the network using the api call as described on [this page](https://github.com/zerotier/ZeroTierOne/tree/master/controller#controllernetworknetwork-idactive).

**To Reproduce**
```
curl -v -XGET --header "X-ZT1-Auth: $(cat /var/lib/zerotier-one/authtoken.secret)" http://localhost:9993/controller/network/XXXXXXXXXXXXXXXX/active

* About to connect() to localhost port 9993 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 9993 (#0)
> GET /controller/network/XXXXXXXXXXXXXXXX/active HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:9993
> Accept: */*
> X-ZT1-Auth: XXXXXXXXXXXXXXXX
>
< HTTP/1.1 404 Not Found
< Cache-Control: no-cache
< Pragma: no-cache
< Content-Type: application/json
< Content-Length: 2
< Connection: close
<
* Closing connection 0
{}
```

**Expected behavior**
A JSON object with list of active ZT nodes.

**Desktop (please complete the following information):**
 - OS: Linux
 - Centos 7.5.1804
 - ZeroTier Version 1.2.12
 - ESXi VM
 
**Additional context**
API call made on Linux machine with curl where the controller is running.

**Comment by laduke** [comment]
I had deleted the API docs for `active` after looking at a different issue. 
Now I'm not sure if it's coming back or not. 

(if so, shouldn't it be /network/{id}/member/active or /network/{id}/member?active=1 ?)
