### ISSUE TITLE
Moon does not support DDNS

### ISSUE THREAD

**Issue by lucktu** [zerotier/ZeroTierOne#881]
As moon, it must use a fixed IP？

**Comment by adamierymenko** [comment]
Yes, any stationary anchor point must have a permanent IP. A cheap $5/month VPS will do just fine.

**Comment by lucktu** [comment]
Give me five dollars every month please！ ^_^

**Comment by lucktu** [comment]
> Yes, any stationary anchor point must have a permanent IP. A cheap $5/month VPS will do just fine.

Give me five dollars every month please！ ^_^

**Comment by lucktu** [comment]
> Yes, any stationary anchor point must have a permanent IP. A cheap $5/month VPS will do just fine.

Or, can you put a root server in China?
