### ISSUE TITLE
Some weird problem with moons.

### ISSUE THREAD

**Issue by kblackcn** [zerotier/ZeroTierOne#882]
**Describe the bug**
After the recent infrastructure changing, my two moon went offline with no reason. At the same time, two devices orbiting two moons were lost too. (They all have the Internet Connection) All 4 devices were shown as "offline" on zerotier Central. Creating a new network and letting them join in didn't help. 
After I deoribt one of the two moons from themselves, its connection is restored and other two devices goes back, But the other moon doesn't come back until I again deorbit it from themselves.
Moon configuration and network environment haven't been changed during the whole process. So, I think there might be some bugs when zerotier dealing with moon.

**To Reproduce**
Don't know the exact reason whey they fell into this problem.

**Expected behavior**
Moons shouldn't go offline in this situation anyway.
Leaves shouldn't go completely offline just because the moon is down.

All my servers run Ubuntu Server 16.04.

**Comment by adamierymenko** [comment]
I am labeling this as bug/wontfix because the whole planet/moon paradigm is going to get totally overhauled in the near future in favor of something simpler and more straightforward. The existing scheme is over-engineered and generally overly complex.

**Comment by paweljacewicz** [comment]
Hi!

@adamierymenko 
With current approach with planet and moons it is possible to create your own, private infrastructure, totally separate from the public one. I'm actually testing it with a planet file compiled by myself and it seems to work flawlessly. 
You mentioned that this approach will be changed in the near future. Will there still be a possibility to create such private infrastructure without relying on the public roots?

Thanks!
PJ

**Comment by adamierymenko** [comment]
Yes and yes. It's going to die and the replacement is much better.
