### ISSUE TITLE
Linux service stop permissions problem

### ISSUE THREAD

**Issue by coladict** [zerotier/ZeroTierOne#883]
Calling `service zerotier-one stop` on our Raspbian (and probably other) system takes far too long, because it waits on `/bin/systemd-tty-ask-password-agent` with no screen or prompt anywhere to answer it.

Workaround is to add the following line with `visudo`:

    zerotier-one ALL=NOPASSWD:/sbin/ip

Perhaps during the package installation, it should add a file in `/etc/sudoers.d` to address this problem.

**Comment by adamierymenko** [comment]
This might be fixed in dev, but will check.
