### ISSUE TITLE
ZeroTier doesn't receive broadcast data on Android

### ISSUE THREAD

**Issue by Krush206** [zerotier/ZeroTierOne#884]
Some games on Android use broadcast to announce host rooms. The broadcast is sent by the host but the rooms are not visible to client nodes. I have tried to route the "everyone's broadcast address" (255.255.255.255) and multicast address (224.0.0.0/4) but still no luck. Routing those addresses on Hamachi VPN or Tinc App works fine, the clients can see the broadcast announcement from the host, but it doesn't seems to work on ZeroTier

**Comment by adamierymenko** [comment]
Broadcast/multicast on Android is limited by Android OS issues. Apps that do not bind specifically to the ZeroTier device (generally tun0 on Android) will not receive multicasts or broadcasts, and I'm not sure that wildcard-bound multicast/broadcast sockets will receive them.

We *technically* support multicast and broadcast on Android, but we can't do things outside what the OS permits. Its behavior is different from a desktop or server OS.

**Comment by Krush206** [comment]
Well, that's a bit weird though. Tinc App uses TUN (tun1) adapter too but broadcast/multicast works fine on it. I can see the broadcast/multicast messages being sent to the ZeroTier adapter but I can't see the messages being delivered to the clients. Also, ZeroTier uses 2 adapters while connected in a network (tun0 and tun0:1)

Tinc App: http://bwass.org/bucket/IMG_20181128_150228.jpg
ZeroTier: http://bwass.org/bucket/IMG_20181128_150255.jpg
