### ISSUE TITLE
make it easier to get IP4/IP6 details out of  `zt-cli info`

### ISSUE THREAD

**Issue by dch** [zerotier/ZeroTierOne#887]
**Is your feature request related to a problem? Please describe.**

While automating zt usage, I have no easy way to split out the zerotier-specific IPv4 and IPv6 addresses obtained from the command line tool, to update our DNS and store in configuration management systems. This comes up in multiple places, where we need to teach some tool or system how to find the appropriate ZT IP to bind a daemon to, or to open a connection to.

**Describe the solution you'd like**

In a single command, without needing jq or other parsing, retrieve IPv6 address(es) assigned to this node. Ditto for IPv4 for feature completeness even though I don't use it.

```
# zerotier-cli get deadcafe ipv6 | head -1
dead:cafe:0000:0000:0000:0000:0000:0001
# zerotier-cli get deadcafe ipv4
123.45.67.89
123.45.67.90
123.45.67.91
...
```

Bonus points:

- documenting the parameters that `zt-cli get|set` can take somewhere. I've found name,portdevicename,status so far, but nothing to do with addresses
- ensure that the same output is available in -j form for completeness
- something that yields the network+host part of the IP6PLANE address so one can simply append the 
jail/container-specific suffix

**Describe alternatives you've considered**

Currently I hack around this with jq and other work-arounds but it's ugly - in ansible:

```
{{ hostvars[inventory_hostname]['ansible_' ~ net.zerotier.interface ]['ipv6'][1].address }}
```

Hacking off the last quartet is done with further template madness to allow later on appending a quartet (0000 - 0fff) for a container-specific ip6 address on each physical server

And carefully abusing the join command:

```
sudo zerotier-cli -j join deadcafe |egrep -o '[0123456789abcdef:]{20,}'
dead:cafe:0000:0000:0000:0000:0000:0001
```

Neither of these is particularly robust against changes.

**Additional context**

**Comment by joseph-henry** [comment]
Thanks for the suggestion @dch. We'll be introducing something like the following, let me know if there's anything missing:

```
$ zerotier-cli get e5cd7a9e1caec84b ip4
11.7.7.97
11.7.7.98
11.7.7.99
11.7.7.15
$ zerotier-cli get e5cd7a9e1caec84b ip6
fde5:cd7a:9e1c:ae19:4f99:93f5:5311:dff0
fcf9:e363:d1f5:5311:dff0:0000:0000:0001
$ zerotier-cli get e5cd7a9e1caec84b 6prefix
fcf9:e363:d1f5:5311:dff0
```

**Comment by joseph-henry** [comment]
Changes are now in the `dev` branch. Available commands are `ip`, `ip4`, `ip6`, `ip6plane`, `ip6prefix`. Additionally `get/set` is now briefly described in `zerotier-cli -h`.

**Comment by dch** [comment]
thanks! I'm unable to compile this without https://github.com/zerotier/ZeroTierOne/pull/952 but otherwise so much goodness in this commit. many thanks!

if you can make a tag then I'll check it against the other supported architectures we have.

**Comment by joseph-henry** [comment]
Thanks, I've instead commented out the offending code for #952, I think you should be able to build without issue now.

**Comment by dch** [comment]
ok works brilliantly! Is it possible to add the `ip6prefix` to `zerotier-cli -j listnetworks`... as well? i.e. also in the json output, for consistency?
