### ISSUE TITLE
How ZeroTier uses the original gateway when added global managed route on MacOS?

### ISSUE THREAD

**Issue by Chenyao2333** [zerotier/ZeroTierOne#888]
I use managed route "0.0.0.0/0 via 10.10.10.1" (zt addr), so that ZeroTier works like a traditional VPN. 

But I am curious how ZeroTier bypass its traffic, and use the original gateway? How Zerotier avoids route loop?

**Comment by sbilly** [comment]
I think its duplicate of #178 

https://github.com/zerotier/ZeroTierOne/issues/178#issuecomment-118082584

**Comment by adamierymenko** [comment]
It binds directly to the interface and also uses the route bifurcation hack common to other full tunnel VPNs.
