### ISSUE TITLE
Can't connect to Linux box locally after installation of Zerotier.

### ISSUE THREAD

**Issue by SuoaJ** [zerotier/ZeroTierOne#890]
I installed Armbian on an Odroid-XU4. Immedialtey after the OS installation, I installed Zerotier using this:
curl -s https://install.zerotier.com/ | sudo bash

Then I joined my network using this:
sudo zerotier-cli join <netowrk id>

As soon a I joined the network, I lost local network connectivity to my Armbian box. I know the box is online because I can connect remotely to it from another Zerotier client on the same network. 

The problem is Zerotier seems to add a route to the routing table which prevent local connections.

If I delete this route, using:
route del -net 192.168.31.0 gw 192.168.192.57 netmask 255.255.255.0 dev ztiah5owb5,

   then I am able to connect locally to the box. But as son at the box is rebooted, the route appears again blocking access locally.

I've spent two days trying to fix this without any success.  Initially, I thought it was an issue with Network-Manager(nmcli) which I have disabled but the issue still persists. Can anyone help?

**Comment by laduke** [comment]
Hello,
that's odd... 

What is the LAN subnet? What managed routes does the zerotier network have?

**Comment by SuoaJ** [comment]
Thanks for the reply. Here is my routing table(below). 

root@odroidxu4:~# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.31.1    0.0.0.0         UG    0      0        0 enx001e06325aeb
169.254.0.0     0.0.0.0         255.255.0.0     U     1000   0        0 enx001e06325aeb
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
192.168.31.0    192.168.192.57  255.255.255.0   UG    0      0        0 ztiah5owb5
192.168.192.0   0.0.0.0         255.255.255.0   U     0      0        0 ztiah5owb5

I think the problem is caused by the 4th entry(by ZeroTier):

192.168.31.0    192.168.192.57  255.255.255.0   UG    0      0        0 ztiah5owb5

If it is remove, everything works properly. But it reappears after the system is rebooted.

**Comment by laduke** [comment]
Did you add a Managed Route to your network?

**Comment by SuoaJ** [comment]
No, I have not added any routes. I installed Armbian, then installed Zerotier. All routing is done by the OS and Zerotier.

**Comment by laduke** [comment]
My routes look like this on linux

```
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.82.1    0.0.0.0         UG    204    0        0 enp4s0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.18.0.0      0.0.0.0         255.255.0.0     U     0      0        0 br-a4dee27ff984
192.168.195.0   0.0.0.0         255.255.255.0   U     0      0        0 ztc3q5jik6
```

I don't understand why yours' has two entries for ztiah5owb5.

**Comment by SuoaJ** [comment]
Oh yes, indeed! I have a managed route. 

192.168.192.0/24    (LAN)
192.168.31.0/24      192.168.192.57

Completely forgot that. Never realised this could be an issue. Wow. Spent over two days trying to fix this. Let me remove it and see what happens. Will report back. Thanks.

**Comment by SuoaJ** [comment]
Everything works fine now. It was the managed route causing the issue. Thanks a million.
