### ISSUE TITLE
Packet loss problem.

### ISSUE THREAD

**Issue by Bigbossbro08** [zerotier/ZeroTierOne#891]
I am using ZeroTier and I have connected to another PC. It seems I am having a lot of packet loss. I tried testing in the Virtual Machine changed my ip location to a various location. But the problem still remains... Is this a problem related setting up IP or what?
![Packet loss problem picture no.1](https://user-images.githubusercontent.com/21245896/49494391-bd9a1580-f889-11e8-9c6a-d1ba0b4ffeff.png)
![Packet loss problem picture no.2](https://user-images.githubusercontent.com/21245896/49494406-c68ae700-f889-11e8-9d03-45d4bda948b2.png)
![Ping to the ZeroTier website](https://user-images.githubusercontent.com/21245896/49494490-0651ce80-f88a-11e8-9c73-0335ed419462.png)

**Comment by laduke** [comment]
Hey, it's probably relaying through our last-resort relay servers. 

https://zerotier.atlassian.net/wiki/spaces/SD/pages/360465/Connectivity+Troubleshooting+and+Configuration+Recommendations

https://zerotier.atlassian.net/wiki/spaces/SD/pages/6815768/Router+Configuration+Tips

**Comment by laduke** [comment]
Keep commenting if you have any questions.
