### ISSUE TITLE
Windows Adapter/Interface Name Issue?

### ISSUE THREAD

**Issue by MrChris79** [zerotier/ZeroTierOne#892]
**Describe the bug**
I scriptomatically manage my ZeroTier connection status in Windows 10 x64. An issue I found or am having is that the name of the ZeroTier adapter/interface name as windows see's it internally does not match with what I see visually in Windows. For example. If I look in the Network Connection GUI in windows it shows the Adapter name as "ZeroTier One [1234567890123456]" for example, but if I do ipconfig in windows it shows ""Ethernet 6" (the 6 is dynamic and differs from PC to PC) for example. Windows seems to ignore the name "ZeroTier One [1234567890123456]" internally and instead only reference it by the name "Ethernet 6" for example. This makes using windows to manage the connection status (ie. release/renew the IP etc..) very difficult. Im not sure if this is a bug or an undocumented feature or what.  

**To Reproduce**
1. Look at Windows Network Connection folder to get ZT Adapter/Interface Name
2. Then type open a command prompt and type 'netsh interface ip show config' or 'ipconfig' to get the adapter/interface name.
3. See a difference in the name?

**Expected behavior**
The name of the Adapter or Interface should be the same?

**Screenshots**
If applicable, add screenshots or console output to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 (1809)
 - ZeroTier Version 1.2.12

**Comment by sh-jeff** [comment]
Pretty sure this is a Windows problem, just like the other issue describes.
A partial workaround I can think of for this is to get the ifIndex of an adapter with nlmtu of 2800. AFAIK ZT is the only thing that uses that MTU.
`get-netipinterface | where-object {$_.nlmtu -eq 2800}`

**Comment by KBrownConsulting** [comment]
I too would like to see this fixed. I've discovered that if you rename the adapter (simply right click on the adapter and choose rename and then make any change to the name) the names sync up. Maybe one solution would be to have ZT create the adapter with a generic name & then after it adds it, rename it to the desired name.

**Comment by glimberg** [comment]
Just fixed this in the `dev` branch https://github.com/zerotier/ZeroTierOne/commit/d43e810ecbcb264e57d2b52138a3729b7667388a

Dug deep into windows API hell to figure out how to get it done, because naturally, Windows has 2 different places in the Registry where these values are set. One of which can't even be read from/written to by mere mortals (or even applications running as Administrator).

Example `ipconfig` output now:

```
Ethernet adapter ZeroTier One [8056c2e21cXXXXXX]:

   Connection-specific DNS Suffix  . :
   IPv6 Address. . . . . . . . . . . : fd80:xxxx:xxxx:xxxx:xx99:93xx:xxxx:xxxx
   Link-local IPv6 Address . . . . . : fe80::xxxx:xxxx:xxxx:xxxx%36
   IPv4 Address. . . . . . . . . . . : 1.2.3.4
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 25.255.255.254
```
