### ISSUE TITLE
Maximum moons limit

### ISSUE THREAD

**Issue by gordon-zhao** [zerotier/ZeroTierOne#893]
**Describe the bug**
The zerotier-idtool generate a broken signed .moon file if the input moon.json has more than 4 moons under the "roots" key. The size of the signed .moon file for 5 moons remains the same as the one for 4 moons. (Exactly 582 Bytes)

**To Reproduce**
1. Run "zerotier-idtool initmoon identity.public >> moon.json"
2. In moon.json, define 4 moons under the "roots" key
3. Run "zerotier-idtool genmoon moon.json && mv 0000***.moon moons.d/"
4. Restart zerotier-one service; Can see correct output from "zerotier-cli listmoons"
5. Go back to the moon.json, append 1 moon under the ""roots" key
6. Run "zerotier-idtool genmoon moon.json && mv 0000***.moon moons.d/"
7. Restart zerotier-one service
8. Run "zerotier-cli listmoons"; Only Sees "[]" as the output, which means the moon file isn't loaded. 

**Expected behavior**
The "zerotier-idtool" should be able to sign the moon.json with more than 4 moons. 
If there is a hard limit on the file size, I would like to see the program throwing out errors, not just keeping silence and ignore it. 

**Screenshots**
```
[root@### zerotier-one]# zerotier-idtool genmoon moon.json
wrote 00000095*******4.moon (signed world with timestamp 1544169517795)
[root@### zerotier-one]# mv 00000095*******4.moon moons.d/
[root@### zerotier-one]# service zerotier-one restart
Redirecting to /bin/systemctl restart zerotier-one.service
[root@### zerotier-one]# zerotier-cli listmoons
[
 {
  "id": "00000095*******4",
  "roots": [
      /*the identity of 4 moons*/
   ]
 }
]

(After adding one more moon in the moon.json)
[root@### zerotier-one]# zerotier-idtool genmoon moon.json
wrote 00000095*******4.moon (signed world with timestamp 1544169579589)
[root@### zerotier-one]# mv 00000095*******4.moon moons.d/
mv: overwrite ‘moons.d/00000095*******4.moon’? y
[root@### zerotier-one]# service zerotier-one restart
Redirecting to /bin/systemctl restart zerotier-one.service
[root@### zerotier-one]# zerotier-cli listmoons
[]
```

**Desktop (please complete the following information):**
 - OS: CentOS 7
 - Hardware: VPS on Linode
 - Version: Zerotier-One 1.2.12

**Comment by adamierymenko** [comment]
Closing because that entire moon/planet system is going to die in favor of something much better.

**Comment by gwh-cpnet** [comment]
I run into this problem too. Even with zerotier v1.4.2 or v1.4.4, I still believe moon very helpful. If I got more than 4 moons, all moons would become `LEAF`. That is quite confusing.

**Comment by gwh-cpnet** [comment]
Especially in the case of building a global private network, with the latest v1.4.4, a cloud-deploy node would not find its peers on the other side of the earth without moons' help.

**Comment by glimberg** [comment]
@gwh-cpnet  4 is the maximum in the 1.x series and won't be changing.  This is all being changed in 2.x which is currently under development

**Comment by gwh-cpnet** [comment]
@glimberg Thanks for your reply. Maybe your solution to replace moons is deploying more planets all over the world. I see new planets get online now. And I think it is causing some glitches on my network. :)

**Comment by isakrubin** [comment]
Two years have passed, is there a workaround for adding more moons? Or an ETA for the 2.0 beta :)

**Comment by isakrubin** [comment]
Three years have passed, is there a workaround for adding more moons? Or an ETA for the 2.0 beta :)

**Comment by isakrubin** [comment]
Five  years have passed, is there a workaround for adding more moons? Or an ETA for the 2.0 beta :)
