### ISSUE TITLE
Access the computers on remote computer lan

### ISSUE THREAD

**Issue by helio58** [zerotier/ZeroTierOne#894]
Hi , new to zero tier . I m enjoying using it.
I have a question , maybe here is not the right place, I ask if isn't appropriate please remove.
Using computer A local lan 192.168.0.1  windows 7. Connect to remote lan 192.168.1.1 windows 10
Is possible to me when connect over internet access the other 2 computers in the windows 10 side?
Without using zero tier in all computers.
Thanks for this great application.

**Comment by laduke** [comment]
Hi!
You can add a managed route in the zerotier network settings at
my.zerotier.com. This will create a route on all the zerotier clients.
You'll might also have to add the opposite route to the 2 computers. And
turn on IP forwarding in Windows.

...If that doesn't make sense, post on the subreddit or in the community
chat. We try to keep the github issues for work on zerotier features and
bugs. thanks!

**Comment by helio58** [comment]
Thanks@laduke sorry I did not know about the subreddit once again thanks.
