### ISSUE TITLE
Zerotier ignores system proxy settings

### ISSUE THREAD

**Issue by alexforencich** [zerotier/ZeroTierOne#896]
**Describe the bug**
Zerotier refuses to use system proxy settings if direct internet access requires using a web proxy configured via http_proxy, https_proxy, etc.  Networks can be joined successfully, but zerotier-cli always reports the status as 'offline'.

Note that I am not expecting actual zerotier traffic to transit the web proxy, only the control connection so that peers can be discovered.  There are other nodes running zerotier on the same physical network that are joined to the same zerotier network that can directly connect to the internet and can also directly connect to the machines in question.  Once the node can establish a control connection through the proxy, direct peer-to-peer connections should be possible.  

**To Reproduce**
1. Run zerotier behind a web proxy

**Expected behavior**
zerotier should transition to 'online'.  

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.1
 - ZeroTier Version: 1.2.12
 - Hardware HP DL360p G8
 
**Additional context**
- General Network Environment: University campus

**Comment by adamierymenko** [comment]
Passing through a proxy is not supported and is not going to work too well. If we did support it it would be horrendously slow due to latency. You'd be making one HTTP request per packet, and the proxy would add its own latency.

I've seen software for tunneling VPNs over HTTP. You could set up a VPS somewhere cheap like Vultr or Digital Ocean, tunnel to it, and then run ZeroTier over that, but like I said it's going to be SLOOOOOOOOOOOW. :turtle:

**Comment by alexforencich** [comment]
I do not expect the traffic to go through the proxy.  I only expect the control connection to go through the proxy.  There are other machines that are visible over the network that can establish direct peer-to-peer connections, but the node in question never comes out of the 'offline' state so no connections are made.

**Comment by adamierymenko** [comment]
Local control of the service is via http to 127.0.0.1 but that's not ZeroTier traffic, just a control API.

**Comment by alexforencich** [comment]
Well, I guess I might have to use some other VPN software for this particular project, then.  But that is a use case to consider - nodes that can see other nodes, but can't directly access the internet.

**Comment by adamierymenko** [comment]
This can be done but right now it's a bit of a hassle. You have to run a local root, etc. We're planning some work in early 2019 to make this a lot easier as we have one large customer that uses this on air-gapped networks.

**Comment by bricolodu13** [comment]
Hello,

I have the very same request.
I'm using a Proxy from my phone (PdaNet HotSpot) and want the units that connect to this hotspot to be visible on ZeroTier.
**It's working fine on Windows Machines that run the PdaNet application script**
It's NOT working on Windows Machines that are connected to the Proxy without running the PdaNet application script although they can acces internet and the ZeroTier managment page
It's NOT working on Linux machines
I don't know what does the PdaNet application script that is not done in other case, but it looks it should be possible to set something somewhere to allow the connection...

**Comment by sabbiolino80** [comment]
@adamierymenko any news on that?

**Comment by MasterJubei** [comment]
Any update? I want to use this behind an http proxy since phone tethering apps on Android typically require it.
