### ISSUE TITLE
High CPU usage on receiving packets

### ISSUE THREAD

**Issue by darkain** [zerotier/ZeroTierOne#897]
**Describe the bug**
Early investigation right now about a higher than expected CPU usage when receiving ~30mbps worth of packets. Sending node is a single-core Pentium M CPU (32bit) with OPNsense running on bare metal, and only uses around 10-12% CPU during encryption and transmission. Receiving side is a VMWare virtual machine running OPNsense with two Xeon CPU (64bit) cores allocated. The VM is reporting 33% CPU usage, and was reporting even higher when it only had a single CPU core allocated. 

I'll continue to investigate this issue more when I have more time. I have additional 32bit and 64bit Intel servers and 64bit AMD servers sitting idle at home, so when I have time I'll test out a few more configurations to see if it is a CPU issue, encryption issue, 32bit vs 64bit issue, virtualization issue, or something else entirely.

Both nodes:
 - OS: OPNsense 18.7.9
 - ZeroTier Version: 1.2.12

**Screenshots**
![zt-cpu-usage](https://user-images.githubusercontent.com/2524251/50029302-2cbceb80-ffa7-11e8-90a1-c5ce211a0220.png)

**Comment by joeholden** [comment]
I'm also seeing this on KVM/Qemu VMs, 100% of a single core with a relatively small load of 20-25Mbps (single tcp stream) - bare metal does not exhibit the same problem with the same disk image booted.

Rather than just slow down it stalls entirely until it recovers, then obviously repeats itself as the traffic ramps back up again.

**Comment by joeholden** [comment]
Interestingly it seems to be better if I disable lro and gro from the guest

**Comment by joeholden** [comment]
Anything I can do help debug this? It's rendering zerotier pretty much entirely useless on VMs...

**Comment by adamierymenko** [comment]
I don't see this at all on our cloud nodes, VMs on local desktops with bigger CPUs, etc.

Is it possible that this is somehow related to some kind of CPU feature emulation that QEmu/KVM is doing?

**Comment by joeholden** [comment]
Well thats what I thought initially but its also present somewhat under VMWare - In testing however I'm using 2 KVM guests, one at Vultr, one elsewhere - they both exhibit the problem if theres a spike in traffic flowing *away* from them, but not in the other direction (ie; if sending from host A -> B, only host A will see high cpu usage and traffic stalls, B happily sits at basically 0% throughout), it also doesn't appear to affect relayed traffic, just IP/ethernet - perhaps this is why you don't see it on yours?

**Comment by darkain** [comment]
@adamierymenko Are you using Linux, or another OS for your VM testing? In my particular case, these are with FreeBSD (more specifically, OPNsense) machines.

**Comment by joeholden** [comment]
Actually I should clarify - I see this on Linux
