### ISSUE TITLE
iOS App crashing: Memory Leak?

### ISSUE THREAD

**Issue by devrando** [zerotier/ZeroTierOne#901]
**Describe the bug**

The connection setup works.
However, the VPN tunnel crashes when traffic is passing through (e.g. some parallel DNS queries or ICMP).
I then looked at the console logs of the iPhone (with the Apple Configurator) and it looks like the Zerotier app is terminated.

Test Device: iPhone 8+(iOS 12.1). Latest Zerotier App available.

**To Reproduce**

1. Connect to  a Zerotier Network with an iOS Device
2. Generate some parallel Traffic on the iOS Device.(Net Analyzer App: Scan VPN Subnet)
3. VPN Tunnel crashes

iPhone console log:

```
Jan  1 22:03:00 dev-name ZeroTierPTP(CocoaLumberjack)[271] <Notice>: Received memory warning
...
Jan  1 22:03:01 dev-name ReportCrash[276] <Notice>: Process ZeroTierPTP [271] killed by jetsam reason per-process-limit
...
Jan  1 22:03:01 dev-name neagent[270] <Error>: Extension com.zerotier.ZeroTier-One.ZeroTierPTP died unexpectedly
```

The logs obviously show that Zerotier first gets a memory warning, and then is hard killed by the Apple Jetsam Watchdog.

**Expected behavior**
No crash :)

 
**Smartphone :**
 - Device: iPhone 8+
 - OS: iOS 12.1
 - Version 1.2.12-1

**Comment by gck1fhqntd6** [comment]
According to:
https://forums.developer.apple.com/thread/106377
which references to:
https://forums.developer.apple.com/message/213651#213651

there seem to be the following ressource limits:

Provider | 32-bit | 64-bit
-- | -- | --
packet tunnel | 14 MiB | 15 MiB
filter data | 5 MiB | 6 MiB
filter control | 5 MiB | 6 MiB
app proxy | 14 MiB | 15 MiB

**Comment by gck1fhqntd6** [comment]
iOS12 and iOS11 seem to have lower limits regarding "filter data":

Provider | 64-bit
-- | --
packet tunnel | 15 MiB
app proxy | 15 MiB
filter control |  12 MiB
filter data | 6 MiB
DNS proxy | 15 MiB

**Comment by laduke** [comment]
#920

**Comment by devrando** [comment]
I can't confirm that the problem is solved.
The app continues to crash as soon as traffic goes through the VPN tunnel.

Also, the error message is the same, Zerotier is terminated by iOS because it does not meet the memory limits.
