### ISSUE TITLE
some websites like google search refuse through zerotier VPN

### ISSUE THREAD

**Issue by llyang1** [zerotier/ZeroTierOne#903]
**Basic Info**
VPS (unbuntu/centos) was set as service, IP 172.25.10.10, named Server-A here
"Client" with windows 7/windows 10, IP 172.25.10.11, named Client-A
Android phone, named Client-B

router add, 0.0.0.0/0 172.25.10.10

**Problem in Client-A**
Most websites works fine from Client-A, but www.google.com report the firewall problem, and the reports change a little time by time, so I can not search by google. but others like google scholar, youtube, google photos works very well.

And the dropbox show connecting, can not upload or download

**What I do in Client-A**
I changed several computers with different OS like windows 7, windows 10. the same

The default Gateway was blank, and get something like 25.255.255.254 by ipconfig, it should be something like 172.25.0.1

I set the default Gateway as 172.25.10.10. still problem

I changed DNS, the same

**The stupid way to solve the problem**
I setup a proxy shadowsocksR (SSR) in Server-A, and run SSR with IP 172.25.10.10
All works very well

**Problem in Android phone** Client-B
Again, most APP works very well, but google play store not work, the store even can not display anything. Google search, google photo, youtube and many other app works fine

I do not know this is a bug, or some new functions required to solve such problem.

BTW, google search, youtube, google scholar and dropbox are not opened to china here

**Comment by laduke** [comment]
Hi, 
haven't seen that before. Did you follow the guide here? https://zerotier.atlassian.net/wiki/spaces/SD/pages/7110693/Overriding+Default+Route+Full+Tunnel+Mode

`25.255.255.254` is a kind of hack for Windows. See #719

**Comment by llyang1** [comment]
after several clients for one week, one computer with windows 7, google works

others, google search, nytimes.com, dropbox, do not work

change into v2ray, wireguard, shadowsocks, all perfect

maybe, it is special in china

**Comment by adamierymenko** [comment]
It's likely Chinese IP blacklisting or Google blacklisting IPs from certain providers. Unfortunately it's not something we have any control over whatsoever.
