### ISSUE TITLE
more info about next major release 1.4.x?

### ISSUE THREAD

**Issue by selay01** [zerotier/ZeroTierOne#905]
here is what i can get:
https://www.zerotier.com/blog/2018-05-04-128.shtml
https://www.zerotier.com/manual.shtml#2_1_5
https://www.zerotier.com/manual.shtml#2_2_7

https://github.com/zerotier/ZeroTierOne/issues/716

**Comment by AlexisTM** [comment]
https://github.com/zerotier/ZeroTierOne/tree/dev

The version was bumped to 1.4.0 recently :+1:

**Comment by AlexisTM** [comment]
https://www.zerotier.com/zerotier-1-4-0pre/

1.2.99 version available to be downloaded for testing with Multipath enabled.

**Comment by AlexisTM** [comment]
https://github.com/zerotier/ZeroTierOne/releases

The version 1.4.0 has been released last week ;)
