### ISSUE TITLE
Slackware Support

### ISSUE THREAD

**Issue by lohmuller** [zerotier/ZeroTierOne#907]
I tried to install on slackware 14.1... But dont install =[
```bash
curl -s 'https://install.zerotier.com/' | sudo bash
```
Have some way? Thanks!

**Comment by sh-jeff** [comment]
Here is the install script:
https://github.com/zerotier/install.zerotier.com/blob/master/install.sh.in

Packages are only built for RPM & DEB as far as I know, and the script only checks for distributions that use those, so you will need to build them yourself.
Build instructions are in the README.

**Comment by adamierymenko** [comment]
We don't have the resources to support every Linux distribution, so for minor ones you'll have to build/install manually or do a pull request.
