### ISSUE TITLE
two zerotire network adapters?

### ISSUE THREAD

**Issue by llyang1** [zerotier/ZeroTierOne#908]
**Alternative, faster ways to get help**

**Describe the bug**
centos 7 vps, got two adapters after one time installation

just install like this
curl -s https://install.zerotier.com/ | sudo bash

ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether 00:16:3c:87:15:d4 brd ff:ff:ff:ff:ff:ff
3: ztrf25ytbh: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2800 qdisc pfifo_fast state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether 22:2e:a0:90:2f:ca brd ff:ff:ff:ff:ff:ff
4: ztc3qxpvjz: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2800 qdisc pfifo_fast state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether 12:95:6c:be:0d:ad brd ff:ff:ff:ff:ff:ff
5: wg0: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/none 

wg0 is wireguard virtual adapter

works very good, ping and even as a vpn server

just report here, works fine

**To Reproduce**
because many others installed, and works fine, I do not want to reinstall

**Expected behavior**
hope only one virtual adapter

**Screenshots**
message listed above

**Desktop (please complete the following information):**
 - OS: centos 7
 - OS/Distribution Version
 - ZeroTier Version 1.2.12
 - Hardware vps with 1GB RAM
 
**Smartphone (please complete the following information):**
 not related

**Additional context**
got this just after install, not related to firewall etc

**Comment by laduke** [comment]
If you do `sudo zerotier-cli listnetworks` are there two networks in the output?

**Comment by llyang1** [comment]
I got following

sudo zerotier-cli listnetworks
200 listnetworks <nwid> <name> <mac> <status> <type> <dev> <ZT assigned ips>
200 listnetworks blabla1 A-host 12:95:6c:be:0d:ad OK PRIVATE ztc3qxpvjz fc8a:4897:a5f6:ef94:bb59:0000:0000:0001/40,10.242.138.31/16
200 listnetworks blabla2 B-bwg 22:2e:a0:90:2f:ca OK PRIVATE ztrf25ytbh fd1d:7193:9404:4fd8:2399:93f6:ef94:bb59/88,172.25.138.31/16


I set up two networks, I think this is the reason. thank you, laduke
