### ISSUE TITLE
Windows 7, stuck on "Executing restore operation" during install.

### ISSUE THREAD

**Issue by Quenser** [zerotier/ZeroTierOne#909]
Stuck on "Executing restore operation" during Install, waited for 2 hours with nothing happening: https://i.imgur.com/kK6Sei4.png

Install impossible to cancel/stop without killing all ZeroTier processes in task manager and rebooting. After reboot seemingly not installed, no service running from what I can see but leaves behind a folder in Program Files: https://i.imgur.com/u80PUuC.png

- Windows 7 Ultimate x64 SP1
- Desktop PC with nothing weird in it
- Latest installer package of ZeroTier One
- No special network configs of any kind

**Comment by adamierymenko** [comment]
We test the Windows installers on clean Windows VMs and have never seen this. We also use a top-shelf (and fairly expensive) installer builder called Advanced Installer to try to give the best Windows install experience.

In the end there's still people out there who experience problems like this and typically it results from what is generally called "Windows rot." The windows installer subsystem is a horrid mess and can get corrupted in a million different ways.

**Comment by Vegz78** [comment]
Thanks for a great app, by the way, adamierymenko!

In my case, experiencing the same, the culprit was that I was writing my temp-files to a ramdisk. Turning that off, and it installed just fine, for some reason.

A small chance that it's the same reason for failure, but at least I got the same error message.

Vegard

**Comment by Quenser** [comment]
I was not writing to ramdisk, however I have my swap set up on a drive that is different from the system drive. So it seems likely that it's somehow related to temp files not being in their default location.

**Comment by VoidFletcher** [comment]
![issue](https://user-images.githubusercontent.com/10835605/74335690-694fc700-4da5-11ea-8a46-91b259c131b9.png)

A friend is also having this issue. He is running windows 10 x64

**Comment by n9yty** [comment]
Also seeing this on Windows Server 2016.

**Comment by ianthrive** [comment]
I was able to fix this on Server 2016:
1. Open **gpedit.msc**
2. Go to **Computer Configuration > Administrative Templates > Windows Components > Remote Desktop Services > Remote Desktop Session Host > Application Compatibility**
3. Double-click **Turn off Windows RDS Compatibility**
4. Select **Enabled**
5. Click **OK**
