### ISSUE TITLE
OSX Network System Configuration Integration

### ISSUE THREAD

**Issue by adamierymenko** [zerotier/ZeroTierOne#91]
Make ZT1 network devices show up in System Configuration, precursor to allowing DHCP and all kinds of good stuff. Shhh nobody tell Apple. :smile: 
![screen shot 2014-07-09 at 10 37 45 am](https://cloud.githubusercontent.com/assets/591635/3528499/fe46ddb0-078f-11e4-94c4-2ec9f0ca8f1f.png)

**Comment by adamierymenko** [comment]
Closing since we do not want to do this by hacking internal OS X plist files. Instead we're going to look at using the OS X version of the network extension API at some point in the future.

**Comment by kevinob11** [comment]
Any news on this? My network doesn't show up in my networks list and I need to be able to configure DHCP on it.
