### ISSUE TITLE
question: access each other through a http/socks proxy? support? how?

### ISSUE THREAD

**Issue by gMan1990** [zerotier/ZeroTierOne#910]
* PC1 with ZeroTierOne IP - 10.144.1.1
* PC2 with ZeroTierOne IP - 10.144.1.2

Can PC1 access PC2 through a http/socks proxy with IP-10.144.1.2 ?

**Comment by sh-jeff** [comment]
I don't see why you wouldn't be able to use PC2 as a proxy. I would think using tunnel all would be simpler.
FYI, this sort of thing should be asked at https://my.zerotier.com/community

**Comment by adamierymenko** [comment]
There's no native SOCKS support in ZeroTIer and we don't plan on it. SOCKS isn't heavily used enough. It *might* be possible to recompile against a SOCKS pass-through library or LD_PRELOAD one on Linux at least.

**Comment by adamierymenko** [comment]
I've heard tales of people using LD_PRELOAD with Tor SOCKS proxies to run it through Tor, but it would be incredibly slow that way!

**Comment by gMan1990** [comment]
http proxy or socks proxy
