### ISSUE TITLE
Crash on Linux if /dev/net/tun does not exist (???)

### ISSUE THREAD

**Issue by lunarthegrey** [zerotier/ZeroTierOne#912]
**Describe the bug**
When starting zerotier-one on this kernel `linux-image-4.9.0-8-armmp` I get the following when trying to start it.

```
root@node:~# zerotier-one       
Segmentation fault
```

```
root@node:~# service zerotier-one start
root@node:~# service zerotier-one status
* zerotier-one.service - ZeroTier One
   Loaded: loaded (/lib/systemd/system/zerotier-one.service; enabled; vendor preset: enabled)
   Active: failed (Result: signal) since Wed 2019-01-30 18:49:56 CET; 1s ago
  Process: 1986 ExecStart=/usr/sbin/zerotier-one (code=killed, signal=SEGV)
 Main PID: 1986 (code=killed, signal=SEGV)

Jan 30 18:49:56 node systemd[1]: zerotier-one.service: Failed with result 'signal'.
Jan 30 18:49:56 node systemd[1]: zerotier-one.service: Service hold-off time over, scheduling restart.
Jan 30 18:49:56 node systemd[1]: Stopped ZeroTier One.
Jan 30 18:49:56 node systemd[1]: zerotier-one.service: Start request repeated too quickly.
Jan 30 18:49:56 node systemd[1]: Failed to start ZeroTier One.
Jan 30 18:49:56 node systemd[1]: zerotier-one.service: Unit entered failed state.
Jan 30 18:49:56 node systemd[1]: zerotier-one.service: Failed with result 'signal'.
```

**To Reproduce**
Start zerotier-one via systemd or directly on the CLI.

**Expected behavior**
zerotier-one starts up as it did when running the other kernel `4.5.2-armada375`

**Desktop (please complete the following information):**
 - OS: Linux
 - OS/Distribution Version: Debian 9
 - ZeroTier Version: 1.2.12
 - Hardware: ARMv7 Cortex 2

**Additional context**
I am using one of these little ARMv7 servers https://www.soyoustart.com/ie/server-storage/

**Comment by martinellimarco** [comment]
I encounter the same problem a while ago. Using `strace` I noticed that it crashed becaused it was not able to open /dev/net/tun
I checked and the module was not loaded.
A simple `modprobe tun` fixed the problem for me.

**Comment by adamierymenko** [comment]
Still it should not crash. Flagging as minor bug.

**Comment by lunarthegrey** [comment]
Seems like in my case it's due to the kernel modules.

It says it's running this but it's wrong. Something with how these boards work maybe?

```
root@node:~# uname -r
4.5.2-armada375
```

```
root@kerberos:~# dpkg -l | grep linux-image
ii  linux-image-4.9.0-8-armmp       4.9.130-2                      armhf        Linux 4.9 for ARMv7 multiplatform compatible SoCs
```

I tried doing this as a workaround `ln -s /lib/modules/4.9.0-8-armmp /lib/modules/4.5.2-armada375` but no luck.

```
root@node:~# modprobe tun
modprobe: ERROR: could not insert 'tun': Exec format error
```

**Comment by martinellimarco** [comment]
In my case I'm running zerotier on a QNAP with ARM, inside an lxc container that runs ubuntu server.
I'm running ZeroTier One version 1.2.12 build 0 (platform 1 arch 3).

I'm connected to the QNAp from another location now, using zerotier and ssh, and I can't strace the process but @lunarthegrey  if you can please post the output of `strace zerotier-one`. I'll be able to tell if it's the same output I saw or not.

**Comment by lunarthegrey** [comment]
Yep, it is because of `tun`. Although I can't seem to load the module at all on this kernel :(

```
open("/dev/net/tun", O_RDWR|O_LARGEFILE) = -1 ENODEV (No such device)
open("/dev/tun", O_RDWR|O_LARGEFILE)    = -1 ENOENT (No such file or directory)
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x5} ---
+++ killed by SIGSEGV +++
Segmentation fault
```
