### ISSUE TITLE
TVOS

### ISSUE THREAD

**Issue by lifeiscontent** [zerotier/ZeroTierOne#913]
**Is your feature request related to a problem? Please describe.**
I'd like to run ZeroTierOne on my AppleTV.

**Describe the solution you'd like**
have a tvOS port of ZeroTierOne

**Describe alternatives you've considered**
None

**Additional context**
Please, thank you.

**Comment by adamierymenko** [comment]
This unfortunately can't be done. Network extensions are only possible on iOS and MacOS.

**Comment by lifeiscontent** [comment]
@adamierymenko oh, darn... that's unfortunate, thanks for the info though.

**Comment by dimitarvp** [comment]
Yeah, Apple said tvOS will be able to download and install VPN apps.

@adamierymenko Are you guys and girls gonna work on a ZeroTier app for AppleTV when the beta drops? Would be amazing to visit a friend's house carrying my device and have access to my home's media collection.

**Comment by danielhelmstedt** [comment]
This has been possible for a while now, the Tailscale app is pretty good. Has there been any movement on a ZeroTier tvOS app yet?

**Comment by bladmoreno** [comment]
Looking forward to use Zerotier with TvOS/AppleTV

**Comment by certuna** [comment]
Really hoping for this, AppleTV units are really good as default route/gateways since they're typically always on, and I don't really want to switch to Tailscale.
