### ISSUE TITLE
Compilation on Enigma2 linux

### ISSUE THREAD

**Issue by aros1975** [zerotier/ZeroTierOne#917]
Hi,

Can someone help mi to compile ZeroTierOne for Enigma2 (VU+ Ultimo 4k sat-receiver)?
I need an *.ipk file.

Results of uname -a:
Linux vuultimo4k 3.14.28-1.12 #1 SMP Tue Nov 13 16:52:01 CET 2018 armv7l GNU/Linux

Greetings,
Arek

**Comment by adamierymenko** [comment]
We just don't have the bandwidth to do this ourselves. If you want you're welcome to do a community port and we will link it under community ports on our download page.
