### ISSUE TITLE
moon When is the ddns address supported?

### ISSUE THREAD

**Issue by hhhnb** [zerotier/ZeroTierOne#918]
Intranet devices have this need, such as Raspberry Pi or router
moon  Will it develop support for ddns address?

**Comment by laduke** [comment]
Hi, 
moons need a fixed IP. DDNS won't be added. 

See also:
#881 
#622

**Comment by hhhnb** [comment]
I have a dynamic ip but I don't want to reconfigure it every time the client is reconfigured
So ddns is a necessary feature

**Comment by hhhnb** [comment]
I want to build the moon in my own home, which can reduce the delay, but my home ip will change after a while, it is an external network ip, so ddns is really a required function.

**Comment by laduke** [comment]
Until something like #622 happens, you'll have to keep re-doing it :/
This can help a little, if you haven't seen it: https://github.com/rwv/docker-zerotier-moon/

Or find a very cheap VPS in your area.

**Comment by troilus** [comment]
> I have a dynamic ip but I don't want to reconfigure it every time the client is reconfigured
> So ddns is a necessary feature

How to reconfigure the moon server when IP address is changed ? Also need to reconfigure client?

**Comment by freeAhao** [comment]
This feature must be useful.
Is there any script to help rebuild moon when ip changed?
I rebuild the moon manually , and the moon id not changed, do i need reconfigure client?

**Comment by charmyoung** [comment]
It seems working for me when leaving the IP address and port empty, and it would dynamically change the IP and the port is set as default 29994. Anyway, do not know the mechanism behind it.
