### ISSUE TITLE
IOS 12 connection drop 

### ISSUE THREAD

**Issue by packetpunter** [zerotier/ZeroTierOne#920]
It seems this is similar to Issue #742, 752, 745. 

I open the ZeroTier app on my iPhone, connect via toggling the connect button, and after I switch to another app, the connection closes to ZeroTier. I can go re-enable it again but this continues. 

iOS 12.1.4
ZeroTier One 1.2.12-1

**Comment by tim-jones-anthropos** [comment]
Have same problem on iPad Pro running iOS 12.1.4
Deleted network in zerotier app and recreated, as this seemed to have worked in the past, but this does not make any difference now.

**Comment by devrando** [comment]
I'm relatively sure it's #901.
I was able to recreate the behavior on the Apple iOS debug console

**Comment by laduke** [comment]
Hi everyone,
I'm able to reproduce this and am looking into it. The memory limit for network extensions is 15MB!
Seems like in new iOS's this is easier to hit for some reason.
