### ISSUE TITLE
API "/controller/network/<network ID>/active" not working

### ISSUE THREAD

**Issue by ertankucukoglu** [zerotier/ZeroTierOne#921]
I am on ZeroTier v1.2.12. Using my own controller on a Raspberry Pi running Debian 9 Stretch at home. If nothing extraordinary happens, Raspberry Pi is up and running 24/7.

I have tried to see active member list using API. Every time I use it nothing is listed. This is not quite possible as I have currently 2 Raspberry Pi, 1 Windows computer connected up and running to that network. Moreover, there are other members in the network (I am not sure if they are online when I run below commands).

I use following curl commands:
Accessing API using IP number:
```
root@raspberrypi:/var/lib/zerotier-one# curl -v --header "X-ZT1-Auth: my_secret" http://192.168.1.91:9993/controller/network/my_network/member
*   Trying 192.168.1.91...
* TCP_NODELAY set
* Connected to 192.168.1.91 (192.168.1.91) port 9993 (#0)
> GET /controller/network/my_network/member HTTP/1.1
> Host: 192.168.1.91:9993
> User-Agent: curl/7.52.1
> Accept: */*
> X-ZT1-Auth: my_secret
> 
< HTTP/1.1 200 OK
< Cache-Control: no-cache
< Pragma: no-cache
< Content-Type: application/json
< Content-Length: 61
< Connection: close
< 
* Curl_http_done: called premature == 0
* Closing connection 0
{"44451bdb1b":8,"70444bc06d":3,"9af5fdb57d":3,"3cda61761a":8}
```

Accessing API using IP number:
```
root@raspberrypi:/var/lib/zerotier-one# curl -v --header "X-ZT1-Auth: my_secret" http://192.168.1.91:9993/controller/network/my_network/active
*   Trying 192.168.1.91...
* TCP_NODELAY set
* Connected to 192.168.1.91 (192.168.1.91) port 9993 (#0)
> GET /controller/network/my_network/active HTTP/1.1
> Host: 192.168.1.91:9993
> User-Agent: curl/7.52.1
> Accept: */*
> X-ZT1-Auth: my_secret
> 
< HTTP/1.1 404 Not Found
< Cache-Control: no-cache
< Pragma: no-cache
< Content-Type: application/json
< Content-Length: 2
< Connection: close
< 
* Curl_http_done: called premature == 0
* Closing connection 0
{}
root@raspberrypi:/var/lib/zerotier-one# 
```

Accessing API using "localhost":
```
root@raspberrypi:/var/lib/zerotier-one# curl -v --header "X-ZT1-Auth: my_secret" http://localhost:9993/controller/network/my_network/active
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9993 (#0)
> GET /controller/network/my_network/active HTTP/1.1
> Host: localhost:9993
> User-Agent: curl/7.52.1
> Accept: */*
> X-ZT1-Auth: my_secret
> 
* Curl_http_done: called premature == 0
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
root@raspberrypi:/var/lib/zerotier-one# 
```
I was expecting to see at least 3 active member's listed.

I made a test and joined a network on my.zerotier.com on these 3 devices I listed above, and I could see all of them ONLINE in there.

I am no C++ guy. I might as well did not understand codes. But, looking at sources at master branch, there is no "active" checked in EmbeddedNetworkController.cpp - handleControlPlaneHttpGET function.

Any help is appreciated.

**Comment by glimberg** [comment]
Looks like the docs are out of date.  There is no `/network/network_id/active` path any more.

**Comment by glimberg** [comment]
Re the 404:  By default, ZeroTier listens only on `127.0.0.1`.  When you use `localhost`, it's resolving to `::1`, the IPv6 equivalent of `127.0.0.1`.  Unless `::1` is specifically allowed in `local.conf`, it's not going to work.

**Comment by ertankucukoglu** [comment]
> Looks like the docs are out of date. There is no `/network/network_id/active` path any more.
I do not know reasons behind removing that API. Are there any plans on having online status information in the future?

**Comment by ertankucukoglu** [comment]
> Re the 404: By default, ZeroTier listens only on `127.0.0.1`. When you use `localhost`, it's resolving to `::1`, the IPv6 equivalent of `127.0.0.1`. Unless `::1` is specifically allowed in `local.conf`, it's not going to work.

Yes, I have my own local.conf to listen one more IP number in my Raspberry Pi.

**Comment by glimberg** [comment]
> I do not know reasons behind removing that API. Are there any plans on having online status information in the future?

No not at this time.

> Yes, I have my own local.conf to listen one more IP number in my Raspberry Pi.

If you want to use `localhost`, you'll also have to add `::1` to your local.conf file.  `::1` != `127.0.0.1`

**Comment by ertankucukoglu** [comment]
> If you want to use `localhost`, you'll also have to add `::1` to your local.conf file. `::1` != `127.0.0.1`

Why would I need `::1` in my local.conf file? I do not have it at the moment. Below is my current local.conf file:
```
{
  "settings":{
    "allowManagementFrom": ["127.0.0.1/8", "192.168.1.91"]
  }
}
```
> When you fill out the `allowManagementFrom` field in local.conf, it _only_ allows management from IP addresses listed there.

Yes, that is what I read in documentation and there was a warning that I can break things.

**Comment by glimberg** [comment]
Because:

```
root@raspberrypi:/var/lib/zerotier-one# curl -v --header "X-ZT1-Auth: my_secret" http://localhost:9993/controller/network/my_network/active
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9993 (#0)
```

On your system, when curl uses `localhost`, it resolves to `::1` as seen in the snippet above.  That's why you need `::1` in your `allowManagementFrom` field.

**Comment by ertankucukoglu** [comment]
Got it. Added `::1` in my `allowManagementFrom` list.
Thanks.

**Comment by ertankucukoglu** [comment]
> Looks like the docs are out of date. There is no `/network/network_id/active` path any more.

Since that path is no more, is there another way to get activeness state of a member?

**Comment by glimberg** [comment]
Not in the self hosted controller, no.
