### ISSUE TITLE
different internet different traceroute

### ISSUE THREAD

**Issue by myfire888** [zerotier/ZeroTierOne#922]
I use zerotier with remote desktop.
so I have a problem, that I have to use 1 specific internet provider so that I could use the remote desktop
lets say if I use provider A, I could connect my remote desktop perfectly
tracert seems to be direct to the remote host :
  1    29 ms    51 ms    27 ms  PC [10.147.17.92]

if I use provider B, I'm struggling to get my remote desktop working, because the connection would be very very slow
and tracert seems to routing to anywhere else :
Tracing route to 10.147.17.92 over a maximum of 30 hops

  1     7 ms     4 ms     3 ms  192.168.43.1
  2     *        *        *     Request timed out.
  3    26 ms    41 ms    30 ms  192.168.109.25
  4     *       43 ms     *     192.168.19.242
  5    50 ms     *       45 ms  114.120.194.5
  6    46 ms    69 ms    39 ms  192.168.211.29
  7     *        *        *     Request timed out.
  8     *        *        *     Request timed out.
  9     *        *        *     Request timed out.
 10     *        *        *     Request timed out.
 11     *        *        *     Request timed out.
 12     *       94 ms    79 ms  10.147.17.92

both internet speedtest would reveal good internet connection, and both internet would reveal fast internet when trying to remote with teamviewer (which I wouldnt need vpn with zerotier if I want to use the likes of teamviewer). 
but I do need to use rdp, and that's why I need to use zerotier for vpn. is there any setting to do so that both provider could use direct tracert ?
because provider A is not always available to be used.

thx for the answer

**Comment by laduke** [comment]
Hi
I'd start here : https://zerotier.atlassian.net/wiki/spaces/SD/pages/6815768/Router+Configuration+Tips


Closing because it's a question, but you can still comment more.
