### ISSUE TITLE
Descriptive error message when CLI is run as non-administrator

### ISSUE THREAD

**Issue by M-Pixel** [zerotier/ZeroTierOne#923]
**Is your feature request related to a problem? Please describe.**
When running zerotier-cli on Windows as a non-administrator, I get the error `missing authentication token and authtoken.secret not found (or readable) in C:\ProgramData\ZeroTier\One`.  My default assumption is that the functionality will not work until I've set up an auth token through some explicit process.  It was not until I searched the error and read through a related issue posted to GitHub that it became apparent that the solution was to run the program as a system administrator.

**Describe the solution you'd like**
If the file exists, but the user does not have permission to read it, instead of stating that it was "not found (or readable)", state very explicitly "The current user does not have permission to access authtoken.secret.  Try again from a user account that has the correct permissions (likely root/Admin)."

**Describe alternatives you've considered**
Don't actually differentiate programatically between "file doesn't exist" and "file not readable", instead just append something about trying again as an admin to the error message.

**Comment by mischa-s** [comment]
Ran into this issue today on linux, thanks for opening this issue as it told me how to fix the problem
