### ISSUE TITLE
macOS change tickbox UI

### ISSUE THREAD

**Issue by ort163** [zerotier/ZeroTierOne#925]
**Is your feature request related to a problem? Please describe.**
In macOS GUI,
Instead of 'Allow Default' change it to 'Route via Zerotier'

**Describe the solution you'd like**
see above

**Describe alternatives you've considered**

Telling non technical people 'allow Default means 'Route via zt' (trust me it does not work well)!

**Additional context**
Language normal users can understand

**Comment by laduke** [comment]
Though if it says "Route via Zerotier", people will think it magically sets up a VPN/Gateway.

**Comment by adamierymenko** [comment]
Yup. We already have issues with people thinking this is one of those one-click "privacy VPN" thingies which it is not (though you can use it to DIY one if you use a cloud host as your router).
