### ISSUE TITLE
Low spead conection my home PC and mobile conection 3G 4G

### ISSUE THREAD

**Issue by birdoplo** [zerotier/ZeroTierOne#926]
I want to connect to my home PC from my android mobile phone. On the phone using 3G, 4G connection.
The problem is that I get a big ping 150-200 ms. and a very low speed of 15-20 kb/s.
How can I optimize my connection?
Firewall on router and on PC disables.
![2](https://user-images.githubusercontent.com/46086380/53912453-a07c0b00-4061-11e9-912a-33924226c726.jpg)
Update
I connected my mobile phone to my PC as a USB modem. And also produced a comand **listpeer**
![vodafone zerotier](https://user-images.githubusercontent.com/46086380/54092292-231f0600-4393-11e9-9673-bce651378adf.JPG)
What do you say to that?

**Comment by laduke** [comment]
https://zerotier.atlassian.net/wiki/spaces/SD/pages/6815768/Router+Configuration+Tips

which two nodes are you pinging between? 
can you post the ping time to the path to 159924d630? (35.236.x.x)?
where are you located?

**Comment by birdoplo** [comment]
> which two nodes are you pinging between?
![Безымянный](https://user-images.githubusercontent.com/46086380/54636010-1df64100-4a8e-11e9-8836-80de77f090c8.jpg)
> can you post the ping time to the path to 159924d630? (35.236.x.x)?
How to do it?
> where are you located?
Ukraine

**Comment by birdoplo** [comment]
https://github.com/zerotier/ZeroTierOne/issues/926#issuecomment-474542905

вт, 12 бер. 2019 о 21:54 Travis LaDuke <notifications@github.com> пише:

**Comment by laduke** [comment]
Hi
aefd471990 and ceda0bfb8c seem to not be able to make direct connections to each other
(no IP Address under <path>) so they will be relaying through ZeroTier server. This is slow.

**Comment by birdoplo** [comment]
Hello
How can you manage flows? Route changes?

ср, 20 бер. 2019 о 21:06 Travis LaDuke <notifications@github.com> пише:
