### ISSUE TITLE
zerotier-idtool genmoon fails on Windows for CRLF json file

### ISSUE THREAD

**Issue by KireinaHoro** [zerotier/ZeroTierOne#933]
`zerotier-idtool genmoon moon.json` fails to generate a proper .moon file on Windows, but exits prematurely at

https://github.com/zerotier/ZeroTierOne/blob/52c4385c16ec1e989369d550e0f720a050f72e32/one.cpp#L902

The json file generated by `zerotier-idtool initmoon` had CRLF line endings.  A `dos2unix` on the json file fixed this, but the JSON parser should be configured to support CRLF endings.

**Comment by KireinaHoro** [comment]
```
ZeroTier One version 1.2.12
Copyright (c) 2011-2018 ZeroTier, Inc.
This is free software: you may copy, modify, and/or distribute this
work under the terms of the GNU General Public License, version 3 or
later as published by the Free Software Foundation.
No warranty expressed or implied.
```

**Comment by adamierymenko** [comment]
We are going to say "wontfix" because the whole moon/planet thing is going to go away pretty soon.
