### ISSUE TITLE
zerotier-1.2.12 sets wrong MTU for wireless connection?

### ISSUE THREAD

**Issue by danielrobbins** [zerotier/ZeroTierOne#935]
I have been consistently noticing an issue with zerotier when using it under Funtoo Linux on my personal laptop on public WiFi networks. The symptoms really look like an MTU issue and the workaround is to lower the MTU on the zerotier interface. Here are the details:

When connecting over zerotier via WiFi, I can ssh into a system and commands that generate a little bit of input work properly, but commands that send a bunch of data like "ps axu", "htop", etc. will cause the connection to hang.

Upon investigation, I noticed the zerotier MTU was at 2800 and the wlan0 MTU was 1500. Upon viewing another MTU-related bug (that apparently was fixed) for an earlier zerotier version, I attempted to follow the work-around in that bug and reduce the MTU to around 1384. This didn't solve the issue. However, dropping the MTU to 800 on the zerotier interface and -- boom -- we're in business -- the connection is rock-solid again. This has happened on multiple WiFi networks in different locations, so I don't think it's specific to the WiFi network, and I am using a recent Debian LTS kernel (4.9.141) so nothing really wonky there.

I do not have this problem when I use zerotier using identical kernel and zerotier version over wired ethernet.

**Comment by danielrobbins** [comment]
After a bit of testing, I have determined that any MTU 1379 or lower works reliably, and any MTU 1380 or higher will trigger the issue.

**Comment by zhyf1019** [comment]
> After a bit of testing, I have determined that any MTU 1379 or lower works reliably, and any MTU 1380 or higher will trigger the issue.

dear，
It seems that i have this problem, too.   
I'd like to change MTU,
Could you pls. tell me how to change the MTU?  (Windows 10)

THS a lot~

**Comment by danielrobbins** [comment]
So, this issue appears to have resolved itself automatically, so I am wondering if it was related to an upstream issue on a zerotier server/moon?

**Comment by adamierymenko** [comment]
Closing since the issue seems to have resolved. It could also have been a transient configuration problem with one of the networks. That's a very small MTU!

**Comment by adamierymenko** [comment]
1.4 does use a slightly smaller default physical MTU size of 1432 to accommodate some cloud providers. This still fits one 2800 byte frame into two packets, so it doesn't affect performance for everyone else.

**Comment by danielrobbins** [comment]
Yes, I think it was a network issue where very small packets were able to get through but the larger ones were simply getting dropped on the floor. Working fine now.

**Comment by myfingerhurt** [comment]
@danielrobbins 

I had the same issue. I was trying to access my AC86U-merlinwrt 384.13 router's ssh & webui through zerotier such as 10.9.8.4. It worked perfectly until I moved house and changed my ISP. 

With the default MTU 2800, as long as I typed ps/ifconfig in console through zerotier address from remote node the putty would hang at around 10 lines output, and got disconnected after few seconds.

```
router@RT-AC86U:/tmp/home/root# ps
  PID USER       VSZ STAT COMMAND
    1 router    9352 S    /sbin/init
    2 router       0 SW   [kthreadd]
    3 router       0 SW   [ksoftirqd/0]
    5 router       0 SW<  [kworker/0:0H]
    7 router       0 SW   [rcu_preempt]
    8 router       0 SW   [rcu_sched]
    9 router       0 SW   [rcu_bh]
   10 router       0 SW   [migration/0]
   11 router       0 SW   [watchdog/0]

putty hung from here
```

 Also tested webui as following. Short returns worked, but when loaded main page it hung.
```
>curl http://10.9.8.4/

<HTML><HEAD><script>top.location.href='/Main_Login.asp';</script>
</HEAD></HTML>
```
```
curl http://10.9.8.4/Main_Login.asp
Nothing till timeout 
```

I saw your post and changed zerotier MTU to 1388. 
In my case everything works with MTU below 1388.
`fconfig ztzlgf7vul mtu 1388`

Boom! Instantly putty works and webui also can be open by browser.

I have 3 ac68u and 2 of them are working well with zertier MTU 2800, but 1 was behaving the same as ac86u through the same ISP.   I had to changed both of their mtu to 1388.

**Comment by danielrobbins** [comment]
@myfingerhurt It is very possible to create network loops with zerotier. When this is the case, it's those big packets that saturate the network and cause the network to hang. So make sure you don't have a network loop condition. If I have more than two zerotiers running in a private bridge, they will try to peer up and I get a network loop.

You can test this by looking at the amount of data flowing over your interfaces and anything crazy is indicative of a network loop. This can be mitigated with some firewall rules so the zerotier instance don't talk to each other.

**Comment by myfingerhurt** [comment]
@danielrobbins
Thanks, I have checked, read from the pkts, it seems no network loops.  
Every device within this network seems good, no visible lag.
Bandwidth monitors also show low network activities.

```
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
num   pkts bytes target     prot opt in     out     source               destination
1     4017  763K ACCEPT     all  --  eth0   *       0.0.0.0/0            0.0.0.0/0
2    44028 2798K ACCEPT     all  --  ztzlgf7vul *       0.0.0.0/0            0.0.0.0/0
3        0     0 ACCEPT     udp  --  eth0   *       0.0.0.0/0            0.0.0.0/0            udp dpt:9399
4        0     0 ACCEPT     tcp  --  eth0   *       0.0.0.0/0            0.0.0.0/0            tcp dpt:9399
5     116K   22M ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            state RELATED,ESTABLISHED
6        0     0 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            state INVALID
7    30077 7057K PTCSRVWAN  all  --  !br0   *       0.0.0.0/0            0.0.0.0/0
8      176 45410 PTCSRVLAN  all  --  br0    *       0.0.0.0/0            0.0.0.0/0
9      176 45410 ACCEPT     all  --  br0    *       0.0.0.0/0            0.0.0.0/0            state NEW
10   23914 5846K ACCEPT     all  --  lo     *       0.0.0.0/0            0.0.0.0/0            state NEW
11    6163 1212K OVPN       all  --  *      *       0.0.0.0/0            0.0.0.0/0            state NEW
12       0     0 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp spt:67 dpt:68
13       0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            192.168.7.1          ctstate DNAT tcp dpt:8443
14       0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:22
15       8   672 INPUT_ICMP  icmp --  *      *       0.0.0.0/0            0.0.0.0/0
16    6163 1212K DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0

```
I only have one zerotier bridge in one device.

By setting zerotier mtu to 1388, my network is working as perfectly as usual.
```
ztzlgf7vul Link encap:Ethernet  HWaddr EA:86:25:D8:AF:5D
          inet addr:10.9.8.4  Bcast:10.9.8.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1388  Metric:1
          RX packets:55586 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2196 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:500
          RX bytes:4297118 (4.0 MiB)  TX bytes:1008916 (985.2 KiB)

br0       Link encap:Ethernet  HWaddr  (censored)
          inet addr:192.168.7.1  Bcast:192.168.7.255  Mask:255.255.255.0
          UP BROADCAST RUNNING ALLMULTI MULTICAST  MTU:1500  Metric:1
          RX packets:9921 errors:0 dropped:0 overruns:0 frame:0
          TX packets:81607 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:2100346 (2.0 MiB)  TX bytes:20197149 (19.2 MiB)

eth0      Link encap:Ethernet  HWaddr (censored)
          inet addr:192.168.9.2  Bcast:192.168.9.255  Mask:255.255.255.0
          UP BROADCAST RUNNING ALLMULTI MULTICAST  MTU:1500  Metric:1
          RX packets:137267 errors:0 dropped:1249 overruns:0 frame:0
          TX packets:103260 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:24210544 (23.0 MiB)  TX bytes:15356074 (14.6 MiB)


```

**Comment by yanggis** [comment]
@myfingerhurt May I know how to change the MTU value for the zerotier-one interface?

**Comment by samvrlewis** [comment]
Same way you would change it for any other network interface - something like `ip link set zt0 mtu 1500` or `ifconfig eth0 mtu 1500`

**Comment by laduke** [comment]
https://github.com/zerotier/ZeroTierOne/issues/74#issuecomment-499966236
