### ISSUE TITLE
Zerotier connection/sessions are slow as of today.

### ISSUE THREAD

**Issue by siddiquagig** [zerotier/ZeroTierOne#936]
My containers which are getting IPs from my zerotier are very slow today , they were working fine since a month now, when i connect to them , i loose my session, have to press some key to refresh it etc, One simple command takes like 2 to 5 min to process like ```ls```
From logs:

```
Installing etcd on node 002590d531f8 failed: (EtcdDeployError(...), "(EtcdDeployError(...
), '500 Server Error: Internal Server Error for url: https://my.zerotier.com/api/network/83048a06327b8706/member/fa5976fc1b')")
```

This never happened before and my network is fast and just having issues with zerotier.

 - ZeroTier Version : 1.2.12

**Comment by KestutisMa** [comment]
For me too, that is happening for several weeks I think, it is occasionally very slow and big packet loss. Often few times a day, for several hours. Also this is happening now.

**Comment by KestutisMa** [comment]
Currently Hamachi works without problem, but Zerotier has high latency and packet loss. So probably it is not physical connection problem.
Zerotier sometimes also work without problem. What could be cause of that?

**Comment by laduke** [comment]
https://zerotier.atlassian.net/wiki/spaces/SD/pages/6815768/Router+Configuration+Tips
https://zerotier.atlassian.net/wiki/spaces/SD/pages/360465/System+Configuration+Recommendations
https://zerotier.atlassian.net/wiki/spaces/SD/pages/31358977/Common+AWS+Issues

**Comment by laduke** [comment]
Visit the my.zerotier.com chat and we'll try to figure it out.
