### ISSUE TITLE
cli does not have a way to auth itself and I write a script

### ISSUE THREAD

**Issue by trawor** [zerotier/ZeroTierOne#937]
**Is your feature request related to a problem? Please describe.**
cli does not have a way to auth itself , I understand this is a dup of #796 

**Describe the solution you'd like**
with param like `--api-token` to call ZT api

**Describe alternatives you've considered**
I write a script and docker image already, please take a look https://github.com/trawor/zerotier

**Comment by glimberg** [comment]
ZeroTier CLI does not interact with the ZeroTier Central API, nor is it meant to.
