### ISSUE TITLE
Zerotier creating constant duplicate firewall entries

### ISSUE THREAD

**Issue by DjBlades** [zerotier/ZeroTierOne#938]
**Describe the bug**
I used to use Zerotier to play emulated games with a friend, but suddenly their Zerotier lost connection to the server and would always give a "Cannot connect to Zerotier service" error upon trying to reconnect. They reinstalled the program and were able to rejoin the network, but they still couldn't connect to my game server. They checked Windows Firewall to see if perhaps it wasn't properly configured to allow Zerotier through, but surprisingly found 6 entries for the program. As they closed and reopened the Firewall window, the entries seemed to duplicate each time. In the end they had 9 "ZeroTier One" entries, two "ZeroTier One x64 Binary" entries and two "TCP 9993" entries. They've since uninstalled Zerotier again and removed all Firewall rules to be sure of a complete removal. Any idea as to what could be causing this? What precautions could they take during their next reinstall to try prevent this?

**Expected behavior**
Connections to work, Single entry for each Zerotier component in Firewall rules.

**Screenshots**
Firewall Entries: https://i.imgur.com/t8pxFH9.png

**Desktop (please complete the following information):**
 - OS: Windows 10
 - ZeroTier Version [e.g. 1.2.12]

**Comment by adamierymenko** [comment]
So we investigated and confirmed that firewall entry creation is only done by the installer. Did you repeatedly install the MSI package? Maybe that's it.
