### ISSUE TITLE
Zerotier | Create a network

### ISSUE THREAD

**Issue by h0lysp4nk** [zerotier/ZeroTierOne#939]
Hi,

After taking a look at the documentation at "https://www.zerotier.com/manual.shtml#4_1" I cannot seem to find a way to create a world(network) using the API. Would someone be able to help?

**Comment by laduke** [comment]
There are two APIs you might be referring to:

- https://my.zerotier.com/help/api
- https://github.com/zerotier/ZeroTierOne/tree/master/controller

**Comment by laduke** [comment]
Hello, 
visit the chat and we'll point you in the right direction.
