### ISSUE TITLE
A way to update supernodes without a release

### ISSUE THREAD

**Issue by adamierymenko** [zerotier/ZeroTierOne#94]
In the future I'd like to do supernodes via signatures or maybe even a DHT or similar, but for now it'd be nice if nodes could update the supernode list without a release. It's a pain for OSS users to upgrade if a supernode has to change.

**Comment by sbilly** [comment]
Has this feature included in current version v1.1.4 ??

**Comment by adamierymenko** [comment]
Since 1.1.0.
