### ISSUE TITLE
Punching multiple UDP holes

### ISSUE THREAD

**Issue by nicedayever** [zerotier/ZeroTierOne#940]
**Is your feature request related to a problem? Please describe.**
It is known that the connectivity between the NAT-ed network in China is not very stable.  Usually, the UDP holes does not last long. 

**Describe the solution you'd like**
Perhaps Zerotier may punch and maintain multiple UDP holes at the same time. One hole can be used as the main connectivity while others can be used as the back up.

**Comment by adamierymenko** [comment]
We do what we can, but that's all we can do... there's a long tail of nasty router variations, broken NATs, and other things that we just can't deal with. Use IPv6 or open a port and that might help.
