### ISSUE TITLE
Windows 10 Blocking ZeroTier One Virtual Port

### ISSUE THREAD

**Issue by FRDS** [zerotier/ZeroTierOne#941]
So, I have a PC with dual OS installed, Windows 7 and Windows 10 (both 64-bit). Out of the way, ZeroTier **works perfectly** with Windows 7, it connects with my private network and I have tested the connection by playing games with my friends. But surprisingly it never works with my Windows 10 installation. I've followed the usual procedure:

1. Downloaded and installed ZeroTier One for Windows.
2. Join a network by inputting a network ID.
3. There should have been a prompt that tells me what to do with the network I've connected. It never shows up. There are also no network displayed in the "Show Network" menu.
4. After I checked, ZeroTier Virtual Port is installed but it was disabled. Moreover, I can't never enable it. Every time I click "Enable", it shows the process of enabling it until it's done but never actually enabling it.

![image](https://user-images.githubusercontent.com/17400640/56846109-f304d580-68f4-11e9-8e22-338311e42540.png)|

Is there something on my Windows 10 or my network blocking ZeroTier virtual port?

**Details:**
- Windows 10 64-bit (Build 17763)
- ZeroTier One 14.5.2

**Comment by laduke** [comment]
Hello, visit us in the chat and we'll try to figure it out. Maybe you haven't authorized the member in the network. You shouldn't need to mess around with the adapter. 
You can also try poking around with the cli instead of the tray app:
https://zerotier.atlassian.net/wiki/spaces/SD/pages/29065282/zerotier-cli
