### ISSUE TITLE
One server (out of several) with public routable IP still appears as "Physical IP Unknown"

### ISSUE THREAD

**Issue by farfalle75** [zerotier/ZeroTierOne#942]
Hello there, I don't know if this is a potential bug or something else as I couldn't find anything to correct what I see happening. I'd appreciate if someone has any idea about it.

We have several dedicated servers in Paris and Amsterdam, all of them have public IPv4 addresses (not behind any NAT or fancy filtering). Some of them run KVM virtual machines (accessing the outside world through NAT/masquerade).  Each and every node (hosts and guests) have been installed with Zerotier and all are joined to the same Zerotier network. Servers span in 3 different data centers in Paris (located in different physical locations) and another one in Amsterdam.

All nodes *but one* are working like a charm, peer discovery was even able to understand that servers can reach each other via faster private routes (some of them are also connected together with a cross connect using a secondary physical interfaces, or RPN link)

One of the server though seems to behave strangely. When I look at it in the Zerotier Central, I always see it with "Physical IP" equal to "(unknown)". The virtual machines running on it show the same thing. Keep in mind that the other servers are correctly advertising the "Physical IP" (same for virtual machines hosted on them). I even run something from my home behind cable connection and double NAT (my broarband NAT and a Linux server with virtual machines parameterized the same way as publicly visible ones, with bridge and NAT) and believe it or not it just survives without any flaw, host and virtual machines have the same "Physical IP" and it's the right one. Kudos.

I decided to create another test network and just added one server known to work well and the server known to fail. No VM or NAT in the ways. The same thing happens !

If I look to the known peers using zerotier-cli listpeers on both servers and compare. I see something quite strange on the malfunctionning one. Let's say my network is AABBCCDDEEFF123456

Failing server has this:
200 listpeers AABBCCDDEEFF- -1 - LEAF

Working servers all have this :
200 listpeers AABBCCDDEEFF 35.236.10.22/some_port;908;908 142 1.2.13 LEAF

It seems that this ztaddress (the one starting with the 10 first letters of the network) has a special role and that the failing server has trouble with 35.236.10.22. I tried to nmap from the failing server to 35.236.10.22/some_port and it appears as open|filtered (just the same from the working server)

nmap -sU -p 35368 35.236.10.22

Starting Nmap 7.60 ( https://nmap.org ) at 2019-04-27 16:47 CEST
Nmap scan report for 22.10.236.35.bc.googleusercontent.com (35.236.10.22)
Host is up (0.14s latency).

PORT      STATE         SERVICE
some_port/udp open|filtered unknown

The failing server is on network 51.159.0.0/16, all other ones are in different networks (163.172.0.0/16, 3 servers  and 195.154.0.0/20, 2 servers)

Any idea why this would happen ? 

Thanks !

PS: The reason it's a problem it that all the VMs on this faulty server, and the server itself, cannot be reached directly by any other member of the network. Everything goes through "bob" or "alice" servers. While they are some close to the servers, the bandwidth is way slower and the packet loss % is way higher too.

**Comment by janjaapbos** [comment]
The node with matching first part of the network id, is the network controller (part of zerotier central if you use my.zerotier.com)

**Comment by janjaapbos** [comment]
Sometimes it can take more than 10 hours for a node to reach a direct path. You can check later again. Also perhaps open up the firewall a bit, eg allow all udp for dest and source ports 9993 and everything higher.

**Comment by farfalle75** [comment]
The network has been up for months. Firewall is open to anything. And
strangely other servers just get the direct path in a few seconds. I asked
the hosting company if something was different with this data center as
this misdemeaning server is the only one there. Is it possible the
filtering is on google side ?

**Comment by janjaapbos** [comment]
That is always a possibillity with cloud hosting. Perhaps a previous user of the ip address was blocked. If you can allow for downtime you can try to build and use zerotier from the dev branch. I think it has some improvements to direct path establishment.

**Comment by farfalle75** [comment]
Will try that thanks. Perhaps I need to find a way to see if Google is
blocking things in that particular network too. I don't see how else the
network controller cannot see something coming from a public IP with no NAT
nor Firewall. As I said, starting the service on any other server and you
got all your ztadresses going through direct path in a matter of seconds.
Same thing if I start a new network and join any of the servers (any but
the locked out one). After a long time most servers are managing to find
direct routes to even the locked out one and its VMs. But it remains
'unknown' on the central. And also, we have a lot of collaborators joined
as road warriors on the network, coming from office, home, 4g connections,
public wifi, etc... Those can't plug 10 hours to have a direct route
download

**Comment by farfalle75** [comment]
I cloned, built (bumped version.h to 1.2.13 to be sure central sees me) and no luck. I see my 1.2.13 node joined but the "physical IP" is still "(unknown)".

Also looked here and there if the IP of the server is blacklisted. Most of black listings came clean, just one came out as blocked (dnsbl.spfbl.net) and is also blocked for the other servers (that work with fine with ZT)

Is there a way that the network controller could be deployed elsewhere ?

**Comment by janjaapbos** [comment]
You can host your own controller. Or perhaps try to get a different ip on a new vm.

**Comment by farfalle75** [comment]
I tried to capture packets from the public IP interfaces (faulty server and a working one)
1) the working out chats with 35.236.10.22 (UDP)
2) the non working one just doesn't ever receive or send any packet to that address

**Comment by janjaapbos** [comment]
Did you try to leave and rejoin the network from the faulty node?

**Comment by farfalle75** [comment]
The servers are bare metal ones on which we host several VMs. The only way
to change IP would be to open a subscription for a new one, migrate
everything there and close the subscription to the replaced one. A bit of a
burden to change IP. Without any guarantee the new one will work.

Is hosting our own controller going to solve this problem? If so it will
probably be a more easy thing to do :) If yes we have plenty of places to
put it. Is there a KB article to explain how to do that somewhere?

Thanks a lot for your help!

**Comment by farfalle75** [comment]
I did try yes to leave/join. Also created a new test network and joined it
with two different servers, one known to work, and the faulty one. Same
results. It's like if this particular host in google cloud could not reach
us (tcpdump is silent)

**Comment by janjaapbos** [comment]
you can also test what happens when you have a fresh zerotier id. Perhaps the controller is stuck in a a dead end for the faulty id. Either delete the  old id on the faulty server and restart zerotier, or first test it on a vm on the faulty server with a new zerotier client install.

**Comment by farfalle75** [comment]
already tried that :) thanks anyways

**Comment by farfalle75** [comment]
Hello again, 

I decided to give some time to setup using 6PLANE (instead of having each and every VM installed with ZeroTier) and it works like a charm.

The strange thing is that ZeroTier central now sees the physical address of the "faulty" server. Removing Zerotier nodes from within the host seems to have solved the problem !

Perhaps some kind of conflict ?
