### ISSUE TITLE
Question regarding CLA

### ISSUE THREAD

**Issue by Nayana-ibm** [zerotier/ZeroTierOne#943]
We're interested in contributing, but are concerned about the lack of a CLA and the fact that the codebase is default licensed under GPL, as we might want to reuse the code we're submitting here under a license incompatible with GPL. Can you allow us to contribute code while explicitly letting us keep all copyright rights, including the right to license it under a different license?

**Comment by adamierymenko** [comment]
What do you want to contribute?

**Comment by Nayana-ibm** [comment]
@adamierymenko We would like do PR to add support for s390x. We have code changes ready . 
We could also open a issue with our proposed changes

**Comment by Nayana-ibm** [comment]
@adamierymenko Created another [issue ](https://github.com/zerotier/ZeroTierOne/issues/950) with code patches to support s390x.

**Comment by joseph-henry** [comment]
Thank you for your contribution. We can definitely integrate your changes to our `Makefile` and `header file` if you would like. To answer your question, we do allow exceptions to our license for paying enterprise customers, and this is something @adamierymenko can give you more details on if you send a message to contact@zerotier.com

**Comment by Nayana-ibm** [comment]
@joseph-henry Yes..please integrate the changes

**Comment by Ornias1993** [comment]
@Nayana-ibm
If there is no CLA, you still hold all rights to the code you write.
The GPL requires you to licence it under GPL, but you are free to also licence your changes under other licences as well.

A CLA can't even overrule the GPL licence either.

If anyone has fears about licencing: Contact a Legal professional and, if there is a problem, let them contact the company formally to get a licence grant if needed.
