### ISSUE TITLE
Spike in ping times every 10 to 20 packets or so

### ISSUE THREAD

**Issue by saket424** [zerotier/ZeroTierOne#945]
**Describe the bug**
More a question than a bug. When I ping a host using the zerotier interface I see spikes in ping times every so often. Without zerotier, the ping times are rock solid stable and do not vary as much

**To Reproduce**
1. Create a Network '...'
2. Install zerotier-one on two nodes
3. ping one another
4. Notice the jump in ping times from an average of roughly 50 ms to a peak of nearly 10 times as much to 404 ms at icmp_seq=24 if you ignore the initial few packets 

**Expected behavior**
Expecting consistent ping times. Anyone else pay attention to their ping times and notice occasional spikes of up to 10 times the average ping times with zerotier ? Any ideas as to why ?

**Screenshots**
ping 172.8.64.202
PING 172.8.64.202 (172.8.64.202) 56(84) bytes of data.
64 bytes from 172.8.64.202: icmp_seq=1 ttl=64 time=602 ms
64 bytes from 172.8.64.202: icmp_seq=2 ttl=64 time=87.6 ms
64 bytes from 172.8.64.202: icmp_seq=3 ttl=64 time=56.1 ms
64 bytes from 172.8.64.202: icmp_seq=4 ttl=64 time=51.1 ms
64 bytes from 172.8.64.202: icmp_seq=5 ttl=64 time=50.7 ms
64 bytes from 172.8.64.202: icmp_seq=6 ttl=64 time=50.9 ms
64 bytes from 172.8.64.202: icmp_seq=7 ttl=64 time=52.1 ms
64 bytes from 172.8.64.202: icmp_seq=8 ttl=64 time=53.0 ms
64 bytes from 172.8.64.202: icmp_seq=9 ttl=64 time=50.6 ms
64 bytes from 172.8.64.202: icmp_seq=10 ttl=64 time=49.6 ms
64 bytes from 172.8.64.202: icmp_seq=11 ttl=64 time=49.6 ms
64 bytes from 172.8.64.202: icmp_seq=12 ttl=64 time=59.8 ms
64 bytes from 172.8.64.202: icmp_seq=13 ttl=64 time=53.1 ms
64 bytes from 172.8.64.202: icmp_seq=14 ttl=64 time=49.8 ms
64 bytes from 172.8.64.202: icmp_seq=15 ttl=64 time=50.7 ms
64 bytes from 172.8.64.202: icmp_seq=16 ttl=64 time=51.3 ms
64 bytes from 172.8.64.202: icmp_seq=17 ttl=64 time=53.7 ms
64 bytes from 172.8.64.202: icmp_seq=18 ttl=64 time=50.3 ms
64 bytes from 172.8.64.202: icmp_seq=19 ttl=64 time=57.8 ms
64 bytes from 172.8.64.202: icmp_seq=20 ttl=64 time=62.0 ms
64 bytes from 172.8.64.202: icmp_seq=21 ttl=64 time=60.0 ms
64 bytes from 172.8.64.202: icmp_seq=22 ttl=64 time=51.3 ms
64 bytes from 172.8.64.202: icmp_seq=23 ttl=64 time=55.3 ms
64 bytes from 172.8.64.202: icmp_seq=24 ttl=64 time=404 ms
64 bytes from 172.8.64.202: icmp_seq=25 ttl=64 time=53.7 ms
64 bytes from 172.8.64.202: icmp_seq=26 ttl=64 time=58.1 ms
64 bytes from 172.8.64.202: icmp_seq=27 ttl=64 time=153 ms
64 bytes from 172.8.64.202: icmp_seq=28 ttl=64 time=51.1 ms
64 bytes from 172.8.64.202: icmp_seq=29 ttl=64 time=54.7 ms
64 bytes from 172.8.64.202: icmp_seq=30 ttl=64 time=49.8 ms
64 bytes from 172.8.64.202: icmp_seq=31 ttl=64 time=51.0 ms
64 bytes from 172.8.64.202: icmp_seq=32 ttl=64 time=53.6 ms
64 bytes from 172.8.64.202: icmp_seq=33 ttl=64 time=49.8 ms
64 bytes from 172.8.64.202: icmp_seq=34 ttl=64 time=66.0 ms
64 bytes from 172.8.64.202: icmp_seq=35 ttl=64 time=55.3 ms
64 bytes from 172.8.64.202: icmp_seq=36 ttl=64 time=54.2 ms
64 bytes from 172.8.64.202: icmp_seq=37 ttl=64 time=52.3 ms
64 bytes from 172.8.64.202: icmp_seq=38 ttl=64 time=50.9 ms
64 bytes from 172.8.64.202: icmp_seq=39 ttl=64 time=51.2 ms
64 bytes from 172.8.64.202: icmp_seq=40 ttl=64 time=52.2 ms
64 bytes from 172.8.64.202: icmp_seq=41 ttl=64 time=55.3 ms
64 bytes from 172.8.64.202: icmp_seq=42 ttl=64 time=54.8 ms
64 bytes from 172.8.64.202: icmp_seq=43 ttl=64 time=53.3 ms
64 bytes from 172.8.64.202: icmp_seq=44 ttl=64 time=57.3 ms
64 bytes from 172.8.64.202: icmp_seq=45 ttl=64 time=60.4 ms
64 bytes from 172.8.64.202: icmp_seq=46 ttl=64 time=52.5 ms
64 bytes from 172.8.64.202: icmp_seq=47 ttl=64 time=68.2 ms
64 bytes from 172.8.64.202: icmp_seq=48 ttl=64 time=61.9 ms
64 bytes from 172.8.64.202: icmp_seq=49 ttl=64 time=56.9 ms
64 bytes from 172.8.64.202: icmp_seq=50 ttl=64 time=52.8 ms
64 bytes from 172.8.64.202: icmp_seq=51 ttl=64 time=51.5 ms
64 bytes from 172.8.64.202: icmp_seq=52 ttl=64 time=51.9 ms
64 bytes from 172.8.64.202: icmp_seq=53 ttl=64 time=50.0 ms
64 bytes from 172.8.64.202: icmp_seq=54 ttl=64 time=331 ms
64 bytes from 172.8.64.202: icmp_seq=55 ttl=64 time=52.8 ms
64 bytes from 172.8.64.202: icmp_seq=56 ttl=64 time=52.5 ms
64 bytes from 172.8.64.202: icmp_seq=57 ttl=64 time=54.3 ms
64 bytes from 172.8.64.202: icmp_seq=58 ttl=64 time=53.4 ms
64 bytes from 172.8.64.202: icmp_seq=59 ttl=64 time=54.5 ms

If applicable, add screenshots or console output to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Linux
 - OS/Distribution Version : Ubuntu 18.04 and 16.04 respectively
 - ZeroTier Version 1.2.12
 - Hardware UP2 (Intel(R) Pentium(R) CPU N4200 @ 1.10GHz)
 
**Additional context**
- ZeroTier Network Configuration
- Router Config
- Firewall Config (try turning the firewall off)
- General Network Environment: Home in Illinois pinging another Home in Massachusetts

**Comment by adamierymenko** [comment]
What's the ping time look like over regular naked Internet across a similar path?

**Comment by saket424** [comment]
Over regular naked internet (without zt) across a similar path, the ping times are consistently hovering around the same 50msec mark with no big spikes.

**Comment by adamierymenko** [comment]
Leaving open since we want to see if this continues happening after 1.4.0 release. If so we'll look into it. We don't see this ourselves.
