### ISSUE TITLE
Option to copy IP address quickly from the controller network page

### ISSUE THREAD

**Issue by swapneelp** [zerotier/ZeroTierOne#946]
**Is your feature request related to a problem? Please describe.**
Not exactly a problem. It would be nifty to quickly copy an IP address to clipboard from the controller network page which lists the machines/devices. 

This would be extremely useful when accessing the page from a mobile device. 

**Describe the solution you'd like**
A small button besides the IP address which when clicked will copy it to clipboard. 

**Describe alternatives you've considered**
The current option is to use the phone's select and copy feature which at times becomes too much effort in an emergency when you want to ssh.

**Comment by joseph-henry** [comment]
This feature is now available in the beta version of the web UI (accessible by selecting "Preview a beta Members interface" in the `Members` section.) Then merely "click" the address you want to copy to your clipboard. This works on desktop and mobile.
