### ISSUE TITLE
Adding support for s390x

### ISSUE THREAD

**Issue by Nayana-ibm** [zerotier/ZeroTierOne#950]
We are trying to build ZeroTier v1.2.12 on s390x architecture . However build failed with an errors.
On further investigation, we found that we need to make below code changes to build it on s390x.
https://github.com/zerotier/ZeroTierOne/blob/master/include/ZeroTierOne.h
```
@@ -1038,7 +1038,8 @@ enum ZT_Architecture
ZT_ARCHITECTURE_SPARC64 = 12,
ZT_ARCHITECTURE_DOTNET_CLR = 13,
ZT_ARCHITECTURE_JAVA_JVM = 14,
- ZT_ARCHITECTURE_WEB = 15
+ ZT_ARCHITECTURE_WEB = 15,
+ ZT_ARCHITECTURE_S390X = 16
};
```

https://github.com/zerotier/ZeroTierOne/blob/master/make-linux.mk
```

@@ -205,6 +205,9 @@ ifeq ($(CC_MACH),mips64el)
ZT_ARCHITECTURE=6
override DEFS+=-DZT_NO_TYPE_PUNNING
endif
+ifeq ($(CC_MACH),s390x)
+ ZT_ARCHITECTURE=16
+endif


# Fail if system architecture could not be determined
ifeq ($(ZT_ARCHITECTURE),999)

```

With these patches, we could successfully build and start Zerotier service.

**Comment by sbilly** [comment]
maybe you can send pull request ?

**Comment by Nayana-ibm** [comment]
@sbilly   We're not allow to sign CLA. I have also raised issue related to CLA [here](https://github.com/zerotier/ZeroTierOne/issues/943)

**Comment by Nayana-ibm** [comment]
@joseph-henry Could you please integrate changes to Makefile and header file as suggested in 
https://github.com/zerotier/ZeroTierOne/issues/943#issuecomment-497034906

**Comment by joseph-henry** [comment]
The changes have been integrated.
