### ISSUE TITLE
Configurable default roots

### ISSUE THREAD

**Issue by prawnsalad** [zerotier/ZeroTierOne#951]
I'm trying to wrap my head around the naming schemes but am I correct in thinking that if I was to create my own roots, I could then use those roots in place here which would in theory remove the default ZeroTier dependancy entirely? https://github.com/zerotier/ZeroTierOne/blob/e75a093a8cd004856788032a3eb977c98359e9a6/attic/world/mkworld.cpp#L83-L116

If correct, it would awesome and so much easier to override these hard coded roots if we have a `roots` config file in the zerotier home dir.

**Comment by adamierymenko** [comment]
This is definitely coming, but via a very different mechanism. Closed because we are doing this.

**Comment by prawnsalad** [comment]
@adamierymenko is there anywhere I can follow this since you've closed this issue?
