### ISSUE TITLE
Asymmetric bandwidth between peers ( 40x difference)

### ISSUE THREAD

**Issue by devbhosale** [zerotier/ZeroTierOne#953]
I have two peer nodes which are listed using "listpeers" command.
Both are Ubuntu 18.04 LTS VPS servers.

If I do bandwidth test without zerotier on their public network. The performance is symmetrical ( with approximately similar numbers)

If I run the same test on zerotier network, bandwidth changes significantly depending on the direction.

 

Bandwidth test over Public Network in both client server mode
root@server-01:~# iperf -s
------------------------------------------------------------
Server listening on TCP port 5001
TCP window size: 85.3 KByte (default)
------------------------------------------------------------
[  4] local xxx.xxx.133.92 port 5001 connected with xxx.xxx.186.109 port 17112
[ ID] Interval       Transfer     Bandwidth
[  4]  0.0-10.0 sec  2.34 GBytes  2.01 Gbits/sec

root@server-01:~# iperf -c  xxx.xxx.186.109
------------------------------------------------------------
Client connecting to xxx.xxx.186.109, TCP port 5001
TCP window size:  128 KByte (default)
------------------------------------------------------------
[  3] local xxx.xxx.133.92 port 65458 connected with xxx.xxx.186.109 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-10.0 sec  1.98 GBytes  1.70 Gbits/sec

Bandwidth test over zerotier Network in both client server mode

root@server-01:~# iperf -s
------------------------------------------------------------
Server listening on TCP port 5001
TCP window size: 85.3 KByte (default)
------------------------------------------------------------
[  4] local 172.16.2.1 port 5001 connected with 172.16.2.2 port 59358
[ ID] Interval       Transfer     Bandwidth
[  4]  0.0-10.2 sec  33.2 MBytes  27.3 Mbits/sec

[  4] local 172.16.2.1 port 5001 connected with 172.16.2.2 port 59362
[  4]  0.0-10.2 sec  26.2 MBytes  21.6 Mbits/sec

***** ( slowest bandwidth above) ***** 

root@eu-01-app-01:~# iperf -c 172.16.2.2
------------------------------------------------------------
Client connecting to 172.16.2.2, TCP port 5001
TCP window size:  128 KByte (default)
------------------------------------------------------------
[  3] local 172.16.2.1 port 48560 connected with 172.16.2.2 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-10.0 sec  1.04 GBytes   889 Mbits/sec

if direction is changed, bandwidth improves significantly

Zerotier Version: 1.2.12

Both are part of Zerotier-one network.

**Comment by adamierymenko** [comment]
What does the network look like between these endpoints? Is there anything in the way like:

 * A "sophisticated" NAT or Carrier Grade NAT

 * A QoS-enforcing router

 * SD-WAN (someone else's like VeloCloud or Viptela)

 * A multipath Internet connection

**Comment by quivalen** [comment]
@devbhosale can you check CPU usage during the transfer on both sender and receive?
Also state the machine differs in terms of CPU (take into account cores, Ghz, AND features set

@adamierymenko Does Zerotier depends heavilty on aes-ni instruction ?

**Comment by qlikq** [comment]
Hello, i have similar, 2 ZT endpoints on Windows 10, cpu util 5-10 % during iperf test, and i have 20-30 mbit/s on 200/200 mbit/s uplink.  After switching to ZT , we have 20-30 mbit/s. Our connection is Netherlands - Poland. On both sides: "tcpFallbackActive": false .

**Comment by joseph-henry** [comment]
Closing due to age and lack of response. If this is still an issue you are experiencing please reopen. @qlikq If you are still having similar issues please open another ticket and we can discuss there. Thanks.
