### ISSUE TITLE
https://www.zerotier.com/ is down !!!

### ISSUE THREAD

**Issue by cocoflan** [zerotier/ZeroTierOne#954]
website is down !!!!
**Alternative, faster ways to get help**
If you have just started using ZeroTier, here are some places to get help:
- my.zerotier.com has a _Community_ tab. It's a live chat with other users and the developers. 
- [ZeroTier Knowledge Base](https://zerotier.atlassian.net/wiki/spaces/SD/overview)
- www.zerotier.com has a Contact Us button
- email contact@zerotier.com

**Describe the bug**

**To Reproduce**
1. Create a Network '...'
2. Install zerotier-one '....'
3. '....'

**Expected behavior**

**Screenshots**
If applicable, add screenshots or console output to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Mac, Linux, Windows, BSD]
 - OS/Distribution Version
 - ZeroTier Version [e.g. 1.2.4]
 - Hardware [e.g. raspberry pi 3]
 
**Smartphone (please complete the following information):**
 - Version [e.g. 1.2.4]

**Additional context**
- ZeroTier Network Configuration
- Router Config
- Firewall Config (try turning the firewall off)
- General Network Environment: [ e.g Home, University Campus, Corporate LAN ]

**Comment by flyingchipmunk** [comment]
and not just the website, I can't connect to any of my networks.

**Comment by glimberg** [comment]
Yes, we're aware. This is due to the current & ongoing Google Cloud issues https://status.cloud.google.com/

All clients that have been online the entire time are fine.  Any newly turned on clients, or newly joined clients will have to wait until Google resolves their issues.
