### ISSUE TITLE
about windows SDK

### ISSUE THREAD

**Issue by wmdfy** [zerotier/ZeroTierOne#955]
dear
The Windows platform SDK whether still have update?
thanks.

**Comment by laduke** [comment]
https://github.com/zerotier/libzt/ ?

**Comment by joseph-henry** [comment]
@wmdfy, yes I will issue and update soon.

**Comment by wmdfy** [comment]
> https://github.com/zerotier/libzt/？
No, I mean this.https://github.com/zerotier/ZeroTierOne/tree/master/windows/ZeroTierOneSDK

**Comment by glimberg** [comment]
I think that's just old test code, possibly.  It's not something actively used or under development.  I don't know what the purpose of it is or was supposed to be.

The only SDK we have available was linked above:  https://github.com/zerotier/libzt/

**Comment by wmdfy** [comment]
> Just looking through the history of that because I didn't recognize it. It appears to be a DLL export of https://github.com/zerotier/ZeroTierOne/blob/master/include/ZeroTierOne.h contributed by a customer for something they use it for. It's not something we actively use or develop.

all right.I just want to easy integration into other software in the system

**Comment by joseph-henry** [comment]
Can you describe your system? What languages are you using? What's the application? With these questions answered we can point you in the right direction.

**Comment by wmdfy** [comment]
> 你能描述一下你的系统吗？你用的是哪种语言？什么是申请？回答这些问题后，我们可以指出正确的方向。

I am trying to use VB to make an online gaming platform

**Comment by joseph-henry** [comment]
Why VB?

**Comment by wmdfy** [comment]
> 为何选择VB？
/(ㄒoㄒ)/~~
Because of just and friends interested, I am not programmer, programming related training
