### ISSUE TITLE
Windows 10 Join Network on GUI with blank box

### ISSUE THREAD

**Issue by Oofles** [zerotier/ZeroTierOne#958]
**Describe the bug**
When I first install ZeroTier One (v 1.2.12) on Windows 10, it will prompt for a login. Once logged in, it will present the interface shown in the screenshot. You are unable to join a network using this interface, and have to close and use the toolbar functionality to join a network. 

**To Reproduce**
1. Install ZeroTier via the .msi
2. Login or create a new account
3. See error

**Expected behavior**
I feel like you should be able to type a network to join from this point.

**Screenshots**
![image](https://user-images.githubusercontent.com/29664630/59375184-384d5d00-8d13-11e9-872b-1a9b96fc55f1.png)

**Desktop (please complete the following information):**
 - OS: WIndows 10 Pro x64
 - OS/Distribution Version: 1809
 - ZeroTier Version: 1.2.12 
 - Hardware: Custom PC Build

**Comment by laduke** [comment]
Until the next release, use [zerotier-cli](https://zerotier.atlassian.net/wiki/spaces/SD/pages/29065282/zerotier-cli)
