### ISSUE TITLE
http://download.zerotier.com/ZeroTierOneInstaller-linux-x?? returned 404

### ISSUE THREAD

**Issue by qwerty250** [zerotier/ZeroTierOne#960]
**Alternative, faster ways to get help**
If you have just started using ZeroTier, here are some places to get help:
- my.zerotier.com has a _Community_ tab. It's a live chat with other users and the developers. 
- [ZeroTier Knowledge Base](https://zerotier.atlassian.net/wiki/spaces/SD/overview)
- www.zerotier.com has a Contact Us button
- email contact@zerotier.com

**Describe the bug**
Tutor for Unix-like systems in Wiki give the link http://download.zerotier.com/ZeroTierOneInstaller-linux-x?? to download the script, but the link returned 404 not found.

**To Reproduce**
1. Create a Network '...'
2. Install zerotier-one '....'
3. '....'

**Expected behavior**
A downloadable script.

**Screenshots**
If applicable, add screenshots or console output to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Mac, Linux, Windows, BSD]
 - OS/Distribution Version
 - ZeroTier Version [e.g. 1.2.4]
 - Hardware [e.g. raspberry pi 3]
 
**Smartphone (please complete the following information):**
 - Version [e.g. 1.2.4]

**Additional context**
- ZeroTier Network Configuration
- Router Config
- Firewall Config (try turning the firewall off)
- General Network Environment: [ e.g Home, University Campus, Corporate LAN ]

**Comment by laduke** [comment]
Which tutorial? 

On linux you typically use the install script here: https://www.zerotier.com/download.shtml

**Comment by qwerty250** [comment]
> Which tutorial?
> 
> On linux you typically use the install script here: https://www.zerotier.com/download.shtml

https://github.com/zerotier/ZeroTierOne/wiki/Unix-Like-OS-Users'-Guide

**Comment by laduke** [comment]
Thanks. I removed that outdated info from the wiki.
