### ISSUE TITLE
Can't assign IPv6 address automatically

### ISSUE THREAD

**Issue by dfc643** [zerotier/ZeroTierOne#961]
**Describe the bug**
Can't assign IPv6 address to TAP adapter in Windows automatically.
but assigned IPv6 after disable and re-enable TAP manually.

**To Reproduce**
1. Create a Network '...' with IPv6 supports
2. Install zerotier-one '....' and join network in Windows
3. Restart computer

**Expected behavior**
Assign IPv6 address for TAP adapter automatically when computer restarted.

**Screenshots**
If applicable, add screenshots or console output to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - ZeroTier Version 1.2.12
 - Hardware H110+G4560
 
**Additional context**
- ZeroTier Network Configuration
- Router Config
- Firewall Config (try turning the firewall off)
- General Network Environment: Home and Corporate

**Comment by dfc643** [comment]
But  working fine in Windows 10 1809

**Comment by laduke** [comment]
Which type of IPv6 ?
<img width="386" alt="Screen Shot 2019-11-04 at 8 38 54 PM" src="https://user-images.githubusercontent.com/11598/68179071-33e44380-ff43-11e9-90b6-b935ad953560.png">

**Comment by dfc643** [comment]
> Which type of IPv6 ?
> <img alt="Screen Shot 2019-11-04 at 8 38 54 PM" width="386" src="https://user-images.githubusercontent.com/11598/68179071-33e44380-ff43-11e9-90b6-b935ad953560.png">

ZeroTier RFC4193

**Comment by unquietwiki** [comment]
Hey @dfc643 I'm going over GitHub issues as we prepare for 1.6.0. Did you ever update your Windows 8.1 box to use 1.4.6, and have you had any problems in the past 10 months?

**Comment by dfc643** [comment]
> Hey @dfc643 I'm going over GitHub issues as we prepare for 1.6.0. Did you ever update your Windows 8.1 box to use 1.4.6, and have you had any problems in the past 10 months?

thanks for your replying, 10 months ago, i have upgraded to windows 10 without any problem, but i cannot confirm it works fine in windows 8.1 or not now.

**Comment by unquietwiki** [comment]
@laduke heads up. I was assigned on a few of these. If I get any other follow-up, I'll let you know. Thanks.

**Comment by joseph-henry** [comment]
Closing due to age. If you still experience this issue please re-open. Thanks.
