### ISSUE TITLE
Not start on Raspberry pi on archlinux 

### ISSUE THREAD

**Issue by KP3AV** [zerotier/ZeroTierOne#962]
I Use:
[root@RaspBerryPI ~]# pacman -U zerotier-one-1.2.12-1-armv7h.pkg.tar.xz
loading packages...
warning: zerotier-one-1.2.12-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) zerotier-one-1.2.12-1

Total Installed Size:  1.15 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                                                                         [#######################################################################] 100%
(1/1) checking package integrity                                                                                       [#######################################################################] 100%
(1/1) loading package files                                                                                            [#######################################################################] 100%
(1/1) checking for file conflicts                                                                                      [#######################################################################] 100%
(1/1) checking available disk space                                                                                    [#######################################################################] 100%
:: Processing package changes...
(1/1) reinstalling zerotier-one                                                                                        [#######################################################################] 100%

When i tried start:

systemctl status zerotier-one.service

* zerotier-one.service - ZeroTier One
   Loaded: loaded (/usr/lib/systemd/system/zerotier-one.service; enabled; vendor preset: disabled)
   Active: inactive (dead) (Result: exit-code) since Fri 2019-06-28 09:44:44 AST; 7min ago
  Process: 11054 ExecStart=/usr/bin/zerotier-one (code=exited, status=127)
 Main PID: 11054 (code=exited, status=127)

Jun 28 09:44:43 RaspBerryPI systemd[1]: zerotier-one.service: Unit entered failed state.
Jun 28 09:44:43 RaspBerryPI systemd[1]: zerotier-one.service: Failed with result 'exit-code'.
Jun 28 09:44:44 RaspBerryPI systemd[1]: zerotier-one.service: Service hold-off time over, scheduling restart.
Jun 28 09:44:44 RaspBerryPI systemd[1]: Stopped ZeroTier One.
Jun 28 09:44:44 RaspBerryPI systemd[1]: zerotier-one.service: Start request repeated too quickly.
Jun 28 09:44:44 RaspBerryPI systemd[1]: Failed to start ZeroTier One.

[root@RaspBerryPI ~]# zerotier-cli info
zerotier-cli: error while loading shared libraries: libminiupnpc.so.17: cannot open shared object file: No such file or directory

Any Help....

**Comment by trobotham** [comment]
looks like you are missing libminiupnpc17, I would advise to try installing that and try starting zerotier again.

**Comment by KP3AV** [comment]
zerotier-one info
zerotier-one: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by zerotier-one)

**Comment by trobotham** [comment]
ZeroTier requires libstdc++6 in order to run, if you do not have it installed, you will get said error.

**Comment by KP3AV** [comment]
I reinstall zeroTier an Relocate the libminiupnpc17 and this is the new error...

**Comment by KP3AV** [comment]
Any other package to ArchLinux to armv7h

http://mirror.archlinuxarm.org/armv7h/community/zerotier-one-1.2.12-1-armv7h.pkg.tar.xz
