### ISSUE TITLE
[CLEANUP] cppcheck 1.88 analysis of current master (1.40-pre)

### ISSUE THREAD

**Issue by unquietwiki** [zerotier/ZeroTierOne#965]
Ran [cppcheck](http://cppcheck.sourceforge.net/) 1.88 against the current master codebase (1.40-pre). Found some errors; the unused variable warnings can probably be ignored. Ran check as POSIX, to improve the chance of finding stuff that wouldn't work cross-platform.

**cppcheck --enable=all --force --inconclusive --std=posix -I Include . 2> ../zerotier-cppcheck.txt**

[zerotier-cppcheck.txt](https://github.com/zerotier/ZeroTierOne/files/3358283/zerotier-cppcheck.txt)

**Comment by unquietwiki** [comment]
[zerotier-cppcheck.txt](https://github.com/zerotier/ZeroTierOne/files/3475632/zerotier-cppcheck.txt) Roughly 20 errors & 20 warnings on latest scan.

**Comment by adamierymenko** [comment]
I installed cppcheck and have done some cleanup in the `edge` branch with it -- will keep using it to audit the code and tidy it up a bit.
