### ISSUE TITLE
Compiling on Centos 7 arm 

### ISSUE THREAD

**Issue by mashiro2004** [zerotier/ZeroTierOne#966]
Hi, I'm trying to compile on centos 7 arm.
Hardware is Raspberry Pi 3b+

The gcc version is too old, as described in the readme. If I use clang initially it gives me an error:
*** FATAL: architecture could not be determined from clang -dumpmachine: C_MACH. Stop.

If instead I try to force the variable ZT_ARCHITECTURE = 3 I get this error:

5 -mno-unaligned-access -marm -c -o node / C25519.o node / C25519.cpp
clang: warning: unknown platform, assuming -mfloat-abi = soft
clang: warning: unknown platform, assuming -mfloat-abi = soft
clang: warning: unknown platform, assuming -mfloat-abi = soft
In file included from node / C25519.cpp: 10:
In file included from /usr/bin/../lib/clang/3.4.2/include/stdint.h:64:
In file included from /usr/include/stdint.h:25:
In file included from /usr/include/features.h:399:
/usr/include/gnu/stubs.h:7:11: fatal error: 'gnu / stubs-soft.h' file not found
# include <gnu / stubs-soft.h>
           ^
1 error generated.
make: *** [node / C25519.o] Error 1

Any help is well appreciated
Thank you
Simone

**Comment by adamierymenko** [comment]
Honestly I'm starting to say that CentOS 7 is not natively supported for builds. The compilers and stuff on this platform are **ancient**.
