### ISSUE TITLE
Repeated "The request timed out." messages from macOS client

### ISSUE THREAD

**Issue by Intensity** [zerotier/ZeroTierOne#967]
**Describe the bug**

While using the ZeroTier UI on macOS (in my case Mojave, but I've seen this before in earlier OS versions), after a day or a few hours of connecting to a ZeroTier network (that is, normal usage - but with timeout from a peer), I see a "The request timed out." prompt pop up.

It may very well be that the request timed out (see below). However I'm not sure why I would need to be prompted here. I ended up getting dozens of those popups in a row, after I repeatedly choose "Retry". This is mainly a usability / user experience report, but this may open up other considerations about how to respond internally in the code when a peer connection attempt times out in this way.

I'm wondering if the dialog could be suppressed altogether, since I'm not sure what choice the user needs to be presented with. From my perspective, when I've seen this before, I've chosen Retry for a few times in a row, and then when I choose Quit, I end up launching the ZeroTier UI again anyway. Even if the dialog box needs to be presented, maybe one or two per hour is enough. Or there could be a checkbox allowing the user to choose "always retry".

In my case, I may have come across this more commonly than others because I use Little Snitch in prompting mode - to accumulate a list of valid nearby ZeroTier peers that can eventually be whitelisted when I connect from a certain network starting point. Although, I'm not always in front of the computer to answer in the affirmative. I'll assume that this is the uncommon trigger that's causing the error to show itself, but nevertheless I wonder if the prompt is needed at all. For other users, the error might crop up occasionally. I would be ok with a default policy to perpetually retry a connection, or to try the next peer in sequence.

_(As an aside, maybe by compiling ZeroTier in tracing mode, I'll be able to accumulate the same list of peers)._

**To Reproduce**
1. Create a Network
2. Install zerotier-one and UI on macOS
3. Install Little Snitch to operate in prompting mode, and after allowing a few peers, let a prompt (for an outbound UDP connection request from ZeroTier) time out
4. Observe the UI message

**Expected behavior**
I'd prefer to perpetually retry, or to retry with the next peer, unless there's a downside to doing this. As I see it this wouldn't consume excessive CPU, or network bandwidth.

**Screenshots**
The error string ought to pinpoint the related code path, but let me know if I can clarify. The dialog box shows just what I mentioned; it's pretty straightforward.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS/Distribution Version: Mojave
 - ZeroTier Version: 1.2.12
 - Hardware: Mac
 
**Smartphone (please complete the following information):**
N/A

**Additional context**
- Permissive corporate LAN with IPv6 connectivity too
- As mentioned main trigger of this might be the use of LS. Operating as a kernel extension, it might let certain network calls time out in a way that's not usual, and so triggering the error message.

**Comment by laduke** [comment]
This dialog?
![Screen Shot 2019-07-09 at 9 48 28 AM](https://user-images.githubusercontent.com/11598/60907586-c04d5680-a22e-11e9-8f35-2778e11c24b5.png)

I don't think the UI knows anything about peers. It only connects to http://localhost:9993, the control api for the zerotier-one service. 

I'd guess littlesnitch is causing the zerotier-one service to hiccup and then the UI errors.

**Comment by Intensity** [comment]
Yes - that's the dialog.

Sounds like there is an issue attempting to connect to localhost due to LS, as you suggest.
