### ISSUE TITLE
ZeroTier One service listening 9993 but not replying anything

### ISSUE THREAD

**Issue by Jamesits** [zerotier/ZeroTierOne#968]
**Describe the bug**
ZeroTier One daemon is listening on TCP 9993:

```
# ss -tulpn | grep zerotier
udp    UNCONN     0      0      10.189.15.2%eth0:9993                  *:*                   users:(("zerotier-one",pid=383,fd=8))
udp    UNCONN     0      0      10.189.15.2%eth0:55007                 *:*                   users:(("zerotier-one",pid=383,fd=10))
udp    UNCONN     0      0      10.189.15.2%eth0:55008                 *:*                   users:(("zerotier-one",pid=383,fd=12))
tcp    LISTEN     0      128    10.189.15.2%eth0:9993                  *:*                   users:(("zerotier-one",pid=383,fd=9))
tcp    LISTEN     0      128    127.0.0.1:9993                  *:*                   users:(("zerotier-one",pid=383,fd=6))
tcp    LISTEN     0      128    10.189.15.2%eth0:55007                 *:*                   users:(("zerotier-one",pid=383,fd=11))
tcp    LISTEN     0      128    10.189.15.2%eth0:55008                 *:*                   users:(("zerotier-one",pid=383,fd=13))
```

But it is not replying to any requests:

```
# zerotier-cli info
Error connecting to the ZeroTier service: 

Please check that the service is running and that TCP port 9993 can be contacted via 127.0.0.1.
# curl -Lv 127.0.0.1:9993
* Rebuilt URL to: 127.0.0.1:9993/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 9993 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:9993
> User-Agent: curl/7.52.1
> Accept: */*
> 
* Curl_http_done: called premature == 0
* Empty reply from server
* Connection #0 to host 127.0.0.1 left intact
curl: (52) Empty reply from server
```

**To Reproduce**
1. Used the official script to install ZeroTier One

**Expected behavior**
zerotier-one daemon should reply API requests on port 9993

**Desktop (please complete the following information):**
 - OS: Linux
 - OS/Distribution Version: Debian 9
 - ZeroTier Version: 1.2.12
 - Hardware: VM
 
**Additional context**
* I don't think there is a way to reproduce it, only one of my servers had this issue
* Already tried rebooting, flushing iptables rules, purging and reinstalling zerotier-cli package
* Cannot find any log anywhere

**Comment by laduke** [comment]
If it's not the firewall, usually it's something in /etc/hosts

**Comment by Jamesits** [comment]
@laduke this is my `/etc/hosts`:

```
127.0.0.1  localhost  localhost.localdomain  yici-router
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

iptables have no filter rules and all defaults set to ACCEPT.

**Comment by MrFox42** [comment]
I have the same issue, using Debian Buster on a Raspberry 4, on relatively fresh system. ZeroTier installed from repo (install script).

ZeroTier is listening on 9993, telnet connects fine, curl response is empty or `"{}"` to every request.

**Comment by Jamesits** [comment]
More information on my case:

I used a VPS from Qcloud (cloud service by Tencent) with their default Debian 9 template. This bug only appears if I enable the "use as a router" option when creating the VPS. Reinstalling the same VPS without that option enabled, and ZeroTier One works flawlessly. 

AFAIK that option sets `net.ipv4.forwarding=1` and creates a `MASQUERADE` rule for all ports in iptables. I tried to manually flush iptables rules but the problem still exists. I don't know what other things that option would change -- they have little documentation on this.

**Comment by MrFox42** [comment]
Looks like this issue is only happening on my end, when a resource-heavy process is running in the background.

**Comment by connected201** [comment]
> 
> 
> **Describe the bug**
> ZeroTier One daemon is listening on TCP 9993:
> 
> ```
> # ss -tulpn | grep zerotier
> udp    UNCONN     0      0      10.189.15.2%eth0:9993                  *:*                   users:(("zerotier-one",pid=383,fd=8))
> udp    UNCONN     0      0      10.189.15.2%eth0:55007                 *:*                   users:(("zerotier-one",pid=383,fd=10))
> udp    UNCONN     0      0      10.189.15.2%eth0:55008                 *:*                   users:(("zerotier-one",pid=383,fd=12))
> tcp    LISTEN     0      128    10.189.15.2%eth0:9993                  *:*                   users:(("zerotier-one",pid=383,fd=9))
> tcp    LISTEN     0      128    127.0.0.1:9993                  *:*                   users:(("zerotier-one",pid=383,fd=6))
> tcp    LISTEN     0      128    10.189.15.2%eth0:55007                 *:*                   users:(("zerotier-one",pid=383,fd=11))
> tcp    LISTEN     0      128    10.189.15.2%eth0:55008                 *:*                   users:(("zerotier-one",pid=383,fd=13))
> ```
> 
> But it is not replying to any requests:
> 
> ```
> # zerotier-cli info
> Error connecting to the ZeroTier service: 
> 
> Please check that the service is running and that TCP port 9993 can be contacted via 127.0.0.1.
> # curl -Lv 127.0.0.1:9993
> * Rebuilt URL to: 127.0.0.1:9993/
> *   Trying 127.0.0.1...
> * TCP_NODELAY set
> * Connected to 127.0.0.1 (127.0.0.1) port 9993 (#0)
> > GET / HTTP/1.1
> > Host: 127.0.0.1:9993
> > User-Agent: curl/7.52.1
> > Accept: */*
> > 
> * Curl_http_done: called premature == 0
> * Empty reply from server
> * Connection #0 to host 127.0.0.1 left intact
> curl: (52) Empty reply from server
> ```
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
>     1. Used the official script to install ZeroTier One
> 
> 
> **Expected behavior**
> zerotier-one daemon should reply API requests on port 9993
> 
> **Desktop (please complete the following information):**
> 
>     * OS: Linux
> 
>     * OS/Distribution Version: Debian 9
> 
>     * ZeroTier Version: 1.2.12
> 
>     * Hardware: VM
> 
> 
> **Additional context**
> 
>     * I don't think there is a way to reproduce it, only one of my servers had this issue
> 
>     * Already tried rebooting, flushing iptables rules, purging and reinstalling zerotier-cli package
> 
>     * Cannot find any log anywhere
i have same problem!
