### ISSUE TITLE
ZT Windows client can't connect to other client under ZT router.

### ISSUE THREAD

**Issue by Tennyleaz** [zerotier/ZeroTierOne#969]
**Describe the bug**
I set up an openwrt router with zerotier:

![pic1](https://user-images.githubusercontent.com/7089271/61206819-171ec880-a726-11e9-9d71-28de502b5314.png)

`10.144.0.209` is the ZT ip of my router. The router enables bridging:

![pic](https://user-images.githubusercontent.com/7089271/61207624-2141c680-a728-11e9-8634-08d50829e2f8.png)

I could successfully connect to any IP `172.22.1.1/24` under the router, with my Android phone as another zerotier client via 4G network.

However I have issue connecting using a Windows client:
![pic2](https://user-images.githubusercontent.com/7089271/61206964-767cd880-a726-11e9-8279-5b0e56cef774.png)
`10.144.88.55` is the ZT ip of my Windows client. 
I could access my ZT router IP `10.144.0.209`, or other ZT clients, but I cannot connect or ping any IP `172.22.1.1/24` under that router.
For example, `172.22.1.1` is the lan address of my router. 
If I try `tracert 172.22.1.1`:

    C:\WINDOWS\system32>tracert 172.22.1.1
      1    <1 ms    <1 ms    <1 ms  my.router [10.10.15.241]
      2     1 ms     2 ms     2 ms  172.22.1.1

It seems that my lan gateway `10.10.15.241` is hijacking the route.

Info from zerotier-cli on Windows client:

    C:\WINDOWS\system32>zerotier-cli info
    200 info ef51c862db 1.2.12 TUNNELED

**Expected behavior**
I expect the Windows client could access IP under my zerotier router.

**Desktop (please complete the following information):**
 - OS: Windows 10 1903
 - ZeroTier One 1.2.12
 

**Additional context**
- General Network Environment: My Windows client is in an office lan network.

**Comment by Tennyleaz** [comment]
Graph of my network setup:

![zerotier graph](https://user-images.githubusercontent.com/7089271/61262750-edfb4800-a7b8-11e9-9f50-4f5c28c1ee96.png)

**Comment by Tennyleaz** [comment]
It seems that I need to manually add a route on Windows client.
I use:

    route add 172.22.0.0 MASK 255.255.0.0 10.144.0.209 IF 35
              ^subnet                      ↑               ^number of ZT interface
                                           ip of my openwrt gateway router

After that I could successfully trace route:

    C:\WINDOWS\system32>tracert 172.22.2.2
      1   215 ms   124 ms   115 ms  10.144.0.22
      2   122 ms   117 ms   116 ms  172.22.1.2

**Comment by laduke** [comment]
ZeroTier should add it...
What does the routing table look like on your workplace machine (without zerotier joined)?

**Comment by Tennyleaz** [comment]
My routing table was like:

    C:\Windows\System32>route print
    ===========================================================================
    Interface List
     36...8a 10 89 7d 23 52 ......ZeroTier One Virtual Port
     34...0a 00 27 00 00 22 ......VirtualBox Host-Only Ethernet Adapter #3
      2...3e 6a a7 52 e8 15 ......Microsoft Wi-Fi Direct Virtual Adapter #2
     30...3c 6a a7 52 e8 16 ......Microsoft Wi-Fi Direct Virtual Adapter #4
      5...3c 6a a7 52 e8 15 ......Intel(R) Wireless-AC 9260 160MHz
     26...00 ff 8f b7 53 88 ......AnchorFree TAP-Windows Adapter V9
     19...e0 d5 5e ad c5 d6 ......Intel(R) I211 Gigabit Network Connection
      4...00 ff 0b 02 0c b6 ......TAP-Windows Adapter V9
      1...........................Software Loopback Interface 1
    ===========================================================================
    
    IPv4 Route Table
    ===========================================================================
    Active Routes:
    Network Destination        Netmask          Gateway           Interface Metric
              0.0.0.0          0.0.0.0     10.10.15.241         10.10.12.48     35
            10.10.8.0    255.255.248.0          On-link       10.10.12.48    556
          10.10.12.48  255.255.255.255          On-link       10.10.12.48    556
         10.10.15.255  255.255.255.255          On-link       10.10.12.48    556
           10.144.0.0      255.255.0.0          On-link      10.144.88.55    257
         10.144.88.55  255.255.255.255          On-link      10.144.88.55    257
       10.144.255.255  255.255.255.255          On-link      10.144.88.55    257
            127.0.0.0        255.0.0.0          On-link         127.0.0.1    331
            127.0.0.1  255.255.255.255          On-link         127.0.0.1    331
      127.255.255.255  255.255.255.255          On-link         127.0.0.1    331
         192.168.56.0    255.255.255.0          On-link      192.168.56.1    281
         192.168.56.1  255.255.255.255          On-link      192.168.56.1    281
       192.168.56.255  255.255.255.255          On-link      192.168.56.1    281
            224.0.0.0        240.0.0.0          On-link         127.0.0.1    331
            224.0.0.0        240.0.0.0          On-link      192.168.56.1    281
            224.0.0.0        240.0.0.0          On-link       10.10.12.48    556
            224.0.0.0        240.0.0.0          On-link      10.144.88.55    257
      255.255.255.255  255.255.255.255          On-link         127.0.0.1    331
      255.255.255.255  255.255.255.255          On-link      192.168.56.1    281
      255.255.255.255  255.255.255.255          On-link       10.10.12.48    556
      255.255.255.255  255.255.255.255          On-link      10.144.88.55    257
    ===========================================================================

**Comment by Tennyleaz** [comment]
I also tried install zerotier one on debian.
I seems that no additional rules are added. Maybe another bug? @laduke

    tenny@debian:~$ sudo route
    Kernel IP routing table
    Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
    default         10.10.15.241    0.0.0.0         UG    100    0        0 enp1s0
    10.10.8.0       0.0.0.0         255.255.248.0   U     100    0        0 enp1s0
