### ISSUE TITLE
Duplicated Windows 10 VM

### ISSUE THREAD

**Issue by audiotecnicality** [zerotier/ZeroTierOne#970]
I duplicated a Windows 10 virtual machine which has been set up with ZeroTier One.  When I bring up the new VM instance, it has the same NodeID.  I'd like to generate a new one so the two VM's aren't using the same one.

Very similar to this issue: https://github.com/zerotier/ZeroTierOne/issues/477 but for Windows.

TIA!

**Comment by laduke** [comment]
On Windows, the zerotier home is usually "\ProgramData\ZeroTier\One

https://zerotier.atlassian.net/wiki/spaces/SD/pages/327693/How+to+Clear+Reset+your+ZeroTier+Address

**Comment by audiotecnicality** [comment]
Worked perfectly.  I was only deleting the files in \Users\MYUSER\AppData\Local\ZeroTier\One, and it wasn't working.  Thanks!

**Comment by laduke** [comment]
nice!
