### ISSUE TITLE
Route via Multiple

### ISSUE THREAD

**Issue by M-Pixel** [zerotier/ZeroTierOne#971]
I'm setting up access to a LAN member using "Managed Routes" on my.zerotier.com.  It's not clear to me from the minimal documentation on routes if I'm able to add multiple routes to the same destination.  If not, then it would be a good feature to have.  In my case, the primary goal of having multiple routes to the same destination is redundancy - if one ZeroTier client on the LAN goes offline, another ZeroTier client may still ensure outside access to the destination.

**Comment by adamierymenko** [comment]
I believe you can, but which one gets used is kind of an OS-specific thing. Some OSes don't seem to really obey metrics.
