### ISSUE TITLE
Strange issue with zt using the wrong address

### ISSUE THREAD

**Issue by joewholden** [zerotier/ZeroTierOne#972]
**Describe the bug**
Simple 2-device network, one host is dual stacked whereas the other is v4 only (behind nat) - the dual stacked node has routable addresses on both outside and inside interfaces and for some reason I'm seeing the v4 only device try to connect to the inside address and zt doesn't appear to reply (perhaps its expecting udp/9993 on the outside interface)

I observe the same result with or without any iptables rules on the dual stacked device, however udp/9993 is already allowed as this device participates in other networks. The other device is a Windows 10 machine.  Although this appears to be an address selection or reporting issue rather than a firewall related one.

Not sure how to enable debug in zt to figure out why it's choosing that address or how to get a dump of addresses reported to my.zerotier.com controller...

Running 1.2.12 on both devices.

**Comment by joewholden** [comment]
"Fixed" with using bind in local.conf, although theres something wrong if its using the wrong address...

**Comment by adamierymenko** [comment]
What are the interfaces on the system called? Can you post some info about them?

**Comment by joewholden** [comment]
eth0 -> wan, eth1 remains the same, the address its picking is on an interface named 'routed' (eth1.X, tagged interface)
