### ISSUE TITLE
S390 support

### ISSUE THREAD

**Issue by Nayana-ibm** [zerotier/ZeroTierOne#976]
Hello,
Want to know about CI infrastructure of ZeroTierOne.  
Also, wondering if there is any plan to support s390x arch,  binaries for s390x.

To add support for s390x architecture, we would like to join ZeroTierOne CI . Can provide s390x vms too.
Please let us know.

**Comment by Nayana-ibm** [comment]
@adamierymenko @joseph-henry Could you guide us on this?

**Comment by glimberg** [comment]
We have no public continuous integration infrastructure

**Comment by adamierymenko** [comment]
Which Linux distribution(s) do you use with s390?

**Comment by Nayana-ibm** [comment]
@adamierymenko We use Ubuntu 16.04, 18.04, 19.04 ,  RHEL 7.x and SLES distributions

**Comment by adamierymenko** [comment]
I'll see if we can get s390x. Right now for builds we use a whole bunch of qemu-chroot environments and it **should** emulate that architecture okay.

**Comment by adamierymenko** [comment]
Okay, we have s390x qemu-chroot environments now for Debian buster and stretch, Ubuntu bionic and disco, CentOS/RHEL 7 for s390x. We could not get the older ubuntu to run in qemu-chroot so we'll skip that one.

**Comment by adamierymenko** [comment]
1.4.2 will include s390 for all but the 16.04 Ubuntu release since we couldn't get that one to work.

**Comment by Nayana-ibm** [comment]
@adamierymenko Thanks for your help!

**Comment by Nayana-ibm** [comment]
@adamierymenko Now I could see that the s390x binaries are available on 
https://download.zerotier.com/debian/bionic/dists/bionic/main/
https://download.zerotier.com/debian/bionic/pool/main/z/zerotier-one/

Will it be possible to specify s390x arch in release notes on main download page : https://www.zerotier.com/download/
