### ISSUE TITLE
Extend the API for network members with writable name, and readable last seen and physical IP parameters

### ISSUE THREAD

**Issue by MrFox42** [zerotier/ZeroTierOne#981]
**my.zerotier.com** allows me to set a custom name and description for network members individually, and also provides information like *last seen* and *physical IP*. However, these properties are missing from the self-hosted controller's API.

Are these parameters intentionally left out from the API?

**Comment by laduke** [comment]
Hi, they don't exist in the controller api; The Central api is built on top of the Controller api and those extra properties are stored in a different database.
