### ISSUE TITLE
Periodic packet loss between two hosts

### ISSUE THREAD

**Issue by bogaurd** [zerotier/ZeroTierOne#984]
I have a ZT network with a number of hosts connected (all machines have zt installed and connected to this network)

* WAN1
  * vmhost1
    * vm1
    * vm2
    * vm3
    * vm4
  * server1
* WAN2
  * server2
* WAN3
  * server3
* WAN4
  * workstation1
  * workstation2

For the most part, everything works great. However, I have strange issues with a couple of hosts in particular;

When workstation1 tries to reach vm3, packet loss is very high (>30%) as a result of multi-second periods where no data flows. workstation1 has no issues with any of the other vms, and communication between all other nodes appears fine. workstation2 has no issues with packet loss to vm3, despite being connected to the same network & internet connection as workstation1.

All hosts are x64, with all servers & vms (inc vmhost) running Ubuntu 18.04. The vms are all docker hosts and both workstations are Windows 10 machines, all hosts are running zt 1.2.12.

No devices are behind more than a single layer of NAT, the virtual machines are bridged to the physical interface of vmhost. No outbound rules are active on any of the networks, the machines have unrestricted access to the internet.

Latency over ZT between all hosts is great, even workstation1 -> vm3 is fine until it starts dropping packets.

I have watched the output of `zerotier-cli listpeers` on both ends and everything looks right, even when data flow stops.

Not sure what to try next - is it possible to access verbose logs from zerotier?

**Comment by adamierymenko** [comment]
Do you still observe this with the recently released 1.4.0?

**Comment by bogaurd** [comment]
> Do you still observe this with the recently released 1.4.0?

I upgraded the two hosts in question to 1.4.0 and the issue appears to have been resolved.

Great work team ZT. Any thoughts on what might have been causing the issue @adamierymenko?
