### ISSUE TITLE
macOS hosts unreachable v1.4.0

### ISSUE THREAD

**Issue by Fastidious** [zerotier/ZeroTierOne#985]
**Describe the bug**
After upgrading to v1.4.0, I cannot connect to macOS hosts.

**To Reproduce**
1. Upgrade to Zerotier v1.4.0 on macOS (tested on High Sierra and Mojave) 
2. Try to connect to such macOS machines
3. Host will not be found, unreachable.

**Expected behavior**
Expect all hosts to be reachable, as they were before upgrade.

**Desktop (please complete the following information):**
 - OS: [e.g. Mac, Linux, Windows, BSD]: macOS (latest High Sierra, latest Mojave)
 - OS/Distribution Version: 10.14.6 (18G84)
 - ZeroTier Version [e.g. 1.2.4]: 1.4.0
 - Hardware [e.g. raspberry pi 3]: iMac
 
**Additional context**
- ZeroTier Network Configuration: Running Zerotier controller

Linux machines upgraded to 1.4.0 can talk to each other fine. I can also establish communications amongst macOS Zerotier v1.2.x and Linux 1.4.0. The problem seems related to Zerotier v1.4.0 under macOS.

**Comment by Fastidious** [comment]
Hm, there might be something else. Cancelling, will open a new one after I fully test this.

**Comment by adamierymenko** [comment]
Can you check to ensure that the interfaces are being created on MacOS? This version uses the `feth` virtual Ethernet device feature in Darwin instead of the old kernel extension. We have tested this extensively but it has not yet been tested by a lot of outsiders.

**Comment by Fastidious** [comment]
The interfaces are being created. Yet, I cannot connect from one macOS v1.4.0 to another v1.4.0 macOS. I can connect from a macOS v1.2.12 to a macOS v1.4.0, and from a macOS v1.4.0 to a Linux v1.4.0, and vice versa, just not between two macOS v1.4.0.

If there is anything you would want me to test, please let me know. I am leaving one of my macOS machines on v1.2.12 for now. I have two on v1.4.0, plus two Linux on 1.4.0.

**Comment by adamierymenko** [comment]
We just did a 1.4.0.1 point release for this:

https://download.zerotier.com/dist/ZeroTier%20One.pkg

**Comment by Fastidious** [comment]
@adamierymenko excellent turnaround on the fix, worked like a charm!
