### ISSUE TITLE
mDNS no longer working in 1.4.0

### ISSUE THREAD

**Issue by daviehh** [zerotier/ZeroTierOne#986]
**Describe the bug**
In the previous version 1.2.12, multicast-DNS used to work even across different wifi networks and I can access other machines using e.g. `foo.local`. Since the last update, mDNS no longer works.

**To Reproduce**
1. mDNS bulit-in on mac os; or, linux hosts running avahi
2. (previous version) I can e.g. ssh to `machine-name.local`
3. (this version) `machine-name.local` no longer works but ip address assigned by zerotier works fine.

**Expected behavior**
access other machines on the network using mDNS.

**Desktop (please complete the following information):**
 - OS: Linux
 - OS/Distribution Version: Linux raspberrypi 4.19.58-v7l+ #1245 SMP Fri Jul 12 17:31:45 BST 2019 armv7l GNU/Linux
 - ZeroTier Version 1.4.0
 - Hardware raspberry pi 4, macbook

**Comment by adamierymenko** [comment]
More details: does it work Linux-to-Linux? Mac-to-Mac? Mac-to-Linux? Or not at all?

**Comment by daviehh** [comment]
@adamierymenko it does not work between mac and linux, both ways (do not have more machines to test), since the 1.4.0 update. Thanks!

**Comment by adamierymenko** [comment]
This is fixed. We are going to post a 1.4.0.1 Mac version under 1.4.0 on download.

https://download.zerotier.com/dist/ZeroTier%20One.pkg

**Comment by daviehh** [comment]
wow, that's quick :-) Thanks!

**Comment by reaktivo** [comment]
I also cannot connect via .local domains, either from iOS to Mac, Mac to Linux, etc. The versions are 1.4.6 and 1.4.4

Can it be the version mismatches that are preventing the connection, and if will a 1.4.6 version be released for iOS?

**Comment by glimberg** [comment]
Multicast is not available on iOS or Android as they do not give developers permission to enable it on the network adapters they give us for use.
