### ISSUE TITLE
install script: gpg location changed?

### ISSUE THREAD

**Issue by daviehh** [zerotier/ZeroTierOne#989]
In the "Linux (DEB/RPM)" section at https://www.zerotier.com/download/, under "If you have GPG installed, a more secure option is available:", the code listed points to `https://raw.githubusercontent.com/zerotier/download.zerotier.com/master/htdocs/contact%40zerotier.com.gpg` but that file is no longer available; is it due to the `https://github.com/zerotier/download.zerotier.com` being possibly changed now to `https://github.com/zerotier/install.zerotier.com` (changed: download to install in the github repo's raw path)? Thanks!

**Comment by adamierymenko** [comment]
Oops! Will fix. Had to take DL off GitHub because it contains files that are too big.

**Comment by adamierymenko** [comment]
Fixed on web site
