### ISSUE TITLE
Packet characteristic "ipauth" reports false for addresses within 6plane

### ISSUE THREAD

**Issue by fakuivan** [zerotier/ZeroTierOne#990]
**Describe the bug**
The packet characteristic "ipauth" reports false for source addresses within the address space assigned by 6plane to that node. This means that if you choose to drop unauthorized packets, you will also be _disabling_ 6plane for any address different from the one assigned to the node itself.

**To Reproduce**
1. Create a Network with the default rule set and uncomment the ``drop not chr ipauth;`` line
2. Enable 6plane addressing
3. Add two nodes, alice and bob
4. Follow [this guide](https://zerotier.atlassian.net/wiki/spaces/SD/pages/7274520/Using+NDP+Emulated+6PLANE+Addressing+With+Docker) to configure Docker to use 6plane for all containers on bob
4. Ping alice with the command ``docker run --rm -it alpine ping "<alice's 6plane address>"``
5. Monitor traffic using ``tcpdump 'icmp6 && (ip6[40] == 128 || ip6[40] == 129)' -i "<zt network interface>"`` on both alice and bob
6. Notice that packets do leave the container and bob but do not reach alice. 

This is even more evident if you try to ping the container from alice, the packet will be received by bob, relayed to the container and vice versa, but once it leaves bob to reach alice, it will get silently dropped by zt. 

**Expected behavior**
A single node should be able to relay packets from the 6plane addressing space assigned to it, packets sent from there should be identified as authorized. 

**Screenshots**
![2019-08-02_19-35-42](https://user-images.githubusercontent.com/15100012/62405459-be4b8e80-b573-11e9-963c-92f0f5924f39.gif)

**Desktop (please complete the following information):**
 - OS: Linux, Windows
 - OS/Distribution Version: Ubuntu Server 18 LTS, Windows 10
 - ZeroTier Version: 1.2.4, 1.4
 - Hardware: Virtual Machines hosted with Hyper-V, same behaviour observed on bare metal servers hosting docker containers
 
**Smartphone (please complete the following information):**
 - Device: PC
 - OS: Linux, Windows
 - Version: 1.4.0, 1.2.12

**Additional context**
- General Network Environment: Hyper-V internal network, home LAN

**Comment by adamierymenko** [comment]
You know what... I'm not sure we have ever tried this! Technically this mechanism is redundant for 6PLANE and similar addresses as they embed the ZT address into the IP itself, emulate NDP, and therefore cannot be spoofed. But it should still work in the rules engine the way you would expect.

**Comment by adamierymenko** [comment]
Fixed in `dev`, 1.4.2 coming later today or tomorrow.

**Comment by fakuivan** [comment]
I don't see this being fixed in ``1.4.2``? Do you need me to provide more details?

**Comment by fakuivan** [comment]
It's not clear to me if [``InetAddress::isEqual``](https://github.com/zerotier/ZeroTierOne/blob/master/node/InetAddress.hpp#L397-L413) will only compare the first 80 bits to validate any ip address on the 6plane subnet.

**Comment by adamierymenko** [comment]
Hmm... will take a look.

**Comment by fakuivan** [comment]
e8ae3334433216a43ba772f5b96350a29a92190f looks promising! I'll check and report back once ``1.4.4`` comes out, thanks for all the help so far.

**Comment by fakuivan** [comment]
My testing suggests 1.4.4 did not fix the issue. I'm confident I did not explain myself correctly.

As far as I understand 6plane allows a node to route packets from ipv6 addresses in the ``fc:xored_network_id:node_id::/80`` address space, essentially delegating addresses in said space to any downstream services or subnets. What I'm proposing is for packets forwarded by the node from these addresses to be characterized as "ip authenticated" by the nodes. This would allow any one node to utilize this address space even when the ``drop not chr ipauth;`` rule is active on that network. 

A first attempt on pseudo-cpp would look something like this:
```cpp
const InetAddress trimmed_6plane(
    // Set the last bits to ::1, so that we only compare the first 80 bits 
    // no matter what address on the subnet it is
    ip.setBits(1ULL, 128-80) // off-by-one error waiting to happen, also hypothetical method
);
const InetAddress node_6plane(
    InetAddress::makeIpv66plane(nconf.networkId,
                                nconf.issuedTo.toInt())
);
if (node_6plane.isEqual(trimmed_6plane))
    return true;

// check rfc4193
```

Please, don't hesitate to ask for more info, I'm not a native speaker so it can sometimes be tricky for me to communicate correctly, I apologize if that is the case.

**Comment by servadestroya** [comment]
@adamierymenko I can confirm this has not been fixed

**Comment by fakuivan** [comment]
Would you consider reopening this issue? @adamierymenko

**Comment by KenMacD** [comment]
I just ran in to this when trying to get 6plane working with podman. Took forever to realize it was this that I've had at the start of my rules forever:

```
# Allow only IPv6 traffic from ZeroTier-assigned IP addresses
drop                      # drop cannot be overridden by capabilities
  not ethertype ipv6      # is not ipv6
  or not chr ipauth       # OR IP addresses are not authenticated (1.2.0+ only!)
;
```

Should I open a new issue for it?
