### ISSUE TITLE
Convoluted Versioning

### ISSUE THREAD

**Issue by mwarning** [zerotier/ZeroTierOne#992]
Just a wish for less convoluted version identifiers.
"1.4.0.1-2" as a tag is a bit silly. When the package version is appended, it would be "1.4.0.1-2-1".
It would be nicer if you could do with three digits. - thanks

**Comment by adamierymenko** [comment]
Yeah that was kind of a one-off... usually it's major.minor.revision.build and build has been 0 up until our point release to fix that Mac bug. BTW 1.4.2 is coming probably later on today or maybe tomorrow to fix an idle CPU use bug.
