### ISSUE TITLE
backwards compatibility to 1.2.12 peers

### ISSUE THREAD

**Issue by ort163** [zerotier/ZeroTierOne#995]
**Describe the bug**

I have few RHEL 7.x servers, windows (with VNC server installed), OSX (remote screen sharing enabled) running 1.2.12. I have not updated anything from 1.2.12 to 1.4.0 for issue [high CPU usage](https://github.com/zerotier/ZeroTierOne/issues/982)

Our user have OSX as desktops. Actually I know it does not depend what is client and server but assume that our users are remote desktoping or logging onto RHEL or VNC-to-OSX and VNC-to-windows machines via zt-ipaddresses. Worked properly.

Yesterday I upgraded  one client  OSX to 1.4.0 from [website](https://www.zerotier.com/download/). This 1.4.0 OSX can see other 1.2.12 peers . Verified in a Terminal -` zerotier-cli listpeers`

BUT
**No SSH, No remote desktop, no samba server access**. Yes I checked firewall etc. 

Downgrading to 1.2.12 OSX client packages - everything works.

Note that I am **not** using hostnames while trying to connect. We are using actually zt-ip like `ssh 10.147.17.2 `and so on.

**To Reproduce**
1.  Install 1.4.0 on OSX
2. Try to connect via SSH or VNC to 1.2.12 linux or windows peers
3. failure

**Expected behavior**
Hopefully backwards compatible.

**Desktop (please complete the following information):**
 - OS: [Mac, Linux]

 Also tried on a fresh OSX installation. Same issue.

**Comment by pkpowell** [comment]
Is this related to osx vers < 10.13? For me osx 10.13 and 10.14 are fine, but 10.12 and lower won't connect at all - ifconfig shows no entries for any zt interfaces. 
zt installs fine on these older machines and zertotier-cli seems to work, btw.

**Comment by glimberg** [comment]
@pkpowell Yeah we're working on getting a solution for macOS 10.12 and below going.  For now macOS 10.12 and below are going to be stuck on 1.2.12.

@ort163 what version of macOS are you running?

**Comment by ort163** [comment]
OSX 10.11(el Capitan). Now makes sense.
Is it possible that in future you can have a drop down menu for different OSX and allow the user to install only appropriate versions, especially when you *are aware* that such issues exist.

**Comment by glimberg** [comment]
@ort163 We weren't aware of it until after the release

1.4.2 should be coming today.

**Comment by glimberg** [comment]
1.4.2 is [now available](https://www.zerotier.com/download/)
