### ISSUE TITLE
Managed Routes

### ISSUE THREAD

**Issue by mycanaletto** [zerotier/ZeroTierOne#997]
Version 1.4 does not add managed routes to the client, which worked very well in 1.2.x

How to go back to 1.2 on a linux debian 10?

Thank you

**Comment by adamierymenko** [comment]
We updated our repositories to contain older versions, but I'm curious if this is still happening on 1.4.2 and if you can provide details.

**Comment by mycanaletto** [comment]
Yes i do, the problem is now solved on 1.4.2, merci :-)

**Comment by fghorow** [comment]
I am also having this problem. I am using the Ubuntu zerotier-one 1.4.2-2 package under Ubuntu bionic (18.04). The managed routes that used to show up under version 1.2.12 (with whatever patches Ubuntu used to distribute) are no longer appearing in my routing table even after reboots.
Workarounds would be most welcome!

**Comment by CkNoSFeRaTU** [comment]
The problem with route management code for linux is that it is very hacky. It just trying to execute iproute2's ip twice each with one of hardcoded absolute paths to binary and hope it will work eventually without checking anything. If user doesn't have iproute installed or for example like in case of Gentoo ip is located in /bin/ip then route functionality will be broken without any warnings.

From the looks of it there are already bulk of netlink code which is the right way to interact with linux networking. But it just not wired to route management. Hopefully it will be and these kludges will go away.
