### ISSUE TITLE
Suggestion: use libsodium for crypto

### ISSUE THREAD

**Issue by unquietwiki** [zerotier/ZeroTierOne#998]
Per code checks done under #965 , a good amount of the errors flagged involve crypto code from 10+ years ago. It might be worth adopting a more current version of that content.

https://github.com/jedisct1/libsodium

**Comment by adamierymenko** [comment]
We might do this, though we are very allergic to mandatory external dependencies in the ZT core. More likely that we'll update the included code in the core.

**Comment by adamierymenko** [comment]
We are allergic to dependencies in general but especially in the core.
